### ISSUE TITLE
Is there any plan to integrate ray worker with docker?

### ISSUE THREAD

**Issue by ustcfriend** [ray-project/ray#1001]
Hi, @robertnishihara 

Currently, remote python task will be executed by ray worker at host. But we can't ensure all the depended python packages ready at ray worker server. Actually, here's conflict between many python lib packages.

Is there any plan to integrate ray worker with docker? Or integrate ray worker with python virtual environment?

Thanks.

Kai

**Comment by robertnishihara** [comment]
It's already possible to run Ray inside of Docker, e.g., see https://github.com/ray-project/ray/blob/master/docker/deploy/Dockerfile.

We're currently recommending that people run one Docker container per machine (with all of the relevant Ray processes inside of that docker container). The reason is that the worker processes need to be able to share memory with one each other to take advantage of the shared memory object store.

We don't have immediate plans to run individual worker processes in separate docker containers, although I can see why that would be useful. If you're interested in trying this out, I'm happy to help brainstorm how to do that.

As for running ray inside of a virtual env, I think this should already work. That is, if if you run `ray start` inside of a virtual env or a script that does `ray.init()` inside of a virtual env, then the worker processes should be started within the same virtual env. However, I haven't tested this extensively.

**Comment by ustcfriend** [comment]
Thank you so much. We will try the python virtual environment plan.

And, I have one more question, is there any plan to do the resource isolation job in ray?

Thanks.

**Comment by robertnishihara** [comment]
I'm not quite sure I understand what you mean. Do you mean isolating different workers from one another and limiting the amount of CPU/memory/etc that each worker can use? If so, Docker might be a good way to do that, but we don't have a plan yet for this. What would you suggest?

**Comment by robertnishihara** [comment]
You're welcome! I hope it works out nicely.

**Comment by maxim28** [comment]
Hi, @robertnishihara

Is there any plan to support **group** and **priority** feature for tasks in ray cluster?

I mean even if ray can be deployed as a docker container to build a ray cluster, which must ensure that all docker images must be the same and only same kind of tasks can be executed. 

E.g.  

If i build a ray docker image A with dependency for task A,  and build another ray docker image B with different dependency for task B,  i cannot deploy and join these 2 docker container into 1 ray cluster,  because ray scheduler cannot distinguish between them and maybe schedule the task into wrong containers.

If the ray scheduler have the ability to manage group of tasks, i can build a large ray cluster for different type of tasks, every ray containers which join the cluster must provide group name with specific dependency, and ray scheduler will assign the task to proper containers with priority.

**Comment by maxim28** [comment]
Otherwise, i must build a ray cluster for one task,  and build another ray cluster for another task with different dependencies, which might not be good :(

**Comment by robertnishihara** [comment]
We currently don't have any plans to do this, though there will likely be workarounds that enable this.

E.g., if we support the ability to control scheduling with labels (see #695), then you can probably use that to do the thing you're trying to do.

Do you have an actual example where you want to run multiple python functions but they can't run in the same docker container?

**Comment by maxim28** [comment]
If multiple python functions using different dynamic libraries or python packages , i must put all these things together in one container for a ray cluster, which is unnecessary.
Further more, if multiple python functions using same libraries and packages but different versions, version control in one container also can be a problem.

**Comment by robertnishihara** [comment]
It's possible that scheduling with labels could be in 0.3 or 0.4.

Which Python libraries are you using that are difficult to install in the same docker container?

**Comment by lenassero** [comment]
> It's already possible to run Ray inside of Docker, e.g., see https://github.com/ray-project/ray/blob/master/docker/deploy/Dockerfile.
> 
> We're currently recommending that people run one Docker container per machine (with all of the relevant Ray processes inside of that docker container). The reason is that the worker processes need to be able to share memory with one each other to take advantage of the shared memory object store.
> 
> We don't have immediate plans to run individual worker processes in separate docker containers, although I can see why that would be useful. If you're interested in trying this out, I'm happy to help brainstorm how to do that.
> 
> As for running ray inside of a virtual env, I think this should already work. That is, if if you run `ray start` inside of a virtual env or a script that does `ray.init()` inside of a virtual env, then the worker processes should be started within the same virtual env. However, I haven't tested this extensively.

Hi @robertnishihara, I have some issues when using ray inside a `virtualenv`. 
Basically, I have a `remote` task that I am executing from the head node inside a `virtualenv`. It works fine on the head node, but on the worker nodes, the remote function seems to be executed using the base `python` (not the one in the `virtualenv` with all the necessary modules installed), thus causing import errors.
Do you have any ideas for fixing this ?

Thanks for your help!
