### ISSUE TITLE
[rllib] How can a trainer access total reward?

### ISSUE THREAD

**Issue by bentzinir** [ray-project/ray#10041]
### What is your question?
Can an off-policy algorithm that trains on offline samples access the total reward of the trajectories from which the samples were taken?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.9.0.dev0, Python 3.8, TF 2.3,

**Comment by ericl** [comment]
If the batches written to the files are complete trajectories, then you can probably compute the total reward (discounting as needed) easily since the entire data is there.

If the batches are trajectory fragments, you have to instead precompute the reward totals and save them as fields in the batch when building it (e.g., https://docs.ray.io/en/master/rllib-offline.html#example-converting-external-experiences-to-batch-format). This might be the easier approach in either case.
