### ISSUE TITLE
Killing program that uses Ray

### ISSUE THREAD

**Issue by Suchandan** [ray-project/ray#1005]
Whenever a program using Ray is killed from the command line via kill -9 <PID>, the worker threads it spawns aren't killed. This can be reproduced by executing the program below, via

python main.py

Is it possible to kill all worker threads instead?

As suggested by @robertnishihara , one gets different behaviour depending on how the program is killed. In particular, this issue doesn't arise if the main python process is killed with a KeyboardInterrupt. 

The corresponding issue with the ProcessPoolExecutor from the python standard library concurrent.futures is discussed here: 

https://stackoverflow.com/questions/29177490/how-do-you-kill-futures-once-they-have-started 

```python
import ray
from time import sleep

@ray.remote
def g(x):
    sleep(100)
    return x

@ray.remote
def func2():
    x = g.remote(100)
    y = g.remote(200)
    return ray.get(x) + ray.get(y)

@ray.remote
def func1():
    x = g.remote(1)
    y = g.remote(2)
    return ray.get(x) + ray.get(y)

def main():
    ray.init()
    print "Program ended: ", ray.get([func1.remote(), func2.remote()])

if __name__ == "__main__":
    print "Program started."
    main()
```

**Comment by robertnishihara** [comment]
This is a good point, it looks like we may not be handling all cases at the moment.

In your example, the **driver script** starts a **local scheduler**, and the local scheduler starts a number of **worker processes**.

If the driver exits gracefully, it will send a kill signal to the local scheduler (via `services.cleanup`), which should run the local scheduler's cleanup handler, which kills all of the workers. The relevant lines of code are

https://github.com/ray-project/ray/blob/c26c7553bcb0c181e196a0b18dc647791473fc16/python/ray/worker.py#L1365

https://github.com/ray-project/ray/blob/c26c7553bcb0c181e196a0b18dc647791473fc16/src/local_scheduler/local_scheduler.cc#L154

Now, it looks like in the situation where I send a kill signal to the driver script, the local scheduler does not die (and therefore does not clean up the workers). In this case, we want to cause the local scheduler to die when the driver exits.

Note that this should only be relevant in the case where you start ray with `ray.init()` on a single machine. In the cluster case you don't want the workers (or any of the processes) to exit when a single driver fails.

**Comment by Suchandan** [comment]
Thanks for your message @robertnishihara, and for your work on this awesome package! I'm not sure I understand why this isn't relevant in the cluster case. Could you please elaborate?

Suppose main.py executes code via Ray on a cluster, and the main program is killed because the computation is deemed unnecessary. The workers may be consuming lots of resources on an unnecessary computation - why shouldn't they exit?

**Comment by robertnishihara** [comment]
In the cluster case, what should already happen when a driver exits is the following.

1. The local scheduler that the driver was connected to detects that the driver exited.
2. That local scheduler broadcasts a message declaring that the driver exited.
3. All of the local schedulers receive the message and kill all workers that are still executing tasks related to the removed driver.

We don't want to kill **all workers** because some workers may be running tasks for other drivers.

The code for step 2 can be found at

https://github.com/ray-project/ray/blob/c26c7553bcb0c181e196a0b18dc647791473fc16/src/local_scheduler/local_scheduler.cc#L906

The code for step 3 can be found at

https://github.com/ray-project/ray/blob/c26c7553bcb0c181e196a0b18dc647791473fc16/src/local_scheduler/local_scheduler.cc#L858

**Comment by Suchandan** [comment]
Thanks for the clarification!
