### ISSUE TITLE
when head node failes，  how to keep the ray  cluster still work 

### ISSUE THREAD

**Issue by lileishitou** [ray-project/ray#10065]
is there any module such as zookeeper for ray cluster using in the high availability ;

**Comment by rkooo567** [comment]
Hi, @lileishitou. We are currently in progress to support HA for Ray. Ray's single point of failure is GCS (Redis) because they are residing in a head node. We are in progress of decoupling this piece of component from Ray clusters (so that you can use any reliable databases such as etcd as GCS backend). Supporting modules such as zookeeper for leader election should be the next step once this decoupling is completed (we cannot say exact timeline for this to be done, although supporting multiple backends for GCS will be done relatively sooner). If HA of Ray is crucial for your use cases, please create an enhancement request with your use case!

**Comment by rkooo567** [comment]
HA is achieved by one advanced user, but we need a little more work to make it generally available. Currently, that’s not the highest priority.
