### ISSUE TITLE
Allow ray.init to discover that one instance of Ray is already running

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#1025]
If I have two Python processes on the same system, and I call `ray.init()` in both of them, I get two instances of everything. It would be great if one would discover that one other already running and just connect to it.

Use case: We have a Docker image with our system which runs Ray inside and exposes a port for services to connect to it. But sometimes you also want to `docker exec` a custom script in it, connecting to Ray and spawning custom tasks. So if that script can just do `ray.init()` and find the Ray inside Docker container it would be very simple.

**Comment by robertnishihara** [comment]
The current behavior (duplicating everything) is intentional in order to provide more isolation.

A natural way to do what you want is to allow an optional `--redis-address` to be passed in to your script. If it isn't passed in, then it calls `ray.init()`. If it is passed in then it passes the redis address into `ray.init`. For example, see

https://github.com/ray-project/ray/blob/b020e6bf1fb00d0745371d8674146d4a5b75d9f0/examples/hyperopt/hyperopt_simple.py#L19-L26

To make simplify the process of figuring out the address, you could call `ray start` with flags like `--node-ip-address=127.0.0.1 --redis-port=6379`, and then you should be able to just use `--redis-address=127.0.0.1:6379`. Though that IP address will only work if you're using Ray on a single machine.

In terms of automatically discovering an existing Ray cluster. In the single machine case, we could just check if there's a redis server on port 6379. In the multi machine case we may need to integrate something like etcd for service discovery.

**Comment by mitar** [comment]
Hm, I would like to make it so that it does not matter which one I call first. Could it be something like calling `ray.init()` with IP and port, and if that is available, it starts it at that address, if not, it connects to that address?

**Comment by atumanov** [comment]
@mitar , there're two ways to do this.
1. `exec ray start --redis-port 6379` in your dockerfile, so that Ray starts when the docker container is brought up. Then, change all of your scripts running inside your docker container to `ray.init(redis_address=127.0.0.1:6379)`. This option basically assumes that the ray cluster has already been started. Pro: no Ray code changes required.
2. Minor code change in the implementation of `ray.init` to check if port 6379 is open or closed. If closed, assume it's Ray's Redis shard and continue initialization with `redis_address=127.0.0.1:6379`. If open, assume Ray hasn't been started yet. The disadvantage here is that you have to make several assumptions (e.g., that port 6379 (Redis default port) actually belongs to an instance of Ray already running. As Robert mentioned, this would also require a couple of lines of python to check the port.

I think option #1 is a better one. You control the Redis port and can change it, if you want. Fewer assumptions, no Ray code change, one extra argument passed to `ray.init` in your existing scripts, and all scripts are symmetric (all attach to an existing Ray instance).

**Comment by mitar** [comment]
Yes. I agree that 1 is better. But 2 is magical for lazy. :-) But is probably also too magical and could lead to issues.

**Comment by kirk86** [comment]
This doesn't work if you have static ip configured on your machine.
Starting ray explicitly `ray start --head --redis-port=6379 --num-workers=18` always defaults in staring it with `node-ip-adress` the actual ip address and not the localhost address `127.0.0.1`.
Even if you explicitly tell it to start with ray node-ip-address 127.0.0.1 it will still start ray with ip address my actual static ip.
`ray start --head --node-ip-address=127.0.0.1 --redis-port=6379 --num-workers=18``
