### ISSUE TITLE
[GCS]Open lightweight heartbeat by default

### ISSUE THREAD

**Issue by ffbin** [ray-project/ray#10355]

**Comment by WangTaoTheTonic** [comment]
working on it :)

**Comment by WangTaoTheTonic** [comment]
[ ] enhence robust of test cases
[ ] handle special case of resource turning empty 
[ ] handle cluster resource view in gcs node manager
[ ] add light_heartbeat_enalbed flag in python
[ ] handle resource update in monitor.py
[ ] add get all heartbeat interface and use in state.py instead of broadcast

**Comment by rkooo567** [comment]
@WangTaoTheTonic I forgot what was the progress with lightweight heartbeat. Can I close it?

**Comment by WangTaoTheTonic** [comment]
> @WangTaoTheTonic I forgot what was the progress with lightweight heartbeat. Can I close it?

Yeah we can close this! The only thing left to do is removing old code path but that needs no hurry~
