### ISSUE TITLE
[Autoscaler] Only recognizes workers it launches

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#10404]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
0.8.6+

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

* Start a ray cluster with gpu workers (non-resource demand autoscaler), head should not have gpu's.
* Manually add a node (not using autoscaler), with a custom resource {"custom": 1}

```
@ray.remote(num_gpus=1)
def gpu_task():
    pass

@ray.remote(resources={"custom":1})
def launch_gpu():
    # This blocks and never starts a gpu worker.
    ray.get(gpu_task.remote())

ray.get(launch_gpu.remote())
```

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by wuisawesome** [comment]
The root cause of this is that `StandardAutoscaler::workers()` explicitely filters
```
    def workers(self):
        return self.provider.non_terminated_nodes(
            tag_filters={TAG_RAY_NODE_KIND: NODE_KIND_WORKER})

```

**Comment by rkooo567** [comment]
@wuisawesome Can you set the priority of this task?

**Comment by PidgeyBE** [comment]
> The root cause of this is that `StandardAutoscaler::workers()` explicitely filters
> 
> ```
>     def workers(self):
>         return self.provider.non_terminated_nodes(
>             tag_filters={TAG_RAY_NODE_KIND: NODE_KIND_WORKER})
> ```

This is indeed the root cause. When this would be fixed, the autoscaler will however still try to update the manual node because the `ray-launch-config` and `ray-runtime-config` labels are not set on the manual node either.

Additionally, the script you posted looks very similar to the thing I'm trying to do, but is still a little different.
In my case the `gpu_task` task is not started from within an actor but simply from within python code that is running on the manually started worker. I don't know if that makes a difference or not...
