### ISSUE TITLE
Implement exit actor API in Java

### ISSUE THREAD

**Issue by kfstorm** [ray-project/ray#10442]
We have `ray.actor.exit_actor()` in Python. We need `Ray.exitActor()` in Java.

**Comment by kfstorm** [comment]
#7291

**Comment by chaokunyang** [comment]
Since python worker process can only have one worker, thus one actor. It make sense to make `exit_actor` as a method of `ray.actor` module. But for java worker, we can have multiple worker in one worker process, thus multiple actor in one worker process. It we add `exitActor` as a static method, we can't know which actor to exit. So I think we should add `exitActor` to `ActorHandle` for java. And to keepe api consistent between java/python, do we need to move `ray.actor.exit_actor()` as an instance mehtod of ray python actor? @kfstorm @raulchen @edoakes

**Comment by chaokunyang** [comment]
Or to ensure we can clean resource completely, multithreaded worker is not allowed for `exitActor`

**Comment by kfstorm** [comment]
@chaokunyang An actor doesn't have its own handle by default. That's why it needs to be a static method.

As for the multi-worker feature in Java worker process,

* The `Ray.exitActor()` API can only be called by the main thread of a worker or any thread that the user passed thread context via `Ray.setAsyncContext` API. So we do know which actor to exit because we know which worker is invoking the `Ray.exitActor()` API. Actually we throw an exception if a Ray API is invoked without the required thread context. https://github.com/ray-project/ray/blob/6fa0edfbef4c51c5e1762d3a56d94a020d26d9fe/java/runtime/src/main/java/io/ray/runtime/RayRuntimeProxy.java#L75-L82

* The `Ray.exitActor()` API will cause the underlying `CoreWorker` instance to shut down and the task execution loop of this instance will end. Then the thread running the `CoreWorker` instance will exit. It will not cause the whole process to exit (unless all workers in the process have exited) because we wait for all threads to exit in the `CoreWorkerProcess::RunTaskExecutionLoop`. https://github.com/ray-project/ray/blob/6fa0edfbef4c51c5e1762d3a56d94a020d26d9fe/src/ray/core_worker/core_worker.cc#L529 https://github.com/ray-project/ray/blob/6fa0edfbef4c51c5e1762d3a56d94a020d26d9fe/src/ray/core_worker/core_worker.cc#L259-L261

**Comment by kfstorm** [comment]
@chaokunyang We already implemented `Ray.exitActor()` in our internal codebase. It should be easy to paste the code into the public codebase.
