### ISSUE TITLE
Ray queue details  required 

### ISSUE THREAD

**Issue by manishagarwal23** [ray-project/ray#10644]
I am on a small head node with 6 worker node on the same linux machine . When i submit my very small program to it it works . However as soon as I submit a little bit large program all the ray workers crash .

I read on https://docs.ray.io/en/ray-0.4.0/internals-overview.html
"Once a task has been scheduled to a local scheduler, whether by itself or by a global scheduler, the local scheduler queues the task for execution. A task is assigned to a worker when enough resources become available and the object dependencies are available locally, in first-in, first-out order. "

1) So where can i see the ray job queues ?
2) What is its size and memory ?
3 ) How can i see its really working ; like to me it seems may be there is no queue ?

**Comment by rkooo567** [comment]
Ray's architecture has been changed a lot since then, and most of information you found from 4.0 might be misleading. You can instead take a look at our white paper for more details. 

https://docs.ray.io/en/master/whitepaper.html

About your question, (Note all the information I am writing here is reflecting the "lates master" branch. If you are using some older version, some details could be different).

1. There's current a no way to see the job queue states. It is a little tricky because Ray uses decentralized scheduler (and being in the first entry in the queue doesn't gurantee it will be executed).
2. It should be unlikely your applications crash because of the length of job queue. The problem should be more related to Ray objects management. You can take a look at this doc to figure out how the memory management works for Ray. 

https://docs.ray.io/en/master/memory-management.html
