### ISSUE TITLE
[ray] How to regenerate micro-benchmarks results from the ray paper ?

### ISSUE THREAD

**Issue by jindal2309** [ray-project/ray#10664]
Hi,

I would like to run some experiments to regenerate results shown in Microbenchmarks section of Ray paper (Moritz 2018) on our GPU clusters. I want to try these two experiments: End-to-end scalability and Locality-aware task placement experiment. In the first experiment, the authors increase the number of nodes and check if throughput scales linearly or not and in the second experiment, the authors compare mean task latency for locality-aware and unaware placement.

**There are not that much code level details given in the paper. Can someone share the evaluation code with me so that I can generate these results on my own GPU clusters?**

Thanks a lot for the help

**Comment by wuisawesome** [comment]
I'm not sure if those code examples still exist, but just a heads up, Ray has been rearchitected since then, so it's significantly faster and the architecture is a bit different since that paper. 

You could probably recreate a benchmark with similar results by 
1. spinning up a 100 node cluster
2. place objects on random nodes by calling `ray.put` from random nodes (this can be achieved by calling `put` in a remote task which requires the custom `node:xxx.xxx.xxx.xxx` resource).
3. run many tasks
for locality awareness, you would want to place actors on the appropriate nodes (the current scheduler does not consider data locality). 

cc @robertnishihara @pcmoritz
