### ISSUE TITLE
[tune] why some trail run more iters at a moment?

### ISSUE THREAD

**Issue by noprohuangqi** [ray-project/ray#10789]
+---------------------+----------+------------------+------------+--------+------------------+
| Trial name          | status   | loc              |         lr |   iter |   total time (s) |
|---------------------+----------+------------------+------------+--------+------------------|
| RayYolo_482d6_00000 | RUNNING  | 172.17.0.4:25969 | 0.00530472 |     28 |          2154.4  |
| RayYolo_482d6_00001 | RUNNING  | 172.17.0.4:25965 | 0.00508012 |     23 |          2074.5  |
| RayYolo_482d6_00002 | RUNNING  | 172.17.0.4:25950 | 0.00496791 |     24 |          2170.12 |
| RayYolo_482d6_00003 | RUNNING  | 172.17.0.4:25956 | 0.00449017 |     24 |          2151.4  |
+---------------------+----------+------------------+------------+--------+------------------+

When I use pbt schedules to train, sometimes I find my trails not synchronization. For example , one trail at 28 iter ,and the others is less. This situation is reasonable？

**Comment by richardliaw** [comment]
Good question; maybe check nvidia-smi or htop to see if CPU utilization is fair.

**Comment by noprohuangqi** [comment]
> Good question; maybe check nvidia-smi or htop to see if CPU utilization is fair.

Thanks for your quickly reply .
Do you mean that resource cause this situation? And what I really want to know is this situation whether to affect the normal operation of PBT .

**Comment by amogkam** [comment]
@noprohuangqi you can try running PBT with `synch=True` parameter set. This will add a synchronization barrier for all trials and makes sure perturbations only occur after all trials are at the same epoch ensuring fairness.

**Comment by amogkam** [comment]
More info here: https://docs.ray.io/en/master/tune/api_docs/schedulers.html#ray.tune.schedulers.PopulationBasedTraining

**Comment by noprohuangqi** [comment]
> More info here: https://docs.ray.io/en/master/tune/api_docs/schedulers.html#ray.tune.schedulers.PopulationBasedTraining

Thanks , seem like this is new version of PBT. My version at 0.8.6 has no keyword like synch.

**Comment by amogkam** [comment]
Right, this was added recently and is in the 0.8.7 release. It should give you what you want in terms of perturbations only occurring when all trials are at the same epoch. Otherwise the default is async and there's no guarantee that this will hold. If you plan to try out synch mode let me know how it goes/if you run into any issues!

**Comment by noprohuangqi** [comment]
> Right, this was added recently and is in the 0.8.7 release. It should give you what you want in terms of perturbations only occurring when all trials are at the same epoch. Otherwise the default is async and there's no guarantee that this will hold. If you plan to try out synch mode let me know how it goes/if you run into any issues!

Yes, I want all perturbations only occurring when all trials are at the same epoch. But I can not understand why in the async mode, different trails compare at the different epoch? Because usually larger epoch has better perfermance,this compare is not reasonable.

**Comment by amogkam** [comment]
Sorry about that, I guess it didn't make it into 0.8.7! Yes it's in the latest nightly build.

Regarding async vs sync: In async mode each trial runs independently and theres no guarantee that they will all run at the same speed. Training state for each epoch for each trial is not stored, only the current state is. So when trial A reaches a perturbation interval, it will compare against the current state of trial B, trial C, etc. regardless of what epoch B & C are at.

As you said, this isn't fully fair since trials which run faster usually will have better performance. This is the reason we implemented a synch mode so that all comparisons are fair even if trials are run at different speeds. The downside with synch mode is possibly longer training times and resources not being fully utilized at all times.

**Comment by amogkam** [comment]
@noprohuangqi were you able to try out synch mode?

**Comment by noprohuangqi** [comment]
> @noprohuangqi were you able to try out synch mode?

Yes,I update version to 1.0.0 and try `synch=True` mode , everything goes well.
THANKS.
