### ISSUE TITLE
[ray] Is there any way to create actors more quickly?

### ISSUE THREAD

**Issue by Seraphli** [ray-project/ray#11044]
In our project, we have to initialize about 2000+ actors in the cluster. The whole process takes about 20+ mins to finish. It's quite a long time. Is there any way to create actors more quickly?

**Comment by rkooo567** [comment]
1. What's the standard of "creating actors"? Is it time to create all handles or time it takes to ray.get on every actor's method?
2. Based on the stress test we performed on 100 nodes cluster (2 CPUs each), it took around 3 seconds to create 200 actors. So, 2000+ actors for 20 minutes definitely sounds like there are some bottlenecks. 

Just note that unlike normal tasks, actor creation always should pass a centralized component called the GCS server. There's a possibility the GCS server is overloaded and became extremely slower when creating actors (but I am not sure).

Maybe one thing you can try is to "batch" create actors. Since creating 200 actors (small) in our testing took only 3 seconds, there is a possibility of a performance bottleneck when actors are created a lot at once. 

Here is what I suggest you do.

1. Measure how long it takes to create 10, 50, 100, 200, 500, and 1000 actors and see how long it takes to create them.
2. If you have a similar performance for 200 actors creation (3 seconds), you can create 200 actors, ray.get on them, and repeat. This will reduce the load to the GCS server so that it is possible to create actors faster.

**Comment by Seraphli** [comment]
Yes, creating actors means creating actor handlers and making sure the actors are set up properly. I can do some tests and write feedback here. BTW, the GCS server is not overloaded.

**Comment by rkooo567** [comment]
Got it. There might be some unknown bottlenecks we haven't discovered as well (since we don't currently have this large scale tests that test more than  2000+ workers). Feedback will be really helpful to investigate them!
