### ISSUE TITLE
Fail to schedule actor even though resources are available

### ISSUE THREAD

**Issue by endremborza** [ray-project/ray#11179]
I ended up here through #6007 that linked me to #8326 that ended up being closed for being confused with other problems, so I'd like to separate the core issue here, as it didn't get fixed in 1.0

ray 1.0.0 python 3.8

### Reproduction

```
import ray

ray.init()

actor_size = 0.7

@ray.remote(num_cpus=actor_size)
class TestActor():
    def __init__(self):
        pass

actor_list = []
for i in range(int(ray.cluster_resources()["CPU"] // actor_size)):  # mine is a 4 CPU system
    actor_list.append(TestActor.remote())
```

this consistlently reproduces the output

```
The actor or task with ID ffffffffffffffff88866c7d01000000 is pending and cannot currently be scheduled. 
It requires {CPU: 0.700000} for execution and {CPU: 0.700000} for placement, but this node only has remaining 
{node:192.168.0.199: 1.000000}, 
{accelerator_type:GTX: 1.000000}, 
{CPU: 1.200000}, 
{memory: 6.933594 GiB}, 
{GPU: 1.000000}, 
{object_store_memory: 2.392578 GiB}. 
In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
```

and only schedules 4 actors even though it claims enough resources are available

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by endremborza** [comment]
same thing happens if I insert even 20 seconds sleep after each actor initiation

**Comment by rkooo567** [comment]
Can you tell us more about your setup? Are you using docker? What's the version of OS? I will try to reproduce it from my local laptop, but I'd like to know if you have any different env from me.

**Comment by rkooo567** [comment]
actually, I could just reproduce. Let me troubleshoot the issue.

**Comment by rkooo567** [comment]
Actually, I realized it was intended behavior. Imagine you have 3 GPU instances, A, B, and C, and 4 tasks that require 0.6 GPU. In this case, we will have the case where there's a task that is using 2 GPUs at the same time. For example,

task 1 uses 0.6 GPU of GPU instance A
task 2 uses 0.6 GPU of GPU instance B
task 3 uses 0.6 GPU of GPU instance C
task 4 should use 2 GPU instances at the same time. This doesn't make sense because GPU is not an interchangeable resource.

For some reason, we apply this rule to CPU instances as well (though I think it makes sense multiple CPUs are allocated to a single task, for example, imagine you have multi-threading). I think it is applied only to CPUs and GPUs.

This is the reason why you have this error. If you set the resources in a way that it won't be allocated in two instances at the same time (for example, 0.5 or 0.25 or 0.33), this can be scheduled properly.

I think we should document this behavior better & improve the warning messages. I will create another issue to report this.

**Comment by endremborza** [comment]
Thanks for the quick reply!

I thought CPU can be thought of as divisible, like in k8s, but it makes sense if ray can't apply fractional cpu restrictions.

**Comment by rkooo567** [comment]
Yep! We actually already have an open issue to make this divisible. (I also agree with you this can definitely be divisible). The thing is we are currently re-developing a new version of the scheduler, and that will solve the issue. So, instead of fixing the old scheduler, we will wait until the new scheduler development is done (it will be done within a couple months).

Thanks again for the report :)!

**Comment by stefanbschneider** [comment]
I have the same error message with ray RLlib 1.0 on a freshly install Ubuntu 20.04 VM. It has 22 cores, but still I can't start my RLlib script:

```
Memory usage on this node: 1.6/125.9 GiB
Using FIFO scheduling algorithm.
Resources requested: 2/22 CPUs, 0/0 GPUs, 0.0/78.37 GiB heap, 0.0/25.93 GiB objects
Result logdir: /home/stefan/deep-rl-mobility-management/results/PPO
Number of trials: 1 (1 RUNNING)
+-------------------------------------+----------+-------+
| Trial name                          | status   | loc   |
|-------------------------------------+----------+-------|
| PPO_MultiAgentMobileEnv_28f12_00000 | RUNNING  |       |
+-------------------------------------+----------+-------+


2020-10-08 14:17:06,338 WARNING worker.py:1134 -- The actor or task with ID ffffffffffffffff45b95b1c0100 is pending and cannot currently be scheduled. It requires {CPU: 1.000000} for execution and {CPU: 1.000000} for placement, but this node only has remaining {node:131.234.28.107: 1.000000}, {CPU: 22.000000}, {memory: 78.369141 GiB}, {object_store_memory: 25.927734 GiB}. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
2020-10-08 14:17:06,571 INFO (unknown file):0 -- gc.collect() freed 25 refs in 0.13523793300009856 seconds
```

I have the same script running on other, physical machines with Ray 1.0. Could this be a problem with VMs?
