### ISSUE TITLE
[tune] Which should be called first: tune.report OR tune.checkpoint_dir?

### ISSUE THREAD

**Issue by ag-tcm** [ray-project/ray#11240]
Using the function API for tune, the docs show an [example](https://docs.ray.io/en/latest/_modules/ray/tune/session.html#checkpoint_dir) where `tune.checkpoint_dir` is used to save the state in a checkpoint before calling `tune.report`:

```
...
         for iter in range(start, 10):
                time.sleep(1)

                with tune.checkpoint_dir(step=iter) as checkpoint_dir:
                    path = os.path.join(checkpoint_dir, "checkpoint")
                    with open(path, "w") as f:
                        f.write(json.dumps({"step": start}))

                tune.report(hello="world", ray="tune")
...
```

Assume that the actor running a trial dies in between these two calls. Then, you restart the tuning with `resume=True`. The trial will continue with the reporting of an iteration skipped.

Alternatively, if `tune.report` is called and the actor dies before `tune.checkpoint_dir` runs, on resume the trial continues using a state that is out of date by one training iteration.

What is the rationale for saving a checkpoint before reporting the results for an iteration as opposed to the other order?

**Comment by richardliaw** [comment]
Hey, thanks for the thorough investigation @ag-tcm !

`tune.checkpoint_dir` should be called before `tune.report`, as you noticed. The reason is because we want checkpoints to be correlated with the result (i.e., we want to be able to retrieve the *best* checkpoint, etc). Many algorithms depend on this behavior too. 

However, calling checkpoint after report could introduce inconsistencies, as you've noted (state that is out of date).

Do you have any suggestions as to how we can improve here?

**Comment by ag-tcm** [comment]
Thanks for the quick and thorough response @richardliaw . Makes sense. Only thing I might suggest is perhaps an entry in the FAQ of the docs mentioning the preference of the order between report and checkpoint and a short explanation as to why.
