### ISSUE TITLE
[tune] bohb does not support `tune.sample_from`

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#11341]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* d1579819e95fa6080e46a39a22913fe0e4447b1a

### Reproduction (REQUIRED)
In tune [bohb_example.py:53](https://github.com/ray-project/ray/blob/d1579819e95fa6080e46a39a22913fe0e4447b1a/python/ray/tune/examples/bohb_example.py#L53), replace `"activation": tune.choice(["relu", "tanh"])` with:
```python
        "activation": tune.sample_from(lambda config: (
            'relu' if config['width'] < 10 else 'tanh'
        ))
```

The script then fails with:
```
ValueError: TuneBOHB does not support parameters of type `Function` with samplers of type `NoneType`
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by krfricke** [comment]
This is also a follow-up to https://github.com/ray-project/ray/issues/11216#issuecomment-710553677 and replaces #11469.

**Comment by krfricke** [comment]
I've finally looked into this. The problem here is that ConfigSpace does not allow nested search space natively. We could build workarounds to support this, e.g. sampling a categorical index and set the respective config parameter in dependence of that. However, this seems like a lot of overhead to maintain. Instead, it would be probably best to track progress of https://github.com/microsoft/nni/issues/1239 and add support if this gets implemented upstream.
