### ISSUE TITLE
RaceCondition problem in gcs_actor_manager_test

### ISSUE THREAD

**Issue by clay4444** [ray-project/ray#11432]
### What is the problem?
there are some RaceCondition problem in ut gcs_actor_manager_test (maybe more than one, I'm not sure).
for example in TestBasic ut:
`finished_actors` is update in io_service_  (in gcs_table_storage_), but get in main thread.

### solution
all event in io_service is executed in order, so I think we can also wait container result in io_service, like `WaitActorCreated() method`. 

cc @ffbin

**Comment by rkooo567** [comment]
@ffbin @clay4444 This issue literally happens more than 5~6 times if I remember correctly. It is probably better finding a way to make it single threaded instead of using multi threading in the test. One idea is completely mocking out gcs_table_storage to be synchronous. Let's discuss what's the best solution here.

**Comment by clay4444** [comment]
hi, @rkooo567 ,     @ffbin has already update the issue, the pr link is [Fix GcsActorManagerTest multithreading bug](https://github.com/ray-project/ray/pull/11361/files), but there maybe some remaining RaceCondition problem (like this pr described).

I think there is no need to mock another gcs_table_storage, because gcs_table_storage is already use the memory store as it's store client, I think the memory store client is just for user local test and ut.

**Comment by rkooo567** [comment]
The root cause of so many race condition is that we are using multiple threads in our test that is unnecessary. We are using multi-thread because we need to have an io service that is used for gcs_table_storage. I think instead of fixing tons of race condition from our tests that are not maintainable, I hope to have a better solution (like making a unit test completely single-threaded).

**Comment by clay4444** [comment]
yes, that's right, the root cause is io_service from gcs_table_storage, so I think there are two solution to solve this:

1. mock a single-threaded gcs_table_storage, It's advantage is we don't have to worry about any of a race condition problem, but ti will mock another memory store client which very similer to the current  memory store client (just single-threaded ) 

2. add a root assert method, It will handle all the assert of containers that involve in multi-threaded (post it to the same io_service and wait it done), but it still require us to consider the problem of race condition...

I was originally prefer solution 2, but when I write this comment down, I think the solution 1 maybe more better, after all, for the ut, on the premise that the logic is correct, stability is more importent....

**Comment by clay4444** [comment]
so, I will try solution 1 to solve this, is there any other questions? @rkooo567

**Comment by rkooo567** [comment]
Nope. I will be super happy if we succeed to make 1 work! our actual. code is anyway single threaded, and we'll be free of race condition in gcs_actor_manager test and gcs_placement_Group test. The only drawback is that we cannot test race condition in UT, but I can live with that (it is anyway better than breaking our unit test every other day due to race conditoin.)

**Comment by clay4444** [comment]
yes!

**Comment by ffbin** [comment]
@rkooo567 @clay4444 If it is forced to change to single thread, the execution order of the function will be modified, for example: order before modification is FunctionA  -> Callback, order after modification is FunctionA part1  -> Callback ->  FunctionA part2.

**Comment by ffbin** [comment]
Another solution is similar to GCS client, which calls functions through RPC.

**Comment by rkooo567** [comment]
Hmm I see... Do we have many tests that requires Function A - > Function B -> Callback scenario?

**Comment by ffbin** [comment]
This is mainly because it is different from the normal function execution process, so the significance of UT will become smaller.

**Comment by rkooo567** [comment]
Stale
