### ISSUE TITLE
Enable object store to spill to disk when memory fills up.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1157]
Currently, when an object store fills up, it starts evicting objects in a least-recently-used manner.

**Some question:**
- Should we store objects on disk when we evict them?
- What should we do when the disk fills up?
- How much disk space should it be allowed to use?
- Should we expose a separate API for persisting objects to disk (e.g., `ray.persist`).

**Comment by salsasepp** [comment]
Comment from a user who is unaware of the inner workings of the object store:

In my application, I distribute an object (a few MB of data) to a bunch of workers that crunch away at it. After they're done, they return their results and the object is never needed again. I'd be happy to explicitly declare the object as obsolete from within my driver, so the object store could discard it as it sees fit.

Also, I have an actor with several "worker" methods. Some of these methods never change the state of their actor instance, so any objects that were used by these methods would not need to be stored to recreate the actor in case that becomes necessary. I don't know if it might be beneficial to be able to specify that on a per-method or per-object basis.

I certainly have insufficient understanding to provide a meaningful comment to this, it just seems to me that my specific use case would not require evicting to disk.

If memory fills up from not-yet-obsolete objects, would disk space be sufficient in the long run?

**Comment by devin-petersohn** [comment]
Would it be possible to pin something to memory?

For our use-case, least-frequently-used (LFU) may be more effective. Would it be possible to use a similar approach as the Adaptive Replacement Cache (ARC) ([link](http://ieeexplore.ieee.org/abstract/document/1297303/))?

The goal for persisting objects to disk is to prevent having to recreate expensive objects, the assumption being that it is significantly faster to load from disk than it would be to recreate the object. I would be interested to know how Ray would behave in the following scenario:

1.) Load text file from disk, each character in the file is its own remote object.
2.) Memory fills up and objects start getting evicted.
3.) We access an evicted object

Would Ray scan through the file until it reached the correct character? Is the offset of the file for the character stored in the reproduction stack?

We may also have remote objects that were built based on other remote objects, so the cost of recreation/load will be compounded. Would it be possible to choose between evict and persist based on the complexity of recreation or based on whether an evicted object depends on the current object?

**Comment by robertnishihara** [comment]
@salsasepp Right, I think in your use case we do not want to evict to disk, so that should probably be an opt-in feature. As for your "stateless" actors, it probably does make sense to provide some ability to optimize that use case later on (e.g., by declaring that the entire actor is "stateless" or that certain methods are "read-only" or by providing more customizability of the reconstruction behavior). We'll need to give this more thought.

@devin-petersohn So this automatically happens for objects that are backed by object store memory (this is true for numpy arrays and objects that contain numpy arrays). For example.

```python
x_id = ray.put(np.zeros(10))
x = ray.get(x)
```

As long as `x` is in scope, then the corresponding object in the object store will not be evicted.

As for changing the eviction policy, we would ultimately like to factor that out nicely as something that can be changed easily. It's implemented in https://github.com/apache/arrow/blob/master/cpp/src/plasma/eviction_policy.h.

To answer your question about loading from files, I'm not sure what the best implementation is, but we may want to evict to disk in a way that allows us to have random access without scanning. But all of this is somewhat hypothetical at the moment. We're interested in feedback on the best practice here.

Choosing between evicting/persisting based on cost of recreation is something that in principle should be doable and we don't want to rule it out, but it also sounds pretty complicated, so for now I'd prefer to stick with simple heuristics.

**Comment by barrachri** [comment]
Should we store objects on disk when we evict them?
> What should we do when the disk fills up?
 * a simple FIFO system?  
> How much disk space should it be allowed to use?
 * set by the user, otherwise no more than x, where x can be 50% of the free disk available when you start ray (for example)
> Should we expose a separate API for persisting objects to disk (e.g., ray.persist).
* It seems [Spark](https://jaceklaskowski.gitbooks.io/mastering-apache-spark/spark-rdd-caching.html) has something similar

Shouldn't be easy to move from arrow (memory) to parquet (disk) ?

**Comment by pcmoritz** [comment]
I agree implementing a custom eviction policy is the way to go here and FIFO on disk seems reasonable as a first pass.

Also writing things to disk with parquet should be simple yeah.

**Comment by ericl** [comment]
Here's one use case for spilling to disk (checkpoints can get quite large, and you don't want to lose them on evict): https://github.com/ray-project/ray/pull/1212

**Comment by ben-manes** [comment]
I have a fairly rich [cache simulator](https://github.com/ben-manes/caffeine/wiki/Simulator) which focuses on the hit rate curve. In [traces](https://github.com/ben-manes/caffeine/wiki/Efficiency) ARC's performance varies but generally stays close to LRU. You might want to run your own traces to see how your cache might perform using different algorithms.

I would recommend using TinyLFU + FIFO for disk, perhaps with LRU in memory. The reason being that LRU handles sparse bursts very well, like @salsasepp case of workers crunching an item and then never using it again. It does poorly when the cache is polluted by one-hit wonders, e.g. a table scan, so frequency keeps the most valuable items that are otherwise flushed out. Due to disk, you also want to avoid I/O churn and for writes and only retain the frequently used entries (since in-memory absorbed all the recency).

TinyLFU is an admission policy that rejects new items if they have a lower estimated frequency than the eviction policy's victim. It uses a popularity sketch, e.g. CountMin, making it very compact. You could keep the sketch in memory, filter out most of the noisy writes, and have nice sequential I/O due to FIFO. Most likely this would give you better performance and be simpler than the alternatives like ARC or ClockPro.

**Comment by robertnishihara** [comment]
@ben-manes thanks for the tips! The eviction policy is defined in a separate class in https://github.com/apache/arrow/blob/master/cpp/src/plasma/eviction_policy.cc. So it should be possible to experiment with different policies and see what works best. There's definitely a lot of room for improvement here (e.g., making things more scan resistant).

**Comment by rkooo567** [comment]
Will be implemented by object spilling
