### ISSUE TITLE
Can Ray support TensorRT ？

### ISSUE THREAD

**Issue by ppdollhhh** [ray-project/ray#11611]
Can Ray support TensorRT ， please give me a quickstart？ How to select designated GPU？

**Comment by simon-mo** [comment]
Hi @ppdollhhh, can you tell us a little more about how are you using TensorRT? Are you using their Python API? Are you using it for serving or batch inference? Thanks!

**Comment by ppdollhhh** [comment]
I use Python API TensorRT do image inference(input single or batch)，such as detect，classification,  extract feature and so on.Now I have used celery to do these work，which connect to flask gunicorn.
Now I want estimate ray to replace celery.
thx

**Comment by simon-mo** [comment]
Because Ray support arbitrary Python code, you can just call the TensorRT code. To select designated GPU, you can either manually mask the `CUDA_VISIBLE_DEVICES` environment variable or assign `num_gpus=1` for Ray to allocate and assign it for you.

If you are looking to replace flask, checkout [Ray Serve](https://docs.ray.io/en/latest/serve/index.html#rayserve)! You can create flask like endpoint that runs on GPU and can easily scale out like celery.
