### ISSUE TITLE
[tune] HyperBand doesn't reach max_t

### ISSUE THREAD

**Issue by nadav-jac** [ray-project/ray#11695]
Hi all.

When using HyperBand, except from the first bracket, no trial is reached to max_t steps. This it due to the next line in the successive_halving() method:

> `self._r = int(min(self._r, self._max_t_attr - self._cumul_r))`

that sets the last milestone in a bracket to (max_t - (max_t/reduction_factor)).

I would love to understand what is the purpose of this feature. In my point of view, it stops the trials before they reached full training as defined by the user. In addition, it almost always causes that the best trial is one of the trials in the first bracket, because trials in this bracket are training for more steps.

**Comment by krfricke** [comment]
Hi @nadav-jac, I believe this is just following the algorithm in the hyperband/asha paper. The idea here is that if you set a maximum training time, you don't want a trial that starts late to stretch out the experiment. As you correctly observed, the best trials are often found in the first bracket because they have more training iterations. This is especially true the more we proceed in time, and it gets much harder for new trials to be better than these initial trials.

Thus, if a new trial is started very late, we have a couple of options: 

1. Train this trial for a number of timesteps. All existing trials will continue to train, too. It is very hard for the new trial to reach the performance of the existing trials. Also, we need a global stop condition anyway.
2. Train this trial, but stop other long-training trials so that we get a more fair comparison. This is not great, because we might waste resources if we don't train more trials in parallel.
3. Exit the trial when a global timestep budget is reached (as is the implementation now)

You are correct that this is sub-optimal, and there are actually papers trying to tackle this problem (e.g. [HyperSched](https://arxiv.org/abs/2001.02338)).

I'll close this issue for now, but if you'd like to discuss this further, please feel free to head to https://discuss.ray.io/
