### ISSUE TITLE
[RLlib] TrajectoryView positive shifts doesn't work

### ISSUE THREAD

**Issue by raphaelavalos** [ray-project/ray#11974]
Hello,
I am trying to access the next action during training. I updated the requirement with 
```
"next_actions": ViewRequirement( SampleBatch.ACTIONS, shift=1, used_for_training=True)
```
However it doesn't work because, when building the batch, data gets an empty list (see line 141)

https://github.com/ray-project/ray/blob/ad639f12d85297690b1190837e55ee47ce554e60/rllib/evaluation/collectors/simple_list_collector.py#L127-L144

I think that line 141 should be changed to 
```
data = np_data[data_col][self.shift_before + shift:] + padding
```
@sven1977 could you take a look ?
Thanks !

**Comment by sven1977** [comment]
Hey @raphaelavalos , thanks for filing this issue!
Great stuff that users are already trying to do cool (and completely unexpected :D ) things with the API. Taking a look right now. ...

**Comment by sven1977** [comment]
And yes, this should actually work, as it does well for `next_obs`.

**Comment by sven1977** [comment]
Adding this to the SimpleListCollector (_AgentCollector::build) actually fixes the issue. I'll get a PR ready.
The reason this issue is not happening for next_obs is that observations are already stored one ts behind everything else due to them starting with an initial obs, where all other columns (and the next-obs) are then added after that per ts. So there is always one more obs than everything else in the buffers and we shift by -1 for the obs-batch generation.

```
            # Shift is positive: We still need to 0-pad at the end here.
            elif shift > 0:
                data = to_float_np_array(
                    self.buffers[data_col][self.shift_before + shift:] +
                    [np.zeros(shape=view_req.space.shape,
                              dtype=view_req.space.dtype) for _ in
                     range(shift)]
                )
```

**Comment by sven1977** [comment]
PR: https://github.com/ray-project/ray/pull/12407

There is also a new test case in rllib/evaluation/tests/test_trajectory_view_api.py::test_traj_view_next_action, which is working now.

**Comment by raphaelavalos** [comment]
Thank you @sven1977 !
