### ISSUE TITLE
[Core] Zero Copy Read not working for PyTorch Tensor

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#12317]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

@wuisawesome found this bug:
```python
import torch
import ray
import psutil
import numpy as np

ray.init()
def mem():
    return psutil.Process().memory_full_info().rss

def test(arr):
    ref = ray.put(arr)
    start = mem()

    one_get = [ray.get(ref)]
    delta_1 = mem()

    ten_get = [ray.get(ref) for _ in range(10)]
    delta_2 = mem()

    print(f"memory growth for: {type(arr)}, 1x get {delta_1}, 10x get {delta_2}")


pt_arr = torch.zeros(128,3,224,224)
np_arr = np.zeros((128,3,224,224))

test(pt_arr)
test(np_arr)
```

Output:
```
$  /tmp python mem.py
File descriptor limit 256 is too low for production servers and may result in connection errors. At least 8192 is recommended. --- Fix with 'ulimit -n 8192'
2020-11-23 15:33:49,801	INFO services.py:1173 -- View the Ray dashboard at http://127.0.0.1:8265
memory growth for: <class 'torch.Tensor'>, 1x get 426221568, 10x get 1196986368
memory growth for: <class 'numpy.ndarray'>, 1x get 1505411072, 10x get 1505435648
```
Basically you can see that np array incurs little memory growth but pytorch tensor got deserialized each time.

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
@suquark thoughts on making PyTorch and Tensorflow Tensor zero-copy read by default (without user doing anything)

**Comment by suquark** [comment]
we can setup an internal serializer for pytorch (as pyarrow did before)

**Comment by robertnishihara** [comment]
This could just be a consequence of numpy arrays previously not being 64-byte aligned. @suquark do we know if this issue is present in the master branch?

Also, I'd suggest checking whether it's zero copy or not by checking the address of the underlying numpy array as well as timing the calls for very large arrays.

**Comment by wuisawesome** [comment]
I can confirm that the issue appears on master (as of a few days ago), after #11888. I can also confirm that the timing isn't just noise. We tested this in a batch inference job, where switching from pytorch tensors to numpy arrays led to a 4-5x improvement in overall throughput over 20+GB of data (~100KB chunks).

**Comment by robertnishihara** [comment]
@suquark if we do a custom serializer, note that there are a bunch of "gotchas". E.g., https://github.com/ray-project/ray/issues/4855. Could we make sure that that issue gets fixed here as well? It's probably already fixed, but we shouldn't regress and should test it.

It'd be good to understand the underlying issue. I would expect this to already do the right thing without a custom serializer, since I would expect it to go through numpy...

**Comment by suquark** [comment]
I'll reopen this issue, since https://github.com/ray-project/ray/pull/12478 causes windows CI failures unexpectedly, and I don't know what could be the cause.
