### ISSUE TITLE
[autoscaler] Support for container images with custom HOME directory in k8s operator

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#12408]
### Describe your feature request

We currently hardcode the `~` expansion to `/home/ray` ([code](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/_private/constants.py#L50)), which breaks paths with a tilde in containers that have a different `HOME` directory.

A few options here:
- Don't manually expand the tilde ourselves and let bash handle it. I assume there's a reason why we're not doing this already -- @ijrsvt or @ericl do you know?
- Allow users to specify RAY_HOME via an environment variable.
- Explicitly mark it in the docs that we don't support container images that are not built from an official Ray base image.

**Comment by edoakes** [comment]
Note that this is only used in the k8s operator

**Comment by ijrsvt** [comment]
@edoakes Does k8s handle `~` better than Docker? Docker tends to error if `~` is used. The reason is that there is a potential for bash expansion to happen _before_ entering the container.

Would manually checking the `$HOME` dir [(like here)](https://github.com/ray-project/ray/blob/09d5413f70f4c8c952ab979d7f11a8c0168b1fed/python/ray/autoscaler/_private/command_runner.py#L676) be sufficient?
