### ISSUE TITLE
[Placement Group] Support resizing

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#12562]
### Describe your feature request

Currently, the placement group only supports the static size bundles. But there were some requirements to support resizing (e.g., Serve wants to resize it when there are more nodes added to the cluster).

**Comment by rkooo567** [comment]
cc @edoakes 

The implementation details;
- If resize up => just schedule additional partial bundles.
- If resize down => Send RPCs to nodes that contain the bundles and remove all bundles that are not used by tasks/actors. 
    - If original - removed_bundles < new_size: reschedule bundles to match up the new size
    - else: Other returns fail or queue up the removal request.

**Comment by amogkam** [comment]
This is an awesome feature @rkooo567! It would be very useful for xgboost_ray in order to support placement groups with elastic training. In our case, we have a bunch of training actors each represented by a bundle and using a PACK strategy. But if some of the actors die, we want to continue training with the remaining actors that are still alive. In that case it seems like we would either have to resize the existing placement group or create a new one with the new size and somehow move over the existing actors to this new placement group.

And thanks for adding the implementation details. I'm curious about what the API would look like. Would there be an option to specify how large to resize the placement group to? Also is there an estimated timetable for implementing this? Also let me know if I'm misunderstanding how placement groups work or if it's currently possible to handle our elastic training use case without resizing.

**Comment by edoakes** [comment]
This sounds pretty similar to the use case for Serve. The tricky part of the API will be sizing the bundle down. @rkooo567 maybe you can propose an API here for all of us to agree on?

**Comment by rkooo567** [comment]
I will create a API proposal after coming back from the vacation!

**Comment by clay4444** [comment]
hi, we have made an API proposal for this, https://docs.google.com/document/d/1OHO0XkwMBFHXGiCrz45FfBjCGTIARs0OfFHQmIs2LAY/edit#   maybe you can take a look firstly,  thanks~

**Comment by clay4444** [comment]
cc @ffbin

**Comment by edoakes** [comment]
@clay4444 I left some comments in the doc but at a high level it looks reasonable. Are you planning to implement this soon if the API proposal is approved?

**Comment by rkooo567** [comment]
It is a duplicate

**Comment by amogkam** [comment]
@rkooo567 what's the link to the duplicate issue?

**Comment by rkooo567** [comment]
Here you go! https://github.com/ray-project/ray/issues/16403. There's a PR out, but we are deferring to merge them a bit until stability is good enough. Are you waiting for this feature now? cc @scv119

**Comment by amogkam** [comment]
It's not urgent, but would be useful to for elastic training if it's stable enough!
