### ISSUE TITLE
[dashboard] Can not see objs in 'Memory'

### ISSUE THREAD

**Issue by DonYum** [ray-project/ray#12743]
### What is the problem?

ray version: 1.0.1.post1
python version: 3.6.5
OS: CentOS 7

### Reproduction (REQUIRED)

Ray cluster: 1 head, 3 worker

push some objs and submit some actors.

And you Can not see objs in 'Memory'.

`Code`:
![image](https://user-images.githubusercontent.com/1471864/101740329-a428a580-3b03-11eb-833a-bedaf2a7b398.png)

`ray memory` results:
![image](https://user-images.githubusercontent.com/1471864/101740364-aee33a80-3b03-11eb-97a8-26bbd14b241c.png)

`dashboard view`:
![image](https://user-images.githubusercontent.com/1471864/101740461-d0442680-3b03-11eb-916d-9e93192e1791.png)

![image](https://user-images.githubusercontent.com/1471864/101740503-de924280-3b03-11eb-8420-d54d532f6348.png)

BRs!

**Comment by rkooo567** [comment]
cc @mfitton

**Comment by mfitton** [comment]
@DonYum This is actually the intended behavior at this point. In the case of these counter objects, the only thing stored in the object store is an "Actor Handle" a reference to the actor itself. The counter's inner variables are not kept in the object store. 

There was a user request a while ago to remove "Actor Handles" from the memory view dashboard because they're tiny objects and were cluttering up the view when users were looking for more substantial things occupying space in memory.

This is currently the intended behavior, but I'm willing to have a discussion around whether it should continue to be. @ericl your input would be useful here too.

**Comment by ericl** [comment]
Ah I misunderstood, I thought the issue was that the "Memory" UI wasn't showing the same thing as "ray memory".

**Comment by DonYum** [comment]
@mfitton @ericl  I'm sorry that my expression was misinterpreted.
My problem is just as @ericl understands it: `the "Memory" UI wasn't showing the same thing as "ray memory"`.
Is this a bug?
Thx you all a lot.
