### ISSUE TITLE
[Core] `--port` doesn't work very well

### ISSUE THREAD

**Issue by DonYum** [ray-project/ray#13085]
ray version: 1.0.1.post1/1.1.0
Python 3.8.3
CentOS 7

I use `--port=8380` to specify redis port, it always use 6379 again:

![image](https://user-images.githubusercontent.com/1471864/103145513-14c3f900-4777-11eb-89b2-e648c4628442.png)

Unless I use `--redis-shard-ports=xxx,xxx,xxx` to  specify redis shard ports.

In this case, if the automatic port allocation mechanism is used, should the port be fetched from infrequently used.

**Comment by rkooo567** [comment]
Hmm this seems bad. Can you tell me the command that I can reproduce it?

**Comment by DonYum** [comment]
@rkooo567 

- Make sure ray stop: `ray stop`
- Check ports: `netstat -tlnp | grep -E "6379|6380"`
- Start Ray: `ray start --head --port=6380`
- Check ports: `netstat -tlnp | grep -E "6379|6380"`
![image](https://user-images.githubusercontent.com/1471864/103148282-f2db6e00-4798-11eb-934f-1fbb300eab8b.png)

- Check process: `ps -aux | grep redis`

**Comment by rkooo567** [comment]
Will take a look at it soon.

**Comment by clarkzinzow** [comment]
If the user doesn't specify [`--redis-shard-ports`](https://github.com/ray-project/ray/blob/7166949194365593bb38813843d8a8ab6be38e06/python/ray/scripts/scripts.py#L241-L246), the Redis starter routine will [fallback to `None` for each port](https://github.com/ray-project/ray/blob/7166949194365593bb38813843d8a8ab6be38e06/python/ray/_private/services.py#L817-L818), and when [starting the Redis instance for a shard](https://github.com/ray-project/ray/blob/7166949194365593bb38813843d8a8ab6be38e06/python/ray/_private/services.py#L874-L883), [it will fall back](https://github.com/ray-project/ray/blob/7166949194365593bb38813843d8a8ab6be38e06/python/ray/_private/services.py#L943-L948) to the [default primary Redis shard port, 6379](https://github.com/ray-project/ray/blob/master/python/ray/ray_constants.py#L37-L39).

Would it be less confusing to users if the first fallback port for shards started in a different range?

**Comment by rkooo567** [comment]
@clarkzinzow Yeah that makes sense. Would you mind taking the issue?

**Comment by clarkzinzow** [comment]
Sure, can do!

**Comment by schwab** [comment]
I'm adding this information because it seems related.  If you start ray with custom port  like this....
```
 ray start  --head --num-cpus=16 --num-gpus=1 --port 6385
Local node IP: 192.168.1.175
2021-01-15 22:00:38,463 INFO services.py:1171 -- View the Ray dashboard at http://localhost:8265

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='192.168.1.175:6385' --redis-password='5241590000000000'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')
  
  If connection fails, check your firewall settings and network configuration.
```
It runs correctly on that port, horay stop
Could not terminate `"redis-server *:6379" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""` due to psutil.AccessDenied (pid=23864, name='redis-server')
Could not terminate `"redis-server *:6379" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""` due to psutil.AccessDenied (pid=24283, name='redis-server')
Could not terminate `"redis-server *:6379" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""` due to psutil.AccessDenied (pid=3255295, name='redis-server')
Stopped only 15 out of 19 Ray processes. Set `-v` to see more details.
Try running the command again, or use `--force`.wever if you do a ray stop, then it tries to kill  the redis default port....

```

It does kill the instance it started, but the message is quite confusing.
