### ISSUE TITLE
Include compiled extension binaries into windows wheel

### ISSUE THREAD

**Issue by nirvana-msu** [ray-project/ray#13293]
At the moment, when installing Ray on Windows, despite there being a wheel, it requires compiler to be installed. This is well documented in the [Windows Dependencies](https://docs.ray.io/en/master/installation.html#windows-dependencies) section.

One of the main benefits of the wheel format however, is to distribute pre-built binaries - so that users would be able to install packages without compiler present. We could as well just install from source if we had compiler setup.. but the problem is that in certain Corporate environments it's just not feasible for most Windows users to have the compiler installed.

My question is - is it possible to compile the necessary extension(s) as part of the build and include them in the wheel - so that Windows users without C++ compiler could use ray (with `pip install`)?

Thanks!

**Comment by nirvana-msu** [comment]
Ok upon further checking I can see that `_raylet.pyd` is actually there, but the fact that it fails during import means it's missing some linked DLLs. I understand that packing self-sufficient `.pyd` on Windows is not as easy as e.g. on Linux (where we have auditwheel) but quick googling shows some promising leads:

[Delocate/auditwheel, but for Windows?`](https://discuss.python.org/t/delocate-auditwheel-but-for-windows/2589/11)

Towards the end of that discussion you can see two projects that attempt to re-link `.pyd` and its dependencies:
 * https://github.com/vinayak-mehta/pdftopng/blob/6e4a9d589228f66dfbb6f0197740b0b7c1bef9b3/scripts/wheel_repair.py
 * https://github.com/adang1345/delvewheel

It would be really great if you tried to incorporate one of these approaches into your build process and produce self-contained binaries.

Thanks!

**Comment by nirvana-msu** [comment]
So I've tried patching 3.8 wheel with [delvewheel](https://github.com/adang1345/delvewheel) and it works almost like a charm!

```bash
$ ./venv/Scripts/delvewheel show ray-1.1.0-cp38-cp38-win_amd64.whl
Analyzing ray-1.1.0-cp38-cp38-win_amd64.whl

The following dependent DLLs will be copied into the wheel.
    concrt140.dll (C:\Windows\system32\concrt140.dll)
    msvcp140.dll (C:\Windows\system32\msvcp140.dll)
    vcruntime140.dll (C:\Windows\system32\vcruntime140.dll)
    vcruntime140_1.dll (C:\Windows\system32\vcruntime140_1.dll)

The following dependent DLLs will not be copied into the wheel.
    advapi32.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    dbghelp.dll
    iphlpapi.dll
    kernel32.dll
    pdh.dll
    powrprof.dll
    psapi.dll
    python38.dll
    shell32.dll
    shlwapi.dll
    ws2_32.dll




$ ./venv/Scripts/delvewheel repair ray-1.1.0-cp38-cp38-win_amd64.whl
repairing ray-1.1.0-cp38-cp38-win_amd64.whl
finding DLL dependencies
copying DLLs into ray.libs
mangling DLL names
calculating DLL load order
updating ray-1.1.0.dist-info\RECORD
repackaging wheel
fixed wheel written to D:\dev\ray\wheelhouse\ray-1.1.0-cp38-cp38-win_amd64.whl
```

The only [issue](https://github.com/adang1345/delvewheel/issues/6) I've encountered is that it failed to patch `__init__.py` (to load DLLs on module import). After loading the DLL dir myself, `ray` appears to work perfectly fine (installed on a machine without compiler, obviously):

```py
import os
import sysconfig
from pathlib import Path

os.add_dll_directory(Path(sysconfig.get_paths()["purelib"]) / 'ray.libs')  # add_dll_directory is for Python 3.8+

import ray
ray.init()
```

Please consider vendorizing the DLLs into your wheels! It only increases wheel size by <3% (14.5 MB to 14.9 MB in my case) but it removes a massive dependency and installation hurdle for Windows users.

**Comment by nirvana-msu** [comment]
Any thoughts?

**Comment by nirvana-msu** [comment]
Ping... could you please incorporate this into your build? Would make like of windows users much easier.

**Comment by mattip** [comment]
The files `concrt140.dll`, `msvcp140.dll`, `vcruntime140.dll`, and `vcruntime140_1.dll` were needed for this build of ray. The usual path to get these is to download and install them, rather than to package them with a library. For instance, SciPy also depends on these and does not distribute it with the wheel. Perhaps ray could document the need for a [visual studio runtime](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) `vc_redist.x86.exe`or `vc_redist.x64.exe`.

**Comment by nirvana-msu** [comment]
Actually SciPy, as well as numpy and most other packages, install on Windows from wheels without the need for visual studio runtime (from my fairly recent experience). The whole point of (good) wheels is to avoid such dependencies. I'd be happy to be proven wrong.

My example in the comments above was actually a bad one - not all those DLLs are, in fact, needed. My issue was that I was using Anaconda-based python (while still using `pip install`), and Anaconda-based python lacks those DLLs (unlike normal CPython, which pip packages are built for).

I haven't tried installing Ray recently on a windows machine without compiler. It could well be that it just works (and if so this issue can be closed) - but if it doesn't, I'd still consider this to be an issue.

**Comment by rgommers** [comment]
The above is not quite correct, SciPy's Windows wheels do ship with `msvcp140.dll`. If you unpack the `scipy-1.7.1-cp39-cp39-win_amd64.whl` wheel from https://pypi.org/project/scipy/1.7.1/#files, you will find this DLL in `scipy/.libs/`.

It's copied into the wheel here: https://github.com/MacPython/scipy-wheels/blob/ab97e7f6c409cc992ebe909dcbd623105e51d450/appveyor.yml#L149.

I expect that if you ship C++ code on Windows, you want to bundle in the relevant DLLs to avoid issues. These issues happen on a small fraction of end user installs, because many projects install those DLLs onto a system - but they're not guaranteed to be there.

**Comment by mattip** [comment]
Thanks @rgommers for the clarification.

**Comment by nirvana-msu** [comment]
I would expect the issue to be quite common for users working within firewalled corporate environments without administrative access on their machines.

And just to clarify again - not all DLLs from my old comment have to be bundled (obviously). E.g. CPython before 3.5 included `msvcr140.dll`, and 3.6+ includes `vcruntime140.dll`.

[delvewheel](https://github.com/adang1345/delvewheel) that I mentioned above seems to handle this task perfectly - it's really just one `delvewheel repair` call that you need to include in your build script - much like `auditwheel` on linux.

**Comment by dharhas** [comment]
I wonder if we could use the dev vm and uninstall the compiler packages, it might be baked in however.

**Comment by mattip** [comment]
I can reproduce this using [docker desktop](https://docs.docker.com/desktop/windows/install/), setting it to use [windows containers](https://docs.docker.com/desktop/windows/#switch-between-windows-and-linux-containers) rather than linux ones, then running a [python windows docker image](https://hub.docker.com/r/winamd64/python) which provides a bare python3.9 inside windows. From there doing the following fails with the "FileNotFoundError" that indicates a supporting DLL is missing.
```
> docker run -it --rm winamd64/python cmd.exe
rem Now inside the docker
C:\> python -m pip install ray
C:\> pyhon -c "import ray"
```

I don't think this is practical to run in CI, but it will let me create a PR to solve the issue.

**Comment by mattip** [comment]
I can confirm that only `msvcp140.dll` is missing, so the solution should look like the one in SciPy:
- add the `dll` to the directory where `_raylet.pyd` is
or
- add the `dll to a `.libs` directory under ray, and
- add a `os.add_dll_directory() call to `__init__.py` before importing `_raylet`

I think the first solution is easier.
