### ISSUE TITLE
[Tune] IterableDatasets gives TypeError on Python3.7+

### ISSUE THREAD

**Issue by yorickvanzweeden** [ray-project/ray#13528]
### What is the problem?

The usage of an IterableDataset with Python 3.7+ gives a TypeError. I am using Pytorch Lightning. 
```
TypeError: object of type 'MyIterableDataset' has no len()
```

This does not occur on Python 3.6. It also does not occur when not using raytune (i.e.: calling `train_model` rather than `tune_hyperparameters`).

Package versions:
```
python==3.7+
pytorch-lightning==1.1.3
ray[tune]==1.1.0 (and the latest nightly)
pytorch==1.7.1
```

### Reproduction (REQUIRED)
```python
import torch
from torch.utils.data import DataLoader, IterableDataset
from pytorch_lightning.loggers import TensorBoardLogger
import pytorch_lightning as pl

from ray import tune
from ray.tune import CLIReporter
from ray.tune.schedulers import ASHAScheduler
from ray.tune.integration.pytorch_lightning import TuneReportCallback

class MyIterableDataset(torch.utils.data.IterableDataset):
    def __init__(self):
        super(MyIterableDataset).__init__()

    def __iter__(self):
        for i in range(1, 1000):
            yield torch.rand(1, 768), torch.Tensor(1)

class BoringModel(pl.LightningModule):
    def __init__(self, batch_size: int = 32):
        super().__init__()
        self.layer = torch.nn.Linear(768, 2)
        self.batch_size = batch_size

    def forward(self, x):
        return self.layer(x)

    def loss(self, batch, prediction):
        # An arbitrary loss to have a loss that updates the model weights during `Trainer.fit` calls
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def step(self, x):
        x = self(x)
        out = torch.nn.functional.mse_loss(x, torch.ones_like(x))
        return out

    def training_step(self, batch, batch_idx):
        output = self.layer(batch[0])
        loss = self.loss(batch[1], output)
        return {"loss": loss}

    def training_step_end(self, training_step_outputs):
        return training_step_outputs

    def training_epoch_end(self, outputs) -> None:
        torch.stack([x["loss"] for x in outputs]).mean()

    def validation_step(self, batch, batch_idx):
        output = self.layer(batch[0])
        loss = self.loss(batch[1], output)
        return {"loss": loss}

    def validation_epoch_end(self, outputs) -> None:
        self.log(f"val_loss", torch.stack([x["loss"] for x in outputs]).mean())

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]
    
    def train_dataloader(self):
        return DataLoader(MyIterableDataset(), batch_size=self.batch_size, num_workers=2)

    def val_dataloader(self):
        return DataLoader(MyIterableDataset(), batch_size=self.batch_size, num_workers=2)

    def test_dataloader(self):
        return DataLoader(MyIterableDataset(), batch_size=self.batch_size, num_workers=2)

def train_model(config):
    logger = TensorBoardLogger(save_dir="")
    model = BoringModel(config["batch_size"])
    trainer = pl.Trainer(
        max_epochs=5,
        logger=logger,
        progress_bar_refresh_rate=0,
        callbacks=[TuneReportCallback({
            "val_loss": "val_loss",
        }, on="validation_end")]
    )
    trainer.fit(model)

def tune_hyperparameters(num_samples=10, num_epochs=10):
    config = { "batch_size": tune.choice([32, 64]) }

    scheduler = ASHAScheduler(
        max_t=num_epochs,
        grace_period=1,
        reduction_factor=2)

    reporter = CLIReporter(
        parameter_columns=["batch_size"],
        metric_columns=["val_loss", "val_accuracy", "epoch"])

    analysis = tune.run(
        train_model,
        resources_per_trial={
            "cpu": 1,
            "gpu": 0
        },
        metric="val_loss",
        mode="min",
        config=config,
        num_samples=num_samples,
        scheduler=scheduler,
        progress_reporter=reporter)

tune_hyperparameters(1, 15)
```
- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### Full stacktrace
```
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/ray/tune/function_runner.py", line 316, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/ray/tune/function_runner.py", line 575, in _trainable_func
    output = fn()
  File "IterableDataset_example(1).py", line 81, in train_model
    trainer.fit(model)
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 472, in fit
    results = self.accelerator_backend.train()
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py", line 62, in train
    results = self.train_or_test()
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 69, in train_or_test
    results = self.trainer.train()
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 494, in train
    self.run_sanity_check(self.get_model())
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 692, in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 595, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 827, in __init__
    self._reset(loader, first_iter=True)
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 857, in _reset
    self._try_put_index()
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1091, in _try_put_index
    index = self._next_index()
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 427, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/opt/miniconda3/envs/iterabletest4/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 67, in __iter__
    return iter(range(len(self.data_source)))
TypeError: object of type 'MyIterableDataset' has no len()
```

**Comment by richardliaw** [comment]
So I'm not exactly sure why, but it seems like the dataloader used in lightning switches from `SequentialSampler` to `RandomSampler` when using Ray/Tune, and one of them has better support for custom DataLoaders. 

One workaround for this is to support `__len__` in your custom dataloader for now.

**Comment by yorickvanzweeden** [comment]
I suspected something to the likes of that, but I could not confirm it.

When you implement `__len__`, it crashes on a lack of `__get_item__`. It tries to use an indexer:
```
data = [self.dataset[idx] for idx in possibly_batched_index]
```
I think the best workaround is to use Python 3.6 for now

**Comment by rubick1896** [comment]
This bug has not been fixed in ray 1.2. I am using pytroch instead of pytorch_lightning and got the same error.
The following are some rewrite code from the original example posted.

python==3.7+
ray[tune]==1.2.0
pytorch==1.8.1

```python
import torch
from torch.utils.data import DataLoader, IterableDataset
from torch import nn
import torch.optim as optim

from ray import tune
from ray.tune.schedulers import ASHAScheduler

class MyIterableDataset(torch.utils.data.IterableDataset):
    def __init__(self):
        super(MyIterableDataset).__init__()

    def __iter__(self):
        for i in range(1, 1000):
            yield torch.rand(1, 768), torch.Tensor(1)

class BoringModel(nn.Module):
    def __init__(self, batch_size: int = 32):
        super().__init__()
        self.layer = torch.nn.Linear(768, 2)
        self.batch_size = batch_size

    def forward(self, x):
        return self.layer(x)

def train_model(config):
    device = torch.device('cpu')
    model = BoringModel(config["batch_size"]).to(device)
    train_loader = DataLoader(MyIterableDataset(), batch_size=config['batch_size'], num_workers=2)
    #valid_loader = DataLoader(MyIterableDataset(), batch_size=config['batch_size'] num_workers=2)
    model_optim = optim.Adam(model.parameters(), lr=1e-3)
    criterion =  nn.MSELoss()
    for epoch in range(5):
        train_loss = []
        for x_batch, y_batch in train_loader:
            x_batch = x_batch.to(device)
            y_batch = y_batch.to(device)
            output = model(x_batch)

            loss = criterion(output, batch_y)
            train_loss.append(loss.item())

            loss.backward()
            model_optim.step()

    tune.report(train_loss=np.mean(train_loss))

def tune_hyperparameters(num_samples=10):
    config = {"batch_size": tune.choice([32, 64]) }

    scheduler = ASHAScheduler(
        max_t=5,
        grace_period=1,
        reduction_factor=2)

    analysis = tune.run(
        train_model,
        resources_per_trial={
            "cpu": 1,
            "gpu": 0
        },
        metric="train_loss",
        mode="min",
        config=config,
        num_samples=num_samples,
        scheduler=scheduler)

tune_hyperparameters()
```

`
(pid=2632136) 2021-04-20 08:48:53,507	ERROR function_runner.py:254 -- Runner Thread raised error.
(pid=2632136) Traceback (most recent call last):
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/ray/tune/function_runner.py", line 248, in run
(pid=2632136)     self._entrypoint()
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/ray/tune/function_runner.py", line 316, in entrypoint
(pid=2632136)     self._status_reporter.get_checkpoint())
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/ray/tune/function_runner.py", line 576, in _trainable_func
(pid=2632136)     output = fn()
(pid=2632136)   File "<ipython-input-1-c5806bb62548>", line 36, in train_model
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 355, in __iter__
(pid=2632136)     return self._get_iterator()
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 301, in _get_iterator
(pid=2632136)     return _MultiProcessingDataLoaderIter(self)
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 940, in __init__
(pid=2632136)     self._reset(loader, first_iter=True)
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 971, in _reset
(pid=2632136)     self._try_put_index()
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1205, in _try_put_index
(pid=2632136)     index = self._next_index()
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 508, in _next_index
(pid=2632136)     return next(self._sampler_iter)  # may raise StopIteration
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
(pid=2632136)     for idx in self.sampler:
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 67, in __iter__
(pid=2632136)     return iter(range(len(self.data_source)))
(pid=2632136) TypeError: object of type 'MyIterableDataset' has no len()
(pid=2632136) Exception in thread Thread-2:
(pid=2632136) Traceback (most recent call last):
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/threading.py", line 926, in _bootstrap_inner
(pid=2632136)     self.run()
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/ray/tune/function_runner.py", line 267, in run
(pid=2632136)     raise e
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/ray/tune/function_runner.py", line 248, in run
(pid=2632136)     self._entrypoint()
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/ray/tune/function_runner.py", line 316, in entrypoint
(pid=2632136)     self._status_reporter.get_checkpoint())
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/ray/tune/function_runner.py", line 576, in _trainable_func
(pid=2632136)     output = fn()
(pid=2632136)   File "<ipython-input-1-c5806bb62548>", line 36, in train_model
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 355, in __iter__
(pid=2632136)     return self._get_iterator()
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 301, in _get_iterator
(pid=2632136)     return _MultiProcessingDataLoaderIter(self)
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 940, in __init__
(pid=2632136)     self._reset(loader, first_iter=True)
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 971, in _reset
(pid=2632136)     self._try_put_index()
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1205, in _try_put_index
(pid=2632136)     index = self._next_index()
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 508, in _next_index
(pid=2632136)     return next(self._sampler_iter)  # may raise StopIteration
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
(pid=2632136)     for idx in self.sampler:
(pid=2632136)   File "/home/wenrui29/anaconda3/envs/gpu5/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 67, in __iter__
(pid=2632136)     return iter(range(len(self.data_source)))
(pid=2632136) TypeError: object of type 'MyIterableDataset' has no len()
`

**Comment by cmlakhan** [comment]
Any update on this issue?  Having the same issue when I try to run ray tune.  Is this a Ray issue or PyTorch issue?

python - 3.8.5
pytorch - 1.8.1
ray - 1.4.0

**Comment by amogkam** [comment]
Looking into this right now...this is because of some weird pickling issue specifically with IterableDataset.

What's happening is that when used with Ray, this https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L200 line is returning False when it shouldn't be, causing torch to think that the dataset being passed in is a Map-style dataset instead of an Iterable-style. Hence, it tries to do `len()` calls on the dataset.

Here's a simpler example illustrating the same issue:
```
import ray
from torch.utils.data import IterableDataset

class MyIterableDataset(IterableDataset):
	def __iter__(self):
		while True:
			yield 1

def f():
	iter_ds = MyIterableDataset()
	assert isinstance(iter_ds, IterableDataset)

f() # This passes.

ray.init()
remote_f = ray.remote(f)
ray.get(remote_f.remote()) # This fails.
```

**Comment by amogkam** [comment]
Looking into this now...it's some weird pickling issue.

What's happening is that when using with Ray, this line https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L200 is returning False when it shouldn't be. This causes torch to think a Map-style dataset is passed in instead of an Iterable-style one, hence it tries to make `len()` calls on the dataset.

Here is a simpler example showing the same issue:
```
import ray
from torch.utils.data import IterableDataset

class MyIterableDataset(IterableDataset):
	def __init__(self):
		super(MyIterableDataset).__init__()
	def __iter__(self):
		while True:
			yield 1

def f():
	iter_ds = MyIterableDataset()
	assert isinstance(iter_ds, IterableDataset)

f() # This passes.

ray.init()
remote_f = ray.remote(f)
ray.get(remote_f.remote()) # This fails.
```

**Comment by amogkam** [comment]
OK this should work if you move `MyIterableDataset` to a separate file and then import in into the main script. This is due to cloudpickle serialization. @suquark can provide more info here.

**Comment by cmlakhan** [comment]
Thank you, looks like moving IterableDataset to a separate file did the trick.
