### ISSUE TITLE
Use of fork in process.cc

### ISSUE THREAD

**Issue by smorad** [ray-project/ray#13568]
It appears that `process.cc` uses only `fork` for Linux systems. There is a `TODO` there that discusses using `clone` or `spawnp` https://github.com/ray-project/ray/blame/86d5000047593439c768d35565ece702b1b62162/src/ray/util/process.cc#L175. I was wondering if this work was still planned by @mehrdadn or any others.

Many of the popular 3D simulators tend to use `libEGL` and it's my understanding that `fork`ing the environments causes issues. If fixes are no longer planned, are there any other workarounds?

**Comment by mehrdadn** [comment]
I don't have any plans to make changes to it (I doubt others do either), but that's mostly a consequence of us not being aware of people encountering problems with it yet. I think if problems are reported, the team might investigate solutions. Have you seen `fork` cause problems? If so, would you mind providing details of what the problem is and how you have traced it to `fork` as the root cause?

Note that `posix_spawnp` uses `clone`, and `clone` can replicate `fork` (or not) depending on the flags. If there are problems, the precise nature needs to be tracked down, since that will dictate which flags need to be passed to which functions.

**Comment by smorad** [comment]
I'm looking specifically at [Habitat](https://github.com/facebookresearch/habitat-sim), but I believe [Gibson](https://github.com/StanfordVL/GibsonEnv) and [others](https://github.com/minosworld/minos) also use `libegl`

https://github.com/facebookresearch/habitat-sim/issues/664#issuecomment-650590776
I'm still investigating, I will update once I learn more:

**Comment by mehrdadn** [comment]
I see, thanks. It sounds like the problem might be one (or more) of the following:

1. File descriptors (FDs) for CUDA contexts aren't marked with `FD_CLOEXEC`, and thus they persist into `fork`ed processes, which then causes `fork`ed processes to be unable to open new contexts without closing the old ones.

2. Once a process gets a CUDA context, some other part of its state (such as the virtual memory or its kernel-mode state) is altered in a way such that a new context cannot be obtained following a `fork`, no matter what is done afterward.

Possible solutions to case 1 might be one of the following, in order of preference:

1. To mark the FD with `FD_CLOEXEC`.
2. Use `pthread_atfork` to manually close the FD following a `fork`.
3. To close all FDs except standard I/O after `fork` but before `exec`.

Possible solutions to case 2 might be one of the following, in order of preference:

1. If the problem is with virtual memory behaving funny, `vfork` might solve this.
2. Otherwise, the only potential solution might be to simply avoid acquiring a context before a `fork`.

Here's what I would recommend doing:

Write a simple hello-world CUDA program (just a simple `C` file, without anything from Ray in it) that `fork`s and then breaks in the same way that Ray does. Then figure out how to make it spawn a process without `fork` such that it succeeds. Then post the solution here so the team can look into implementing in Ray.

**Comment by smorad** [comment]
@mehrdadn thanks for the detailed writeup. I'm attaching minimal source code that appears to replicate this issue (it appears that using `clone` solves the problem). Please take a look at the comments in `main()` for further understanding. Thanks to @erikwijmans for providing the GLAD/EGL device enumeration code.

I'm using docker `nvidia/cudagl:11.0-devel-ubuntu20.04` to test.

[egl-test-case-smorad.zip](https://github.com/ray-project/ray/files/5875873/egl-test-case-smorad.zip)

**Comment by smorad** [comment]
I've figured out a workaround. My mistake was calling `ray.get_gpu_ids()` before the initialization of my environment. This creates a CUDA context and causes future EGL calls to fail. By querying `CUDA_VISIBLE_DEVICES` instead, we can ensure CUDA initialization happens after EGL initialization.

Closing as changing the worker/process architecture of ray is likely a herculean task.

**Comment by mehrdadn** [comment]
@smorad Thanks for the example! So I'm looking at it and I'm confused about 2 things:

- Are you saying you would replace `fork()` with `clone(..., ..., CLONE_VM, ...)`? Because that would make the child run in the same memory space as the parent *immediately*, which means effectively get 2 threads rather than 2 processes. You can't launch processes this way. And you also need to make sure `SIGCHLD` gets sent to the parent when the child dies, so I think what you really wanted is `CLONE_VM | CLONE_VFORK | SIGCHLD`? (It turns out calling `clone()` with these parameters is equivalent to `vfork()`.)

- Shouldn't there be an `exec()` call too? We only do `fork()` + `exec()`, not a `fork()` by itself. That affects what's in the memory space.

If `clone(CLONE_VM | CLONE_VFORK | SIGCHLD)` followed by `exec()` works, then it would suggest we could just replace `fork()` with `vfork()` and get the behavior you want, but it has [some caveats](https://dwheeler.com/secure-programs/Secure-Programs-HOWTO/avoid-vfork.html). I do think your workaround is better, but let me know if your workaround might not be possible in some situations.

**Comment by smorad** [comment]
As you can tell, it has been a long time since my last operating systems course.

What python `multiprocessing` does is give you an option of methods when creating processes: `[fork, forkserver, spawn]`. I think what might make most sense is to give a second process creation method to the users that they can switch to if `fork` doesn't work for them. I didn't try `vfork` because it stalls the parent process and requires an `execve` call -- I forgot that `process.cc` immediately `exec`s after forking, which makes this a non-issue.

**Comment by mehrdadn** [comment]
@smorad Oh, interesting. I think that means the user can just run `multiprocessing.set_start_method('forkserver')` in the start of the process? Does that work if you try it? How about `spawn`? (Note that it [might not](https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods).)

There _is_ a contextual version of `multiprocessing` (`get_context()`) Ray could accept from the user and use it to launch processes, but I'm not sure that's a good idea in this case: here, it sounds like this is a setting that would need to be changed globally, otherwise any other launch via `fork` would still break CUDA.

**Comment by smorad** [comment]
I have tried all three methods outside of ray and they work on a normal linux system. Both `forkserver` and `spawn` seem to bypass the issue that occurs using `fork`. 

In the parent process, you call `set_start_method`. In child processes you can use `get_context` to see how the child was spawned and presumably use the same start method for children's children.

**Comment by mehrdadn** [comment]
I think the child process inherits the start method, so there's no need for `get_context`?
```
def f(*args): print(__import__('multiprocessing').get_start_method())
if __name__ == '__main__':
	import multiprocessing as mp
	mp.set_start_method('forkserver')
	mp.Process(target=f).start()
```
So it sounds like you just need to call `set_start_method` before using Ray?

**Comment by smorad** [comment]
Are you saying that `rllib` uses python's `multiprocessing` module and not `process.cc` behind the scenes for creating workers?

**Comment by mehrdadn** [comment]
Oh, no, sorry. I thought you'd seen `multiprocessing` in some part of the code and were talking about that. Otherwise I'm very confused what its relevance to the C code was. You're saying Python should tell the C code what its mode is, and then... skip the `fork()` call in C and do what exactly? Call back into Python and have e.g., the fork server do the spawning? Sorry I'm really confused.

**Comment by mehrdadn** [comment]
(And to clarify, I'm not familiar with the whole codebase (especially not rllib) so I don't know offhand what mechanism is used everywhere.)

**Comment by smorad** [comment]
Ah, no, sorry.

I meant to say that the `ray` python interface seems to somewhat emulate python's `multiprocessing` module, but calls out to `process.cc` to actually handle process creation. I was thinking it would make sense if `ray` followed the python approach of allowing different types of process creation `fork, spawn`, etc. to be specified by the user. Perhaps in the JSON ray config, there could be something like `"fork_method": "vfork"`.

To do this would require implementing other process creation methods in `process.cc`.

**Comment by mehrdadn** [comment]
Oh I see. With respect to `fork` vs. `vfork`/`clone`/etc., I think it's unrelated to what you're seeing in `multiprocessing`. What I understand `spawn` does is that it launches a separate process first, then tries to replicate the Python state into that process via pickling—meaning it would miss any non-Python state. And what `forkserver` does is that it pre-launches a process and then forks from that. But I think all of those use `fork()` underneath. So the only way "emulating `multiprocessing`'s approach" could work is if the C++ code starts its own forkserver. I'm not sure this is a great way to go personally (imagine if every program did this!) but if it becomes really necessary then I imagine someone could look into it.

The better approach to me does seem to be to provide an option to use `vfork` in C++. It's tricky though, because you have to (a) ensure that between the `vfork` and `exec` calls, *nothing* is manipulated anywhere except on the stack (no heap allocations, etc.), and (b) write enough comments/warnings in the code to ensure that this remains the case as the code evolves.

This might be something to look into for the future, but I imagine it'd be pretty low priority for the team given that you mentioned you can just defer calling `ray.get_gpu_ids()` to post-initialization to avoid the entire problem. So I'd say just try to do that for now. If you (or others) run into this problem in a scenario where that isn't an option, then I'd say you should reopen this issue and ask the team to look into this.
