### ISSUE TITLE
[core] Fail submitted tasks immediately when an actor is temporarily unavailable

### ISSUE THREAD

**Issue by kfstorm** [ray-project/ray#13594]
Currently, when an actor has `max_restarts` > 0 and crashed, the actor will enter RESTARTING state and then ALIVE. Imagine this scenario: an online service provides HTTP service and the proxy actor receives requests, forwards them to worker actors, and replies to clients with the execution results from worker actors.

```
                                                        -> Worker A (actor)
                                                       /
                                                      /
HTTP requests -------> Proxy (actor with HTTP server) ---> Worker B (actor)
                                                      \
                                                       \
                                                        -> ...
```

For each HTTP request, the proxy picks one worker (e.g. worker A) based on some algorithm, sends the request to it, and call `ray.get()` to wait for the result. If for some reason the picked worker crashed, Ray will restart the actor, and `ray.get()` will throw an error. The proxy may pick another worker (e.g. worker B) and re-send the request to it. This is OK.

But new requests keep coming. The proxy may pick worker A again. But because worker A is still in RESTARTING state, it's not ready to serve requests. This time, `ray.get()` will hang until worker A is back online (ALIVE state). The proxy won't be able to reschedule the request to another worker because it doesn't if worker A is alive or not. `ray.get()` hanging is probably just because the execution on worker requires quite a lot of time.

To solve this issue, in Ant internal repo, we added a new flag when creating an actor to control the strategy of submitting new tasks when the actor is in RESTARTING state. When the callee actor is in RESTARTING state, by default, newly submitted tasks will be queued in direct actor transport and only send them when the ALIVE state notification is received. But if the flag is turned on, newly submitted tasks will fail immediately with a RayActorError. This solution makes the fallback very quick when a worker is temporarily unavailable and improved P99 latency of the online service.

We hope we can contribute this back to community. @rkooo567 @stephanie-wang what do you think?

cc @raulchen @ffbin @jovany-wang @MissiontoMars

**Comment by rkooo567** [comment]
cc @edoakes

**Comment by raulchen** [comment]
@ericl FYI, this issue is related to your comment https://github.com/ray-project/ray/pull/13334#issuecomment-762650327

**Comment by raulchen** [comment]
Another important thing is the semantics of actor restart. E.g., whether we should make actor restart transparent to users. 
Currently the semantic is kind of broken:
- If the task is submitted before the caller receives the RESTARTING notification, the task will fail due to the network errors.
- If the task is submitted after the caller receives the RESTARTING notification, the task will be pending until the actor restarts.

**Comment by kfstorm** [comment]
Does anyone want to comment on this issue?

**Comment by edoakes** [comment]
@kfstorm @raulchen the problem makes a ton of sense (this is actually an existing problem for Ray Serve cc @simon-mo ) and the solution sounds pretty reasonable to me.

One question I have: how does this interact with the `max_task_retries` mechanism that we have for actors? In the situation you described, we probably don't want `max_task_retries` to be turned on at all, so maybe they should just be mutually exclusive.

**Comment by kfstorm** [comment]
@edoakes Do you mean `max_retries`? We haven't tried this feature internally. But I think you are right, they are mutually exclusive. Does Ray Serve use `max_retries`?

**Comment by edoakes** [comment]
@kfstorm I meant `max_task_retries` - it's an option to actors that enables actor tasks to be retried when the actor restarts. Serve does not currently use it because of a similar issue to what you described above, we don't want to have to wait until the actor restarts for the request to be processed.

**Comment by stephanie-wang** [comment]
I'm not sure if it's a good idea to expose internal states like RESTARTING to the user.

One idea we prototyped a while back was having callbacks for when an actor fails the first time and when the actor restarts. That seems like it would be enough for all of these use cases, is that right?

**Comment by edoakes** [comment]
@stephanie-wang even with callbacks, wouldn't the user still need to know the state of the actor in order to make the informed decision to send it to an actor that's currently running (avoid the restarting actor)? Or are you thinking that the user does something like remove the actor from a "running" map when it restarts and then asynchronously re-add it once it's been restarted? That might be tricky to implement, especially if you're running in a serial python script and not an `asyncio` loop or similar.

**Comment by kfstorm** [comment]
@edoakes Oh, I see. `max_retries` is for tasks and `max_task_retries` is for actors, right?

I think letting users maintain a map of alive actors is error-prune. Users may not have the knowledge to implement it correctly.

**Comment by kfstorm** [comment]
The issue is still valid.

**Comment by kfstorm** [comment]
Working on this.
