### ISSUE TITLE
[tune] Why does some search algos have random seed argument while others algo/schedulers does not?

### ISSUE THREAD

**Issue by turmeric-blend** [ray-project/ray#13616]
Why does `HyperOpt` and `BOHB` have a `seed` argument while other search **algorithms** or even search **schedulers** not have them? Wouldn't it be more consistent to have it across all the functions? I am using Ray version 1.1.0

**Comment by krfricke** [comment]
Hi @turmeric-blend, those search algorithms use a custom random state that has to be instantiated independently. The other ones usually use either python's `random` module or (more common) numpy's `np.random` module for random sampling. In these cases seeding with `random.seed` and `np.random.seed` should lead to the desired behavior.

Please note though that distributed training introduces some kind of non-determinism that is hard to tackle, e.g. if a trial finishes before another trial, which might be just due to machine performance. Thus even with seeds you'll not always get the exact same results. Also note that there seems to be some more non-determinism (https://github.com/ray-project/ray/issues/13295) that I'm looking into fixing this/next week.

By the way, are the missing seed parameters something you'd like to see in the docs?

**Comment by turmeric-blend** [comment]
So far for the `non-determinism when trial finishes before another trial`, I understand this and would work keeping this in mind.

For the random seeds of **algorithms** and **schedulers**, I think 

1. If it can be set via `random`/`numpy.random`/`torch.random`, its better if its stated in the docs in each method for clarity.
2. If it can be implemented as a random seed argument like `ASHA`, then yes it would be nice to have it as an argument.
3. If it can't be done via 1. or 2. and requires `"custom random state that has to be instantiated independently"` as you mentioned, then also mentioning this in the docs would provide more clarity.

Thanks for you time :)

**Comment by krfricke** [comment]
Thanks for the feedback! I'll add this to the docs when working on #13295.
