### ISSUE TITLE
[Ownership-based Object Directory] Not resilient to owner failures.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#13654]
### What is the problem?

Imagine there are 10 raylets (R1...R10) that are subscribing to owner A existing on a node R1. If A dies, this will happen. 

- In R1, all the objects owned by A will be evicted.
- Object directory will detect it and update this location change.
- Since the owner is already dead, there's no way for other raylets to know if the object was evicted.

We need a robust protocol to avoid this. cc @stephanie-wang @clarkzinzow 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by stephanie-wang** [comment]
The existing ownership protocol should already handle this case because the raylet will eventually notice that the owner is dead and mark the object as failed ([code here](https://github.com/ray-project/ray/blob/master/src/ray/raylet/node_manager.cc#L2086)).

**Comment by clarkzinzow** [comment]
@stephanie-wang Sweet! On the object pull path, if the object location subscription RPC fails (e.g. because the owner can't be reached), I'm assuming that it would be fine to propagate that failure as an empty set of object locations and no spill URL/node ID set? It looks like the pull manager would currently do a no-op pull, silently, given that [there's no else clause](https://github.com/ray-project/ray/blob/edbb2937d393f9cd95a5016bc2df5250bbd59152/src/ray/object_manager/pull_manager.cc#L318-L344). Or should the pull be explicitly canceled somewhere in that flow?

**Comment by clarkzinzow** [comment]
For the sake of posterity, once all of the task’s dependencies are ready (including the `UNRECONSTRUCTABLE` error object added by the reconstruction policy), the task will get scheduled and `RemoveTaskDependencies` and `CancelGet` will get invoked, cancelling those outstanding pull requests.
