### ISSUE TITLE
Got permission denied while trying to connect to the Docker daemon when deploying a ray-cluster in Azure

### ISSUE THREAD

**Issue by GiovanniGatti** [ray-project/ray#13711]
### What is the problem?

Splitting from [issue 13599](https://github.com/ray-project/ray/issues/13599), I'm unable to install a ray cluster in Azure.

```
$ ray up ~/sources/yaps/example-full.yaml --no-config-cache
Cluster: <hidden>

Checking Azure environment settings
2021-01-26 14:52:01,797 INFO config.py:39 -- Using subscription id: <hidden>
2021-01-26 14:52:01,797 INFO config.py:53 -- Creating/Updating Resource Group: <hidden>
No head node found. Launching a new cluster. Confirm [y/N]: y

Acquiring an up-to-date head node
  Launched a new head node
  Fetching the new head node
  
<1/1> Setting up head node
  Prepared bootstrap config
  New status: waiting-for-ssh
  [1/7] Waiting for SSH to become available
    Running `uptime` as a test.
    Fetched IP: <hidden>
ssh: connect to host <hidden> port 22: Connection refused
    SSH still not available (SSH command failed.), retrying in 5 seconds.
...
ssh: connect to host <hidden> port 22: Connection refused
    SSH still not available (SSH command failed.), retrying in 5 seconds.
Warning: Permanently added '<hidden>' (ECDSA) to the list of known hosts.
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

 13:56:20 up 2 min,  1 user,  load average: 2.93, 1.01, 0.37
Shared connection to <hidden> closed.
    Success.
  Updating cluster configuration. [hash=b6e4a35cf161a0aeadf43c85d921602da74217c1]
  New status: syncing-files
  [2/7] Processing file mounts
Shared connection to <hidden> closed.
Shared connection to <hidden> closed.
  [3/7] No worker file mounts to sync
  New status: setting-up
  [4/7] Running initialization commands
Warning: Permanently added '<hidden>' (ECDSA) to the list of known hosts.
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

Connection to <hidden> closed.
  [5/7] Initalizing command runner
Shared connection to <hidden> closed.
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=rayproject%2Fray-ml&tag=latest-gpu: dial unix /var/run/docker.sock: connect: permission denied
Shared connection to <hidden> closed.
  New status: update-failed
  !!!
  SSH command failed.
  !!!
  
  Failed to setup head node.
```

### Reproduction (REQUIRED)

OS: ubuntu 18.02
Python: 3.7.1
VirtualEnv: [requirements.txt](https://github.com/ray-project/ray/files/5873812/requirements.txt)

example-full.yaml is the same provided by ray team (except by the cluster-name/resource_group/subscription_id fields)

e.g., ` pip install ray azure-cli azure-mgmt-compute==14.0.0`

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [  ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by arh89** [comment]
@GiovanniGatti I had the same issue. As a workaround I tried adding `sudo usermod -aG docker $USER` to the `initialization_commands` section (below the existing `touch` command), which seemed to resolve things. Hope that helps you too.

**Comment by arh89** [comment]
@GiovanniGatti I had the same issue. As a workaround I tried adding `sudo usermod -aG docker $USER; newgrp docker` to the `initialization_commands` section (below the existing `touch` command), which seemed to resolve things. Hope that helps you too. (Annoyingly I had to `exit` from the head node after adding these commands, but I'm sure the fix for that isn't too challenging...)

(NB: As far as I'm aware, if you just take the existing `example-full.yaml` config and try to deploy (after changing the subscription id etc) using `ray up` then it won't quite work because the `setup_commands` section modifies the `.bashrc` to activate the `py37_tensorflow` conda environment which doesn't exist inside the `ray-ml` docker images. As far as I'm aware, the solution would be to _either_ use the docker image _or_ stick with the setup commands which build upon the Azure data science VM image. That might be covered under another issue though, or it might that I'm misunderstanding how the deployment process works...)

**Comment by richardlin047** [comment]
Adding `sudo usermod -aG docker $USER; sleep 10` helped fix the Docker permission error. I then get this error:
``` 
  [6/7] Running setup commands
    (0/4) echo 'eval "$(conda shell.bash...
Shared connection to 52.137.121.68 closed.
    (1/4) echo 'conda activate py37_tens...
Shared connection to 52.137.121.68 closed.
    (2/4) pip install -U https://s3-us-w...
Could not find conda environment: py37_tensorflow
You can list all discoverable environments with `conda info --envs`.

Could not find conda environment: py37_tensorflow
You can list all discoverable environments with `conda info --envs`.

Shared connection to 52.137.121.68 closed.
  New status: update-failed
  !!!
  SSH command failed.
  !!!
  
  Failed to setup head node.
```

I've tried removing the setup_commands, but still the same error.

**Comment by AmeerHajAli** [comment]
@gramhagen @eisber, can we please have someone from azure look into this?

**Comment by gramhagen** [comment]
why do we use the rayproject/ray-ml docker image here? is it to leverage the same image across all cloud deployments?

**Comment by AmeerHajAli** [comment]
Cc @ijrsvt

**Comment by omnific9** [comment]
Can we have this looked at please? Learning Ray on the first day because of all the hype, but I keep getting error after error due to version mismatches and other undocumented reasons is quite discouraging.

**Comment by ijrsvt** [comment]
> why do we use the rayproject/ray-ml docker image here? is it to leverage the same image across all cloud deployments?

Yes, to have a consistent set of dependencies with Ray!

@richardlin047 , @omnific9 
Try setting `setup_commands: []`.

Ray autosets `setup_commands` if they are not already set. This behavior is changing to something that will not break inside docker in Ray 1.3 (coming out soon).

**Comment by AmeerHajAli** [comment]
@gramhagen , do you know who is maintaining this from Azure size?

**Comment by gramhagen** [comment]
@eisber and I will help as much as we can from Azure side, but I'm not actively following all issues, so feel free to ping me when something pops up.

Since the goal is to use docker, leveraging the dsvm image isn't that useful, other than the fact that it already has docker installed, but the ubuntu user isn't part of the docker usergroup and I don't think there's any easy way to switch groups from inside a script. It would be possible to force docker commands to run with sudo, but probably an easier alternative is just use a bare Ubuntu image and install docker in rootless mode so sudo is not required.

I switched the node_config settings for head and worker nodes to this:
```
imagePublisher: Canonical
imageOffer: UbuntuServer
imageSku: 18.04-LTS
imageVersion: 18.04.202103250
```

then modified the commands to this:
```
initialization_commands:
    # get rid of annoying Ubuntu message
    - touch ~/.sudo_as_admin_successful
    # install docker in rootless mode
    - curl -fsSL https://get.docker.com/rootless | sh
    - echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
    - echo 'export DOCKER_HOST=unix:///run/user/1000/docker.sock' >> ~/.bashrc
    - source ~/.bashrc

# List of shell commands to run to set up nodes.
setup_commands: []
```

I still have some more testing to do, but wanted to see if you had any concerns with this approach

**Comment by gramhagen** [comment]
see latest configuration here: https://github.com/ray-project/ray/pull/15380#issuecomment-821997615

this is still using the dsvm image (not bare ubuntu image mentioned above)

**Comment by ijrsvt** [comment]
@gramhagen Quick Question, does the DSVM have GPU Drivers built in?

**Comment by gramhagen** [comment]
Yes, you just need to use an n-series VM.
