### ISSUE TITLE
[tune] ray.tune.logger.CSVLogger cannot handle new keys in tune.report

### ISSUE THREAD

**Issue by avandekleut** [ray-project/ray#13766]
In my code, I will sometimes call `tune.report` with different metrics depending on if I am training or evaluating. If I first log training metrics, only those keys reported initially will continue to be written to at calls to `tune.report`.

Specifically, these two lines:
[https://github.com/ray-project/ray/blob/0452a3a435e023eada85f670e70ffef02ceb5943/python/ray/tune/logger.py#L146]
[https://github.com/ray-project/ray/blob/0452a3a435e023eada85f670e70ffef02ceb5943/python/ray/tune/logger.py#L151]
cause the issue. It seems like the problem is figuring out how to add a column to the csv file post-hoc. The problem is that `progress.csv` is then used by the `Analysis` class, which fails to know about the evaluation metrics.

Funnily, since the values are also logged to Tensorboard, I can load the values up using Tensorboard's backend, which solves my problem for now. Another solution on my end might be to just always report every key I will ever report at each call to `tune.report`, using `None` or `NaN` or something for the values that arent reported.

Script to reproduce:
```python
from ray import tune

def trainable(config, checkpoint_dir=None):
    for i in range(10):
        tune.report(i=i)
    for j in range(10):
        tune.report(j=j)

analysis = tune.run(trainable)

trial_dfs = analysis.trial_dataframes
trial_df = trial_dfs[list(trial_dfs.keys())[0]]

print(trial_df['i'])

print(trial_df['j'])
```

you will see that the first key logged (`i`) works fine and shows up in `trial_df`, but not `j`, which is logged second.

- [ x] I have verified my script runs in a clean environment and reproduces the issue.
- [x ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
Hi @avandekleut, yes, as you said as a workaround you can try something like this:
```
def trainable(config, checkpoint_dir=None):
    for i in range(10):
        tune.report(i=i, j=None)
    for j in range(10):
        tune.report(i=None, j=j)
```

Usually Tune expects that the same metrics are reported. Most schedulers and searchers can only handle one metric anyway (and the others are just logged). So if you're reporting different metrics for logging purposes, it might be better to write these logs yourself. If you want to save these logs to the trial directories, you can get the current trialdir with `tune.session.get_trial_dir()`.

We are probably not going to support changing metrics for CSV logging. How should the file look like? CSV expects a fixed set of columns, and if this set of columns changes, we would need to rewrite all existing columns, and this would be very inefficient. Note that Tune writes CSV logs on an ongoing basis so that logs are not lost when the Trial fails or stops preemptively.
