### ISSUE TITLE
Actor view refreshed very slowly (or not at all).

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#13883]
The actor page often has outdated information.

### To reproduce
Run the following script (e.g., in IPython).

```python
import ray
ray.init()
```

Then
- navigate to the dashboard
- click on "try experimental dashboard"
- click on the actor tab

Then run

```python
@ray.remote
class Foo:
    def method(self):
        return 1

f = Foo.remote()
```

Nothing shows up in the actor tab (at least not in the first 30 seconds or so). Reloading the page causes the actor to appear.

**Comment by edoakes** [comment]
Labeling as enhancement because it isn't a bug in existing Ray.

**Comment by mxz96102** [comment]
Actor pages are designed to not refresh because the number of actors might be massive. But for further concern, I think it still needs an auto-refresh switch. And it will be turned off by default when there are too many actors (like 1k+ ?) I think it's a better way to solve this problem. ( Sorry for the late reply, we just have our Chinese new year vacation )

**Comment by SongGuyang** [comment]
Solved by https://github.com/ray-project/ray/pull/26785
