### ISSUE TITLE
[gcp] Workers do not start on GCP 

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#14095]
### What is the problem?

The default docker image and example does not work on GCP with the most recent Ray release.

@ijrsvt can you take a look when you get the chance? thanks!

https://discuss.ray.io/t/ray-cluster-does-is-not-creating-workers/873/5

**Comment by rkooo567** [comment]
This is the regression right? We should give a high priority to it?

**Comment by ijrsvt** [comment]
Hmm, This permission is definitely concerning, let me look into why this is happening!

**Comment by richardliaw** [comment]
I will assign high priority to this, as it makes GCP really hard to use (and GCP is the standard for most ML startups).

**Comment by ijrsvt** [comment]
It appears that the source image (the AMI or HostOS) that we default to uses the user Ubuntu, but with `UID=1001`. The container runs with `user=ray, UID=1000`. This usually is not a big problem because the user inside the container and the user on the host have the same UID (The `ubuntu` user usually defaults to UID=1000).
