### ISSUE TITLE
[tune] Memory leak after crash

### ISSUE THREAD

**Issue by jkterry1** [ray-project/ray#14320]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Reproducing this almost certainly requires using external dependencies, so I'll just include the code I was running (they're very minimal):
https://github.com/justinkterry/all_pistonball/blob/e678a3fa087f07e6a5c21e29e4ec0b299212e698/run_hyperparameters.py

I was running a hyperparameter search over some external RL code. It's crashing due to an error I'm trying to debug, causing ray to stop in terminal. However, despite stopping ray doesn't kill the `ray:IimplicitFunc` runners, so they persist in memory despite not actually doing anything, causing a memory leak.

You can see this in htop and nvidia-smi:

<img width="1740" alt="Screen Shot 2021-02-24 at 4 21 04 PM" src="https://user-images.githubusercontent.com/19422700/109067327-5e1fbe80-76bc-11eb-9430-bbaedd4480f0.png">

**Comment by richardliaw** [comment]
are you using `fail_fast` with Tune?

**Comment by justinkterry** [comment]
@richard4912 

1) No, I was using defaults. If defaults result in resource leaks, this is a problem.
2) Settings fail_fast=True is very undesirable because it appears to remove fault tolerance, which is the only reason I'm using Tune
3) This is slightly unrelated but there's a documentation problem for fail_fast. In https://docs.ray.io/en/master/tune/api_docs/execution.html in the main function documentation at the top is says fail_fast is a boolean, but the description of the variable below discusses passing ’raise’ to it (the function of which is never defined).

**Comment by justinkterry** [comment]
Hey, I'm experienced this same problem with `ray::ImplicitFunc` not being releases from CPU/GPU RAM, except for jobs that successfully terminate. This means that I can't run the long tune search I'd like to without running out of memory.

**Comment by ericl** [comment]
I think this is fixed in nightlies if you use placement groups with tune https://docs.ray.io/en/master/tune/api_docs/internals.html#ray.tune.utils.placement_groups.PlacementGroupFactory

The resources will get cleared up with the placement group destruction.
