### ISSUE TITLE
[autoscaler] bash 4.4 does not support set -i

### ISSUE THREAD

**Issue by atypic** [ray-project/ray#1444]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 17.10

- **Ray installed from (source or binary)**:
Source
- **Ray version**:
commit b8811cbe3418ab0d3ea10deaa54947d5bb26cecf

- **Python version**:
3.6
- **Exact command to reproduce**:
ray create_or_update example.yaml

### Describe the problem

As of bash 4.4, set -i is no longer accepted to create an interactive shell. Consider -t in stead.

**Comment by atypic** [comment]
Tried using -t, this creates problems down the line. Will try to come up with a better suggestion...

**Comment by atypic** [comment]
OTOH -- why try to force interactive shells anyway?

**Comment by robertnishihara** [comment]
Thanks @atypic, I believe the motivation was so that the sequence of commands, e.g.,

https://github.com/ray-project/ray/blob/215d526e0d605e2f090da3c7b1ec66c990bec89c/python/ray/autoscaler/aws/development-example.yaml#L69-L80

would share "state" with each other. E.g., modifying the `PATH` in one command carries over to the next.

**Comment by ericl** [comment]
@robertnishihara the commands are actually still separate sessions. The original motivation was so that the setup commands can run with a similar PATH as an interactive shell (otherwise, you'd have to prepend all your commands with things like `PATH=~/anaconda3/bin:$PATH`).

You might think that just auto-prepending `source ~/.bashrc` to each command would be sufficient, but it turns out many bashrc scripts early exit if the session is non-interactive. Hence the `set -i`.

One solution might just be to remove the `set -i`, this is not as nice from the user perspective but avoids weird pitfalls.

**Comment by ericl** [comment]
This stackoverflow post has a better explanation: https://stackoverflow.com/questions/940533/how-do-i-set-path-such-that-ssh-userhost-command-works

**Comment by atypic** [comment]
I tried to remove set -i and modify the yaml accordingly, however something odd happens to the startup of the redis server, making me unable to connect to the socket. The server is running and all seems fine, but ray.init() fails ("Unable to connect to socket /tmp/<id>"...).

Somehow depending on the behavior of bash is not something I'd recommend either, as people like to use a variety of shells.

Another solution could perhaps be to have a "PATH" section in the yaml, and use .ssh/environment.

Node provisioning is always such a mess :(
