### ISSUE TITLE
[rllib] Compute_actions() and Compute_actions_from_input_dict() with AlphaZero algorithm

### ISSUE THREAD

**Issue by KiborgBBK** [ray-project/ray#14477]
Good day!
need help solving this error

ray 2.0.0 (however I installed different versions, and the result is the same)
python 3.7
Ubuntu 20.04

training:
    ModelCatalog.register_custom_model ("dense_model", DenseModel)
    config = {
        "env": CartPole,
        "num_workers": args.num_workers,
        "rollout_fragment_length": 10,
        "train_batch_size": 10,
        "sgd_minibatch_size": 10,
        "lr": 1e-4,
        "num_sgd_iter": 1,
        "mcts_config": {
            "puct_coefficient": 1.5,
            "num_simulations": 100,
            "temperature": 1.0,
            "dirichlet_epsilon": 0.20,
            "dirichlet_noise": 0.03,
            "argmax_tree_policy": False,
            "add_dirichlet_noise": True,
        },
        "ranked_rewards": {
            "enable": True,
        },
        "model": {
            "custom_model": "dense_model",
        },
    }
    log_dir = '/ media / vitaliy / New volume / save_network'

    analysis = tune.run (
        "contrib / AlphaZero",
        config = config,
        local_dir = log_dir,
        keep_checkpoints_num = None,
        checkpoint_freq = 1,
        stop = {"training_iteration": args.training_iteration},
        checkpoint_at_end = True)

loading from save checkpoint:

env = CartPole ()
register_env ("CartPoleEnv", CartPole)
agent = AlphaZeroTrainer (env = "CartPoleEnv", config = config)
agent.restore (checkpoint)
state = env.reset ()
action = agent.compute_action (state)
print (action)

however, as it is written in the documentation ... everything works on the example of other agents (for example, ppo).

... ray / rllib / contrib / alpha_zero / core / alpha_zero_policy.py ", line 62, in compute_actions_from_input_dict
    for i, episode in enumerate (episodes):
TypeError: 'NoneType' object is not iterable

in other versions of ray the same error:
... ray / rllib / contrib / alpha_zero / core / alpha_zero_policy.py ",  in compute_actions
for i, episode in enumerate(episodes):
TypeError: 'NoneType' object is not iterable

or is there some other way to save and load to alpha zero?

It is still not clear how the error pops up:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-35: ordinal not in range (128)
Exception ignored in: 'ray._raylet.get_py_stack'

But it seems like it does not interfere with anything ...

thanks in advance for the help

**Comment by polyzer** [comment]
Hello) I have similar error. But in my case there is Nan here:
 File "C:\Users\user\anaconda3\envs\ray\lib\site-packages\ray\rllib\contrib\alpha_zero\core\alpha_zero_policy.py", line 90, in compute_actions_from_input_dict
    mcts_policy, action, tree_node = self.mcts.compute_action(
  File "C:\Users\user\anaconda3\envs\ray\lib\site-packages\ray\rllib\contrib\alpha_zero\core\mcts.py", line 150, in compute_action
    action = np.random.choice(
  File "mtrand.pyx", line 928, in numpy.random.mtrand.RandomState.choice  
ValueError: probabilities contain NaN

Windows 10, Ray 1.2.0.
config={
    "env_config": current_config['env_params'],  # config to pass to env class
    "num_gpus": 0.0,
    "num_workers": args.num_workers,
    "env": AlphaZeroWrapper,
    "framework": "torch",
    "output_compress_columns": ["obs", "new_obs", "reward", "info"],
    "output": None,
    "explore": True,
    "ranked_rewards": {
        "enable": True,
    },
    "model": {
        "custom_model": "dense_model",
    }, 
}

**Comment by mehes-kth** [comment]
@KiborgBBK 

This AlphaZero implementation doesn't directly use the `observation` input parameter,
instead it keeps its own copy of the environment and computes observations "on-demand"
as it explores and settles on the best course of action.  The environment state is kept in
the `user_data` field(s) of the `episodes` parameter to to the policy's `compute_actions`
method (alternatively, a single `episode`, if `compute_single_action` is used).

Unfortunately, `trainer.compute_action` does not handle `episodes`, but either `tune.run`,
or `agent.evaluate` would; so, depending on your use case, you _could_ use one of those.

If you do want to "single step" the trained policy, you'll have to use the policy directly
(i.e. NOT through the trainer/agent) **and** will also need to set up an `episode` instance.

The following hack seems to work:
```python
from ray import rllib, tune
from ray.rllib.contrib.alpha_zero.core.alpha_zero_trainer import AlphaZeroTrainer
from ray.rllib.policy.sample_batch import DEFAULT_POLICY_ID
from ray.rllib.policy.policy_map import PolicyMap
from ray.rllib.evaluation.episode import MultiAgentEpisode

# checkpoint_path = analysis.get_last_checkpoint() or args.checkpoint

agent = AlphaZeroTrainer(env=CartPole, config=config)
agent.restore(checkpoint_path)
policy = agent.get_policy(DEFAULT_POLICY_ID)

env = CartPole()
obs = env.reset()

episode = MultiAgentEpisode(
    PolicyMap(0,0),
    lambda _, __: DEFAULT_POLICY_ID,
    lambda: None,
    lambda _: None,
    0,
)

episode.user_data['initial_state'] = env.get_state()

done = False

while not done:
    action, _, _ = policy.compute_single_action(obs, episode=episode)
    print(action)
    obs, reward, done, _ = env.step(action)
    print(obs, reward)
    episode.length += 1

assert reward == episode.length
```

I'm fairly convinced that something similar could be implemented in
`AlphaZeroTrainer.compute_single_action(...)`, say, by making use of
 the `info: EnvInfoDict` parameter to pass the initial `env` state.

@Coac  @jbsevestre
What do you think?

**Comment by mehes-kth** [comment]
@polyzer 
That  `ValueError: probabilities contain NaN` error is due to a division by `0` right here:

https://github.com/ray-project/ray/blob/7916500c43de46721c51e6b95fb51cfa2c6078ba/rllib/contrib/alpha_zero/core/mcts.py#L140

The reason all `child_number_visits` are `0` is that the children of a "done" node are never expanded.
On the other hand, the policy should never encounter such a node **IF** the AlphaZero implementation's
internal environment is "in sync" with the real environment, which _SHOULD_ be the case if and when
the `env.get_state` and `env.set_state` work as expected.

I hit this exact error, because my environment implicitly included another player  making random moves,
but I forgot to include that player's RNG state in my `env_state`. Once I fixed that, the error disappeared.
I hope fhis helps...

**Comment by timurcarstensen** [comment]
@andras-kth 
> I hit this exact error, because my environment implicitly included another player making random moves, but I forgot to include that player's RNG state in my `env_state`. Once I fixed that, the error disappeared. I hope fhis helps...

I'm running into the exact same issue but cannot figure out how to fix the synchronisation issue. Could you possibly elaborate on how you fixed your particular problem? :)

**Comment by andras-kth** [comment]
@timurcarstensen 

It's the _principle_ that's important, not the exact details of any particular case.
The point is that at all internal state in the environment that may affect the trajectory
*MUST* be saved and restored by `.get_state` and `.set_state` to guarantee that
the evolution of the environment restored from a "snapshot" is indistinguishable
from the evolution of the environment at the time said snapshot was taken.

For relatively simple environments, this may be easiest to achieve by returning
and reinstating a deep copy of `self` (or an embedded environment), which is the
approach taken by the sample [Cartpole adaptation](https://github.com/ray-project/ray/blob/master/rllib/contrib/alpha_zero/environments/cartpole.py#L43-L50).

For complex environments, keeping numerous deep copies of the environment around
for AlphaZero's tree search could become quite costly very quickly; so, picking just enough
internal state to guarantee the "indistiguishability" (or "restartability") property makes sense.
That `ValueError` indicates that the saved/restored state information is *not* sufficient.
Something in the environment not captured in the state influences the state evolution,
hence stepping forward from the "real" environment at the time the snapshot was taken
will differ/diverge from the trajectory the environment restored from snapshot follows.

I don't know if this helps, as I'm guessing this much you may have understood already. :smirk: 

If you need help, you should probably share the details of _your_ case,
since that's the one that doesn't seem to work.
