### ISSUE TITLE
MAC Mojave OS, File descriptor limit 2560 is too low for production servers and may result in connection errors. 

### ISSUE THREAD

**Issue by yywangvr** [ray-project/ray#14507]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version:  1.2.0
Python version: 3.7.10

### Reproduction (REQUIRED)

```python

In [1]: import ray

In [2]: ray.init()
File descriptor limit 2560 is too low for production servers and may result in connection errors. At least 8192 is recommended. --- Fix with 'ulimit -n 8192'
2021-03-05 18:55:06,750	INFO services.py:1174 -- View the Ray dashboard at http://127.0.0.1:8265
Out[2]: 
{'node_ip_address': '192.168.43.42',
 'raylet_ip_address': '192.168.43.42',
 'redis_address': '192.168.43.42:53487',
 'object_store_address': '/tmp/ray/session_2021-03-05_18-55-06_102502_36950/sockets/plasma_store',
 'raylet_socket_name': '/tmp/ray/session_2021-03-05_18-55-06_102502_36950/sockets/raylet',
 'webui_url': '127.0.0.1:8265',
 'session_dir': '/tmp/ray/session_2021-03-05_18-55-06_102502_36950',
 'metrics_export_port': 63568,
 'node_id': '80533a2ed6f7b1fa83b81184798c49a1b0c384e06c170b3f25d61193'}
```

Note that I input the 
```bash
ulimit -n 8192
```
which did not make any changes...

I get the error what I start to run ray.init(). could you explain me how to fix it?  I am using Mac system.
Thank you.

**Comment by yywangvr** [comment]
I finally find a solution for Mac user, 

```sh
# before starting the ipython,  type the following line:
ulimit -Sn 8192
#and it works. Now the soft limit is 8192.. 
```

it should be fixed through the above mentioned  code.

**Comment by rkooo567** [comment]
Hi, @yywangvr! I think this might also work; 

```
ulimit -n 8192 ipython
```

Also the log is a warning, and it is unlikely you will see an issue if you use ray within an ipython. This becomes more important when you use clusters (because ray components have many connections from other ray components). It is non-trivial to permanently solve the problem because this means we should drastically reduce connection across nodes in the cluster (which might require huge architectural changes).

**Comment by yywangvr** [comment]
Thanks @rkooo567, it solved my problem:)
