### ISSUE TITLE
Assertion Error for Ray Tune Example Code

### ISSUE THREAD

**Issue by RuofanKong** [ray-project/ray#1475]
I tried the example code from Ray Tune: http://ray.readthedocs.io/en/latest/tune.html, and this is the code copied from the page:

```
import ray
from ray.tune import register_trainable, grid_search, run_experiments

def my_func(config, reporter):
    import time, numpy as np
    i = 0
    while True:
        reporter(timesteps_total=i, mean_accuracy=i ** config["alpha"])
        i += config["beta"]
        time.sleep(.01)

register_trainable("my_func", my_func)

ray.init()
run_experiments({
    "my_experiment": {
        "run": "my_func",
        "resources": { "cpu": 1, "gpu": 0 },
        "stop": { "mean_accuracy": 100 },
        "config": {
            "alpha": grid_search([0.2, 0.4, 0.6]),
            "beta": grid_search([1, 2]),
        },
    }
})
```
When running the code, I got the assertion error `AssertionError: Perhaps you called ray.init twice by accident?`. I wonder what's going wrong there or I missed something.

P. S The code was running with Ray 0.3.0 and Python 3.5.2 on the MacOS Sierra 10.12.6.

**Comment by ericl** [comment]
Hey @RuofanKong, you can either remove the ray.init() or use the master version of Ray. In master, we moved ray.init() out of run_experiments() to allow for greater control.

Unfortunately the online docs seem to point to master instead of 0.3.0 by default (http://ray.readthedocs.io/en/ray-0.3.0/rllib.html), let me see if we can fix that.

**Comment by RuofanKong** [comment]
Hi @ericl, Thanks for looking at it! Yes, removing `ray.init()` fixes the issue :)
