### ISSUE TITLE
[tune] Issue on page /tune/tutorials/tune-advanced-tutorial.html

### ISSUE THREAD

**Issue by evdcush** [ray-project/ray#14822]
### Describe your feature request
Thanks for providing lots of examples for new users!

I've been having issues with one of the tutorials, the [Guide to Population Based Training (PBT)](https://docs.ray.io/en/master/tune/tutorials/tune-advanced-tutorial.html).

It feels like there is a good amount of context missing from the tutorial.

As a new user, I find myself spending time browsing the ray repository looking for this `ray/tune/examples/mnist_pytorch.py` that was referenced, rather than learning about Ray Tune or PBT.

I think all tutorials should be self-contained, and not rely on any code that isn't explicitly provided somewhere in the tutorial. Or, at least, there should be clear links to relevant borrowed code, rather than plaintext relative paths to docs (and the docs then point to another file in the git repo).

Might be a RTFM thing here, but the usefulness or signal of this tutorial is obfuscated by implicit dependencies to unknown files. I'd rather learn about Ray Tune and PBT than dig through the source docs, and connect the dots for the author.

I've noticed this is maybe a consistent anti-feature of Ray Docs' tutorials; the PyTorch ["Hyperparameter tuning with Ray Tune"](https://pytorch.org/tutorials/beginner/hyperparameter_tuning_tutorial.html) is also confusingly structured, focusing on snippets of code that haven't been defined beforehand, then suddenly dumping the entire code block that you now need to cross-reference with the comments from the earlier undefined snippets. It seems like there is a lot of unnecessary thrashing going on here with the tutorials, which are the entrypoint for new users.
Ray Tune has been frustrating to learn so far.

I'd really like to see the tutorials structured in a manner where you continue building up code and concepts, such as the ["What is torch.nn Really?"](https://pytorch.org/tutorials/beginner/nn_tutorial.html) tutorial, or the ["Train a Mario-playing RL Agent"](https://pytorch.org/tutorials/intermediate/mario_rl_tutorial.html) tutorial.

Nonetheless, I feel I have learned a lot reading through each of the tutorials. Looking forward to learning more about Ray Tune, thank you!

**Comment by krfricke** [comment]
Hi @evdcush, thanks for the feedback. This is really valuable to us, as we really want to make sure that our documentation is great and helps users get familiar with our tools, rather than confuse them.

I totally see your points for both tutorials. I think the first tutorial would benefit from a general overhaul. The second one (hosted on pytorch tutorials) is not as straightforward to revamp - we wanted to be as close as possible to the original pytorch example, but we need to wrap most of the code blocks in functions (the tutorial source file is a self-contained runnable python script). I think a good idea might be to add some comments to the decoupled code-blocks to give more context where they will be placed.

Again, thanks for the feedback!

**Comment by evdcush** [comment]
Hi @krfricke, thank you for your quick response and consideration!

I understand your points regarding keeping things as close as possible to the pytorch example; that makes sense especially since you just want to show how to use Ray Tune in pytorch and not how to use pytorch.

I'm glad to hear that PBT tutorial may get a cleanup. And if I find a simpler example I may make a MR.

Thank you!
