### ISSUE TITLE
Wrong implementation in CQL? [rllib]

### ISSUE THREAD

**Issue by syuntoku14** [ray-project/ray#15110]
### What is the problem?

Wrong implementation in CQL? 
https://github.com/ray-project/ray/blob/e0ed549006a25523b4fdbb3df3e289544114527b/rllib/agents/cql/cql_torch_policy.py#L186

The random density in this line should be the logp of the random action.
So I think it should be modified as:
```
random_density = np.log(0.5**curr_actions.shape[-1])
-> random_density = np.log(0.5**rand_actions.shape[-1])
```

**Comment by mvindiola1** [comment]
@syuntoku14 
The name of the variable is misleading but the change you proposed will not make any difference in the performance of the CQL. curr_actions.shape[-1] and rand_actions.shape[-1] will be exactly the same because that is just the number of actions that can be taken from the environment.

There is a legitimate in CQL right now that I will post in a seperate comment.

**Comment by mvindiola1** [comment]
CQL as it exists in master right now is not training because no data is being saved in the replay buffer. 

This is coming from here
https://github.com/ray-project/ray/blob/64cc092959264cea42099690f13eceb6036e34d8/rllib/agents/cql/cql.py#L63-L71

https://github.com/ray-project/ray/blob/64cc092959264cea42099690f13eceb6036e34d8/rllib/agents/cql/cql.py#L98-L100

There are a couple other little things too:
1.)  This comment is literally the exact opposite. There is a torch implementation but not a tf one
https://github.com/ray-project/ray/blob/64cc092959264cea42099690f13eceb6036e34d8/rllib/agents/cql/tests/test_cql.py#L30-L32
2.) There is no learn_on_batch in the CQL default config so a user cannot add it to config to use one.
https://github.com/ray-project/ray/blob/64cc092959264cea42099690f13eceb6036e34d8/rllib/agents/cql/cql.py#L113

**Comment by syuntoku14** [comment]
> curr_actions.shape[-1] and rand_actions.shape[-1] will be exactly the same 
I assumed they are different but I understand that they are the same as you explained. Thank you for the response!
