### ISSUE TITLE
[sgd] LightningOperator help needed

### ISSUE THREAD

**Issue by malloc-naski** [ray-project/ray#15291]
Hello, I'm trying to pretrain a BERT model on multiple nodes with RaySGD. This is [the script](https://github.com/NVIDIA/NeMo/blob/1b11678b2fed258715df09486ebf71a837d18464/examples/nlp/language_modeling/bert_pretraining.py) that I've been using for training on one node. As stated in [docs](https://docs.ray.io/en/master/raysgd/raysgd_ptl.html#quick-start), I should be able to convert the LightningModule to a Ray SGD compatible LightningOperator. Yet, the BERTLMModel in NeMo inherits from ModelPT, which inherits from both LightningModule and Model. Should I implement that myself?

**Comment by richardliaw** [comment]
@amogkam is the right person to help here

**Comment by amogkam** [comment]
Hey @malloc-naski, I'd actually recommend you try out the [Ray Lightning](https://github.com/ray-project/ray_lightning) library which implements a RayPlugin for distributed Pytorch Lightning on Ray. This should be a lot easier than the RaySGD LightningOperator since you would only have to make a change to the plugin that you are using.

**Comment by malloc-naski** [comment]
Great, thank you! @amogkam
