### ISSUE TITLE
ray.init address should take gcs address instead of redis address

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#15354]
In order to remove redis, users should provide gcs_server's address instead of redis's address.

Note: This depends on all other uses of redis clients to be removed first.

**Comment by WangTaoTheTonic** [comment]
ray.init will use gcs client in runtime, which will get gcs server address from redis.
I'm afraid that it's hard to use gcs address directly because its port is chosen randomly for now.

Btw in current implementation, it is **implicit** that gcs client will always get available gcs server address from redis.

**Comment by wuisawesome** [comment]
Agreed, this is likely going to involve an API change (like doing `ray.init(address="gcs_server_address")`). I'll eventually make an RFC and we can try to make the migration as smooth as possible.

**Comment by richardliaw** [comment]
Closing this due to stale; if is an issue let's open a new one.
