### ISSUE TITLE
Use rainbow to train a single agent

### ISSUE THREAD

**Issue by Yuanzhuo-Liu** [ray-project/ray#15450]
I don't know what's wrong, could you look over it for me?
![sendpix1](https://user-images.githubusercontent.com/68255669/115675494-a229eb00-a31c-11eb-9708-7fdfbc10d33f.jpg)
![sendpix2](https://user-images.githubusercontent.com/68255669/115675512-a5bd7200-a31c-11eb-93fe-346646336b70.jpg)

**Comment by mvindiola1** [comment]
Hi @Yuanzhuo-Liu,

By the time it reaches base_env, rllib expects all environments to act as a multiagent environment. Single agent environments are treated as a multiagent environment with just one agent. Normally rllib will do this wrapping automatically for you but in this case SumoEnvironment already inherits from MultiagentEnv so it does not think it needs to.

What that means practically is that the call to reset is expecting a dictionary of observations (one per agent in the environment) but since you instantiated SumoEnvironment with single_agent=True it is not returning a dictionary but just the unwrapped  numpy array instead.

You should be able to fix this by changing `single_agent=True` to `single_agent=False`

**Comment by Yuanzhuo-Liu** [comment]
> Hi @Yuanzhuo-Liu,
> 
> By the time it reaches base_env, rllib expects all environments to act as a multiagent environment. Single agent environments are treated as a multiagent environment with just one agent. Normally rllib will do this wrapping automatically for you but in this case SumoEnvironment already inherits from MultiagentEnv so it does not think it needs to.
> 
> What that means practically is that the call to reset is expecting a dictionary of observations (one per agent in the environment) but since you instantiated SumoEnvironment with single_agent=True it is not returning a dictionary but just the unwrapped numpy array instead.
> 
> You should be able to fix this by changing `single_agent=True` to `single_agent=False`

Hi ! Thanks! It works.
