### ISSUE TITLE
secure dashboard using https

### ISSUE THREAD

**Issue by andrew-rosenfeld-ts** [ray-project/ray#15548]
It would be nice to have the Ray dashboard support some sort of security and authentication, e.g. like Jupyter notebooks do.

Some organisations require even internal web traffic to be over https, so to review the dashboard for a running cluster from another machine, this would be required.

**Comment by hegdeashwin** [comment]
Team, Let me check this out.

**Comment by andrew-rosenfeld-ts** [comment]
I'm still interested in this.

**Comment by pcmoritz** [comment]
It isn't too hard to run the dashboard in this manner yourself without having to change the source code of Ray -- just pass the traffic through an https proxy that supports the required authentication scheme.

The details depend on the infrastructure (and authentication) you are using. For example Caddy is a good solution for SSL in order to get https if you are running on bare metal servers (it has an integration that allows you to get certificates from Let's Encrypt). If you are running in the cloud, using a tool like ALB is a good choice and Amazon will automatically provide the certificates for you. On kubernetes, there are a lot of different choices for ingress controllers that allow you to get https easily (in that case you need to again manage your certificates by yourself) and expose the dashboard through them. Setting up a simple authentication proxy is also not too hard, or you can use the https proxy and a simple token based authentication.

Again there are many different options and which is the best for you depends a lot on your setup and infrastructure (certificate management, proxy/ingress, authentication), so it doesn't make sense to integrate this into Ray out of the box.
