### ISSUE TITLE
Reserving more gpus then I have let the code not finish executing even when sequential processing would be possible. [ray] 

### ISSUE THREAD

**Issue by RaymondKoopmanschap** [ray-project/ray#15594]
### What is the problem?
When creating multiple actors. Say two, and I reserve 1 GPU for both of them and only have 1 GPU in my machine, the code hangs (i.e. doesn't finish executing) when I want to ray.get the results of the second item. 

- Python version == 3.8.8
- Ray version == 1.3.0
- OS == Windows (also tested on Linux, and this gives the same issue)
- I have 1 GPU in my machine, a RTX 2060. 

### Reproduction (REQUIRED)
I have used the exact same code example from: https://docs.ray.io/en/master/walkthrough.html#remote-classes-actors for clarity. The only thing I changed is that I gave ray.remote an argument with num_gpus=1.
Note that the code properly gives a warning saying 
```
WARNING worker.py:1115 -- The actor or task with ID ffffffffffffffff942e3404ccaf20b967ce35c601000000 cannot be scheduled right now. It requires {CPU: 1.000000}, {GPU: 1.000000} for placement, but this node only has remaining {11.000000/12.000000 CPU, 4.498190 GiB/4.498190 GiB memory, 0.000000/1.000000 GPU, 2.249095 GiB/2.249095 GiB object_store_memory, 1.000000/1.000000 node:192.168.178.28}
. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
```
However, after this warning the code didn't finish executing the script. It hangs forever and never finishes. 
What I expect to happen is either
- The code gives an error and say this isn't possible
- It is possible and ray executes the processes sequentially (and still gives a warning) and at some point finishes executing the script. 

```Python
@ray.remote(num_gpus=1)
class Counter(object):
    def __init__(self):
        self.value = 0

    def increment(self):
        self.value += 1
        return self.value

counter1 = Counter.remote()
counter2 = Counter.remote()

num1 = counter1.increment.remote()
num2 = counter2.increment.remote()

print('test')
result1 = ray.get(num1)
print('test2')
result2 = ray.get(num2)  # the code gives a warning and hangs at this line
print(result1, result2)
```

Note that this order of the code also produces the same behavior
```Python
counter1 = Counter.remote()
num1 = counter1.increment.remote()
result1 = ray.get(num1)

counter2 = Counter.remote()
num2 = counter2.increment.remote()
result2 = ray.get(num2)
print(result1, result2)
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue occurs with the latest official release (Ray 1.3.0)

**Comment by mvindiola1** [comment]
Hi @RaymondKoopmanschap,

The issue you are running into is with scheduling counter2. In this example ray has 1 gpu available and 2 actors that each specify a requirement of  1 gpu. counter1 is created first and claims the gpu so when counter 2 is created there is no gpu available. The scheduler will not schedule tasks for that actor until counter1 has released it. If you look at the code flow it looks like sequential processing but it is not you have two concurrent actors with resource contention on the gpus.

This sample code will run as you expected:
```python
@ray.remote(num_gpus=1)
class Counter(object):
    def __init__(self):
        self.value = 0

    def increment(self):
        self.value += 1
        return self.value

counter1 = Counter.remote()
counter2 = Counter.remote() # If you run it in an interpreter you will see that the warning is printed after this line
num1 = counter1.increment.remote()
num2 = counter2.increment.remote()

print('test')
result1 = ray.get(num1)
counter1.__ray_terminate__.remote() # This can occur anywhere before  ray.get(num2)  
print('test2')
result2 = ray.get(num2)  
print(result1, result2)
```

**Comment by RaymondKoopmanschap** [comment]
Thanks for the answer and for the solution with ray_terminate. This makes sense to me. Although I still find it weird that the program basically gets in an infinite loop without finishing. It seems the second Actor is waiting for the first one to be terminated which never happens.

**Comment by mvindiola1** [comment]
@RaymondKoopmanschap,

Yes it is unintuitive. It is not an infinite loop though it is more like resource contention on a semaphore. You have defined a limited amount of a resource (num_gpus=1) and have asked for more of that resource than is available (two classes that each want to use that resource) so the second one has to wait until the resource is released before it can run.

In ray the Actors (python classes) specify their requirements so the gpu is pinned to the Counter object and will not be released until that object is destroyed. There are two ways to do that. One is like the example above where we explicitly terminated the actor. You could probably also do "del counter1 and I would bet that would work too but I have not tested it. The other way an object would be destroyed is if the reference count on the object is 0 then it would eventually be garbage collected. Here is an example where that happens by defining a counter within the scope of a function so after that function returns the counter actor will be cleaned up. It of course could only count things within one call of that method.

```python
@ray.remote(num_gpus=1)
class Counter(object):
    def __init__(self):
        self.value = 0
    def increment(self):
        self.value += 1
        return self.value
    
def get_num():
    counter=Counter.remote()
    return counter.increment.remote()
num1 = get_num()
num2 =  get_num()
print('test')
result1 = ray.get(num1)
print('test2')
result2 = ray.get(num2)
print(result1, result2)
```
I tried to find a way to define ray resource requirements on a class method rather than the class itself. A case where only one method in a class requires a gpu so we only specify that it is necessary if that method is invoked. That would solve your issue here. I did not find a way to do that but @richard4912  or @simon-mo would know better if that was possible.

**Comment by simon-mo** [comment]
The API was designed this way (not throwing and error on pending actors) because the cluster is expected to autoscale in common production scenarios. If you want the erroring behavior, we recommend:
- For a single actor, define an empty `def ready(self): return True` method and call `ray.wait([actor.ready.remote()], timeout=...)` to make sure the actor was scheduled given some time
- For group of actors, use [placement group](https://docs.ray.io/en/master/placement-group.html) to reserve a group of resource and schedule them all at once.

**Comment by RaymondKoopmanschap** [comment]
Thanks a lot for the elaborate answers and for the ```ray.wait()```  recommendation. I now understand much better what happens. I can confirm that ```del counter1``` also works.
