### ISSUE TITLE
Ray stop kills all jupyter related processes

### ISSUE THREAD

**Issue by finity84** [ray-project/ray#1562]
`ray stop` currently kills all jupyter related processes started by user, not just the one started by Ray.

**https://github.com/ray-project/ray/blob/ray-0.3.1/python/ray/scripts/scripts.py**
``` 
   # Find the PID of the jupyter process and kill it.
    subprocess.call(["kill $(ps aux | grep jupyter | grep -v grep | "
                     "awk '{ print $2 }') 2> /dev/null"], shell=True)
```

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Debian
- **Ray installed from (source or binary)**: Binary
- **Ray version**: 0.3.1
- **Python version**: 3.6
- **Exact command to reproduce**: ray stop

**Comment by robertnishihara** [comment]
Good point, this is a problem. The relevant line is

https://github.com/ray-project/ray/blob/ab37d0cd1964581e55122ac13bbdf950fad77fce/python/ray/scripts/scripts.py#L241-L242

There's probably a better way to do it, but one option could be to pass in a dummy argument to the `jupyter notebook` command so that we can grep for it and filter out other jupyter notebooks that weren't started by Ray.

**Comment by richardliaw** [comment]
I think this should be fixed! Please reopen if this is still an issue.
