### ISSUE TITLE
[serve] Support prev_version in .deploy()

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#15642]
Reject other versions to avoid concurrency control issues.

**Comment by edoakes** [comment]
FYI @simjay

**Comment by simjay** [comment]
Hey @edoakes 

a few questions

1. According to the doc you shared with me (https://docs.google.com/document/d/1MqAmWKC6Ev2jKnxoPn93PJ_Ya53k_tJsChJs5zJORd0), looks like you wanted to input `prev_version` to be an argument for `options` method rather than `deploy` method (from `api.py`). I'm a bit concerned as `options` method give you an `Deployment` object and this might lead us to a race-condition problem. If `options` method is always used in this way: `MyService.options(version="new_git_sha", prev_version="old_git_sha").deploy()` , then we might not have a race condition but we cannot always assume that users will not use `options` method to simply create another `Deployment` object. If that is the case, and if we check if `prev_version` matches with the current `version` of Deployment when we invoke `options` method, two different process might legally call `deploy` method without a problem -> causing a race condition. Am I missing something here?

2. I remember at some point you mentioned that you will work on the legacy structure (backend and endpoint). Will you be removing `backend` and `endpoint` reference? If yes, will you change ServeController as well?

Thanks in advance

**Comment by simjay** [comment]
@edoakes Made a PR here and it's my PR for Ray repo so please let me know if I am doing smth wrong! https://github.com/ray-project/ray/pull/15821

**Comment by simjay** [comment]
@edoakes A quick question on one possible edge case: How do you wanna handle if user specified a `prev_version` but there is no deployment made yet (with controller) for that deployment object? Possible actions we could do are

1. Raise an error (since it does not match with existing version, which is None) -> This may make `deploy` method not idempotent
2. Ignore and deploy, as it won't matter as there is no deployment before -> This may create another case of race condition.

What do you think?

**Comment by edoakes** [comment]
Semantically it makes most sense to raise an error. This would catch a potential race condition where you think you're deploying an incremental version but another client deleted the deployment.

**Comment by simjay** [comment]
Awesome. Thank you for the confirmation and I agree with your logic. Will make the corresponding changes!

**Comment by simjay** [comment]
@edoakes Should we close this?

**Comment by edoakes** [comment]
Oops meant to tag it on the PR. Closed by https://github.com/ray-project/ray/pull/15821
