### ISSUE TITLE
[core] Is it possible that workers can use python packages that is only in the driver?

### ISSUE THREAD

**Issue by getElementsByName** [ray-project/ray#15665]
## example

```python
import local_module

@ray.remote()
def remote_task():
    local_module....
```

**Comment by simon-mo** [comment]
Hi @getElementsByName, thanks for posting this issue. Can you help us understand the use case better? Is it because the workers doesn't have the same files and you have trouble putting the module there? 

There are progress towards helping address this kind of issue, please take a look and comment on this RFC: https://github.com/ray-project/ray/issues/14019

**Comment by getElementsByName** [comment]
@simon-mo
- thanks for your help.
- The issue https://github.com/ray-project/ray/issues/14019 is exactly what I asks
