### ISSUE TITLE
[RFC] Namespace

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#15684]
# Motivation

See #15557. 

# API

The initially proposed API provides for isolation of named actors only. To create a job in a namespace:

```
ray.client().namespace("my-namespace")
```

If no namespace is provided, it is equivalent to

```
ray.client().namespace(str(uuid.uuid4()))
```

**Note: this breaks backwards compatibility for named actors.**

Using the `ray.init` api:

```
ray.init(namespace=str(uuid.uuid4())
```

## Cross namespace communication.

The interface for cross-namespace communication is far more controversial and out of scope for this API change. 

For now, there we won't support this feature. Jobs should be placed in the same namespace if they need to communicate.

# Proposed Implementation

The proposed implementation is to make a namespace a property of a job and actor. We will propagate the namespace via the job config. We'll also store the namespace with the actor for ease of lookup.

**Comment by wuisawesome** [comment]
cc @edoakes

**Comment by rkooo567** [comment]
Why don't we just use the global default namespace (constant value) if it is not specified? In this case, we can keep the backward compatibility

**Comment by rkooo567** [comment]
Hmm but other multi-tenant systems like Linux or Kubernetes doesn't create namespaces dynamically right? It is usually sys_admins who have the access to create new namespaces, and applications are just connecting to existing ones instead of dynamically creating ones on the fly. Is our concept of namespace different from those systems, and that's why it is better for multi-tenant use cases?
