### ISSUE TITLE
[rllib] ValueNetworkMixin is not using value baseline when use_gae is set to False

### ISSUE THREAD

**Issue by roireshef** [ray-project/ray#15715]
### What is the problem?
ValueNetworkMixin is also being used by A3C (although it is implemented inside the PPO file). When initialized, ValueNetworkMixin looks at the config dictionary for _use_gae_ and if it is set to False, it will use 0.0 as the returned value. The result is invalid in some cases, specifically when one wouldn't like to use GAE but still decides to use a critic. Since all the following use ValueNetworkMixin, this applies to them as well: A3C  MAML, MARWIL, PPO, APPO

I propose the following changes:
1. ValueNetworkMixin.value() implementation based on _use_critic_ and not _use_gae_
2. Move ValueNetworkMixin from _ppo_torch_policy.py_ to its parent _torch_policy.py_ so it is properly shared between different algo without referencing one another's files.
3. Validation that always _use_critic_ >= _use_gae_

*Ray version and other system information (Python version, TensorFlow version, OS):*
1.3.0 and latest

**Comment by mvindiola1** [comment]
Hi @roireshef,

I am not seeing why change 1 is necessary. Do you mind elaborating on your thought process here.

I might be missing something but as I was looking through the code the only place I saw that was using it was here: https://github.com/ray-project/ray/blob/e973b726c2e4039bd5a35ecfffad5028a15cdfee/rllib/evaluation/postprocessing.py#L124

I don't think changing it from `use_gae` to `use_critic` will change anything but it will add unnecessary passes through the value network.

**Comment by mvindiola1** [comment]
@sven1977 I had a comment here but accidentally deleted it on my phone. At first I thought it had already been fixed too but as I was thinking about it more I think there might still be an issue. 

The PR you mentioned made sure that the loss was including the critic but here I think @roireshef identified an issue with computing the "reward" for a sample batch when the last timestep does not align with an episode done.

Right now line 124 in the snippet below will return 0.0 when use_critic == True and use_gae == False but I think in those cases it should instead use the value function estimate. 

https://github.com/ray-project/ray/blob/4795048f1b3779658e8b0ffaa05b1eb61914bc60/rllib/evaluation/postprocessing.py#L113-L126

For example  in A3C it used to do this but the behavior changed when you switched it to use the PPO ValueNetworkMixin to fix "[RLlib] Issue 9071 A3C w/ RNN not working due to VF assuming no RNN."

https://github.com/ray-project/ray/commit/2e3655e8a9b1e37fa6e29f11db02a6b53cfb5928#diff-d8628d52537ed3efcb3d82824ac189f9dd5051cc72d7f528b5bf0a2edbfad415L72

**Comment by roireshef** [comment]
> Right now line 124 in the snippet below will return 0.0 when use_critic == True and use_gae == False but I think in those cases it should instead use the value function estimate.

@mvindiola1 I'm not fluent in the history of changes here, but yes, I agree this is the expected behavior, and that current behavior is different. Thanks for the clarification.

**Comment by roireshef** [comment]
> Hey @roireshef , I think this was actually fixed in a PR I merged yesterday, but I'll double check now ...
> #15610

@sven1977 I only skimmed through #15610, but it seems it only changes PPO-specific code. The issue I'm pointing to is actually an unexpected behavior of ValueNetworkMixin, which is shared across different algorithms than PPO. ValueNetworkMixin can be implemented so that it supports **using critic without GAE**, which is the essence of proposed change in my PR.
