### ISSUE TITLE
[object spilling] spill work will block by `CoreWorkerPlasmaStoreProvider::WarmupStore` in `CoreWorker` construct function

### ISSUE THREAD

**Issue by Catch-Bull** [ray-project/ray#15940]
### What is the problem?

It seem like `worker_pool.maximum_startup_concurrency`  limits the number of  task workers and I/O workers at the same time. When `worker_pool.maximum_startup_concurrency=1`, and `raylet` construct a new `CoreWorker`，it will store a little data in plasma store for warmup. In this process, will trigger object spilling and need a spill worker，but unfortunately, we can't start one, because we are starting a task worker and `worker_pool.maximum_startup_concurrency=1`. Finally `raylet` will kill this task worker (after 30 seconds) and start a spill task to finish this job.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

- Ray version and other system information:
    - macos: 11.3.1
    - python: 3.6.13
    - ray version: opensource master (dde7cbd2885765a9fc61b05daca4f6f9973aed10)

- We can modify the pytest case `python/ray/tests/test_object_spilling.py::test_spill_during_get` to easily reproduce it:

```python
@pytest.mark.skipif(
    platform.system() == "Windows", reason="Failing on Windows.")
def test_spill_during_get(object_spilling_config, shutdown_only):
    object_spilling_config, _ = object_spilling_config
    address = ray.init(
        num_cpus=1,
        object_store_memory=100 * 1024 * 1024,
        _system_config={
            "automatic_object_spilling_enabled": True,
            "object_store_full_delay_ms": 100,
            "max_io_workers": 1,
            "object_spilling_config": object_spilling_config,
            "min_spilling_size": 0,
        },
    )

    @ray.remote(num_cpus=0)
    def f():
        return np.zeros(10 * 1024 * 1024)

    ids = []
    for i in range(10):
        x = f.remote()
        print(i, x)
        ids.append(x)

    # Concurrent gets, which require restoring from external storage, while
    # objects are being created.
    for x in ids:
        print(ray.get(x).shape)
    assert_no_thrashing(address["redis_address"])
```

- what we change:

```bash
diff --git a/python/ray/tests/test_object_spilling.py b/python/ray/tests/test_object_spilling.py
index a1dbc31ad0..f546e12b5d 100644
--- a/python/ray/tests/test_object_spilling.py
+++ b/python/ray/tests/test_object_spilling.py
@@ -350,7 +350,7 @@ def test_spill_stats(object_spilling_config, shutdown_only):
 def test_spill_during_get(object_spilling_config, shutdown_only):
     object_spilling_config, _ = object_spilling_config
     address = ray.init(
-        num_cpus=4,
+        num_cpus=1,
         object_store_memory=100 * 1024 * 1024,
         _system_config={
             "automatic_object_spilling_enabled": True,
@@ -361,7 +361,7 @@ def test_spill_during_get(object_spilling_config, shutdown_only):
         },
     )
 
-    @ray.remote
+    @ray.remote(num_cpus=0)
     def f():
         return np.zeros(10 * 1024 * 1024)
```

- We use `pytest` to run it, here is result:
![image](https://user-images.githubusercontent.com/11995469/118957667-4aba8180-b993-11eb-847c-2097d56fbd57.png)

- We have some question：
    - why use `worker_pool.maximum_startup_concurrency >= {number of starting IO workers} + {number of starting task worker}`？ Maybe just assign an upper limit to each of them？
    - Why not use `NomalWorkerPool` and `IOWorkerPool` to manager task workers and io workers respectively ?.

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by Catch-Bull** [comment]
cc @kfstorm

**Comment by kfstorm** [comment]
The above test case is expected to finish within 10 seconds but actually finished in more than 30 seconds.

cc @rkooo567 @suquark @ericl

**Comment by rkooo567** [comment]
I have a couple question; 

- When's the case num_cpus=1 in ray cluster? I am asking it because it doesn't really make sense to me.
- Also why does warmup workload trigger object spilling? 

About questions;

> Why not use NomalWorkerPool and IOWorkerPool to manager task workers and io workers respectively ?.

I think there's no special reason here. When I first worked on it, it was written in this way, and I just followed it because I didn't want to spend time for refactoring it.  But it is welcomed to refactor them to different worker pool.

> why use worker_pool.maximum_startup_concurrency >= {number of starting IO workers} + {number of starting task worker}？ Maybe just assign an upper limit to each of them？

yeah this should work. Feel free to update it. The easiest solution is probably just to limit the max startup to 2?

**Comment by kfstorm** [comment]
> When's the case num_cpus=1 in ray cluster? I am asking it because it doesn't really make sense to me.

Internally we hardcode `maximum_startup_concurrency` to 1 to avoid too many idle workers. We use `num_cpus=1` to reproduce the issue with the community code. Anyway, I think setting `num_cpus` to 1 is a totally valid scenario. Do you assume all machines are multi-core nowadays?

> Also why does warmup workload trigger object spilling?

Because the warmup workload wants to put a temporary object into the plasma store, but the plasma store is almost full. So spilling is triggered. But the spill worker cannot be started due to the limit of `maximum_startup_concurrency==1` and the worker is hanging on warmup and is not considered as started by the worker pool.

**Comment by kfstorm** [comment]
I know this is an edge case. But the point is we shouldn't manage IO workers and normal workers in the same worker pool. We've already seen some bugs caused by this mixed management. See https://github.com/ray-project/ray/pull/14578.

If we go a bit more further, spill/restore/util workers are not even WORKERs.

**Comment by Catch-Bull** [comment]
> * Also why does warmup workload trigger object spilling?

My bad, object spilling not trigger by warmup but the second task's returning object. And `warmup` will block by object spilling.

**Comment by Catch-Bull** [comment]
> * When's the case num_cpus=1 in ray cluster? I am asking it because it doesn't really make sense to me.

This is just for the convenience of reproduction. 

Let's suppose:
- maximum_startup_concurrency < N < upper limit of workers
- N is the number of tasks, we will submit them at the same time.

In a short period, the number of starting workers will always be equal to `maximum_startup_concurrency`, during this time , the first spilling task will wait for 30 seconds(and suppose none of them finished `WarmupStore`).
