### ISSUE TITLE
Usage of ray.util.queue.Queue for data processing

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#16007]
Python: 3.7
Ray: 1.2

I want to use `Queue` to preprocess some data sequentially and in parallel. I implement it as follows:
```
import time
import ray
import numpy as np
from ray.util.queue import Queue


@ray.remote(num_cpus=0.0)
def process_func(x):
    time.sleep(0.5)
    return x + np.random.rand()


@ray.remote(num_cpus=0.0)
def parallel_process(queue):
    for i in range(50):
        while True:
            if queue.full():
                continue
            else:
                ref = process_func.remote(i)
                print(ref)
                queue.put_async(ref)
                break
    queue.put("done")


ray.init()
q = Queue(maxsize=10)
st_time = time.time()
parallel_process.remote(q)
data = []
while True:
    r = q.get()
    if r == "done":
        break
    else:
        data.append(r)
print(f"Queue Parallel:\n{data}\n{time.time() - st_time}s")

st_time = time.time()
data = []
for i in range(50):
    data.append(process_func._function(i))
print(f"For Loop:\n{data}\n{time.time() - st_time}s")
```
However, I get the following message:
```
RuntimeWarning: coroutine 'Queue.put_async' was never awaited
(pid=37563)   type=str,
(pid=37563) RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
I may use `Queue` in a wrong way. Or, is there a better way to implement the above function? The basic logic is that we continually issue remote functions and store the object refs in a queue. At the same time, we can fetch the results of finished remote functions.

Thanks for your help!

**Comment by rkooo567** [comment]
Hi, @llan-ml I couldn't reproduce the error message you specified when I ran it locally. Can you try ray 1.3 and see if it works?

**Comment by llan-ml** [comment]
Hi @rkooo567, I created a [notebook](https://colab.research.google.com/drive/1i0slcC9C_Rj8dyRPfVCzUHaGUNipOsde?usp=sharing) to reproduce it. We can see the warning message and that there is nothing in the list `data`.

I'm not familiar with `async`. It seems that we cannot use the `async`ed function alone and I use it in a wrong way.

**Comment by rkooo567** [comment]
> I'm not familiar with async. It seems that we cannot use the asynced function alone and I use it in a wrong way.

Yeah this is the problem. You cannot call `put_async` without `await` keyword, and you cannot use this from ray task which is not running in the async context. One of possibilities is to use async actor instead (which by default support `async def`). https://docs.ray.io/en/master/async_api.html#asyncio-concurrency-for-actors

**Comment by GoingMyWay** [comment]
Change `queue.put_async(ref)` to `queue.put(ref)`

**Comment by GoingMyWay** [comment]
@llan-ml, Heyyy. I misunderstood your question previously. As `put_async` is an async function, you should use it in a coroutine way.  Please use [async Actors](https://docs.ray.io/en/latest/ray-core/actors/async_api.html#defining-an-async-actor). I modified your code and put the runnable code below:

```python
import time
import asyncio

import ray
import numpy as np

from ray.util.queue import Queue

@ray.remote(num_cpus=0.0)
def process_func(x):
    time.sleep(0.5)
    return x + np.random.rand()


@ray.remote
class AsyncActor:
    async def run_concurrent(self, queue):
        objs = []
        for i in range(100):
            st = time.time()
            objs.append(queue.put_async(process_func.remote(i)))
            print(f'cost: {(time.time()-st):.2f}')
        await asyncio.wait(objs)  # NOTE: as queue.put_async are corountine objs, please await here
        # NOTE: equivalently or you can await the results in this way
        # for obj in objs:
        #     await obj
        return 'Get all data'

    def ready(self):
        # waiting for the ready of the actor
        return True


async def main(actor, queue):
    ray_results = await actor.run_concurrent.remote(queue)  # NOTE: as run_concurrent is corountine obj, please await
    print(f"Get: {ray_results}")


ray.init()
q = Queue(maxsize=1000)

actor = AsyncActor.remote()
print(ray.get(actor.ready.remote()))

st_time = time.time()

asyncio.run(main(actor, q))

data = []
print(f"Getting data")
while True:
    r = q.get()
    print(f"Getting data!!!!!!!!!!!!!")
    if q.size() == 0:
        print('done!')
        break
    else:
        print(f'get 1 sample')
        data.append(r)
print(f"queue.put_async, len(data): {len(data)}, data: {data}, \ntotal time cost: {time.time() - st_time}s")
```

Here, in the code, when running sequentially, it will take 50 seconds. Will async actor, it takes only ~13.5 seconds. I think this is what you want. 

See more comments in the code. I highly recommend learning [coroutines in Python](https://docs.python.org/3/library/asyncio-task.html). The merit of Ray can be leveraged by using coroutines.

@rkooo567, Heyyyyy. It seems docs of Ray is intended for experienced programmers. Examples in Ray are not easy to understand, say how to integrate Ray with coroutines in Python. Examples are not concrete. For experienced users, `await asyncio.sleep(1)` is easy to understand. For mediate-level programmers, it is not ready to understand. I appreciate your great work on developing Ray; that is all my humble suggestion.

**Comment by msingh00** [comment]
how would i start tasks without waiting?   what i would like to do is modify this example as a producer/consumer.   to that i would like to create n number of workers that read from the queue, and blocks while the queue is empty.  to that i need to be able to start the to tasks and not wait or block.   i dont see any examples on how to do this...

**Comment by movy** [comment]
Since this is pretty high on Google when searching for "ray queue async", I'll share my experience and solution. 

My goal was to implement async logger for `tune.Tuner.fit()` fn, as I run some extra computations upon logging and storing data in external DB, which can be slow at times, and I did not want slowing down the whole cluster by a non-async logging process.

After a very frustrating Saturday trying to implement this via ray.remote, ray.queue, async and threading actors etc -- literaly every single recipe from Ray docs, the best I could achieve with Ray was this error message:
`asyncio.run() cannot be called from a running event loop`

 Eventually I gave up and resorted to "vanilla" Python queue as described here: https://superfastpython.com/thread-queue/

Final solution is dead simple: 

```python
from queue import Queue
from threading import Thread

queue = Queue(maxsize=1000)

def post_to_db():
    while True:
        row_data = queue.get()
        if row_data["row_number"] == -1: 
            print("🏁 Stopped logging queue...")
            break
        if row_data["row_number"] > 0:
        . . . 

Thread(target=post_to_db, args=()).start()

def logging_callback():
    queue.put({row_data})
```

THIS IS IT. I have no clue why Ray made is so convoluted and lacking clear and working examples in their docs. Python is "slightly counter-intuitive" as it is (a quote from every single Python manual on Earth), but Ray really takes it up a notch, not sure why it has to be that complex. 

Couple extra notes:

- I'm using global `queue` and no arguments on consumer/producers as I see no point tossing global object between functions
- Best part -- you can call `Ray.remote()` functions from inside your threaded consumer (`post_to_db` in this case), with proper resource allocation and placement groups. It was the whole point of me taking on Ray queue path initially, as logging does some extra calculations on results and without proper resource allocation it was taking forever. 

Hope it saves time someone, cheers.
