### ISSUE TITLE
Ship remote function definitions lazily when they are first invoked.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1609]
We may want to ship remote function definitions when they are first invoked (as opposed to when they are first defined. This would help avoid problems like #1607.

This could also avoid shipping a ton of remote function definitions that are not used (e.g., because they are defined in a Python module which is imported by a user).

The main downside is that it increases latency for the first invocation.

cc @ludwigschmidt

**Comment by ludwigschmidt** [comment]
A few thoughts on this:

- From personal experience, Robert's point regarding slow `import` due to remote functions could become a serious usability problem. I remember similar issues from Julia where compiling packages on import was quite annoying because it led to slow program / notebook starts.

- I find it more intuitive to have some extra latency on the actual invocation. As a user, I know that data is being transferred over the network now. And probably my code takes some time anyway.

- Would lazy shipping also make the @remote annotation unnecessary? That would significantly simplify usability since I don't have to worry about annotating my functions any more (this is a nice feature of Pywren for me).

**Comment by robertnishihara** [comment]
Responding to your third point, I think we'd still need the decorator if we want to do invoke functions with `f.remote()`. We could add a `ray.submit(f)` function to the API which would avoid the decorator. I like it less (aesthetically), though it does have the advantage of allowing you to pass in other arguments (e.g., resource requirements) when the function is invoked as opposed to when it is defined (so they can differ between invocations).

**Comment by ludwigschmidt** [comment]
As a user who doesn't know what's going on under the hood, I prefer `ray.submit(f)` (or `ray.run(f)` or `ray.execute(f)`). It is more transparent to me because I know that `f` is still just the function I defined.

**Comment by ludwigschmidt** [comment]
Also, if `f.remote()` turns out to be the only thing that the decorator enables after lazy shipping, it might be good to clarify that in the documentation. It might also be good to make the decorator optional at this point.

**Comment by richardliaw** [comment]
```
@ray.remote
def f():
    return 1
```
and 
```
def f():
    return 1

f = ray.remote(f)
```
The above two are equivalent and currently work. @ludwigschmidt does the latter approach provide the semantics you were suggesting above?

Just as a note, often times I don't use the annotation, but it's helpful to have it for fast scripting.

**Comment by ludwigschmidt** [comment]
I forgot to comment on this earlier.

The latter approach does not quite have the semantics I had in mind because f is still a special object and not the function I initially defined. With the `ray.submit(f)` proposed by @robertnishihara , f can remain the "plain" Python function I define.
