### ISSUE TITLE
Replacing the default policy optimizer using PPOTorchPolicy.with_updates and PPOTrainer.with_updates does not work

### ISSUE THREAD

**Issue by a-python-script** [ray-project/ray#16159]
I am trying to replace the default Adam optimizer for my policy model with another optimizer from the torch library. I followed the tutorials on page https://docs.ray.io/en/latest/rllib-concepts.html#extending-existing-policies to do this. The following code I have: 

```
from ray.rllib.policy.policy import Policy
from ray.rllib.utils.typing import TrainerConfigDict, LocalOptimizer
from ray.rllib.agents.ppo import PPOTrainer
from ray.rllib.agents.ppo.ppo_torch_policy import PPOTorchPolicy
import ray

ray.init(ignore_reinit_error=True)

# Custom torch optimizer
def custom_optimizer(policy: Policy, config: TrainerConfigDict) -> LocalOptimizer:
    return torch.optim.RMSprop(policy.model.parameters(), lr=config["lr"])

# Custom policy
CustomPolicy = PPOTorchPolicy.with_updates(
    name="MyCustomPPOTorchPolicy",
    optimizer_fn=custom_optimizer
)

# Custom trainer
CustomTrainer = PPOTrainer.with_updates(default_policy=CustomPolicy)

# Trainer instance
trainer = CustomTrainer(
    env="CartPole-v0",
    config={"framework": "torch"})

print(trainer.get_policy().optimizer())
```
The output is: 
```
[Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 5e-05
    weight_decay: 0
)]
```
I have already tried all possible combinations, including using the `build_trainer` and `build_torch_policy` helper functions, however I just can't get it to just replace the default optimizer with another one. On page https://docs.ray.io/en/latest/rllib-concepts.html#extending-existing-policies it also says something about a `make_*` function, but I couldn't find it anywhere in the source code. About any help I would be very grateful.

**Comment by richardliaw** [comment]
Hmm, this seems odd. Maybe it's that one of the layers is overriding the underlying policy. 

@michaelzhiluo, @krfricke , @sven1977 do you have time to take a look?

**Comment by ColorfulSS** [comment]
Please refer to these documents:
1. https://github.com/ray-project/ray/blob/releases/1.8.0/rllib/agents/ppo/ppo.py#L311
2.  https://github.com/ray-project/ray/blob/72fdf3be605e4aadfd9a8c3f01dd7843c01cb8fd/rllib/agents/trainer_template.py#L53

_**default_policy (Optional[Type[Policy]]): The default Policy class to use if `get_policy_class` returns None.
get_policy_class (Optional[Callable[ TrainerConfigDict, Optional[Type[Policy]]]]): Optional callable that takes a config and returns the policy class or None. If None is returned, will use `default_policy` (which must be provided then).**_


Note: 
1.  PPOTrainer [ from ray.rllib.agents.ppo import PPOTrainer ] use function build_trainer() [In ray/rllib/agents/trainer_template.py ].
2. Therefore, PPOTrainer has the following properties: default_policy=PPOTFPolicy & get_policy_class=get_policy_class etc. 
4. And build_trainer() function explains that the policy corresponding to the ‘default_policy=PPOTFPolicy’ parameter is used only when the value of the ’get_policy_class‘ is None. 
5. Therefore, in order to use the custom policy, you need to update the value of the  ’get_policy_class‘  parameter to be None.

- [ ] **Solution:** 
# Custom trainer
CustomTrainer = PPOTrainer.with_updates(default_policy=CustomPolicy, get_policy_class=None)

**Comment by a-python-script** [comment]
+1. Thx son, now it works. Closing this issue.
