### ISSUE TITLE
#16408 broke XGBoost-Ray + Ray Tune related unit and release tests

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#16507]
### What is the problem?

Bisection revealed that https://github.com/ray-project/ray/pull/16408 broke all XGBoost-Ray/Ray Tune related unit and release tests (these run on the XGBoost-Ray repo or in the releaser tool). From a first glance it seems that data loading tasks are not recognized as finished. This is only the case when more resources are requested from a cluster than available (e.g. when not all trials can run concurrently)

Unfortunately I cannot revert the PR: ` Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged. `

### Reproduction (REQUIRED)

E.g. run `release/xgboost_tests/workloads/tune_small.py`, adjust number of trials to exceed number of parallel running trials.

cc @ericl @rkooo567 

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
Does the test pass with `RAY_yield_plasma_lock_workaround=0` env var set? You could flip just that flag to disable the feature.

**Comment by scv119** [comment]
Currently we suspect it might not related to  #16408 
https://anyscaleteam.slack.com/archives/CLJQR6420/p1623938034324100 has more context.

**Comment by scv119** [comment]
we bisected and confirmed the test fails after #16437 was merged.
most likely the test wasn't using correct placement_group.

**Comment by scv119** [comment]
- After #16437 the Actor placement behavior [has changed for ](https://github.com/ray-project/ray/pull/16437/files#diff-f67ab59de16332a2ea8df0fb7032ea69a0912c3bb52538649b4ed0c9fc21d9d2R636)`placement_group = None` versus `placement_group = "default"`; 
- Also in #16437, by default the `placement_group` is set to `"default"` instead of `None` [when creating Ray Actors](https://github.com/ray-project/ray/pull/16437/files#diff-f67ab59de16332a2ea8df0fb7032ea69a0912c3bb52538649b4ed0c9fc21d9d2R500).
- However in tune_small.py test,  RayXGBoostActor's`placement_group` was set to `None`, even if it seems we didn't customize its [placement group](https://github.com/ray-project/xgboost_ray/blob/7f9dbfb3cb0336dbdbcc5b9b1bd1f33dfc44e6eb/xgboost_ray/main.py#L355) 
- Is this a dependency issue? Looks like it might because xgboost_ray depends on an early version of Ray, so when RayXGBoostActor is created, it set `placement_group = None`?

**Comment by krfricke** [comment]
Ok so the problem was a breaking API change when using `placement_group=None`. Previously (Ray <= 1.4.0) this would use the parent placement group. Since #16437 passing `None` will instead break out of/ignore the parent placement group. 

I'm working on a backwards compatible fix for XGBoost-Ray and will release a new version to reflect this. Thanks for your help bisecting this @scv119!

**Comment by krfricke** [comment]
I'll close this for now as we introduced a fix in XGBoost-Ray.
