### ISSUE TITLE
Document how to use Ray on the Windows Linux subsystem.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1673]
cc @devin-petersohn @mehrdadn

**Comment by mehrdadn** [comment]
One thing to note: `/dev/shm` and `tmpfs` [use actual disk storage on WSL rather than RAM](https://www.reddit.com/r/bashonubuntuonwindows/comments/69zez8/does_tmpfs_really_work/), so you get both the performance hit of the storage device and the overhead of the file system.

**Comment by dynamicwebpaige** [comment]
It might be worthwhile to consider [documenting WSL2 with Ray](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#exceptions-for-using-wsl-1-rather-than-wsl-2) rather than the original implementation of WSL, as there have been significant performance improvements (ex: adding a Linux kernel with full system call compatibility).

#### Some useful content to draw inspiration from:
* [CUDA on WSL2 - PyTorch with Horovod](https://morioh.com/p/98db79b3e39b)
* [Enable PyTorch with DirectML on WSL2](https://docs.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-wsl)
* [Run RAPIDS on Windows 10 with WSL2](https://developer.nvidia.com/blog/run-rapids-on-microsoft-windows-10-using-wsl-2-the-windows-subsystem-for-linux/)

**Comment by pcmoritz** [comment]
Thanks for chiming in!

Since this issue has been created, we actually have a pretty stable version of Ray for Windows that can be downloaded from https://docs.ray.io/en/latest/ray-overview/installation.html -- currently we call it "beta", but in the next 1-2 month the plan is to label it as stable as we keep making progress on getting more and more of the Ray test suite running on Windows.

I would expect that most people will prefer to run Ray natively on Windows instead of using WSL2 -- if this assumption is wrong or if Ray on WSL2 can somehow run better than our native port, we can write documentation on using WSL2 with Ray.

**Comment by pcmoritz** [comment]
(would it make sense to close the issue for now?)

**Comment by devin-petersohn** [comment]
@pcmoritz In my experience, WSL2 is not providing any significant benefits over WSL1 in terms of Ray performance. I do not recommend folks use ray with WSL2, it will be a really bad experience.

I think it makes sense to close the issue and not recommend to run ray on WSL2
