### ISSUE TITLE
[tune][rllib] Issue with the use of Wandb on MacOs/Linux

### ISSUE THREAD

**Issue by loicsacre** [ray-project/ray#16808]
### What is the problem?

When using tune.run with the WandbLoggerCallback, there is an error when the ray local mode is set to `True` due to the usage of a Tee object proper to Tune. The following condition fails in the wandb module when the OS is not Windows:

```
  File "/Users/loicsacre/miniconda3/envs/rllib_env/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1462, in _display_run
    if platform.system() != "Windows" and sys.stdout.encoding == "UTF-8":
AttributeError: 'Tee' object has no attribute 'encoding'
```

*System version*

OS: MacOs
Python version: 3.7.9
torch==1.7.1
wandb==0.10.33
ray==1.3.0

### Reproduction

It is difficult to give a code snippet due to use of wandb and the requirements for an API key

**Comment by amogkam** [comment]
Hey @loicsacre, this bug has been fixed by https://github.com/ray-project/ray/pull/16674. It will be included in the next Ray release, but in the meantime you can update your Ray version to use the nightly wheels. I'm going to close this for now, but feel free to reopen if this is still not working for you.

**Comment by loicsacre** [comment]
Ok my bad I did not update ray due to this issue which is not fixed yet https://github.com/ray-project/ray/commit/f8cf4a19856409b7d31007e384cc5cbdf81fe9ee and this one https://github.com/ray-project/ray/issues/16809
