### ISSUE TITLE
Tune not saving checkpoint after Ctrl+c

### ISSUE THREAD

**Issue by Dylan-Kerler** [ray-project/ray#16855]
Run the following tune experiment:

```python
from ray import tune
from ray.rllib.agents.ppo import PPOTrainer

tune.run(
    PPOTrainer,
    config={"env": "LunarLander-v2", "framework": "torch"},
    name="testing123",
    metric="episode_reward_mean",
    local_dir="./tune_results/",
    stop={"episode_reward_mean": 30},
    checkpoint_at_end=True,
)
```

Do Ctrl+C

Expect to see a checkpoint file but no checkpoint file is generated:

![Screenshot from 2021-07-02 21-45-51](https://user-images.githubusercontent.com/37438950/124326771-efc59e00-db7e-11eb-8009-67ece21f451a.png)

As per the docs here: https://docs.ray.io/en/master/tune/api_docs/execution.html
It says that a checkpoint file will be generated after Ctrl+C.

**Comment by richardliaw** [comment]
I think a checkpoint is only generated for the controller (not the trial itself).

**Comment by Dylan-Kerler** [comment]
What's the difference?

**Comment by richardliaw** [comment]
Ah @Dylan-Kerler sorry for the bad reply, got distracted:

Checkpoint upon ctrl-c is only useful for checkpointing the experiment (i.e, what trials were run, etc). I think what you might be also interested in is trial checkpointing - in which case you should probably set "checkpoint_freq=1" and "keep_checkpoints_num=X". This makes it so that you can resume both the experiment and your trials after ctrl-c. let me know if that makes sense!

**Comment by Dylan-Kerler** [comment]
Thanks 👍🏼
