### ISSUE TITLE
Arrow error when building from source

### ISSUE THREAD

**Issue by pschafhalter** [ray-project/ray#1692]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu subsystem on Windows 10
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.3.1
- **Python version**: 3.6.3 in a virtual environment.
- **Exact command to reproduce**: `python3 setup.py develop`

### Describe the problem

Building from source fails with `error: [Errno 2] No such file or directory: './ray/pyarrow_files/pyarrow'`.

The problem was also mentioned in #1065 and #1670. 

### Source code / logs

TODO. Will include the next time I have access to the machine.

**Comment by robertnishihara** [comment]
You ended up resolving the problem, right? Was the issue that you needed to do `sudo apt-get install flex bison` and then do a clean build (to get rid of cached cmake files)?

**Comment by pschafhalter** [comment]
I'll try that once I have access again, but I didn't resolve the reported error on the Windows subsystem. I resolved the other error with building parquet/thrift by installing the parquet Linux prerequisites.

**Comment by richardliaw** [comment]
I ran into this error on Ubuntu 14.04, and I was able to resolve it by `pip install cython==0.27.3`

**Comment by robertnishihara** [comment]
I think the above error happens in the following setting. First you try to build Ray from source and Arrow fails to compile for some reason. Then you try to build it again, and the compilation of Arrow is skipped because it thinks Arrow is already built, but then later on in the build when it tries to use pyarrow it doesn't find it because it wasn't actually built.

**Comment by pschafhalter** [comment]
Closing because I'm not getting this issue anymore.
