### ISSUE TITLE
[tune] Clarify documentation around using different resource requirements across trials

### ISSUE THREAD

**Issue by seyuboglu** [ray-project/ray#17088]
[This discuss thread](https://discuss.ray.io/t/different-resource-amount-for-different-trials/509) shows how to run tune with different resource requirements for each trial. This is useful in settings where some models in the search require GPU and others do not. 

We can achieve this by taking advantage of the fact that the `resources_per_trial` are treated as part of the "hyperparameter space" under the hood:_
```
tune.run(
    ...
    config={
        ...
        "use_gpu": tune.grid_search([True, False])
    },
    resources_per_trial=tune.sample_from(
        lambda spec: {"gpu": 1} if spec.config.use_gpu else None
    )
)
```

The documentation should ideally address this behavior. It's super useful but hard to find!

**Comment by heyitsmui** [comment]
perhaps somewhere here e.g. https://github.com/heyitsmui/ray/commit/86a7b7748cdd31b41658e8ffc901061c89258694?

**Comment by xwjiang2010** [comment]
Hmmm, I am actually not sure how this "hack" works with the new `with tune.resources()` API for functional trainables.

for example,
```
def f(config):
  session.report({"bla": 1})
tuner = tune.tuner(tune.with_resources(f, tune.sample_from(lambda spec: {"cpu": 1} if spec.config.x > 0 else {"cpu": 2})))
tuner.fit()
```
doesn't work

while 
```
tune.run(f, resources_per_trial = tune.sample_from(lambda spec: {"cpu": 1} if spec.config.x > 0 else {"cpu": 2}), config={"x": tune.grid_search([1, -1])})
``` 
works

This is because `tune.with_resources` doesn't go through VariantGenerator (where `sample_from` stuff is resolved...)

On the other hand, for the new ray AIR trainers, we can achieve specifying resources through param_space["scaling_config"] (see `ray.air.config.ScalingConfig`). 

Maybe we should just make it clear that if you want to do conditional resource allocation, please implement a new Trainer from `BaseTrainer` and achieve that through ScalingConfig.

**Comment by heyitsmui** [comment]
@xwjiang2010 sounds good! seems like there are some docs that call out `ScalingConfig` is tunable: https://docs.ray.io/en/master/train/config_guide.html. In that case, will try to see if we can make it clearer via FAQ etc. Will send out a PR for review later today.

**Comment by xwjiang2010** [comment]
ah just tried again:
```
from ray import tune
from ray.air import session
from ray.air.config import ScalingConfig

def f(config):
	session.report({"bla": 1})

if __name__ == "__main__":
	trainable = tune.with_resources(f, resources=lambda config: {"cpu": 1} if config["x"] > 0 else {"cpu": 2})
	tuner = tune.Tuner(trainable, param_space={"x": tune.grid_search([1, -1])})
	tuner.fit() 
```
should work for functional trainables. So we should have both cases covered!
