### ISSUE TITLE
Parquet partitioning support doesn't work (should be using native pyarrow partitioning support)

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#17325]
```
part
part/p=3
part/p=3/9af4eee4508e4da593552f577ae81326_000096_000000.parquet
part/p=1
part/p=1/9af4eee4508e4da593552f577ae81326_000059_000000.parquet
part/p=2
part/p=2/9af4eee4508e4da593552f577ae81326_000066_000000.parquet
```

```
>>> ray.data.read_parquet("/tmp/output/part")
Dataset(num_rows=30, num_blocks=3, schema={0: int64})
```

The schema here is wrong, it should include the partitioning column `p`. This is probably since we stopped using the pyarrow parquet reader after the port to FileBasedDatasource, we might need to revert part of that.

**Comment by ericl** [comment]
I dug into this a bit. There are multiple issues with the current implementation of ParquetDatasource:
1. We should not be resolving the paths in `_resolve_paths_and_filesystem`. Instead, we should let ParquetDataset walk the directory itself, since it implements partitioning support. The only thing we should resolve is the filesystem.
2. Similarly, the file metadata should be generated based on the piece metadata, not from FileInfos.

**Comment by clarkzinzow** [comment]
>The schema here is wrong, it should include the partitioning column p. This is probably since we stopped using the pyarrow parquet reader after the port to FileBasedDatasource, we might need to revert part of that.

This has always been broken, the schema of individual Parquet pieces/fragments don't include the partition columns since those columns don't exist at the piece/fragment/file level. Pretty sure that the partition columns are added back into the schema at the dataset level.

https://github.com/apache/arrow/blob/6323c12f2273e4473108ecc3a270ab40651a76fd/python/pyarrow/parquet.py#L1401-L1416
https://github.com/apache/arrow/blob/6323c12f2273e4473108ecc3a270ab40651a76fd/python/pyarrow/tests/test_dataset.py#L908-L923
