### ISSUE TITLE
[Rllib] `TorchPolicy` and `TFPolicy` cannot find any GPUs

### ISSUE THREAD

**Issue by XuehaiPan** [ray-project/ray#17397]
### What is the problem?

`ray.get_gpu_ids()` gets an empty list on my machine when I'm using `TorchPolicy` with `config['num_gpu']` set. It will get an `IndexError` at `self.devices[0]` when using `TorchPolicy` on GPUs:

https://github.com/ray-project/ray/blob/1f35470560c90de69e7555097a4d2dd85065d6f8/rllib/policy/torch_policy.py#L154-L159

This issue can be reproduced on multiple machines. *Ray version and other system information (Python version, TensorFlow version, OS):*

##### Machine 1:
- OS version: Ubuntu 20.04 LTS
- Python version: 3.8.10
- Ray version: 1.5.0 from PyPI (tested with nightly build as well)
- PyTorch version: 1.9.0
- NVIDIA driver version: 470.57.02
- CUDA version: 11.1.1

##### Machine 2:
- OS version: Ubuntu 16.04 LTS
- Python version: 3.7.10
- Ray version: 1.5.0 from PyPI (tested with nightly build as well)
- PyTorch version: 1.4.0
- NVIDIA driver version: 430.64
- CUDA version: 10.0.0

Same issue on Windows: https://discuss.ray.io/t/error-with-torch-policy-and-ray-get-gpu-ids-on-windows/2711

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```bash
conda create --name test python=3.8 --yes
conda activate test
pip3 install https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
python3 -c 'import ray; print(ray.get_gpu_ids())'
nvidia-smi --list-gpus
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
Hi @XuehaiPan, which version of Ray are you using? And which tensor backend?

Does torch or tensorflow detect the GPUs?

```
import tensorflow as tf
tf.config.list_physical_devices('GPU')
```

or 

```
import torch
torch.cuda.is_available()
```

**Comment by XuehaiPan** [comment]
I'm using PyTorch 1.9.0 with Ray's nightly build.

```console
$ python3 -c 'import ray; print(ray.get_gpu_ids())'
2021-07-28 16:55:06,816 INFO services.py:1245 -- View the Ray dashboard at http://127.0.0.1:8266
[]

$ python3 -c 'import torch; print(torch.cuda.is_available(), torch.cuda.device_count())'
True 10

$ nvidia-smi --list-gpus
GPU 0: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-f9ca790e-683e-3d56-00ba-8f654e977e02)
GPU 1: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-f8e5a624-2c7e-417c-e647-b764d26d4733)
GPU 2: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-6d2a57c9-7783-44bb-9f53-13f36282830a)
GPU 3: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-2428d171-8684-5b64-830c-435cd972ec4a)
GPU 4: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-96de99c9-d68f-84c8-424c-7c75e59cc0a0)
GPU 5: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-18ef14e9-dec6-1d7e-1284-3010c6ce98b1)
GPU 6: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-849d5a8d-610e-eeea-1fd4-81ff44a23794)
GPU 7: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-843ecb19-b449-3be8-f49c-27697124f714)
GPU 8: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-55f97fef-2770-f1da-8757-04b458ab93fe)
GPU 9: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-6ec821a6-121f-02b1-43d1-73e0e24c3229)

$ [[ "${CUDA_VISIBLE_DEVICES-x}" == x ]]; echo $?
0  # CUDA_VISIBLE_DEVICES not set
```

**Comment by krfricke** [comment]
Okay, thanks.
It seems Ray is being initialized newly - I'm wondering if this might be in conflict with the running Ray instance. Could you try passing either `ray.init(address="auto")` to connect to the running ray session, or `ray.init(num_gpus=10)` to start a new Ray session with 10 GPUs before calling `ray.get_gpu_ids()`?

**Comment by XuehaiPan** [comment]
`ray.get_gpu_ids()` returns an empty list after `ray.init(address='auto')` or `ray.init(num_gpus=10)`.

```console
python3 -c 'import ray; ray.init(address="auto"); print(ray.get_gpu_ids())'
2021-07-28 18:56:30,137 INFO worker.py:800 -- Connecting to existing Ray cluster at address: aaa.bbb.ccc.ddd:6379
[]

$ python3 -c 'import ray; ray.init(num_gpus=10); print(ray.get_gpu_ids())'
2021-07-28 18:56:54,361 INFO services.py:1245 -- View the Ray dashboard at http://127.0.0.1:8266
[]
```

**Comment by krfricke** [comment]
Okay, thanks.

I'll try to reproduce this on a cluster later today.

cc @ijrsvt

**Comment by XuehaiPan** [comment]
I have just tried to reproduce this issue inside a nvidia docker.

- Tag: `pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime`

```bash
docker run -it --rm --runtime=nvidia --gpus all pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime
pip3 install -qqq ray[default]
python3 -c 'import ray; print(ray.get_gpu_ids())'
python3 -c 'import torch; print(torch.cuda.is_available(), torch.cuda.device_count())'
nvidia-smi --list-gpus
```

<details>
<summary>Show screenshot ...</summary>
<p>
<img src="https://user-images.githubusercontent.com/16078332/127315631-a323c622-61a6-4f3e-b0d4-2c8c2038eb29.png">
</p>
</details>  

- Tag: `tensorflow/tensorflow:latest-gpu`

```bash
docker run -it --rm --runtime=nvidia --gpus all pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime
pip3 install -qqq ray[default]
python3 -c 'import ray; print(ray.get_gpu_ids())'
python3 -c 'import tensorflow as tf; print(tf.config.list_physical_devices("GPU"))' 2>/dev/null
nvidia-smi --list-gpus
```

<details>
<summary>Show screenshot ...</summary>
<p>
<img src="https://user-images.githubusercontent.com/16078332/127315803-5d194f33-92b4-479b-bfdd-a4aa1932f941.png">
</p>
</details>

**Comment by krfricke** [comment]
Confirmed using Ray cluster launcher:

```
(base) ray@ip-172-31-16-127:~$ ray status
======== Autoscaler status: 2021-07-28 06:44:21.751891 ========
Node status
---------------------------------------------------------------
Healthy:
 1 cpu_4_ondemand
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------

Usage:
 0.0/4.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:V100
 0.00/35.597 GiB memory
 0.00/17.799 GiB object_store_memory

Demands:
 (no resource demands)
(base) ray@ip-172-31-16-127:~$ nvidia-smi
Wed Jul 28 06:44:49 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   46C    P0    27W / 300W |      0MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
(base) ray@ip-172-31-16-127:~$ ray status
======== Autoscaler status: 2021-07-28 06:44:48.189085 ========
Node status
---------------------------------------------------------------
Healthy:
 1 cpu_4_ondemand
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------

Usage:
 0.0/4.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:V100
 0.00/35.597 GiB memory
 0.00/17.799 GiB object_store_memory

Demands:
 (no resource demands)
(base) ray@ip-172-31-16-127:~$ python3 -c 'import ray; ray.init(address="auto"); print(ray.get_gpu_ids())'
2021-07-28 06:44:55,502	INFO worker.py:736 -- Connecting to existing Ray cluster at address: 172.31.16.127:6379
[]
```

But:

```
{'node_ip_address': '172.31.16.127', 'raylet_ip_address': '172.31.16.127', 'redis_address': '172.31.16.127:6379', 'object_store_address': '/tmp/ray/session_2021-07-28_06-43-06_018883_312/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2021-07-28_06-43-06_018883_312/sockets/raylet', 'webui_url': '127.0.0.1:8265', 'session_dir': '/tmp/ray/session_2021-07-28_06-43-06_018883_312', 'metrics_export_port': 63257, 'node_id': '819b046909b777f273f163c1024c8fe92f7f6aeb005ac15a418e37a0'}
>>> ray.cluster_resources()
{'accelerator_type:V100': 1.0, 'memory': 38222325351.0, 'CPU': 4.0, 'GPU': 1.0, 'node:172.31.16.127': 1.0, 'object_store_memory': 19111162675.0}
```

```
>>> @ray.remote(num_gpus=1)
... def test_gpu():
...     import torch
...     print(torch.cuda.is_available())
... 
>>> ray.get(test_gpu.remote())
>>> (pid=603) True
```

So it might a problem with `ray.get_gpu_ids()`?

cc @ijrsvt

**Comment by akshaygh0sh** [comment]
Definitely an issue with ray.get_gpu_ids(), it still hasn't been fixed. See #17174, #17316, and #16715. Does anyone know how to get a GPU to work with a PyTorch policy (i.e. downgrading to a specific version of ray/rllib? I can't seem to get it to work at all.)

**Comment by XuehaiPan** [comment]
> Does anyone know how to get a GPU to work with a PyTorch policy (i.e. downgrading to a specific version of ray/rllib? I can't seem to get it to work at all.)

I find a way to hack the function `ray.get_gpu_ids` using the `unittest.mock` module:

```python
from functools import wraps
from unittest import mock

import ray

def get_gpu_ids_torch():
    import torch
    return list(range(torch.cuda.device_count()))

def get_gpu_ids_tf():
    import tensorflow as tf
    return tf.config.list_physical_devices('GPU')


def patch_ray_get_gpu_ids(patcher):
    def wrapper(func):
        @wraps(func)
        def wrapped(*args, **kwargs):
            with mock.patch('ray.get_gpu_ids', patcher):
                print('Patched ray.get_gpu_ids() = {}'.format(ray.get_gpu_ids()))

                return func(*args, **kwargs)

        return wrapped

    return wrapper


# Add `patch_ray_get_gpu_ids` to your main function before `ray.init()`!
@patch_ray_get_gpu_ids(get_gpu_ids_torch)  # replace with `get_gpu_ids_tf` for TensorFlow
def main(*args, **kwargs):
    print('training ...')

    # Your code here ...

if __name__ == '__main__':
    main()
```

This is only a temporary solution, the official solution should wait to fix `ray.get_gpu_ids()`. The patch result on my machine:

```console
$ python3 ray_patch.py
Patched ray.get_gpu_ids() = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
training ...
```

**Comment by richardliaw** [comment]
@rkooo567 do you have any context here? This is coming up a lot.

**Comment by ericl** [comment]
Isn't this working as intended? GPU IDs are for assigned GPUs only, and are only valid to call in a remote function.

It will always be the empty list in the driver.

**Comment by ericl** [comment]
Hence, the bug is in torch policy--- you shouldn't call get GPU ids, if you want to be able to use GPUs on the driver.

**Comment by ericl** [comment]
Maybe this should raise an exception on the driver.

**Comment by sven1977** [comment]
Thanks for clarifying @ericl . That explains why I never saw it (using `tune.run()`).
I'll provide a fix in `TorchPolicy`.

**Comment by sven1977** [comment]
So in other words: As a workaround for now, run your RLlib workloads using `tune.run()` as described in most of our example scripts, e.g. here (don't set the `--no-tune` flag):
https://github.com/ray-project/ray/blob/master/rllib/examples/custom_env.py

Alternatively, you can also run `rllib train -f [your yaml config file]`.

This will make sure that any TorchPolicy runs with assigned GPUs (no policy will run on the driver then).

**Comment by XuehaiPan** [comment]
> I'll provide a fix in TorchPolicy.

Same issue for `TFPolicy` as well. I tried to fix it using `torch.cuda.device_count()` and `tf.config.list_physical_devices('GPU')` in #17398.

**Comment by sven1977** [comment]
Great, @XuehaiPan , thanks for the feedback. Working on a PR rn.

**Comment by ericl** [comment]
Thanks for confirming @sven1977 . Made this PR to add a warning to flag this scenario: https://github.com/ray-project/ray/pull/17436

**Comment by akshaygh0sh** [comment]
> Thanks for clarifying @ericl . That explains why I never saw it (using `tune.run()`).
> I'll provide a fix in `TorchPolicy`.

I am running the training loop with my custom environment using tune.run() and if I set the config["num_gpus"] = 1 for the single GPU I have on my device, I do get the error mentioned in this GitHub issue. If I remove/don't specify the num_gpus on my system from the run config, the training loop executes properly except it runs (obviously) on the CPU.

@sven1977

**Comment by sven1977** [comment]
Hmm, strange, do you use `local_mode=True` in ray.init()? @akshaygh0sh

**Comment by sven1977** [comment]
I'm confirming different scenarios right now.

The following fix in torch_policy.py::~L154 works for me when running a trainer not through tune, but creating it directly, e.g.:

`trainer = PPOTrainer(env="CartPole-v0", config={"num_gpus": 1, "framework": "torch"})`

```
            gpu_ids = ray.get_gpu_ids()
            # In case, we are running this Policy directly on the driver and
            # thus no GPUs have been assigned (ray.get_gpu_ids() returns []),
            # derive the GPUs from asking torch directly.
            if not gpu_ids:
                gpu_ids = list(range(torch.cuda.device_count()))
```

**Comment by akshaygh0sh** [comment]
@sven1977 I do not use local_mode = True in my ray.init(). My ray.init() looks like ray.init(num_cpus = 16, num_gpus = 1, ignore_reinit_error = True).

**Comment by sven1977** [comment]
ok, any other pointers that I could use to make this reproducible when using `tune.run()`?

**Comment by sven1977** [comment]
Could you quickly try the above suggested fix in your ray.rllib.policy.torch_policy.py file?

**Comment by akshaygh0sh** [comment]
I'm getting an error that says worker has no attribute mode:

`File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\policy\torch_policy.py", line 152, in __init__
    if worker.mode != 1:
AttributeError: 'RolloutWorker' object has no attribute 'mode'`

For reference, I replace [line 154](https://github.com/ray-project/ray/blob/2ae6b944a25dc2d371e0496895e3bdbe29c3d046/rllib/policy/torch_policy.py#L154) with the following: 

`# We are a remote worker: GPUs should be assigned to us by ray.
            if worker.mode != 1:
                gpu_ids = ray.get_gpu_ids()
            # In case, we are running this Policy directly on the driver and
            # thus no GPUs have been assigned (ray.get_gpu_ids() returns []),
            # derive the GPUs from asking `torch` directly.
            else:
                gpu_ids = list(range(torch.cuda.device_count()))`

**Comment by sven1977** [comment]
Testing the above PR now ...

**Comment by akshaygh0sh** [comment]
@sven1977 Any updates?

**Comment by sven1977** [comment]
@akshaygh0sh just merged this. Could you try again with the latest master?

**Comment by akshaygh0sh** [comment]
@sven1977 I am using an Anaconda virtual environment on Windows 10, is there an easy (er) way for me to get the latest master, or should I just forget Anaconda and clone the ray repo locally?

**Comment by akshaygh0sh** [comment]
@sven1977 I believe the GPU is now being used properly, but now I'm getting a different error thrown within the DictFlatteningPreprocessor that I wasn't getting before. 

`Traceback (most recent call last):
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\tune\trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\tune\ray_trial_executor.py", line 746, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\_private\client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\worker.py", line 1611, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::PPO.train() (pid=4728, ip=10.0.0.37)
  File "python\ray\_raylet.pyx", line 535, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 485, in ray._raylet.execute_task.function_executor
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\_private\function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\agents\trainer.py", line 648, in train
    raise e
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\agents\trainer.py", line 637, in train
    result = Trainable.train(self)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\tune\trainable.py", line 237, in train
    result = self.step()
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\agents\trainer_template.py", line 193, in step
    res = next(self.train_exec_impl)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\util\iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\util\iter.py", line 876, in apply_flatten
    for item in it:
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\util\iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\util\iter.py", line 471, in base_iterator
    yield ray.get(futures, timeout=timeout)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\_private\client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\worker.py", line 1611, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::RolloutWorker.par_iter_next() (pid=14104, ip=10.0.0.37)
  File "python\ray\_raylet.pyx", line 535, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 485, in ray._raylet.execute_task.function_executor
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\_private\function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\util\iter.py", line 1151, in par_iter_next
    return next(self.local_it)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 347, in gen_rollouts
    yield self.sample()
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 747, in sample
    batches = [self.input_reader.next()]
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\evaluation\sampler.py", line 100, in next
    batches = [self.get_data()]
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\evaluation\sampler.py", line 230, in get_data
    item = next(self.rollout_provider)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\evaluation\sampler.py", line 610, in _env_runner
    sample_collector=sample_collector,
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\evaluation\sampler.py", line 815, in _process_observations
    policy_id).transform(raw_obs)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\models\preprocessors.py", line 259, in transform
    self.write(observation, array, 0)
  File "C:\Users\408aa\Anaconda3\envs\rl_env\lib\site-packages\ray\rllib\models\preprocessors.py", line 266, in write
    observation = OrderedDict(sorted(observation.items()))
AttributeError: 'numpy.ndarray' object has no attribute 'items'`

This error happens when running on both CPU (num_workers = 0) and GPU (num_workers = 1 in my case). I wasn't getting this error before when I was training on my CPU, the training loop executed fine, so I'm not sure what's happening.

**Comment by richardliaw** [comment]
Hey Akshay, could you open a new issue for this?

**Comment by akshaygh0sh** [comment]
@richardliaw Sure, I will try to post an issue by tomorrow; I think it will be a little hard to reproduce since I am using a custom PettingZooEnv and a custom network, but I will try my best.

**Comment by ferrantedev** [comment]
Just in case anyone stumbles upon this issue and is running Ray locally, adding `local_mode=True` to the `ray.init()` call could fix the issue, just make sure Tensorflow or PyTorch are able to detect the GPU

**Comment by tinducvo** [comment]
On python 3.11.5 with Ray 2.7.1,
With `ray.init(local_mode=True)`, `get_gpu_ids()` returned` ['0']`
Whereas with `ray.init()`, `get_gpu_ids()` returned` []`

**Comment by guotong1988** [comment]
> Just in case anyone stumbles upon this issue and is running Ray locally, adding `local_mode=True` to the `ray.init()` call could fix the issue, just make sure Tensorflow or PyTorch are able to detect the GPU

Same solution..

**Comment by guotong1988** [comment]
With `ray.init(local_mode=True)`, `get_gpu_ids()` works. But the mode has changed.
