### ISSUE TITLE
Stdout Logging for Ray Head and Worker Nodes

### ISSUE THREAD

**Issue by nkratzke** [ray-project/ray#17467]
Is there any way that Ray head and worker pods in Kubernetes just log to stdout/stderr? Kubernetes already ensures that the pod logs land on the Kubernetes hosts and can then be subjected to simple log consolidation from there.

This way, log consolidation in Kubernetes environments would be easier and could be solved using filebeat, for example.

Unfortunately, I have not found a corresponding logging setting.

This "primitive" way of stdout logging would also be more in line with the 12 factor principles (factor 11, https://12factor.net/logs).

**Comment by rkooo567** [comment]
cc @DmitriGekhtman Are you aware a way to achieve this? I think this is a common use case

**Comment by isaac-vidas** [comment]
Hi, same question here. Are there any plans to enable this?

**Comment by simon-mo** [comment]
One idea, we can include [fluentbit](https://docs.fluentbit.io/manual/about/what-is-fluent-bit) in the container image and just have it discover and stream logs to stdout at entrypoint.

**Comment by DmitriGekhtman** [comment]
Documenting how to log is an open ticket
https://github.com/ray-project/ray/issues/16822 

Simon made a suggestion here
https://discuss.ray.io/t/export-logs-from-cluster-when-using-ray-operator/3340/4

stdout may not be the best solution right now because Ray head and worker pods wildly violate the principle of one concern per container -- there are a bunch of processes in a Ray pod producing multiple log files.

**Comment by simon-mo** [comment]
@isaac-vidas would you be ok the pod log prints from all sorts of files?

**Comment by DmitriGekhtman** [comment]
I imagine could would be workable if the output has some prefixes to filter by.

**Comment by DmitriGekhtman** [comment]
@nkratzke -- what method are you using to deploy Ray on K8s? We could suggest some solutions based on the configs you're currently using.

**Comment by nkratzke** [comment]
We are deploying the Ray cluster using the helm chart of the official repository in a very basic and almost unmodified config. We are only using specific images with some addon libraries on the ray worker nodes (using a super-simple `pip install -r requirements.txt` based approach to add these addon libraries on top of the base rayproject/ray-ml image).

Regarding the logging. We operate filebeat, to ship all container logs to a central elasticsearch db (outside the cluster). There is the filtering and querying been done. So, even if the logs of different processes of a ray worker/operator pod are totally cluttered, we should manage that somehow by specific query and conditions (that would be handled totally outside of ray). 
So, if the logs of different processes have some prefixes to simplify querying that would be perfect for us. Even if not, a cluttered stdout logging would simplify things for us as well.

**Comment by wuisawesome** [comment]
Bumping to p2, we should consider kuberay in the context of dealing with this issue now.

**Comment by clarkzinzow** [comment]
FYI @nkratzke @wuisawesome @DmitriGekhtman, [this PR](https://github.com/ray-project/ray/pull/21767) adds support for disabling log redirection to files (i.e. letting logs being directed to stdout/stderr) via specifying an environment variable when starting each Ray node/driver. As an extension, we can consider doing the following in future APIs:
1. Adding first-class API support for disabling log redirection, via the Python and CLI APIs.
2. Prefixing log messages with their component when logs are directed to stdout/stderr instead of named files.
3. Allowing a user to configure structured logging, which would be a richer extension of (2).

**Comment by rkooo567** [comment]
This is supported now, but there might be some usability gaps between the default option (e.g., log_monitor might not be working). Please comment issues if you have any in this thread.

**Comment by DmitriGekhtman** [comment]
See also https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/logging.html for tips on aggregating logs from the Ray container file system on K8s.
