### ISSUE TITLE
[rllib] Increasing number of workers on tuned examples reduces performance

### ISSUE THREAD

**Issue by matej-macak** [ray-project/ray#17490]
I am trying to reproduce some of the `rllib` examples to create baseline comparison for my future runs and I came across a really puzzling reduction in performance as a result of increased number of workers (see here for a sample output):

![image](https://user-images.githubusercontent.com/5074413/127781312-621002db-8eba-4613-85ac-16449e81b7f8.png)

I am running the following `yaml` adjusted from [here](https://github.com/ray-project/ray/blob/master/rllib/tuned_examples/impala/atari-impala.yaml):

```
# Run on a AWS cluster with a g3.16xl head node and 3x m4.16xl worker nodes.
# https://github.com/ericl/ray/commit/1c6c2730ac7f9292d35080c6eb06726c372a4fcc
atari-impala:
    env:
        grid_search:
            - BreakoutNoFrameskip-v4
    run: IMPALA
    config:
        train_batch_size: 500
        num_workers: 
          grid_search: [1, 2, 4, 8]
        num_gpus: 0
        framework: torch
        num_envs_per_worker: 5
        lr_schedule: [
            [0, 0.0005],
            [20000000, 0.000000000001],
        ]
```
I have tried different algorithms such as `PPO` and different environment such as `Cartpole-v0` and played with different parameters. I have tried running it on stock `Ubuntu 20.04` and within a `Docker` environment but the results are almost always the same. It seems to me that I am missing something obvious. 

This may be conceptually similar to the following [issue](https://github.com/ray-project/ray/issues/13907)

```
Setup:
Ubuntu 20.04
Python 3.8.10
ray==1.4.1
torch==1.9.0+cu111
```

**Comment by Mathieu-Prouveur** [comment]
I have 

Same observation here.

With a custom environment and `DDPG`, performance decreases with increasing number of workers.

At first I had not set `training_intensity` (if not set,  `num_workers` has an impact on the number of train steps per iteration ) but even after setting `training_intensity` I see a drop of performance from 4 to 8+ workers. `num_agent_steps_trained` and `num_agent_steps_sampled` are now the same in my tests but i still observe some heavy changes between runs with different workers.

Maybe there are other side effects from changing `num_workers`. It would be nice to have some insights so as to what impacts/side-effects are expected by increasing that parameter, especially since it is very tempting too assume that changing `num_workers` will just speed up trainings.

**Comment by krfricke** [comment]
cc @sven1977 @gjoliver @avnishn

**Comment by Mathieu-Prouveur** [comment]
After some experimentations I observe the same behaviours for similar number of environments `num_workers * num_envs_per_workers` (as expected).

Some side effect that may explain my results and those of @matej-macak on breakout is that increasing the number of environments will lead to :

- more frequent updates of the network during an episode : if an `episode lasts 200 steps`, and` rollout_fragment_length=20` and `num_workers * num_envs_per_worker = 10`, then there will be 10 updates during an episode (versus only 1 update if  `num_workers * num_envs_per_worker = 1`).
- different kind of data distribution in the training batch :  if an `episode lasts 200 steps`, and` rollout_fragment_length=20` and `num_workers * num_envs_per_worker = 10`, then there will be 10 bits of episodes instead of 1 full episode for the update.

However I find it surprising that `DDPG` is not robust to this on my environment (if the replay buffer is big enough, it's rare to sample recent rollouts) as well as `PPO` on `cartpole` since by default the batch size and rollout_fragment length are relatively large (respectively 4000 and 200) compared to the length of an episode on cartpole

**Comment by Mathieu-Prouveur** [comment]
@matej-macak could you share your config for `PPO` on `Cartpole-v0`? I tried with 1, 5 and 20 workers with different batch modes and I did not observe some significative change between runs (with repeats, as the variance can be high between runs). I also tried on other environments such as `LunarLander-v2` and `Acrobot-v1`.

**Comment by matej-macak** [comment]
Hey @Mathieu-Prouveur! For the PPO, I have used the default config with `lr=0.0001`. I am running longer run on both `LunarLander-v2` and `Acrobot-v1` to see if this is maintained across different environment areas (across different batch sizes). I am also testing whether asynchronous updating models are more resilient to this (e.g. `APPO` or `Impala`). They seem to have a slightly better result but I don't see advantage of multiple workers.

I have also run the analysis on the `stable-baselines3` which seems to be able to parallelize well on their implementation of `PPO`. 

I will update when I get the results.

**Comment by matej-macak** [comment]
I have run some of the analyses and it seems to me that the advantage of multiple workers is very quickly lost due to the update cost. Here is the time that it takes to achieve 200 reward:

![image](https://user-images.githubusercontent.com/5074413/135729080-78caaed3-1bb9-4d4e-b76e-a9ebce110479.png)
 
At least in these two environments, on my system, the bottleneck even with GPU (3090 RTX) is driven by learning update time:

![image](https://user-images.githubusercontent.com/5074413/135729117-825ab8a2-014a-4344-a675-e630a4282dc6.png)

I have tried `Impala` and `APPO` as well which have a much higher throughput in terms of samples due to their asynchronous nature of updates but are not very effective at learning as quickly as `PPO` is even with the bottleneck. What surprises me is that in the other examples more workers were typically used even with PPO so I would be curious as to the setup that enabled more efficient scaling.

**Comment by gjoliver** [comment]
Thanks for the detailed description and testing results.

We will try to make the sampling behaviors consistent across algorithms. But at this point for APPO/IMPALA, if you have more workers, you are essentially getting back larger training batches, which will cause more time being spent on learning.
For PPO, under batch_mode=truncte_episodes, the batch size will stay the same, but we will get back fewer consecutive frames from each worker environment. And there will be more train steps before an episode finishes. Under batch_mode=complete_episodes, behavior is the same as APPO.

I don't think more worker can be easily mapped to better performance. There are a lot of factors in play here (parallelism, queue size, cpu/gpu speed, batch size, episode length, etc). num_workers is a hyper parameters that is worth tuning a bit.

**Comment by avnishn** [comment]
I think we're gonna close this -- this seems that if you were to extend to more compute nodes that you may not face the same issues. We personally have not faced these issues. @gjoliver

**Comment by Cobular** [comment]
> I have run some of the analyses and it seems to me that the advantage of multiple workers is very quickly lost due to the update cost. Here is the time that it takes to achieve 200 reward:
> 
> ![image](https://user-images.githubusercontent.com/5074413/135729080-78caaed3-1bb9-4d4e-b76e-a9ebce110479.png)
>  
> At least in these two environments, on my system, the bottleneck even with GPU (3090 RTX) is driven by learning update time:
> 
> ![image](https://user-images.githubusercontent.com/5074413/135729117-825ab8a2-014a-4344-a675-e630a4282dc6.png)
> 
> I have tried `Impala` and `APPO` as well which have a much higher throughput in terms of samples due to their asynchronous nature of updates but are not very effective at learning as quickly as `PPO` is even with the bottleneck. What surprises me is that in the other examples more workers were typically used even with PPO so I would be curious as to the setup that enabled more efficient scaling.
> 

Hey! I'm running into similar behavior on my project, and I'd like to run a similar profile to your second set of graphs. How did you get that time breakdown data out of Ray?
