### ISSUE TITLE
[rllib] Add toggle to disable automatic min/max/mean computation

### ISSUE THREAD

**Issue by jsuarez5341** [ray-project/ray#17631]
Ray automatically computes min, max, and mean for each metric here: https://github.com/ray-project/ray/blob/5a45009ebc40f1a96a75ff52e1532ff4a86f21eb/rllib/evaluation/metrics.py#L177

There is currently no way to disable this feature, which does not play nice with certain integrations. In my case: it spams the wandb integration with tons of redundant plots:
 
![image](https://user-images.githubusercontent.com/14065750/128452397-a4862dff-dda0-4c71-946a-266606e12b48.png)

Can you please add a toggle for this -- ideally for custom and core metrics separately, but a global toggle would suffice

**Comment by nicofirst1** [comment]
Why was this closed?
With the wandb integration having 3 graphs per metric becomes overwhelming

**Comment by michaelfeil** [comment]
For the sake of the wandb exclusion, you could do this with `excludes` keyword in the wandb integration.

I modified this integration to compile the "excludes" as regex string, and allows you to filter with regex, instead of needing to provide the exact string.

`from ray.tune.integration.wandb import *
import re
from ray.tune.utils import flatten_dict, merge_dicts, unflattened_lookup

from ray.tune.utils.util import flatten_dict, unflatten_dict

class CustomWandbLoggerCallback(WandbLoggerCallback):
    """_summary_

    Args:
        WandbLoggerCallback (_type_): _description_
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.excludes_re = re.compile("(" + ")|(".join(self.excludes) + ")")
    
    def log_trial_result(self, iteration: int, trial: "Trial", result: Dict):
        """handles the wandb trial result log.

        Args:
            iteration (int): _description_
            trial (Trial): _description_
            result (Dict): _description_
        """             
        result = flatten_dict(result)
        
        for key, value in result.copy().items():
            if self.excludes_re.match(key):
                result.pop(key)
                
        result = unflatten_dict(result)
            
        super().log_trial_result(iteration=iteration, trial=trial, result=result)`
        
  You can use it like this:
   CustomWandbLoggerCallback(
                    # ray
                    log_config=False,
                    excludes=["warmup_time", ".*custom_metrics.*max", ".*custom_metrics.*min"],
                )
                
  Maybe It would be a cool idea in general to to "re.match(string, result)" of the strings instead of checking it with the pytonic way of s

**Comment by r4hul77** [comment]
Hello, I appreciate the work you guys have done. How to set a  flag such that Rllib logs the custom metric instead of max, min and mean if we have all that data we can calculate it our self. I need that metric for the episode end like the total distance traveled by the robot or the work done by the robots etc
