### ISSUE TITLE
Dead lock in python import thread.

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#17980]
### What is the problem?

`test_args.py` may time out. After digging into it, I found this is caused by a dead lock introduced by #16278. cc @ckw017 @suquark @rkooo567 

This is stack trace of the dead-locked worker

![image](https://user-images.githubusercontent.com/2883335/130209507-184bd1b0-4aab-46ea-b961-83634702dc53.png)

Then main thread is holding the lock and waiting for an actor class to be imported. While the import thread is blocked in `fetch_and_register_remote_function` and cannot proceed to import the actor class.

Theoretically, this dead-lock can happen to any Python app, not only `test_args`. 

### Reproduction (REQUIRED)

run `test_args.py` many times.

**Comment by ckw017** [comment]
Great find, looks like #16304 might be the way to go then (global import lock, or inject lock on imports just for deserializer).

**Comment by ericl** [comment]
@ckw017 I assume you're working on this? cc @suquark

**Comment by ckw017** [comment]
Side tracked on client disconnect stuff.

I think a quick fix would be to drop the lock that introduced the bug, and then introduce the following somewhere before the import when the import thread is started:

```python
real_import = __builtins__.__import__
import_lock = threading.Lock()

def locked_import(*args, **kwargs):
    with import_lock:
       return real_import(*args, **kwargs)

__builtins.__import__ = locked_import
```

This would prevent threads competing on imports. Technically you could still get deadlock if for some reason the act of importing something spawns a new thread that tries to import other stuff, but the case is unlikely.

Also technically some performance implications, although due to GIL I'm under the impression it's not a huge overhead since import logic is already pretty synchronous. 

Injecting a lock like this though does seem like something that warrants discussion. In the meantime it might(?) be worth it to revert the PR and regress on the import conflict issue, since this the problem it fixes is a lot more specific than than the deadlock problem it creates.

**Comment by ericl** [comment]
@ckw017 did you check the test is fixed / not flaky any more now?

**Comment by ckw017** [comment]
@ericl Attempted to reproduce (ran the test on loop ~1000 times) and could not reproduce the failure with the changes, although fwiw I was only able to reproduce once after ~400 attempts before the changes. 

@raulchen If you have more details on how to reproduce or want to try to reproduce again in your environment I can look further into it
