### ISSUE TITLE
[ray client][doc] include ray status and ray monitor into ray command line api docs

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#18527]
currently, [ray command line api docs](https://docs.ray.io/en/master/package-ref.html#the-ray-command-line-api) doesn't include ray status and ray monitor. we should add them

**Comment by javi-redondo** [comment]
Maybe doesn't have to be part of this since it's also a larger item, but I'd consider converging on a single page between:
https://docs.ray.io/en/master/cluster/commands.html
https://docs.ray.io/en/master/package-ref.html#the-ray-command-line-api

There is some redundancy and probability that people will land on either of the 2 pages, but then they'll miss the information from the other page because it doesn't really read cohesively.
