### ISSUE TITLE
[Feature] DirectCall task backpressure required

### ISSUE THREAD

**Issue by MissiontoMars** [ray-project/ray#18703]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Currently, there is no backpressure or flow control on direct call. When transmitting large amounts of data using direct call, the memory usage will rise until oom, if the producer continues to send data without restraint.

Task-based backpressure has been supported in AntGroup for some time. I propose this feature here: https://docs.google.com/document/d/1OGkiOJ-mIxmgNNigO9E7XTCZxzXaj-36u1hQQnAjZgg/edit?usp=sharing

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
This is a nice feature. I think we should review the design doc! Cc @ericl @scv119

**Comment by simon-mo** [comment]
What's the user facing API?

**Comment by MissiontoMars** [comment]
> What's the user facing API?

If the actor function has return value, `actor.func.remote()` returns an `ObjectRef`, the object ref will be None if backpressure occurs.
For the void actor function which has no return value, there is no good solution now, i think maybe the void remote call should be blocked in raycore when backpressured. Any suggestions?  :pray:

**Comment by ericl** [comment]
> the object ref will be None if backpressure occurs.

How about raising an exception on submission? It would be surprising to return None without any additional information.

**Comment by MissiontoMars** [comment]
> > the object ref will be None if backpressure occurs.
> 
> How about raising an exception on submission? It would be surprising to return None without any additional information.

A great suggestion! I prefer to raise an exception now, more user-friendly than return None. Our users can catch the exception when they meet backpressure.

**Comment by simon-mo** [comment]
I thought about this. This seems to increase actor task submission latency by a lot. Before `actor.method.remote()` is asynchronous and the `ObjectRef` returned is almost immediate. When the ref is returned, the task might not even finish sending from the gRPC client. I think this is intentional by design so actor task submission is fast. However, with back pressure, each actor task submission will wait for an RPC to come back.

Is it possible to propagate the actor stats to the client in the background, so we achieve backpressure without compromising performance? For example, the actor can periodically send (or client pull) some statistics about the number of actor call queued and perform backpressure. 

For actor call backpressure, the good thing is that we don't need "exact" semantics for capping number of pending actor calls. One can imagine the following the semantics:
```
0 -> 800 pending calls: ok
800 -> 1000 pending calls: client will start returning error indicating backpressure (i.e. don't even submit it)
1000+ pending calls: actor will immediately fail the actor call (admission control as the final line of defense)
```

**Comment by simon-mo** [comment]
@MissiontoMars can you write the user facing API documentation either here or in the docs so @pcmoritz and take a look and approve the API?

**Comment by MissiontoMars** [comment]
@simon-mo Thanks for your advice!

> However, with back pressure, each actor task submission will wait for an RPC to come back.
This seems not very accurate, actor task submission fails immediately with backpressure, not blocked until RPC comes back. Leave the failure to the application to try again or give up the submission. 
What's the exact impact of actor task submission latency? In my opinion, the end-to-end actor call latency is more important than submission latency. Fortunately, end-to-end latency was not affected even if backpressure occurs.

> For example, the actor can periodically send (or client pull) some statistics about the number of actor call queued and perform backpressure.
Hmm... It's hard to decide an appropriate interval. The interval is positively correlated with the end-to-end latency, if a smaller interval value is selected and there are a large number of actors in the application, the statistics notification becomes a large overhead. In some internal applications, a consumer actor may connect to 1K producer actors at the same time. If the statistics interval is set to 200ms, then the notification RPCs throughput will reach 5K/s.

> For actor call backpressure, the good thing is that we don't need "exact" semantics for capping number of pending actor calls. One can imagine the following the semantics:
Sound good! It's an early warning mechanism. And going a bit further, based on this idea the user can using some policy like the dynamic rebalance when sending remote calls to multiple actors. It should be implemented in the following PRs.

**Comment by simon-mo** [comment]
Ok I think my previous misconception was that the direct call is limiting size of server side queues, but this design just limit the size of client queue. However, because we only mark a request finished inside the client queue when actor finishes that actor tasks, the on_going requests in the client queue also indicates the number of in_flight requests for that actor.

**Comment by MissiontoMars** [comment]
> because we only mark a request finished inside the client queue when actor finishes that actor tasks, the on_going requests in the client queue also indicates the number of in_flight requests for that actor.

Yeah, that'is exactly why the send_queue can be removed.

**Comment by jovany-wang** [comment]
> > the object ref will be None if backpressure occurs.
> 
> How about raising an exception on submission? It would be surprising to return None without any additional information.

So, that means it's an API change raising an exception right?
