### ISSUE TITLE
Consider replacing redis with elasticell for GCS

### ISSUE THREAD

**Issue by yingfeng** [ray-project/ray#1915]
Hi,
Within the Ray project, I notice that the GCS has played a very important role within the cluster, and currently redis is used to serve GCS, as a result, it's easy to be a bottleneck for both high availability and data consistency. I notice that the Ray project team has started some works to resolve redis sharding(bredis) as well as replication (credis) issue, as a result, what about considering our solution [elasticell](https://github.com/deepfabric/elasticell), it's a cloud native redis compatible storage with strong consistency, reliability, and can easily scale without human get involved. If you would like to try this solution, we could provide some help.  Thank you~

**Comment by robertnishihara** [comment]
Hi @yingfeng, we're currently using "Redis modules" quite heavily, which let you define your own custom Redis commands, so I suspect it won't be easy to use elasticcell as a drop in replacement. But let me know if I'm wrong about that.

The current GCS implementation isn't really a bottleneck, since it's easy to start multiple Redis shards, and there is no interaction between different keys. However, handling failures is more of an issue.

**Comment by yingfeng** [comment]
Hi, If data consistency as well as reliability are some issues to be considered, perhaps elasticell could be an alternative.  I noticed that credis provides chain replication for redis, while elasticell is a multi-raft based replication with rocksdb to be the persistence storage.  But it depends, perhaps we will do that replacement in future.
