### ISSUE TITLE
[train] Tune/Datasets with_parameters

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#19292]
Make sure that we can pass arbitrarily large Ray Datasets to `Trainer.to_tune_trainable`.

**Comment by jwyyy** [comment]
Hi @matthewdeng, is anyone currently working on this issue? If no, I would like to give it a try 😄

**Comment by matthewdeng** [comment]
Hey @jwyyy, no one is currently working on this, but I'm actually not sure if there's anything that needs to be done here!

@clarkzinzow do you have any advice on how to think about the serialization cost of `Dataset`s? I tried reading in a 10MB parquet file and the pickled `Dataset` was only 10KB. Is it expected that the pickled `Dataset` will always be relatively small due to the reference based implementation, or would the size scale based on some conditions/attributes?

**Comment by clarkzinzow** [comment]
@matthewdeng The Dataset should always be very small relative to the full data size, since only Ray object references + some metadata is stored in the `Dataset` object. The size will scale with the number of blocks, since there is a Ray object reference and metadata object per block, but you can just calculate the ref + metadata size of one block and extrapolate the expected size of the full `Dataset` object for N blocks.

**Comment by jwyyy** [comment]
> Hey @jwyyy, no one is currently working on this, but I'm actually not sure if there's anything that needs to be done here!
> 
> @clarkzinzow do you have any advice on how to think about the serialization cost of `Dataset`s? I tried reading in a 10MB parquet file and the pickled `Dataset` was only 10KB. Is it expected that the pickled `Dataset` will always be relatively small due to the reference based implementation, or would the size scale based on some conditions/attributes?

@matthewdeng thank you for your confirmation! I will follow the conversation in this discussion to see if there is anything I can help.

**Comment by amogkam** [comment]
Datasets are now supported as a first-class citizen in the new AIR APIs.
