### ISSUE TITLE
[release] wheel_urls nightly test failure

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#19331]
https://buildkite.com/ray-project/periodic-ci/builds/1224#1c2bb8d4-909a-4d70-a317-521d5dc61385

```
There are 4 URLs to retry. Sleeping 10 minutes to give some time for wheels to be built.
List of URLs to retry: ['https://s3-us-west-2.amazonaws.com/ray-wheels/master/74ee99ff99f08a3035a60972a41564ac4f08b7dd/ray-2.0.0.dev0-cp36-cp36m-macosx_10_15_intel.whl', 'https://s3-us-west-2.amazonaws.com/ray-wheels/master/74ee99ff99f08a3035a60972a41564ac4f08b7dd/ray-2.0.0.dev0-cp37-cp37m-macosx_10_15_intel.whl', 'https://s3-us-west-2.amazonaws.com/ray-wheels/master/74ee99ff99f08a3035a60972a41564ac4f08b7dd/ray-2.0.0.dev0-cp38-cp38-macosx_10_15_x86_64.whl', 'https://s3-us-west-2.amazonaws.com/ray-wheels/master/74ee99ff99f08a3035a60972a41564ac4f08b7dd/ray-2.0.0.dev0-cp39-cp39-macosx_10_15_x86_64.whl']
Retrying now...
Traceback (most recent call last):
  File "workloads/wheel_urls.py", line 69, in <module>
    f"URL still not found: {url}"
AssertionError: URL still not found: https://s3-us-west-2.amazonaws.com/ray-wheels/master/74ee99ff99f08a3035a60972a41564ac4f08b7dd/ray-2.0.0.dev0-cp36-cp36m-macosx_10_15_intel.whl
```

I manually checked and the wheels are now available, could be that our Mac wheels are just taking a little longer to build.

@architkulkarni any thoughts on how to make this more robust? I don't think this is a release blocker but we'll probably want to modify the pipeline/test to avoid false positives.

Related issues:
- https://github.com/ray-project/ray/issues/18635
- https://github.com/ray-project/ray/issues/18559

cc @xwjiang2010 @krfricke

**Comment by architkulkarni** [comment]
I checked the bucket and it looks like the Mac wheels appear about 90 minutes after the windows wheels appear.  @simon-mo I think you had mentioned that the nightly tests run at around the same time as the nightly wheel builds.  Is it easy enough to offset either one of these by a couple hours?  

Another option is to change this test to keep trying for up to 90 minutes instead of giving up after 10 minutes.  Since some of the nightly tests appear to take around 80 minutes anyway, this wouldn't have much of a negative impact.  Also, it would only be slow in the uncommon case where the Mac wheels are delayed.  I'll go ahead and make a quick PR for this.
