### ISSUE TITLE
[Java] Use local ip to fix security popups instead of public ip.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#19702]

**Comment by jovany-wang** [comment]
Hi @jjyao could you add some context? so that I'll finish this.

**Comment by jjyao** [comment]
Sorry, didn't really have time to do this task. Basically on macosx, if we listen to 0.0.0.0 then a security window will pop up. To fix it, we can listen to only 127.0.0.1 which is enough since mac is always in the single node mode.

Related PR for python is https://github.com/ray-project/ray/pull/18904.

**Comment by jovany-wang** [comment]
FYI: Previous related issue: https://github.com/ray-project/ray/issues/19690
