### ISSUE TITLE
Dataset with nested refs cannot be checkpointed in workflows

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#20082]
If you comment out the `.map()` part of the test, this fails: https://github.com/ray-project/ray/blob/master/python/ray/workflow/tests/test_dataset.py#L13

It seems to be a bug checkpointing doubly nested refs, which occurs in Datasets on initial read (cc @wuisawesome @iycheng ).

**Comment by wuisawesome** [comment]
Yup, makes sense. We left nested refs as a TODO since they're a bit more complicated to support (especially while maintaining de-dupe behavior since the inner references will change upon recovery). 

I think there are 2 options:

1. Just implement support for nested object references
2. Special case the reducer for lazy blocks in datasets, so we can serialize without serializing the underlying objects (this would also stop us from duplicating data that could be re-read from the initial source.

**Comment by ericl** [comment]
We shouldn't special case anything for specific libraries.

**Comment by iycheng** [comment]
@suquark please close this if you think it's fixed.

**Comment by suquark** [comment]
Now workflow still does not support nested refs, but due to changes in ray dataset, there are no nested refs in related workflow+dataset tests. We can close it for now.
