### ISSUE TITLE
[RFC][Feature] Enhance xlang usability

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#20372]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

I summarized the status quo of xlang usability. Feel free to comment on the doc.
https://docs.google.com/document/d/1m1uIqt1Fj4hBjSse3-rY6uchZPjnaLb86Ni0fxYzvVI/edit?usp=sharing

After we reviewing and discussing it, we'll make a proposal on enhancing it.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jovany-wang** [comment]
@ericl @raulchen

**Comment by ericl** [comment]
Thanks @jovany-wang . Could you also share with comment access? Also cc @gjoliver

**Comment by jovany-wang** [comment]
@ericl DONE

**Comment by jovany-wang** [comment]
@kira-lin cc

**Comment by jovany-wang** [comment]
CC @qicosmos 
We can also consider the CPP worker part as well.

**Comment by jovany-wang** [comment]
Hi @ericl @gjoliver , do you guys have any initial idea or some additional requirements on this topic?
And does @gjoliver is willing to get involve in this?

**Comment by gjoliver** [comment]
yeah, I'd like to champion and help this effort as much as I can. mostly catching up at the point though.
I went through the doc, at a high level, it seems to me, for complex objects, we need to define a serialize/de-serialize API.
and for primitive types, I don't actually understand why msgpack doesn't do the job for us already.
need to read some more I guess.

**Comment by jon-chuang** [comment]
One example of serialization lib with support (and spec) for complex types I've come across: https://borsh.io/
Unfortunately, I don't think support for langs outside of Rust/typescript exists.

**Comment by gjoliver** [comment]
it's unlikely there will be a library that handles serialization of arbitrarily complex objects for multiple languages.
we need to let users define these.
we then can just save and retrieve a bunch of binary blobs or array/dict of binary blobs in object store for anything that needs to be used xlang.

**Comment by ericl** [comment]
It seems that msgpack with extensions may be enough to cover most of the use cases. Basically, we can support a list of common msgpack types, and Object refs, and then also support opaque language-specific blobs, e.g. PythonObject, JavaObject.

**Comment by qicosmos** [comment]
Maybe we could also look at [microsoft bond](https://github.com/microsoft/bond), it support multiple languages, c++, java, python.
[cpp example](https://github.com/microsoft/bond/tree/master/examples/cpp/core/serialization)
[java example](https://github.com/microsoft/bond/tree/master/examples/java/core/serialization)
it can support map and vector:
```
struct Person
{
    0: string first_name;
    1: string last_name;
    2: Color eyes = Brown;
    3: blob hash;
}

struct Example
{
    0: map<uint32, Person> people;
}

struct Struct
{
    0: uint32          n;
    1: string          str;
    2: vector<double>  items;
}
```

**Comment by jovany-wang** [comment]
We have a cross language serializer, which has been serving our internal cross language applications. Let us make it as one of the options when investigating.  @chaokunyang CC
https://docs.google.com/document/d/1nrKrXnyRqiIQqLV1P6i3t6TXQEwduoyLeHLMT2DV-fc/edit#heading=h.yb77c3r8bwjt

**Comment by gjoliver** [comment]
Great doc!

It looks to me Fury is heavily designed to work across Python and Java. Any idea how hard it would be to extend Fury to support languages like C++ or Go?
Is there any plan to open source Fury?

Otherwise, the "Integration With Ray" section looks like the right way to go about this.

**Comment by jovany-wang** [comment]
@gjoliver Yes. We're finding a way to opensource it and integrate it to Ray at least as an option.
Also we're planing to support C++. But we have no plan to support Rust yet.
@chaokunyang

**Comment by chaokunyang** [comment]
> complex



> Great doc!
> 
> It looks to me Fury is heavily designed to work across Python and Java. Any idea how hard it would be to extend Fury to support languages like C++ or Go? Is there any plan to open source Fury?
> 
> Otherwise, the "Integration With Ray" section looks like the right way to go about this.

Fury is language and platform independent. Currently we provided the java and python support and partly c++ support. Because we don't have other requirements yet. But fury serialization is language-independent, it's easy to add other language support. Actually, fury python is based on fury cpp code and use cython to build python implementation. And we are working on go-lang support.

**Comment by chaokunyang** [comment]
> Maybe we could also look at [microsoft bond](https://github.com/microsoft/bond), it support multiple languages, c++, java, python. [cpp example](https://github.com/microsoft/bond/tree/master/examples/cpp/core/serialization) [java example](https://github.com/microsoft/bond/tree/master/examples/java/core/serialization) it can support map and vector:
> 
> ```
> struct Person
> {
>     0: string first_name;
>     1: string last_name;
>     2: Color eyes = Brown;
>     3: blob hash;
> }
> 
> struct Example
> {
>     0: map<uint32, Person> people;
> }
> 
> struct Struct
> {
>     0: uint32          n;
>     1: string          str;
>     2: vector<double>  items;
> }
> ```

bond need schema-compiling, users need to defined a schema using bond `idl` and compile thje code using `gbc`. Since it need schema-compiling, it's impossible for automatic object serialization.

**Comment by chaokunyang** [comment]
> @gjoliver Yes. We're finding a way to opensource it and integrate it to Ray at least as an option. Also we're planing to support C++. But we have no plan to support Rust yet. @chaokunyang

We are planing to provide more cpp support, currently we've provide row-format support and arrow integration in cpp, and python implementation is based on the cpp code. Go-lang support is working-in-progress.

**Comment by jon-chuang** [comment]
> Fury is language and platform independent. Currently we provided the java and python support and partly c++ support. Because we don't have other requirements yet. But fury serialization is language-independent, it's easy to add other language support. Actually, fury python is based on fury cpp code and use cython to build python implementation. And we are working on go-lang support.

Hi @chaokunyang a few qns:
1. Based on your understanding of the alternative serialization options, why would you say Fury manages to get such great speedups of 10-100x? 
2. Why do you need to do runtime codegen if you can precompile your byte code and do all of the analysis and codegen statically?
3. How does it compare to msgpack serialization? What is POJO/struct in the context of Python?

**Comment by chaokunyang** [comment]
> 

Hi @jon-chuang thanks for your questions. Those are very good questions. Let me answer one by one.
1. Based on your understanding of the alternative serialization options, why would you say Fury manages to get such great speedups of 10-100x?

For the first question, the speed up of fury mainly comes from runtime-codegen and memory zero-copy. For any serializable objects, the performance of serialization is determined by the times of memory-copy and the cost of writing fields of objects into buffer. For memory-copy, fury implements a cross-language out-of-band support and off-heap(java only) support which can avoid time-consuming memory copy. For writing fields of objects into buffer, the normal process is that iterate every field of the object, get field value, get serializer of value(which has a hash lookup), write object reference info(whether the object is writed before or is null), write object type meta, invoke serializer.write method which has a virtual method call. For most serializable objects, the most objects of whole object tree are primitive types or strings, the cost of writing those types info buffer is minimal, the process before is much larger than it. For example, if we have an object A which have following structure:
```java
class A{
  int f1; double f2; long f3; float f4; double f5;
  String f6; List<Double> f7;
}
```
Without codegen, we may have 100+ method call which have un-inlineable virtual method call, if the list size is big, the method call is more.
Runtime-codegen is a performance omtimization for java, and what it does is try to eliminate those process and make the generated code can be inlined by java jit compiler, so that we can get the speedup. For above class with codegen, the whole serialization code can be generated dynamically and based on the type information of class A, we can avoid all those virtual method calls, in the end java jit can compile the whole serialization code into one method without any other method call. This is where the fury brings the speedup. Other coding tricks such as field reodering to increasing the code cache are also used in fury. Note that the runtime-codegen is a performance omtimization for java, it's not needed by the fury protocal and doesn't bring extra complexity into other languages implementations

2. Why do you need to do runtime codegen if you can precompile your byte code and do all of the analysis and codegen statically?

A key requirements for serialization framework is the ease of use. It should automatically transfer an object from one process/language to another process/language. Fury codegen is only for java speedup, if we need the users do the codegen manually and statically, it's not easy-to-use compared to jdk/fst/kryo serialization which all don't need static compiling. But I guess what you mean is define a schema and generate the class based on the schema case. In most cases the the objects which need the serialization are defined by the users, those class are not the classes generated based on the schema case. For example, the class `A` in question 1 are defined by the users, and the user need to serialize this class automatically. If the class are generated by a schema, users can just use protobuf or other libraries and do the serialization manually. 

3. How does Fury compare to msgpack serialization? 

a. `msgpack`/`protobuf` itself is just a serialization protocal, what a serialization framework do is serialize an object(maybe customized type) into binary which `msgpack` doesn't support. 
b. For nested/complext objects, it may hold reference to other objects or hold reference to itself. For example, when deserializing following `list_`, `list_[2]` and `list_[3]` should be same object, `list_` and `list_[3]` should be same object too.
```python
s = "str"
list_ = [1, 2 s, s]
list_.append(list_)
```
A serialization frameowrk can handle those reference relationship and restore the reference relationship when deserialization. But it's not supported by `msgpack`/`protobuf`/`bond`. The reference relationship is important, since reference relationship is supported by language-native serialization such as pickle, if reference relationship can't be retained by cross-language serialization framework, then those types can't be serialized by cross-language serialization framework, otherwise the reference relationship will be lost and the correctness will be affected or recusrion_error occurs when serialization.
c. Type inconsistency: When deserializing an `Integer` serialized by `msgpack` in java, we get `Byte` returned if the value is in byte range. See more on https://github.com/ray-project/ray/issues/20369. For more complex types such as serializing a `LinkedList` in java which `msgpack` doesn't support yet, the deserialized type should be a `LinkedList` instead of an `ArrayList`. And it's not easy to support it in messagepack.

4. What is POJO/struct in the context of Python?
Basically a class with some fields can be taken as an POJO/struct. Since we can add any attr to python object dynamically, Fury need the class has typehints for it's fields needing the serialization to tell fury which fields need to bed serialized. In python all dataclass can be taken as an POJO/struct.

5. How complex is the fury project in terms of LOC? And would you say its strength is in terms of the chosen binary format, or the implementation? How complex is an implementation for a particular language in terms of loc?

Fury is a light-weight serialization library. Acutally implementing fury cross-language ability for a new language is less than 2500 lines.
For java serialization, the strength is the implementation(runtime-codegen) and out-of-band support. For cross-language serialization, the strength is the chosen binary format which supports reference relationship and out-of-band serialization.

**Comment by chaokunyang** [comment]
> > Fury is language and platform independent. Currently we provided the java and python support and partly c++ support. Because we don't have other requirements yet. But fury serialization is language-independent, it's easy to add other language support. Actually, fury python is based on fury cpp code and use cython to build python implementation. And we are working on go-lang support.
> 
> Hi @chaokunyang a few qns:
> 
> 1. Based on your understanding of the alternative serialization options, why would you say Fury manages to get such great speedups of 10-100x?
> 2. Why do you need to do runtime codegen if you can precompile your byte code and do all of the analysis and codegen statically?
> 3. How does Fury compare to msgpack serialization? What is POJO/struct in the context of Python?
> 4. How complex is the fury project in terms of LOC? And would you say its strength is in terms of the chosen binary format, or the implementation? How complex is an implementation for a particular language in terms of loc?

Hi @jon-chuang thanks for your questions. Those are very good questions. Let me answer one by one.
1. Based on your understanding of the alternative serialization options, why would you say Fury manages to get such great speedups of 10-100x?
The speed up of fury mainly comes from runtime-codegen and memory zero-copy. For any serializable objects, the performance of serialization is determined by the times of memory-copy and the cost of writing fields of objects into buffer. For memory-copy, fury implements a cross-language out-of-band support and off-heap(java only) support which can avoid time-consuming memory copy. For writing fields of objects into buffer, the normal process is that iterate every field of the object, get field value, get serializer of value(which has a hash lookup), write object reference info(whether the object is writed before or is null), write object type meta, invoke serializer.write method which has a virtual method call. For most serializable objects, the most objects of whole object tree are primitive types or strings, the cost of writing those types info buffer is minimal, the process before is much larger than it. For example, if we have an object A which have following structure:
```java
class A{
  int f1; double f2; long f3; float f4; double f5;
  String f6; List<Double> f7;
}
```
Without codegen, we may have 100+ method call which have un-inlineable virtual method call, if the list size is big, the method call is more.
Runtime-codegen is a performance omtimization for java, and what it does is try to eliminate those process and make the generated code can be inlined by java jit compiler, so that we can get the speedup. For above class with codegen, the whole serialization code can be generated dynamically and based on the type information of class A, we can avoid all those virtual method calls, in the end java jit can compile the whole serialization code into one method without any other method call. This is where the fury brings the speedup. Other coding tricks such as field reodering to increasing the code cache are also used in fury. Note that the runtime-codegen is a performance omtimization for java, it's not needed by the fury protocal and doesn't bring extra complexity into other languages implementations

2. Why do you need to do runtime codegen if you can precompile your byte code and do all of the analysis and codegen statically?
A key requirements for serialization framework is the ease of use. It should automatically transfer an object from one process/language to another process/language. Fury codegen is only for java speedup, if we need the users do the codegen manually and statically, it's not easy-to-use compared to jdk/fst/kryo serialization which all don't need static compiling. But I guess what you mean is define a schema and generate the class based on the schema case. In most cases the the objects which need the serialization are defined by the users, those class are not the classes generated based on the schema case. For example, the class `A` in question 1 are defined by the users, and the user need to serialize this class automatically. If the class are generated by a schema, users can just use protobuf or other libraries and do the serialization manually. 

3. How does Fury compare to msgpack serialization? 
  * `msgpack`/`protobuf` itself is just a serialization protocal, what a serialization framework do is serialize an object(maybe customized type) into binary which `msgpack` doesn't support. 
  * For nested/complext objects, it may hold reference to other objects or hold reference to itself. For example, when deserializing following `list_`, `list_[2]` and `list_[3]` should be same object, `list_` and `list_[3]` should be same object too.
```python
s = "str"
list_ = [1, 2 s, s]
list_.append(list_)
```
A serialization frameowrk can handle those reference relationship and restore the reference relationship when deserialization. But it's not supported by `msgpack`/`protobuf`/`bond`. The reference relationship is important, since reference relationship is supported by language-native serialization such as pickle, if reference relationship can't be retained by cross-language serialization framework, then those types can't be serialized by cross-language serialization framework, otherwise the reference relationship will be lost and the correctness will be affected or recusrion_error occurs when serialization.
  * Type inconsistency: When deserializing an `Integer` serialized by `msgpack` in java, we get `Byte` returned if the value is in byte range. See more on https://github.com/ray-project/ray/issues/20369. For more complex types such as serializing a `LinkedList` in java which `msgpack` doesn't support yet, the deserialized type should be a `LinkedList` instead of an `ArrayList`. And it's not easy to support it in messagepack.

4. What is POJO/struct in the context of Python?
Basically a class with some fields can be taken as an POJO/struct. Since we can add any attr to python object dynamically, Fury need the class has typehints for it's fields needing the serialization to tell fury which fields need to bed serialized. In python all dataclass can be taken as an POJO/struct.

5. How complex is the fury project in terms of LOC? And would you say its strength is in terms of the chosen binary format, or the implementation? 
Fury is a light-weight serialization library. Acutally implementing fury cross-language ability for a new language is less than 2000 lines.
For java serialization, the strength is the implementation(runtime-codegen) and out-of-band support. For cross-language serialization, the strength is the chosen binary format which supports reference relationship and out-of-band serialization.

6. How complex is an implementation for a particular language in terms of loc?
Implementing fury cross-language ability for a new language is less than 2000 lines.

**Comment by jon-chuang** [comment]
Thank you for your detailed reply!

From what I understand then, Fury aims to be a performant serialization framework that can serialize types dynamically without needing to provide schemas. The speedups are against naive approach when no schemas exist, by leveraging JIT to compress multiple method calls into a single method, and additional optimizations.

For Rust, one typically generates schemas via the Serde macro framework, and it works with all supported serialization formats (incl msgpack, json etc). However, perhaps such a framework is missing from Java, while C++ also requires `MSGPACK_DEFINE` and `MSGPACK_DEFINE_MAP`.  

I am a bit confused about the type for a POJO type that is interoperable between Python and Java, thought. Doesn't this need the class to be defined in both languages? Generally, I am just unfamiliar with how POJO is serialized. For one thing, I am unclear if the type information like field names are encoded in the serialization format itself, or has some other way of propagating.

It seems that Fury is still good for some complex types with references as mentioned, but its unclear what the picture is for structs.

Actually, what do you mean by "out-of-band" serialization?

**Comment by chaokunyang** [comment]
@jon-chuang https://docs.google.com/document/d/12VvpGw_tEW2fb_Xj5Crmoh-zHR6Jx4ggRtEZjbPcMGs/ Here is a more complete introduction for fury.

**Comment by chaokunyang** [comment]
> @chaokunyang Thank you for your detailed reply!
> 
> From what I understand then, Fury aims to be a performant serialization framework that can serialize types dynamically without needing to provide schemas. The speedups of Fury are against naive approach, by leveraging JIT to compress multiple method calls into a single method, and additional optimizations.
> 
> For Rust, one typically generates schemas for arbitrary types via the Serde macro framework, with field attributes for configurability, and it works with all supported serialization formats under Serde (incl msgpack, json, bincode, yaml etc).
> 
> However, perhaps such a framework is missing from Java, while C++ requires format-specific declarations like `MSGPACK_DEFINE` and `MSGPACK_DEFINE_MAP`.
> 
> I am a bit confused about the type for a POJO type that is interoperable between Python and Java, though. Doesn't this need the class to be defined in both languages? Generally, I am just unfamiliar with how POJO is serialized. For one thing, I am unclear if the type information like field names are encoded in the serialization format itself, or has some other way of propagating.
> 
> It seems that Fury is still good for some complex types with references as mentioned, but its unclear to me what the picture is for structs (or POJO).
> 
> Actually, what do you mean by "out-of-band" serialization?

For pojo(java)/data-class(python)/struct(cpp) serialization, tag will be serialized if configured, by default fury order all fields and serialize them one by one. Serializing by tag name is only used for class compatibility and evolution. msgpack didn't consider there may be subclass instance for field value of field type, so some info will be lost when deserialization. Maybe it's smae case for rust?

**Comment by chaokunyang** [comment]
For POJO, the reference are still considered. For exmaple, if two fields of a pojo reference an object, it will be serialized only once, if the object is already serialized before, it won't be serialized at all.

**Comment by chaokunyang** [comment]
For  "out-of-band" serialization, you can reference pickle5 outt of band serialization proposal:https://www.python.org/dev/peps/pep-0574/ @jon-chuang

**Comment by chaokunyang** [comment]
> @jon-chuang https://docs.google.com/document/d/12VvpGw_tEW2fb_Xj5Crmoh-zHR6Jx4ggRtEZjbPcMGs/ Here is a more complete introduction for fury.

@jon-chuang Any comments would be appreciated

**Comment by jovany-wang** [comment]
What languages should be considered in xlang? I believe currently Python C++ and Java are necessary to be considered. Should we consider the Rust or Golang? @jon-chuang @ericl

**Comment by ericl** [comment]
Hmm good question, I think it's an important requirement to support Go/Rust. Otherwise, we would essentially be locking out those languages or requiring some other serializer to be implemented for them, which would defeat the purpose of having a unified x-lang experience.
