### ISSUE TITLE
[Bug] test_basic_2_client_mode is flaky

### ISSUE THREAD

**Issue by ckw017** [ray-project/ray#20376]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

Possibly related to object ref changes

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Anything else

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mattip** [comment]
A segfault in `test_actor_recursive` in `test_basic_2_client_mode` seems to be the cause, and this tests is scoring quite high on flaky-tests.ray.io:
![Screenshot from 2022-01-12 00-52-21](https://user-images.githubusercontent.com/823911/149034158-ae4aa23f-b854-4061-a715-a467e49df53d.png)

**Comment by czgdp1807** [comment]
Note that `test_basic_2_client_mode` times out in [buildkite CI](https://buildkite.com/ray-project/ray-builders-branch/builds/5426#044a26a9-6bb7-4e60-babe-26ff63af0d71) because it takes more than 300s. Now, we might need to take a similar approach as in https://buildkite.com/ray-project/ray-builders-branch/builds/5426#044a26a9-6bb7-4e60-babe-26ff63af0d71 i.e., split the test into smaller chunks so that each split takes lesser time.

Also, the test doesn't always times out so most probably it's the randomness in execution speed on Windows which is causing it to time out and not the code in Ray itself (AFAIK).

**Comment by czgdp1807** [comment]
I reproduced the failure and found that `test_basic_2_client_mode` times out at different points. Like in one run `test_actor_recursive` didn't complete and in the second run it timed out at some other test. So, I'd say the problem is that there are too many tests to be executed in `test_basic_2` and sometimes all the tests don't complete within 300s. We can follow the same approach as in https://github.com/ray-project/ray/pull/20433/files i.e., splitting the tests.

**Comment by mwtian** [comment]
This issue is not Windows specific. It could be a deadlock during shutdown. But if it is reproducible on Windows, feel free to post the stack trace of deadlock here. If splitting helps, that's great. If not, I will revisit this later.

**Comment by mattip** [comment]
The strange thing is that locally the previous tests take about the same amount of time, so it is not that the machine overall is slow.
test | CI time | local time
---|---|---
test_modin | 3s | 3s
test_actor_pool | 105 | 93s
test_asyncio | 45s | 40s
