### ISSUE TITLE
[Bug] Dataset .to_pandas() throws

### ISSUE THREAD

**Issue by crclark** [ray-project/ray#20488]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

`ray.data.from_items([0, 1, 2, 3, 4]).to_pandas()` throws an exception: `AttributeError: 'list' object has no attribute 'to_pandas'`.

I'd expect it to return a Pandas dataframe with a single column, since that is what `ray.data.from_items([0, 1, 2, 3, 4]).to_arrow()` does.

### Versions / Dependencies

Ray 1.8.0, Python 3.8.4

### Reproduction script

```
import ray.data
ray.data.from_items([0, 1, 2, 3, 4]).to_pandas()
```

### Anything else

A workaround is to do `pyarrow.concat_tables(ray.data.from_items([0, 1, 2, 3, 4]).to_arrow()).to_pandas()`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
@crclark I've confirmed that this is fixed in master:
```
In [1]: import ray
In [2]: ray.init()
In [3]: ray.data.from_items([0, 1, 2, 3, 4]).to_pandas()
Out[3]:
   0
0  0
1  1
2  2
3  3
4  4
```
Specifically, fixed by [this commit](https://github.com/ray-project/ray/commit/f5dfe6c1580443b3ce0a149b4e7f9d108cf43b6d), which should be released in a few days when the 1.10 release comes out.

I'm closing this issue for now, please reopen if the fix doesn't work for you!
