### ISSUE TITLE
[workflow] log is not pushed to driver if run multiple times

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#20524]
```
import ray
from ray import workflow
ray.init(address='auto')
workflow.init()

@workflow.step
def s():
    return 10


print(s.step().run())
```
Run the above script multiple times and only the first one will print the log correctly. Need to always push the log to the driver.

**Comment by wdapalma** [comment]
I noticed that if I use create a program to subscribe to the `RAY_LOG_CHANNEL` channel in redis, all the log messages are there, however they are associated with the initial `job_id` of the `WorkflowManagerActor`. Because of that, the additional workflows started have a different `job_id` associated with the driver and discards the logs published with the old job_id.

**Comment by iycheng** [comment]
@wdapalma  that's right.  The reason here is that the actor is started with the old driver and it'll only push the log to the old ones. What we need here is to push the log to the new driver. `push_error_to_driver` could be something we can update, but I haven't got time to give it a try.

**Comment by iycheng** [comment]
https://github.com/ray-project/ray/blob/master/python/ray/_private/ray_logging.py @lchu-ibm

**Comment by lchu-ibm** [comment]
@iycheng thanks for the pointer. I think a more general way to describe this is "Workflow has kept the initial **Ray Runtime** due to detached WorkflowManagmentActor."

```
import ray
from ray import workflow

ray.init(address='auto')
workflow.init()

# runtime A: {'job_id': JobID(2e000000), 'node_id': NodeID(b4afbfe3a24f773951e7a857697724fdc7dfa0ddf6d61ea4e58da6fe), 'namespace': '64adb95e-c68d-4463-9f68-57514c2aca70'}
print(ray.get_runtime_context().get())

# runtime B:  {'job_id': JobID(01000000), 'node_id': NodeID(b4afbfe3a24f773951e7a857697724fdc7dfa0ddf6d61ea4e58da6fe), 'namespace': 'b6431e8b-0875-4326-9c2c-443a573bf95d', 'task_id': TaskID(c0e6efeeb84daafaffffffffffffffffffffffff01000000)}
@workflow.step
def s():
    return ray.get_runtime_context().get()
print(s.step().run())

# runtime C: {'job_id': JobID(2e000000), 'node_id': NodeID(b4afbfe3a24f773951e7a857697724fdc7dfa0ddf6d61ea4e58da6fe), 'namespace': '64adb95e-c68d-4463-9f68-57514c2aca70', 'task_id': TaskID(fde118e4e9277b0fffffffffffffffffffffffff2e000000)}
@ray.remote
def f():
    return ray.get_runtime_context().get()
print(ray.get(f.remote()))
```

the worker-side runtime C is identical to driver-side runtime A (from `ray.state.next_job_id()`), but worker-side workflow's runtime B is picked up from the initial runtime when workflowManagementActor was firstly created. 

I am not sure if we should fix from logging side as there might be other things suffer from non-updating job_id, namespace, etc., what are the challenges if we try to see if we can fix it on the actor side to make job_id, etc. updated?  

Also, if not fixing on actor side, all session's logs are saved as the same job_id e.g. `worker-worker_id-01000000-pid.err`, even we could re-route to the new session, how do we know which of them to reroute?

**Comment by iycheng** [comment]
@lchu-ibm it's not about the runtime but about the job_id. Basically, logs will be pushed to the driver. 
The driver of WorkflowManager is the script where the workflow.init runs.

The thing we need to do is to push the log to the right driver. All drivers listen to the log channel, so we just need to log to the right driver.

This means: 1) we need to understand how logging is working here. (you need to check the code for some implementation details); 2) carry the job_id and push it to the right job_id when doing logging.

**Comment by lchu-ibm** [comment]
@iycheng I feel maybe we should escalate this issue to Ray Core rather than trying to fix it on the workflow side.  As this is essentially a more general problem for detached actors (or even more general - it is a problem for re-usable workers.)

As we discussed, for any re-usable workers, since the log is configured during initial worker setup (https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/workers/default_worker.py?L231), any usable worker will write logs to initial driver's job id.

So I think this is more a Ray Core problem, and it is just workflow might be the most common use case atm for detached actors while detached actors might be the most common use case for a re-usable workers.

**Comment by lchu-ibm** [comment]
A simple script to reproduce the issue:

script1.py
```
import ray
import logging
ray.init(address='auto', namespace="test")
@ray.remote
class Counter(object):
    def __init__(self):
        logging.basicConfig(level=logging.INFO)
        self.value = 0

    def increment(self):
        self.value += 1
        return self.value

    def get_counter(self):
        logging.info("value: {}".format(self.value))
        return self.value

counter = Counter.options(name="CounterActor", lifetime="detached").remote()
print(ray.get(counter.get_counter.remote()))
```

script2.py
```
import ray
import logging
ray.init(address='auto', namespace="test")

counter = ray.get_actor("CounterActor")
ray.get(counter.get_counter.remote())
```

The logs won't be there in script2.py, for the same reason.  And this is outside the scope of workflow

**Comment by lchu-ibm** [comment]
Even for non-detached actor, the same issue will be there.  E.g. in the same example above, if the actor is not detached but script 1 is not exited, script 2 has the same issue of lost logs in the driver.

**Comment by iycheng** [comment]
@lchu-ibm we don't need to fix it in ray core layer since this is the behavior we'd like. 

The thing here is that we need to redirect the log to the right driver by updating the logging library.

We don't need to do this for most jobs. For workflow, we need to do this because it damages UX.
