### ISSUE TITLE
[Bug][Dataset] Inference nightly test download regression

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#20625]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

There was a large performance regression in the inference nightly test. Bisecting showed that it was caused by #199660. Before that commit the download stage of the pipeline was taking 50s to complete, after that, it took 150s to complete. 

### Versions / Dependencies

#19660

### Reproduction script

`python e2e.py --session-name=inference_$RANDOM --test-config=nightly_tests/dataset/dataset_test.yaml --test-name=inference`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
Thanks for reporting this! This seems to be due to LazyBlockList. With block splitting, we need call ray.get() while iterating over the list since we need to ray.get() the inner refs. This means task submission gets delayed.

https://github.com/ray-project/ray/pull/20660/files will be a short term mitigation. Working on another PR to fix this properly for the block splitting case.
