### ISSUE TITLE
[API] Disallow @serve.deployment() with no arguments

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#20650]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

Both of the following work

```python
@serve.deployment
def hello(request):
    name = request.query_params["name"]
    return f"Hello {name}!"
```

```python
@serve.deployment()
def hello(request):
    name = request.query_params["name"]
    return f"Hello {name}!"
```

We should disallow the second one (with a great error message of course). Similarly, you can do `@ray.remote`, but you can't do `@ray.remote()`.

### Versions / Dependencies

I tested this with Ray 1.8.0.

### Reproduction script

Currently this succeeds, but it should give an error.

```python
import requests

from ray import serve

serve.start()


@serve.deployment()
def hello(request):
    name = request.query_params["name"]
    return f"Hello {name}!"


hello.deploy()

# Query our endpoint over HTTP.
response = requests.get("http://127.0.0.1:8000/hello?name=serve").text
assert response == "Hello serve!"
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by simon-mo** [comment]
> We should disallow the second one (with a great error message of course)

@robertnishihara what's wrong with both of them? 

This is not the case of having "one way to do things" because:
- we advocate `@serve.deployment` for simple use and with `@serve.deployment(...)` for advanced configuration. You have to know both.
- the empty `@serve.deployment()` doesn't do any harm and does not exist in the doc. if a user stumble on to this, it cause no harm. forcing users to migrate off doesn't improve readability nor performance, it just slow down time to get the code working.
- `@serve.deployment` is simply a syntactic sugar for empty `@serve.deployment()`. users can see that and understand.

**Comment by robertnishihara** [comment]
Mostly aesthetic, but 
- Consistency with `@ray.remote`
- Generally good to have one recommended way of doing things

I came across some code somewhere that used both in the same file, but now I'm having trouble finding it.
