### ISSUE TITLE
[doc] API doc show things like "Mock name='mock.ObjectRef' id='140639907666512'"

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#20892]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

https://docs.ray.io/en/latest/package-ref.html#ray-wait

shows

ray.wait(object_refs: List[<Mock name='mock.ObjectRef' id='140639907666512'>], *, num_returns: int = 1, timeout: Optional[float] = None, fetch_local: bool = True) → Tuple[List[<Mock name=’mock.ObjectRef’ id=’140639907666512’>], List[<Mock name=’mock.ObjectRef’ id=’140639907666512’>]][source]

It seems to have been this way since 1.6

### Versions / Dependencies

1.6+

### Reproduction script

https://docs.ray.io/en/latest/package-ref.html#ray-wait

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by matthewdeng** [comment]
@maxpumperla do you have any ideas about this one? cc @bveeramani

**Comment by maxpumperla** [comment]
@matthewdeng this problem was introduced in 1.7, actually. Interestingly it's not at all related to a doc build system change, but rather due to the fact that 1.6 and earlier versions did not have type annotations, see here:

https://github.com/ray-project/ray/blob/ray-1.6.0/python/ray/worker.py#L1698

and here for reference:

https://github.com/ray-project/ray/blob/ray-1.7.0/python/ray/worker.py#L1699-L1704

Since we mock all kinds of modules in sphinx (we've been doing this since the dawn of time), we get these `Mock` names for some `autofunction`s with type annotations (see here for mocked modules: https://github.com/ray-project/ray/blob/ray-1.7.0/doc/source/conf.py#L59-L65).

Since we didn't have types before 1.7, this never got noticed. Now that we know, we should probably rethink the way we mock ray core functionality there.
