### ISSUE TITLE
[Bug] [Serve] Ray hangs on API methods 

### ISSUE THREAD

**Issue by spolcyn** [ray-project/ray#20971]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

After connecting to Ray and Ray Serve on a remote Ray cluster (running on k8s), running a job, and then waiting for a little while, future `serve`/`ray` methods seem to block indefinitely.

### Versions / Dependencies

ray[serve]==1.9.0
Python 3.7.12

### Reproduction script

Repro script with experiment results commented (Note: must edit remote cluster URL):

```python
import logging
import time

import ray
from ray import serve
from tqdm import tqdm

logger = logging.getLogger("ray")


def init_ray(use_remote: bool = True, verbose: bool = True):
    logger.info("Entering init_ray")
    if ray.is_initialized():
        logger.info("Ray is initialized")
        # NOTE: If you put `ray.shutdown()` here and remove the return, the script will also hang on that.
        return

    if use_remote:
        # This should be a remote ray cluster connected to with the Ray Client
        address = "ray://<your Ray client URL>:10001"
        logger.info("Running ray.init")
        ray.init(address=address, namespace="serve", log_to_driver=verbose)

        # Start Ray Serve for model serving
        # Bind on 0.0.0.0 to expose the HTTP server on external IPs.
        logger.info("Running serve.start")
        serve.start(detached=True, http_options={"host": "0.0.0.0"})


DEPLOYMENT_NAME = "DeployClass"
ray_autoscaling_config = {
    "min_replicas": 1,
    "max_replicas": 100,
    "target_num_ongoing_requests_per_replica": 5,
}


@serve.deployment(
    name=DEPLOYMENT_NAME,
    version="v1",  # required for autoscaling at the moment
    max_concurrent_queries=10,
    _autoscaling_config=ray_autoscaling_config,
)
class DeployClass:
    def f(self, i: int):
        logger.info(f"Handling {i}")
        time.sleep(2)
        return i


def deploy_deployment():
    try:
        # NOTE: This is the line it stalls on! The first `serve.` line
        logger.info("Trying to get existing deployment")
        return serve.get_deployment(DEPLOYMENT_NAME)
    except KeyError:
        logger.info("DeployClass is not currently deployed, deploying...")
        DeployClass.deploy()
        return DeployClass


inputs = list(range(10))

for i in range(5):
    logger.info("Starting ray init")
    init_ray(True, True)
    logger.info("Deploying deployment")
    deployment = deploy_deployment()
    logger.info("Getting handle")
    handle = deployment.get_handle()

    logger.info("Making method calls")
    futures = [handle.f.remote(i) for i in inputs]
    logger.info("Getting results")
    results = ray.get(futures)
    logger.info(f"Results: {results}")

    # simulate doing lots of other work...
    # Confirmed to not work:
    # 1) 10m (waited 5m on serve.get_deployment before interrupting). Also saw
    #    `Polling request timed out` error on `listen_for_changes`
    # 2) 2m (waited 10m on serve.get_deployment before interrupting). Also saw
    #    `Polling request timed out` error on `listen_for_changes`
    # 3) 1m (waited 10m on serve.get_deployment before interrupting). Also saw
    #    `Polling request timed out` error on `listen_for_changes`
    # 4) 30s (waited 10m on serve.get_deployment before interrupting). Also saw
    #    `Polling request timed out` error on `listen_for_changes`
    # Confirmed to work sometimes:
    # 5) 15s (worked 2x, then stalled out on iteration #3)
    # 5) 30s (worked 1x, then stalled out on iteration #2)
    logger.info(f"Waiting for a while...")
    for minute in tqdm(range(1)):
        logger.info(f"Waiting a minute (already waited {minute})")
        time.sleep(60)
```

### Anything else

Every time for certain wait periods. See `Confirmed to work`/`Confirmed to not work` experiments at the bottom of the repro script.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jiaodong** [comment]
hi @spolcyn i tried to reproduce this using my local ray cluster address 127.0.0.1 with 60s wait time under your "confirmed not to work"and it runs fine: https://gist.github.com/jiaodong/61e07fbfb92b373e236b5a2209f9a27a

So i think it has something to do with ray client connect with remote ray cluster. Let me try to repro it on remote cluster and see if it's consistent. Meanwhile I think you can try to do the remote `serve.start` by using our job submission API instead: https://docs.ray.io/en/latest/ray-job-submission/overview.html such that you submit and run your serve deployment script on remote ray cluster, but then interact with it via your given HTTP endpoint rather than serve handle.

**Comment by spolcyn** [comment]
Hi @jiaodong  -- yes, it's just the remote ray cluster we're having problems with. We ran locally on some of our larger nodes as a temporary workaround for certain use cases.

We'll take a look at the job submission API.

**Comment by jiaodong** [comment]
@spolcyn i'm giving this suggestion mostly because that's very likely better way to run your workload. Ray client technically gives you the interactive experience but starting serve there and calling serve APIs on your script via ray client is not quite the recommended way to run your service, specially for remote ray cluster -- it's better to have a clear client - server separation and communicate via exposed HTTP endpoint rather than assuming everything is working in one ray cluster while it's actually not.

It will be a legit P0 issue if it breaks consistently on remote cluster however, which is what i'm trying to reproduce :)

**Comment by spolcyn** [comment]
@jiaodong Thanks for working on this! Glad the issue context was helpful for reproducing.

**Comment by jiaodong** [comment]
This issue is actually also reproducible on laptop. The key is to enforce using ray client by 

`ray start --head`

Then use `ray://127.0.0.1:10001` as address. The symptom on laptop is identical to remote cluster.

**Comment by edoakes** [comment]
cc @ckw017 looks to be a ray client-specific issue

**Comment by jiaodong** [comment]
While the deployment script hangs on my laptop, i can still use ray client to connect to the running controller actor in "serve" namespace, make actor calls to it such as `get_deployment_info()`.

This suggests the issue likely happen at serve's api.py level regarding the use of ray client that led to deadlock, rather than controller implementation itself that is not responding.

```
❯ ipython
iPython 3.8.12 (default, Oct 12 2021, 06:23:56)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import ray

In [2]:

In [2]: ray.init(address="ray://127.0.0.1:10001")
Out[2]: ClientContext(dashboard_url='127.0.0.1:8265', python_version='3.8.12', ray_version='2.0.0.dev0', ray_commit='{{RAY_COMMIT_SHA}}', protocol_version='2021-12-07', _num_clients=2, _context_to_restore=<ray.util.client._ClientContext object at 0x7f8188451c70>)

In [3]: controller = ray.get_actor('SERVE_CONTROLLER_ACTOR', namespace="serve")

In [4]: ray.get(controller.get_deployment_info.remote("DeployClass"))
Out[4]: (<ray.serve.common.DeploymentInfo at 0x7f8188f3ab80>, None)
```

**Comment by edoakes** [comment]
@simon-mo is there any reason why the callback in longpollclient would not be async?

As a meta point, this callback mechanism is really nasty and I'm not surprised it caused a bug like this. We should try to come up with a way to make this less race-condition-prone.

**Comment by ckw017** [comment]
After more digging, the it looks like the hanging is from:

1. remote call to listen_for_change is made
2. when response (timeout error) from listen_for_change is back, the dataclient invokes `callback1`
3. `callback1` set by serve logic sees that a timeout error occurs
4. `callback1` creates a new object ref with a new listen_for_change.remote(). This is asynchronous, i.e. the object ref isn't populated yet.
5. `callback1` tries to register a `callback2` onto the new object ref
6. to register `callback2`, we need to wait for the new object ref to be populated, which requires the dataclient to process the response
7. we can't process the response, because we're still waiting for `callback1` to return

**Comment by simon-mo** [comment]
@edoakes the callback should not block at all.

@ckw017 Great finding! what's your ideal next step here? Should we fix this in Ray Client or Serve must accept this limitation?

**Comment by ckw017** [comment]
Two fixes I can think of here would be:
- Have [this part run](https://github.com/ray-project/ray/blob/master/python/ray/serve/long_poll.py#L104-L105) on a separate (very short lived) thread, which would let the dataclient carry on/bypass the deadlock. Obvious downside is it seems a bit overkill
    - Alternatively, have some long running separate thread/task that spawns the new listen_for_change call based on a non-blocking signal from the callback 
- If possible, only run LongPollClient's remotely if the driver script is in client mode, but not really sure if this is possible (not super sure how LongPollClient is used)

Otherwise, a client fix could be worked out, but would require some pretty significant changes to the architecture. cc @mwtian for any thoughts, issue is related to how we handle asynchronous remote methods

**Comment by simon-mo** [comment]
hmm... okay i think i find a way for Serve to get around this. I'll make a PR by EOD. @ckw017 can you create a separate issue for Ray client to track this?

**Comment by mwtian** [comment]
Great investigations! To summarize Chris's findings, Ray client uses a single thread to process responses from get() and remote() calls, and run `ClientObjectRef._on_completed()` callbacks. During the processing of a response, the thread runs a `ClientObjectRef._on_completed()` callback that makes a `remote()` call and waits for the response containing the object ID. This causes deadlock on the thread.

I agree we should avoid non-trivial work (anything calling into Ray worker) inside the `_on_completed()` callbacks, otherwise it feels risky even in Ray cluster mode. There was a plan to move ray.get() calls and responses off the data thread, and support multi-threaded ray.get() and ray.put() in Ray client. That would avoid the issue too.

**Comment by simon-mo** [comment]
PR is up #21104

**Comment by jpatidar30** [comment]
@simon-mo @ckw017 i am still facing this issue in version `2.22.0`. There seems to be an related open issue as well #38605
