### ISSUE TITLE
[Bug] Fail to access GCS data using Datasets API with token="cloud"

### ISSUE THREAD

**Issue by daikeshi** [ray-project/ray#21030]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

We host Ray cluster on a GKE using Ray k8s operator, and Ray head node and worker pod are configured to use the GKE workload identity to access GCS datasets. 

On my local laptop, I'm using the following code to load the GCS dataset. 

```python
from gcsfs import GCSFileSystem
ray.init("ray://127.0.0.1:10001", runtime_env = {"pip": ["gcsfs==2021.11.1"]})
fs = GCSFileSystem(project="ml-sketchbook", token="cloud")
df = ray.data.read_csv("gs://ml-sketchbook-keshi/ray/data/simpleHIGGS.csv", filesystem=fs)
```

After the long wait, I got the following error:
```
google.auth.exceptions.RefreshError: Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true 
from the Google Compute Enginemetadata service. Compute Engine Metadata server unavailable
```

I think what happened is that the above piece of code tried to connect Google's Metadata server from my local laptop although it should use my local gcloud crentidenal. I don't have a way to config `fs` to use different authentication methods (with or without tokens) through Ray. If I remove the token field from `GCSFileSystem`, the code will fail on the worker side. I would expect the code should work both locally and remotely to allow me to access GCS dataset. 

More discussion regarding this issue can be found in [this slack thread](https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1638551088168600).

### Versions / Dependencies

```shell
ray==1.8.0
gcsfs==2021.11.1
```

### Reproduction script

```python
from gcsfs import GCSFileSystem
ray.init("ray://127.0.0.1:10001", runtime_env = {"pip": ["gcsfs==2021.11.1"]})
fs = GCSFileSystem(project="ml-sketchbook", token="cloud")
df = ray.data.read_csv("gs://ml-sketchbook-keshi/ray/data/simpleHIGGS.csv", filesystem=fs)
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by richardliaw** [comment]
cc @clarkzinzow @scv119 to track

**Comment by clarkzinzow** [comment]
The issue that you're running into is the same as [this one](https://github.com/fsspec/gcsfs/issues/264#issuecomment-705505992), where the project mismatch is being thrown as an error and `token="cloud"` isn't being tried. The default `token=None` should work, since when the mismatch between the specified project ID and the project ID included in the default credentials raises an error, that error should be caught and logged, and gcsfs should continue to the `token="cloud"` attempt, which should succeed. Unfortunately, this code was recently [changed](https://github.com/fsspec/gcsfs/pull/390/files#diff-ab034e54024ab92b8af1b6538da0baa77f986980ccab9a67a8b3441a1d83cde9L216) such that the project ID mismatch error is no longer caught, making it a fatal error.

If you don't want to wait for a fix in gcsfs, you can solve this at the application level by manually getting the correct Google credentials and passing them to the gcsfs filesystem as the token:
```python
from gcsfs import GCSFileSystem
import google.auth
import google.auth.compute_engine

ray.init("ray://127.0.0.1:10001", runtime_env = {"pip": ["gcsfs==2021.11.1"]})

project = "ml-sketchbook"
credentials, cred_project = google.auth.default()
if cred_project != project:
    credentials = google.auth.compute_engine.Credentials()

fs = GCSFileSystem(project=project, token=credentials)
df = ray.data.read_csv("gs://ml-sketchbook-keshi/ray/data/simpleHIGGS.csv", filesystem=fs)
```

This assumes that the project of your user account on your laptop is also `"ml-sketchbook"`, which should be the case since `token=None` was working for you locally.

**Comment by daikeshi** [comment]
Thank you @clarkzinzow for the detailed explanation! This workaround should work for us.

**Comment by clarkzinzow** [comment]
For the record: solving the underlying issue (and therefore obviating the need for the workaround) is blocked by gcsfs making something akin to [this change](https://github.com/fsspec/gcsfs/issues/264#issuecomment-995042989). Keeping this issue open until this is fixed upstream.

**Comment by daikeshi** [comment]
@clarkzinzow sounds good to me. Yes, the workaround worked for us. Thank you!
