### ISSUE TITLE
Autoscaler never scales up initially-zero resource

### ISSUE THREAD

**Issue by AdamGleave** [ray-project/ray#2106]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Amazon Linux 
- **Ray installed from (source or binary)**: Binary
- **Ray version**: 0.4.0
- **Python version**: 3.6.5
- **Exact command to reproduce**:

Create an AWS config with min_workers set to 0, a head node that is not a GPU instance and worker nodes that are GPU instances. Start a Ray task with a non-zero GPU resource requirement.

### Describe the problem
In the above configuration, the task is blocked on a GPU resource requirement the cluster cannot satisfy. Consequently, the Ray autoscaler does not launch any worker nodes, as the resource utilization is zero.

I'm working around this by using a GPU head node, which isn't ideal (GPU instances are much more expensive than compute nodes, and by default the head node runs all the time), but is OK.

However, there seems to be something fundamentally wrong with the autoscaler only taking into account the usage of currently running tasks, and not tasks that are still in the queue.

**Comment by ericl** [comment]
I agree the correct behavior would be to take into account queue length for currently un-utilized resources.

@robertnishihara do you know if queue statistics are also propagated in local scheduler heartbeats? Last I checked only the resource usage was.

**Comment by robertnishihara** [comment]
Looks like we currently do send queue lengths around https://github.com/ray-project/ray/blob/99ae74e1d2cc97297197ae89fadd2b9261288b14/src/common/format/common.fbs#L138.

This is being replaced with https://github.com/ray-project/ray/blob/99ae74e1d2cc97297197ae89fadd2b9261288b14/src/ray/gcs/format/gcs.fbs#L143-L152
but adding something like queue length is fairly straightforward.

Questions:

1. We currently only allow one instance type for worker machines, right?
2. So the autoscaler needs to be able to detect whether there are tasks that are ready to execute but are prevented from doing so by resource requirements? One subtlety is that tasks could be queued because some object dependency isn't available yet (even if there are enough resources).
3. It seems like the heuristic of "check current resource utilization" should work well as long as the worker instance type is the same as the head node instance type, right?
4. Does the autoscaler currently only take into account CPU resources?

**Comment by ericl** [comment]
> We currently only allow one instance type for worker machines, right?

Right.

> So the autoscaler needs to be able to detect whether there are tasks that are ready to execute but are prevented from doing so by resource requirements? One subtlety is that tasks could be queued because some object dependency isn't available yet (even if there are enough resources).

That's a good point. I guess the queue length as currently available would not be useful, since you wouldn't know it is blocked on e.g. GPUs.

> It seems like the heuristic of "check current resource utilization" should work well as long as the worker instance type is the same as the head node instance type, right?

Yes, or alternatively if the min cluster size has at least 1 worker node.

> Does the autoscaler currently only take into account CPU resources?

It takes into account all types of resources. If any resource's slot utilization exceeds a specified fraction, more worker nodes will be launched. This does assume that launching more worker nodes will actually increase the number of resources of that type.

**Comment by npyoung** [comment]
I think this is something very useful to fix for people who want a tiny head node they can leave on, and heavy lifting compute nodes that cost too much to leave on all the time.
> One subtlety is that tasks could be queued because some object dependency isn't available yet (even if there are enough resources).

This seems like the major blocking issue here. Is there a way for the scaler to query what resources queued tasks are waiting on?

**Comment by mattearllongshot** [comment]
Not sure if this is covered by this issue, but it looks like if a list of tasks is scheduled they'll automatically go to running nodes rather than being queued before being sent to a freshly launched node. For example, if I have a head node with `--num-cpus 1`, min-workers 0, max-workers 10, then the following code:

```
@ray.remote
class Actor:
    def run(self):
        time.sleep(1)
        return socket.gethostname(), time.time()

actors = [Actor.remote() for _ in range(10)]
ray.get([a.run.remote() for a in actors])
```

ends up running all the tasks on the head node (serially, because --num-cpus is 1):

```
[('<head-node-hostname>', 1542622268.3170865),
 ('<head-node-hostname>', 1542622269.321265),
 ('<head-node-hostname>', 1542622270.325505),
 ('<head-node-hostname>', 1542622271.329596),
 ('<head-node-hostname>', 1542622272.3335125),
 ('<head-node-hostname>', 1542622273.3375838),
 ('<head-node-hostname>', 1542622274.3414338),
 ('<head-node-hostname>', 1542622275.34548),
 ('<head-node-hostname>', 1542622276.3493326),
 ('<head-node-hostname>', 1542622277.353414)]
```

One new worker ends up being launched, but it doesn't do anything because the head node processes all of the tasks.

**Comment by npyoung** [comment]
Seems like you have a different issue, since in your case the worker does eventually launch and you're not using a GPU task.

Try increasing `time.sleep(1)` to `time.sleep(5 * 60)` in your `Actor.run` method to simulate a long-running task. It can take several minutes for a worker to come online, but all your tasks can be processed by a single CPU thread in 10 seconds.

**Comment by mattearllongshot** [comment]
That's a good point, however I just tried it with 30 tasks and a delay of 60 seconds with the same result (all getting executed on the head node with a gap of 60 seconds between), even though the worker node had fully booted in well under 30 minutes (probably < 5 minutes).

**Comment by ericl** [comment]
Actors don't get moved once placed. I think the issue here is you didn't
request any CPUs with the actor so it defaults to 0 (meaning any number of
actors can get placed on the head). If you do ray.remote(num_cpus=1) this
will force spread scheduling of the actors once the head fills up.

**Comment by robertnishihara** [comment]
Hm @ericl, I think actors should not be placed on a node with 0 CPUs because we distinguish between "resources acquired during the actor's lifetime" and "resources required to place an actor on a machine". And the default is for an actor to acquire 0 CPUs for its lifetime but require 1 for placement on a machine.

E.g., running

```python
import ray

ray.init(num_cpus=0)

@ray.remote
class Actor:
    pass

a = Actor.remote()
```

will print

*I1119 22:51:56.395251 2888553344 scheduling_policy.cc:109] The task with ID 00000000503472016199697790966f70d4c904c7 requires {CPU,0.000000} for execution and {CPU,1.000000} for placement, but no nodes have the necessary resources. Check the client table to view node resources.*

**Comment by richardliaw** [comment]
I think #3530 is a nice workaround for this - closing for now. (Feel free to reopen otherwise)

**Comment by npyoung** [comment]
So is the idea for #3530 that the cluster can scale down to 0 workers only after it's spun up `initial_workers`? So every time you want to use a cluster that has `min_workers=0` you have to "refresh" it to guarantee there are some resources available?

I think I'd prefer to tie this initial workers setup to ray context initialization rather than to `up`ing the cluster. One might want to have a long-running cluster monitor that runs quietly on a small machine without intervention and spends most of its time doing no work. It seems safe to assume that if `ray.init` is called and connects redis, you will want to guarantee a non-zero number of cpu or gpu resources, but if no one is connected, it's safe to drop down to 0 workers.

Maybe we can have `min_workers_idle` (absolute minimum), `min_workers_active` (minimum allowed while something is connected to redis), and `max_workers`.
