### ISSUE TITLE
[Bug] ModuleNotFoundError during deployment after upgrade to 1.9.0

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#21095]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

We seem to have different module import behavior compare to previous version that `serve start` should only be executed at project root.

Likely a module import / pickling issue.

### Versions / Dependencies

ray 1.9

### Reproduction script

User created https://github.com/blshao84/ray-deploy-repro/tree/main to reproduce.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by G-Lauz** [comment]
Hi @jiaodong,

I was wondering if you found any workaround to this issue yet? I'm experimenting the same issue with ray 1.9.0 and a multi-node cluster on kubernetes.

Thanks you.

**Comment by jiaodong** [comment]
hi @G-Lauz i haven't got bandwidth to repro or fix this yet :/ but according to user's comment in https://discuss.ray.io/t/modulenotfounderror-during-deployment-after-upgrade-to-1-9-0/4376/, there's a workaround by doing `But with 1.9.0, I have to run both ‘serve start’ and ‘python deploy.py’ from my project root`, could you try this in the meantime to unblock ? Feel free to comment here if the issue persists, or update with a minimal repro script for your workload.

**Comment by G-Lauz** [comment]
Hi @jiaodong,

Here's a minimal repro script that describe what I'm trying to do: https://github.com/G-Lauz/ray-serve-repro
With the inheritance I'm trying to create a level of abstraction for the user.

I'm using `serve.start()` from the serve api instead of CLI `serve start`, so I'm not sure how I can use the work around. I notice will making my minimal repro script that the error occur right after I add the inheritance structure. Without inheritance everything was working well.

**Comment by jiaodong** [comment]
Issue should be resolved in https://discuss.ray.io/t/modulenotfounderror-during-deployment-after-upgrade-to-1-9-0/4376/11
