### ISSUE TITLE
[DataFrame] Design for Memoizer

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#2131]
In Pandas on Ray, we often have repetitive calls over time to functions like `_blk_to_col` with *identical arguments*. Because arguments are immutable, we assume the execution is stateless and the result is deterministic. Starting the second call, the execution becomes redundant. We can reduce this by implementing a memoizer on top of `ray.remote` decorate. 

Basic implementation:
```python
class memoize:
    def __init__(self, f):
        self.old_remote_func = f.remote
        self.cache = {}

    # Consider this @override
    def remote(self, *args):
        if args in cache: 
                return cache[args]
        else:
                return self.old_remote_func(*args)
```

Usage:
```python
@memoize
@ray.remote
def some_func(...):
    ....
```

Comments? @devin-petersohn @kunalgosar @pschafhalter

**Comment by simon-mo** [comment]
There will also be options to record metrics like cache hit/misses for profiling purpose

**Comment by simon-mo** [comment]
- Redis is doable. 
- Should we really override? This will incur cache lookup overhead each remote call. To avoid this overhead, we will override ray.remote so that one can do `@ray.remote(memoize=True)`. However, compare:
```
@memoize
@ray.remote
def func
```
I still think an explicit memoize decorator works best for our use case because for now, we just need to memoize the functions that we anticipate temporal redundancy. 
- A better implementation (probably requires touching ray core) would requires asynchronous cache lookup and killing or canceling task as needed.

**Comment by devin-petersohn** [comment]
I don't think we should override, not at first. I think for now we should try this idea out on just one or two functions. 

I'm still not sure how we would make sure that:
1.) We have a good policy for keeping objects around. In order to make sure they are not evicted we will have to touch them every once in a while
2.) We have a way to force evict from the cache first (in the case that the object is no longer needed), then evict other objects in low memory cases.

**Comment by devin-petersohn** [comment]
Closing via #2157.
