### ISSUE TITLE
[Tune] [Feature] Run multiple Tune jobs on a single cluster via the new ray submission server

### ISSUE THREAD

**Issue by thoglu** [ray-project/ray#21329]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Is it possible to run multiple ray.tune jobs (e.g. 5 different hyper-parameter searchers for 5 different models) in parallel on the same cluster via the new job submission system?

If the answer is yes, we should add documentation on how to do that.

If the answer is no, I think this would be a very useful feature.

It seems,  in the standard tune use case, this is not possible without hacks (#18851).

REMARK: Via tune.run_experiments one can run multiple tune experiments, but all using the same scheduler and/or search algorithm, as far as I understand. However, if one wants to run one experiment with a particular search algorithm, and another experiment with another search algorithm (i.e. the same search algorithm with slightly different parameters), this is not possible.
Is this correct?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
The trial runner uses a global searcher and scheduler. Thus, we currently have no way of running heterogeneous trials in parallel for different search jobs. The same is true for callbacks, which are also run-global.

If we want to enable this, we would need to keep experiment information in the trial runner, and it would generally require re-thinking the trial running logic.

**Comment by amogkam** [comment]
I think this should be possible by just submitting 5 different Tune jobs to the same cluster, but I'm not sure what the benefit would be, since each Tune job on its own will try to fully maximize the cluster resources anyways.

**Comment by amogkam** [comment]
@thoglu have you tried this out and has there been any issues? With Ray Jobs, I don't think the problems in https://github.com/ray-project/ray/issues/18851 will apply since each job should be running in a separate environment. 

I am going to close this for now, but @thoglu feel free to re-open if there are any further issues with this!

**Comment by tsaoyu** [comment]
Since Ray now support multiple clients, can we leverage this to run multiple `ray.tune` in the same cluster? The use case is to have multiple ML algorithms to be optimised by `tune` with limited resources. Of course, we can start more clusters in the same amount of CPUs but the experience is segmented. Any simpler workaround?

**Comment by yc2984** [comment]
@amogkam @krfricke This is surprising info to find out. Right now we provide a ML training platform by deploying a single ray cluster with auto-scaling for multiple users to submit jobs to it. Now we want to start incorporate ray tune to our platform, what is the recommended way to support our use case?

**Comment by yc2984** [comment]
> I think this should be possible by just submitting 5 different Tune jobs to the same cluster, but I'm not sure what the benefit would be, since each Tune job on its own will try to fully maximize the cluster resources anyways.

Can you elaborate on "since each Tune job on its own will try to fully maximize the cluster resources"? Can't we allocate resources like this?  https://docs.ray.io/en/latest/tune/faq.html#how-do-i-set-resources

**Comment by JuliaWasala** [comment]
I'm also having issues with this - from the documentation it wasn't clear to me at all that this isn't possible. 

I want to run separate tune experiments on separate nodes, but instead now every node executed each experiment.

Is it possible to block communication between multiple runs?

I don't need the global scheduling because we use slurm. I think Ray is great overall and it would be really cool if this could be made easier. Or if there were documentation on an alternative, better way of doing it.  
similar libraries (like NNI) have this global scheduling setup but there seems to be little to nothing out there for us folks who want to run independent, smaller experiments instead of just one large one.

**Comment by jaanli** [comment]
Also running into this!

**Comment by maximilianreimer** [comment]
Why has this been closed? We also would like this use case?
