### ISSUE TITLE
[rllib] install lz4 for tests?

### ISSUE THREAD

**Issue by alok** [ray-project/ray#2137]
I noticed that Jenkins spits out the warning about `lz4` not being installed, and I was wondering if we installing it would speed up rllib tests.

**Comment by robertnishihara** [comment]
One thing I've noticed a few times is that if I install the latest version of `lz4`, then `tensorflow` will fail to import because it has a dependency on `dask` and the version of `dask` that ships with Anaconda uses an older version of `lz4` (there was an API change), and so you may need to install the latest version of `dask`.

**Comment by ericl** [comment]
It's mostly for Apex, also the test cases run are small enough it wouldn't make a difference performance wise. However it could be good to test that path if lz4 is easy to install.
