### ISSUE TITLE
More detailed Java installation instructions.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#2144]
The documentation should include all necessary commands for getting up and running on a new Ubuntu image. This includes dependencies like `sudo apt install maven default-jdk`.

**Comment by robertnishihara** [comment]
cc @kingchin1218 @raulchen do we have any good examples of how to pass more complex Java objects in and out of remote functions?

**Comment by kingchin1218** [comment]
@robertnishihara  @ggdupont 
Could u plz give me an example of passing complex objects in python code?
Then I can know how much complex the objects should be.

**Comment by raulchen** [comment]
@ggdupont 
I'm not sure if I understand what you meant.
Are you talking about serialization of complex Java objects, or propagating user-defined classes' definition to the JVM on remote worker?

**Comment by ggdupont** [comment]
Thanks for the feedback guys.

@raulchen it's actually both : my complex objects are classes already defined in libraries (bunch of jar made in-house).

@kingchin1218 not sure I can do that in Python since it doesn't present the same package dependency situation (and in python any locally defined stuff are correctly uploaded to the worker - as far as I understood).

I just managed to get these loaded in the worked by adding these in the `<ray-root-folder>/java/test/lib` and run my stuff based on tutorial examples but it doesn't seems like the way to go for proper deployment.

So to state it more clearly: I need to enable worker to run some custom java code from jars and exploit a set of resources (static data from files). Where should I package these so that initiating Ray will enable the correct things to be uploaded to the worker nodes?

**Comment by raulchen** [comment]
@ggdupont thanks for clarifying.

Regarding serializing complex objects, it should already work, as long as the object is serializable.

Regarding uploading dependencies to remote workers. There's a CLI tool that allow you to 'submit a job' to the Ray cluster. You'll need to package all jars and resource files in a zip file, and tell the tool the main function of your driver. Then the tool will upload all dependencies and run your driver. You can take a look at [this script](https://github.com/ray-project/ray/blob/master/java/test_cluster.sh) and [this PR](https://github.com/ray-project/ray/pull/2359/files).

PS:
- I'm not able to test the above script at this moment. There's an error, `example/app1.zip` should be changed to `tutorial/app1.zip`. I'll try it later today and come back to you if I find other issues.
- We're sorry that this tool is not very convenient right now, and is lack of proper documentation. We'll try to see how to improve that. cc @zhijunfu 
- The CLI tool may change or be deprecated in the future, because we're considering introducing job management APIs to Ray. But that may take some time.

Last, thanks again for your feedback.

**Comment by kingchin1218** [comment]
@raulchen 
The [script](https://github.com/ray-project/ray/blob/master/java/test_cluster.sh) was not able to be used right now because of the java tutorial's PR.
And the script in this [PR](https://github.com/ant-tech-alliance/ray/pull/68) can be used, but it isn't merged now.  I am going to change it.

@ggdupont Maybe u can refer to this [script](https://github.com/ant-tech-alliance/ray/blob/test_cluster_ci/java/test_cluster.sh) if ur work is blocking now .

**Comment by ggdupont** [comment]
Thks all, I'll try to progress with these pointers.
