### ISSUE TITLE
[Core] [Bug]  Recursive ray.util.multiprocessing.Pool deadlock

### ISSUE THREAD

**Issue by yogeveran** [ray-project/ray#21488]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Using from ray.util.multiprocessing import Pool recursively generates a deadlock.
Generating ray actors recursively does not get stuck.
I assume a solution of the same principle as this could solve the issue:
https://github.com/ray-project/ray/pull/1920

I gave the code generating the error below:

2022-01-09 15:20:50,690	INFO services.py:1265 -- View the Ray dashboard at ****omitted****
2022-01-09 15:21:10,746	WARNING worker.py:1215 -- The actor or task with ID ffffffffffffffffe7315b869e1f68be487f8f1301000000 cannot be scheduled right now. You can ignore this message if this Ray cluster is expected to auto-scale or if you specified a runtime_env for this actor or task, which may take time to install.  Otherwise, this is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increasing the resources available to this Ray cluster.
Required resources for this actor or task: {CPU: 1.000000}
Available resources on this node: {0.000000/1.000000 CPU, 31.779781 GiB/31.779781 GiB memory, 1.000000/1.000000 GPU, 15.889890 GiB/15.889890 GiB object_store_memory, 1.000000/1.000000 node:172.17.0.2, 1.000000/1.000000 accelerator_type:RTX}
In total there are 0 pending tasks and 1 pending actors on this node.

### Versions / Dependencies

ray version 1.9.1

### Reproduction script

```
import ray
from ray.util.multiprocessing import Pool


def poolit_a(idx):
    with Pool(ray_address='auto') as pool:
        return list(pool.map(np.sqrt, np.arange(0, 2, 1)))



def poolit_b():
    with Pool(ray_address='auto') as pool:
        return list(pool.map(poolit_a, range(2, 4, 1)))


if __name__ == '__main__':
    try:
        ray.init(num_cpus=1)
        print(poolit_b())
    finally:
        ray.shutdown()

```

### Anything else

Every run.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yogeveran** [comment]
Note: I tried to write a simple map method and it did not suffer the same issue.
```

@ray.remote(num_cpus=1, max_calls=1)
def remote_wrapper(func, *args, **kwargs):
    return func(*args, **kwargs)


def rmap(func, lst):
    return [remote_wrapper.remote(func(task)) for task in lst]

```

**Comment by czgdp1807** [comment]
I can kind of reproduce this issue. It hangs on my Windows machine (probably due to the deadlock you are suggesting). With the simple map in https://github.com/ray-project/ray/issues/21488#issuecomment-1008316056, the code completes execution, provided remove `with Pool(...) as pool` context.

**Comment by czgdp1807** [comment]
**Cause**

Consider the following three blocks in `python/ray/util/multiprocessing/pool.py`,

https://github.com/ray-project/ray/blob/893536ebd94796548f348e61f63436d5fc86e5a1/python/ray/util/multiprocessing/pool.py#L434-L436

https://github.com/ray-project/ray/blob/893536ebd94796548f348e61f63436d5fc86e5a1/python/ray/util/multiprocessing/pool.py#L556-L560

https://github.com/ray-project/ray/blob/893536ebd94796548f348e61f63436d5fc86e5a1/python/ray/util/multiprocessing/pool.py#L566-L573

Following points can be observed from the above three code blocks,

1. For creating a new `PoolActor` object 1 CPU is always consumed because, `@ray.remote(num_cpus=1)` is present in the declaration of `PoolActor` class and `num_cpus` argument is not passed in `PoolActor.remote(self._initializer, self._initargs)`.
2. In the reproduction script we limit the number of CPUs to 1 (`ray.init(num_cpus=1)`).
3. Since, only 1 CPU is allowed at max, one `PoolActor` object is created for `poolit_b` function. However, there are no CPUs left. Hence, for `poolit_a` when `self._new_actor_entry` is called, the request for a new `PoolActor` is never completed (because it at least 1 CPU per object is needed but we aren't left with any). Hence, `poolit_a` never gets completed, so the code hangs. There is a deadlock.
4. I did two things. First, changing, `@ray.remote(num_cpus=1)` to `@ray.remote(num_cpus=0.1)` for `PoolActor`. The program completes execution and there is no deadlock. Second, instead of the previous change, I pass `num_cpus=0.1` to `PoolActor.remote` call in `self._new_actor_entry` definition. It needed proper delegation of this argument. And things worked again without any deadlock.

**Possible Fixes**

1. Precompute number of CPUs per `PoolActor` object - We can obtain the global number of CPUs left (the `num_cpus` argument passed to `ray.init`) (say NCPU) and also the number of actors (say NA) that might be needed can be figured out (hopefully). Then per new `PoolActor.remote` call we can pass, `num_cpus=NCPU/NA` and things will work without deadlocks. An easy and higher level fix to the problem.
2. Release the resources from previously created actors if creation of a new actor is blocked - This requires detecting which previously created actors are not executing any tasks and then removing the resources from them so that new actor creation requests can be fulfilled. A lower level fix. It would basically require detecting a deadlock situation at runtime and removing that deadlock.

**Comment by yogeveran** [comment]
Hello, 
Thank you for the response.
The solutions 1 and 3 do not seem appropriate.
The second solution is very similar to the one suggested here: [#1920](https://github.com/ray-project/ray/pull/1920)

I also think that Pool actor resource allocation should be defined as an argument to the Pool constructor, and not statically.

**Comment by czgdp1807** [comment]
Great. I will start implementing the second solution tomorrow.

**Comment by czgdp1807** [comment]
I tried detecting the deadlock (gives correct results) and then removed that deadlock by releasing resources from a leased worker. The things worked and the final output was correct. I have added the diff below. However, the confusing part is that why releasing resources from a worker (which is already leased to an actor (again which hasn't completed executing one of its methods)) is successfully giving correct outputs? Also no worker is blocked here (specifically, `worker->IsBlocked` is `false`), it's just a typical deadlock i.e., the first `PoolActor` is waiting for the second `PoolActor` to complete but the second one is unable to do so because all the resources are already consumed by the first `PoolActor`. @stephanie-wang Would like to know your thoughts on this.

```diff
diff --git a/src/ray/raylet/scheduling/cluster_task_manager.cc b/src/ray/raylet/scheduling/cluster_task_manager.cc
index f3ee6f6a8..d3221c65c 100644
--- a/src/ray/raylet/scheduling/cluster_task_manager.cc
+++ b/src/ray/raylet/scheduling/cluster_task_manager.cc
@@ -1439,6 +1439,22 @@ void ClusterTaskManager::ScheduleAndDispatchTasks() {
   // in the PullManager or periodically, to make sure that we spill waiting
   // tasks that are blocked.
   SpillWaitingTasks();
+
+  RayTask deadlocked_task;
+  bool any_pending = false;
+  int num_pending_actor_creation, num_pending_tasks;
+  AnyPendingTasksForResourceAcquisition(&deadlocked_task, &any_pending,
+    &num_pending_actor_creation, &num_pending_tasks);
+  if( any_pending ) {
+    auto& deadlocked_taskid = deadlocked_task.GetTaskSpecification().TaskId();
+    for (auto it = leased_workers_.begin(); it != leased_workers_.end(); it++) {
+      auto& worker = it->second;
+      if( worker->GetAssignedTaskId() != deadlocked_taskid &&
+          worker->GetAssignedTask().GetTaskSpecification().IsActorCreationTask() ) {
+        ReleaseWorkerResources(worker);
+      }
+    }
+  }
 }
 
 void ClusterTaskManager::SpillWaitingTasks() {
```

**Comment by pcmoritz** [comment]
We discussed this issue in a bit more detail and came to the conclusion that we should set the CPU resource requirement for each actor in the actor pool to 0, to make the Ray Pool compatible/same behavior as the Python multiprocessing pool. Would that work for you @yogeveran ? (very similar to solution 4 mentioned above, but with 0.0 instead of 0.1, so it works in all cases).

**Comment by yogeveran** [comment]
**Design wise:**

I think that Pool actor resource allocation should be defined as an argument to the Pool constructor, and not statically.
And you can set the default as 0 for compatibility with Python multiprocessing pool.

But if someone sets it more than 0 then we are back to the same dead lock issue.
The issue can be solved if an actor is waiting to one of its children to finish, 
then it can free any CPU/GPU (Not Memory) resources which aren't used.
The release of resources can only happen if all of the children (separately, not sum) have equal or greater resources requirements.

This way we know the parent can resume running as soon as any of its children finishes.


**Practically:**
Your suggestion to just set the value 0 solves the bug.
Then my suggestion can be converted to a feature request which is less urgent.

**Comment by czgdp1807** [comment]
> Your suggestion to just set the value 0 solves the bug.
> My design suggestion can be converted to a feature request which is less urgent.

+1.

**Comment by czgdp1807** [comment]
> The issue can be solved if an actor is waiting to one of its children to finish,
> then it can free any CPU/GPU (Not Memory) resources which aren't used.
> The release of resources can only happen if all of the children (separately, not sum) have equal or greater resources requirements.

Yes., theoritically that seems correct to me. In fact, I would like to know if there is any internal C++ API in ray which maintains parent-child relationships between tasks. That would lead to a very simple solution and no-risk solution for this problem.
