### ISSUE TITLE
Is that a worker only execute a task now? Why?

### ISSUE THREAD

**Issue by cklsoft** [ray-project/ray#2150]
In local_scheduler_algorithm.cc, a task will be assigned to the worker in available_workers, and a worker will be pop from available_workers when it's dispatched a task. Worker is a process, but only run a task, why not use thread pool? Using thread pool will more efficient?

**Comment by raulchen** [comment]
From my personal understanding, for Python workers, the reason is because: 
1) workers don't share much resources with each other;
2) Python (CPython) can't run real multithreading, because of GIL.

However, as Java worker was recently introduced in Ray, it'd be necessary to change this design. Because in a Java process, JVM itself costs significant amount of overhead.

Thus, I think it'd be better to decouple workers and processes, and support different concurrent mechanisms in different scenarios.

The first try could be using one worker per thread for Java. In the future, we can even use coroutines to make a worker very light-weight.  

Any thoughts?

**Comment by robertnishihara** [comment]
Yes, the primary reason for doing multiprocessing in Python is the global interpreter lock.

However, it should be possible to have multiple Ray "workers" in a single process (this isn't supported very well at the moment, but isn't so hard to support).

**Comment by cklsoft** [comment]
@robertnishihara Actor is stateful, when an actor has slow method, since actor is single thread/process, other method calls of this actor may hang. Is ray can solve this scenario?

**Comment by raulchen** [comment]
@cklsoft No. When an actor is executing a task, it's marked busy in the backend. Subsequent tasks will be queued until the actor becomes available.
