### ISSUE TITLE
[Bug] client tests are very flaky

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#21625]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

tests are very flaky.

### Versions / Dependencies

.

### Reproduction script

.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by AmeerHajAli** [comment]
@ckw017 , looks like ray client tests are very flaky:
test_client 29%
test_basic_2_client_mode 9-11%
test_client_reconnected 7% 
....
Can you please treat this as a hot interrupt? It is very important for developer productivity.

**Comment by ckw017** [comment]
Looks like the main offenders (client, reconnect, client_mode, basic_2_client_mode) are all pretty stable at the moment (The last 5 master CI runs passed all the client tests). The stats are just a bit skewed because of few breaking PRs early last week that took a while to fix, most obvious victim of this is test_client. CI rate should go back up to >85 once the history from those breaks go out of scope.

It looks like test_actor_recursive flakiness is unrelated to those breaks though, so will leave issue open for now

**Comment by AmeerHajAli** [comment]
Please close this issue when you think it is no longer relevant.
