### ISSUE TITLE
[Bug] Shuffle data loader nightly test failing

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#21681]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

https://buildkite.com/ray-project/periodic-ci/builds/2414#7e0505a3-f7d6-4945-bf87-b5d4985615bb

```
AttributeError: 'AioClientCreator' object has no attribute '_register_lazy_block_unknown_fips_pseudo_regions'
```

@clarkzinzow do you know what's going on? Maybe some api changes from dataset? 

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
@rkooo567 Appears to be an issue with `botocore` removing that function:
- https://stackoverflow.com/a/70028682/3204624
- https://github.com/boto/botocore/issues/2568
- https://github.com/fsspec/s3fs/issues/357

**Comment by rkooo567** [comment]
Does anyone work on fixing this? Cc @jjyao ?

**Comment by jjyao** [comment]
@scv119  is on it: https://github.com/ray-project/ray/pull/21680

**Comment by clarkzinzow** [comment]
Ok, so this would be fixed if we updated `aoiboto3` to the most recent version, 9.3.1 ([broken in aiobotocore](https://github.com/aio-libs/aiobotocore/issues/905), [needs to bump botocore to 1.23.0](https://github.com/aio-libs/aiobotocore/issues/904), [happens in aiobotocore 2.1.0](https://github.com/aio-libs/aiobotocore/commit/4d198ec4501c582e69a1427f8d30417f31808677), [aioboto3 upgrades to aiobotocore 2.1.0 in 9.3.1](https://github.com/terrycain/aioboto3/pull/252)), but I don't think that's an option for us since `aiotboto3` stops supporting Python 3.6 after 8.3.0.

**Comment by clarkzinzow** [comment]
Pinning `botocore` to a version before that function is removed might work.
