### ISSUE TITLE
Provide option to print task stdout to driver on a cluster in real time

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#2173]
It would be really useful to have a flag that collects task outputs to drivers and displays them in real time in the background.

cc @joschu

**Comment by nikhilkhanna** [comment]
Seconded!

**Comment by mitar** [comment]
Related: #2573

**Comment by mitar** [comment]
I like this as well. We are planing to do for now this ourselves by wrapping each task into a context manager intercepting stdout and stderr. In fact, the idea is to [redirect stdout and stderr to logging](https://gitlab.com/datadrivendiscovery/d3m/blob/devel/d3m/utils.py#L559), do the same for [warnings](https://docs.python.org/3/library/logging.html#integration-with-the-warnings-module), and then capture all logging and store it to our MongoDB document for the task.

What I would say though is that while displaying all that in real-time in the background could be a good default, ideally there should be an API to subscribe to those logs so that one can decide what to do about them (maybe instead of displaying them, storing them).

**Comment by robertnishihara** [comment]
When we address this we should also fix #3874.
