### ISSUE TITLE
[Bug] `test_cli.py` might not run in the master

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#21791]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

https://github.com/ray-project/ray/blob/45eebdd6e348aadea9c41a86023247b4751bbbef/dashboard/modules/job/tests/test_cli.py#L84

This line of code fails the test in the master because `await` is not called within `test_address`. But in the master CI, this failure seems to be not caught, meaning the test is probably not running in the master.

cc @jiaodong 

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jiaodong** [comment]
The line you pointed out should be removed since the test is not async. 

About if this test is running on master: https://sourcegraph.com/github.com/ray-project/ray/-/blob/dashboard/BUILD?L16:5 this suggests all subfolders {actor, event, job, log, node} files in dashboard with `test*.py` pattern will be executed including this test, since all job tests have the same structure as other folers.

It's a bit weird why this test fails on master but not master CI however, since when i locally try to execute this test with `@pytest.mark.asyncio` it also passes and prints my added print statements:

`❯ pytest test_cli.py -svv
Test session starts (platform: darwin, Python 3.8.12, pytest 6.2.5, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /Users/jiaodong/Workspace/ray/dashboard/modules/job/tests
plugins: asyncio-0.16.0, sugar-0.9.4, rerunfailures-10.2, anyio-3.4.0, timeout-2.0.1, lazy-fixture-0.6.3
collecting ... >>>>>> <Result okay>
>>>>>> <Result ValueError('Address must be specified using either the --address flag or RAY_ADDRESS environment variable.')>

 test_cli.py::TestSubmit.test_address ✓                                                                                                                       25% ██▌
 test_cli.py::TestSubmit.test_working_dir ✓                                                                                                                   50% █████
 test_cli.py::TestSubmit.test_runtime_env ✓                                                                                                                   75% ███████▌
 test_cli.py::TestSubmit.test_job_id ✓`

So here's my suggestion: This decorator should be removed and I will send out a PR for this; Meanwhile can you send me the particular test run that failed on master (is it your laptop or which python version it's running on ?) to see if I can reproduce the error you saw ? I wonder if it only appears on certain environment.

**Comment by rkooo567** [comment]
If it worked on your local, it probably is the API change from the pytest. I will send you my result tomorrow or day after tomorrow (I am outside now)!

**Comment by jiaodong** [comment]
Sure, no rush :) I will put up a PR to remove it anyways as it seems to be included by mistake.

**Comment by rkooo567** [comment]
```
============================================ test session starts =============================================
platform darwin -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /Users/sangbincho/anaconda3/envs/dashboard/bin/python
cachedir: .pytest_cache
rootdir: /Users/sangbincho/work/ray/python
plugins: timeout-1.3.4, asyncio-0.10.0, celery-4.4.2, mock-3.0.0, aiohttp-0.3.0, repeat-0.9.1, lazy-fixture-0.6.3, cov-2.8.1
collected 4 items                                                                                            

python/::TestSubmit::test_address FAILED
python/::TestSubmit::test_working_dir PASSED
python/::TestSubmit::test_runtime_env PASSED
python/::TestSubmit::test_job_id PASSED

================================================== FAILURES ==================================================
__________________________________________ TestSubmit.test_address ___________________________________________

pyfuncitem = <Function test_address>

    @pytest.mark.tryfirst
    def pytest_pyfunc_call(pyfuncitem):
        """
        Run asyncio marked test functions in an event loop instead of a normal
        function call.
        """
        for marker_name, fixture_name in _markers_2_fixtures.items():
            if marker_name in pyfuncitem.keywords \
                    and not getattr(pyfuncitem.obj, 'is_hypothesis_test', False):
                event_loop = pyfuncitem.funcargs[fixture_name]
    
                funcargs = pyfuncitem.funcargs
                testargs = {arg: funcargs[arg]
                            for arg in pyfuncitem._fixtureinfo.argnames}
    
                event_loop.run_until_complete(
                    asyncio.ensure_future(
>                       pyfuncitem.obj(**testargs), loop=event_loop))

../../anaconda3/envs/dashboard/lib/python3.7/site-packages/pytest_asyncio/plugin.py:158: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

coro_or_future = None

    def ensure_future(coro_or_future, *, loop=None):
        """Wrap a coroutine or an awaitable in a future.
    
        If the argument is a Future, it is returned directly.
        """
        if coroutines.iscoroutine(coro_or_future):
            if loop is None:
                loop = events.get_event_loop()
            task = loop.create_task(coro_or_future)
            if task._source_traceback:
                del task._source_traceback[-1]
            return task
        elif futures.isfuture(coro_or_future):
            if loop is not None and loop is not futures._get_loop(coro_or_future):
                raise ValueError('loop argument must agree with Future')
            return coro_or_future
        elif inspect.isawaitable(coro_or_future):
            return ensure_future(_wrap_awaitable(coro_or_future), loop=loop)
        else:
>           raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
                            'required')
E           TypeError: An asyncio.Future, a coroutine or an awaitable is required

../../anaconda3/envs/dashboard/lib/python3.7/asyncio/tasks.py:619: TypeError
```

Deps
```
pytest==5.3.5
pytest-aiohttp==0.3.0
pytest-asyncio==0.10.0
pytest-cov==2.8.1
pytest-lazy-fixture==0.6.3
pytest-mock==3.0.0
pytest-repeat==0.9.1
pytest-timeout==1.3.4
```

**Comment by rkooo567** [comment]
Highly likely related to the version of `pytest-asyncio` I think.. good to know it wasn't broken in the master
