### ISSUE TITLE
[RFC] Change the behavior of Runtime Environments inheritance

### ISSUE THREAD

**Issue by SongGuyang** [ray-project/ray#21818]
Hi all:
    Runtime Environments is already GA in Ray 1.6.0. The latest doc is [here](https://docs.ray.io/en/master/ray-core/handling-dependencies.html#runtime-environments). And now, we already supported a [inheritance](https://docs.ray.io/en/master/ray-core/handling-dependencies.html#inheritance) behavior as follows (copied from the doc):
- The runtime_env["env_vars"] field will be merged with the runtime_env["env_vars"] field of the parent. This allows for environment variables set in the parent’s runtime environment to be automatically propagated to the child, even if new environment variables are set in the child’s runtime environment.
- Every other field in the runtime_env will be overridden by the child, not merged. For example, if runtime_env["py_modules"] is specified, it will replace the runtime_env["py_modules"] field of the parent.

For example, if the parent runtime env is:
```
{
   "py_modules": "s3://ab.zip",
    "pip": ["requests", "pendulum==2.1.2"],
    "env_vars":{
        "a":"b",
    }
}
```

and the child runtime env is:
```
{
   "py_modules": "s3://cd.zip",
    "env_vars":{
        "c":"d",
    }
}
```

The final merged runtime env for child is:
```
{
   "py_modules": "s3://cd.zip",
    "pip": ["requests", "pendulum==2.1.2"],
    "env_vars":{
        "a":"b",
        "c":"d",
    }
}
```
We think this runtime env merging logic is so complex and confusing to users because users can't know the final runtime env before the jobs are run.

Another case is that If you set a special `conda` env in parent actor and set a special `pip` env in child actor, you will get a `ValueError` exception because `conda` and `pip` are conflicting.

So, we want to do a refactor and change the behavior of Runtime Environments inheritance. Here is the new behavior:
- **If there is no runtime env option when we create actor, inherit the parent runtime env.**
- **Otherwise, use the optional runtime env directly and don't do the merging.**

We think the behavior above could cover more than 90% scenes. If you really want to do a specific merging from parent runtime env, you can use a new API named `ray.get_current_runtime_env()` to get the parent runtime env and modify this dict by yourself. Like:
```Actor.options(runtime_env=ray.get_current_runtime_env().update({"X": "Y"}))```

Refer to some discuss in issue https://github.com/ray-project/ray/issues/21494.

**Comment by SongGuyang** [comment]
@cc @edoakes @architkulkarni @rkooo567 @raulchen

**Comment by rkooo567** [comment]
Since it is already GA, I added core-api-change-approval. cc @ericl @edoakes please review it!

**Comment by edoakes** [comment]
I think this behavior is reasonable and simplifies the mental model, while still allowing libraries and advanced users to achieve today's functionality.

My only concern is that this is going to be a breaking change for some users. If we do this, it needs to be well documented and ideally we would raise a useful warning message in the cases where behaviors have changed (I'm not sure if that's possible to detect though).

**Comment by SongGuyang** [comment]
Make sense. I will add a warning message in the implementation.

**Comment by architkulkarni** [comment]
Returning to this RFC to centralize the discussion here.  The new inheritance logic caused a breakage (https://github.com/ray-project/ray/issues/25484) and had to be reverted.  The breakage surfaced an issue with Jobs that we hadn't considered before, so we need to restart the discussion of this RFC.

Copying the options proposed in https://github.com/ray-project/ray/issues/25484:

### Option 1
- Add to the docs that all Ray Jobs users must use the API `runtime_env=ray.get_runtime_context().runtime_env.update({"X": "Y"})` in their Jobs scripts.
- Unrevert the inheritance PR, along with applying the above update within the Tune codebase.
### Option 2
The PR stays reverted, and we stick with the old inheritance behavior.
### Option 3
 Raise an error if the user specifies an override runtime_env that has less keys. For example, suppose:

Job runtime_env is {"working_dir": "/foo"}.
- Case 1: User specifies {"working_dir": "/bar", "env_vars": {"foo": "bar"}} -> OK
- Case 2: User specifies {"working_dir": None, "env_vars": {"foo": "bar"}} -> OK
- Case 3: User specifies {"env_vars": {"foo": "bar"}} -> `ValueError: the runtime_env you specified must specify the working_dir key from the parent runtime_env. Use 'ray.runtime_env.get_runtime_env.update({...})' to merge the runtime_envs.`
### Option 4
Default to the existing merge logic and expose a flag that the user can set when using a runtime_env to discard the parent runtime_env.

## Pros and cons

### Downsides of Option 2 

From the previous discussions at https://github.com/ray-project/ray/issues/22595 and https://github.com/ray-project/ray/issues/21494 
1. Hard to know the current runtime env from reading the code.
2. Too complex/“magical”
3. (Conflicting fields) If you have `conda` set in a parent actor and `pip` set in a child actor, you’ll get an exception because you’re not allowed to set `conda` and `pip` simultaneously in a runtime env.

(1) is the most important and was reported independently by several people.

### Downsides of Option 1
Breaks the execution model of Job Submission.  Jobs are submitted by `ray job submit —working_dir=/dir-containing-script-py —entrypoint=script.py`.    `python script.py` might run fine locally.  But suppose it contains a per-task runtime env, e.g. `{“env_vars”: {“A”: “bar”}}`, and the body of the task also uses some object from a different Python file in the current directory.  Then `python script.py` works locally, but it mysteriously breaks when used with Job Submission because the working_dir is not inherited in the task’s runtime env.
 - **Unintuitive for Ray library developers.**  This situation is not rare; this pattern is used in Ray Train and Ray Tune for example.  It means that every current and future library must use `get_current_runtime_env().update({“env_vars”: {“X”: “Y”)})` for every per-task/actor runtime env that can accept a user-provided argument, even if the library author never uses or thinks about `working_dir`.  Otherwise, their library will break when used with Ray Job Submission, which will be the primary way of running Ray workloads in the future.  It'll also break in any script where the user uses `working_dir` in `ray.init`.  In other words **the breakage https://github.com/ray-project/ray/issues/25484 will likely happen again**; it is not feasible for every internal task/actor to be covered by an integration test with Ray Job Submission / `working_dir`, especially for third-party Ray libraries. In the future there will be a lot more libraries built on Ray, and these have to automatically work with Job Submission.
 - Unintuitive for Jobs users.  Same issue as above, but for per-task/actor runtime envs in the user’s entrypoint script.

After further thought, I think the issue **Unintuitive for Ray library developers** is the most important by far.  Options 3 and 4 suffer from the same issue.  Option 3 has the slight advantage of having a readable error message, but the code will still break and the user will have no way to fix it besides pasting all their `working_dir` contents into a single driver script file.

## Recommendation
Neither option is totally satisfactory, but for the long term, the downsides of Option 1 are worse than those for Option 2, so we should go with Option 2.

**Comment by architkulkarni** [comment]
I'll get consensus from some Ray committers and then we can conclude the discussion of this issue.  I'll follow up with a design for implementing the inheritance logic, since the current location in C++ is hard to maintain and it would be better to do it in the `RuntimeEnvAgent`.

**Comment by ericl** [comment]
+1. I also wonder if we should just define a merging strategy for
pip/conda, and env vars, explicitly. Such as: pip or conda override each
other, and env vars are always merged. That also avoids issues with user
env vars mistakenly overwriting job env vars.

**Comment by rkooo567** [comment]
+1 on Eric's comment. Is this feasible?

working_dir + env var -> it makes more sense to merge always unless it is specified. 
pip / conda -> seems better overriding it since that will make dependency look clear.

**Comment by rkooo567** [comment]
Also, we can probably provide a simple API to debug the final merged version of runtime env 

```
actor = Actor.option(runtime_env={...}).remote()
print(actor.runtime_env)
```

**Comment by edoakes** [comment]
Thanks for the detailed writeup @architkulkarni, I agree with the conclusion.

@ericl @rkooo567 we currently have such logic for env_vars (e.g., if you provide per-task env vars, they're merged into the per-job env vars). We don't have anything for conda/pip but we could add it.

**Comment by architkulkarni** [comment]
Sounds good, so we have consensus on having custom merging logic of some kind.  

So there would only be two changes from 1.x to 2.0:
-  A child's `pip` or `conda` should overwrite the parent's `conda` or `pip`, respectively.  We should print a warning message in this case notifying the user that the parent's `conda` field was deleted because of the child's `pip` field.  (This should be a pretty rare situation.)
- Add an API `print(actor.runtime_env)` to inspect the `runtime_env` from the driver script for debugging, which wasn't possible previously and partially addresses the concern "hard to tell the `runtime_env` from reading the code".
