### ISSUE TITLE
Top hit for Pytorch on Ray isn't helpful for starting out

### ISSUE THREAD

**Issue by worldveil** [ray-project/ray#22064]
Searching for ["ray pytorch"](https://www.google.com/search?q=ray+pytorch&oq=ray+pytorch) leads to [this page](https://docs.ray.io/en/latest/using-ray-with-pytorch.html) 

We should update this page to be more beginner resources / an index, and move advanced best practices (current content) to another page via link.

**Comment by amogkam** [comment]
I think we can just remove this page altogether. It's pretty much all completely moot now with Ray Train. Just the "Downloading Data" Section we can move over to the Ray Train user guide. cc @maxpumperla @richardliaw

**Comment by worldveil** [comment]
Not sure I agree. We need a page that is the definitive place people land when they search "pytorch ray python". What will the contents be?

**Comment by richardliaw** [comment]
@maxpumperla to comment, but how about let's just wait a bit to address this? Things should make more sense with Ray ML  higher-level structure.

**Comment by amogkam** [comment]
@worldveil thats just an SEO question right? When people search up "python ray pytorch" it should lead to the torch section of Ray ML.

**Comment by maxpumperla** [comment]
@ericl mentioned in Slack that we might want to move or remove some of the examples currently under Core. I think these 3 best practices guides (TF, Pytorch, notebooks) should be revisited.

We currently have good content for Pytorch for Tune and Train, and those should be surfaced in search first. Both are good destinations.

I think the page in question is interesting, because you learn how to use Ray Core to parallelise training. But then again, it's rather lengthy and I agree with @amogkam that we have train now and don't really need it. That's even more true since the page is called "best practice", which it certainly isn't. It might be instructive to have it for comparison in train, to show people how much work you save with train / all the stuff train does for you.

**Comment by worldveil** [comment]
I see in "master" this [page is still around](https://docs.ray.io/en/master/ray-core/using-ray-with-pytorch.html). 

Can we have a link at top of page at least to direct people to an easier integration with PyTorch? it's not a good page for first time googlers of Ray + PyTorch...

**Comment by maxpumperla** [comment]
@worldveil @ericl will take care of this, got enough info from Eric now

**Comment by maxpumperla** [comment]
Everything addressed in the PR linked above, we also have redirect rules in place for all deleted examples:

![Screenshot 2022-03-03 at 15 05 07](https://user-images.githubusercontent.com/3462566/156580277-298e54e9-4e8e-4f41-b74d-221079665306.png)

In particular, @worldveil 's search result should now redirect to Train examples, which have proper TF examples.

**Comment by maxpumperla** [comment]
@worldveil the file is now deleted, and at least in our algolia search on our docs the right documents are now surfaced when searching for pytorch. closing for now
