### ISSUE TITLE
[tune] How to maintain a persistent variable in trainable class

### ISSUE THREAD

**Issue by panye** [ray-project/ray#2227]
### Describe the problem

Hi, I'm recently using population based training module in ray. And I encountered a problem about variable initialization. It seems that when exploiting,  PBT will first run "_setup" method. And then it will run "_restore" method and "_train" method. The problem came here. The setup method initializes parameters. But for some parameters, I don't want to them to be initialized during exploiting. For example, I may initialize "max_accuracy = 0" in _setup. This parameter maintains the best accuracy during training. And when a better result comes out, max_accuracy will be updated in _train method. So how could I remain this variable when  _setup is called during exploiting processes? Thank you!

**Comment by richardliaw** [comment]
cc @ericl

**Comment by ericl** [comment]
Can you save that variable during _save() and restore it in _restore()?

**Comment by panye** [comment]
Thanks! @ericl . I solved it by saving them in _train() and restoring them in _restore(). Because I'm not sure when will _save() be called.

**Comment by ericl** [comment]
Hey @payne, save is called when ever the state is checkpointed, to snapshot the model parameters. Including the variable in the data written by save will be similar to pretending it is part of the model parameters.

I don't know how you're saving it in train exactly, that shouldn't work except possibly in a single machine, since it won't be part of the state checkpoint.

**Comment by richardliaw** [comment]
Sounds like this is resolved; closing for now.
