### ISSUE TITLE
Error while installing from source

### ISSUE THREAD

**Issue by kunalrdeshmukh** [ray-project/ray#2257]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04 LTS
- **Ray installed from (source or binary)**: source
- **Ray version**: latest 
- **Python version**: 2.7
- **Exact command to reproduce**: pip install -e . --verbose

### Describe the problem
I faced error while installing ray library from source on ubuntu. I tried to replicate the issue on new VM and I am successful in doing it.

### Source code / logs
PFA the output of above command it includes error as well.
[installation.txt](https://github.com/ray-project/ray/files/2104889/installation.txt)

**Comment by raulchen** [comment]
the error says
`fatal: unable to access 'https://github.com/apache/arrow.git/': Could not resolve host: github.com`
do you have network connection on the machine?

**Comment by kunalrdeshmukh** [comment]
Yes.
in fact i had ran repo clone command on same computer minutes ago.

**Comment by kunalrdeshmukh** [comment]
I tried to run again today. while ensuring good internet connectivity. but I got the error again. 
PFA logs. 
[output.txt](https://github.com/ray-project/ray/files/2106725/output.txt)

**Comment by richardliaw** [comment]
This particular error looks like you need to clean the build from a previous installation; maybe try something like `git clean -f -f -x -d` and then rebuild?

**Comment by kunalrdeshmukh** [comment]
I tried it on brand new ubuntu VM and I tried git clean -f -f -x -d as well as suggested by you.
But I got same error every time.

**Comment by guoyuhong** [comment]
@richardliaw @robertnishihara I think the problem is that [node_manager.cc](https://github.com/ray-project/ray/blob/master/src/ray/raylet/node_manager.cc#L4) has included local_scheduler_generated.h, but in the CMakeList.txt of that lib, this is not added as a dependency of the lib. 

This problem will occur randomly because it is not guaranteed that gen_local_scheduler_fbs will always build ahead of raylib. In most cases, gen_local_scheduler_fbs will be built ahead of build raylib and the building process will success. I think the root cause is that raylet is design to decouple with old ray backend. However, in the node_manger.cc, there is a coupling of both parts to guarantee the enum value is right. 

Is that correct?

**Comment by robertnishihara** [comment]
Please try with the latest master and let me know if the issue persists.

**Comment by kunalrdeshmukh** [comment]
Hi @robertnishihara 
I got error again. It was some cython related error. so I installed cython and ran again. 
PFA error I got after running it again
[installation.txt](https://github.com/ray-project/ray/files/2117340/installation.txt)
.

**Comment by robertnishihara** [comment]
You could always try installing Ray inside of Docker, since that should be reproducible. E.g., https://github.com/ray-project/ray/blob/master/build-docker.sh.

**Comment by kunalrdeshmukh** [comment]
i ran just 2 commands more than the ones suggested on http://ray.readthedocs.io/en/latest/installation.html

sudo apt-get install python-pip python-dev build-essential
and
pip install git

then

sudo apt-get update
sudo apt-get install -y cmake pkg-config build-essential autoconf curl libtool unzip flex bison python # we install python here because python2 is required to build the webui

# If you are not using Anaconda, you need the following.
sudo apt-get install python-dev  # For Python 2.
sudo apt-get install python3-dev  # For Python 3.

# If you are on Ubuntu 14.04, you need the following.
pip install cmake

pip install cython

git clone https://github.com/ray-project/ray.git
cd ray/python
pip install -e . --verbose  

i will try docker tonight. Do I need to follow any special instructions to this this script?

**Comment by guoyuhong** [comment]
@robertnishihara @kunalrdeshmukh This time the error message changed... I think I found the root cause and I can reproduce this failure by change `make -j${PARALLEL}` to `make -j1` in build.sh. I found @kunalrdeshmukh used this setting. My default setting will use make -j8. In multi-thread mode, some dependencies will be compiled by other threads. That is why the local_scheduler failure does not appear in most cases. I will try to fix problem once for all.
