### ISSUE TITLE
[xray] Error "Create Chunk Failed index = 0: object already exists in the plasma store" when running many tasks and running two raylets on one machine.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#2284]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **Ray installed from (source or binary)**: Source
- **Ray version**: 18ee044f033d044c8604af24fb5f0173c3e75bfd
- **Python version**: Python 3.6.4 :: Anaconda, Inc.
- **Exact command to reproduce**:

1. Start Ray with `RAY_USE_XRAY=1 ipython`.
2. Run
```python
import ray

ray.worker._init(start_ray_local=True, num_local_schedulers=2, num_cpus=1)

@ray.remote
def f():
    return 1

results = ray.get([f.remote() for _ in range(1000)])
```

This succeeds but prints a ton of messages like `/Users/rkn/Workspace/ray/src/ray/object_manager/object_manager.cc:638: Create Chunk Failed index = 0: object already exists in the plasma store
`.

cc @elibol

**Comment by elibol** [comment]
With this configuration, we have 1 object store, but 2 raylets registered to the GCS as distinct clients. How does the python client decide where to submit tasks?

Assuming a round-robin scheme WRT which raylet is used: It's possible that task `X` executes on raylet `A`, registers the object's location with GCS, while raylet `B` attempts to pull that object. Of course, when raylet `A` pushes the object to raylet `B`, the call to create the object in the object store fails, since it's already there.

One possible fix might involve introducing a node id, where raylets on the same node have the same node id. This would be distinct from the client id, and would be used instead of the client id to prevent a raylet from pulling an object to the node it's running on.

Another, simpler, possible fix (if the semantics work out) could be to use the same client id for raylets on the same node. However, I'm not a fan of this solution as the name `ClientID` no longer uniquely identifies a raylet's GCS client.

I'm not familiar with the configuration of using multiple raylets on a single node. @atumanov does this configuration make sense for xray?

Although this is unexpected behavior, I think it's low priority since duplicate transfers are non-fatal.

**Comment by robertnishihara** [comment]
Actually I think there are 2 object stores in this case, right?

**Comment by valiantljk** [comment]
Hi, is this issue fixed? I got a similar error using two MPI processes to put objects into the plasma store. 
```
"object already exists in the plasma store" 
```
I don't understand why this happens. The two processes are writing different objects into the store.

**Comment by elibol** [comment]
@valiantljk could you create a separate issue detailing your cluster configuration and providing relevant code snippets? It's difficult to determine whether your issue is related to what is being discussed here without more information.

**Comment by robertnishihara** [comment]
The warning is suppressed now I believe.
