### ISSUE TITLE
[Feature] Ray dataset loading large list of parquet files is extremely slow

### ISSUE THREAD

**Issue by yupbank** [ray-project/ray#22910]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Trying to use ray to run inference on our big dataset. And we are using ray dataset to load the dataset. The read operation is quite slow on 2k files, and increases linearly proportional to number of files, as our goal is to process 100k files. 

Here is a simple code snippet to "reproduce" the "problem".
```
import gcsfs
import ray

fs = gcsfs.GCSFileSystem()
len(file_names)
# 2048
%time ds = ray.data.read_parquet(file_names, filesystem=fs, parallelism=len(file_names))
# 4 minute
```

### Use case

After some poking around, the bottleneck appears to be using [arrow.parquet.ParquetDataset](https://github.com/ray-project/ray/blob/master/python/ray/data/datasource/parquet_datasource.py#L92) as the basis for ray.dataset. It's a single machine, sequential operation. And have no much room to user to scale up. 

```
import pyarrow.parquet as pq
len(file_names)
# 2048
%time ds = pq.ParquetDataset(file_names, filesystem=fs)
# Wall time: 2min 55s
```
appears majority of the time is spend on this operation.  There are some room for improving pyarrow by using multiple cpu, but it doesn't help in our case :(  
```
import pyarrow as pa
pa.set_cpu_count(10)
%time ds = pq.ParquetDataset(file_names, filesystem=fs)
# Wall time: 3min 56s
```

We've used apache beam before for loading dataset for inference. Which doesn't have this type of problem, since it's using [arrow.parquet.ParquetFile](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/parquetio.py#L332), and handles the filenames using beam distributed data abstraction. This is a much more efficient/smart approach, as it would process the files in parallel hence adding machine would definitely help.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
This has been greatly improved in master: https://github.com/ray-project/ray/pull/22665, though I think it's only speeding up metadata resolution and not creation of the initial ParquetDataset. In nightly tests, we resolve parquet files from S3 at ~100 files/s, so not sure why it's going at ~20/s here.

The reason we need to use ParquetDataset in general is for handling of schema and partitioning. Using individual file reads would sacrifice that functionality. @clarkzinzow any thoughts?

**Comment by ericl** [comment]
It could also be a GCSFilesystem specific issue. On S3 with the master build of Ray, I get the following timing (similar results for pyarrow 4.0.1/6.0.1/7.0.0):

```
        start = time.time()
        pq_ds = pq.ParquetDataset(
            paths, **dataset_kwargs, filesystem=filesystem, use_legacy_dataset=False,
        )
        print(time.time() - start)
```

```
(_prepare_read pid=15244) Dataset construction time 0.753044843673706
```

So no significant amount of IO happens when constructing the ParquetDataset. Note that use_legacy_dataset=False is passed in.

**Comment by pdames** [comment]
> The reason we need to use ParquetDataset in general is for handling of schema and partitioning. Using individual file reads would sacrifice that functionality. @clarkzinzow @pdames any thoughts?

I think there is some immediate value in creating a Parquet File datasource to supplement the existing Parquet Dataset datasource, given that Parquet Datasets currently have other problems like being unable to read files with index columns (due to running an implicit merge across files and https://issues.apache.org/jira/browse/ARROW-13851). This is why I also recently [created a Parquet File Datasource](https://github.com/pdames/deltacat/blob/ray112/deltacat/io/pyarrow/parquet_datasource.py) to support a S3-based [Redshift Datasource](https://github.com/pdames/deltacat/blob/ray112/deltacat/io/aws/redshift/redshift_datasource.py) for Ray. 

This datasource also provides a content-type-agnostic [partition predicate push-down filter for hive-style partition keys ](https://github.com/pdames/deltacat/blob/ray112/deltacat/io/aws/redshift/redshift_datasource.py#L215-L230) which would be pretty straightforward to extend beyond just Redshift/S3, and the [metadata provider](https://github.com/ray-project/ray/pull/22896) PR lets users provide their own unified schema for all files (which may be stored in external metadata, or inferred more quickly up-front through parallel reads and/or a smaller subset of files).

Ideally, ParquetDataset will have both this issue and filesystem-specific performance issues fixed soon, but I think its parallelization constraints will continue to be a problem for the foreseeable future. For that reason, I think there's a legitimate long-term need for a Parquet File datasource that allows both maintainers and users to completely skip or customize metadata collection. The Parquet Dataset reader could continue to exist alongside it to use when unified schema inference across all files is required/desired, when row-level filters are required, or to support alternative filesystem partition layouts.

**Comment by ericl** [comment]
+1 to have a separate parquet file datasource. @pdames does it make sense to contribute your implementation? We could add it as a simpler `read_parquet_fast()` API that acts more like the other file datasources.

Another possibility is just making it the default implementation, if the partitioning support is good enough.

**Comment by pdames** [comment]
> +1 to have a separate parquet file datasource. @pdames does it make sense to contribute your implementation? We could add it as a simpler `read_parquet_fast()` API that acts more like the other file datasources.
> 
> Another possibility is just making it the default implementation, if the partitioning support is good enough.

Yep - I'm happy to start by contributing my Parquet File Datasource back and linking it to this PR. 

I'll also open some related issues for consideration like (1) contributing content-type-agnostic `read_files()` APIs/datasources w/ partition predicate push-down support, (2) an AWS S3 datasource built on the code from [1] (w/ some S3 perf improvements like input file discovery via Key Prefix), and (3) an AWS Redshift datasource built on the code from [2] (w/ some Redshift usability/perf improvements like manifest file metadata IO support and Arrow reader argument inference).

I think there are opportunities to continue building better data lake, data catalog, and data warehouse connectors off the foundation of [1] in particular.
