### ISSUE TITLE
[tune][Bug] Ray Tune+RL CPUs underutilized

### ISSUE THREAD

**Issue by fridary** [ray-project/ray#22950]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune, RLlib

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

OS: Debian 9
Processor: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz 6 cores (12 processores)
RAM: 64Gb
Python: 3.8.12

The problem is all 12 CPUs not working 100% full power and it takes much time to execute tuning.

<img width="1184" alt="Снимок экрана 2022-03-09 в 18 07 33" src="https://user-images.githubusercontent.com/3791864/157470311-cc7721e5-7207-4d08-99ad-91df47a79eaa.png">

```
== Status ==
Current time: 2022-03-09 18:08:22 (running for 00:01:58.50)
Memory usage on this node: 5.0/62.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 8.0/12 CPUs, 0/0 GPUs, 0.0/36.96 GiB heap, 0.0/18.48 GiB objects
```

`watch -n.1 "grep \"^[c]pu MHz\" /proc/cpuinfo"` shows maximum GHz 4.3:
```
cpu MHz         : 4299.999
cpu MHz         : 4299.340
...x12
```

### Versions / Dependencies

Ray: 1.11.0

### Reproduction script

```
ray.init(num_cpus=12)  # removing num_cpus gets the same time

analysis = tune.run(
    run_or_experiment="PPO", 
    metric='episode_reward_mean',
    mode='max',
    stop={ "training_iteration": 5},
    config={
        "env": "MyTrainingEnv",
        "env_config": {},
        "framework": "torch",
        "ignore_worker_failures": True,
        #"num_cpus_per_worker": 12,
        "num_workers": 1,  # if increase it will take x10 more time
        "num_envs_per_worker": 1,
        "num_gpus": 0,
        "clip_rewards": True,
        "lr": tune.grid_search([0.001, 0.0005])
        "observation_filter": "MeanStdFilter",
        "model": { "fcnet_hiddens": tune.grid_search([[256, 256], [128, 64, 32]])},
        "sgd_minibatch_size": tune.grid_search([5, 10]),
    },
    num_samples=1,
    keep_checkpoints_num=10,
    checkpoint_freq=1,
)
```

Any ideas what's wrong?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by matthewdeng** [comment]
Hey @fridary, 

Thanks for posting this question. First, I want to clarify one common misconception about `num_cpus` and `num_cpus_per_worker`. Unfortunately, these don't necessarily translate to 12 cores being utilized, and would explain why you're seeing the same behavior no matter what you configure `num_cpus` and `num_cpus_per_worker` as. From [the docs](https://docs.ray.io/en/master/ray-core/walkthrough.html#specifying-required-resources):
> If specifying CPUs, Ray does not enforce isolation (i.e., your task is expected to honor its request).

What these values would affect, however, is how many concurrent tasks can be scheduled. For example, if `num_cpus=12` and `num_cpus_per_worker=12`, you can only schedule 1 worker at a time, but if `num_cpus=12` and `num_cpus_per_worker=1` you can concurrently schedule 12 workers.

Going back to your original question, I can think of 2 routes to consider for increased resource utilization:
1. Increase the amount of concurrent Tune Trials that are being run. Seeing as your config will generate 8 Trials, you may want to keep the resources needed for an individual Trial low so that multiple can run concurrently.
2. Increase the utilization of a single Trial/Trainer. One possibility here is to increase `num_workers`, but it's not clear to me why you're seeing the 10x increase in time when you do this (maybe you can try setting `num_cpus_per_worker=0` so that you're not bottlenecked by resource scheduling).

**Comment by krfricke** [comment]
This seems to be resolved, feel free to re-open if not

**Comment by fridary** [comment]
@matthewdeng Hi!
I still testing parallel computing in ray and got powerful server:
2x Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz 18 cores 36 threads

<img width="1056" alt="Снимок экрана 2022-05-20 в 21 00 25" src="https://user-images.githubusercontent.com/3791864/169586579-3f302dd7-ef3d-448b-b777-36be99627af4.png">


Do you know can we speed up simple `train()`? Whatever params I set in config for code below, script executes ~10 seconds for each iteration every time. Moreover, if I wrap it in `tune()`, I can make more trials by config, but iteration speed always almost the same (I can write tests here).
```
import ray
import ray.rllib.agents.ppo as ppo
from ray.tune.logger import pretty_print

ray.init(num_cpus=72)
config = ppo.DEFAULT_CONFIG.copy()
config.update({
    "framework": 'tf',
    "num_workers": 5,
    "num_cpus_per_worker": 10,
    # "num_cpus_for_driver": 1,
})
trainer = ppo.PPOTrainer(config=config, env="CartPole-v0")

for i in range(100):
   print('n_iter=', i)
   result = trainer.train()
```

**Comment by avnishn** [comment]
RLlib maintainer here -- 


You've increased the `num_cpus_per worker` to 10, but theres no reason to do this, as the sampling for cartpole will only ever use 1 cpu per sampling worker. I'd suggest only touching that parameter if your environment can leverage multiple cpus. 

Instead I'd try increasing `num_workers`, in this case to 50, and turning your `num_cpus_per_worker` back to 1.

This will increase your sampling throughput, but not necessarily your learning speed. 

Another thing is that in RLlib we have a parameter called `min_time_s_per_reporting` which we use to control the frequency that we log results at. By default for ppo its set to 10 seconds, so results will be reported only ever 10s at minimum. That would explain why your experiment takes 10s, instead of being faster.

**Comment by fridary** [comment]
@avnishn thank you! I made time tests, changing only `num_workers`, `"num_cpus_per_worker": 1`, and get such results. It's interesting num_workers=16 is best speed when I have 72 cpus.

```
num_workers: 1. Sample throughput: 366.007. Sample time: 10928.746. Total time 62.21537494659424
num_workers: 2. Sample throughput: 458.468. Sample time: 8724.705. Total time 50.320414781570435
num_workers: 4. Sample throughput: 525.706. Sample time: 7608.819. Total time 44.99417781829834
num_workers: 8. Sample throughput: 567.197. Sample time: 7052.219. Total time 42.259016036987305
num_workers: 16. Sample throughput: 648.898. Sample time: 6164.297. Total time 37.433276414871216
num_workers: 24. Sample throughput: 695.024. Sample time: 11464.346. Total time 70.18130779266357
num_workers: 32. Sample throughput: 642.693. Sample time: 6223.807. Total time 38.90728306770325
num_workers: 45. Sample throughput: 705.989. Sample time: 11218.307. Total time 68.8963782787323
num_workers: 64. Sample throughput: 254.856. Sample time: 31139.126. Total time 170.04277849197388
num_workers: 72. Sample throughput: 228.632. Sample time: 34640.859. Total time 188.71401858329773
```
So this is maximum that I can do to speed up execution? And there is no way to increase learning speed?
