### ISSUE TITLE
[job submission] Support running supervisor actors in worker nodes

### ISSUE THREAD

**Issue by SongGuyang** [ray-project/ray#23399]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

In some real world use cases, we will deploy the dashboard in a separate node which doesn't include a Raylet process. We do this because we want to achieve high available of dashboard. But now in job submission, we use `ray.init` in dashboard to ensure the supervisor actor could be launched. The assumption is that dashboard and Raylet are collocated in one node.

So, can we use Ray Client in dashboard?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SongGuyang** [comment]
@jiaodong @edoakes @architkulkarni What do you think?

**Comment by SongGuyang** [comment]
@edoakes I think we should also avoid using `ray.init` in agent if it is possible. Do we have other alternatives? Two uncertain options:

1. Start a long running system actor when the ray cluster started. Dashboard interacts with the system actor by pubsub channel. When job submitted, dashboard pub a message to start the supervisor actor for the job.
2. Dashboard call the GCS grpc service directly to create the supervisor actor. In this case, dashboard should construct the `TaskSpec`. But we should find a way to monitor the state of supervisor actor because we don't have the actor handle.

Of course, use agent is also an option. Dashboard should select an alive agent and send a rpc to create the supervisor actor .
cc @raulchen

**Comment by edoakes** [comment]
Why is it preferable to use a separate pubsub channel or gRPC service to communicate instead of the public API? That seems like it will increase maintenance burden vs. using actor calls (which is generic to many other things we do in the dashboard).

**Comment by SongGuyang** [comment]
If we create actor in agent directly, agent will become a driver, instead of a pure python process. It will rely on ray cluster. And there will be a lot(equals node number) system level jobs in gcs view.
Of course, I agree using ray api is a simple way.
I'm not sure which is the best way now.

**Comment by SongGuyang** [comment]
Related issue https://github.com/ray-project/ray/issues/23010#issuecomment-1079249521

**Comment by SongGuyang** [comment]
Hey @edoakes, I think we need an agreed solution for this recently. Do you have any other thought for this now? Can you discuss in your team first?

**Comment by SongGuyang** [comment]
cc @raulchen @Catch-Bull

**Comment by edoakes** [comment]
@SongGuyang sorry for leaving you hanging here, we don't have anyone actively working on this at the moment because we are focused on finishing the runtime_env stability & plugins work. I'm also not sure what the best solution is -- the reason I want to use the actor as a supervisor is because we can rely directly on the existing runtime_env setup and scheduling logic rather than reinventing it for this use case. If we instead change this to create the driver directly in the agent, we will need to reinvent a scheduling policy and extend the runtime_env mechanism with another code path.

Right now the best solution seems to me that we make a REST call to an agent, then that agent schedules an actor. This can be made stateless so any call can go to any agent. I expect us to start working on this in June, @architkulkarni will likely be leading it. Let's sync up then when we have a chance to write a more detailed design doc and evaluate tradeoffs.

**Comment by edoakes** [comment]
Of course, if you're interested in contributing here before then we'd appreciate it :)

**Comment by SongGuyang** [comment]
Seems we still have more than a half month before June. I will lead discuss first in Ant next week and go back to sync with you.

**Comment by rkooo567** [comment]
I believe it is done! Please reopen if it is not correct
