### ISSUE TITLE
[Shuffle] Profile driver memory usage

### ISSUE THREAD

**Issue by mwtian** [ray-project/ray#23603]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

With current shuffle implementations, driver memory usage, and in particular ObjectRef memory usage in the driver, can scale quadratically with the number of partitions we use. We would like to profile / instrument driver memory usage to understand the issue better, and confirm the strategies for optimizing driver memory usage.

### Use case

Improve scalability of shuffle, by avoiding the bottleneck on driver memory.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by mwtian** [comment]
I ran shuffle under gperftools / tcmalloc with heap profiling enabled. With https://github.com/ray-project/ray/pull/23337, the command was
```
TEST_OUTPUT_JSON=/tmp/release_test_out.json python sort.py --num-partitions=2000 --partition-size=1e7 --shuffle
```
e.g. using 2000 shuffle partitions, with 10MB per partition / 20GB total data. The script failed with `AttributeError: module 'pickle5' has no attribute 'PickleBuffer'` on Ubuntu, but it does not fail on MacOS. The stats printed from the script after the failures are:

Without tcmalloc (using system default malloc),
```
Finished in 37.05284285545349

==== Driver memory summary ====
max: 15.856388GB
rss: 14.682472448GB

--- Aggregate object store stats across all nodes ---
Plasma memory usage 3 MiB, 2000 objects, 0.01% full, 0.01% needed
Objects consumed by Ray tasks: 2 MiB.
Object fetches queued, waiting for available memory.
```

With tcmalloc but without heap profiling:
```
Finished in 36.91074776649475

==== Driver memory summary ====
max: 17.717724GB
rss: 18.142949376GB

--- Aggregate object store stats across all nodes ---
Plasma memory usage 3 MiB, 2000 objects, 0.01% full, 0.01% needed
Objects consumed by Ray tasks: 3 MiB.
``` 

So even before the script finishes, significant memory are used for the 2000 partition case. Also I observed quadratic scaling before # of object refs and the driver memory usage (1000 -> 2000 object refs, rss memory ~4GB -> ~16GB).

With heap profiling, the program becomes really slow. I ran the program until it is using ~12.5GB RSS. At the time, tcmalloc measures ~10GB memory usage. Here is the profile:
<img width="1759" alt="Screen Shot 2022-04-06 at 6 12 59 PM" src="https://user-images.githubusercontent.com/81660174/162101885-489a6167-1da2-4c3b-9295-4d088a8bcf51.png">
Raw data: [profile001.pb.gz](https://github.com/ray-project/ray/files/8438925/profile001.pb.gz)

We can see that memory related to ObjectRef, i.e. `ReferenceCounter::AddOwnedObject()` and `LocalMemoryBuffer` in `RayObject` contribute the most to memory usages.

Changing memory scaling on driver from quadratic to linear with the # of partitions seem to be the fundamental solution here.

**Comment by stephanie-wang** [comment]
Nice results! That makes sense and matches what we thought.

One thing is that with 10MB partitions, we will have to lower the threshold for storing objects in plasma, since now probably a bunch of objects are getting stored locally at the CoreWorker (that would also explain the high memory usage from LocalMemoryBuffer). The default size threshold is 100KB and 10MB partition / 2000 = 5KB intermediate objects. So we can lower it by setting [RAY_max_direct_call_object_size](https://github.com/ray-project/ray/blob/master/src/ray/common/ray_config_def.h#L147)=1024.

Not sure if it will still be a problem if all objects are stored in plasma, but I bet we could also optimize `LocalMemoryBuffer`. For context, objects whose physical values are actually stored in plasma will have a LocalMemoryBuffer at the CoreWorker that tells the reader to check plasma instead. [Here](https://github.com/ray-project/ray/blob/master/src/ray/core_worker/task_manager.cc#L247)'s an example where the code stores the `OBJECT_IN_PLASMA` dummy value.

**Comment by mwtian** [comment]
After setting `RAY_max_direct_call_object_size=128`, most of the memory usage seems to be in the `ReferenceCounter::object_id_refs_` table.

<img width="1658" alt="image" src="https://user-images.githubusercontent.com/81660174/162328026-6858e3ff-77cf-40c0-845b-2f065a6bd271.png">
Visualized from [profile001.pb.gz](https://github.com/ray-project/ray/files/8447139/profile001.pb.gz)

We will start with trimming the `ReferenceCounter::Reference` struct for the shuffling use case. After that we may look into making the memory usage of ObjectRefs grow linearly with the # of partitions.
