### ISSUE TITLE
[RLlib] Wrong probabilities from `compute_log_likelihoods`

### ISSUE THREAD

**Issue by jwarley** [ray-project/ray#23898]
### What happened + What you expected to happen

**Observed behavior:** For a nearly optimal policy trained on the [SimpleCorridor](https://github.com/ray-project/ray/blob/master/rllib/examples/custom_env.py) example, `compute_log_likelihoods` over the whole state space produces something resembling a uniform distribution over actions for every state.

**Expected behavior:** I expect `compute_log_likelihoods` to output a distribution that describes the actual behavior of the policy, which in this case is that one of the two actions is chosen on nearly every step.

I tried [asking](https://discuss.ray.io/t/confused-by-output-of-compute-log-likelihoods/5564) about this [twice](https://discuss.ray.io/t/how-do-you-get-action-probabilities-from-a-policy/5712) on the discussion forum in case I'm just misunderstanding the intent of the function, but it's been over two weeks with no replies, so I'm going to interpret the silence to mean this is a bug.

### Versions / Dependencies

Ray 1.11.0
Python 3.8
Mac OS 10.15.7

### Reproduction script

https://gist.github.com/jwarley/3f7501ccc4a86e6ee9ffa5ad71ecc995

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
The _log_likelihoods_ that you compute are representations of Q-Values because you are using DQN.
Since the Q Values between different state-action pairs in your environment don't vary a lot, they are very close. Luckily, DQN uses the Epsilon Greedy action sampling function and therefore almost always simply picks the action with the slightly higher Q Value. The likelihoods that you print in your repro script underline this - right is always slightly higher than left.
