### ISSUE TITLE
[RLlib] Upgrade Gym Version

### ISSUE THREAD

**Issue by jkterry1** [ray-project/ray#23976]
### Description

Right now, RLlib pins Gym to a maximum version of 0.21.0 (https://github.com/ray-project/ray/blob/e57ce7efd6ea1d0e4f6942fcf6f526287340e63d/python/setup.py#L248), which was released in October of last year. Since then there's been 3 releases that have included several very large bug fixes, so I was wondering if this could be upgraded. I'd be happy to answer any questions if needed.

**Comment by sven1977** [comment]
Hey @jkterry1 , we have had a quite difficult time getting the newer versions of gym to run with RLlib. Here is the latest PR that will make this happen, though:
https://github.com/ray-project/ray/pull/23541

**Comment by mgerstgrasser** [comment]
@sven1977  @avnishn Also curious if/when this will happen. We just ran into an environment (PettingZoo/SISL Pursuit) that seems to be broken with gym 0.21.0, but working with gym 0.22.0. We don't see any issue when using ray with gym 0.22.0. The PR you linked to seems to concern 0.23 - and also it looks like it's been closed without merging? 
In the mean time, could the ray requirement be updated to `gym<=0.22.0` or `gym<0.23` instead of `gym<0.22`? As it is right now, we can't specify a working set of dependencies in setup.py / pyproject.toml because of the conflicting gym version requirements, and have to ask users to manually upgrade to 0.22. Or are there other issues with ray and gym 0.22 that we haven't noticed?

**Comment by psirenny** [comment]
> We don't see any issue when using ray with gym 0.22.0

Our project is successfully using an older version of ray with gym@0.22.0. But we're prevented from upgrading because of the `gym<0.22` constraint.

**Comment by PhilippWillms** [comment]
Hello, what is the latest status of this topic? Has the dependency to gym<=0.21.0 be relieved and upgraded in ray version 2.1.0? This is what I understand from the link @avnishn provided before.

**Comment by PhilippWillms** [comment]
> Hello, what is the latest status of this topic? Has the dependency to gym<=0.21.0 be relieved and upgraded in ray version 2.11.0? This is what I understand from the link @avnishn provided before.

Yes, as I saw in the upgrading process, the new upper limit is now <0.24.0.

**Comment by ArturNiederfahrenhorst** [comment]
Sven has upgraded the gym version. (In a series of commits, for example in [this](https://github.com/ray-project/ray/pull/30583) one)
