### ISSUE TITLE
Importing RLlib on M1 macOS gives illegal hardware instruction

### ISSUE THREAD

**Issue by ali-naqvi** [ray-project/ray#24027]
### What happened + What you expected to happen

Importing `rllib` on M1 Mac gives the following error

```
(cuj_rl_production) alinaqvi@Syeds-MBP rl-end-to-end-tutorial % python
Python 3.8.12 (default, Oct 12 2021, 06:23:56)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> from ray import tune
>>> from ray import rllib
zsh: illegal hardware instruction  python
```

### Versions / Dependencies

Ray Version: 1.12.0
Python 3.8.12
OS: macOS Monterey 12.3.1 (21E258)
Chip: Apple M1 Max

### Reproduction script

```
(cuj_rl_production) alinaqvi@Syeds-MBP rl-end-to-end-tutorial % python
Python 3.8.12 (default, Oct 12 2021, 06:23:56)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> from ray import tune
>>> from ray import rllib
zsh: illegal hardware instruction  python
```

**Comment by architkulkarni** [comment]
cc @amogkam Perhaps the fix for this should be picked into 1.12.1?

**Comment by edoakes** [comment]
@gjoliver any experience w/ this one?

**Comment by gjoliver** [comment]
I looked at ali's installation. it was an x86 python build. so the x86 macos wheel got installed.
@ali-naqvi here is a document describing how to create a dev build of Ray on M1.

https://docs.google.com/document/d/1XgpuUX0vtk82NIVQyEk8d3tnbpSFHO8ZGmF-i2J8_9A/edit#heading=h.xmeeytf4d7fv

if you don't want to build Ray locally, you can simply follow all the env setup steps, and instead of "pip install -e .", just simply do "pip install ray", and you should be all good.

thanks.
