### ISSUE TITLE
[Ray Tune] `tune.run` hangs on a simple script that uses `ray.remote`

### ISSUE THREAD

**Issue by uduse** [ray-project/ray#24445]
### What happened + What you expected to happen

I expect this simple script to finish quickly but it turned out to hang forever. The reporter is still active (printing out stuff on the screen nonstop) while there's no actual progress made.

Possible duplicates: #6340

### Versions / Dependencies

```
Python 3.8.12
ray==1.12.0
```

### Reproduction script

```
import ray
from ray import tune

hparams_space = {
    "x": tune.uniform(0, 1),
}

@ray.remote
def get_score(config):
    print(config)
    return config["x"] ** 2


def run_trial(config):
    score = ray.get(get_score.remote(config))
    tune.report(score=score)


if __name__ == "__main__":
    ray.init(num_cpus=72)
    analysis = tune.run(
        run_trial,
        num_samples=2,
        metric="score",
        mode="max",
        config=hparams_space,
        resources_per_trial={"cpu": 2},
    )

    print(f"{analysis.best_trial.config=}")
```

Example log:
```
== Status ==
Current time: 2022-05-03 16:08:54 (running for 00:00:36.79)
Memory usage on this node: 60.1/502.5 GiB
Using FIFO scheduling algorithm.
Resources requested: 4.0/72 CPUs, 0/8 GPUs, 0.0/305.98 GiB heap, 0.0/135.13 GiB objects (0.0/1.0 accelerator_type:V100)
Result logdir: /home/zeyi/ray_results/run_trial_2022-05-03_16-08-17
Number of trials: 2/2 (2 RUNNING)
+-----------------------+----------+-----------------------+----------+
| Trial name            | status   | loc                   |        x |
|-----------------------+----------+-----------------------+----------|
| run_trial_c59c4_00000 | RUNNING  | 10.193.241.102:137704 | 0.753093 |
| run_trial_c59c4_00001 | RUNNING  | 10.193.241.102:138189 | 0.232018 |
+-----------------------+----------+-----------------------+----------+
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by xwjiang2010** [comment]
hi @uduse 
This is expected behavior. Please take a look at https://docs.ray.io/en/latest/ray-core/placement-group.html (the section around "In order to fully utilize resources pre-reserved by the placement group, Ray automatically schedules children tasks/actors to the same placement group as its parent.")

You could make your script work by either 
1. `@ray.remote` --> `@ray.remote(num_cpus=0)` or
2. `score = ray.get(get_score.remote(config))` --> `score = ray.get(get_score.options(placement_group=None).remote(config))`

**Comment by uduse** [comment]
Thanks @xwjiang2010 for your quick response! I still don't quite understand what's happening here.

So the reason for `get_score.remote(config)` being blocked here is that the resources required for the `get_score` task is unavailable, right? Quote:

> Infeasible placement groups will be pending until resources are available.

Why the resources for `get_score` is unavailable? The script doesn't specific `placement_group` argument and according to the docs this is set to `"default"`. There's nowhere in the docs of `ray.remote` or`ray.remote_function.RemoteFunction.options` describe the behavior of this `"default"` behavior.

Also, if the child is scheduled to the same placement group as its parent, then why setting `        resources_per_trial={"cpu": 2}` here doesn't solve this problem? In other words, why 2 CPUs aren't enough in this scenario?

Additionally, what if I have no control over the `ray.remote` and `ray.get` part of the code in my script? e.g., in the `run_trial`, we need to call third-party function that internally uses `ray.remote` and `ray.get`. How do I allocate resources for the tasks in this case?

**Comment by xwjiang2010** [comment]
Hi @uduse 
This has something

**Comment by Yard1** [comment]
Yeah, it was very similar to the setup here. Modin on Ray uses Ray Tasks/Actors internally, so unless you create a placement group with enough free resources, the training will get stuck on Modin calls. Since the first bundle in the placement group factory for Tune is allocated fully to the Trainable Actor, the fix was to add another bundle Modin could use (eg. `[{"CPU": 2}, {"CPU":1}]` for a total of 3 CPUs per trial).

**Comment by uduse** [comment]
@Yard1 Thank you for your tip, it works now.

In case anyone wants more specific solution, we set `resources_per_trial=tune.PlacementGroupFactory([{}, {"CPU": 2}]),` in the script above, it won't hang.

**Comment by xwjiang2010** [comment]
Yes, that means the actor gets zero resources itself and thus its child can get the remaining.
