### ISSUE TITLE
redis-server(s) are not secured 

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#2457]
Ray's redis servers are not secured. 

Out of all the [security features](https://redis.io/topics/security/#authentication-feature) outline by redis, it is most sensible to implement a basic [authentication feature](https://redis.io/topics/security/#authentication-feature) and enable it by default. 

I can help implement it. But I was wondering *what is the most efficient way to implement it in ray without touching too much code path?*

I'm currently thinking:
- Add an argument in `ray.init(redis_password=None)`, we can generate a password if possible.
- In `start_redis` (of `services.py`) start the redis process with flag `--requirepass <PASSWORD>`
- Store the password in `ray.experimental.global_state` for ease of access

Please give feedback! Thanks!

**Comment by robertnishihara** [comment]
You probably need to change the following
1. The `start_redis` function in `services.py`.
2. Some or all of the places where we create a Redis client in Python (e.g., we call `redis.StrictRedis`. Unfortunately this is quite a few places, but it's possible only the one in `connect` in `worker.py` needs to be changed and probably the one in `start_ray_processes` in `services.py`.
3. Every place where we create a Redis client in C++, which is called from within here https://github.com/ray-project/ray/blob/05490b8cb9b321ed12e4e3e7df75545957a8766f/src/ray/gcs/client.cc#L39-L47, though you'll need to unpack that a little more.

I don't think we want this on by default since it adds a big burden in the cluster setting, but we can make it possible to do

```
ray start --head --redis-password=1234
```

```python
import ray
ray.init(redis_address='...', redis_password='1234')
```

**Comment by richardliaw** [comment]
Just for reference, this is mainly in response to @jkuroda's comment about unsecured redis instances on local machines right?

I guess not on by default but probably should be on for our jenkins tests.

**Comment by simon-mo** [comment]
@richardliaw yep. also for the millennium cluster where many gpu intensive experiments are using ray. At this moment there are many ray workers running on both blaze and stereopes. I agree not to enable it by default for the ease of use. But we should make it possible to run it securely on the millennium cluster

**Comment by richardliaw** [comment]
Sounds good; can you push a PR? Thanks!

**Comment by danielsuo** [comment]
A quick question: is the intent to access ```redis``` outside a trusted environment? We were thinking of having some sort of authentication as part of our external thin client / API gateway (#2282, #2478). This way, we continue to use ```redis``` as intended while securing from untrusted access points.

**Comment by robertnishihara** [comment]
In the case of this feature, I think the goal is to be able to *prevent* access to Redis from outside a trusted environment. By default we start Redis in "unprotected mode" so that we can communicate with Redis from other machines without a password. However, when the machine is open to the whole world, this can be insecure.

**Comment by danielsuo** [comment]
Ah, I see. I suppose the assumption is that the cluster must be accessed somehow (including open to the whole world). Thanks for the clarification!
