### ISSUE TITLE
[Ray: Tune] - Checkpoint sync fails at end of Ray Tune experiment 

### ISSUE THREAD

**Issue by peterhaddad3121** [ray-project/ray#24675]
### What happened + What you expected to happen

I have Ray tune set up to sync to an S3 bucket. During execution of Ray Tune, I notice that checkpoints get uploaded to S3 just fine during execution of the experiments.

At the end of the experiment the Agents fail with: upload failed: ray_results/PPO/basic-variant-state-2022-05-10_15-43-21.json to s3://my_bucket/test3/PPO/basic-variant-state-2022-05-10_15-43-21.json An error occurred (403) when calling the PutObject operation: Forbidden.

The policy has full permissions, and checkpoints get uploaded during. Unsure what is actually happening because the policy for the bucket has full write permission.

Below is a larger stack trace:

```python
File ~/.local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py:104, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    100 if client_mode_should_convert(auto_init=auto_init):
    101     # Legacy code
    102     # we only convert init function if RAY_CLIENT_MODE=1
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
--> 104         return getattr(ray, func.__name__)(*args, **kwargs)
    105 return func(*args, **kwargs)

File ~/.local/lib/python3.9/site-packages/ray/util/client/api.py:43, in ClientAPI.get(self, vals, timeout)
     36 def get(self, vals, *, timeout=None):
     37     """get is the hook stub passed on to replace `ray.get`
     38 
     39     Args:
     40         vals: [Client]ObjectRef or list of these refs to retrieve.
     41         timeout: Optional timeout in milliseconds
     42     """
---> 43     return self.worker.get(vals, timeout=timeout)

File ~/.local/lib/python3.9/site-packages/ray/util/client/worker.py:433, in Worker.get(self, vals, timeout)
    431     op_timeout = MAX_BLOCKING_OPERATION_TIME_S
    432 try:
--> 433     res = self._get(to_get, op_timeout)
    434     break
    435 except GetTimeoutError:

File ~/.local/lib/python3.9/site-packages/ray/util/client/worker.py:461, in Worker._get(self, ref, timeout)
    459         logger.exception("Failed to deserialize {}".format(chunk.error))
    460         raise
--> 461     raise err
    462 if chunk.total_size > OBJECT_TRANSFER_WARNING_SIZE and log_once(
    463     "client_object_transfer_size_warning"
    464 ):
    465     size_gb = chunk.total_size / 2 ** 30

RayTaskError(TuneError): ray::run() (pid=95664, ip=10.128.6.76)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/tune/tune.py", line 685, in run
    wait_for_sync()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/tune/syncer.py", line 47, in wait_for_sync
    syncer.wait()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/tune/syncer.py", line 273, in wait
    self.sync_client.wait()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/tune/sync_client.py", line 316, in wait
```

### Versions / Dependencies

Python 3.9
Ray 1.12.0

### Reproduction script

```python
tune.run(
    "PPO",
    stop={"episode_reward_mean": 10},
    config={
        "env": "CartPole-v1",
        "num_gpus": 0,
        "num_workers": 1,
        "lr": tune.grid_search([0.01]),
    },
    sync_config=tune.SyncConfig(
        upload_dir="s3://my_bucket/test3/",
        sync_on_checkpoint=True,
        sync_to_driver=True,
        cloud_sync_period=10,
        node_sync_period=10
        
    ),
    checkpoint_at_end=True # I've tried setting this to both True or False
)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by matthewdeng** [comment]
Hmm this does seem odd, are any of the other files getting synchronized? @krfricke any ideas?

**Comment by peterhaddad3121** [comment]
@krfricke @matthewdeng Looks like a ton of the .json files were uploaded and the typical: .json, .csv, .pckl, events.out, result,json. Everything you would expect from checkpoints. It runs for a while then fails.

**Comment by matthewdeng** [comment]
One thing I noticed is that this has a `json` file extension but is actually saved as a pickled file. I wonder if AWS is rejecting it because of that...

https://github.com/ray-project/ray/blob/9b2086c726fba46b0aa2ded28920c0cb6952ec08/python/ray/tune/suggest/basic_variant.py#L393-L398

https://github.com/ray-project/ray/blob/9b2086c726fba46b0aa2ded28920c0cb6952ec08/python/ray/tune/utils/util.py#L391-L395

**Comment by krfricke** [comment]
@peterhaddad3121 this happens during upload of the experiment-level checkpoint. The worker checkpoints seem to work fine, that's why you can see the files on s3.

`basic-variant-state-2022-05-10_15-43-21.json` is a file of the experiment checkpoint, and this gets uploaded by the head node. Do you maybe have different setups on the head and worker nodes?

Are you using Ray client or do you execute your code directly on the head node?

Can you try `aws s3 ls 3://my_bucket/test3` on the head node?

We also changed some of the syncing logic in 1.13.0 and also on latest master. Maybe you can try again with that versions, but this won't help if this is indeed a credential setup issue.

**Comment by krfricke** [comment]
Closing as there's no follow-up and it seems to be related to cluster setup issues. Please reopen if the issue persists.
