### ISSUE TITLE
Discuss Ray streaming support

### ISSUE THREAD

**Issue by eric-jj** [ray-project/ray#2476]
@istoica When we discuss the ray streaming support during riselab retreat, I proposed the shared memory queue idea to you. You suggestted us to try to use an actor as an queue to support streaming. So we write a prototype to verify it. Our prototype shows that with the shared memory queue, the latency is much better than the directly remote call(pass by value). If we add the actor to work as a queue, the perf will be more worse, since the queue get method must return by the reference.
And in our testing, the latency of pass 10w int between two machines, the shared memory queue is in the same level as grpc. So I propose to add the shared memory queue support to plasma. The detail data and proposal is in the doc.
https://docs.google.com/document/d/1rRYtA3MXCdcBSvDX4cdT7g12Kyk1mmN18P60WuxRGEk/edit
cc @robertnishihara @pcmoritz

**Comment by danielsuo** [comment]
FYI: @gwallace @mihaic

**Comment by istoica** [comment]
@eric-jj I left few comments. Thanks

**Comment by eric-jj** [comment]
@istoica after internal discussion, we will have a failover plan for the shared memory queue. We have added the doc, please review it.

**Comment by istoica** [comment]
@eric-jj thanks for updating the document with the fail over design. I left a few comments. I'll try to add a few more later.

**Comment by istoica** [comment]
I added a few more comments. Again, great start! Two things 
- It would be great showing one or two examples illustrating the failover mechanism. I think that would help eliminate many misunderstandings. 
- I suggest we are explicit about *any* assumptions (e.g., idempotency) and limitations (in addition to having a queue for each producer/consumer pair).
Thanks.

**Comment by istoica** [comment]
@eric-jj thanks for adding the examples. I think it looks good though I need to spend more time to make sure I understand all subtleties.

In the meantime I added an alternative at the end of the document (in green) that tries to simplify the system support as much as possible, while presumably pushing more complexity to the application. It's still work in progress, but please take a look.

It would be nice to reach a conclusion in one week or so. Going forward I should be more responsive as I'll be back starting with tomorrow.

Eventually we can have an online call to speed up the convergence.

**Comment by eric-jj** [comment]
@istoica Sorry for late response, we set up several meetings in our side to discuss the whole streaming support base on your proposal. We have a whole design for the streaming now. 
https://docs.google.com/document/d/1EubVMFSFJqNLmbNztnYKj6m0VMzg3a8ZVQZg-mgbLQ0/edit#
The main idea is the streaming layer will be an individual layer on ray just as ray tune. It will start actors on ray and provide the high level API just like join, split to users(We will try to make it compatible with Flink or Spark API for quick on-boarding). The FO also be encapsulated in these actors. The plasma queue will be transparent to user application.

**Comment by istoica** [comment]
@eric-jj thanks for putting this together. Very nice. Some questions so I make sure I fully understand the proposal: 
1) Are you still assuming that the sender and receiver are on different nodes, so that you can handle one node failures without problems? What happens if both queues are lost?
2) I assume a queue item is identified by the *queue ID* and a *sequence number*, and that I should think about a queue item as being similar to an plasma object. Is this the case?
3) What is the lineage granularity being recorded in the case of queues. At one extreme you can record lineage whenever you write/read an item to/from queue. However, I assume this is not the case as the overhead could be too high. At the other extreme you don't maintain lineage on an item basis. However, in this case what would be the interaction with Ray's fault tolerance?
Thanks.

**Comment by eric-jj** [comment]
_Inline_

Are you still assuming that the sender and receiver are on different nodes, so that you can handle one node failures without problems? What happens if both queues are lost?
_[eric.jj] Yes. We assume it. But even when the two actors are allocated on same machine, when the machine download, we will fail back to the full snapshot FO just like Flink. We add the barrier to the queue message to actor for checkpoint, in this way, we can get a full snapshot for whole system._

I assume a queue item is identified by the queue ID and a sequence number, and that I should think about a queue item as being similar to an plasma object. Is this the case?
_[eric.jj] Yes, it is similar to a plasma object. And I am thinking to make the queue id's low part is (0x8F31241235000000), and we can get the the queue item by the queue id + sequence number._

What is the lineage granularity being recorded in the case of queues. At one extreme you can record lineage whenever you write/read an item to/from queue. However, I assume this is not the case as the overhead could be too high. At the other extreme you don't maintain lineage on an item basis. However, in this case what would be the interaction with Ray's fault tolerance?
_[eric.jj] We will not record the lineage in our system. When we fail back to the global snapshot FO, all  actors will recover from last succeed global checkpoint. And re-consume the data from the source after the checkpoint. At that point, we may need some change to ray FO policy. I am not sure about it, maybe we can implement it in the streaming layer, just send a recover from checkpoint command to actors from streaming master.  
In our assumption, as we will allocate the actors in the upstream and downstream to different machines, recovered from the checkpoint is not a common case. So it is acceptable._

**Comment by istoica** [comment]
@eric-jj Thanks for clarifications. A few more questions/comments:

a) How do you expect "Streaming runtime" to learn about actor failure. There is a proposal for "actors without fault tolerance" but in that case you get an exception on `ray.get()` which I'm not sure you can generalize for queues: https://docs.google.com/document/d/1JCLrSNh8K5xqK4QikWd_6P9HrOQlcJ8xleK8hhjh_a0/edit

b) Are you assuming the driver will create a new actor once one fails?

c) One possibility to better integrate queues with Ray is to:
- ask the developer to implement checkpoint and restore methods;
- add to the checkpoint the sequence numbers of the latest items read by the actor (and maybe the latest output items written); if the actor operation is deterministic, then on reconstruction Ray restarts the actor from previous checkpoint and the actor goes ahead to reconstruct both its state and outputs. (The sequence numbers of the output items might be needed for Ray to trigger reconstruction when another actor requests a missing item form an input queue.)

**Comment by eric-jj** [comment]
_Inline_

a) How do you expect "Streaming runtime" to learn about actor failure. There is a proposal for "actors without fault tolerance" but in that case you get an exception on ray.get() which I'm not sure you can generalize for queues: https://docs.google.com/document/d/1JCLrSNh8K5xqK4QikWd_6P9HrOQlcJ8xleK8hhjh_a0/edit
_[eric.jj] The streaming actor is created by us, we only provide the high level API to application code, if the ray.get() throw exception and the streaming layer can't handle, it can throw exception and crash itself._

b) Are you assuming the driver will create a new actor once one fails?
_[eric.jj] Yes, we assume it._ 

c) One possibility to better integrate queues with Ray is to:

ask the developer to implement checkpoint and restore methods;

add to the checkpoint the sequence numbers of the latest items read by the actor (and maybe the latest output items written); if the actor operation is deterministic, then on reconstruction Ray restarts the actor from previous checkpoint and the actor goes ahead to reconstruct both its state and outputs. (The sequence numbers of the output items might be needed for Ray to trigger reconstruction when another actor requests a missing item form an input queue.)
_[eric.jj] Sorry, I didn't find the difference between your suggestion and our proposal. User application must implement their checkpoint and restore methods, streaming layer don't know the user logical. If your concern is the high level API, it can be an option one for easy porting existing code._

**Comment by raulchen** [comment]
@istoica regarding your questions, we've added more details about the fault tolerance mechanism in the 4.2.3.1 section.

**Comment by istoica** [comment]
Thanks, @eric-jj, but let me reformulate my questions. 

Any fault tolerant system has to accomplish three tasks:
1) detect an actor has failed;
2) start a new actor to replace the failed actor;
3) reconstruct the actor's state and outputs;

As far as I understand, in your proposal, the driver will instantiate all actors to create the streaming graph. So question (a) is how does the driver learns about an actor failure, i.e., about (1) above. Do you assume Ray will signal actor failure (and if yes, how?) or do you assume there is an application level keep-alive mechanism, e.g., the driver periodically pings every actor to check whether it is alive? In other words is fault detection implemented by Ray or streaming runtime, and how.

For question (b), assume Ray knows the sequence numbers of inputs and outputs associated to a given checkpoint. For example, assume an actor A connected to input queue Qin and output queue Qout. Assume, the last item processed by checkpoint chk1 of A is Qin.20 and the output is Qout.11. Similarly, assume the last item processed by chk2 of A is Qin.40 and the output is Qout.24. Now, assume that another actor or task queries Qout.15 and this item does not exist maybe because Qout was lost due to failures. Then Ray can reconstruct Qout.15 by restarting A from chk1. In other words, if we expose the item sequences to Ray, Ray can implement both (1) and (2) above. (Of course, the application can still chose to implement everything, but most other applications would be happy to delegate to Ray as much as possible.)

**Comment by eric-jj** [comment]
@istoica 
For question 1 and 2, we will not rely on the ray to detect the failure, because there is no ray.call will be executed during the streaming execution. There is a master actor in the ray streaming will create and  monitor the actors's status. Master will send heartbeat messages to all workers periodically, so when any worker is down, master can detect it and restart the failover process.

For the recover from fail over, your understand is similar as us. The difference is we want to implement a ray streaming layer above ray core. Include the failure detection(heartbeat) and use the checkout to recovered from the failure. The design will change less current ray core code. For the detail fail detection and recover from checkpoint, we have added more details to the design doc.

**Comment by istoica** [comment]
@eric-jj, thanks. So what you need from Ray are the followings:
- a queue object, where queue id + sequence id are Ray visible, i.e., they can be part of the lineage;
- ability to disable actor fault-tolerance; in this case the streaming runtime will manage all aspects of the fault tolerance: failure detection and recovery.

Tomorrow will review the proposal in our group meeting and will send out any other comments we might have.

Otherwise, as the next step I suggest we refine the queue design proposal. Thanks!

**Comment by eric-jj** [comment]
@istoica Sure, we will rewrite the plasma queue proposal, the old one contains too much content.

**Comment by zhijunfu** [comment]
@istoica  @eric-jj  Here's a [refined proposal ](https://docs.google.com/document/d/11MiOns63QTK_Apxy6VLj_zhmO1wCRZ06pB2UZoUFKOY/edit#)for plasma queue. Thanks.

**Comment by istoica** [comment]
@zhijunfu I looked over the proposal. It looks great, but there are some suggestions. Left some comments. In summary:

1. Please articulate the requirements of the queue construct. What problems we try to address, and why objects are not good enough (e.g., performance, absorb bursts)?

2. We should consider some alternative designs before committing. For example, we might want to consider exposing the sequence numbers of the queue items to Plasma Store, and re-using existing object access methods for queue items, i.e., ray.put(), ray.get(), and ray.wait(). Basically we want to make queues usable beyond the streaming applications, for example in producer consumer applications. (I don't think that any of these changes would affect the streaming proposal.)

**Comment by zhijunfu** [comment]
@istoica  Thanks very much for the review.  

I think it's fine to expose sequence numbers, and using existing ray.put() and ray.get() is a good idea.   I added a section at the beginning of the proposal as background on why we need to add plasma queue (microburst, back pressure, performance).  I also put a few questions on some of your comments in the doc. 

There are a few problems that probably need some further discussions, e.g. how eviction and FO should work if we want to support multiple queue readers? how it would look like if we want to support lineage for queue items?  As you mentioned, this shouldn't impact the streaming proposal though.

**Comment by istoica** [comment]
@eric-jj and @zhijunfu here are our thoughts on Ray Queue: https://docs.google.com/document/d/1LP9_KdAOwJ6ZKvMEPGC67GFakosivQn8AQ3wA2ZB-vk/edit?ts=5b956e85# 

While there are still some open questions even among ourselves (as you can see from @robertnishihara and @ericl)  I think we should be able to converge quite fast, especially since I believe we are on the same page with (1) exposing the sequence numbers of the items in the queue to the applications for supporting fault-tolerance, and (2) extending ray.get(), ray.put(), and ray.wait() to queue items.

If you see fit, please feel free to consolidate the two documents.

**Comment by eric-jj** [comment]
@istoica I am ok for the two points you raised. We can exposing the sequence numbers of the queue items and extending the ray.get(), ray.put() and ray.wait() interface to support queue items. Will update the doc later.

**Comment by zhijunfu** [comment]
@istoica Thanks, that makes a lot of sense. I just consolidated your content into the original one. Kindly let me know if I missed anything. 

https://docs.google.com/document/d/11MiOns63QTK_Apxy6VLj_zhmO1wCRZ06pB2UZoUFKOY/edit#

**Comment by istoica** [comment]
@zhijunf, thanks! Will look later today. Before then I'd like to clarify two things:
1) Single reader. I just want to make sure I understand why is this a hard requirement in your proposal. Is this because you want to make sure that a queue item is read and processed by a single actor? If yes, wouldn't it be possible to ensure this at the application level? I'm asking this because having multiple readers is more consistent with current API (e.g., any number of actors/tasks can read an object or access an actor). Also, it's hard to preclude the application to send the queue id to multiple actors. Finally, there are many legitimate use cases of multiple readers, e.g., send status information (notifications) to multiple actors (we leverage Redis for this in Ray's implementation). To make sure, the alternative proposal here is to enable multiple reaaders and ensure at the application level a single reader, if needed.

2) In the proposal, we argue for using the maximum number of items instead of bytes to specify the queue size for several reasons specified in the proposal. This might require to periodically do realloc() if we use a ring buffer, as we do not know for sure the size of the buffer. (We can optimize this though by allocating the ring buffer when the writer writes the first item by assuming all items have the same size.) Anyway, I think this is fine, but wanted to make sure we are on the same page. Also, I'd encourage us to compare the performance of a ring buffer with a chain of blcoks as proposed by @ericl.

**Comment by eric-jj** [comment]
@istoica 
For the multiple readers support, I just want to keep it simple for the queue items' GC.  If you think it is a required feature, we can support it.

For the memory management. We can change the queue implementation to the list<array[]>, it is more reasonable from memory management. We design as ring buffer before because it is similar as current object in the plasma, it is easy for code change.

**Comment by zhijunfu** [comment]
@istoica yes we will support multiple readers, it's just that it would require some additional logic when handling evictions and failover. I think we're on the same page for this:)

**Comment by istoica** [comment]
@zhijunfu sounds great!

BTW, can you say a bit more about garbage collection? The reason I'm asking this is because I don't think we should remove an item once the reader (or all the readers in the multi-reader case) have read it. If there is a failure such item is the most recent one and one that is very likely needed for reconstruction. 

As such we need to keep the most recent items (e.g., the last couple of seconds worth of items) besides the (write_seq_number - min(read_seq_number)) items, i.e., the items which were written but not yet read by *all* readers.

**Comment by zhijunfu** [comment]
@istoica Yes our usage of queue differs to some extent from a normal "queue". I think this can/should be supported. As in the current circular-buffer based design, queue items are already lazily evicted - old queue items only get evicted when the writer tries to add a new item which requires some space that cannot be met without evicting existing queue items.

**Comment by istoica** [comment]
@zhijunfu, thanks. Just to make sure though.

Say we create a queue for 100 items, i.e., `qid = ray.queue(100)`. The user expectation is that the queue will hold up to `100` items, and back pressure will happen when the queue has `100` items, i.e., `last_write_seq - last_read_seq = 100` (this is modulo some delay to send the `last_read_seq` to the writer queue; also, for multiple readers, the second term is replaced by `min(last_read_seq_i))`. However, this might be too small for reconstruction, and we might want to allocate a larger queue. 

In general, I think there are two queue sizes: (1) `size` as specified by the user, which determines when the back pressure is triggered, and (2) `reconstruction_size` which is how many items we decide to keep in the queue, so that on single node failure we still have all queue items we need for reconstruction with high probability. Thus, the actual queue size is `max(size, reconstruction_size)`.

Does it make sense?

**Comment by zhijunfu** [comment]
@istoica Thanks. Yes this makes sense to me. A few questions:
- How is the value of reconstruction_size determined? Is it passed by user when creating the queue, or it's internally set by ray itself?
- Is reconstruction_size a must met criteria? For example, if plasma store is full, and we need to evict existing queue items to make space for a new one, we could not do eviction if it causes queue item size to be less than reconstruction_size? 
- The queue item reconstruction is done by retaining old items, seems like we don't need lineage for queue items.  May you please confirm?

**Comment by istoica** [comment]
1) How is the value of reconstruction_size determined? 
`I was thinking about this, but not sure yet. Maybe have Ray determine it in the first iteration?`
2)  Is reconstruction_size a must met criteria? 
`I'd probably have it as best effort for the reasons you mentioned.`
3) The queue item reconstruction is done by retaining old items.
`I think this is only an optimization. Like you said, we cannot guarantee it, so lineage might still be needed. However, just to make it clear: if the applications is handling fault-tolerance like in the streaming case, the lineage should be disabled.`

**Comment by istoica** [comment]
@zhijunfu after some more consultation among us, we converged to a minimal API, shown at the bottom of the Plasma Queue document, called Proposal Z (https://docs.google.com/document/d/11MiOns63QTK_Apxy6VLj_zhmO1wCRZ06pB2UZoUFKOY/edit#heading=h.3q7hw5xkescy)

We are still trying to find a better name for `seq_num` as this is an abbreviation and we don't use abbreviations anywhere else in the API. On candidate is `index`. But otherwise we are ok with it.

BTW, we should make this API (or an evolution of it) experimental so we can iterate on it by developing a bunch of applications before finalizing it.

**Comment by eric-jj** [comment]
@istoica It is fine for us to name it as stream. And we will use the API to onboard our business first, we expect it can be online in Dec.

**Comment by zhijunfu** [comment]
@istoica Thanks. The proposal Z looks good to me.

**Comment by istoica** [comment]
@eric-jj and @zhijunfu, thanks. This sounds good. So just to understand: is the plan to have a version by December? That would be great!

**Comment by eric-jj** [comment]
Yes. The first version stream is during integration test with streaming layer, we expect it can be deployed to cluster for testing in the early next month and release to production in Dec.

**Comment by istoica** [comment]
@eric-jj sounds great. A few quick qustions:
1. I assume the implementation is following the design available here: https://docs.google.com/document/d/1EubVMFSFJqNLmbNztnYKj6m0VMzg3a8ZVQZg-mgbLQ0/edit#heading=h.2unk4ej07e9r , right?
2) By "streaming layer" I assume you mean "streaming runtime", right?
3) Finally, is this just the Ant internal implementation or it is the one to be released in the open source?
Thanks

**Comment by eric-jj** [comment]
For the first and second question, the answer is yes.
And we definitely want to contribute the stream and streaming layer to open source. It is reason we want to discuss the detail design with you.

**Comment by istoica** [comment]
@eric-jj this sounds really great!

Would it be possible to share the code with us, so we familiarize with it and we can start discussing it? 

Thanks

**Comment by eric-jj** [comment]
We are still during the integration test, which is in our gitlab in the company network. So it is a big work item to create a PR on github. We have a tight deadline to make the streaming work on cluster recently. 
How about we share the code and start the review after we make the streaming work on the test cluster? The API and code will be stable at that time. And we will have bandwidth to do it at that time. It most likely around the Riselab camp. 
I will attend the camp this time, we can discuss it face to face.

**Comment by zhe-thoughts** [comment]
I think this issue can be closed with #4268 . If there's no objection I'll close it after 2 days. cc @raulchen
