### ISSUE TITLE
[RLlib] Sampler <-> Env Spec

### ISSUE THREAD

**Issue by gjoliver** [ray-project/ray#24802]
### Description

This is a cover issue for our latest thoughts about the interfacing spec between RLlib's Sampler and user environments.

The context behind this is that users are using complicated environments in production, which sometimes have dependencies on other remote backend services.
There is then a question of how these environments should report application errors to RLlib during simulation, and what should be the contract users can rely on.

A simple proposal is as follows:

1. To account for potential backend service recovery, sample() calls should have a long timeout (10 mins per episode?), giving user envs opportunity to retry / recover from backend error.
2. The reset() and step() APIs of Gym both support returning an info dict, with which users can return an error=True flag, and optionally an error_msg="..." string.
3. RLlib will discard the active episode and go back to reset() upon seeing the error flag, and write the error message in log if available.
4. Upon un-recoverable errors, envs are allowed to throw Exceptions, in which case RLlib will catch and re-construct the env (or worker?).
5. If RLlib can not make any training progress for a configurable long delay (1 hr for example). the entire job will throw exception, giving Tune a chance to restart everything from checkpoint.

### Use case

Complex production user environments.

**Comment by kouroshHakha** [comment]
For handling this my proposal is to create a `InfoProcessor` Callback class. It should be a stateful implementation so that user can create arbitrary re-routings depending on the history of the behavior. There should be a default behavior like you said (e.g. 10 min timeout per eps, reseting the env upon err=True, .etc). The outcome of this implementation should be several of pre-defined scenarios that will tell RLlib what to do upon such situations? (e.g. `on_env_exception(exception)`)
