### ISSUE TITLE
[Datasets] unable to convert decimal to pandas

### ISSUE THREAD

**Issue by pvanderlinden** [ray-project/ray#25181]
### What happened + What you expected to happen

Having multiple decimals in a ray dataset, will prevent it to convert to pandas.

### Versions / Dependencies

* ray: 1.12.1
* pandas: 1.4.2
* pyarrow: 8.0.0

### Reproduction script

Toy example:
`ray.data.from_items([{"test": Decimal('0.000002346')}, {"test": Decimal('0.00123')}]).to_pandas()`
error: `*** pyarrow.lib.ArrowInvalid: Unable to merge: Field test has incompatible types: decimal128(9, 9) vs decimal128(5, 5)`
It should convert just fine to python decimals

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xiurobert** [comment]
Which `Decimal` class is that?

**Comment by pvanderlinden** [comment]
> Which `Decimal` class is that?

this is the builtin python decimal class: `from decimal import Decimal`

**Comment by pvanderlinden** [comment]
Should I use a different type for fixed point decimals?

**Comment by xiurobert** [comment]
I'm attempting to replicate your issue now.

**Comment by xiurobert** [comment]
Yeah, so this looks like the `pyarrow.concat_tables` function failing to concat the 2 different decimal types.

**Comment by pvanderlinden** [comment]
So far I have tested this with 3 different methods: `to_pandas` failed, `to_modin` succeeded, `write_parquet` works as well. Do you confirm it's a bug?

**Comment by xiurobert** [comment]
Interestingly enough I'm getting a different error now.
```
TypeError: sequence item 0: expected str instance, pyarrow.lib.Table found
```

**Comment by xiurobert** [comment]
`to_pandas_refs()` is working fine.

**Comment by xiurobert** [comment]
I notice when you run the from_items function, it constructs a Dataset with 2 blocks. If you try to construct the dataset with parallelism=1, it will fail too. Not too sure if this is intended behaviour (I'm not familiar with pyarrow's behaviour). Can't confirm if this is a bug either, I'm sadly not one of the ray core contributors, just a random open source contributor.

**Comment by xiurobert** [comment]
`.repartition()` fails as well, but constructing the dataset with `parallelism=1` seems to work just fine.

**Comment by pvanderlinden** [comment]
Does this mean it can randomly break if I ingest a bunch of Decimal rows?

**Comment by xiurobert** [comment]
Likely.

**Comment by pvanderlinden** [comment]
Is there a way around it?

**Comment by xiurobert** [comment]
For now you can convert all the decimals to use the same precision.

**Comment by pvanderlinden** [comment]
How do I do that? The python decimals all have the same precision, the arrow however seem to have a precision set to the exact max decimals they happen to have.

**Comment by xiurobert** [comment]
If you need it now, a very hacky method: `pd.concat((row._row.to_pandas() for row in ds.iter_rows()))`

**Comment by pvanderlinden** [comment]
I think I'm mainly thinking of `repartition` and writing the dataset. Which wouldn't even use pandas.

**Comment by xiurobert** [comment]
> `.repartition()` fails as well, but constructing the dataset with `parallelism=1` seems to work just fine.

**Comment by mwtian** [comment]
cc @jianoaix @clarkzinzow

**Comment by pvanderlinden** [comment]
If I compare it to dask: I can provide type hints, which I then set to a decimal precision and scale which will fit all decimals I have in the dataset.

**Comment by jianoaix** [comment]
@pvanderlinden thank you for raising the question, and @xiurobert for helping out the community!

This is likely a type inference issue in pyarrow.
The issue happens like this:
- When creating dataset with ray.data.from_items([{"test": Decimal('0.000002346')}, {"test": Decimal('0.00123')}]), there are two blocks created, one for each item in the list
- The Decimal('0.000002346') is inferred as decimal(9, 9) and Decimal('0.00123') as decimal(5, 5) in pyarrow, which are two different types
- When "to_pandas()" called, Ray will build these two blocks into one: however, since the two blocks have different schema, it failed to merge

So one way to get the type inference right is something like this: ray.data.from_items([{"test": Decimal('0.000002346')}, {"test": Decimal('0.001230000')}]).to_pandas().
It should make both as type decimal(9, 9) so the two blocks will be able to merge.

I think we should file a bug to pyarrow to fix this. There was something similar like this before: https://issues.apache.org/jira/browse/ARROW-2160

**Comment by xiurobert** [comment]
It looks like this is an issue with `pyarrow.concat_tables()` defined here: https://github.com/apache/arrow/blob/261ad3a06fdf1010a02552468910ee0bb3a26626/cpp/src/arrow/table.cc#L450
