### ISSUE TITLE
[xray] No hanging actors warning

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#2541]
### Describe the problem
```
import ray

@ray.remote(num_cpus=10)
class X(object):
    def __init__(self):
        pass
    def get(self):
        return 2

ray.init(use_raylet=True, num_cpus=10)
actors = [X.remote() for _ in range(20)]
print(ray.get([a.get.remote() for a in actors]))
```
### Source code / logs
If you run the above, it will just silently hang without warnings. In the old backend, we printed nice error messages saying an actor was pending creation due to lack of resources.

**Comment by krfricke** [comment]
This issue affects the current ApexAgent on a multi-node setup:

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04 on Google cloud.
- Ray installed from (source or binary): Source
- Ray version: Master
- Python version: 3.6.4

**Setup**
Master node: Google cloud instance with 12 GPUs, 48 GB RAM, 1 Tesla V100 GPU
Child node: Google cloud instance with 64 GPUs, 256 GB RAM
Running Ape-X with 32 workers.

**Relevant code**
```python
    agent_config_obj = apex.APEX_DEFAULT_CONFIG.copy()
    agent_config_obj['num_workers'] = 32
    agent = apex.ApexAgent(config=agent_config_obj, env=env_spec['gym_env'])

    for i in range(1000):
        results = agent.train()
```

**Behavior**
The agent hangs at the creation of the co-located replay memory shards at this line in [ray/rllib/utils/actors.py](https://github.com/ray-project/ray/blob/master/python/ray/rllib/utils/actors.py#L65):


```python
def split_colocated(actors):
    localhost = os.uname()[1]
    hosts = ray.get([a.get_host.remote() for a in actors])  # Agent hangs here
    local = []
```

I suppose that's because the [remote evaluators of the DQN Agent](https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/dqn/dqn.py#L140) take up all the CPUs on the master node (?). It usually works with fewer workers (e.g. 16, but sometimes fails even then), probably because the chances are better that not all CPUs are occupied by other tasks.

**Comment by ericl** [comment]
@krfricke is this with the default ray backend (not with raylet?)

If so it must be a latent scheduler bug, cc @robertnishihara. Zero cpu actors should never be queued for creation.

**Comment by ericl** [comment]
https://github.com/ray-project/ray/issues/2588
