### ISSUE TITLE
[raylet] Raylet crashes unexpectedly or has lagging heartbeats

### ISSUE THREAD

**Issue by olivierlabreche** [ray-project/ray#25671]
### What happened + What you expected to happen

Users of our Ray platform are experiencing intermittent failures with their Ray prediction jobs. They are requesting a placement group of 400 actors with 2 CPUs per actor, and the placement group seemingly never becomes ready.
The snippet of code is as such:
```
        import ray
        from ray.util import placement_group
        ...
        resource_per_actor = {"CPU": cpus_per_actor}
        resource_bundles = [resource_per_actor for _ in range(actor_count)]
        pg = placement_group(resource_bundles, strategy="SPREAD")
        logger.info("Waiting for placement group to be ready")

        ray.get(pg.ready())
```

We see the logged messages above but not other logs downstream after `ray.get`. Raylet is apprently timing out with this log entry:

```[2022-06-10 07:27:51,402 I 125 125] (raylet) main.cc:301: Raylet received SIGTERM, shutting down..."```

And the application logs show this entry:

```WARNING worker.py:1382 -- The node with node id: xxxxxxxxxxxxxxxxxx and ip: xx.x.xx.xxx has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats."```

It appears that the job sometimes work, and sometimes fails with above errors. We are stuck not being able to help our users further debug their job given the information at hand. Is there any known cause for this problems? Where could we further dig to help us uncover the underlying issue? 

Would reducing the number of actors be a band-aid solution? From our investigation it does not seem to be related to a lack of memory.

### Versions / Dependencies

Ray 1.12.0

### Reproduction script

```
        import ray
        from ray.util import placement_group
        ...
        resource_per_actor = {"CPU": cpus_per_actor}
        resource_bundles = [resource_per_actor for _ in range(actor_count)]
        pg = placement_group(resource_bundles, strategy="SPREAD")
        logger.info("Waiting for placement group to be ready")

        ray.get(pg.ready())
```

**Comment by DmitriGekhtman** [comment]
cc @iycheng

**Comment by rkooo567** [comment]
I think there are 2 issues we should figure it out here.

(1) why is placement group not ready?
(2) why is the node dead by heartbeat issue?

## why is placement group not ready?
I recommend you to try these out.
- Does it always work if you don't use placement group?
- Does it always work if you reduce the number of actors?

After that, I recommend you to try when pg is not ready
- Call ray status and see if there's any pending placement group.
- If there is, create a driver that calls
```python3
ray.init("auto")
print(ray.util.placement_group_table())
```

The table should contain detailed scheduling stats & state. 

## why is the node dead by heartbeat issue?

Raylet reports the health information every 1 second to the centralized metadata server called `gcs_server.cc`. The error happens if it is not reported more 30+ seconds

When this happens there are 3 possible causes.
- Raylet is unexpectedly killed (ray stop --force, OOM, spot instance, machine's shutdown, the node has an issue, segfault)
    - Check logs from raylet.out / raylet.err in a dead node (you can obtain the data from the error). 
    - If there's no log at the end of the file, it is usually a machine related issue. Check
        - if the instance was spot instance, and it was taken.
        - Use dmesg and see if OOM killer kills the raylet process
        - See if there was any other issue on the instance.
- Network delay (network partition, high network bandwidth usage on a head node which slows down the heartbeat processing)
    - Check the head node network usage (if it is too high, this could be an issue).
    - Check if there was network partition (I almost never saw this though)
- High load. (e.g., raylet is too busy to report heartbeat. GCS is too busy to process the heartbeat)
    - Check the dead raylet's logs. If there's `    RAY_LOG(WARNING)
        << "Last heartbeat was sent " << interval
        << " ms ago. There might be resource pressure on this node. If heartbeat keeps "
           "lagging, this node can be marked as dead mistakenly.";
  }`, it means there was a high load. In this case, check the log around the time this warning is printed and show me something called debug dump.
    - Check the GCS log gcs_server.cc | grep [node_id] and share the logs. 

Btw, we are working on improving observability upon failures & write debugging runbook for various failure scenarios (as well as this REP https://github.com/ray-project/enhancements/pull/8). Please share the feedback if you have a common issue!

**Comment by olivierlabreche** [comment]
Thank you @rkooo567 ! We'll try these steps and update you.

**Comment by DmitriGekhtman** [comment]
I think there are many reasons this could potentially happen. If someone can share details about recent occurrences of this issue, we could investigate.

**Comment by DmitriGekhtman** [comment]
Oh I see, there are some reproduction details in the original post. Perhaps it's enough to start looking into it or make some general suggestions.

**Comment by DmitriGekhtman** [comment]
cc @scv119 @ericl to help triage

**Comment by ericl** [comment]
@rkooo567 , can you triage? This seems like it should be solved with the placement group improvements, but it would be good to check their script to verify.

**Comment by rkooo567** [comment]
@olivierlabreche are you still in ray 1.12? From Ray 2.0, you can use `ray get placement-groups` API to know the exact scheduling status of the placement group.

For this particular issue, I think it is related to the node failure, not the placement group API. Have you tried https://github.com/ray-project/ray/issues/25671#issuecomment-1159017418?

**Comment by rkooo567** [comment]
Also, I think scheduling 400 actors is a pretty small-scale workload in Ray, so it should be mostly fine. I am also curious how many nodes you have?

**Comment by olivierlabreche** [comment]
@rkooo567 I opened this issue on behalf of one of our platform users, but I have not heard back about a resolution. Unfortunately I don't have a lot of additional details or context to share. We are trying to migrate to Ray 2.0 though I believe most projects are still on 1.x. I heard back recently from another user running into this issue again, so I am hoping he might be able to jump on this issue and provide us with more details.

**Comment by rkooo567** [comment]
Sounds good! Let me know if the user wants to talk to me directly. I'd love to do pair debugging or share more debugging tips in person. Also, what you can try as a short-term quick fix is to increase the heartbeat timeout. I've seen it. worked for some users before. 

Currently, the heartbeat is sent 1 per second for 30 seconds, and you can control it by setting the env var;

```
# 30 by default
RAY_num_heartbeats_timeout=30

# You start head node with longer timeout
RAY_num_heartbeats_timeout=120 ray start --head
# same for workers
RAY_num_heartbeats_timeout=120 ray start --address=<head_ip>
```

**Comment by rkooo567** [comment]
I will bump the priority once the details are confirmed, and we can create a concrete action item. Right now, I will wait for the follow-up.

**Comment by rkooo567** [comment]
We improved the heartbeat mechanism in the master. If this issue is happening in the master, please ping me! I will add repro-required tag until then
