### ISSUE TITLE
[Datasets] Custom per-block or per-dataset metadata

### ISSUE THREAD

**Issue by cboulay** [ray-project/ray#25740]
### Description

I request the ability to access per-block or per-file metadata during Actor initialization or accompanying each Block/Batch.

Due to the semi-static (changes after 40 MM rows) nature of the metadata, and the very large number of rows, it does not make sense to add the metadata as a new column to each row.

Many thanks to @clarkzinzow for helping me narrow down my issue and suggesting this feature request.

### Use case

My Actors require metadata to calculate their model. For example, an Actor implementing a temporal filter (`scipy.signal.sosfilt`) requires the `sample_rate` to design the filter correctly (`scipy.signal.butter`). The `sample_rate`, does not change within a file, but it might change across files and will not be known until file read. I would like to expose this per-file metadata either at the top-level when I instantiate my actors, or have it travel along with each Block/Batch so my actor can create the coefficients upon first site of a new sample-rate.

I'm using a custom DataSource. I would like to grab the sample_rate from the file during `prepare_read` and insert it into a shared variable, whether that's in BlockMetaData or the schema doesn't matter to me, as long as I can access it when I'm creating my actors or when the actors see their first block.

**Comment by cboulay** [comment]
For any other readers, I came up with a hack that should hold me over.

In prepare_read...

```Python
schema = pa.Table.from_pydict(schema_dict).schema
schema_meta = {k: json.dumps(v) for k, v in series_meta.items()}
schema = pa.schema(zip(schema.names, schema.types), metadata=schema_meta)
```

Then in my main script...
```Python
schema = ds.schema(True)
metadata = {k.decode(): json.loads(v) for k, v in schema.metadata.items()}
actor1 = MyActor.remote(metadata=metadata)
```

This allows me to construct my filters during initialization which satisfies my immediate use-case. As I move to multiple files, I can treat each file as a separate dataset. I don't know how to run these efficiently but I will come to that later.

**Comment by pdames** [comment]
I can start looking into the changes required to close out this issue, since we have the same requirement for efficient preservation of per-input-file metadata for integrating Ray Datasets with DeltaCAT compute implementations like [statistics collection](https://github.com/ray-project/deltacat/tree/main/deltacat/compute/stats). In our case, this statistics collector needs to preserve a unique catalog locator for each file (i.e. conceptually a concat of table_provider+table+table_version+partition+delta_index+delta_file_index) read into a dataset, passed through a series of data inspections, and then have the corresponding stats collected during inspection written back to a durable statistics cache (e.g. in S3) using these file locators as keys.
