### ISSUE TITLE
[Core] [RFC] Add ability to filter application-level exceptions that should be retried.

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#25743]
In Workflows, Datasets, and other libraries/use cases, it is desirable to support retrying transient application-level errors. This is currently supported via the `retry_exception=True` argument:
```python
@ray.remote(retry_exceptions=True, max_retries=3)
def f():
   raise ValueError()   # retried up to 3 times
```

However, not all application-level errors _are_ transient, and this blanket "always retry" policy will result in needless retries on unrecoverable failures. The common solution in other retry libraries is to have either:
1. An allowlist of exceptions that can be retried and/or a denylist of exceptions that should not be retried.
2. A predicate (callable) that is given an exception instance and returns `True` if the exception is retryable.

Some examples are [`urllib3.Retry`'s `allow_methods` and `status_forcelist`](https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry), [gRPC's retry policy with retryable status code lists](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#retryable-status-codes), and [Google Cloud Python `Retry`'s `predicate`](https://googleapis.dev/python/google-api-core/latest/retry.html).

## Proposal

We should offer such an API so users can filter to the application-level exceptions that are transient, preventing needless retries. The predicate callable is the most powerful, and allows the user to multiplex based on error metadata included on the exception, such as status codes. For the sake of making the common path UX ideal, we should also accept an allowlist of exceptions.

**NOTE:** We ultimately decided to go with an exception allowlist to start, and will revisit an exception predicate once users wish to (1) specify a denylist, (2) use error metadata (such as status codes) to determine whether to retry an exception/error, or (3) use such error filtering in other language workers (Java, C++); in any such cases, standardizing on an exception predicate would make the most sense.

### Exception Allowlist

```python
@ray.remote(
    retry_exceptions=ConnectionError,
    max_retries=3,
)
def f(a):
    if a < 0:
        raise ValueError("invalid input")
    else:
        # connect_and_add might transiently raise a ConnectionError
        return connect_and_add(a)

# Fails without retrying the non-transient error.
ray.get(f.remote(-1))

# Retries up to 3 times.
ray.get(f.remote(5))
```

### Exception Predicate

```python
@ray.remote(
    retry_exceptions=lambda e: isinstance(e, ConnectionError),
    max_retries=3,
)
def f(a):
    if a < 0:
        raise ValueError("invalid input")
    else:
        # connect_and_add might transiently raise a ConnectionError
        return connect_and_add(a)

# Fails without retrying the non-transient error.
ray.get(f.remote(-1))

# Retries up to 3 times.
ray.get(f.remote(5))
```

We have a few options for the API itself:
1. Overload `retry_exceptions`, whose type would be `Union[bool, Callable[[Exception], bool]]` with the following semantics: if `False`, don't retry application-level errors; if `True`, retry all application-level errors; if a callable, only retry application-level errors for which the provided callable predicate returns `True`.
2. Have a separate `retry_exceptions_predicate` arg that's `None` by default and only settable if `retry_exceptions=True`.
3. Add a `RetryPolicy` data class that houses all args relating to retrying, similar to the `SchedulingStrategy` data class.

```python
class RetryPolicy:
    num_retries: int
    retry_exceptions: bool
    exception_predicate: Callable[[Exception], bool]
```

For API conciseness and implementation simplicity, I would lean towards (1), but happy to hear other opinions.

## Implementation Note

For both predicate callables and allowlist/denylist lists of exception types, we'll need to serialize and deserialize this task option with Pickle.

**Comment by rkooo567** [comment]
Maybe we can create `RetryPolicy` class? (similar to `SchedulingStrategy`)

**Comment by clarkzinzow** [comment]
@rkooo567 Agreed, something like:
```python
class RetryPolicy:
    num_retries: int
    exception_predicate: Callable[[Exception], bool]
```
which would then be easy to extend in the future:
```python
class RetryPolicy:
    num_retries: int
    exception_predicate: Callable[[Exception], bool]
    initial_backoff: int
    max_backoff: int
    backoff_factor: int
    jitter: bool
```

**Comment by rkooo567** [comment]
Yeah or maybe it could be dictionary (if that's more pythonic lol).

Btw, I have a doubt this is not very easy to implement actually because the original exceptions are not propagated to the caller (but we raise RayTaskError). Can you verify if it is necessary to devlier the original exceptions to users before implementing this?

**Comment by merrysailor** [comment]
Doesn't the ray.remote decorator compose with existing retrying libs & their decorators, e.g., https://tenacity.readthedocs.io/en/latest/index.html ?

**Comment by clarkzinzow** [comment]
@rkooo567 I don't think that we'd need to propagate the original exception to the caller, we only need to tweak the existing logic around determining if we should retry an application-level error. I.e.:
1. Change the `is_application_level_error` to `is_retryable_error` in the [task submission data model](https://github.com/ray-project/ray/blob/d89c8aa9f9bca0c14ba6435d77cd2c566bc0c2dd/src/ray/protobuf/core_worker.proto#L128-L129).
2. Propagate the (pickled) exception predicate to the worker executing the task via the task spec, and check whether the exception satisfies the predicate in the execution handler exception catch, [here](https://github.com/ray-project/ray/blob/5d77d2b1602c0c306a69e39127b8baa77efb4082/python/ray/_raylet.pyx#L694-L701). If so, set `is_retryable_error=True`, sending that back in the response to the task submitter.
3. In the [task submitter](https://github.com/ray-project/ray/blob/91dd360f9d510d34ecf8e62e28a6b43a7566c560/src/ray/core_worker/transport/direct_task_transport.cc#L589-L590), check if `is_retryable_error` is `true` in the response, and if so, retry the task if max number of retries has not been hit yet.

Is there any reason that wouldn't work?

**Comment by clarkzinzow** [comment]
@merrysailor Unfortunately not, since the `@ray.remote` decorator doesn't block until execution completes; instead, it immediately returns a future, while Ray internally tracks the execution of the task. Therefore, we need to push the retry into Ray's internal task submission and task management.

**Comment by rkooo567** [comment]
Hmm yeah I guess that should work (I was thinking we will add the predicate logic on the caller side, but I don't think there's downside of doing it in from a executing side).

**Comment by rkooo567** [comment]
actually @clarkzinzow 

> 
@merrysailor Unfortunately not, since the @ray.remote decorator doesn't block until execution completes; instead, it immediately returns a future, while Ray internally tracks the execution of the task. Therefore, we need to push the retry into Ray's internal task submission and task management.

Isn't this possible if we can properly propagate the exception to the caller side?

**Comment by clarkzinzow** [comment]
@rkooo567 if we wanted to compose with these kind of retry decorators, we'd need to push the retry decorator into the remote function (i.e. make sure that it's always the inner decorator), where it does it's own exception catching and retrying in Python land within a single Ray task run on the executor worker. But I don't think that you could get this to work with a retry decorator wrapping the remote function, even if you could get by the remote API impedance mismatch, since the task submission doesn't block on the result, so the exception wouldn't be raised until the future is fetched.

You could resubmit the task from Python land with your own driver-side wrapping of both submission and result fetching, but that seems a lot more suboptimal than tracking retries internally, as we already do.

Maybe I'm missing something, are you referring to a different driver-side retry mechanism?

**Comment by scv119** [comment]
i'm also confused. I think there are 3 types of errors:
1. application errors, where application could just catch and decide if it should be retried in the application code.
2. errors we know for sure the application code is not executed, in this case we should just retry;
3. errors we don't know if the application code has been executed or not. in this case, we should only retry if the application marks itself idempotent; where i suppose `retry_on_exception` serve the purpose.

does this make sense? which category of errors we try to solve here?

**Comment by merrysailor** [comment]
If I may add to https://github.com/ray-project/ray/issues/25743#issuecomment-1157260687, hopefully without confusing things.
1. There are retrying libs that users can use, if they want (inner decorators etc).
2. Re: idempotent tasks. In a distributed framework, users need to accept that things can fail at different points in time; that fact that their task completed from their perspective doesn't mean much. So, not obvious to me what support a framework can add there, since it cannot be complete.
3. There is a corner case that I can think of where the user might want to explicitly communicate to ray to retry, but on a different worker/node altogether: sometimes in clusters you might hit a 'funky' node and just retrying an a different one can help. This could be communicated e.g., by the user task raising a special exception. But not sure this is worth adding/maintaining.
4. Wrt communicating the original task exception back to the user, isn't this already there in the thrown RayTaskError.cause? Note that retrying libs, can propagate (rethrow) the last or all exceptions thrown.

**Comment by rkooo567** [comment]
I actually like the google api style;https://googleapis.dev/python/google-api-core/latest/retry.html

```
task.options(
    retry_policy=RetryPolicy(
        predicate=if_exception_type(ConnectionError, RayActorError),
        initial_s=10,
        num_retries=3)
).remote()
```

I prefer to at least wrap this into a single argument like `retry_policy`. I think we can require dict instead of the dataclass (like runtime env) if we really care about becoming pythonic. This will help us support more complicated policies easily if we ever need to support them (not sure if we need it).

It also seems like supporting delay & backoff factors is a pretty common argument. Should we also support it? I cannot imagine this won't be required by users anytime soon if we support a retry policy like this. The current policy is we retry in 30 seconds (this seems to be a bad policy especially if users want to control their retry)

If we support delay, we should also think about how this will play with system level failures. Currently we retry up to 3 times (with 30 seconds delay) on system failures.  Should we apply the same delay as app-level retry policy? Or should we just make it as a separate argument as per https://github.com/ray-project/ray/issues/25457? 

For @merrysailor's question;
1. I think it is a bit tough to make it work with them since as Clark said, we raise an exception on ray.get. 
3. I think by default, we will retry on another worker/node. Maybe users can just retry within their application code if they'd like to use the same worker? 
4. I think we don't support this now (there's a backlog, but we haven't finished IIRC).

**Comment by clarkzinzow** [comment]
@scv119 This would focus on addressing (3), where the task is considered idempotent and we only what to retry for errors that we consider to be transient.

@rkooo567 Agreed that a single `retry_policy` argument would be more ideal going forward, although this will no longer be backwards compatible, since we'd be consolidating `max_retries` and `retry_exceptions` into the `retry_policy` argument. I don't think that we should introduce this `RetryPolicy` now since I think that there are unanswered questions around system vs. application-level retries, consolidating actor retry args (`max_restarts` and `max_task_retries`), etc., that I consider out-of-scope for this RFC.

>It also seems like supporting delay & backoff factors is a pretty common argument. Should we also support it?

Yes, definitely. I've heard justified grumblings from multiple users about the hard-coded 30 second delay.

>If we support delay, we should also think about how this will play with system level failures... Should we apply the same delay as app-level retry policy? Or should we just make it as a separate argument as per https://github.com/ray-project/ray/issues/25457?

For normal (non-actor) tasks, what are the typical system-level failures encountered? If those system-level failures are best handled with a specific e.g. number of retries, backoff configuration, etc., then having a separate internal retry policy (maybe configurable via Ray environment variables) for those system-level failures makes more sense to me. The current (non-actor task) semantics apply `max_retries` to both system-level errors and application-level errors, so we wouldn't be changing these semantics if we add the exception predicate. Whether to have different retry policies between system-level errors and application-level errors seems like a good thing to figure out in a larger-scope retry policy effort.

@rkooo567 @ericl @scv119 How about we create another, larger-scope RFC covering the introduction of a `RetryPolicy` API that will include discussion of:
1. Backoff configuration (initial backoff, max backoff, backoff factor, jitter).
2. System-level vs. application-level retry policies.
3. Consolidation of normal task retries and actor (task) retries.

and we keep this RFC focused on the "should retry exception" filtering, which is currently the top user request? If we split the work up like that and go with overloading `retry_exceptions`, we should be able to get an exception predicate in (satisfying the P0) by the 2.0beta branch cut that (a) doesn't introduce a new API arg and is backwards compatible with the current API, (b) will add minimal implementation complexity, and (c) doesn't need to answer any of (1)-(3) above.

**Comment by rkooo567** [comment]
> @rkooo567 @ericl @scv119 How about we create another, larger-scope RFC covering the introduction of a RetryPolicy API that will include discussion of:

> Backoff configuration (initial backoff, max backoff, backoff factor, jitter).
System-level vs. application-level retry policies.
Consolidation of normal task retries and actor (task) retries into this RetryPolicy.

This SGTM!

**Comment by clarkzinzow** [comment]
Ropening since this was reverted.
