### ISSUE TITLE
[RLlib] RLlib needs more examples

### ISSUE THREAD

**Issue by ChristosPeridis** [ray-project/ray#25941]
### Description

Dear Ray Team,

I would like to see more clear examples on how to set up the different algorithms supported by rllib in order to be able to run experiments and test their performances in different environments with the ray.tune API. 

For example, I am trying to run some experiments to test R2D2 algorithm’s performance in a custom environment. However I am getting errors and the experiments do not run. I tried initializing the configuration of the R2D2 based on a script that I found on github but when I am executing the command

from ray.rllib.algorithms.r2d2.r2d2 import R2D2Config

I am getting the following error

ModuleNotFoundError: No module named ‘ray.rllib.algorithms’

I am running Ray version 1.12.1 in my workstation and 1.12.0 in my laptop. The same problem occurs in both.

It is worth to mention that there are no issues when I am running the same script with PPO, A2C and DQN. So what special set up does R2D2 require?

Please provide a clear and analytical guide for conducting such experiments with all the algorithms that rllib supports.

Thank you very much!

Christos Peridis

### Link

https://docs.ray.io/en/latest/rllib/rllib-algorithms.html

**Comment by scv119** [comment]
@gjoliver @matthewdeng to triage.

**Comment by gjoliver** [comment]
as @mvindiola1 said, the specific problem you ran into is because you are looking at a script in HEAD, while using Ray 1.12, which is significantly behind HEAD.
if you are willing to try the nightly wheel, things should work: https://docs.ray.io/en/latest/ray-overview/installation.html#daily-releases-nightlies

let me know if you have request for specific examples. in general, all the scripts under ray/rllib/tuned_examples/ should run just fine.
please file bugs if they don't.
thanks again.
