### ISSUE TITLE
[Ray Core][Job Submission] Refactor Job Submission: rayletless head node 

### ISSUE THREAD

**Issue by Catch-Bull** [ray-project/ray#25963]
## Motivation
Currently, the raylet process is always started within the head node, which means that the actors/tasks will be scheduled in the head node. This feature increases the burden of the head node and reduces the stability of GCS and the dashboard. This document mainly discusses the design of job submission when the head node removes the raylet process.

## Proposed design: Add the JobAgent module in the agent process
Start a job agent module in each agent of the worker nodes, which starts the JobSupervisor Actor, and the dashboard job head communicates with the job agent through gRPC. The job submission steps are as follows:
![image](https://user-images.githubusercontent.com/11995469/174848804-436b774a-35c9-4b51-bec9-0f77e99ad141.png)

### Some Details
- The dashboard communicates directly with the agent process. Considering that the address of the agent process will change after restarting, add the IP address and port of the agent process in `GcsNodeInfo`.
- Driver process will die when it finds the parent process died. To solve this corner case: `Supervisor Actor` died but the driver process is not run `ray.init` yet.  `Supervisor Actor` will restart and kill the driver process, then report job status and eventually shutdown.
- JobAgent will only call `ray.init` after the first received job starts request.
- The parameter `N` can be configured at the cluster level, which means that the dashboard will only select the first `N` nodes in the node list.  The point is that we think `N` should be as small as possible, so fewer JobAgents have executed `ray.init`. I think that in actual use, the probability of `N` will be 1.
- Dashboard According to the above configuration N, find a JobAgent to call the supervisor actor to kill the driver process and job.
- **Log Stream Reflow**: 
    1. **Option 1. Synchronize the log file corresponding to the driver's stdout/err to the head node**: JobAgent will scan the log directory and synchronize all driver logs to the head node through the dashboard(Return logs via Pub/Sub or some other method).
    2. **Option 2. Direct access to JobAgent to get logs**: Get the address of the JobAgent on the same node as the Job driver through the dashboard, and then return the log content through the JobAgent.
    - **PS**: We don't have a similar scenario and don't know much about the user's usage scenario. If the user basically executes `ray job logs` on the head node, and the operation is ordinary, I think **Option 1** may be better, if the user does not execute `ray job logs` on the head node.  **Option 2** should be better.

### Worker Items:
1. Implements a cluster parameter `USE_OLDE_JOB_SUBMISSION`, which defaults to `True`.
4. Add the IP address and port of the agent process in `GcsNodeInfo`.
5. Implement the JobAgent module on the agent process.
6. Implement log stream reflow.
7. Set the default value of `USE_OLDE_JOB_SUBMISSION` to `False`.
8. Finally, remove the old job submission code.

**Comment by architkulkarni** [comment]
Thanks for the details and work items!  A few questions:
1. I didn't fully understand the corner case.  Is this order correct? `SupervisorActor` dies -> driver is killed automatically because it's a child process -> `SupervisorActor` is restarted by Ray -> Our `SupervisorActor `implementation reports the job status as Failed.  Or do we intend to restart the job?  (If that's the case, it might be a problem if there's some non-idempotent code in the `entrypoint` script that gets executed before `ray.init()`.)
2. Also regarding the corner case, why is "before `ray.init()`" an important distinction?  What happens if the actor dies after `ray.init()`?
3. Regarding `N`: What's the use case for selecting the first `N` nodes in the node list?  (Some more minor questions: How is the node list ordered, and can it be reordered?  How does it change when nodes are added or deleted?)
4. Maybe this part is straightforward, but how exactly does the JobAgent send the logs to the head node?
5. In the work items, any reason why "Set the default value of USE_OLDE_JOB_SUBMISSION to False." comes before "Implement log stream reflow."?
6. Currently we store job data in the Internal KV and publish it in the cluster snapshot (eventually this info will be used by the Dashboard, see https://github.com/ray-project/ray/pull/25902).  Is this compatible with the new approach or will we need some changes?

**Comment by Catch-Bull** [comment]
> 

1. In our internal job submission, the driver is dependent on a thread in `CoreWorker` to watch the parent process but seems ray master use a new subprocess to kill the driver when SupervisorActor died.
2. The reason why we think `ray.init` is important is `ray.init` will construct CoreWorker, based on the above item, we rely on CoreWorker to bind driver process fate with `SupervisorActor`.
3. I didn't make it clear here. The point is that we think N should be as small as possible, so fewer JobAgents have executed `ray.init`. I think that in actual use, the probability of N will be 1.
4. I have added above.
5. My fault, I have corrected it.

**Comment by Catch-Bull** [comment]
> Thanks for the details and work items! A few questions:
> 
> 1. I didn't fully understand the corner case.  Is this order correct? `SupervisorActor` dies -> driver is killed automatically because it's a child process -> `SupervisorActor` is restarted by Ray -> Our `SupervisorActor `implementation reports the job status as Failed.  Or do we intend to restart the job?  (If that's the case, it might be a problem if there's some non-idempotent code in the `entrypoint` script that gets executed before `ray.init()`.)
> 2. Also regarding the corner case, why is "before `ray.init()`" an important distinction?  What happens if the actor dies after `ray.init()`?
> 3. Regarding `N`: What's the use case for selecting the first `N` nodes in the node list?  (Some more minor questions: How is the node list ordered, and can it be reordered?  How does it change when nodes are added or deleted?)
> 4. Maybe this part is straightforward, but how exactly does the JobAgent send the logs to the head node?
> 5. In the work items, any reason why "Set the default value of USE_OLDE_JOB_SUBMISSION to False." comes before "Implement log stream reflow."?
> 6. Currently we store job data in the Internal KV and publish it in the cluster snapshot (eventually this info will be used by the Dashboard, see [Fix the jobs tab in the beta dashboard and fill it with data from both "submission" jobs and "driver" jobs #25902](https://github.com/ray-project/ray/pull/25902)).  Is this compatible with the new approach or will we need some changes?

6. I don't think this modification to the Job submission is going to change the storage of Job information, so there should be no conflict here.

**Comment by architkulkarni** [comment]
Thanks for the response and for adding the details about the logging!  I don't have any concerns, if there are finer details we can discuss in the PRs.

**Comment by iycheng** [comment]
I feel the overall direction looks ok. I'm curious about why step 5) is a RPC call? Shouldn't it be a REST call? I'm imagining in k8s env, we'll expose agent as a service and send to agent directly.

**Comment by iycheng** [comment]
@SongGuyang I think the dashboard doesn't necessary need to be the component to control this. My use case is that it seems more flexible and easier to use. Also very friendly to k8s env.
Right now, dashboard serves as a router and service discovers module. But in k8s env, it's actually not very necessary. These can be done by k8s operator and services.
Maybe we should give dashboard and agent a better and clear positions for the long term.

Besides these, I actually have some other open questions:

- Previously, when we submit all jobs to dashboard, it’s hard to run job in each node, so we use actor to do this work. But now, it’s submitted to dashboard agent, then, why not just run the python script there and make the dashboard agent track the progress instead of using an actor?
- Log Stream flow: why not just use ray logs ?
- The dashboard & dashboard agent, in the longer term, what’s the positioning and does the current design fit into the long term vision?

**Comment by rkooo567** [comment]
is it completed?
