### ISSUE TITLE
[autoscaler] Autoscaler overestimates number of healthy nodes

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#26138]
### What happened + What you expected to happen

This issue causes the many_nodes_actor_test to timeout.

https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_1pCeQ7r9ZfPvMNSpgHAQ1KwA?command-history-section=command_history. https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_JQth83CcsiuKKJ9MndgJbTBV?command-history-section=command_history
is the example it timed out.

### Versions / Dependencies

latest ray.

### Reproduction script

run nightly test many_nodes_actor_test

**Comment by zhe-thoughts** [comment]
Should this be a release blocker for 2.0.0beta? @iycheng cc @sihanwang41

**Comment by iycheng** [comment]
This test is flakey recently, I think it should be a release blocker cc @scv119 
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/74173148/176256136-3c093291-265b-4f84-97ca-f338388f2b32.png">

**Comment by zhe-thoughts** [comment]
OK marking as `release-blocker` for precaution. We can remove once verified not a blocker

**Comment by iycheng** [comment]
The hanging happens because of raylet is dead and there is no resources for the cluster to start new actors. Still investigation why the raylet is dead.

**Comment by iycheng** [comment]
Also, once the worker is back the resource seems be wrong:
```
======== Autoscaler status: 2022-06-28 16:45:24.060778 ========
Node status
---------------------------------------------------------------
Healthy:
 250 worker_node
 1 head_node
Pending:
 (no pending nodes)
Recent failures:
 172.31.89.220: worker_node
 172.31.82.114: worker_node
 172.31.69.222: worker_node
 172.31.79.10: worker_node
 172.31.67.186: worker_node
 172.31.90.62: worker_node
 172.31.79.4: worker_node
 172.31.67.164: worker_node
 172.31.84.148: worker_node
 172.31.64.194: worker_node
 172.31.92.17: worker_node
 172.31.75.125: worker_node
 172.31.93.240: worker_node
 172.31.92.163: worker_node
 172.31.93.90: worker_node
 172.31.70.238: worker_node
 172.31.68.146: worker_node
 172.31.74.15: worker_node
 172.31.70.244: worker_node

Resources
---------------------------------------------------------------
Usage:
 960.0/960.0 CPU
 0.00/2672.866 GiB memory
 0.00/1065.390 GiB object_store_memory

Demands:
 {'CPU': 0.2}: 200+ pending tasks/actors
```

**Comment by iycheng** [comment]
We actually only have 224 workers (4 cpu) + 1 head (64cpu) alive and started 4800 actors.

It's supposed to start 250 workers. 

ray status shows 250 healthy, but dashboard shows 224 healthy and 50 failure. 

It seems like autoscaler is not working properly.

**Comment by iycheng** [comment]
More informations:
The GCS is returning the right info, for example, if the node is marked dead by GCS it won't show up in the resource (GetAllResourceUsage)

Autoscaler should be able to detect the node failure and either terminate it and bring a new one back or just recover the local one.

@wuisawesome  could you take a look at what's going wrong?

I have a cluster here for you

https://console.anyscale.com/o/anyscale-internal/projects/prj_LFKjNprpiYt4AjAf1NdLDJwn/clusters/ses_J1aXGQu5yPFFRGsijHqR7tsn?command-history-section=command_history

If you run `ray status`

```
ray status
======== Autoscaler status: 2022-06-29 16:58:01.616043 ========
Node status
---------------------------------------------------------------
Healthy:
 250 worker_node
 1 head_node
Pending:
 (no pending nodes)
Recent failures:
 172.31.68.165: worker_node
 172.31.76.112: worker_node
 172.31.80.42: worker_node
 172.31.84.217: worker_node
 172.31.79.160: worker_node
 172.31.89.143: worker_node
 172.31.64.88: worker_node
 172.31.74.105: worker_node
 172.31.91.22: worker_node
 172.31.94.10: worker_node
 172.31.76.232: worker_node
 172.31.86.200: worker_node
 172.31.92.250: worker_node
 172.31.73.5: worker_node
 172.31.77.64: worker_node
 172.31.86.152: worker_node
 172.31.93.182: worker_node
 172.31.66.231: worker_node
 172.31.86.127: worker_node

Resources
---------------------------------------------------------------
Usage:
 0.0/1020.0 CPU
 0.00/2839.032 GiB memory
 0.00/1132.080 GiB object_store_memory
```

It actually should be 1064 CPUS (250 workers * 4 CPUs + 1 head * 64 CPUs)

The failure is because there are more than 16 nodes failed and they are never back.

**Comment by wuisawesome** [comment]
It's quite concerning that the resource and node counts are inconsistent. also, the fact that the `wait_cluster.py` finishes makes me concerned things may actually be crashing in the ray core?

**Comment by stephanie-wang** [comment]
@iycheng can you confirm that you think this is not a problem with OSS? If so, let's remove the release-blocker tag.

**Comment by iycheng** [comment]
@wuisawesome I don't think it's a problem of ray core. In the cluster we set 250 as min/max for workers. So autoscaler should just work. Even `wait_cluster.py` finished, worker might crash in the future. The issue here is that, the cluster is never scaling to 250 nodes if there is a node failure.  (Even if there is demands not fulfilled [link](https://github.com/ray-project/ray/issues/26138#issuecomment-1169394953)).


@stephanie-wang I need to double check it with @wuisawesome to confirm this.

**Comment by iycheng** [comment]
@wuisawesome  I think there is some bugs in wait_cluster

https://github.com/ray-project/ray/blob/master/release/ray_release/command_runner/_wait_cluster.py#L48

We didn't check Alive actually. cc @rkooo567

**Comment by stephanie-wang** [comment]
What were the symptoms for this issue? I'm wondering if #26240 is related to this too?

**Comment by wuisawesome** [comment]
We did a bit of digging and it seems like there's a problem in which the autoscaler thinks there are more healthy nodes in the cluster than GCS does. I suspect this can be manifesting itself in many different ways (we're working off of a repro cluster that @iycheng started for us)

**Comment by wuisawesome** [comment]
Ok, it seems this was an infra issue misclassified as an autoscaler issue, due to a bug in the release testing infrastructure (fixed by https://github.com/ray-project/ray/pull/26236). 

The actual infra issue is due to the (private) node provider providing returning corrupt information. The bug is that the output is corrupt.

#26236 means that this should be correctly classified as an infra issue now and retried accordingly.
