### ISSUE TITLE
[tune/core] Question about GPU allocation in Tune

### ISSUE THREAD

**Issue by Harris-Xie** [ray-project/ray#26184]
### Description

If I have 4 nvidia GPUs and there are 30 trials, I set {resources_per_trial={"cpu“：0，”gpu“:0.1}, it means  one gpu can run 10 trials. However, when I start my tune, the trials preferentially run on cuda:0( the first gpu) until there are 10 trials on cuda:0. and then run on the second gpu ,then the third.... the load of the 4 GPUs is evidently unbalanced. 
So, is there a implementation that tune can start trials according to current load of gpu ？or can you tell me where does the tune choose which gpu to start  in the source code so that I can implement it by my strategy on my own. Thanks a lot!

**Comment by Harris-Xie** [comment]
Really appreciate your attention and answer! CUDA_VISIBLE_DEVICES is env variable right? So I think once I set it , it can't be changed during tune is running, so I'm wondering  how can I allocate a new trial on a specific gpu to balance the load of 4 gpu?

**Comment by xwjiang2010** [comment]
@Harris-Xie This is a great question. I did a bit digging into Ray Core concept and it seems there is this `RAY_scheduler_spread_threshold`, which is a global config that controls the fraction of resource utilization on a node after which the scheduler starts to prefer spreading tasks to other nodes. By setting this threshold, users can choose between spread scheduling and pack scheduling. This is a global config meaning that it affects scheduling of all the tasks and actors in the cluster.

Also cc @jjyao as he is definitely more involved in this topic and can better help you on this.

**Comment by xwjiang2010** [comment]
@jjyao ah got it. I think @Harris-Xie is using one machine with 4 GPUs. Is there any other way to specify the intention of spreading the load evenly across the 4 GPUs?

**Comment by jjyao** [comment]
I checked the code and it does what @Harris-Xie says (code is [here](https://github.com/ray-project/ray/blob/ccabba88ae2f464688eab1e72f111b49b5dc9155/src/ray/raylet/scheduling/local_resource_manager.cc#L159)). The reason is that we want to avoid fragmentation (e.g. in case we want to schedule a 1 GPU task later). 

Currently there is no way to change this behavior. For now, you can do what @matthewdeng suggests: overriding `CUDA_VISIBLE_DEVICES` env var. Ray is not doing anything special to restrict your task to a particular GPU besides setting `CUDA_VISIBLE_DEVICES` env var (https://docs.ray.io/en/master/ray-core/tasks/using-ray-with-gpus.html). In your task code, you can just do `os.environ["CUDA_VISIBLE_DEVICES"] = xxx` to change it. @xwjiang2010 Does tune allow people to execute that piece of code for each trial?

**Comment by jjyao** [comment]
Actually can you also set "gpu" to 0.13 (4 / 30), which will force Ray to use all 4 gpus.

**Comment by Harris-Xie** [comment]
Oh, thanks a lot, your answer really helps me a lot!  There is still only one question I want to ask you: when I get the `allocation` in local_resource_manager.cc , how does Ray implement GPU isolation according to `allocation` ,,does ray do so by setting `CUDA_VISIBLE_DEVICES` env variable ? could you yell me where the code is ?

**Comment by Harris-Xie** [comment]
@jjyao
