### ISSUE TITLE
[Datasets] fsspec HTTPFileSystem does not work for reading http files

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#26423]
### What happened + What you expected to happen

```
from fsspec.implementations.http import HTTPFileSystem
import ray; ray.data.read_csv('https://air-example-data.s3.us-east-2.amazonaws.com/breast_cancer.csv', filesystem=HTTPFileSystem())
```

This fails and is an important user path.

The main problem seems to be in https://github.com/ray-project/ray/blob/0c469e490e0ed5e6ca848c627f3b852382e2bf2a/python/ray/data/datasource/file_based_datasource.py#L505 since if you comment this out then the code will run.

What ends up happening is that the `https` prefix is removed and then `HTTPFileSystem().info(path)` begins to return null.

### Versions / Dependencies

python 3.7, pyarrow 6.0.1

### Reproduction script

```
from fsspec.implementations.http import HTTPFileSystem
import ray; ray.data.read_csv('https://air-example-data.s3.us-east-2.amazonaws.com/breast_cancer.csv', filesystem=HTTPFileSystem())
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by clarkzinzow** [comment]
Interesting, removing the protocol prefix is required for other filesystems (e.g. S3), but must not be for the HTTP fsspec implementation.

We can certainly add a special-case for `HTTPFileSystem` to make sure the protocol isn't removed.

**Comment by richardliaw** [comment]
Actually, can we also make it so that HTTPFileSystem is automatically inferred if `fsspec` is installed and the provided uri is prefixed with `http`?

This would allow all of our examples to read directly from the s3 http links.

**Comment by clarkzinzow** [comment]
>Actually, can we also make it so that HTTPFileSystem is automatically inferred if fsspec is installed and the provided uri is prefixed with http?

Definitely, that's a good idea!

>This would allow all of our examples to read directly from the s3 http links.

Hmm I'm not sure that we want to advise that over the S3 object URIs, I think that this would result in degraded performance and some usability issues. We should instead focus on fixing the current perf and usability issues with the S3 object URI path, since that is more tailored to the storage system and therefore has a higher perf and usability ceiling.

**Comment by richardliaw** [comment]
Now if you can get this to work without configuring credentials, I think that'd be great. But as far as I can tell it's not possible?

**Comment by clarkzinzow** [comment]
> It seems to me that without proper S3 configuration, you cannot read from a public AWS bucket using the S3FS though:

@richardliaw That's the usability issue that I'm referring to, and @c21 is looking into that this sprint (today, actually!) so we should have a feasibility conclusion this sprint.

>OSError: When reading information for key 'breast_cancer.csv' in bucket 'air-example-data': AWS Error [code 100]: No response body.

Note that this isn't an access denied error, which is an [error code 15](https://github.com/aws/aws-sdk-cpp/blob/c4a5c1e5c861c880e638f66e37947094b4548e9e/aws-cpp-sdk-s3/include/aws/s3/S3Errors.h#L35), this is an unknown error, so I don't know whether this is a clear-cut-and-dry credentials/permissions issue.

>Now if you can get this to work without configuring credentials, I think that'd be great. But as far as I can tell it's not possible?

We should be able to grant read-only access to public, anonymous users, which shouldn't require credential configuration. https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-bucket-policies.html#example-bucket-policies-use-case-2

We also should disable ACLs, IIUC the most restrictive access policy between the bucket policies and the ACLs will be applied, which may prevent public, anonymous access: https://docs.amazonaws.cn/en_us/AmazonS3/latest/userguide/about-object-ownership.html

I've made the following changes to the `air-example-data` bucket:

1. I changed the public access bucket policy to just reading, since we really shouldn't allow public writes, which we were previously.
2. I changed the object ownership to "Bucket owner enforced", which should disable ACLs and only enforce access via the bucket policies.

This appears to be as public as we can make the S3 bucket (in terms of reading), so @c21 can you test that access with the `s3://` protocol and the Arrow S3 filesystem still doesn't work? We may need to specify `s3 = S3FileSystem(anonymous=True)` so Arrow doesn't try to include AWS credentials, and we should also try to match the S3 region of the bucket, if required: `s3 = S3FileSystem(region="us-east-2", anonymous=True)`.

**Comment by richardliaw** [comment]
Nice! So seems like the explicit configuration works and datasets will work now.

**Comment by clarkzinzow** [comment]
@richardliaw Thanks for checking! In that case, I think that defaulting to the HTTPS URLs in our docs and examples should be the default, although we should do a performance check; if the HTTPS fsspec filesystem is way slower than the Arrow S3 filesystem, then we should recommend using S3 URLs over the HTTPS URLs in the docs.

**Comment by richardliaw** [comment]
How did you come to that conclusion? The dataset option seems to work fine right, so we can default to s3 right?

**Comment by clarkzinzow** [comment]
Ah is the manual `S3FileSystem` configuration, `s3 = S3FileSystem(region="us-east-2", anonymous=True)`, not a dealbreaker? I thought that would dip it below the docs quality bar.

**Comment by richardliaw** [comment]
Hmm, well after you fixed the ACLs on the bucket, you can just do:

```
(base) root@95868ebcf700:/ray/doc/source/ray-air/examples# ipython
Python 3.7.9 (default, Aug 31 2020, 12:42:55)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.34.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import ray;
   ...: ds = ray.data.read_csv("s3://air-example-data/breast_cancer.csv")
   ...:
   ...:
2022-07-11 12:42:30,958	INFO services.py:1483 -- View the Ray dashboard at http://127.0.0.1:8265
2022-07-11 12:42:30,961	WARNING services.py:2018 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 2684354560 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.11gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2022-07-11 12:42:36,853	WARNING read_api.py:264 -- The number of blocks in this dataset (1) limits its parallelism to 1 concurrent tasks. This is much less than the number of available CPU slots in the cluster. Use `.repartition(n)` to increase the number of dataset blocks.

In [2]: ds
Out[2]: Dataset(num_blocks=1, num_rows=569, schema={mean radius: double, mean texture: double, mean perimeter: double, mean area: double, mean smoothness: double, mean compactness: double, mean concavity: double, mean concave points: double, mean symmetry: double, mean fractal dimension: double, radius error: double, texture error: double, perimeter error: double, area error: double, smoothness error: double, compactness error: double, concavity error: double, concave points error: double, symmetry error: double, fractal dimension error: double, worst radius: double, worst texture: double, worst perimeter: double, worst area: double, worst smoothness: double, worst compactness: double, worst concavity: double, worst concave points: double, worst symmetry: double, worst fractal dimension: double, target: int64})
```
now, so s3 should work fine with datasets without any other configuration knobs?

**Comment by clarkzinzow** [comment]
Oh really? By

>Minimal configuration is broken, and anonymous without region will break too.

I thought that you mean that `ds = ray.data.read_csv("s3://air-example-data/breast_cancer.csv")` would break, since there's no explicit region-specific and anonymous filesystem specified. I.e. I thought that
```python
from pyarrow.fs import S3FileSystem

s3 = S3FileSystem(region="us-east-2", anonymous=True)
ds = ray.data.read_csv("s3://air-example-data/breast_cancer.csv", filesystem=s3)
```
would be required.

**Comment by richardliaw** [comment]
Yep I meant `Test Arrow with minimal configuration` codeblock is broken. Cool, thanks!

let's leave this open as the https path is still quite important to fix.

**Comment by clarkzinzow** [comment]
@c21 If the latter (`ds = ray.data.read_csv("s3://air-example-data/breast_cancer.csv")`) works, then we can consider https://github.com/ray-project/ray/issues/19799 to be mitigated, and we should ping @dmatrix to try out public, anonymous access with Ray Datasets on one of our `air-example-data` S3 datasets. If it works, then we can consider that issue fully resolved.

@dmatrix could you try [this reproduction](https://github.com/ray-project/ray/issues/19799#issuecomment-1159322867) (i.e. use the same environment) but with one of our `air-example-data` datasets? Something like this should do the trick:

```python
import ray

ray.init()
ds = ray.data.read_csv("s3://air-example-data/breast_cancer.csv")
```

**Comment by richardliaw** [comment]
> ds = ray.data.read_csv("s3://air-example-data/breast_cancer.csv")

OK this is unfortunate. I tried pushing this onto CI, and it's still not working, even after we adjusted the ACLs.
