### ISSUE TITLE
[ML][Nightly-test] tune_scalability_network_overhead is failing

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#26722]
### What happened + What you expected to happen

please investigate, this is a release blocker.

### Versions / Dependencies

latest ray.

### Reproduction script

https://b534fd88.us1a.app.preset.io/superset/dashboard/19/?native_filters_key=eEV0-NhAr6leVqaXtREv9Dac9epk5cVV-ZIJm-27j0EUa9wjk6jlLBxz_olU2qTM

### Issue Severity

High: It blocks me from completing my task.

**Comment by scv119** [comment]
@jiaodong @matthewdeng please triage.

**Comment by jiaodong** [comment]
@scv119 i think this test is just flaky, it consistently passed in past week except one timeout

https://b534fd88.us1a.app.preset.io/superset/dashboard/19/?native_filters_key=p_QMoBOhMHSwORBahYtwpNhnb0bNjUPpdA0PySa_XK6EyoUVr5D_sj7V4NbLt-Vo

And it's passing in past two days again.

**Comment by jiaodong** [comment]
This test's weekly version has been failing since 6/18 but mostly due to its aggressive timeout of 15mins but meanwhile requesting 100 hosts to run. I will submit a PR and increase its timeout.

The nightly version with 20 hosts finishes consistently, which I would take it as signal of codebase healthiness, mostly larger scale stability.
