### ISSUE TITLE
[Core] [DAG] Proposal on adding `build()` API for DAGNodeBase to return a DAG handle.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#26941]
Ray DAG defines very useful APIs to allow users submit tasks in static DAG usage. 
We should standardize the Ray DAG APIs and let users to optimize their DAG in different implementation.

I'm using the Ray DAG for building our multiple controllers execution engine based on Ray, that means our users program their applications in Ray DAG APIs, and then our engine receives the whole DAG and split it into different sub DAGs for feeding to every controller. Every controller optimizes its local sub dag and then submit the dag nodes as Ray tasks.

The working pipeline looks like:
![image](https://user-images.githubusercontent.com/19473861/180638840-905f0ca0-f3bc-4cee-9579-c4a9fa0ca09e.png)

So we need a `build()` API which is used for building the whole DAG and returning it as a handle.
```python
a = A.bind()
b = B.bind(a)
my_dag = b.build() # my_dag is a DAG handle, which holds the final node `b`.
obj = my_dag.execute()    # invoke `b.execute()`under the hood.
ray.get(obj)
```

We only propose adding a new API without any breakage in this issue.

**Comment by jovany-wang** [comment]
@jiaodong @ericl

**Comment by jiaodong** [comment]
At high level having a `build` makes sense as Ray DAG means to provide a way to build static computation graphs, where the next natural step is static graph analysis / inject / fusion. Ray Serve team's Deployment Graph actually already had this API to convert, replace and generate `Deployment` objects to facilitate declarative deployment of entire DAG.

A few questions of your diagram and API:
 * What does "Multi Controller" mean in your diagram ? In my understanding the process that calls `.execute()` becomes the driver of entire DAG where acts as single controller, rather than multiple.
 * What should `build()` return here ? Currently you can call `b` as `my_dag` and it can be executed without the `build()` returned DAG handle -- the root node of our chose becomes the DAG handle already.

**Comment by jovany-wang** [comment]
@jiaodong Sorry for the delay response. I'll update details ASAP. :)

**Comment by jovany-wang** [comment]
> What does "Multi Controller" mean in your diagram ? In my understanding the process that calls .execute() becomes the driver of entire DAG where acts as single controller, rather than multiple.

We have N parties in one Ray cluster, and the user script will be distributed to N parties. Every party runs it as a driver, so you know it should be N drivers. Every driver acts as a controller.
For example, 
```python
a_o = a.options(res=PARTY_A)bind()
b_o = b.options(res=PARTY_B)bind()
c_o = c.options(res=PARTY_B).bind(a_o, b_o)
c_o.execute()
```
The above script will be distributed to  party A and B.
Task a should be executed in party A while task b and c should be executed in party B. 

Therefore, what my custom DAG executor should do is extract the partial DAG and submit it as a DAG. That's why this could be a multiple controllers.


> What should build() return here ? Currently you can call b as my_dag and it can be executed without the build() returned DAG handle -- the root node of our chose becomes the DAG handle already.

We expect that build() returns a DAG Handle which holds the final node of the graph.
The reason for needing the DAG handle is: Adding a new API in my framework to get the output of the final node, like `my_dag.get()`

**Comment by jovany-wang** [comment]
Closing this now, will open it once we still need
