### ISSUE TITLE
[data] Crash with multi-column tensor dataset

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#27116]
### What happened + What you expected to happen

Try to read any multi-column tensor dataset (example in https://github.com/ray-project/ray/pull/26952). It crashes with:

```
    #TODO(ekl) why does this crash with TensorDType not understood?

    # Read a multi-column example dataset.
    ray.data.read_parquet("example://parquet_images_mini")
    # -> Dataset(num_blocks=3, num_rows=3, schema={image: TensorDtype, label: object})

    next(ds.iter_batches())
    # -> TypeError: data type 'TensorDtype' not understood
```

### Versions / Dependencies

master

### Reproduction script

See above.

**Comment by clarkzinzow** [comment]
Investigated this, the sidecar Pandas metadata shows that it was written with an older version of the extension type, which is why the read failed in the tensor docs PR after rebasing on master and getting the new version of the extension type. Doing a roundtrip on regenerated data works as expected on latest master:
```
In [15]: ds = ray.data.read_datasource(ImageFolderDatasource(), root="/mnt/data/workspace/ray2/python/ray/data/tests/image-folder", size=(128, 128))

In [16]: ds
Out[16]: Dataset(num_blocks=3, num_rows=3, schema={image: TensorDtype(shape=(128, 128, 3), dtype=uint8), label: object})

In [17]: ds.write_parquet("/mnt/data/workspace/scratch/parquet_images_mini")

In [18]: ds2 = ray.data.read_parquet("/mnt/data/workspace/scratch/parquet_images_mini")

In [19]: ds2
Out[19]: Dataset(num_blocks=3, num_rows=3, schema={image: ArrowTensorType(shape=(128, 128, 3), dtype=uint8), label: string})

In [20]: next(ds2.iter_batches())
Out[20]:
                                               image label
0  [[[ 96,  76,  61], [ 92,  72,  57], [ 92,  72,...   cat
1  [[[ 38,  38,  38], [ 39,  39,  39], [ 39,  39,...   cat
2  [[[ 47,  39,  33], [ 43,  36,  29], [ 43,  36,...   dog
```
Closing this as solved!

**Comment by orm011** [comment]
Here's a potential workaround to get you out of hot water if you also run into this issue:
`
import pyarrow as pa
def read_parquet_workaround(path):
    tab = pa.parquet.read_table(path)
    df = tab.to_pandas(ignore_metadata=True) # this would fail without the flag.
    return df # df will somehow still include the new ray TensorArray 
`
One downside of this solution is that some third party code (eg `ray.data.Dataset.iter_batches()`)
will call `to_pandas()`  on its own.

Another downside is that I'm not sure if ignore_metadata will also break other things.
Maybe there's a better way.

**Comment by orm011** [comment]
Looks like the main issue is that as of 1.13 metadata was written as follows:

``` # ray 1.13
from ray.data.extensions import TensorArray
import pandas as pd
import numpy as np
import pyarrow as pa

df = pd.DataFrame({'arr':TensorArray(np.ones(6).reshape(2,3))})
df.to_parquet('/tmp/arr_1.13.parquet')
tab = pa.parquet.read_schema('/tmp/arr_1.13.parquet')
tab.pandas_metadata

{'index_columns': [{'kind': 'range',
   'name': None,
   'start': 0,
   'stop': 2,
   'step': 1}],
 'column_indexes': [{'name': None,
   'field_name': None,
   'pandas_type': 'unicode',
   'numpy_type': 'object',
   'metadata': {'encoding': 'UTF-8'}}],
 'columns': [{'name': 'arr',
   'field_name': 'arr',
   'pandas_type': 'object',
   'numpy_type': 'TensorDtype', ### NB
   'metadata': None}],
 'creator': {'library': 'pyarrow', 'version': '6.0.1'},
 'pandas_version': '1.4.3'}
```

In the new version, when converting to pandas, the 'TensorArray' string in that metadata is passed to 
`TensorDtype.construct_from_string(type_str)` in [https://github.com/pandas-dev/pandas/blob/6df6691438dde3aa9c6fdfa359d39b730e29e331/pandas/core/dtypes/base.py#L521](pandas) which  fails.

The new version can read its own data because it writes more information to metadata:
``` # ray 2.
df = pd.DataFrame({'arr':TensorArray(np.ones(6).reshape(2,3))})
df.to_parquet('/tmp/arr2.parquet')
tab = pa.parquet.read_schema('/tmp/arr2.parquet')
tab.pandas_metadata

{'index_columns': [{'kind': 'range',
   'name': None,
   'start': 0,
   'stop': 2,
   'step': 1}],
 'column_indexes': [{'name': None,
   'field_name': None,
   'pandas_type': 'unicode',
   'numpy_type': 'object',
   'metadata': {'encoding': 'UTF-8'}}],
 'columns': [{'name': 'arr',
   'field_name': 'arr',
   'pandas_type': 'object',
   'numpy_type': 'TensorDtype(shape=(3,), dtype=float64)', #### <- here
   'metadata': None}],
 'creator': {'library': 'pyarrow', 'version': '8.0.0'},
 'pandas_version': '1.4.3'}
```

The shape and type are still available in elsewhere, as `tab[0].type`, on either of these metadata,  on ray 2 yields `ArrowTensorType(shape=(3,), dtype=double)`
