### ISSUE TITLE
[tune] PBT exploits trials that have no checkpoint, yet

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#27170]
~It seems that PBT sometimes tries to exploit trials that are currently being restarted or have just been restarted with old statistics.~

PBT tries to exploit trials that never checkpointed. While this could be acceptable for hyperparameter exploitation, it will not progress training.

We should investigate this to see if this is actually the case.

On a different note, PBT pauses function trainable trials that never checkpointed and tries to resume them later. This doesn't work as there is no checkpoint to resume from.

**Comment by xwjiang2010** [comment]
I don't quite get this one, can you elaborate?

**Comment by krfricke** [comment]
I've looked into this and updated the issue description and title.

I think one of the main problems is that pbt both exploits and tries to pause/resume trials for which it has not received a checkpoint. These trials will always run from scratch.

The solution for the horovod test is to either checkpoint every step or only report once at the end of the iteration - I'll open a PR for that

**Comment by akashe** [comment]
Hi,

I am seeing the same behavior as above in version 2 also. PBT starts perturbations from checkpoints that don't exist. Was this supposed to be fixed in version 2?

Best,
Akash

**Comment by krfricke** [comment]
@justinvyu has this been resolved by https://github.com/ray-project/ray/pull/28509?

**Comment by justinvyu** [comment]
I believe that PR doesn't fix this issue. My understanding of this issue is that `checkpoint_interval > perturbation_interval`, which is part of the user-defined configuration. I don't have a good way of fixing the case where the user doesn't checkpoint in time for the first perturbation. I have added suggestions in updated examples/guides that recommends checkpointing on every perturbation, or more often than perturbations (ex: [this guide](https://docs.ray.io/en/master/tune/examples/pbt_guide.html#function-api-with-population-based-training)). Perhaps we should log a warning and recommend a different checkpointing interval. However, one problem with function checkpointing is that the interval is not controlled by Tune.

I do have a PR  that I'll post today that fixes a related issue, where PBT only pulls the checkpoint of trials in the upper quantile, but it's possible for a lower-quantile trial to get upgraded. In this case, my fix was to always save the checkpoint of each trial, since there's no guarantees of which trial will need to be exploited in the next perturbation round.

**Comment by krfricke** [comment]
@justinvyu with your improvements to PBT, this should be resolved, right?

**Comment by krfricke** [comment]
Closing this for now
