### ISSUE TITLE
[CI] //rllib:env/tests/test_remote_inference_cartpole is timing out

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27177]
### What happened + What you expected to happen

 https://buildkite.com/ray-project/ray-builders-branch/builds/9013#01824276-8612-4d4b-8072-94b4fe6cbc38

please unbreak now.

### Versions / Dependencies

releases/2.0.0 branch

### Reproduction script

CI

### Issue Severity

High: It blocks me from completing my task.

**Comment by gjoliver** [comment]
I am going to close this issue.
It seems the test failed first time because CI failed to acquire compute instances.
I tried the test again and it passed fine.

<img width="1191" alt="Screen Shot 2022-07-28 at 3 37 18 PM" src="https://user-images.githubusercontent.com/6347585/181649274-10ae0740-e0e1-4ede-8d54-10a00467eed6.png">
