### ISSUE TITLE
Implementing wandb sweep with RLlib and tune.run

### ISSUE THREAD

**Issue by dejangrubisic** [ray-project/ray#27513]
### Description

Is there a way to run wandb sweeps with RLLib and ray.tune and get results like on picture below? 

![image](https://user-images.githubusercontent.com/40608743/182948781-2ec47d0e-e14b-4680-8587-8225e5ac1b43.png)

From documentation, I only found WandbLoggerCallback approach, but that doesn't really produce a sweep even if you set parameters in config like:
```
ray.tune(...
config={'lr': tune.uniform(1e-3, 1e-6), ...},
callbacks=[ WandbLoggerCallback(...)]
...)
```
I run [mnist_torch_example](https://github.com/NERSC/slurm-ray-cluster/blob/master/examples/mnist_pytorch_trainable.py) getting only:
<img width="1686" alt="image" src="https://user-images.githubusercontent.com/40608743/182949765-516809b5-7c6e-49f7-880a-22181cea1626.png">

### Use case

This would be highly valuable for tuning hyperparameters.

**Comment by Juno-T** [comment]
As a work around, you can use `WandbLoggerCallback` and start ray's hyperparameter search. These search trials will appear in a run's group in your wandb project, at which you can add the visualization panels manually.

In case you can't find the visualization panels: Click [+ Add Panel] button at the top right corner, then click Parallel Coordinates or Parameter Importance.

With that being said, I still support the the request of having wandb sweep integration because of these two reasons:
1. Easier visualization without having to manually setup.
2. In case someone prefer using wandb sweep's hparam search instead of ray tune's. This is probably exclusively for someone who want to use ray rllib only.

**Comment by dejangrubisic** [comment]
@Juno-T thank you for your answer! I think I found a problem.
I previously Initialized id in WandbLoggerCallback(...id=timestamp) and that resulted in visualizing only 1 last trial. Seems like trials override each other. When id is not initialized it logs num_samples trials.

Any quick fix for this?
Note: I was initializing id with custom id, because wandb.run == None after ray.tune.run(...) .

**Comment by dejangrubisic** [comment]
Solution:

```
analysis = tune.run(...)
trial = analysis.trials[0] # say we take 1st trial

api = wandb.Api()
wandb_run = api.run(f'{entity}/{project}/{trial.trial_id}') # Note: don't override run, if you say run = api.run(..) it will throw an error
wandb_run.upload_file('my_artifacts/file.png')
```

**Comment by xwjiang2010** [comment]
cc @nikitavemuri @anabranch
