### ISSUE TITLE
Deprecate "num_workers" argument.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#2759]
We should probably get rid of the `num_workers` argument to `ray.init` and `ray start`. A couple reasons:
1. People accidentally use it when they actually want to use `--num-cpus` or other resource constraints.
2. It doesn't really mean anything since the scheduler can always start more workers than `num_workers`. `num_workers` is just the "initial" number of workers started.

The one use case that I can think of for the argument is when you want to have a test that uses a really large number of CPUs, but doesn't actually need 1000 workers. The test can be made more lightweight by not starting a ton of workers.

cc @atumanov

**Comment by atumanov** [comment]
related to the discussion on limiting the number of concurrent worker process starts in https://github.com/ray-project/ray/pull/2753. 
My preference will be to deprecate `num_workers` and reason about resources only, at least from the user's perspective. Worker processes should be an internal container mechanism automatically handled by the backend. I think `num_workers` remained for historical reasons and predates our capacity-aware resource scheduling.

**Comment by raulchen** [comment]
I prefer to hide `num_workers` from normal users as well. 

In addition to the above reasons. Another one I'm thinking is that we may want to only create workers on demand in the future. 

The context is that as we run multiple jobs (each job is a different use case) in one single large cluster, we need to isolate the worker runtime by jobs. Because: 1) each job depends on different libraries (or even different versions of one library); 2) the task may touch global states (e.g., environment variables and sys.path). Thus we may want to let one worker only work for one job.

Runtime isolation is a much bigger topic. I raise it here just because this issue reminds me of it. I haven't thought thoroughly though. We can open another issue to discuss it later. 

FWIW, I agree that worker is an internal concept that should be hidden from users.

**Comment by robertnishihara** [comment]
Done by #3114.
