### ISSUE TITLE
[Core] RayActorError provides actor's information in the error

### ISSUE THREAD

**Issue by ljjsalt** [ray-project/ray#27800]
### Description

For people who want to have better control over the node failures, and handle the error such as `RayActorError` by themselves. I think it's necessary to make things like `actor_id` as an attributed of the error.

### Use case

```python
actor_table: Dict[str, RayActor] = ...
completed_actors, _ = ray.wait(actors)
obj_ref = completed_actors[0]
try:
    ray.get(obj_ref)
except RayActorError as err:
    actor_id = err.actor_id

    actor = actor_table[actor_id]
    # do something to the failed actor
```

**Comment by jjyao** [comment]
Sounds like a reasonable thing to add. cc @rkooo567.

Just curious: what if you maintain the mapping from obj_ref to actor yourself?

**Comment by ljjsalt** [comment]
> Sounds like a reasonable thing to add. cc @rkooo567.
> 
> Just curious: what if you maintain the mapping from obj_ref to actor yourself?

I think that works, too. But consider node failure is not supposed to happen frequently, it's not worthing tracing every obj refs.

**Comment by suquark** [comment]
I am also pro for this feature: especially during debugging and error handling, it is hard to associate the actor_id with the actor method failure automatically, because we do not know where the error could be raised beforehand. This is actually an observability issue.

Also, `RayActorError` did provide `actor_id` if the actor crashes, it is a bit strange that `actor_id` is not given when there is an exception in the actor.

**Comment by scottsun94** [comment]
@ljjsalt Is this fixed by the merged PR? Shall we close then?

**Comment by ljjsalt** [comment]
@scottsun94 
Yeah, I think the merged PR fixed the issue.
