### ISSUE TITLE
[Test][State Observability] Dashboard snapshot not returning during the serve_multi_deployment_1k_noop_replica test

### ISSUE THREAD

**Issue by shawnpanda** [ray-project/ray#28007]
### What happened + What you expected to happen

Periodically getting this error when polling the Ray dashboard for a snapshot. Normally the data field contains the snapshot object. This error tends to be transient and the cluster may stop responding for awhile and then responding to the endpoint again.
Test: serve_multi_deployment_1k_noop_replica_1660833515

Endpoint is /api/snapshot.
Example clusters:
- [ses_zx3V8zDWLjMcKA5uhSDsY9f1](https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_zx3V8zDWLjMcKA5uhSDsY9f1)
- [ses_6hjJGYipV5nzJZ1jRas3uquG](https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_6hjJGYipV5nzJZ1jRas3uquG)

In the prometheus monitoring, I see that the CPU usage of head node is up to 12.5% and memory usage up to 7% around the time when the snapshot api stops responding. So it is unclear to me why the head node would stop responding

### Versions / Dependencies

ray nightly

### Reproduction script

check source of test which is creating the cluster

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rkooo567** [comment]
<img width="628" alt="Screen Shot 2022-08-31 at 10 08 52 AM" src="https://user-images.githubusercontent.com/18510752/187738736-2cf148cf-b8a9-4bdb-a763-757551c96ad5.png">

Here's the problem as you see, it takes 30+ seconds (the timeout) to finish processing each request occasionally. We need to add more observbility into the dashboard server to figure out the bottleneck, but I think this time, it is not GCS (because it should fail within 3 seconds). Highly likely the dashboard server is overloaded and slow due to something
