### ISSUE TITLE
[autoscaler] Node launch race condition

### ISSUE THREAD

**Issue by kpavel** [ray-project/ray#28150]
### What happened + What you expected to happen

Autoscaler hits race condition resulting in unnecessary nodes provisioning.

It happens in the following way:

- Thread0 **Create N nodes** request submitted in autoscaler
- Thread1 **pending_launches** set to **N** in autoscaler
- Thread1 **(N - x)** nodes created by node_provider
- Thread0 **non_terminated_nodes** called
- Thread1 **N** nodes created and returned
- Thread1 pending_launches  set to **0**
- Thread0 non_terminated_nodes  returns **(N - x)** nodes
- Thread0 **Create x nodes** request submitted in autoscaler -> wrong. those nodes already been created. this results in bouncing create/delete which may result in high cost customer impact  

### Versions / Dependencies

Latest ray

### Reproduction script

Not applicable

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by wuisawesome** [comment]
Mitigation is for users to set 

```
provider:
    foreground_node_launch: True
```

which will serialize node launching

**Comment by wuisawesome** [comment]
i guess ideally what we want to do is define a critical section from before non_terminated_nodes updates to after pending_launches decrements.

since the updated state that non_terminated_nodes reads is somewhere in the middle of create_node we would have to lock around all of create_node i think. from a performance perspective, i think there are a few implications
1. The autoscaler update loop can be blocked by a long `create_node` call. This could be mitigated by small batches (which tends to make `create_node` shorter, but we'd also be relying on some somewhat concerning details of the system scheduler.
2. There will effectively only be one `NodeLauncher` thread active at a time (since all the non-trivial work will be in the critical section).

**Comment by wuisawesome** [comment]
essentially it would look something like this 

```
def launch_node(self : NodeLauncher, config: Dict[str, Any], count: int, node_type: str):
    self.log("Got {} nodes to launch.".format(count))
    with lock:
      self._launch_node(config, count, node_type)
      self.pending.dec(node_type, count)
    # Ideally we'd want to yield back to the main autoscaler thread if it's awake here.
    ...


def _update(self : StandardAutoscaler):
    ...

    with lock:
      # Query the provider to update the list of non-terminated nodes
      self.non_terminated_nodes = NonTerminatedNodes(self.provider)
```

**Comment by kpavel** [comment]
@wuisawesome Thank you for looking into it. There can be another option. Instead of locking whole create_node, we may consider to make **self.pending.dec()** wait until next cycle of **non_terminated_nodes()** finished. Maybe we can just force refresh **non_terminated_nodes** after create, but before **self.pending.dec()**?

**Comment by wuisawesome** [comment]
> Maybe we can just force refresh non_terminated_nodes after create, but before self.pending.dec()?

Hmmm naively, it feels like we would double count nodes in that case? (let's say 5/10 nodes launch, then pending will be 5 and non_terminated_nodes will be 5, so nothing new will be launched until the next iteration). 

it works (since the next iteration would be fine) but would be slower right?

**Comment by kpavel** [comment]
Yes, this will make create_node slower by single cycle of non_terminated_nodes (that suppose to be fast). Usually, after nodes created it takes time until operating system finishes boot, so shouldn't be an impact.
Have a feeling that impact of locking the create_node() with non_terminated_nodes() will be more significant.

**Comment by wuisawesome** [comment]
so actually that approach has relies on the node launchers to finish decrementing before the autoscaler wakes up again, which feels safe (but technically not theoretically safe).

after thinking about it, a safe, but more complicated way, would be to do something like

```
def _update(self : StandardAutoscaler):
    ...
    num_waiting_node_launchers = self.launcher_cv.notify_all()
    for _ in range(num_waiting_node_launchers):
        self.node_launcher_semahpore.acquire()
    pending_launches_dict = pending_launches.breakdown()
    # Query the provider to update the list of non-terminated nodes
    self.non_terminated_nodes = NonTerminatedNodes(self.provider)
```

and node_launcher would do

```
def launch_node(self : NodeLauncher, config: Dict[str, Any], count: int, node_type: str):
    self.log("Got {} nodes to launch.".format(count))
    self._launch_node(config, count, node_type)
    self.launcher_cv.wait()
    self.pending.dec(node_type, count)
    self.node_launcher_semahpore.acquire()
    ...
```

This is a bit complicated because `cv.notify_all()` doesn't actually return anything and `cv.wait` actually requires messing with the lock a bit, but such a class could be implemented. 

Essentially, I think what we're distilling this down to is that at a high level we:
* ensure safety by erring on the side of overestimating the number of nodes
* in the vast majority of cases, everything can happen in a single update with no additional latency

We should also make sure we aren't introducing bugs around idle node calculations

**Comment by anyscalesam** [comment]
Autoscaler v2 fixes this (see here: https://docs.ray.io/en/latest/cluster/key-concepts.html#autoscaling)
