### ISSUE TITLE
[tune] pb2 np.sqrt takes a negative input

### ISSUE THREAD

**Issue by chengscott** [ray-project/ray#28267]
### What happened + What you expected to happen

`venv/lib/python3.9/site-packages/ray/tune/schedulers/pb2_utils.py:102: RuntimeWarning:invalid value encountered in sqrt`
np.sqrt should not have a negative input
in line [101](https://github.com/ray-project/ray/blob/master/python/ray/tune/schedulers/pb2_utils.py#L101), if `m.X.shape[0]` is less than 3, `beta_t` would be negative

### Versions / Dependencies

Python 3.9.13 (main, Jul 11 2022, 14:24:14) [GCC 12.1.0] on linux
ray 1.13.0

### Reproduction script

N/A

**Comment by matthewdeng** [comment]
@justinvyu should this just be `beta_t = max(beta_t, 0)`?

Secondary to this, I took a quick look at https://arxiv.org/pdf/2002.02518.pdf and saw them use `βt = c1 + log(c2t)`, so maybe this is wrong in the first place?

**Comment by justinvyu** [comment]
Yup this looks wrong. After we make the `beta_t = c1 + log(c2 * t)` fix, then the beta_t will still only be negative for the first two timesteps (where the model has only been trained on 1/2 hyperparam configs).

If we set `beta_t = max(beta_t, 0)`, then we will be setting the exploration part of the UCB score to 0 for the first 2 iterations of the algorithm. This should be fine since that's basically what's happening right now, since the `sqrt` is producing a `nan`.

Another idea is to let `beta_t = c1` by default with something like `beta_t = c1 + max(0, log(c2 * t))` if `log` is outputting something negative. This makes a bit more sense to me since this `beta_t` schedule seems to be meant for increasing the exploration as the PBT algorithm progresses, starting from some base constant `c1`.

**Comment by chengscott** [comment]
Both `beta_t` implementations are meaningful in UCB since they only affect the exploration in the first 2 iterations.
I would vote for the latter since equation (5) suggests that `beta_t>0`, and I believe the +log term meant to increase exploration logarithmically, but that term accidentally became negative.

**Comment by justinvyu** [comment]
Hey @chengscott, your reasoning makes sense to me. If you're comfortable making this change and creating a PR, could you take on fixing this to be the 2nd option? No worries if you do not have the time, I can make the change.
