### ISSUE TITLE
[tune] How to run multiple trials in parallel?

### ISSUE THREAD

**Issue by LeZhengThu** [ray-project/ray#28292]
I'm following the official example code `https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/async_hyperband_example.py` to configure my tuning process. I have 12 cpus, and I set CPU resource per trial to 1, just like the example above, except that I have a GPU. 
```
 tuner = tune.Tuner(
        tune.with_resources(easy_objective, {"cpu": 1, "gpu": 1}),
        run_config=air.RunConfig(
            name="asynchyperband_test",
            stop=stopping_criteria,
            verbose=1,
        ),
        tune_config=tune.TuneConfig(
            metric="mean_loss", mode="min", scheduler=scheduler, num_samples=100
        ),
        param_space={  # Hyperparameter space
            "steps": 100,
            "width": tune.uniform(10, 100),
            "height": tune.uniform(0, 100),
        },
    )
```
After I run the code, it shows `Number of trials: 18/100 (17 PENDING, 1 RUNNING)`. I have two questions, one is where does 18 come from? The other is why only 1 trial running and all the others pending? I'm using ray version 2.0.0, and all the answers I can find didn't work for me. For example, change `"cpu": 1` to `"cpu": 0.5`.

**Comment by krfricke** [comment]
The number of trials running in parallel is limited by the least available resource, and this is your GPU in that case. Since you only have 1 GPU, you can only run one trial in parallel. If you use `{"cpu": 1, "gpu": 0.5}` you should see 2 parallel trials, etc. In this case, please make sure that your GPU memory is large enough to fit that many models on it (with the basic example you linked this shouldn't be a problem).

If you set `{"cpu": 1, "gpu": 0}` you should see 16 trials running in parallel.

The 18 trials is an estimate from Ray Tune. In random search, if not otherwise specified, Ray Tune creates n trials where `n = 1.1 * number_of_cpus`. The reason for this is that this creates resource requests, and this will trigger autoscaling on clusters where autoscaling is enabled. Creating more trials will clutter the output and is usuallyunnecessary for triggering autoscaling, creating less trials could potentially trigger not enough autoscaling.

You can adjust this number by setting the `TUNE_MAX_PENDING_TRIALS_PG` env variable, but generally it shouldn't hurt to leave it on.

**Comment by LeZhengThu** [comment]
@krfricke Thanks for the reply. According to your reply, does `{"cpu": 1, "gpu": 0}` mean that all the trials will be executed in cpu rather than gpu?

**Comment by krfricke** [comment]
That's right - in the linked example GPU usage is not configured anyway (there is no training happening).

To be clear, `"gpu": 1` means that 1 GPU will be made _available_ to the trial - but the trial still has to then use it. Usually this requires e.g. to set the torch or tensorflow device.

**Comment by LeZhengThu** [comment]
@krfricke  Thank you, that's very helpful. And after I set `{"cpu": 1, "gpu": 1/5}`, 5 cpus are used during tuning as well, which is great. I'll close this issue now.
