### ISSUE TITLE
[Datasets] Push data block produce / concat / convert to upstream and minimize time spent in user code (training & prediction)

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#28526]

**Comment by richardliaw** [comment]
Will this get done for 2.1 @jiaodong, or likely to spillover?

**Comment by clarkzinzow** [comment]
@richardliaw as indicated in the execution tracker sheet, I'm planning to prototype this early next week so we can rerun the motivating benchmark, with delivery planned for end of next week. This is low risk since it's a P1 optimization, it's a pretty small change, and we have a workload to test it against.
