### ISSUE TITLE
[Datasets] `batch_size` is not respected for `map_batches` 

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#28564]
### What happened + What you expected to happen

I have a very simple script (see below) where I do a `map_batches` with a `batch_size=10`. However, none of the batches are actually of size 10.

Looking at the internal `map_batches` code, it seems that the "true" batch size is `min(batch_size, block_size)`. If I have small blocks, these blocks are not aggregated to give me the batch size I want. I want to be able to use a larger batch size so I can fully utilize my GPU for prediction.

Ideally, we should fix this. At worst, we should raise an error if the batch size is incompatible with the block size telling the user to repartition their dataset. But we shouldn't implicitly not use the user-specified batch size.

### Versions / Dependencies

Ray 2.0

### Reproduction script

```python
import ray
from ray.data.datasource import ImageFolderDatasource

ds = ray.data.read_datasource(ImageFolderDatasource(), root="s3://air-example-data-2/1G-image-data-synthetic-raw")
assert ds.count() == 1624

ds = ds.limit(1600) # Evenly divisible by 10

def check_batch_size(df):
    assert len(df) == 10, len(df)

# I would expect all batches to be of size 10
# Instead, NONE of them are size 10. They are all 8 or 9. 
# This is because default parallelism is 200, so block size is ~1624/200 which equals 8 or 9
ds.map_batches(check_batch_size, batch_size=10)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by amogkam** [comment]
cc @clarkzinzow @c21

**Comment by scv119** [comment]
@c21 let you to triage.

**Comment by c21** [comment]
(Also discussed in separate thread, summarize here.)

This is not a bug per se, but is a suprising behavior for user. Based on dataset's current design, batch size can be varied because each batch is just a slice of block it processes. A few action items in short term and long term:

1. (P0) Improve documentation: add note/warning that `batch_size` is not always guaranteed, but mostly a best-effort hint for now.
2. (P0/1) Introduce new behavior to try to achieve `batch_size` for each batch, but not exceeding `batch_size` limit.
3. (P2) Add query plan optimizer to instruct block size, based on batch size in dataset lazy execution mode.

**Comment by stephanie-wang** [comment]
Btw, you can work around this right now by running this beforehand:
```python
ctx = DatasetContext.get_current()
ctx.min_parallelism = 1
```
