### ISSUE TITLE
[tune/train] make log_to_file work for distributed training workflow

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#28718]
### Description

Desired behavior upon setting `log_to_file`:
1. print statements in distributed workers should show up in driver's corresponding folders on a per trial basis.
2. such print statement should show up in a streaming fashion.

One can tail the file and follow along in the progress made with each trial as training proceeds.

### Use case

W&B integration

**Comment by xwjiang2010** [comment]
cc @amogkam @nikitavemuri

**Comment by alanwguo** [comment]
Is there a sense of how difficult it is to support this? 

This seems like a good quality of life improvement for folks debugging tune trials. It's very common use case that tune trials have distributed workers?

This also will interact with W&B much better because now folks can see their entire trial logs in the W&B log viewer. 

@xwjiang2010 , @richardliaw , what's the process of trying to get this work prioritized?

**Comment by xwjiang2010** [comment]
Actually, we were just talking about this today.
@alanwguo @ericl Is it fair to say that we should always have access to EFS for product? 
Basically,
product --> certain requirements but also get EFS, which can greatly simplify impl
non product --> the impl is more tricky but we can choose not to provide this capability

**Comment by xwjiang2010** [comment]
btw, let me know if this discussion should be moved to product github...

**Comment by nikitavemuri** [comment]
Sure, let's discuss any product features/implementation for this in https://github.com/anyscale/product/issues/13890
