### ISSUE TITLE
Support for environment variables in Cluster YAML

### ISSUE THREAD

**Issue by dolanp83** [ray-project/ray#29016]
Cluster is created from inside a script like so:
```
export MY_VAR=abcd
...
ray up -y my-cluster.yaml
```

Is it possible to use MY_VAR inside the cluster config? Specifically I need this passed through to a **setup_command**, e.g.:
```
setup_commands:  
    - python3 script.py --input $MY_VAR
 ```

I was unable to get it to work as shown and could not find any supporting documentation or examples showing it's possible. I came across runtime environments but it doesn't seem to apply to this, as far as I can tell.

**Comment by zhe-thoughts** [comment]
Hi @dolanp83 if you file this as a `bug` it will go through our triaging process. But thanks for reporting it!

**Comment by Stack-Attack** [comment]
Hello, this would be extremely helpful. For example, we are currently deploying multiple stages of our app by defining stage environment variables. Without the ability to inject them into the cluster YAML, we have to create a seperate YAML for each stage. This is a huge hastle, as it means any upstream ENV changes need to be manually fixed in each cluster YAML file.

Something like:
```
cluster_name: cluster_${STAGE}
...
```
