### ISSUE TITLE
[CI][release] long_running_horovod_tune_test failed 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29318]
### What happened + What you expected to happen

[Build failure ](https://buildkite.com/ray-project/release-tests-branch/builds/1108#0183cdac-c92f-4008-a0c2-3b31129b2ac0)

[Cluster](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_5FSsQny6bZQwDJJBRp5PB9cR?command-history-section=command_history)

```
----------------------------------+
2022-10-12 18:03:13,558 ERROR tune.py:773 -- Trials did not complete: [HorovodTrainer_566a7_00000, HorovodTrainer_566a7_00001, HorovodTrainer_566a7_00002, HorovodTrainer_566a7_00003, HorovodTrainer_566a7_00004, HorovodTrainer_566a7_00005, HorovodTrainer_566a7_00006, HorovodTrainer_566a7_00007]
2022-10-12 18:03:13,558 INFO tune.py:778 -- Total run time: 19102.05 seconds (19101.48 seconds for the tuning loop).

Traceback (most recent call last):
  File "horovod/workloads/horovod_tune_test.py", line 177, in <module>
    assert not result.error
AssertionError


```

### Versions / Dependencies

release branch

### Reproduction script

NA

**Comment by jiaodong** [comment]
I think this failure should not be release blocking, mostly test flakiness given it's long running.

Our latest known good test from CI had 4 errored trial with same cuda error thrown from some trials, but it appeared for both successful and failed end state runs.

In both release tests, the main trial kept training with expected progress and ended up in TERMINATED state. 


The flaky error `RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED` is separate issue that I'm looking at as P1, but as far as i can tell, this error message is there at least since a passed release test on 2022-07-24

**Comment by rickyyx** [comment]
Thanks for the investigation JIao - will remove release blocker for now. cc @matthewdeng

**Comment by krfricke** [comment]
I actually think this might be release blocking after all.

The test does not introduce any deliberate failures. We see failures because bad performing trials try to exploit well performing trials, and this fails after some point. The reason why one trial survives is because after all the other trials failed, it will be the last remaining trial and not try to exploit anything else.

The workload is clearly not running as expected, so we should accordingly decide again if we require this workload to pass for the release or not.

IMO it is specific enough that we can make it not release blocking - PBT + Horovod then just isn't guaranteed to work (regular horovod GPU training (no PBT) is likely not affected as we don't start/stop trials, though we don't have confirmation for that). 

cc @matthewdeng @richard4912 @rickyyx @c21

**Comment by matthewdeng** [comment]
Do we know if this functionality ever worked in the past? Seems like fixing PBT uncovered another issue?

**Comment by rickyyx** [comment]
Declaured non release blocking

**Comment by xwjiang2010** [comment]
non release blocker.
There are multiple things not going quite right with this particular test. The PR above is intended to fix this test and bring down its cost. Pending review right now. Cost wise, we are down from $60 to $10 per run.

Also exposed through debugging this test is that Torch Dataloader with multiprocessing (`num_workers`) may not (get a chance to) clean up the processes it started because Ray Core just kills actors forcefully when GC kicks in. As a result, GPU memory leaks. This is NOT a regression.

For the next step, ML team should work with Core team to making sure that Ray AIR trainer can work nicely with Torch Dataloader if it uses multiple processing. cc @rkooo567 

Started [this](https://github.com/ray-project/ray/issues/29563) to track.

**Comment by xwjiang2010** [comment]
PR landed. Closing this bug. Torch Dataloader thing is tracked separately.
