### ISSUE TITLE
[CI][release] long_running_distributed_pytorch_pbt_failure failed 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29399]
### What happened + What you expected to happen

[Build](https://buildkite.com/ray-project/release-tests-branch/builds/1123#0183d941-4842-4fa2-b086-2170ea0bc3ae)

[Cluster](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_WAvvmyJq5QZ3VXMfBHmtmksi?command-history-section=command_history)

### Versions / Dependencies

release 2.1

### Reproduction script

NA

**Comment by matthewdeng** [comment]
@krfricke @justinvyu can you take a look?

Not sure why Tune was not able to recover from this...
```
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
        class_name: with_parameters.<locals>._Inner
        actor_id: 8e37b2899fd2793a4c875a2b02000000
        pid: 5946
        namespace: bd144428-6637-484e-a82a-8fef0008a016
        ip: 172.31.83.120
The actor is dead because its node has died. Node Id: e8ccd37ef072fbee31697d8f0c4fdf3837a0d9557f836d3b56057722
```

**Comment by justinvyu** [comment]
Kai walked me through this test failure. This test will randomly kill nodes via `FailureInjectorCallback`, and the test failure happens when:
1. A trial result comes in and is processed
2. The node this trial is running on is requested to be killed by the failure injector
3. The driver's syncer callback runs on the `on_trial_result` event
4. The node dies
5. The driver is in the middle of syncing, trying to access the node ip, which errors

Fix: gracefully handle this race condition by catching the error thrown by the sync operation on a dead node, and log a warning to the user.

**Comment by rickyyx** [comment]
Cherry pick?
