### ISSUE TITLE
[AIR] Nightly test regression of air_benchmark_tune_torch_mnist

### ISSUE THREAD

**Issue by c21** [ray-project/ray#29682]
### What happened + What you expected to happen

Last successful run (10/19): https://buildkite.com/ray-project/release-tests-branch/builds/1138
First failed run (10/20): https://buildkite.com/ray-project/release-tests-branch/builds/1143

### Versions / Dependencies

master

### Reproduction script

as above

### Issue Severity

High: It blocks me from completing my task.

**Comment by bveeramani** [comment]
Looks like this is just noise. See figure below.

This test failed on 10/20 because Tune ran slower than expected. However, the test passed on on 10/21 and 10/24. 

In any case, I've opened a PR to prevent this kind of thing in the future: https://github.com/ray-project/ray/pull/29688

```
Full results: {'train_times': [222.085255114, 223.6640359820001, 227.86511183400012], 'train_mean': 224.53813431000006, 'train_sd': 2.4392241719027363, 'tune_times': [279.9481823609999, 275.50665053800003, 281.4376604869999], 'tune_mean': 278.9641644619999, 'tune_sd': 2.5193171261207654}
```

```
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "workloads/tune_torch_benchmark.py", line 152, in main
    ), f"{mean_tune_time:.2f} > {threshold:.2f} = {factor:.1f} * {mean_train_time:.2f}"
AssertionError: 278.96 > 269.45 = 1.2 * 224.54
```

![image](https://user-images.githubusercontent.com/26107013/197907316-a3d9e229-6588-4f50-a58f-ab97fb849049.png)
