### ISSUE TITLE
[Datasets] Promote PandasRow and ArrowRow as PublicAPI

### ISSUE THREAD

**Issue by c21** [ray-project/ray#29761]
### What happened + What you expected to happen

Getting Ray user's feedback, when they want to iterate on rows in dataset, they found the actual row format is either `PandasRow` or `ArrowRow`. Currently these are not public API and there's no good documentation/tutorial coverage for them. Only found https://docs.ray.io/en/latest/data/consuming-datasets.html and https://docs.ray.io/en/latest/data/api/data_representations.html#ray.data.row.TableRow . But the documentation really does not tell how to access and process each column in each row.

We should promote `PandasRow` and `ArrowRow` as PublicAPI, and add more documentation for them, e.g. inside https://docs.ray.io/en/latest/data/consuming-datasets.html#consuming-datasets .

### Versions / Dependencies

master

### Reproduction script

as above

### Issue Severity

High: It blocks me from completing my task.

**Comment by clarkzinzow** [comment]
We should also update the API docs for the row-based APIs (`ds.map()`, `ds.iter_rows()`, etc.) to strongly indicate that these row abstractions will be returned, and that they can be worked with as if they are Python dicts.

**Comment by c21** [comment]
> We should also update the API docs for the row-based APIs (ds.map(), ds.iter_rows(), etc.) to strongly indicate that these row abstractions will be returned, and that they can be worked with as if they are Python dicts.

+1.

**Comment by bveeramani** [comment]
Maybe dumb question, but any reason we can't abstract away `PandasRow` and `ArrowRow`? Like, aren't pandas and Arrow implementation details that don't have anything to do with the user's problem?

**Comment by clarkzinzow** [comment]
@bveeramani As for why these row abstractions are needed: they provide a zero-copy dictionary interface for a single row/record, where no data is copied from the underlying table until a concrete column value is accessed (at which point only that value, which is often a scalar, is copied), or they want to mutate the row. This is a big, big performance win for common per-row workloads, where mutating the row is not needed.

For these Pandas/Arrow-specific row abstractions, the user doesn't actually have to worry about the fact that it's a `PandasRow` or `ArrowRow`, they only need to worry about the `TableRow` interface (which is primarily a dictionary interface + an API to eagerly create a full row copy).

@c21 Actually, could we **only** expose the `TableRow` interface via e.g. using composition rather than inheritance, so we can hide the Arrow/Pandas detail?

**Comment by bveeramani** [comment]
@clarkzinzow gotcha! Thanks for the context.

**Comment by hora-anyscale** [comment]
Per Triage Sync: Should this be 2.2 or 2.3?

**Comment by clarkzinzow** [comment]
@hora-anyscale 2.3, I believe.

**Comment by ericl** [comment]
This is superceded by strict mode, where we are hiding these APIs in favor of Dict[str, Any].
