### ISSUE TITLE
For Both ES and ARS, a custom-model cannot be defined in the same way (as for the other agents e.g. A3C).

### ISSUE THREAD

**Issue by rghelichi** [ray-project/ray#2984]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

**Comment by ericl** [comment]
Hey @rghelichi I think https://github.com/ray-project/ray/pull/2974 should fix this, can you try it out?

**Comment by rghelichi** [comment]
Hi @ericl, I saw the commits but I can't find the branch/pull request that solved it. 

I think apart from those commits:
in es.py
line 29: "DEFAULT_CONFIG = {" , should be read with "with_common_config("
and
in ars.py
there is a check for the shape of the input which should be removed.

**Comment by ericl** [comment]
@rghelichi it's these changes that pass in "model_options" that fixes the problem, for example: https://github.com/ray-project/ray/pull/2974/files#diff-470490be1162955b1e0365174cc5ca17R183

Basically, the problem was that get_model() had the model options (which contains the custom model config) as an optional parameter. So for ARS and ES, we forgot to pass them through correctly and so it would always use the default model.

re: check on the shape, could you comment in the PR where that is?

**Comment by rghelichi** [comment]
@ericl  thank you for the message. 
For the changes I assume I will wait till the merge gets approved then I try the master. 

for shape check, I am referring to ARS:
      ars/policies.py

65        if len(preprocessor.shape) > 1:
               raise UnsupportedSpaceException(
                  "Observation space {} is not supported with ARS.".format(
                      preprocessor.shape))

**Comment by ericl** [comment]
Thanks! I don't remember why that check was there...

**Comment by ericl** [comment]
This should be fixed in master.

**Comment by rghelichi** [comment]
Thank you @ericl . I assume it is version 0.5.3 right?

**Comment by ericl** [comment]
They're in the master builds (you can find the latest wheels here: https://ray.readthedocs.io/en/latest/installation.html) -- though I think you need to replace "0.5.2" with "0.5.3" in the URLs.
