### ISSUE TITLE
[core] ray-data-bulk-ingest-file-size-benchmark throughput regression 

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#29912]
### What happened + What you expected to happen

cluster: https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_cvv1qdwjUXpkGzhX486LRKEe

throughput regression that is not expected, only num img for per file was modified recently

### Versions / Dependencies

master

### Reproduction script

https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_cvv1qdwjUXpkGzhX486LRKEe

**Comment by clarng** [comment]
@cadedaniel i believe you said you will look into this

**Comment by cadedaniel** [comment]
ray-data-bulk-ingest-file-size-benchmark is failing because of the new benchmark which explicitly tests OOM performance implicitly increased the size of the dataset such that the dataset no longer fits into the object store w/o spilling. I think the fix here is to separate out the OOM test from the file-size-benchmark test so that each test can focus on their unique goal. I’ll work on that this week.

**Comment by cadedaniel** [comment]
Closing for now since the performance is at least consistent. We can separate them out if OOM tests are flaky.
