### ISSUE TITLE
[air/tune] Tracker: Ray AIR/Tune checkpointing for Ray 2.2

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#30068]
This is an umbrella issue to track features we hope to land for Ray 2.2

- [x] #30069
- [ ] #30070
- [x] #30073
- [x] #30074
- [x] https://github.com/ray-project/ray/issues/28528

Postponed:
- [ ] #30071
- [ ] #30072

**Comment by h-vetinari** [comment]
This issue is milestoned for an already-released version -- either the milestone should be updated or removed

(I'm using this as a stand-in to comment, as there are about 30 issues/PRs either [milestoned](https://github.com/ray-project/ray/milestone/100) for 2.2 or labeled "[Ray 2.2](https://github.com/ray-project/ray/issues?q=is%3Aopen+is%3Aissue+label%3A%22Ray+2.2%22)".

**Comment by krfricke** [comment]
We can close this issue as the remaining tasks are tracked in separate PRDs
