### ISSUE TITLE
[Datasets] Index silently dropped when creating Dataset from DataFrame

### ISSUE THREAD

**Issue by bdewilde** [ray-project/ray#30261]
### What happened + What you expected to happen

When passing data back and forth between `pandas` and `ray`, I noticed that the latter was silently dropping the dataframe's index. Usually this isn't a big deal — just `.reset_index(drop=False)` to move the index into column(s) — but in some situations, the index is both necessary and necessarily separate from columns. I would prefer to have `ray` preserve the index, or at least emit a warning if it has to drop it.

For example, when fitting an ML model, you'll often have multiple features represented in columns, one (or more) columns for the label/target, and key identifier(s) for each example set as an index. The identifiers shouldn't be columns -- you don't want them going into the model -- but you do want to keep track of which predictions go with which examples. ray's `Trainer` class has functionality built in for splitting features from label (via the `label_column` arg), but nothing for identifier indexes.

I'm guessing this isn't actually a bug, I just couldn't find any documentation calling out this behavior. If so, please consider this a feature request! :)

### Versions / Dependencies

macOS == 12.4
Python == 3.9.13
ray == 2.1
pandas == 1.4.4

### Reproduction script

```python
import pandas as pd
import ray


# features: x1, x2; label: y; identifier: name
df = pd.DataFrame(
    data={"x1": [1,2,3,4,5], "x2": [6,7,8,9,10], "y": [1, 0, 0, 1, 0], "name": ["a", "b", "c", "d", "e"]},
).set_index("name")
dataset = ray.data.from_pandas(df)

# this fails, because the index has been dropped
assert dataset.to_pandas().equals(df)
# this passes tho
assert dataset.to_pandas().equals(df.reset_index(drop=True))
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by chestergan** [comment]
This also occurs when map_batches is applied, with any pandas UDF, with batch_format=‘pandas’, to a ray dataset that is read from a parquet file with Pandas indexes.

Reproduction script

import pandas as pd
import ray

ray.init()

# features: x1, x2; label: y; identifier: name
df = pd.DataFrame(
    data={"x1": [1,2,3,4,5], "x2": [6,7,8,9,10], "y": [1, 0, 0, 1, 0], "name": ["a", "b", "c", "d", "e"]},
).set_index("name")
df.to_parquet(‘test.parquet’)
ds = ray.data.read_parquet(‘test.parquet’, parallelism=1).fully_executed()

# fails because the index is dropped
assert set(ds.schema().names) == set(ds.map_batches(lambda x: x, batch_format=‘pandas’).schema().names)

**Comment by bdewilde** [comment]
@anyscalesam Can you share details on how/where this was completed?
