### ISSUE TITLE
[ml-release] lightgbm_tune_16X4 is failing

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30295]
https://buildkite.com/ray-project/release-tests-branch/builds/1196#01847834-c29d-493e-b456-042b270b5fba

command history is empty

SDK command returns error code 55555.

Asking in the product channel what this means.

https://anyscaleteam.slack.com/archives/CKD613X8S/p1668531183954269

**Comment by sofianhnaide** [comment]
This API has now a depreciation warning and we should move off it since the GCP will no longer be able to issue commands on the dataplane directly.

You can still use the webterminal API to issue a direction command on the webterminal is you want, here is a snippet that does that: https://github.com/anyscale/product/blob/master/frontend/cli/anyscale/commands/workspace_commands.py#L367

**Comment by shawnpanda** [comment]
For OSS tests, should they consider Anyscale Jobs instead of relying on session command?

**Comment by krfricke** [comment]
Migrated to jobs for file transfer which should solve the issue (#30946)
