### ISSUE TITLE
[core] Test cancel is flakey

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#30453]
Test cancel is flakey due to https://github.com/ray-project/ray/commit/3fbd9a66389fd720cb38da252498b7d485beeedc

Need to fix the issues before 2.2 release.

**Comment by clarkzinzow** [comment]
For context: this is because importing many libraries (e.g. Arrow, Pandas, Torch) is not reentrant, and task cancellation is occasionally interrupting the Arrow import triggered via [this deserialization add-on](https://github.com/ray-project/ray/blob/b7072ea244bae72344e9dca9ebeddf9426090673/python/ray/util/serialization_addons.py#L66), which we are then trying to import again when serializing the error. See here for an example failure: https://buildkite.com/ray-project/oss-ci-build-branch/builds/1115#018485e1-df32-480f-9c36-cc898341f0a2

We can prevent this import reentrancy from happening for the task cancellation case by deferring interrupts until after task argument deserialization finishes, so we can be sure that the serialization-related imports have finished before processing the interrupt.

**Comment by scv119** [comment]
After we remerge the lazy initialization PR, does this only impact dataset users?

**Comment by scv119** [comment]
@clarkzinzow is this still a release blocker :/ ?

**Comment by xwjiang2010** [comment]
@clarkzinzow this can be closed with https://github.com/ray-project/ray/commit/b3bcd3a5ba6f973a93e10bcb8c9122b1453eb27a?

**Comment by clarkzinzow** [comment]
@xwjiang2010 That PR was unrelated to this, this is for the core `test_cancel` test. However, I think that this can be closed since https://github.com/ray-project/ray/pull/30558 mitigates this particular flaky test.
