### ISSUE TITLE
[AIR] [Datasets] dataset returned by get_dataset_shard does not have schema 

### ISSUE THREAD

**Issue by kira-lin** [ray-project/ray#30465]
### What happened + What you expected to happen

I'm using TensorflowTrainer. When I call to_tf on the dataset returned by `get_dataset_shard("evaluate")`, it prints the following error message:

> Traceback (most recent call last):
>   File "reproduce_dataset_bug.py", line 26, in <module>
>     trainer.fit()
>   File "/home/lzhi/.pyenv/versions/raydp/lib/python3.8/site-packages/ray/train/base_trainer.py", line 360, in fit
>     raise result.error
> ray.exceptions.RayTaskError(AttributeError): ray::_Inner.train() (pid=47094, ip=10.0.2.139, repr=TensorflowTrainer)
>   File "/home/lzhi/.pyenv/versions/raydp/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 355, in train
>     raise skipped from exception_cause(skipped)
>   File "/home/lzhi/.pyenv/versions/raydp/lib/python3.8/site-packages/ray/train/_internal/utils.py", line 54, in check_for_failure
>     ray.get(object_ref)
> ray.exceptions.RayTaskError(AttributeError): ray::RayTrainWorker._RayTrainWorker__execute() (pid=47183, ip=10.0.2.139, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x7fdb31c15d90>)
>   File "/home/lzhi/.pyenv/versions/raydp/lib/python3.8/site-packages/ray/train/_internal/worker_group.py", line 31, in __execute
>     raise skipped from exception_cause(skipped)
>   File "/home/lzhi/.pyenv/versions/raydp/lib/python3.8/site-packages/ray/train/_internal/utils.py", line 129, in discard_return_wrapper
>     train_func(*args, **kwargs)
>   File "reproduce_dataset_bug.py", line 13, in train_func
>     evaluate_tf_ds = evaluate_ds.to_tf(feature_columns="x", label_columns="y")
>   File "/home/lzhi/.pyenv/versions/raydp/lib/python3.8/site-packages/ray/data/dataset.py", line 2870, in to_tf
>     valid_columns = schema.names
> AttributeError: 'NoneType' object has no attribute 'names'

But it works with `get_dataset_shard("train")`

### Versions / Dependencies

I'm using ray 2.1.0, python 3.8.8, tensorflow-cpu 2.10.0

### Reproduction script

```python
import ray
from ray.air import session
from ray.air.config import ScalingConfig
from ray.train.tensorflow.tensorflow_trainer import TensorflowTrainer
import pyarrow

def train_func(config):
  train_ds = session.get_dataset_shard("train")
  evaluate_ds = session.get_dataset_shard("evaluate")
  # this works
  train_tf_ds = train_ds.to_tf(feature_columns="x", label_columns="y")
  # this does not work
  evaluate_tf_ds = evaluate_ds.to_tf(feature_columns="x", label_columns="y")

if __name__ == "__main__":
  ray.init()
  # generate dataset
  tb = pyarrow.Table.from_pydict({"x": list(range(1000)), "y": list(range(1000, 2000))})
  ds = ray.data.from_arrow(tb)
  # split to two
  train_ds, evaluate_ds = ds.split_proportionately([0.7])
  print(train_ds.schema())
  print(evaluate_ds.schema())
  scaling_config = ScalingConfig(num_workers=1)
  trainer = TensorflowTrainer(train_func, scaling_config=scaling_config, datasets={"train": train_ds, "evaluate": evaluate_ds})
  trainer.fit()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by matthewdeng** [comment]
@jianoaix can you take a look here? 

At a glance it appears related to #29635, though I was able to reproduce the issue locally with a nightly wheel (05451bbee062e50163c0501ce43e76a7ed4ee2db).

**Comment by jianoaix** [comment]
It turns out this is not the same as https://github.com/ray-project/ray/pull/29635, and is an expected behavior (per how it works currently).

Looking at the execution plan at the point of failure:
```
(RayTrainWorker pid=3528466) eval ds plan: ExecutionPlan(dataset_uuid=e3a7a10256f24777ab40dc5f5ef6a48b, run_by_consumer=False, in_blocks=None, stages_before_snapshot=[], stages_after_snapshot=[RandomizeBlocksStage("randomize_block_order")], snapshot_blocks=<ray.data._internal.block_list.BlockList object at 0x7fa0b09c08b0>)
(RayTrainWorker pid=3528466) train ds plan: ExecutionPlan(dataset_uuid=d3af43f2c1da40e08b45e718cdd0dafa, run_by_consumer=False, in_blocks=None, stages_before_snapshot=[], stages_after_snapshot=[], snapshot_blocks=<ray.data._internal.block_list.BlockList object at 0x7fa0b09c0490>)
```
The trainer internally added an extra operation "randomize_block_order" to the eval dataset (but no training dataset). This extra stage means the eval dataset isn't finished execution yet, so the schema is considered unknown unless you explicitly ask to fetch it (e.g. `evaluate_ds.schema(fetch_if_missing=True)`)

**Comment by kira-lin** [comment]
I see. How should I fix it? schema is called in to_tf, I can't change it. What's the suggested way to consume "evaluate" dataset?

**Comment by jianoaix** [comment]
@matthewdeng It looks we should not add a "randomize_block_order" processing step without being requested from API calls by user, but it may be intended.

**Comment by matthewdeng** [comment]
Hmm @jianoaix `randomize_block_order` is set to True by default including the `"train"` dataset. My guess is that the difference is because the `"train"` dataset is split (even though it's a single worker) which triggers execution?

Taking a step back, I think the question is how to make `randomize_block_order` compatible with `schema`/`to_tf`. I did a quick scan and saw that this discrepancy was introduced in https://github.com/ray-project/ray/pull/26090.

A few options come to mind:
1. Update `schema` to work even if `randomize_block_order` is called. 
    - Intuitively, I don't think `randomize_block_order` should change the Dataset's schema? 
2. Update `to_tf` to always call `schema(fetch_if_missing=True)`.

What do you think?

@kira-lin as a short-term workaround, you can fully execute the Dataset shard so that the schema is available.

```diff
- evaluate_ds = session.get_dataset_shard("evaluate")
+ evaluate_ds = session.get_dataset_shard("evaluate").fully_executed()
