### ISSUE TITLE
[Core] Separate runtime env agent from dashboard

### ISSUE THREAD

**Issue by MisterLin1995** [ray-project/ray#30528]
## Description

Currently, raylet fate-shares with dashboard-agent since runtime env agent (called by raylet to manage job / actor runtime environment) is integrated with dashboard agent. Should the dashboard agent fail, the raylet will fail and all tasks on that node will fail which is too expensive to accept. Given this concern, it's necessary to isolate raylet from dashboard agent failure by moving runtime env agent from dashboard agent to a separate process. To make the raylet even more robust, we should make raylet not fate-share with runtime env agent too since some jobs don't require a runtime env and they shouldn't fail because of runtime env agent.

### Step 1: Separate runtime env agent from dashboard agent.
We extract runtime env agent code from dashboard modules and make some adjustments so that it can be started as an individual process provide only runtime env service. At this stage, raylet switches from fate-sharing with dashboard-agent to fate-sharing with this new runtime env process. But, it's a lot easier for us to add comprehensive test cases to make the runtime env agent much more robust. The process will be started by raylet so some initialize work is needed in raylet. 

### Step 2: Enable raylet to auto-restart dashboard agent. 
After Step 1, dashboard agent has become stateless and we can enable raylet to auto-restart crashed dashboard. This logic was implemented before and we just need to find back our code.

### Step 3: Provide failover to runtime env agent.
Finally, we can add failover ability to runtime env agent. Since the states kept in runtime env agent are the reference counts of URIs which can be reconstructed from raylet's workers and job info and the disk. We can pass workers' runtime env metadata to the runtime env agent when raylet restart it. 

#### States to recover
Following states need to be recovered when a runtime env agent is restarted:

- env_cache : Map
    - A map from serialized runtime env to CreatedEnvResult
    - Each CreatedEnvResult contains three fields:
        - success: bool -> This indicates whether the request results in a successful request. Since currently raylet doesn't store information about failed runtime env creation, we cannot recover failed results, so this field will always be True.
        - result: str -> serialized_runtime_env_context if success and error message otherwise. 
        - creation_time: int -> time cost in ms to create this runtime env
- reference_table: ReferenceTable
    - runtime_env_reference:  A map from serialized runtime env to reference count
    - uri_reference: A map from uri to reference count
- plugin_manager : PluginManager
     - a PluginManager has a map from plugin name to PluginSetupContext which contains a URICache
     - URICache contains the following fields:
         - used_uris: set -> A set of in use uri strings
         - unused_uris: set -> A set of not in use uri strings
         - total_size_bytes: int -> Total size of both used and unused URIs in the cache. 

#### Current source of truth
- Type defined in code
```proto
/// The runtime env information which is transferred between ray core processes.
message RuntimeEnvInfo {
  /// The serialized runtime env passed from the user.
  string serialized_runtime_env = 1;
  /// URIs used in this runtime env. These will be used for reference counting.
  RuntimeEnvUris uris = 2;
  /// The serialized runtime env config passed from the user.
  RuntimeEnvConfig runtime_env_config = 3;
}
```
- Raylet
     - registered workers
         - worker_pool.h -> states.worker_processes 
             - each WorkerProcessInfo contains a RuntimeEnvInfo field
     - eagerly-install jobs
         -  worker_pool.h -> all_jobs_
             - each job has a JobConfig which contains RuntimeEnvInfo
- Disk
    - For each plugin, there's a direcotry under the /tmp/ray/ray_session/runtime_resources named after the plugin name: e.g /tmp/ray/ray_session/runtime_resources/pip
    - Each uri will create one subdirectory (named ${uri}) in the plugin directory
 
##### Keep raylet simple and pure
Raylet don't keep extra information than its current design.
##### Don't scan the disk
Scan the whole directory is expensive, it might be a better idea to restore from a metadata file

#### Constructing steps
1. Let agent store URICache metadata for each uri created by each plugin
For each uri directory, create one file named uri.metadata in the metadata directory, which record the following fileds:
plugin size_in_bytes
When the uri is evicted from the cache(directory deleted), the corresponding file should be deleted as well.
2. Agent recovery protocol

    2.1 Procedure
Raylet start new agent -> Agent register to Raylet -> Raylet reply with in use runtime env info -> Agent recover states

    2.2 Message and Service definition:

        ```proto
        message RegisterRuntimeEnvAgentRequest {
          string runtime_env_agent_ip_address = 1;
          int64 runtime_env_agent_grpc_port = 2;
          int64 runtime_env_agent_id = 3;
        }
        
        message RuntimeEnvState {
          string serialized_runtime_env = 1;
          RuntimeEnvConfig runtime_env_config = 2;
          bytes job_id = 3;
           oneof identifier{
              string worker_pid = 4;
   		        string job_id = 5;
           }
        }
        
        message RegisterRuntimeEnvAgentReply {
          AgentRpcStatus status = 1;
          // RuntimeEnvResult list.
          // It's generated from worker pool state's registered workers and eager jobs
          repeated RuntimeEnvState = 2;
        }
        
        service AgentManagerService {
          // This rpc is called once by runtime env agent when it's started.
          rpc RegisterRuntimeEnvAgent(RegisterRuntimeEnvAgentRequest) returns (RegisterRuntimeEnvAgentReply);
        }
        ```

    2.3 Agent recovery steps

      2.3.1 Agent read metadata file to restore all uris on the disk, put all of them into URICache _unused_uris and set the _total_size_bytes

      2.3.2 Agent register process RuntimeEnvState list received from Raylet and recreate runtime env for each serialized_runtime_env, in this process, the following states are recovered
      - env_cache
          - success: always True
          - result: When a serialized_runtime_env first appear, re-run the _setup_runtime_env function to get the runtime_env_context and then serialize it 
          - creation_time: set as reconstruct time
      - reference_table
           - uri_reference: uri can be calculated from serialized_runtime_env, count can be re-added
           - _runtime_env_reference: simply count frequency of each serialized_runtime_env
      - plugin_manager
           - URICache use_uris and unsed_uris will be updated during execution of _setup_runtime_env
    
    2.4 Request handling during recovery
    Requests received during recovery will wait until the recovery finished.

#### In discussion details
- Form of URICache metadata
    - Give each plugin a metadata folder where all metadata files are stored. 
    - Each uri folder has same-name json file with the uri and last access time recorded.
- Failure model
    - When runtime env agent is down, raylet reject all tasks require a runtime env.

**Comment by SongGuyang** [comment]
In addition, we could consider to unify the way of maintaining subprocesses in raylet. Currently, there are two code paths: the worker pool subprocesses and the agent subprocess. 
But I think it is not easy to do it. We can unify them in future. Don't block this issue.

**Comment by rkooo567** [comment]
I don't think we need runtime env agent. I think this is exactly the same discussion @SongGuyang and we had before. What's important is 

1. We should move the runtime-env-related state tracking to raylet. 
2. After that, agent can be just simply restarted. And the agent can just do stateless work (e.g., downloading runtime env and etc.).

**Comment by rkooo567** [comment]
I am specifically saying we should go option 1 here https://github.com/ray-project/ray/issues/21695#issuecomment-1022873950.

**Comment by rkooo567** [comment]
I think it is very unlikely dashboard agent fails now (only practical case is OOM), and there's no reason this is less stable than any new agent processes.

**Comment by SongGuyang** [comment]
> I am specifically saying we should go option 1 here [#21695 (comment)](https://github.com/ray-project/ray/issues/21695#issuecomment-1022873950).

Our conclusion before is [option 3](https://github.com/ray-project/ray/issues/21695#issuecomment-1032161528) ?

**Comment by rkooo567** [comment]
Yes! And then there were 2 options at that time. Don't support restart (the current one) and supporting it (this proposal). This proposal is option 3 + file based recovery + splitting out runtime env agent from dashboard agent.

**Comment by iycheng** [comment]
Related https://github.com/ray-project/ray/issues/30834

**Comment by scv119** [comment]
> I think splitting out runtime env agent is worth the effort because in this design:
> 1. We can isolate future potential dashboard agent failures from the core's job submission path.
> 2. More importantly, although not related to the stability problem we are talking about, it should belong to or be closely coupled with raylet since its functions is only required by raylet. This makes it possible to build a ray cluster without dashboard.


I might miss some context but this might indicating keeping the state in raylet process a potential solution? I can imaging we add a new type of worker whose only role is to install/uninstall runtime env context, and the state and control logic lives in raylet process natively. (AgentManager, specifically); in this case we no longer need to recover the state since AgentManager and Raylet fate share?

**Comment by SongGuyang** [comment]
@scv119 Do you mean we should use the [option 3](https://docs.google.com/document/d/1WEKl7uK54-hVmKQmQtpKi9g87rLu0uOhj51Hq5GmanA/edit#heading=h.mm0rg9nwusl7) ?

**Comment by scv119** [comment]
Synced with Yi


 the main reason we found a separate agent service is useful:
-  there might concurrent runtime env agent installation request, where track their state together in a separate service makes certain optimization, such like ratelimit, simipler
- similarly, for periodically garbage collection it might be easier to have a daemon process doing the job.

some concern worth addressing.

- there is a management cost of running a separate service, but it can be mitigated by managing it using worker_pool under raylet.
- since the state are decoupled, there might be a case where a worker is still using a runtime-env, but the agent mistankenly delete it due to data inconsistency.
- failure model: we need to make sure agent's failure, doesn't affect ongoing work.

**Comment by SongGuyang** [comment]
@scv119 Thanks for the reply above.

> there is a management cost of running a separate service, but it can be mitigated by managing it using worker_pool under raylet.

Agree that we should try to reuse the logic of subprocess management of worker pool. But I think it is not easy to be reused now because:

- The worker process executable is default_worker.py but in our case it should be runtime_env_agent.py
- We need a special process registration RPC from runtime env agent raylet, but the current worker registration is fixed.

I think we can redesign the worker pool and make it easy to support runtime env agent and dashboard agent. But we need to clear the priorities:

option 1: 
- Step 1: Build the runtime env agent process by the same way of current dashboard agent. 
- Step 2: Support failover of runtime env agent and decouple the fates of runtime env agent, dashboard agent and raylet. (Biggest issue)
- Step 3: Do a refactor of worker pool and reuse it in the agent processes management.

option 2: 
- Step 1: Do a refactor of worker pool.
- Step 2: Build the runtime env agent process by worker pool.
- Step 3: Support failover of runtime env agent and decouple the fates of runtime env agent, dashboard agent and raylet. (Biggest issue)

I think the refactor and reusing of worker pool will spend more time. But if we are not hurry to address the biggest issue, we can take the option 2.

**Comment by SongGuyang** [comment]
> since the state are decoupled, there might be a case where a worker is still using a runtime-env, but the agent mistankenly delete it due to data inconsistency.

@scv119 We should avoid this anyway. But I think we don't have this issue in current design.

**Comment by SongGuyang** [comment]
> failure model: we need to make sure agent's failure doesn't interrupt excuting workers/raylet.

@scv119 Sure, we should guarantee this.

**Comment by SongGuyang** [comment]
As the sync with @iycheng offline, we will follow the steps of [option 1](https://github.com/ray-project/ray/issues/30528#issuecomment-1384814463).

**Comment by iycheng** [comment]
Some justifications for the recommendations:

1. process management is important and we'd like to do this first. But given the on-going work about worker pre-start, this is more complicated than before and we are not quite sure about the requirement here:
  a. what's the life cycle of a process?
  b. how is it communicated with raylet for initialization?
  c. how is the health check working?
Given the unknown here, we suggest decouple the work with this one.
2. This issue is trying to fix a design bug, and it can prevent future unknown. The current design failed in practical, when I was building Serve HA and also failed within Ant internally. All these trigger the failure because they are new workloads. There are always new workloads everyday and it's important to have an architecture which remove unnecessary dependence. So this is important.
3. The code to maintain the process is manageable and it's simple: start process, send an RPC for initialization and do health check periodically (we can reuse GCS health check code for this one. Some minor changes might be needed, I can help with this cc @SongGuyang ) and restart if needed. We probably can have a simple framework to cover this (make dashboard agent and runtime env agent using this one). And later when worker pool's requirement is clear, we can migrate to that. cc @rkooo567 @SongGuyang @MisterLin1995
