### ISSUE TITLE
[ci][core] dashboard:modules/job/tests/test_* are failing/timing out

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30550]
see go/flaky

**Comment by xwjiang2010** [comment]
copying from Sang from OSS channel:

For job tests, I think we should cherry pick the flaky test fix for these 2 tests since we changed the job submission mechanism from ray 2.2

**Comment by xwjiang2010** [comment]
@architkulkarni for priority assessment

**Comment by rkooo567** [comment]
@architkulkarni Let me take a look at the test and see if I can help fixing this.

**Comment by xwjiang2010** [comment]
In addition to `test_job_submission` and `test_job_agent` identified on master branch right before branch cut. On release branch, there are failures:

`test_job_agent`, `test_http_job_server`, `test_cli_integration`

See
https://buildkite.com/ray-project/oss-ci-build-branch/builds/1231#01849f93-1b50-463b-9ad3-a11debd9eaf2

**Comment by scv119** [comment]
wait for @architkulkarni to take a look next week.

**Comment by architkulkarni** [comment]
`test_job_submission` and `test_job_agent` are the tests that are most flaky. (All other job tests are 0% red flaky and < ~10% yellow flaky on master)

For both, it's a test issue and not an issue with the feature, so it's not a release blocker.  I'll reduce the priority to P1.

- For `test_job_submission`, the root cause is that we occasionally get `2022-11-28 15:49:27,995 ERROR http_server_agent.py:68 -- Agent port #52365 already in use. Failed to start agent. Ensure port #52365 is available, and then try again.`. I will try to fix this by specifying an unused port number in the test fixture.

- For `test_job_agent` it's an issue where the previous dashboard agent is not killed immediately at the end of each test, being fixed here: https://github.com/ray-project/ray/pull/30683

**Comment by architkulkarni** [comment]
As for `test_http_job_server` and `test_cli_integration`, they seem to be passing on the release branch: https://buildkite.com/ray-project/oss-ci-build-branch/builds/1285#0184b9e8-e7ab-477a-87a1-ecb8311ca1a7 
They aren't flaky on master.

**Comment by xwjiang2010** [comment]
`test_http_job_server` and  `test_job_agent` are failing consistently for the last 3 builds on release branch head.

https://buildkite.com/ray-project/oss-ci-build-branch/builds/1349
https://buildkite.com/ray-project/oss-ci-build-branch/builds/1348
https://buildkite.com/ray-project/oss-ci-build-branch/builds/1346

Can we take another look and see if they are real issues?

**Comment by xwjiang2010** [comment]
Adding back release blocker for tracking. Feel free to drop them if they are not.

**Comment by xwjiang2010** [comment]
Showing up in both "Ray Core Unit Test" and "Dashboard Test", consistently.

**Comment by architkulkarni** [comment]
The `test_http_job_server` and `test_job_agent` failures are reproducible locally.  It might be related to this error message I see:

```
(raylet)   File "/Users/archit/ray/python/ray/autoscaler/_private/autoscaler.py", line 16, in <module>
(raylet)     from six.moves import queue
(raylet) ModuleNotFoundError: No module named 'six'
```

Looking into this.

**Comment by xwjiang2010** [comment]
Verified on release branch ci.
