### ISSUE TITLE
[Test/Core] test_state_api OSX became flaky after log refactoring 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#30586]
### What happened + What you expected to happen

<img width="525" alt="Screen Shot 2022-11-22 at 8 16 03 AM" src="https://user-images.githubusercontent.com/18510752/203365516-76fdb212-7384-45dc-b113-a0971e0c6a3a.png">

### Versions / Dependencies

n/a

### Reproduction script

n/a

**Comment by rickyyx** [comment]
Looks unrelated to the change though? The test failed with thread pool waiting for idle threads, which also shows up in many of the timeout tests that are grey. 

![image](https://user-images.githubusercontent.com/11676094/203381892-8d003fe6-463c-452a-aac3-b990636647e6.png)


Likely due to resource constrain in the mac pool.

**Comment by rickyyx** [comment]
I don't think this should be a release blocker also. Not sure how to get more signals with the mac pool being overloaded now.

**Comment by rkooo567** [comment]
Seems like the grpcio issue from 1.51 that's yanked. Fixed in the master
