### ISSUE TITLE
[xray] Creating many tasks on remote raylet is really slow.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#3088]
```python
import ray

ray.worker._init(start_ray_local=True, num_local_schedulers=2, num_gpus=[0, 1])

@ray.remote
def f():
    return 1

@ray.remote(num_gpus=1)
def g():
    return 1

%time x = ray.get([f.remote() for _ in range(10000)])  # 1.5s
%time x = ray.get([g.remote() for _ in range(10000)])  # 31s (also reconstructs a bunch of stuff)
```

This finishes, but takes way too long and seems to reconstruct a bunch of stuff.

cc @romilbhardwaj

**Comment by atumanov** [comment]
unless I'm missing something, this is not a meaningful comparison, because `f()` is executing in parallel with a parallelism factor equal to 2*num_cpus in the system (16x in my case):
```
In [1]: import ray
In [2]: ray.worker._init(start_ray_local=True, num_local_schedulers=2, num_gpus=[0, 1])
In [3]: ray.global_state.available_resources()
Out[3]: {'CPU': 16.0, 'GPU': 1.0}
```
while `g()` is executing one task at a time (1x). So, on my machine the difference in how many `f()` tasks and how many `g()` tasks are executed in parallel is 16x... Chances are, same on your laptop. If we divide 31/16, we get 1.9s for remote `g()` execution.

**Comment by robertnishihara** [comment]
Ah good point, I set up the test incorrectly. I'll give that a try.

**Comment by stephanie-wang** [comment]
Hmm, what's with the reconstruction though? That seems like it may be a result of spilling over tasks too often, although not really sure.

**Comment by robertnishihara** [comment]
I agree the reconstruction shouldn't be happening.
