### ISSUE TITLE
Ray[core | dashboard]: Multiple issues when upgrading from 1.13 to 2.1||2.0

### ISSUE THREAD

**Issue by raoul-khour-ts** [ray-project/ray#30995]
### What happened + What you expected to happen

I am trying to upgrade from ray 1.13 to 2.1 and running into a number of issues.
I work at a finance company so we have some strick security and firewalls + an inhouse linux like OS. 

If I use 2.1:
`python3 -c "import ray; ray.init(include_dashboard=False)"` hangs indefinably
ray start --head --block fails due to some agent failing with an exitcode -6

If I use nightly (decided to try this once reading https://github.com/ray-project/ray/issues/30214) I get further.
now:
`python3 -c -i "import ray; ray.init(include_dashboard=False)"` 
gets 
2022-12-09 18:04:45,886 INFO head.py:232 -- Starting dashboard metrics server on port 44227
2022-12-09 18:05:01,508 INFO worker.py:1545 -- Started a local Ray instance
ray.available_resources()
yeilds: a good looking set of resources
and I can actually run some quick jobs...
however about 15 seconds in I get:
The raylet exited immediately because the Ray agent failed. The raylet fate shares with the agent. This can happen because the Ray agent was unexpectedly killed or failed. See `dashboard_agent.log` for the root cause.
now ray.available_resources() -> {}
dashboard_agent.log:
```
2022-12-09 18:05:09,963 INFO agent.py:105 -- Parent pid is 2915520
2022-12-09 18:05:09,964 INFO agent.py:131 -- Dashboard agent grpc address: 0.0.0.0:54354
```

1. I really don't want the dashboard or the dashboard metrics I know it won't work on my companies systems and I don't really need it. Why is include_dashboard=False still doing all this dashboard stuff...
2. why is the dashboard failing crashing everything else
3. what changed?

### Versions / Dependencies

using:
python3.9
ray nightly
proprietary Linux like OS
finance company firewalls and security (making external reproducibility hard)

### Reproduction script

ideally
`python3 -c -i "import ray; ray.init(include_dashboard=False)"` 
would not launch a dashboard or a dashboard metrics service.

if that were fixed I think things would run for me.

If not at least ability to recover from dashboard agent failing.

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
dashboard & dashboard_agent is doing more things than the dashboard work now. That's why it is still started (e.g., the agent is used to create runtime env). 

When you start ray with include_dashboard=False, all of the modules related to dashboard is disabled (so it is almost like an empty process). Also dashboard_agent is started all the time in 1.13 too iirc. My guess is there's some code changes added that doesn't play well with you guys internal security setup. We'd like to fix this asap.

For this issue, I feel like doing pair programming is the best way forward. Do you have some time to meet for 30m ~ 1h to debug this issue?

**Comment by rkooo567** [comment]
cc @raoul-khour-ts to follow up! (I believe we also did pair debugging before?)

**Comment by raoul-khour-ts** [comment]
Hey @rkooo567 yes so somewhat pair debugging would be great I’ll ping you on slack for faster communication.

**Comment by rkooo567** [comment]
Follow up: The main issue was the grpcio version. Looks like grpcio==1.33 didn't work well with ray 2.0/2.1.

 I will double check if I have the same problem in my local environment (it could be specific to @raoul-khour-ts's environment because they did something to their grpc). If it turns out 1.33 is not compatible to ray 2.0/2.1, we should bump the version and always have explicit check / warning when ray.init or ray start is called.

**Comment by rkooo567** [comment]
Couldn't reproduce from ubuntu + mac (not M1) using grpcio 1.33.1 + ray 2.2. If anyone sees random hanging or failure like this, please upgrade the grpcio version.
