### ISSUE TITLE
[Datasets] `Dataset` representations don't work out-of-the-box on notebooks

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#31225]
### What happened + What you expected to happen

**On Google Colab**:

At first, you get warning telling you to upgrade the `ipywidgets` version.

![image](https://user-images.githubusercontent.com/26107013/208568240-e59914bf-72b5-4dba-b5a1-dc6df63885ea.png)

If you do that and then restart the runtime you get a new problem:

> Support for third party widgets (widgets outside of the ipywidgets package) needs to be enabled separately. Support for these widgets will be loaded from a CDN external from Colab.

![image](https://user-images.githubusercontent.com/26107013/208568477-b4c3cdaa-4e8d-4f64-ba7c-11d821c45c98.png)

**On Anyscale**:

Instead of a readable output, you get HTML like `VBox(children=(HTML(value='<h2>Dataset</h2>'), Tab(children=(HTML(value='<div class="scrollableTable jp-Render…`:

![image](https://user-images.githubusercontent.com/26107013/208568563-41c9adfb-70aa-44ab-bd02-54db41c8cf3b.png)

### Versions / Dependencies

Ray: master

### Reproduction script

See above.

### Issue Severity

Low: It annoys or frustrates me.

**Comment by bveeramani** [comment]
@peytondmurray do you happen to know how to fix this?

**Comment by peytondmurray** [comment]
I'm happy to take a look at this, but I'm not exactly sure what the issue is. It could be a problem displaying ipywidgets in google colab - I'll do some testing and report back.

**Comment by bveeramani** [comment]
Okay, sweet. Thanks!

**Comment by peytondmurray** [comment]
So this works just fine in JupyterLab locally with ray @ 6b081e9e000f181cb05036c91e3369e58c2baba3.

```
$ jupyter --version
Selected Jupyter core packages...
IPython          : 8.7.0
ipykernel        : 6.19.2
ipywidgets       : 8.0.4
jupyter_client   : 7.4.8
jupyter_core     : 5.1.0
jupyter_server   : 2.0.1
jupyterlab       : 3.5.1
nbclient         : 0.7.2
nbconvert        : 7.2.6
nbformat         : 5.7.0
notebook         : 6.5.2
qtconsole        : not installed
traitlets        : 5.7.1
```

This must be something with colab. Will continue investigating.

**Comment by peytondmurray** [comment]
Hmm, it's possible ipywidgets>=8 is unsupported: https://github.com/googlecolab/colabtools/issues/3020#issuecomment-1223330253. Sadly we don't support `ipywidgets<8`, so for now it seems there is a conflict.

**Comment by peytondmurray** [comment]
Quick update on this: I'm going to try to find a way to detect whether we're running in google colab, and disable the notebook integration if that's the case. Will open a PR in a bit :mechanical_arm:

**Comment by bveeramani** [comment]
@peytondmurray does #32841 also fix the issue on Anyscale?

**Comment by peytondmurray** [comment]
@bveeramani I'm not sure - I wasn't aware that this was affecting Anyscale as well. Is there a way I can access an environment to test?

**Comment by amogkam** [comment]
I'm still seeing this issue on Anyscale even with `ipywidgets>=8`

`VBox(children=(HTML(value='<h2>Dataset</h2>'), Tab(children=(HTML(value='<div class="scrollableTable jp-Render…
`

**Comment by peytondmurray** [comment]
@amogkam @bveeramani So in the process of working on this, I think I came across a separate bug which I've made a PR for in #34339. One question about this issue though - did you restart the jupyter server after install `ipywidgets`? I know locally, at least, the fancy notebook repr won't show up after installing `ipywidgets>=8` unless you restart the jupyter server first. I don't know much about Anyscale, but could you please confirm this fixes the issue locally?

I'm thinking we at the very least should make a better error message for the user `ipywidgets>=8` is not installed, because at the moment the message is not at all clear enough.

At the same time, I'll investigate ways we can check if a repr is being correctly displayed. If there's a way to check this at runtime, we might be able to display a more informative error message rather than this `VBox....` junk.

**Comment by pcmoritz** [comment]
I've also been seeing this issue locally on my laptop with the latest Ray master and the `ipython` executable (in the shell).
