### ISSUE TITLE
[AIR] Dataset is not automatically split for the "train" dataset

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#31416]
### What happened + What you expected to happen

The [docs](https://docs.ray.io/en/latest/ray-air/check-ingest.html#splitting-auxiliary-datasets) seem to say that `split` defaults to True for the training dataset, but this doesn't appear to be the case.

### Versions / Dependencies

3.0dev

### Reproduction script

```
$ pytest -sv python/ray/air/tests/test_dataset_config.py::test_basic
```

Removing `split=True` from [this line](https://github.com/ray-project/ray/blob/master/python/ray/air/tests/test_dataset_config.py#L23) causes the test to fail.

### Issue Severity

Low: It annoys or frustrates me.

**Comment by clarkzinzow** [comment]
@stephanie-wang That guarantee given in the docs is for **users** of the `Trainer` classes that do not specify a `dataset_config` arg for the `Trainer`, and that "split train dataset by default" is enabled by the default `DataParallelTrainer` dataset config: https://github.com/ray-project/ray/blob/ee3abd402925273dae376691404a147323546b52/python/ray/train/data_parallel_trainer.py#L240

However, since you're subclassing `DataParallelTrainer` and are overriding that linked default dataset config, you're changing the default to `None`, which will come out to be `False`.

**Comment by clarkzinzow** [comment]
In other words, the docs are only indicating that the default dataset config in the `Trainer` classes that AIR defines split the training dataset by default, and you're overriding that user-facing default training dataset config in your `Trainer` subclass.

**Comment by stephanie-wang** [comment]
Ah got it, thanks for the explanation! I'll close for now.
