### ISSUE TITLE
[RLlib] Error with waterworld.v4  environment from Pettingzoo

### ISSUE THREAD

**Issue by george-skal** [ray-project/ray#31496]
### What happened + What you expected to happen

The waterworld.v3 environment is depreciated since in v4 there are bug fixes so when I try the parameter sharing example in PPO with v4 from here [https://github.com/ray-project/ray/blob/master/rllib/examples/multi_agent_parameter_sharing.py](https://github.com/ray-project/ray/blob/master/rllib/examples/multi_agent_parameter_sharing.py) I get the following error: 

> (RolloutWorker pid=36487) ValueError: `observation_space` not provided in PolicySpec for shared_policy and env does not have an observation space OR no spaces received from other workers' env(s) OR no `observation_space` specified in config!

I know that there are currently problems with pettingzoo and other issues noticed on ray.discuss, but I am working on a research progress with waterworld so I need the new version and I would appreciate any help.

Thanks

### Versions / Dependencies

Ray latest version (2.2.0), Pettingzoo 1.22.1, tensorflow 2.11.0 Python 3.8, Ubuntu 20.04

### Reproduction script
```

from ray import air, tune
from ray.tune.registry import register_env
from ray.rllib.env.wrappers.pettingzoo_env import PettingZooEnv
from pettingzoo.sisl import waterworld_v4


if __name__ == "__main__":
    # RDQN - Rainbow DQN
    # ADQN - Apex DQN

    register_env("waterworld", lambda _: PettingZooEnv(waterworld_v4.env()))

    tune.Tuner(
        "PPO",
        run_config=air.RunConfig(
            stop={"episodes_total": 60000},
            checkpoint_config=air.CheckpointConfig(
                checkpoint_frequency=10,
            ),
        ),
        param_space={
            # Enviroment specific.
            "env": "waterworld",
            # General
            "num_gpus": 0,
            "num_workers": 2,
            # Method specific.
            "multiagent": {
                # We only have one policy (calling it "shared").
                # Class, obs/act-spaces, and config will be derived
                # automatically.
                "policies": {"shared_policy"},
                # Always use "shared" policy.
                "policy_mapping_fn": (
                    lambda agent_id, episode, worker, **kwargs: "shared_policy"
                ),
            },
        },
    ).fit()

```
### Issue Severity

High: It blocks me from completing my task.

**Comment by sven1977** [comment]
Hey @george-skal , thanks for raising this issue. I think the problem is simply the incompatibility between newer pettingzoo envs (like waterworldv4) and the old gym API (which Ray RLlib 2.2 is still using). Our master branch has been upgraded to use the new gym APIs (replace gym with gymnasium). Could you try that? I just confirmed that your repro script is running fine on Ray's latest master with `pip install gymnasium` installed. You might also want to upgrade `pip install gym==0.26.2` in case you want to run Atari experiments. Otherwise, the `gym` package is no longer needed.
Documentation on the new gymnasium upgrade is currently in the pipeline ...

**Comment by george-skal** [comment]
Hello @sven1977, thanks for the answer. Yes it works with the nightlies releases!
