### ISSUE TITLE
[Core][nightly] long_running_many_actor_tasks and long_running_many_tasks_serialized_ids are failing due to metrics reporting issue

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#31547]
### What happened + What you expected to happen

Metrics reporting takes longer than expected and causes the test to timeout.

https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_us5nnssmnc9ws94kkp6a9jclbz

https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_jf3utm9futnugylhiliujq3wf5

https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_z54reexyaa99sy39frq4vx292h

### Versions / Dependencies

latest

### Reproduction script

n/a

### Issue Severity

High: It blocks me from completing my task.

**Comment by stephanie-wang** [comment]
@scv119 I can take this issue as it seems to be a simple fix (just skip metrics reporting for now). Will open another issue for the long_running_node_failures one.

**Comment by Yard1** [comment]
Hey, so I looked at the logs in https://buildkite.com/ray-project/release-tests-branch/builds/1287. Just to make sure we are all on the same page, here's what happens in regards to metrics collection in release tests:

1. The test script runs first and saves results to a json file
2. After the test script finishes/fails/times out, metrics collection script is ran separately. That script saves the metrics to a json file on the cluster.
3. Results json and metrics json is downloaded to buildkite runner
4. Results json and metrics json are loaded and reported to the database. If metrics json cannot be uploaded for whatever reason, it is skipped and the upload is attempted again without the metrics. Results json is always uploaded.

Looking at all three long running jobs that failed, the following can be observed:

- In `long_running_many_actor_tasks_1673158756` and `long_running_many_tasks_serialized_ids_1673158749` the test script itself timed out and was killed, while the metrics collection script ran fine and took around 20s
- In `long_running_node_failures_1673158736`, the test script errored out and metric collection did not even take place
- In `long_running_many_actor_tasks_1673158756` and `long_running_many_tasks_serialized_ids_1673158749`, the error in buildkite is:
```
[WARNING 2023-01-08 22:35:15,830] db.py: 53  Couldn't persist with prometheus_metrics, trying without them
--
  | WARNING:ray_release.logger:Couldn't persist with prometheus_metrics, trying without them
  | [ERROR 2023-01-08 22:35:15,918] run_release_test.py: 157  Last update to results json was too long ago (inf > 300)
```
We can see that the metrics upload failed gracefully and the next upload was without them. The error is caused by the test itself (or more accurately, caused by the returned test results not matching the assertion) and completely unrelated to metrics collection/uploading.
- In `long_running_node_failures_1673158736` the test command has errored out in the first place.

Given the above, I do not think this is related to metrics collection at all and instead is caused by an actual regression in the test. I am happy to make the "Couldn't persist with prometheus_metrics, trying without them" log more clear to avoid this sort of confusion in the future.

**Comment by Yard1** [comment]
Looking deeper, it looks like the `results.json` file is malformed or nonexistent, therefore causing the alert to use `inf` as the default value. I think that this is because the job is terminated right in the middle of writing to `results.json`.

**Comment by Yard1** [comment]
PR attempting to fix here - https://github.com/ray-project/ray/pull/31727. Started the full release test run there.
