### ISSUE TITLE
[core][state] ray summary breaks when data is missing 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#31575]
### What happened + What you expected to happen

With data loss on the worker side, there might be tasks without task info (e.g. type), however ray summary assumes this to be present. 

### Versions / Dependencies

master

### Reproduction script

failure of ray summary tasks in many_tasks. 

### Issue Severity

None

**Comment by rkooo567** [comment]
why don't we just increase the default worker-side data loss buffer size? I remember although we have sth like 100K, it wouldn't use high memory usage?

**Comment by rickyyx** [comment]
Yeah, that could work - but I guess we should also handle the data loss gracefully (no crashing of the api when it happens).

**Comment by stevenhubhub** [comment]
> 

Hi, Does his question have anything to do with this(I dont konw):

> **Object Store Memory**

Datasets uses the Ray object store to store data blocks, which means it inherits the memory management features of the Ray object store. This section discusses the relevant features:

Object Spilling: Since Datasets uses the Ray object store to store data blocks, any blocks that can’t fit into object store memory are automatically spilled to disk. The objects are automatically reloaded when needed by downstream compute tasks:

Locality Scheduling: Ray will preferentially schedule compute tasks on nodes that already have a local copy of the object, reducing the need to transfer objects between nodes in the cluster.

Reference Counting: Dataset blocks are kept alive by object store reference counting as long as there is any Dataset that references them. To free memory, delete any Python references to the Dataset object.
