### ISSUE TITLE
[Ray 2.3 release] `dask_on_ray_1tb_sort (a954ab7)` OOM failure

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32195]
OOM failure for dask_on_ray_1tb_sort (a954ab7)

BuildKite: https://buildkite.com/ray-project/release-tests-branch/builds/1332#01860fab-fa24-4968-b784-b80406311235
Cluster: https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_b5qgvrfp9n88fsqly46wjtiud7?command-history-section=command_history&drivers-section=interactive-sessions

```
(autoscaler +28s) Resized to 264 CPUs.
Traceback (most recent call last):
  File "dask_on_ray/dask_on_ray_sort.py", line 230, in <module>
    file_path=args.file_path,
  File "dask_on_ray/dask_on_ray_sort.py", line 145, in trial
    10, npartitions=-1
  File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/dataframe/core.py", line 1140, in head
    return self._head(n=n, npartitions=npartitions, compute=compute, safe=safe)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/dataframe/core.py", line 1174, in _head
    result = result.compute()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/base.py", line 290, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/base.py", line 573, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 203, in ray_dask_get
    result = ray_get_unpack(object_refs, progress_bar_actor=pb_actor)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 504, in ray_get_unpack
    computed_result = get_result(object_refs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 491, in get_result
    return ray.get(object_refs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 2380, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::dask:('head-1000-10-sort_index-be01da623ff06afe98fde4f50eda005f', 0)() (pid=1909, ip=10.0.3.188)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::dask:('head-partial-10-sort_index-be01da623ff06afe98fde4f50eda005f', 808)() (pid=2278, ip=10.0.3.188)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.OutOfMemoryError: Task was killed due to the node running low on memory.
Memory on the node (IP: 10.0.3.195, ID: 1fbfe866cadd55f7c78b1549a38263d90f3d9b5a2a01f6969c0d4344) where the task (task ID: b2361cda760e73ce485cb3b069cdda885538befc03000000, name=dask:('sort_index-be01da623ff06afe98fde4f50eda005f', 808), pid=466, memory used=12.27GB) was running was 209.96GB / 219.60GB (0.956091), which exceeds the memory usage threshold of 0.95. Ray killed this worker (ID: 9c704e9766df13b6da7d15dbda87aaa7630eba9dc2122a014d0891a2) because it was the most recently scheduled task; to see more information about memory usage on this node, use `ray logs raylet.out -ip 10.0.3.195`. To see the logs of the worker, use `ray logs worker-9c704e9766df13b6da7d15dbda87aaa7630eba9dc2122a014d0891a2*out -ip 10.0.3.195. Top 10 
```

**Comment by cadedaniel** [comment]
I checked recent runs and they also have some OOM killing going on. It's unclear if it's a flaky failure or regression. Sang suggests running this test on older commits with a memory metric added: https://github.com/ray-project/ray/blob/b31343a8afcafef0fbcf7e81f102aa947870265f/release/benchmarks/distributed/test_many_tasks.py#L81

this will allow us to know if it's a memory usage regression or flaky test

**Comment by cadedaniel** [comment]
cc @c21 can you find an assignee on data team to bisect this? core team is overloaded with release blockers

**Comment by c21** [comment]
Bisecting is finished and https://github.com/ray-project/ray/pull/31976 is causing nightly test failure here.

* Failed nightly test for the commit - https://buildkite.com/ray-project/release-tests-branch/builds/1371
* Successful nightly test for the commit before above one  - https://buildkite.com/ray-project/release-tests-branch/builds/1372

Full bisecting runs are recorded in [here](https://gist.github.com/c21/82f63d6b3fc44d71d55c0df13832c27f). 

Not sure if this is due to the nightly test itself, or a problem in the actual code.

cc @clarng and @scv119 - could you help take a look? Thanks.

**Comment by clarng** [comment]
I notice there is a longer delay before the job starts, that is not directly related to OOM.
New run with regression:
https://ec2-7c1kalm-17wvyib-0000-cust-mon.ray.aws-us-west-2-admin.anyscale-test-production.com/grafana/?editPanel=4&orgId=1&token=FrCxWPaXBnNRGua7TQtfzaF4h3jkXX1ZP18k613zIWw&var-ClusterID=ses_kry382klkkzriktzamhmuj129y&from=1675843287869&to=1675850172188

Previous run, before regression:
https://ec2-7c1kalm-17wvyib-0000-cust-mon.ray.aws-us-west-2-admin.anyscale-test-production.com/grafana/?editPanel=4&orgId=1&token=FrCxWPaXBnNRGua7TQtfzaF4h3jkXX1ZP18k613zIWw&var-ClusterID=ses_ymwrcc8giveshhjamnvxaj7kyr&from=1675849573619&to=1675857056574

**Comment by clarng** [comment]
Got the logs from re-run, relevant logs (reverse chrono)
`
101028Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.10102710102647	0.09	/home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/anyscale session web_terminal_server --deploy...1010251134	4.52	ray::IDLE10102476888	5.01	ray::IDLE_SpillWorker101023752	9.02	ray::IDLE10102276889	9.21	ray::IDLE_SpillWorker101021755	9.90	ray::IDLE101020751	10.08	ray::IDLE101019172	13.38	/home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=...101018756	14.07	ray::dask:('sort_index-be01da623ff06afe98fde4f50eda005f', 961)101017753	20.93	ray::dask:('sort_index-be01da623ff06afe98fde4f50eda005f', 982)101016PID	MEM(GB)	COMMAND101015Memory on the node (IP: 10.0.3.220, ID: d8d86d45a50bf559c95a57040f45917c405e976a5e32b81b80e6c536) where the task (task ID: b909ebe2c3eec18313abb66ea5247f8cdb6d224101000000, name=dask:('simple-shuffle-0e79646bda8fc56e33e539408ef711de', 511), pid=751, memory used=10.08GB) was running was 211.01GB / 219.60GB (0.960898), which exceeds the memory usage threshold of 0.95. Ray killed this worker (ID: 47da16713ea2a9f13cd40df224051de3e4849fc04652759e143e663a) because it was the most recently scheduled task; to see more information about memory usage on this node, use `ray logs raylet.out -ip 10.0.3.220`. To see the logs of the worker, use `ray logs worker-47da16713ea2a9f13cd40df224051de3e4849fc04652759e143e663a*out -ip 10.0.3.220. Top 10 memory users:101014101013[2023-02-08 12:27:57,620 I 172 172] (raylet) node_manager.cc:2890: Killing worker with task Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=ray.util.dask.scheduler, class_name=, function_name=dask_task_wrapper, function_hash=7f6b31139ff54517ade2d28efb827130}, task_id=b909ebe2c3eec18313abb66ea5247f8cdb6d224101000000, task_name=dask:('simple-shuffle-0e79646bda8fc56e33e539408ef711de', 511), job_id=01000000, num_args=2010, num_returns=1, depth=1, attempt_number=0, max_retries=3101012Task should be retried? 0101011101010Task assigned time 1970-01-01T00:00:00+00:00 worker id 192a908f0005efcea7cf9e816f5a48e4d0e7f6948343517f84bbf188 memory used 55169024 task spec Type=NORMAL_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=EmptyFunctionDescriptor}, task_id=NIL_ID, task_name=, job_id=NIL_ID, num_args=0, num_returns=0, depth=0, attempt_number=0, max_retries=0101009Task assigned time 1970-01-01T00:00:00+00:00 worker id 3ed368df37b557bd1e2561a0cd4fc2b361c6250ba1e44e1633865dfa memory used 9889378304 task spec Type=NORMAL_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=EmptyFunctionDescriptor}, task_id=NIL_ID, task_name=, job_id=NIL_ID, num_args=0, num_returns=0, depth=0, attempt_number=0, max_retries=0101008Task assigned time 1970-01-01T00:00:00+00:00 worker id a5365f742192085e89da95144b4a6eecfdc23f1ad66993e42104b875 memory used 77660160 task spec Type=NORMAL_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=EmptyFunctionDescriptor}, task_id=NIL_ID, task_name=, job_id=NIL_ID, num_args=0, num_returns=0, depth=0, attempt_number=0, max_retries=0101007Task assigned time 1970-01-01T00:00:00+00:00 worker id 1ef9f8915ece9a597f797f65e8ac801ec7d325ef8e6f24621112f055 memory used 5384712192 task spec Type=NORMAL_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=EmptyFunctionDescriptor}, task_id=NIL_ID, task_name=, job_id=NIL_ID, num_args=0, num_returns=0, depth=0, attempt_number=0, max_retries=0101006Task assigned time 1970-01-01T00:00:00+00:00 worker id 9420d78236bf4f810539e1d9c1ebb8822b51aa88dae012ed9fe12a58 memory used 76312576 task spec Type=NORMAL_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=EmptyFunctionDescriptor}, task_id=NIL_ID, task_name=, job_id=NIL_ID, num_args=0, num_returns=0, depth=0, attempt_number=0, max_retries=0101005Task assigned time 1970-01-01T00:00:00+00:00 worker id 254c18ca34b1de04ca582ef24ef5110cada2096d055d7fda3d65ea9b memory used 55214080 task spec Type=NORMAL_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=EmptyFunctionDescriptor}, task_id=NIL_ID, task_name=, job_id=NIL_ID, num_args=0, num_returns=0, depth=0, attempt_number=0, max_retries=0101004Task assigned time 1970-01-01T00:00:00+00:00 worker id 61cced5069845896c68c4c302acec4a5b759be50792397f8f6fa4f16 memory used 55332864 task spec Type=NORMAL_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=EmptyFunctionDescriptor}, task_id=NIL_ID, task_name=, job_id=NIL_ID, num_args=0, num_returns=0, depth=0, attempt_number=0, max_retries=0`

**Comment by clarng** [comment]
101002Tasks (retriable: 0) (parent task id: NIL_ID) (Earliest assigned time: 1970-01-01T00:00:00+00:00):101001Task assigned time 2023-02-08T20:25:28.492935869+00:00 worker id aa70362abb405d34bcbc6cb2f80609999a9fb16320d05ba06a8803ab memory used 22472056832 task spec Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=ray.util.dask.scheduler, class_name=, function_name=dask_task_wrapper, function_hash=7f6b31139ff54517ade2d28efb827130}, task_id=dc342cb19bbc5e87982c78ea149f7e634e82d35701000000, task_name=dask:('sort_index-be01da623ff06afe98fde4f50eda005f', 982), job_id=01000000, num_args=12, num_returns=1, depth=1, attempt_number=2, max_retries=3

101000Tasks (retriable: 1) (parent task id: 1d467fd3d3ebe4a77d5b33957ff54333bb3c90ad01000000) (Earliest assigned time: 2023-02-08T20:25:28.492935869+00:00):100999Task assigned time 2023-02-08T20:26:22.542631775+00:00 worker id d288e9e921239e8bb5c5cc7fb7e2282b3c84e771c2a37b41c077a906 memory used 10629337088 task spec Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=ray.util.dask.scheduler, class_name=, function_name=dask_task_wrapper, function_hash=7f6b31139ff54517ade2d28efb827130}, task_id=add93843775a7dd0adc5d779b87277bf0009eb6601000000, task_name=dask:('simple-shuffle-0e79646bda8fc56e33e539408ef711de', 512), job_id=01000000, num_args=2010, num_returns=1, depth=1, attempt_number=0, max_retries=3

100998Tasks (retriable: 1) (parent task id: 12975294b8661e2c7cd094b1895fd31d0f8b888101000000) (Earliest assigned time: 2023-02-08T20:26:22.542631775+00:00):100997Task assigned time 2023-02-08T20:26:25.538821483+00:00 worker id 8e44c445a1f21f3c9b34b2c1a0f5cd6d09447bb63b8ad87e83573355 memory used 4855304192 task spec Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=ray.util.dask.scheduler, class_name=, function_name=dask_task_wrapper, function_hash=7f6b31139ff54517ade2d28efb827130}, task_id=c27bc2524831aa4862a97c54cbc4912002f9335c01000000, task_name=dask:('sort_index-be01da623ff06afe98fde4f50eda005f', 33), job_id=01000000, num_args=12, num_returns=1, depth=1, attempt_number=0, max_retries=3

100996Tasks (retriable: 1) (parent task id: 0f8c5aa2c70d1ae870297758de2565594a3258b701000000) (Earliest assigned time: 2023-02-08T20:26:25.538821483+00:00):100995Task assigned time 2023-02-08T20:27:02.636608373+00:00 worker id cf8923dc5fcd9cc57acc2148b722bd7436d03202219cabb2eac31e01 memory used 15103963136 task spec Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=ray.util.dask.scheduler, class_name=, function_name=dask_task_wrapper, function_hash=7f6b31139ff54517ade2d28efb827130}, task_id=68d278eea8f42c43b7ed4b77e313dd15a9a29bd901000000, task_name=dask:('sort_index-be01da623ff06afe98fde4f50eda005f', 961), job_id=01000000, num_args=12, num_returns=1, depth=1, attempt_number=0, max_retries=3

100994Tasks (retriable: 1) (parent task id: d9eacfa5f97316f25468795c37cb3ef3b32ea35201000000) (Earliest assigned time: 2023-02-08T20:27:02.636608373+00:00):100993Task assigned time 2023-02-08T20:27:38.649324772+00:00 worker id 6a3e1debc3fc769ec8742cac0e5ebc49e78df36132c978897fd373df memory used 9687556096 task spec Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=ray.util.dask.scheduler, class_name=, function_name=dask_task_wrapper, function_hash=7f6b31139ff54517ade2d28efb827130}, task_id=3701b47da96f483a1d614641d123d962d657ccdf01000000, task_name=dask:('simple-shuffle-0e79646bda8fc56e33e539408ef711de', 929), job_id=01000000, num_args=2010, num_returns=1, depth=1, attempt_number=0, max_retries=3

100992Tasks (retriable: 1) (parent task id: e3c0960f7150f41fd12a7c0b5505c93047e630f201000000) (Earliest assigned time: 2023-02-08T20:27:38.649324772+00:00):100991Task assigned time 2023-02-08T20:27:38.892865674+00:00 worker id 47da16713ea2a9f13cd40df224051de3e4849fc04652759e143e663a memory used 10823397376 task spec Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=ray.util.dask.scheduler, class_name=, function_name=dask_task_wrapper, function_hash=7f6b31139ff54517ade2d28efb827130}, task_id=b909ebe2c3eec18313abb66ea5247f8cdb6d224101000000, task_name=dask:('simple-shuffle-0e79646bda8fc56e33e539408ef711de', 511), job_id=01000000, num_args=2010, num_returns=1, depth=1, attempt_number=0, max_retries=3

100990Tasks (retriable: 1) (parent task id: 485617dc596dc10ca10e693490dbb3736af3573301000000) (Earliest assigned time: 2023-02-08T20:27:38.892865674+00:00):100989[2023-02-08 12:27:57,620 I 172 172] (raylet) worker_killing_policy_group_by_owner.cc:91: Sorted list of tasks based on the policy:

**Comment by clarng** [comment]
The problem with this workload is that each task belongs to a different parent, so whenever the policy kills something it will trigger the workload to fail

**Comment by rkooo567** [comment]
Q: why didn't this happen with the previous policy?

**Comment by clarng** [comment]
> Q: why didn't this happen with the previous policy?

We only set infinite retry now and do deadlock detection with new policy

Before retry is finite and we don't do deadlock detection with previous policy


We talked about cleaning up idle workers so I think that should help here (there's over 10GB which I suspect are idle workers)

cc @ericl  @stephanie-wang

**Comment by clarng** [comment]
Also what seems to happen is that the parents of those tasks are not running on this node - since the logs are gone I'm trying to re-run another time to see where those parents are

**Comment by clarng** [comment]
Tested the patch that kills idle worker, but it looks like there is some memory leak (not likely due to the patch) that would then also fail the workload:


```
Traceback (most recent call last):
  File "dask_on_ray/dask_on_ray_sort.py", line 230, in <module>
    file_path=args.file_path,
  File "dask_on_ray/dask_on_ray_sort.py", line 145, in trial
    10, npartitions=-1
  File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/dataframe/core.py", line 1140, in head
    return self._head(n=n, npartitions=npartitions, compute=compute, safe=safe)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/dataframe/core.py", line 1174, in _head
    result = result.compute()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/base.py", line 290, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/base.py", line 573, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 203, in ray_dask_get
    result = ray_get_unpack(object_refs, progress_bar_actor=pb_actor)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 504, in ray_get_unpack
    computed_result = get_result(object_refs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 491, in get_result
    return ray.get(object_refs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 2380, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::dask:('head-1000-10-sort_index-be01da623ff06afe98fde4f50eda005f', 0)() (pid=1904, ip=10.0.3.82)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::dask:('head-partial-10-sort_index-be01da623ff06afe98fde4f50eda005f', 983)() (pid=2275, ip=10.0.3.82)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::dask:('sort_index-be01da623ff06afe98fde4f50eda005f', 983)() (pid=2275, ip=10.0.3.82)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.OutOfMemoryError: Task was killed due to the node running low on memory.
Memory on the node (IP: 10.0.3.76, ID: 3d3208a997acbeae425b2233fe43f18a938d72f6ed77b895af23f13d) where the task (task ID: 6104c1c5a19a1a3c3012b9b922d65796044eab7903000000, name=dask:('simple-shuffle-0e79646bda8fc56e33e539408ef711de', 983), pid=450, memory used=13.68GB) was running was 215.48GB / 219.60GB (0.981237), which exceeds the memory usage threshold of 0.95. Ray killed this worker (ID: 03a3f1b1a088acea524b8a1b15e8200b71fc255464f8a4d14553b245) because it was the most recently scheduled task; to see more information about memory usage on this node, use `ray logs raylet.out -ip 10.0.3.76`. To see the logs of the worker, use `ray logs worker-03a3f1b1a088acea524b8a1b15e8200b71fc255464f8a4d14553b245*out -ip 10.0.3.76. Top 10 memory users:
PID     MEM(GB) COMMAND
172     58.93   /home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=...
447     21.02   ray::IDLE
452     17.25   ray::dask:('sort_index-be01da623ff06afe98fde4f50eda005f', 194)
450     13.68   ray::IDLE
454     13.61   ray::dask:('sort_index-be01da623ff06afe98fde4f50eda005f', 192)
448     2.55    ray::IDLE
813     2.54    ray::IDLE
47      0.09    /home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/anyscale session web_terminal_server --deploy...
351     0.07    /home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/agen...
44      0.06    /home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/jupyter-notebook --NotebookApp.token=aph0_CkY...
Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
```

**Comment by zhe-thoughts** [comment]
Thanks @clarng 

Actually we should keep this open until the commit is cherry picked
