### ISSUE TITLE
[core][AIR] Deadlock in TorchTrainer?

### ISSUE THREAD

**Issue by kpetersen-hf** [ray-project/ray#32856]
### What happened + What you expected to happen

1. The bug:

I would like to use ray tasks within the training function of a TorchTrainer. However, the ray tasks -- here task f() -- are not executed because the train function cannot obtain enough resources.

2. Expected behavior

Ray tasks or ray actors should execute within the training function of the TorchTrainer in the same way as outside of it.

3. Logs

@scottsun94 replicated this issue and created the following screenshots using dashboard in Ray 2.3:

Screen shot 1
<img width="1769" alt="im2" src="https://user-images.githubusercontent.com/56620752/221620736-4961e627-13d0-429b-ad41-8c5b67a5f3ac.png">

Screen shot 2
<img width="1775" alt="im1" src="https://user-images.githubusercontent.com/56620752/221620707-fccbf354-5f84-41a5-94e9-b6c66b79be82.png">

### Versions / Dependencies

Ray 2.2 and 2.3
Centos 7.8.2003

### Reproduction script

```
import ray
from ray.train.torch import TorchTrainer
from ray.air.config import ScalingConfig


@ray.remote
def f():
    import time
    time.sleep(1)
    print("check")


def train_func():
    print("start")
    ray.get([f.remote() for i in range(10)])
    print("end")


def main():
    ray.init()
    scaling_config = ScalingConfig(num_workers=2)
    trainer = TorchTrainer(
                train_loop_per_worker=train_func,
                scaling_config=scaling_config)
    trainer.fit()    

if __name__ == "__main__":
    main()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by justinvyu** [comment]
Hi @kpetersen-hf, could you explain what these remote tasks are used for in each train worker?

**Comment by justinvyu** [comment]
@kpetersen-hf Thanks for the clarification!

The problem here is that Train will set a Ray configuration for child remote tasks to inherit from the placement group allocated to their parent. In this case, the Ray Train worker is assigned some amount of resources, and no resources are left to allocate to run these 10 remote tasks.

To workaround this, you can disable this "placement group inheritance" in the remote task options. See [here](https://docs.ray.io/en/master/ray-core/scheduling/placement-group.html#quick-start) for more info. Search for `placement_group_capture_child_tasks`.

```python
def train_func():
    print("start")
    futures = [
        f.options(
            scheduling_strategy=PlacementGroupSchedulingStrategy(placement_group=None)
        ).remote()
        for i in range(10)
    ]
    ray.get(futures)
    print("end")
```

**Comment by justinvyu** [comment]
Good question! The train worker gets allocated the full 5 CPUs in this case. In Train, there's not currently a way to say "the worker needs X CPUs, and it should also save Y CPUs for remote tasks".

For example, in Tune, there *is a way* to set resources for the "worker" and additional resource bundles for remote tasks that it may spawn.

```python
def train_fn():
    ray.get([f.remote() for _ in range(10)])

tuner = tune.Tuner(
    tune.with_resources(
        train_func,
        resources=tune.PlacementGroupFactory([{"CPU": 0}] + [{"CPU": 1}] * 10)
    ),
)
tuner.fit()
```

See here for more info: [Tune PlacementGroupFactory API ref](https://docs.ray.io/en/latest/tune/api/doc/ray.tune.execution.placement_groups.PlacementGroupFactory.html).

**Comment by justinvyu** [comment]
Let's leave this issue open for tracking purposes.

**Comment by MaxVanDijck** [comment]
Have ran into this issue trying to run remote functions inside TorchTrainer train_func
`TypeError: Remote functions cannot be called directly. Instead of running`

Resolved with the solution proposed in https://github.com/ray-project/ray/issues/32856#issuecomment-1446882245 but this also doesn't strike me as an amazing solution.
