### ISSUE TITLE
[Draft] [RFC] Revamping AIR-Data APIs

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#32929]
Previously, preprocessors could not be called directly on Datasets due to the following reasons:
- AIR needed control when to execute preprocessing (whether before or after converting to DatasetPipeline). **This is not needed anymore with streaming as default execution.**
- AIR would manually fuse preprocessing and prediction stages. **This is not needed anymore with Datasets lazy by default.**
- Determine which batch format to use. **This is not needed anymore with zero-copy batch format.**

As a result, this led to clunky APIs, requiring Checkpoints as a first-class citizen for inference and a heavyweight DatasetConfig for training.

With new changes to Datasets, we should reconsider some previous API decisions around Preprocessors and Predictor

### Before
```python
preprocessor1 = BatchMapper(lambda x: x+1)
preprocessor2 = TorchVisionPreprocessor(torchvision.transforms.Crop(224, 224))
chained = Chain([preprocessor1, preprocessor2])

model = pretrained_resnet()
checkpoint = TorchCheckpoint.from_model(model, preprocessor=chained)
batch_predictor = BatchPredictor.from_checkpoint(checkpoint)

ds = ds.read_parquet("s3://data")
predictions = batch_predictor.predict(ds)
```

### After
```python
model = pretrained_resnet()
predictor = TorchPredictor(model)
# Alternatively delayed model creation
predictor = TorchPredictor(lambda: pretrained_resnet())

predictions = ds.read_parquet("s3://data")
    .map_batches(lambda x: x+1)
    .map_batches(TorchVisionPreprocessor(torchvision.transforms.Crop(224, 224)))
    .map_predict(predictor)
```

- Removes Checkpoints from the critical path for inference
- Removes the need for explicit Chain preprocessor
- Removes BatchMapper in favor of directly defining functions
- Introduces `map_predict` API, which is like `map_batches` but with additional prediction-specific guardrails and optimizations

### Before
```python
train_ds, val_ds = ds.read_parquet("s3://data").train_test_split(0.2)
ordinal_encoder = OrdinalEncoder()
per_epoch_preprocessor = BatchMapper(lambda x: add_random_noise(x))

def train_func():
   # I cannot access the preprocessor stats inside my training function.
   num_embeddings = ???

trainer = TorchTrainer(train_func, 
    preprocessor=ordinal_encoder, 
    datasets = {"train": train_ds, "val_ds": val_ds}
    dataset_config=
        {"train": DatasetConfig(per_epoch_preprocessor=per_epoch_preprocessor)
        "val": DatasetConfig(transform=False)}
)
trainer.fit()
```

### After
```python
train_ds, val_ds = ds.read_parquet("s3://data").train_test_split(0.2)
ordinal_encoder = OrdinalEncoder()
ordinal_encoder.fit(train_ds)

# Per-epoch preprocessing can be applied directly since each epoch is re-executed in streaming mode
train_ds = train_ds.map_batches(ordinal_encoder).map_batches(BatchMapper(lambda x: add_random_noise(x)))

# Alternatively persist in between
train_ds = train_ds.map_batches(ordinal_encoder).persist().map_batches(BatchMapper(lambda x: add_random_noise(x)))

def train_func():
   num_embeddings = ordinal_encoder.stats.count

trainer = TorchTrainer(train_func, datasets = {"train": train_ds, "val": val_ds})
trainer.fit()
```

- Preprocessors can be applied directly to datasets because of lazy execution
- Removes DatasetConfig from Trainer

## TODO
- Online serving. Use DAG API for preprocessor+predictor pipelines?
- Training -> Prediction. Seems that in practice, this is really training -> W&B -> prediction

**Comment by ericl** [comment]
I'm very supportive of this. A couple questions:
- What's the signature change for `map_batches`? Would we be changing Preprocessor to subclass Callable, or changing `map_batches` to take `Preprocessor`?
- Shall we call it `map_predictor` instead of `map_predict`? The former seems to be more precise.
- We might need to also support passing a lambda that creates a Predictor.

I'm a bit less sure on the proposed changes to Train. There seem to be two challenges introduced: capturing the preprocessing pipeline, and management of fitting the preprocessor. It's not obvious how you'd be able to capture that while being able to use Datasets freely outside the Train run.

**Comment by amogkam** [comment]
1. yeah was thinking `Preprocessor` would subclass `Callable` to avoid overloading `map_batches`
2. That sgtm
3. Yes, good idea. We should make this change

Regarding the concerns about training, I agree. Still needs to be fleshed out more.

Maybe we can make the inference changes first?

This would involve
1. Introducing `__call__` to the Preprocessor API (that just calls `transform_batch`)
2. Introduce `map_predict` alpha API (which can just be a wrapper around `BatchPredictor` for now)
3. Update the `__init__` signatures for all Predictors to make them easily instantiable without Checkpoints.
4. Update all examples and documentation to use these APIs

**Comment by ericl** [comment]
The inference changes seem reasonable to me. @c21 @clarkzinzow can you also assess?

**Comment by clarkzinzow** [comment]
Strongly agree with the inference changes, although I'm more in favor of making `ds.map_batches()` `Preprocessor`-aware rather than having it subclass `Callable`, since:
1. we'll want to eventually add optimization rules that know what a particular preprocessor does and how it's configured rather than it being a black-box UDF (e.g. for preprocessor reordering or pushdown of certain sub-operations),
2. `CallableClass` is meant for stateful setup and is only supported by the actor compute model, so stateless preprocessors (i.e. pure transformations) don't quite fit that stateful model or the actor constraint,
3. a `CallableClass` is an uninitialized class, while we'd want to be passing configured `Preprocessor` instances.

In fact, we should maybe think about adding a `ds.map_preprocessor()` API that has a narrower interface tailored to the `Preprocessor` paradigm, similar to `ds.map_predictor()`. That API could pretty much be reduced down to `def map_preprocessor(preprocessor, batch_size, prefetch_batches)`, since all other args are either not applicable or will be set automatically based on the preprocessor config (e.g. `zero_copy_batch`, `batch_format`, `compute`).

As for the training side, I feel like serialized the preprocessing dataset (the plan, not the materialized data) into the checkpoint is the answer here! What we want to capture is (1) the preprocessing plan/lineage, and (2) the fitted stats. But if we do the stats fitting (saving the stats in the preprocessor instance) before we create the preprocessing transformation pipeline, as in your example, aren't we good to go?

The stats will be saved in the preprocessor instance, which will be captured in the preprocessing pipeline plan, which we can serialize into the model checkpoint. Then when it's time for inference, you just load the model + the (lazy) preprocessing pipeline dataset from the checkpoint, and the inference-time preprocessing run will use the stats that were fit on the training data.

**Comment by c21** [comment]
Thanks @amogkam, agreed with making the inference change first.

I am +1 to add `ds.map_preprocessor()` and `ds.map_predictor()`. This looks more consistent, and avoid confusion when user uses `map_batches()` given the reasons (2) and (3) from @clarkzinzow.
