### ISSUE TITLE
Garbage collection for actor dummy objects

### ISSUE THREAD

**Issue by guoyuhong** [ray-project/ray#3308]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **Ray installed from (source or binary)**: Any
- **Ray version**: 0.5.3
- **Python version**: Any
- **Exact command to reproduce**:

### Describe the problem

1. For long running jobs, actor won't exit and it will submit tasks continuously. Each task will have a dummy object put in `local_objects_` in task_dependency_manager.cc. This unordered map will grow very big. When the size grows to 13-16 million, the rehashing algorithm will take more than 10 second, which cause heartbeat timeout. 
2. For python functions, even if there is no return value, a `None` object will be put into Plasma. However, users don't aware there is a None value put into Plasma and they will not call Free to release it, which will also cause very big Plasma usage or large amount of `local_objects_` elements.

**Comment by guoyuhong** [comment]
Thanks, @robertnishihara for the `num_return_vals=0` method. That is what I want!
For 1, we have implemented in local repo to delete the GCS table as well as the dummy object after checkpointing.

**Comment by raulchen** [comment]
Actually, I think we can delete the previous dummy object on the fly after we do `ExtendFrontier`. Because we only need the most recent dummy object to represent Actor's state. I'll experiment this idea when I have time. cc @stephanie-wang

**Comment by robertnishihara** [comment]
@raulchen, I'm not 100% sure, but there may be some issues with that if the actor handles are passed into other tasks because then you may receive tasks that depend on an earlier actor dummy object that has been removed.

**Comment by raulchen** [comment]
@robertnishihara I think that's true for now, because when we pass a handle to another task, the new handle will have the same cursor. But I don't really understand why the new handle needs to depend on the old handle's cursor. I think from the perspective of the actor, these 2 handles can be simply 2 independent clients. Their task execution order shouldn't be related, right?

**Comment by robertnishihara** [comment]
@raulchen I think in a lot of cases, it is intuitive to expect the execution orders to be related. For example,

```python
a = Actor.remote()  # Create an actor.

a.initialize.remote()  # Do some initialization.

f.remote(a)  # Pass a into f, which uses a.
```

In this example, I think people would expect the `initialize` task (and definitely the actor creation task) to happen before whatever tasks `f` submits to `a`.

https://github.com/ray-project/ray/issues/1149 is a related example in which the lack of dependence caused confusion (though this is with the actor creation task).

**Comment by raulchen** [comment]
@robertnishihara Thanks. 
Regarding the 4 options you mentioned in [this comment](https://github.com/ray-project/ray/issues/1149#issuecomment-345153290), I think it makes sense to have option 2 the default behavior. because in normal cases, users may only want to distribute a handle to multiple workers, and don't care about the order.

Regarding the example you commented above, one can explicitly ensure order by doing the following:
```
ray.get(a.initialize.remote())
f.remote(a)
```
or
```
initialized = a.initialize.remote()
f.remote(a, initialized)
```

**Comment by stephanie-wang** [comment]
As @robertnishihara, the original reasoning for keeping the dummy objects around is for ordering. It's hard to say definitively how often users do or don't care about ordering, so I think we'll just have to wait and see.

As a longer-term solution, you can actually decide when to release dummy objects as long as the frontend provides information about how many times an actor handle has been passed around. So in the example posted above, if you did, this then you would only have to keep around the `initialize` dummy object, and it could be released once `f` calls its first method.
```python
a = Actor.remote()  # Create an actor.
a.initialize.remote()  # Do some initialization.
f.remote(a)  # Pass a into f, which uses a.
a.foo.remote()  # Tell the backend that a was passed into f.
```

**Comment by stephanie-wang** [comment]
And yes, I completely agree that we should release old dummy objects after a checkpoint.

**Comment by robertnishihara** [comment]
It is possible that an old dummy object ID could become relevant a long time later, right (even after multiple checkpoints)? E.g., if a handle was passed into a task but the task didn't get scheduled for a very long time due to some other object dependency.

In that case, we really just need to be able to compare the dummy Object ID with the current actor frontier, so if we can encode more semantic information in the IDs, e.g., a vector clock essentially, then we wouldn't need to keep around all of the dummy object IDs.

@stephanie-wang Does something like that make sense?

**Comment by ujvl** [comment]
> In that case, we really just need to be able to compare the dummy Object ID with the current actor frontier, so if we can encode more semantic information in the IDs, e.g., a vector clock essentially, then we wouldn't need to keep around all of the dummy object IDs.

@robertnishihara can you elaborate on how that solves the case you just described (late-scheduled tasks)? Why would having that ordering let you release an old dummy object? I was trying to figure out a solution to the same problem in general for lineage GC after checkpointing.

**Comment by stephanie-wang** [comment]
I really don't think that it's a good idea to pursue comparable object IDs. The best we can do is probabilistic comparison. You will run out of bits very quickly if you try to do perfect comparison.

The way that I would go about the case that @robertnishihara listed is:
1. The frontend notifies the backend that a handle has been passed to another task with dummy object `x`. The backend records the fact that it is waiting for `x`. It can do this by preemptively adding a new handle to the actor frontier.
2. The task with the new actor handle hasn't been scheduled yet, but a bunch of other tasks get submitted on other handles. All dummy objects for these handles in between `x` and the present task can be released. A checkpoint may be taken at any point, but it doesn't affect which objects get released (the set of dummy objects held is already the minimum).
4. The task gets scheduled and submits new tasks on its actor handle. The backend releases `x`.

Also, @raulchen, I think it's okay to release b as soon as x is scheduled the first time. If x gets resubmitted, then you have to roll back the actor to the latest checkpoint anyway, so b will get recreated.

**Comment by robertnishihara** [comment]
@stephanie-wang, regarding

> I think it's okay to release b as soon as x is scheduled the first time. If x gets resubmitted, then you have to roll back the actor to the latest checkpoint anyway, so b will get recreated.

This assumes that the checkpoint is before `b`, right? E.g., if the checkpoint was taken at `d` then reloading from the checkpoint won't cause `b` to get recreated, right?

Also, is there a way to make this work in the setting where the actor is using the "restart only" fault tolerance mode, where the actor is recreated, but no methods are replayed? I suppose that for such actors, task ordering probably doesn't matter and so maybe such actors simply shouldn't use dummy object IDs.

**Comment by stephanie-wang** [comment]
If the checkpoint happens before `b`, then `b` will get recreated. If the checkpoint was after `b`, then I think we should make it so that `b` is considered unreconstructable (similar to what we do right now for evicted actor objects), and gets failed immediately.

I think that the task ordering is still important for "restart only" actors, since it would not be very intuitive to users if tasks could suddenly be executed out-of-order for that failure mode. The part that would be different is after recovering from a failure, we would only require that any **later** task could be executed immediately, instead of requiring that the **next consecutive** task be executed.

**Comment by robertnishihara** [comment]
@stephanie-wang the scenario I'm concerned about is a little different I think.

I'm imagining a setting with no failures.

- Actor methods `a`, `b`, `c`, `d`, and `x` are submitted as above.
- Methods `a`, `b`, `c`, `d` execute.
- A checkpoint is taken (say after `d`), and so dummy object IDs for `a`, `b`, `c`, `d` are flushed.
- Then `x` finally arrives at the raylet (it was delayed for some reason).
- The correct behavior is to just execute `x`. Doing so respects all ordering constraints. However, `x` depends on the dummy object for `b` which has been flushed, so we don't know that we can execute it.

Does that make sense?

**Comment by stephanie-wang** [comment]
Actually, I don't think checkpoints really matter at all. The algorithm I'm proposing is to record the fact that the actor handle was forked from `b` in the task that produces `c`. When `c` gets executed, the raylet will see this and extend the actor's frontier to include the new handle on which `x` will be submitted. Any dummy object on the actor's frontier will be pinned, and everything before the frontier will be released. Therefore, `x`'s dependency will be pinned until it arrives at the raylet.
