### ISSUE TITLE
[Serve] Development workflow user experience bugs/feature requests 

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#33227]
## Development experience issues

1. I prefer the CLI `serve run app:entrypoint` because it shows all the incoming requests being handled + any errors that may occur in my development process. Also, I like the fact that it shuts down my replicas on Ctrl+C, rather than having them stick around and needing to shutdown manually.
    - However, I can't pass arbitrary command line flags through `serve run`, so I'm forced to use the Python `serve.run()` API that seems to have different behavior.
    - Current workaround: Adding an infinite loop after `serve.run()` will stream all the logs to the driver stdout.
3. `serve shutdown` does not work for me, after starting with `serve.run()`. I get this error:
```
$ serve shutdown

  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/dashboard/modules/serve/sdk.py", line 62, in __init__
    self._check_connection_and_version_with_url(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 258, in _check_connection_and_version_with_url
    raise ConnectionError(
ConnectionError: Failed to connect to Ray at address: http://localhost:52365/.
```

## Feature requests

1. I want to be able to query a deployment's status in the Python API. Ex: Get the number of replicas that are currently up, associated with a deployment handle.
    - Use case: in my client application logic, I want to make a certain number of parallel requests, depending on the number of replicas. I was thinking of introducing an endpoint that just queries a `num_replicas` API.
    - Current workaround: I think the REST API allows this: https://docs.ray.io/en/latest/serve/api/rest_api.html. I didn't realize that the endpoint should be targeting the dashboard server at `http://localhost:52365/`. I thought it'd be automatically attached as an endpoint at my application server `http://localhost:52365/api/...`

**Comment by shrekris-anyscale** [comment]
> However, I can't pass arbitrary command line flags through serve run

This has now been enabled by #34584.

> serve shutdown does not work for me, after starting with serve.run(). I get this error:

Based on the terminal output, it looks like the command failed because there was no long running Ray cluster locally. Since we haven't seen the same issue pop up over the last couple of months, I'll treat this as resolved. If it happens again though, please do make a new issue.

> I want to be able to query a deployment's status in the Python API. Ex: Get the number of replicas that are currently up, associated with a deployment handle.
Use case: in my client application logic, I want to make a certain number of parallel requests, depending on the number of replicas. I was thinking of introducing an endpoint that just queries a num_replicas API.

You can get the Serve status using [`client.get_serve_status()`](https://github.com/ray-project/ray/blob/39d8bd3a2c7c3748b8f27ca875874d9c49349ffa/python/ray/serve/_private/client.py#L430), and you can get the number of replicas (although the number may be stale) using [`client.get_deployment_info()`](https://github.com/ray-project/ray/blob/39d8bd3a2c7c3748b8f27ca875874d9c49349ffa/python/ray/serve/_private/client.py#L402). These aren't meant to be called inside a user's Serve application, but they can be helpful for debugging. The use case is nice for demonstration, but users shouldn't have to be concerned with the number of replicas when they make a query. For demonstration we can use `get_deployment_info` or the Serve CLI, but we're not planning to expose another API to get the number of replicas.

Thanks for logging these bugs and feature requests! It looks like they should all be resolved, so I'll close this issue.
