### ISSUE TITLE
KeyboardInterrupt: Fatal Error when using tune

### ISSUE THREAD

**Issue by fruffy** [ray-project/ray#3345]
### System information

    Ubuntu 18.04 4.19.0-041900-generic
    Latest Ray snapshot: 2018-11-16
    Ray 0.5.3
    Python 2.7.15:

### Describe the problem
Tried out the latest snapshot today. I am having issues with the tune framework handling keyboard interrupts and exiting properly. I am not exactly sure what could cause this.
To reproduce I just used the example listed here:
https://ray.readthedocs.io/en/latest/rllib-training.html#python-api

```
import ray
import ray.tune as tune

ray.init()
tune.run_experiments({
    "my_experiment": {
        "run": "PPO",
        "env": "CartPole-v0",
        "stop": {"episode_reward_mean": 200},
        "config": {
            "num_gpus": 0,
            "num_workers": 1,
            "sgd_stepsize": tune.grid_search([0.01, 0.001, 0.0001]),
        },
    },
})
```
(btw "sgd_stepsize" does not seem to exist any more) 
Hitting Ctrl + C here will cause a fatal error.
### Source code / logs

[out.txt](https://github.com/ray-project/ray/files/2591478/out.txt)

**Comment by ericl** [comment]
Btw is it just the error message? Does cleanup happen properly still?

**Comment by fruffy** [comment]
I seems to be just the error message. I assumed it first it had implications on exiting.
However, pull request #3297 still has issues I think, sorry for not catching that. It exits nicely after a normal run but something in ray catches KeyboardInterrupts and just kills the parent process without triggering clean-up on the child processes.
I expanded the example test a bit, which shows the problem I am currently dealing with. 
[test_env_with_subprocess.txt](https://github.com/ray-project/ray/files/2592444/test_env_with_subprocess.txt)

I can move this to a separate issue.

**Comment by ericl** [comment]
I can confirm that Ctrl-C a ray session does not clean up actor processes after https://github.com/ray-project/ray/pull/3297/files#diff-8165ed4a37603e0f7e2eaf79e3a69bf7R907

This seems to be because setting the pgid, while great for containing subprocesses an actor launches, means that signals the driver gets will also not get sent to those actors. There doesn't seem to be a great solution here, since process groups are not hierarchical (without resorting to cgroups...). However leaking processes on control-c is probably worse, so filed https://github.com/ray-project/ray/pull/3347
