### ISSUE TITLE
[RLLib] "Get Started" first example is confusing - Issue as been Closed as fixed but problem remains

### ISSUE THREAD

**Issue by rodrigodesalvobraz** [ray-project/ray#33467]
### Description

https://github.com/ray-project/ray/issues/32979 points to a problem fixed by #33140. However, it does not pass tests and the page continues as before. Is there a way to know the PR will eventually be published?

**Comment by avnishn** [comment]
ah I see the problem here @rodrigodesalvobraz . So when @ArturNiederfahrenhorst committed his fix, his fix shows up in the  docs that are built for master, but they will not show up in the default docs which are for ray 2.3. We'll be coming out with ray 2.4 in the coming weeks and this fix will be reflected in those docs:

https://docs.ray.io/en/master/rllib/rllib-training.html#using-the-rllib-cli
