### ISSUE TITLE
Make it so that the test files do not have more than a certain numer of lines

### ISSUE THREAD

**Issue by ollie-iterators** [ray-project/ray#33739]
### What happened + What you expected to happen

It seems that fixing things like test timeout is done by moving tests to different folders (e.g., like in https://github.com/ray-project/ray/pull/33704), so I think it would be good to split up the test files so that there are not more than, for example, 1000 lines in the test files so that it is easier to run tests.

### Versions / Dependencies

Main branch

### Reproduction script

Look at https://flakey-tests.ray.io/

### Issue Severity

Low: It annoys or frustrates me.

**Comment by ArturNiederfahrenhorst** [comment]
Test timeouts are not determined by the length of files but by their runtime.
Short files are not easier to run.
Splitting up tests can also increase cost and many tests should be kept in a file together simply because they belong together. Are you suggesting to split them up generally? Can you give more details on your idea?

**Comment by ollie-iterators** [comment]
I was suggesting splitting then up generally, like in the PR https://github.com/ray-project/ray/pull/32540 about splitting tensor tests from test_dataset.py

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for the suggestion. I don't think there is much to gain here since we generally want to be able to group tests together in one file, even if they are numerous.
