### ISSUE TITLE
[RLlib] something broken about the way that torch ppo writes out to json

### ISSUE THREAD

**Issue by kouroshHakha** [ray-project/ray#33789]
### What happened + What you expected to happen

when using the output writer, torch ppo writes out sample batches in the incorrect format:

`“value”: {”type”: “MultiAgentBatch”...`

instead of just

`{”type”: “MultiAgentBatch”...`

### Versions / Dependencies

NA

### Reproduction script

Useful debug script:
https://gist.github.com/avnishn/c8599a9947edcd9934421713ed82f175
```
def generate_offline_data(path: str):
    print(f"Generating offline data for training at {path}")
    trainer = RLTrainer(
        algorithm="PPO",
        run_config=RunConfig(stop={"timesteps_total": 5000}),
        config={
            "env": "CartPole-v1",
            "output": "dataset",
            "output_config": {
                "format": "json",
                "path": path,
                "max_num_samples_per_file": 1,
            },
            "batch_mode": "complete_episodes",
            "framework": "tf"
        },
    )
    trainer.fit()
def train_rl_bc_offline(path: str, num_workers: int, use_gpu: bool = False) -> Result:
    print("Starting offline training")
    dataset = ray.data.read_json(
        path, parallelism=num_workers, ray_remote_args={"num_cpus": 1}
    )

    trainer = RLTrainer(
        run_config=RunConfig(stop={"training_iteration": 5}),
        scaling_config=ScalingConfig(num_workers=num_workers, use_gpu=use_gpu),
        datasets={"train": dataset},
        algorithm=BC,
        config={
            "env": "CartPole-v1",
            "framework": "tf",
            "evaluation_num_workers": 1,
            "evaluation_interval": 1,
            "evaluation_config": {"input": "sampler"},
            "framework": "tf"
        },
    )

    # Todo (krfricke/xwjiang): Enable checkpoint config in RunConfig
    # result = trainer.fit()
    tuner = Tuner(
        trainer,
        _tuner_kwargs={"checkpoint_at_end": True},
    )
    result = tuner.fit()[0]
    return result
ray.init(num_cpus=8)

path = "/tmp/out"
generate_offline_data(path)
result = train_rl_bc_offline(path=path, num_workers=2, use_gpu=False)
```
Should work with torch but doesn’t because of the way that sample batches are created.

### Issue Severity

None

**Comment by avnishn** [comment]
ok the problem is that `ray.data.write_json` has first trys to write data to arrow tables and then if the data isn’t able to be accepted by arrow then it writes it as a pandas data frame.
when we run our torch ppo code, our sample batch contains the infos key.
when we run our tf code it does not contain the infos key from the environment
tf doesnt contain that key since env infos is not traceable by `tf.function`
the infos key in this specific torch example is a dictionary that is in a format that is not able to be written to an arrow table.
When 
so when we try to write the tf sample batch we don’t fall back to this pandas style of writing.
when we write the torch sample batch we do fall back to the pandas style of writing

The fix is coming from the ray data team. They'll make it so that there is no fall back behavior when calling `ds.write_json()` and instead there is one expected output always.

We'll lay a commit on their pr that should fix the dataset writer / reader
