### ISSUE TITLE
[core] "soft" option for NodeAffinitySchedulingStrategy doesn't seem to work

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#33835]
## The problem

The following script should be able to utilize all CPU slots on a cluster, but when you run it it will only use CPUs on the head node.

This is a blocker for Dataset streaming, which uses this scheduling hint for best-effort locality optimization. Not supporting "soft" properly means locality scheduling can severely degrade performance.

### Versions / Dependencies

master / py39

### Reproduction script

```
import time
import ray
from ray.util.scheduling_strategies import NodeAffinitySchedulingStrategy

ray.init()

cur_node = ray.get_runtime_context().get_node_id()

@ray.remote
def f():
    time.sleep(1)
    print("done")

start = time.time()
ray.get([
    f.options(scheduling_strategy=NodeAffinitySchedulingStrategy(cur_node, soft=True)).remote()
    for _ in range(1000)
])
print(time.time() - start)
```

Reproduction workspace: https://console.anyscale-staging.com/o/anyscale-internal/workspaces/expwrk_1ncv7mqbfapj4ax5sa1679seep/ses_msttcvnbvzbgzefa2hia2kui9h?command-history-section=head_start_up_log

### Issue Severity

High: It blocks me from completing my task.

**Comment by scv119** [comment]
@clarng want to do the initial investigation?

**Comment by jjyao** [comment]
Oh, currently `soft` only tries to schedule tasks to other nodes when the target node is dead (instead of unavailable).

Actually why do we need NodeAffinitySchedulingStrategy for locality scheduling, shouldn't it just work without it?

**Comment by ericl** [comment]
We need this for push-based locality scheduling, where we send tasks to where actors will be consuming their outputs. The current locality scheduling mechanism cannot handle these forward looking dependencies.

**Comment by jjyao** [comment]
So the soft semantics you need is as long as the target node has no free resources, it should be immediately spilled to other nodes?

**Comment by ericl** [comment]
That's right.

**Comment by jjyao** [comment]
Seems we need to improve the expressiveness of `soft` option, a bool is not enough. I think we need three semantics:

1. no soft (i.e. hard)
2. soft when target is dead or infeasible
3. soft when target is not available

We can add a third option to NodeAffinitySchedulingStrategy that specifies semantic 2 or 3 when soft=True, something like `NodeAffinitySchedulingStrategy(target_node, soft=True, soft_policy="SOFT_WHEN_UNAVAILABLE")`

or we can expand the `soft` option to also accept a string (support bool as well for backward compatibility), something like `NodeAffinityScheduingStrategy(target_noe, soft="SOFT_WHEN_UNAVAILABLE")`

**Comment by ericl** [comment]
Is there a reason to support (2)? Soft seems like it should always be best
effort. It doesn't matter the exact semantics.

**Comment by clarng** [comment]
also, how is 2 different from 1? i.e. if the task stays queued on the target node until it dies or is infeasible?

**Comment by clarng** [comment]
So I see this is what is happening right now

When node affinity is "not soft"
- if the node doesn't exist, it throws error
- if the node is infeasible, it throws error
- otherwise it queues on the node

When node affinity is "soft"
- if the node doesn't exist, it tries to find a different node
- if the node is infeasible, it tries to find a different node
- otherwise it queues on the node

I think the request here is to change it such that

When node affinity is "not soft"
- if the node doesn't exist, it throws error
- if the node is infeasible, it throws error
- otherwise it queues on the node

When node affinity is "soft"
- if the node doesn't exist, it tries to find a different node
- if the node is infeasible, it tries to find a different node
- **if the node is full, it tries to find a different node**

**Comment by rkooo567** [comment]
To me, soft sounds like it will just spill to other node if the target node is unavailable (so I feel like there's no need to handle 2).

**Comment by clarng** [comment]
Have a PR, we can decide if we want to choose the semantics and if so we should merge

**Comment by jjyao** [comment]
> also, how is 2 different from 1? i.e. if the task stays queued on the target node until it dies or is infeasible?

@clarng hard means that you'd rather fail the task if the target node dies instead of running it somewhere else.

**Comment by jjyao** [comment]
Initially soft is introduced for fault tolerance (unlike node ip based scheduling, we don't want to hang/fail when the target node dies) so it has the same behavior as node ip based scheduling when the target node is temporarily unavailable.

I think there are cases where you'd want to wait (since availability is temporary) instead of immediately run on other nodes for reasons like performance. I think currently push based shuffle use soft=True to colocate merge and reduce tasks.


> Soft seems like it should always be best effort. It doesn't matter the exact semantics.

I think we should have well defined semantics (it may not be the current semantics) here otherwise it's hard for users to reason about the system behavior.

**Comment by clarng** [comment]
Is there a use case for a non-fault tolerant option ? Do node ids get re-used?

**Comment by clarng** [comment]
For collocation could they use PG?

**Comment by jjyao** [comment]
Ray node ids are never reused. You can use soft=False if you want to manually handle the node failure. In our codebases, there are "soft=False" usages.

PG is too heavyweight if you don't need gang scheduling: you need to know the total resources you need beforehand and those resources cannot be released gradually as tasks finish, they can only be used by others after pg is freed.

**Comment by ericl** [comment]
If we want well defined semantics, I think we should have explicit flags about the behaviors, such as spill_on_failure=True, spill_on_busy=True. Otherwise, I'd favor soft providing best-effort scheduling, defined as "try to put it here, but if not possible, fall back to other nodes".

**Comment by jjyao** [comment]
So here we are intentionally vague about "if not possible"? The public doc should be like "when soft is true, ray tries to schedule onto the target node but it's not guaranteed (we don't say when it's not guaranteed) and make sure your code can tolerate that"?

Note that this is a breaking change given our public doc now mentions the spill_on_failure behavior.

Personally I prefer adding an explicit flag to control the soft behavior so user can pick the one best for their use cases and we maintain the backward compatibility. This is also an indication that we should explore scheduling strategy as UDF more given it's hard to design one thing that fits all.

**Comment by stephanie-wang** [comment]
I think the ideal case would be for soft to just have one meaning, "spill on busy or failure", but we should only do this if the implementation for "on busy" is good enough. What @jjyao said about the shuffle use case is right, but I don't believe we necessarily need "spill on failure" semantics; I think it's just that the performance is more predictable with this policy. I'm not sure if there are other use cases that need "spill on failure" but not "spill on busy".

I'd say we should try out "spill on busy or failure" on the push-based shuffle release test and also add some CI tests for the behavior. If these results are good, we can change the semantics. Otherwise, we should probably just add a second flag.

**Comment by clarng** [comment]
Places where we are using node affinity - soft = True (aside from push based shuffle)

Data:
https://sourcegraph.com/github.com/ray-project/ray@master/-/blob/python/ray/data/_internal/execution/operators/map_operator.py?L154

(this is where this PR is coming from?)

https://sourcegraph.com/github.com/ray-project/ray@master/-/blob/python/ray/data/_internal/execution/autoscaling_requester.py?L98

Looks fine to me but I'll let @ericl etc decide otherwise

Serve:
https://sourcegraph.com/github.com/ray-project/ray@master/-/blob/python/ray/serve/_private/api.py?L199

https://sourcegraph.com/github.com/ray-project/ray@master/-/blob/python/ray/serve/controller.py?L1015

Seems fine to me to schedule to non-head if head is unavailable, can someone from Serve confirm?
@edoakes @sihanwang41

**Comment by ericl** [comment]
I checked all the call sites and they look fine for both Serve and Data.

**Comment by edoakes** [comment]
Fine for serve

**Comment by rkooo567** [comment]
> Personally I prefer adding an explicit flag to control the soft behavior so user can pick the one best for their use cases and we maintain the backward compatibility. This is also an indication that we should explore scheduling strategy as UDF more given it's hard to design one thing that fits all.

So are we going to do as a follow up?

**Comment by jjyao** [comment]
Not planned unless we get complains from users.
