### ISSUE TITLE
[Core] Raylet becomes zomebie when the HA GCS restarts and the external storage loses the data

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#33854]
### What happened + What you expected to happen

When the external storage loses the data, all the raylet becomes the zombie raylet (it is alive, but it cannot connect to GCS and lives). The main root cause is that the GCS health check from raylet will succeed (because channel is healthy as GCS is alive), but GCS doesn't have the membership information of the raylet, so it won't communicate to it. All the health check of resource broadcasting won't be communicated to this node because the node is dead.

Since GCS HA assumes the backing storage won't lose the data, there's no "fix" we can do in this problem. However, we should fail more loudly in this scenario. More specifically, we need to do the following action items; 

- Fix the behavior so the raylet won’t become a zombie if it connects to a GCS that it isn’t actually registered to
- Improve the logging across the board to make it easier to debug these things

cc @iycheng 

### Versions / Dependencies

master

### Reproduction script

remove data from redis and restart GCS. Worker node raylet should be killed. 

### Issue Severity

Low: It annoys or frustrates me.

**Comment by clarng** [comment]
perhaps @iycheng should triage this one/

**Comment by iycheng** [comment]
Instance leak is critical for all cases, so add it as a release blocker.

To recover the data loss is not an easy job (metadata lose is always a disaster). The priority here is to make sure in all cases no node is leaked even because data is lost.

I'm going to make GCS send signal to the Raylet which it doesn't know to terminate it immediately.

In case of data loss, Serve actually also won't work. But this could be useful for debugging and avoid leaking in case of a bug. cc @edoakes @shrekris-anyscale
