### ISSUE TITLE
[Dashboard][Bug] When using an nginx proxy, the front-end may misspell the URL when accessing the log. 

### ISSUE THREAD

**Issue by Catch-Bull** [ray-project/ray#34043]
### What happened + What you expected to happen

In our use case, we need to access the dashboard in the online cluster through an nginx proxy from the intranet. We found that when accessing the log page under this scenario, the front-end would misspell the URL, resulting in a failure to load.

### Versions / Dependencies

ray: 2.3.0

### Reproduction script

In terminal No.1, we start a ray dashboard:
``` bash
python -c "import ray, time; ray.init(); time.sleep(3600)"
```
In terminal No.2, we start an nginx proxy:
``` bash
sudo nginx -s reload
```
here is my nginx.conf:
```

worker_processes  1;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    server {
        listen       80;
        server_name  localhost;
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        location /proxy:8625/ {
            proxy_set_header Host $host;
            proxy_set_header  X-Real-IP        $remote_addr;
            proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;

            rewrite ^/proxy:8625/(.*)$ /$1 break;
            proxy_pass http://127.0.0.1:8265;
        }
    }

    include servers/*;
}
```

You can see it by entering the address http://localhost/proxy:8625/#/new/logs in your browser:
![image](https://user-images.githubusercontent.com/11995469/229780483-1a666c2e-cc0f-499b-a421-34846ebb0ca4.png)
![image](https://user-images.githubusercontent.com/11995469/229780834-8ab3a52f-60bf-4f6c-905d-40ab4b7b2d4e.png)

I think it may be caused by this "if" statement.

![image](https://user-images.githubusercontent.com/11995469/229782084-c2876801-ea36-446f-9d68-b1c7143adc4a.png)

### Issue Severity

None

**Comment by architkulkarni** [comment]
@Catch-Bull Thanks for catching this, would you be willing to file a PR? Will defer to @alanwguo on the details of the dashbaord frontend code.

**Comment by Catch-Bull** [comment]
> @Catch-Bull Thanks for catching this, would you be willing to file a PR? Will defer to @alanwguo on the details of the dashbaord frontend code.

@architkulkarni In my opinion, the function `getLogDetail` should be deleted, but I don't know the context of this function, and I don't know when this function will come into effect.

**Comment by Catch-Bull** [comment]
@architkulkarni I deleted this "if" statement, and it works.

**Comment by alanwguo** [comment]
@Catch-Bull What's the full url of the `log_proxy` that is being sent? Your screenshot cut it off.

**Comment by alanwguo** [comment]
I think the if statement logic is necessary for browsing files in folders to work.

I think the issue is that the logic assumes there is no slashes in the host name. 
In fact, it seems like that's not even a valid hostname according to DNS specs: https://stackoverflow.com/questions/3523028/valid-characters-of-a-hostname

These are guesses though. Having the `log_proxy` url will help me understand the behavior that is going on.

**Comment by Catch-Bull** [comment]
> @Catch-Bull What's the full url of the `log_proxy` that is being sent? Your screenshot cut it off.

@alanwguo the full url: http://localhost/proxy:8625/log_proxy?url=%2F127.0.0.1%3A52365%2Flogs

it seems %2F127.0.0.1%3A52365%2Flogs is an invalid URL (host is empty)

**Comment by Catch-Bull** [comment]
> It's difficult for me to repro the issue because I don't know how I can add a slash to the hostname for my ray cluster.
> 
> Can you log the `host` and `path` and `url` values before this line: [`master`/dashboard/client/src/pages/log/Logs.tsx#L81](https://github.com/ray-project/ray/blob/master/dashboard/client/src/pages/log/Logs.tsx?rgh-link-date=2023-04-11T17%3A31%3A27Z#L81)
> 
> and post it in this thread?

I add some breakpoint:
![image](https://user-images.githubusercontent.com/11995469/231438359-3a3001e9-b664-4ec5-84ea-38c497954177.png)

**Comment by Catch-Bull** [comment]
> I don't know how I can add a slash to the hostname for my ray cluster.

you can try Nginx on your Macbook with my Nginx config.

**Comment by alanwguo** [comment]
Okay. I'm not sure what this code is used for. In most cases `window.location.pathname` should be null since we use "hash-based routing". Everything after `#` is not considered part of the pathname so in all cases pathname should just be '/' and this if statement is not entered.

Because you have the `/` in the host name, the browser believes `/proxy:8625/log_proxy` is the pathname and goes through that code you highlighted before. I don't think this is a normal usecase for users and since this if statement seems to only impact your case, I'm okay if we just delete that if statement.
