### ISSUE TITLE
[tune] Metrics not reported after time budget expires?

### ISSUE THREAD

**Issue by ahah-figure** [ray-project/ray#34136]
### What happened + What you expected to happen

If a trial completes after the allotted time budget, and I only report the metric at the end of the trial, then `tune.report` does not seem to actually report the metric. When the budget gets hit, I expected the trials to either be [1] killed or [2] allowed to run to completion, but I think something between the two extremes happen. 

In the attached script, I have a time budget of 5 seconds, and each objective function takes greater than 5 seconds to run. The `optimize` function runs without error, and each objective function prints "before report" but no objective function prints "after report". Also, `optimize` gives the following warning:  "Could not find best trial. Did you pass the correct `metric` parameter?". So it seems like after I hit the budget, any call to `tune` interrupts the trial, and nothing runs after that. If it helps, think of the while loop inside `objective` as a function that trains a neural network with early stopping.

If this behavior is intentional, what's the best way to
1. Allow all trials to be killed as soon as we hit the budget? I think I'm looking for something like `tune.no_op()`, which I would call inside the while loop of `objective`.
2. Allow existing trials to run to completion when we hit the budget?

Thanks.

### Versions / Dependencies

* ray 2.2.0
* python 3.8
* ubuntu 20.04.06

### Reproduction script

```python
from typing import Callable

from ray import tune
from ray.tune.analysis.experiment_analysis import ExperimentAnalysis
from ray.tune.search.hyperopt import HyperOptSearch

BUDGET = 5
METRIC = "lr"
MODE = "max"


def objective(lr: float):
    """
    Objective function that takes longer than BUDGET to complete.
    """
    start = time.time()
    while time.time() - start < 1.25*BUDGET:
        time.sleep(0.1)
    print("before report")
    tune.report(lr=lr)
    print("after report")


def optimize(fcn: Callable[[float], None]) -> ExperimentAnalysis:
    param_space = {"lr": tune.loguniform(1e-3, 1e-1)}
    hp_search = HyperOptSearch(metric=METRIC, mode=MODE)
    analysis = tune.run(
        fcn,
        config=param_space,
        num_samples=1000,
        search_alg=hp_search,
        metric=METRIC,
        mode=MODE,
        time_budget_s=BUDGET
    )
    return analysis


def main():
    a = optimize(objective)
    assert a.best_trial is None


if __name__ == "__main__":
    main()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
`time_budget_s` is nothing special other than a `Stopper` that basically tells the Tune driver process to *start* stopping all ongoing trials and not schedule any more trials. 
In this case, notice that `objective ` are running as a remote function, that basically does its own thing. Once in a while it will report back to the Tune driver process with some metrics. This is when the communication between Tune driver and remote function happens. If at this time, the tune driver already knows that the trial should be killed, it will not process its metrics and just directly shuts it down. Note this time could have passed the original `time_budget_s`, since during sleeping (or training, doing heavy work) there is generally no way for driver to interrupt. A little disclaimer, we do have a force kill option if the driver waits for stopping a remote function for too long. 

Also `time_budget_s` treats all existing trials the same - there is no differentiation between running ones and not yet scheduled ones. Everything is stopped as soon as possible.

**Comment by ahah-figure** [comment]
Thanks. Is `tune.report` the only way to trigger communication between the driver and remote function? For example, say

* I'm maximizing some quantity `x` whose floor is 0
* I don't know exactly when I'll be able to see `x` next

Then should I intermittently call `tune.report(-1)` in order to ensure that remote functions get shut down as quickly as possible and `tune` ignores any partial results?
