### ISSUE TITLE
[Core|Serve] Passing two serve handles to actor hangs in pending_creation

### ISSUE THREAD

**Issue by Joshuaalbert** [ray-project/ray#34589]
### What happened + What you expected to happen

I came across this several times throughout the past year in various forms, however I had never narrowed it down to a single reproducible script. Previously, I worked around it. It would manifest as actors staying in PENDING_CREATION status. However, now with the help of @shrekris-anyscale it's reduced to a simple example. Passing two serve handles (async or sync) to an actor init causes the actor to hang.

Note: a workaround now is to create the handles inside the actor rather than passing them in.

### Versions / Dependencies

ray 2.2.0
python 3.10.8

### Reproduction script
```python
import logging

import ray
from ray import serve
from ray.serve.handle import RayServeHandle

logger = logging.getLogger('ray')


@serve.deployment(route_prefix=None, name="foo")
class Foo:
    def __init__(self):
        logger.info('foo started')


@serve.deployment(route_prefix=None, name="bar")
class Bar:
    def __init__(self):
        logger.info('bar started')


@ray.remote(num_cpus=0)
class Baz:
    def __init__(self, handle1: RayServeHandle):
        self.handle1 = handle1
        logger.info("Done Baz init")

    def check_health(self):
        logger.info("Baz is up!")
        return


@ray.remote(num_cpus=0)
class Qux:
    def __init__(self, handle1: RayServeHandle, handle2: RayServeHandle):
        self.handle1 = handle1
        self.handle2 = handle2
        logger.info("Done Qux init")

    def check_health(self):
        logger.info('Qux is up!')
        return


if __name__ == '__main__':
    ray.init(address='auto')
    serve.start()

    Foo.deploy()
    Bar.deploy()
    
    # Passing one handle is fine
    baz = Baz.remote(Foo.get_handle())
    ray.get(baz.check_health.remote())

    # Passing two handles leaves the actor in PENDING_CREATION
    qux = Qux.remote(Foo.get_handle(), Bar.get_handle())
    ray.get(qux.check_health.remote())
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by shrekris-anyscale** [comment]
I repro'd this issue on Ray 2.0:

```python
import logging

import ray
from ray import serve
from ray.serve.handle import RayServeHandle

logger = logging.getLogger('ray')


@serve.deployment(route_prefix=None, name="foo")
class Foo:
    def __init__(self):
        logger.info('foo started')

foo_graph = Foo.bind()


@serve.deployment(route_prefix=None, name="bar")
class Bar:
    def __init__(self):
        logger.info('bar started')


bar_graph = Bar.bind()


@ray.remote(num_cpus=0)
class Baz:
    def __init__(self, handle1: RayServeHandle):
        self.handle1 = handle1
        logger.info("Done Baz init")

    def check_health(self):
        logger.info("Baz is up!")
        return


@ray.remote(num_cpus=0)
class Qux:
    def __init__(self, handle1: RayServeHandle, handle2: RayServeHandle):
        self.handle1 = handle1
        self.handle2 = handle2
        logger.info("Done Qux init")

    def check_health(self):
        logger.info('Qux is up!')
        return


if __name__ == '__main__':
    foo_handle = serve.run(foo_graph, name="foo", route_prefix="/foo")
    bar_handle = serve.run(bar_graph, name="bar", route_prefix="/bar")
    
    # Passing one handle is fine
    baz = Baz.remote(foo_handle)
    ray.get(baz.check_health.remote())

    # Passing two handles leaves the actor in PENDING_CREATION
    qux = Qux.remote(foo_handle, bar_handle)
    ray.get(qux.check_health.remote())
```

**Comment by shrekris-anyscale** [comment]
Also repro'd using tasks:

```python
import logging

import ray
from ray import serve
from ray.serve.handle import RayServeHandle

logger = logging.getLogger('ray')


@serve.deployment(route_prefix=None, name="foo")
class Foo:
    def __init__(self):
        logger.info('foo started')

foo_graph = Foo.bind()


@serve.deployment(route_prefix=None, name="bar")
class Bar:
    def __init__(self):
        logger.info('bar started')


bar_graph = Bar.bind()


@ray.remote(num_cpus=0)
def quux(handle1: RayServeHandle):
    logger.info("quux is running!")
    return

@ray.remote(num_cpus=0)
def corge(handle1: RayServeHandle, handle2: RayServeHandle):
    logger.info("corge is running!")
    return


if __name__ == '__main__':
    foo_handle = serve.run(foo_graph, name="foo", route_prefix="/foo")
    bar_handle = serve.run(bar_graph, name="bar", route_prefix="/bar")
    
    # Passing one handle is fine
    ray.get(quux.remote(foo_handle))

    # Passing two handles leaves the task hanging
    ray.get(corge.remote(foo_handle, bar_handle))
```

**Comment by shrekris-anyscale** [comment]
I pair debugged the issue with @edoakes and @rkooo567. Based on our investigation so far, it looks like the issue is related to the [`LongPollClient`](https://github.com/ray-project/ray/blob/22d935d64edb8d7bff18accb417b3299c21ca9dd/python/ray/serve/_private/router.py#L297-L306) in the [`Router`](https://github.com/ray-project/ray/blob/22d935d64edb8d7bff18accb417b3299c21ca9dd/python/ray/serve/_private/router.py#L274).

We noticed that when 2 `RayServeHandles` are passed into a task or actor, the task/actor successfully deserializes the first handle, but the task/actor hangs when it tries to deserialize the second one. Specifically, it hangs when attempting to run the `ray.get()` call on [this line](https://github.com/ray-project/ray/blob/22d935d64edb8d7bff18accb417b3299c21ca9dd/python/ray/serve/handle.py#L148). Based on some logging that we added, it seems that the entire event loop was blocked while processing the task/actor's dependencies.

When the [`RayServeHandle`](https://github.com/ray-project/ray/blob/22d935d64edb8d7bff18accb417b3299c21ca9dd/python/ray/serve/handle.py#L78) is deserialized to start the actor or the task that its passed into, the handle's [`__init__`](https://github.com/ray-project/ray/blob/22d935d64edb8d7bff18accb417b3299c21ca9dd/python/ray/serve/handle.py#L118) method is called, which starts a new [`Router`](https://github.com/ray-project/ray/blob/22d935d64edb8d7bff18accb417b3299c21ca9dd/python/ray/serve/handle.py#L145). When we tried running passing in two handles and not running that line, the task/actor succeeded.

The current hypothesis is that creating the `LongPollClient` somehow blocks the event loop. @rkooo567 and I will continue debugging later this week.

**Comment by edoakes** [comment]
Nice progress. One suggestion is to enable `asyncio` debug mode, might help indicate what's blocking the loop:
https://docs.python.org/3/library/asyncio-dev.html#debug-mode

**Comment by shrekris-anyscale** [comment]
> One suggestion is to enable asyncio debug mode, might help indicate what's blocking the loop

Thanks, we can take a look at that. Due to bandwidth constraints, @rkooo567 and I will pick this issue up again later next week.
