### ISSUE TITLE
Map of evicted objects in the object manager grows forever

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#3470]
### System information
- **Ray version**: 0.6

### Describe the problem
The object table is stored as a log of addition and deletion entries per object. Since the log is implemented with a redis zset, the entries have to be unique, so each node keeps track of how many times a particular object has been evicted so far in `ObjectDirectory::object_evictions_`. Unfortunately, this means that this data structure will grow forever, since there is no GC. We should change this to remove the data structure and just make entries unique with a random ID, for example.

### Source code / logs
You can track the size of the map in the debug state, under `ObjectDirectory`, then ` - num eviction entries`.

**Comment by ericl** [comment]
There's also the `local_objects_` map in the task dependency manager, which is also around the same size in debug state.

**Comment by robertnishihara** [comment]
Looking at https://redis.io/topics/modules-intro the "List type API" header suggests that lists may now be available within Redis modules.

You can use

```
int RedisModule_ListPush(RedisModuleKey *key, int where, RedisModuleString *ele);
RedisModuleString *RedisModule_ListPop(RedisModuleKey *key, int where);
```

So if we can just get rid of `ZSET` then that should just solve the problem, right? If I remember correctly, we're only using `ZSET` because `LIST` wasn't available before. See also https://github.com/ray-project/ray/issues/3336. Also we had to work around the same issue in https://github.com/ray-project/ray/pull/3316, so when we fix this issue we should go back and clean that up as well.

**Comment by ericl** [comment]
> entries unique with a random ID

Does this mean using random IDs would also work?

**Comment by stephanie-wang** [comment]
> > entries unique with a random ID
> 
> Does this mean using random IDs would also work?

Yeah, that's probably the quickest solution for now. We can add a field to the object table entry that we set with a random value.
