### ISSUE TITLE
[Core] Raylets can communicate to the wrong GCS when GCS is restarted. 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#34763]
### What happened + What you expected to happen

Currently, when raylets cannot connect to GCS, it tries to reconnect to the same address for 60 seconds. 

This will work if we use the HA Ray (that has persistent storage behind it). But if we restart a GCS at the same address and port (e.g., ray stop && ray start), the raylets can connect to the wrong GCS and communicate with it. 

In the past, this was handled by the heartbeat, but we changed it to a push based from GCS. We replaced the membership checking to a separate RPC that's sent every 60 seconds, but 60 seconds are too long, and it can easily corrupt GCS while raylets are keep and running. 

### Versions / Dependencies

master

### Reproduction script

Restart GCS when raylet is alive. 

### Issue Severity

None

**Comment by jjyao** [comment]
For non-FT Ray, when GCS is restarted, it's a new Ray cluster so it should just ignore the messages from old raylets. What's the issue here? Why is there a corruption?

**Comment by iycheng** [comment]
More details for this issue and the solutions.

The potential risk comes from there is no mechanism preventing un-expecting gRPC access to the GCS. This usually happens in failure cases, for example, user `ray stop` and then `ray start` but GCS is not backed by a Redis, and the existing Raylet or CoreWorkers might write to GCS. This is bad for the correctness, especially given that we'd like to support ray stop and ray start in workspace.
Another thing is about how to fail the cluster faster, which is orthogonal to this thread.

## Potential solutions:

Metadata should be exchanged between GCS and all RPC clients. GCS needs to check the metadata to see whether it comes from the client it recognize.

- gRPC [link](https://grpc.github.io/grpc/cpp/classgrpc_1_1_client_context.html)
- client call [link](https://sourcegraph.com/github.com/ray-project/ray@master/-/blob/src/ray/rpc/client_call.h)

It means for each client call, the session_token will be added to the metadata. For the server side, it'll check the token to see whether it's the same as it's own ones. If it's not it should return failure immediately.

## How to generate the token

The token can be generated when GCS started. It'll read from the StoreClient and if it doesn't exist, generate one, otherwise, use it.

Token will be passed to Raylet when Raylet is registered to the GCS. And token will be appended to worker start cmd.

- raylet start worker cmd entry point `python/ray/_private/services.py`. An placeholder should be put there and it'll be replaced during runtime.


GCS client should add the token to context automatically [link](https://github.com/ray-project/ray/blob/master/src/ray/gcs/gcs_client/gcs_client.h#L66)


## Backward compatibility

There are multiple places accessing GCS (dashboard/raylet/autoscaler/core worker/...). We won't be able to update them all at the once especially given there are production workload.

We shall start with cpp workloads first and then revisit the python workload, that means, we'll start with raylet + core worker first then autoscaler and dashboard.

**Comment by jjyao** [comment]
Got it. Instead of token, can we just use node id?

We probably don't need to discuss here. Are we going to have a one pager design for this?

**Comment by iycheng** [comment]
@jjyao node id makes things harder. For example, not all gcs client has node id. Also, RPC layer is below the GCS, it's not good idea to couple the node id concept with RPC layer.

> We probably don't need to discuss here. Are we going to have a one pager design for this

Do you think anything missing in the comment above? I can just add it there.

**Comment by iycheng** [comment]
GCS client:

- Raylet: GcsClient (cpp)
- python worker - Core Worker (GcsClient cpp)
- python worker - python side (GcsClient python???) : This might have been deprecated in Phillip's work of moving grpcio away from python worker.
- dashboard - GcsClient python (it uses aio client)
- autoscaler - GcsClient python (aio ???)
- third party services (??)

**Comment by scv119** [comment]
- The most basic protocol is to make sure all parties in the ray cluster are talking about the same cluster_id, and drop the message if the communicating parties disagrees about the cluster_id.
- For implementation, we can either enforce that inside the communication layer (backed in grpc) or application layer (less ideal). 
- Starting from the basic solution you might able to optimize unnecessary cluster_id if the connection is already established.

**Comment by rkooo567** [comment]
Is this going to be merged soon?

**Comment by vitsai** [comment]
Plan is to merge it by Monday. There is still a deadlock in some of the tests.
