### ISSUE TITLE
[Core][Benchmark] Stress test many tasks + stage 2 avg iteration time latency seems to regress

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#34827]
### What happened + What you expected to happen

<img width="503" alt="Screen Shot 2023-04-27 at 7 04 04 AM" src="https://user-images.githubusercontent.com/18510752/234886495-1919fe48-681c-4b64-a9c4-fbd53142565c.png">

<img width="474" alt="Screen Shot 2023-04-27 at 7 04 09 AM" src="https://user-images.githubusercontent.com/18510752/234886517-3b887c51-6341-40f1-b7aa-823aba083cf0.png">

I suspect there might be regressions in the worker startup time again. But I think the data point is a bit small to confirm it. I will wait for a few days and bisect if the trend lasts

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by jjyao** [comment]
It's just variance since it's back to normal now.
<img width="455" alt="Screenshot 2023-05-01 at 1 22 16 PM" src="https://user-images.githubusercontent.com/898023/235524568-505299f5-79fe-41ab-8d36-21e85745b1b5.png">
<img width="454" alt="Screenshot 2023-05-01 at 1 22 08 PM" src="https://user-images.githubusercontent.com/898023/235524578-aac023f3-c9be-4f94-a519-247514c2640c.png">
