### ISSUE TITLE
[Data] `Datastream` repr is slow

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#35071]
### What happened + What you expected to happen

I tried to read MNIST into a Datastream and inspect the result, but it took more than two minutes for `__repr__` to complete.

```
>>> import ray
>>> ds = ray.data.read_images("s3://anonymous@air-example-data/mnist")
>>> ds  # This statement took 138.96s to run
Dataset(
   num_blocks=16,
   num_rows=60000,
   schema={image: ArrowTensorType(shape=(28, 28), dtype=uint8)}
)
```

### Versions / Dependencies

Ray: 4479f66d4db967d3c9dd0af2572061276ba926ba

### Reproduction script

See above.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by amogkam** [comment]
this is the stack that's taking a long time 

```
Thread 0x104870580 (idle): "MainThread"
    get_objects (ray/_private/worker.py:742)
    get (ray/_private/worker.py:2528)
    wrapper (ray/_private/client_mode_hook.py:99)
    auto_init_wrapper (ray/_private/auto_init_hook.py:18)
    ensure_metadata_for_first_block (ray/data/_internal/lazy_block_list.py:395)
    _get_unified_blocks_schema (ray/data/_internal/plan.py:420)
    schema (ray/data/_internal/plan.py:404)
    get_plan_as_string (ray/data/_internal/plan.py:194)
    __repr__ (ray/data/datastream.py:4291)
    <module> (<stdin>:1)
```

**Comment by amogkam** [comment]
we need to pushdown the schema to within the datasource rather than executing an entire block

**Comment by raulchen** [comment]
The reason is because in `ensure_metadata_for_first_block`, we need to read the first block. Currently we auto determine the number of files in one block based on the total size (512MB by default). In this data set, the files are small. So one block will have 2500 files. There are a few ways that can solve this issue:
1. Push down the limit to the data source. 
2. Batch-access the files in one block.
3. Limit the number of files per block.

(1) is already a ongoing work. I'll look into (2) and decide if we need (3).

**Comment by c21** [comment]
Should be able to close after https://github.com/ray-project/ray/pull/36740 is merged

**Comment by scottjlee** [comment]
It looks like `ds.__repr__()` still takes a long time for the above. However, i'm not sure if this is due to the `schema()`  implementation itself, because even `ds.take(1)` will take a very long time. I just ran `ds` and `ds.take(1)` side by side, and they take almost the same amount of time (several minutes). 

@raulchen @c21 we may need (2), especially because we removed limit pushdown for Ray 2.6. Thoughts?

**Comment by amogkam** [comment]
There’s still no datasource push down right? It’s still going to be slow if the entire first block needs to be executed.

**Comment by scottjlee** [comment]
Right, this will still be reading in the first block, so I think we will need some way to access files for a block in batches in order to avoid reading in a large number of files to populate the first block.

Some additional context: we had limit pushdown implemented, but had to revert because we still need to discuss some additional topics around enforcing number of input rows == number of output rows for Map/MapBatches ops. Hoping to get this in for Ray 2.7 along with the other changes to be discussed.

**Comment by raulchen** [comment]
Note. With the new `schema` optimization, `repr` is slow only when the read blocks are too large. This can be optimized in 2 ways:
- streaming generator.
- integrate limit with the source read tasks. 

The latter requires a big change and is unlikely to be done by 2.6. I'm going to try the former.

**Comment by anyscalesam** [comment]
Both should be done - @bveeramani can you confirm integration limits have been implemeneted?

**Comment by bveeramani** [comment]
It now takes 16.64s down from 138.9s. I'll close the issue, but ideally, we want `repr` to be instant.
