### ISSUE TITLE
Deprecation for ray 2.2 still not deprecated

### ISSUE THREAD

**Issue by ollie-iterators** [ray-project/ray#35782]
### What happened + What you expected to happen

In "ray/python/ray/train/torch/train_loop_utils.py" there is a comment that says: "# TODO: Deprecation: Hard-deprecate args in Ray 2.2."

The current version of ray is 2.4

### Versions / Dependencies

main branch

### Reproduction script

Look at "ray/python/ray/train/torch/train_loop_utils.py"

### Issue Severity

Low: It annoys or frustrates me.

**Comment by enori** [comment]
Is it right only to correct `@PublicAPI(stability="beta")` to `@PublicAPI(stability="stable")` at line 74?
I want to send pullrequest about this issue. 

Thank you in advance!

**Comment by anyscalesam** [comment]
I think so - I'm pretty sure at this point we've deprecated that args as well. cc @matthewdeng  who might know more.

**Comment by matthewdeng** [comment]
This is already done. The args and TODO have both been removed.

**Comment by enori** [comment]
@matthewdeng 
This is a bug still remaining in the 2.4 version.

There will be situations where I will have to use the 2.4 version due to compatibility issues with other software. 
(I too would prefer to use the latest version...)
Therefore, I would like to have it fixed if possible.

Sorry for bothering you.
Thank you.
