### ISSUE TITLE
[<Ray component: Ray Train>] Mosaic trainer example needs num_classes in the ComposerClassifier

### ISSUE THREAD

**Issue by humzaiqbal** [ray-project/ray#35906]
### Description

In the [Ray Mosaic training docs](https://docs.ray.io/en/latest/train/api/doc/ray.train.mosaic.MosaicTrainer.html?highlight=trainer_init_config) the Composer classifier needs to have `num_classes` passed in as a parameter for it to be initialized properly. The line 
```
model = ComposerClassifier(ray.train.torch.prepare_model(model))
```
should be changed to 

```
model = ComposerClassifier(ray.train.torch.prepare_model(model), num_classes=10)
```
See [this line](https://github.com/mosaicml/composer/blob/eda66d78150190d26ef983d2b48335e9767d1d18/composer/models/tasks/classification.py#L80) for the specific error message

### Link

https://docs.ray.io/en/latest/train/api/doc/ray.train.mosaic.MosaicTrainer.html?highlight=trainer_init_config

**Comment by justinvyu** [comment]
This docstring example is actually working due to the the resnet model having a `num_classes` attribute.

See here:

https://github.com/mosaicml/composer/blob/eda66d78150190d26ef983d2b48335e9767d1d18/composer/models/tasks/classification.py#L72-L79

Did this not work for you with a different torch model?

**Comment by justinvyu** [comment]
Closing as this seems to be resolved
