### ISSUE TITLE
Release test rllib_multi_gpu_with_lstm_learning_tests.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#36207]
Release test rllib_multi_gpu_with_lstm_learning_tests.aws failed.
See https://buildkite.com/ray-project/release-tests-branch/builds/1770#018899d9-32a7-460b-8866-9a696d88211b for more details.
cc @rllib

	 -- created by ray-test-bot

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by ArturNiederfahrenhorst** [comment]
I looked into the logs and found that this is because we attemt to use the RL Module API in this test, which is, today, not ready. Same goes for the attention test. I will open a PR to fix this.

<img width="1523" alt="Screenshot 2023-06-21 at 21 40 09" src="https://github.com/ray-project/ray/assets/9356806/33b7d1a9-eaee-468f-8f43-440c4202f93a">

**Comment by can-anyscale** [comment]
Fixed by https://github.com/ray-project/ray/pull/36883. Close to unjail.

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/1855#01891a8d-b896-453b-abbb-2f172bfb6d7a
