### ISSUE TITLE
logging issue using PopulationBasedTraining

### ISSUE THREAD

**Issue by nebulaV** [ray-project/ray#3654]
The order of entries in the logging files (for all .json, .csv and tensorboard event files) is sometimes incorrect. For example, the following four entries of the result.json of a trial (among four trials) in an experiment with multiple GPUs:

{... "pid": 18517, "timestamp": 1545391452, "training_iteration": 26, "done": false, "time_since_restore": 12.159034013748169}
{... "pid": 18517, "timestamp": 1545391476, "training_iteration": 28, "done": false, "time_since_restore": 36.984612464904785}
{... "pid": 18517, "timestamp": 1545391489, "training_iteration": 29, "done": false, "time_since_restore": 49.600470542907715}
{... "pid": 18517, "timestamp": 1545391464, "training_iteration": 27, "done": false, "time_since_restore": 24.7634060382843}

where you could see the last line (training_iteration=27) appears in the wrong order. This will make the build-in visualisation (e.g. using tensorboard) look super weird...

Anyone has an idea why this happens and how to fix it?

**Comment by nebulaV** [comment]
Forget to say that some entries will be missing as well...

**Comment by ericl** [comment]
@arcelien I think you had some ideas on how to fix this? Essentially the issue is that when cloning the parameters of other trials, the iteration number is also being closed. This can sometimes lead to trials appearing to jump backwards or forwards in time if the current best performer is not at the present iteration.

**Comment by arcelien** [comment]
I think this is not a visualization bug, but a side-effect of this particular implementation of PBT.

In the current way, the entire trial is cloned, including iteration number. A benefit is that all trials are guaranteed to run for the same number of iterations. However, we do get this checkpoint backwards in time - and then checkpoint again effect.

Another way would be to save the old iteration number, which fixes this effect (also I think this is closer to the PBT described in the paper). This however, might lead to some trials running for more than others.

A third way could be to only run checkpointing when the last trial reaches a checkpoint interval, which allows all to clone to trials at the same iteration. This would be messier to implement, but should also fix the problem (and all trials run for the same number of iterations).

**Comment by timonbimon** [comment]
just wanted to add that i've been having the same problem of the iteration number sometimes getting out of order (I assume this happens if one trial finishes earlier than the others and then copies another trial that did not finish its current training_iteration?) 

for me this also not just a confusing logging issue but when ray tries to write a checkpoint for such a trial since it throws the following error

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 282, in _process_events
    self._checkpoint_if_needed(trial)
  File "/usr/local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 312, in _checkpoint_if_needed
    self.trial_executor.save(trial, storage=Checkpoint.DISK)
  File "/usr/local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 294, in save
    trial._checkpoint.value = ray.get(trial.runner.save.remote())
  File "/usr/local/lib/python3.6/site-packages/ray/worker.py", line 2386, in get
    raise value
ray.worker.RayTaskError: ray_MyTrainable:save() (pid=2286, host=f73b5828c5c5)
  File "/usr/local/lib/python3.6/site-packages/ray/tune/trainable.py", line 219, in save
    os.makedirs(checkpoint_dir)
  File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/log/classification/train:1-val:1_190106_214233/MyTrainable_6_learning_rate=0.0019402,no_weight=0.76646,partial_weight=0.29467,random_crop_lower_bound=0.76136,raw_weight=0.92_2019-01-06_21-42-34f9uk3eq8/checkpoint_6'

the easy fix would be to check if the directory exists before trying to create the new dir, but I also think it's cleaner to fix the underlying problem with trainables copying the iteration number when being restored.

my two cents would be to save the old iteration number instead (at least for my applications I'm not too worried about the different trials running for the same amount if iterations, I just want to find the best model possible with all the trials combined)

**Comment by richardliaw** [comment]
Hey Timon, this specific error for makedirs should be guarded already in
the latest snapshot of master:
https://ray.readthedocs.io/en/latest/installation.html

@nebulaV I think in your example, the only thing that may be an issue is
when PID<1>iter8 comes before PID<1>iter7. The fix is to make sure whatever
trial that is being invoked `reset_trial` upon should not have any trials
in flight.

@arcelien
> Another way would be to save the old iteration number, which fixes this
effect (also I think this is closer to the PBT described in the paper).
This however, might lead to some trials running for more than others.
I think having some trials run more than others is probably fine;
iterations going backward is probably worse.

**Comment by richardliaw** [comment]
This can be addressed with Sync PBT.
