### ISSUE TITLE
[Serve] Redeploying an application doesn't fetch the `runtime_env` again

### ISSUE THREAD

**Issue by ghpu** [ray-project/ray#36645]
### Description

I deploy my application using a runtime hosted in Google Cloud Storage.

```
runtime_env: {
  "pip": ["transformers", "torch"],
    "working_dir":"gs://[redacted]/python-package.zip",
}
```

If I modify the content of python-package.zip, and wnat to do a redeploy (serve deploy my_conf.yam) , the runtime_env is not fetched again.

Is htere a way to force reloading without destroying and redeploying the cluster ?

**Comment by shrekris-anyscale** [comment]
No, the `runtime_env` is downloaded when the Serve application is first launched on a particular node. You would need to redeploy the application or restart the cluster.

I recommend cross-posting best practices questions like this on the [Ray Discuss](https://discuss.ray.io/c/ray-air/ray-serve/6) forums. There are other Serve users there that can chime in.

**Comment by ghpu** [comment]
So maybe this is a bug then : when I redeploy the application, the runtime_env is not fetched again. My only solution is to restart the cluster :-(

**Comment by shrekris-anyscale** [comment]
Yes, that sounds like a bug. Let me reopen this issue.

**Comment by akshay-anyscale** [comment]
I believe this is expected if the uri doesn't change- https://docs.ray.io/en/master/serve/advanced-guides/inplace-updates.html . The safer way of using this is to update the uri (eg. with a commit id) instead of updating the code without updating the URI.

**Comment by ghpu** [comment]
But in this case, I have to generate a new deployment.yaml file everytime. It would be nice to have a flag to force update.

**Comment by shrekris-anyscale** [comment]
Could you try force-updating by adding an env var to your runtime_env and redeploying?

As @akshay-anyscale mentioned, however, ideally the URI should change each time. Otherwise, you could end up in an inconsistent state where old nodes have a previous version of the package and new nodes have a newer version. See [this section's](https://docs.ray.io/en/latest/ray-core/handling-dependencies.html#option-1-download-zip-quicker-to-implement-but-not-recommended-for-production-environments) warning for more info.

**Comment by ghpu** [comment]
Thanks for your answers. It makes sense, guess I have to convince my private CI/CD ops to adapt their ways.
