### ISSUE TITLE
[AIR output] Remove unnecessary result in the default output. 

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#36797]
### What happened + What you expected to happen

1. Shall we remove the detailed results of the last iteration at the end? This includes confusing concept like `trial_id`. It's also not very readable and useful to me. If people do want more info, this is something we should enable via customization support.
2. Similar to the #36791 , there is random output after the last result.

<img width="1254" alt="Screenshot 2023-06-24 at 11 31 22 AM" src="https://github.com/ray-project/ray/assets/9677264/6c98758d-0a44-4425-85ea-8282ef727512">

### Versions / Dependencies

nightly

### Reproduction script

xgboost training air get started example

### Issue Severity

Low: It annoys or frustrates me.

**Comment by krfricke** [comment]
> ### What happened + What you expected to happen
> 
>     1. Shall we remove the detailed results of the last iteration at the end? This includes confusing concept like `trial_id`. It's also not very readable and useful to me. If people do want more info, this is something we should enable via customization support.

This is a custom print in the training script from the quick start example:

```
print(result.metrics)
```

We can update the example to not print the metrics, but this is not happening automatically, so there is nothing to fix on the Ray Train side.

> 
>     2. Similar to the [[AIR output] make the best result of tune output more readable #36791](https://github.com/ray-project/ray/issues/36791) , there is random output after the last result.
> 

This is due to delayed log propagation of worker stdout/stderr logs from Ray core. Again, nothing we can address from our side. The specific log also indicates that it's mostly due to the toy example running extremely fast, so this shouldn't be a big concern in real-life settings.
