### ISSUE TITLE
how can we make sure the objects free up will not be used in future?

### ISSUE THREAD

**Issue by raopku** [ray-project/ray#368]
when i am trainning a RL agent. I found a log 
[INFO] (/home/dl/rao/ray/ray/src/plasma/eviction_policy.c:179) There is not enough space to create this object, so evicting 421 objects to free up 2878653024 bytes.

```
a = np.zeros((10000,10000))
col = []
for _ in xrange(1000000000):
     id = ray.put(a)
     col.append(id)
```

ray.get(col[0]) # maybe something wrong happened.

what is the memory cleanup strategy of Ray?

**Comment by robertnishihara** [comment]
On each node in the cluster, there is a single **object store** (we use the name **Plasma** to refer to the object store).

Whenever an object store becomes full, it simply evicts a bunch of objects (to free up about 20% of its memory).

If you later call `ray.get` on an object ID that corresponds to an object that has been evicted, then the task that created the object will be rerun to recreate the object.

There are currently a couple limitations here.

1. If the task that created the evicted object is nondeterministic, then when the task is rerun, it may produce a different result (a warning will be logged in this case).
2. If the object was not created by a task but rather was passed as an argument into a remote function or created by a call to `ray.put` on the driver process, it may not be recreated.

The advantage here is the simplicity (we've also experimented with tracking global reference counts). There are some limitations as well of course since we may have to reconstruct objects. Are you running into situations where objects you need later are being evicted?

**Comment by raopku** [comment]
I am just worried about that. No bugs were found.
In the algorithm of DQN, a memory replay is used. So a big memory store is needed. 
The data structure of a fixed length queue is adopted to store memory. How can we delete objects by ray's API? or how can we put a protection flag on some important objects to tell ray to give priority to deleting other objects.

**Comment by robertnishihara** [comment]
Currently with Ray's API, there is no way to delete objects. If you simply stop using an object, then it will be evicted at some point.

As a quick hack, if you want to protect an object, you can regularly access it (e.g., by calling `ray.get` on the object). The eviction proceeds by evicting the least recently used objects first, so if you recently accessed an object, it will be less likely to be evicted. However, this is more of a short-term hack than a real solution.

One limitation is the fact that the object store is currently entirely in memory and so the number and sizes of the objects you have are limited by the amount of memory you have.

**Comment by raopku** [comment]
Thanks. I got your point.
