### ISSUE TITLE
Reproducibility of experimental results failed

### ISSUE THREAD

**Issue by JeremyLinky** [ray-project/ray#37029]
### What happened + What you expected to happen

I'm trying to ensure the reproducibility of experimental results by setting the same random seed, however, I found that with the same seed, sometimes the results are the same, sometimes different.

Through debugging, I found that numpy, random, torch, tf, and env in ray have all determined the seeds through `update_global_seed_if_necessary` and `_update_env_seed_if_necessary` respectively. Also, my num_works=0. I really don't know what to do to solve this bug.

### Versions / Dependencies

ray 1.1.0

### Reproduction script

None

### Issue Severity

High: It blocks me from completing my task.

**Comment by avnishn** [comment]
hi @JeremyLinky are you using ray 1.1 or ray 2.1? I can't guarantee it for 1.1, but for 2.1 I can guarantee for non-asynchronous algos that they are seed reproducible. One thing that may be causing your issue is that we have metrics reporting that can happen every n seconds, every n train timesteps, or every n sample timesteps. By default we do every n seconds, which can make reporting look non-deterministic. If you set the seconds reporting to 0, and instead use train or sample timesteps, you should see that the algorithms are seed reproducible.

I'm going to close this for now, but let me know if youre having any issues, and please update to ray 2.5.1 for the latest. We can try to diagnose issues for ray 2.x., but unfortunately not ray 1.x
