### ISSUE TITLE
[Core] Possible memory leak

### ISSUE THREAD

**Issue by erezinman** [ray-project/ray#37092]
### What happened + What you expected to happen

Using even a simple actor, subsequent calls increase memory rapidly. For example:

```
import ray

ray.init()

@ray.remote
class A:
    cntr = 0
   
    def print(self):
        print(self.cntr)
        self.cntr += 1

a = A.remote()
for i in range(100_000): 
    a.print.remote()
```

The process "ray::A" increases in size from ~40MiB to ~400MiB.

### Versions / Dependencies

Ray Version 2.5.0, Ubuntu 20.04.4 

### Reproduction script

Above

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by iycheng** [comment]
This seems like a memory fragmentation issue and not leak.

The memory increase is reasonable because the tasks are submitting really fast and it'll be queued locally to avoid crashing the actor.

Later the memory didn't drop because of either the fragmentation or the system doesn't release them.


Run the following script:

```
import ray

ray.init()

@ray.remote
class A:
    cntr = 0

    def print(self):
        print(self.cntr)
        self.cntr += 1

a = A.remote()
for i in range(200000):
    a.print.remote()
import time

import gc
while True:
    import time
    time.sleep(10)
    gc.collect()
```

with 

glibc/tcmalloc/jemalloc and the memory usage is 1.2g/1.1g/300mb

If you inject some gc or just slowdown the speed, none of them will show the memory increasing. Close this issue.

**Comment by iycheng** [comment]
Btw, the `ray::A` memory is very stable and not increased in my repo. Only the driver's memory increased. Testing with master branch.
