### ISSUE TITLE
[Data] Remove unhelpful actor pool warning

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#37108]
### Description

If you use `map_batches` with an `ActorPoolStrategy`, you can get this warning:

> 2023-07-03 13:13:04,354	WARNING actor_pool_map_operator.py:267 -- To ensure full parallelization across an actor pool of size 1, the specified batch size should be at most 0. Your configured batch size for this operator was 1.

We should remove it.

### Use case

This warning is confusing.

**Comment by Tanmoy037** [comment]
I want to try this, please assign this to me.

**Comment by bveeramani** [comment]
@Tanmoy037 go for it!

**Comment by Sai-Suraj-27** [comment]
@bveeramani sir, I want to fix this quickly, I see that the warning is generated from 
https://github.com/ray-project/ray/blob/375d0b04899c4948a46fafd885195caf8b5213d2/python/ray/data/_internal/execution/operators/actor_pool_map_operator.py#L271
Is this issue still open? because I see that you have updated the warning message through this [PR](https://github.com/ray-project/ray/pull/37752).

**Comment by bveeramani** [comment]
@Sai-Suraj-27 ah, good catch. We should probably close the issue. Thanks!
