### ISSUE TITLE
[Debugger][Python interface: ray.util.rpdb.py>] Ray debug error on Windows

### ISSUE THREAD

**Issue by chenhaox** [ray-project/ray#37145]
### What happened + What you expected to happen

# What happened + What you expected to happen 
Dear developers,

When I am running `ray debug` on the Windows, I get the following error:
![image](https://github.com/ray-project/ray/assets/3233768/8c5e4b6d-9401-4cf7-8d60-195fc3519d03)

After looking into the error place at https://github.com/ray-project/ray/blob/5a9cf52a667713d983283b9e4bd5304cc66e5001/python/ray/util/rpdb.py#L337-L339 and searching on the internet, I found that `select.select` does not accept file objects (like `sys.stdin`) on Windows (https://docs.python.org/3/library/select.html).

### Versions / Dependencies

ray: 2.5.1
python: 3.9
Windows 11

### Reproduction script

Testing script:
```
import ray


@ray.remote
def test():
    for i in range(100):
        breakpoint()
        print("TEST")


def main():
    ray.init(_node_ip_address='xxxxx', )

    ray.get(test.remote())

if __name__ == '__main__':
    main()
```
Script on my commend line:
``` ray debug```

### Issue Severity

None

**Comment by rkooo567** [comment]
cc @mattip can you guys take a look at this issue?

**Comment by mattip** [comment]
The design of this module is flawed for windows. At the top of the file, it credits [python-remote-pdb](https://github.com/ionelmc/python-remote-pdb), which itself is based on (maybe) [`rpdb`](https://github.com/tamentis/rpdb) but neither of those libraries have a `_connect_pdb_client` function. The change in `_connect_pdb_client()` to use `select.select()` was done 3 years ago by @pcmoritz in #13004 (at the time it was `connect_pdb_client()`) in order to support unicode (which allows such things as tab completion in the debugger).

I am not sure how to best refactor this code. One suggestion would be to "talk" to `stdin` via a socket as well?

**Comment by peytondmurray** [comment]
@rkooo567 or @jjyao, is :point_up: this something you'd still like to pursue? The fix here is somewhat unclear.

**Comment by anyscalesam** [comment]
@rkooo567 @jjyao can you advise here?

**Comment by jjyao** [comment]
I think this issue has relatively low priority. If QS has higher priorities, we should do those first.

**Comment by anyscalesam** [comment]
Let's tackel this after we get CI stable @mattip
