### ISSUE TITLE
[Core] Potential regression in `2.6.0/microbenchmark.json` `placement_group_create/removal`

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#37186]
From https://github.com/ray-project/ray/pull/37084

```
REGRESSION 9.83%: placement_group_create/removal (THROUGHPUT) regresses from 1088.4611425326907 to 981.4762218245539 (9.83%) in 2.6.0/microbenchmark.json
```

**Comment by xieus** [comment]
Assign to @cadedaniel tentatively.

**Comment by jjyao** [comment]
@rkooo567 Can you take this since @cadedaniel is busy with something else.

**Comment by rkooo567** [comment]
<img width="904" alt="Screen Shot 2023-07-13 at 11 15 48 AM" src="https://github.com/ray-project/ray/assets/18510752/612643d0-0cd0-480d-bfc8-7fd050209b9c">

This seems to be a noise. @bveeramani will rerun the test for verification.

**Comment by bveeramani** [comment]
Here's the result from this morning:
```
REGRESSION 9.95%: placement_group_create/removal (THROUGHPUT) regresses from 1088.4611425326907 to 980.1097176315758 (9.95%) in 2.6.0/microbenchmark.json
```

**Comment by rkooo567** [comment]
This is actually okay to close this issue due to 2 reasons.

1. This is not a performance-sensitive test. I think 980 is still pretty good for pg creation/removal.
2. The graph indicates the test result is noisy. It seems like the perf was also around 920 in ray 2.3, so I assume the result from 2.5 was just within a noise range.

cc @jjyao for the approval before I close the issue.

**Comment by bveeramani** [comment]
Sounds good to me!

**Comment by jjyao** [comment]
SGTM.
