### ISSUE TITLE
[Train] Shard all Input Datasets in Ray Train by default

### ISSUE THREAD

**Issue by woshiyyya** [ray-project/ray#37668]
### Description

Currently, Ray Train only shards the "train" datasets by default, leaving all other datasets unsharded. Users can [configure the `DataConfig`](https://docs.ray.io/en/latest/ray-air/check-ingest.html#migrating-from-the-legacy-datasetconfig-api) to shard these other datasets. 

This is not satisfactory because:
- Internal sharding behavior is inconsistent among different datasets.
- All N worker threads evaluate on the full validation dataset, which wastes computation and takes Nx longer time.

We should consider enabling dataset shading by default.

**Comment by YiranJing** [comment]
#### Common use case in Canva (PL model)
- Models have both `train` and `validation` datasets, and the trainer performs validation step on the **entire** validation dataset in **each** epoch following the training step.
- Some models also have a `test` dataset, which is evaluated after `trainer.fit()`.

#### Problem
Currently, the `validation` dataset is not shared by default, leading to longer execution times for each epoch as every worker performs validation on the full dataset simultaneously. This slowdown the training process and wastes resources. 

To address this issue, we need to add `data_config=DataConfig(datasets_to_split=["eval"])`. However, this can be confusing since the `train` dataset gets shared by default

#### Desired Behavior
- The `validation` dataset should be shared by default.
- The same configuration setup for both `train` and `validation` dataset sharding is required from the user side (reducing bugs and enhancing ease of understanding).
- The validation metric should be similar across `1` -> `N` workers.
