### ISSUE TITLE
[RLlib] Action masking is not working in Ray 2.6.1

### ISSUE THREAD

**Issue by nargizas** [ray-project/ray#37707]
### What happened + What you expected to happen

I am following [example on action masking](https://github.com/ray-project/ray/blob/master/rllib/examples/action_masking.py) to train an agent with PPO instead of APPO for the custom Gymanisum environment , where the set of legal actions changes from turn to turn. To do so I use [TorchActionMaskModel](https://github.com/ray-project/ray/blob/master/rllib/examples/models/action_mask_model.py). However, when using Ray 2.6.1 the custom model doesn't seem to initialize before the call of step() function, leading to the illegal action being used:

```
  File "C:\Users\...\.venv\lib\site-packages\ray\rllib\examples\env\action_mask_env.py", line 32, in step
    raise ValueError(
ValueError: Invalid action sent to env! valid_actions=[0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 0.
 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1.
 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 1. 1. 0.
 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1.
 0. 0. 0. 0.]
``` 

Downgrading to Ray 2.5.1 helped, though there was `ModuleNotFoundError: No module named 'tensorflow_probability'` like in #31327, which I resolved by manually fixing tfp import. 

### Versions / Dependencies

Ray 2.6.1
Python 3.9.13
OS Windows 10 Home

### Reproduction script

python -m venv .venv
source .venv/Scripts/activate
pip install "ray[rllib]" tensorflow torch
python .venv/Lib/site-packages/ray/rllib/examples/action_masking.py

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ArturNiederfahrenhorst** [comment]
@nargizas Thanks a lot for raising this!
I found multiple underlying issues:

1. The failures were not picked up by our CI because the error was not propagated
2. The example script should not work out of the box on master, because it is not compatible with RL Modules API (the default). We have to update the example for this case.
3. I could reproduce the issue you described with TF1. I've now ported the example to RL Modules and with TF2, everything runs smoothly.

If you can repro the issue with torch/tf2 with the upcoming nightly versions of RLlib or an upcoming release >=2.7, please let me know!
