### ISSUE TITLE
Ray crashes after unable to update Actor

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#3792]
This is an 8 hour long-running experiment on GCP, and Ray seems to crash halfway through.

(I don't have access to this environment).

This is using a fairly recent version of Ray.

## Logs
All ray logs here. The interesting things happen at 10:06 (in monitor.err), where the actor seems to die.
[ray (1).zip](https://github.com/ray-project/ray/files/2766455/ray.1.zip)

## Other notes 
There are multiple TODOs stemming from this issue:
1. Addressing this issue (or at least reproducing)
1. Graceful failure from Tune if Raylet dies (KeyError should be handled with some better error message, and a note about restarting an experiment should be output when this occurs)
2. GCP 403s should probably be caught and a more informative error can be provided.
3. Add stress-tests that are long-running jobs.

I don't think this is a one-off because a similar failure is reported here: https://groups.google.com/d/msg/ray-dev/E7rAGMDO3ZA/wVVepVnoGAAJ

cc @stephanie-wang 	@ericl @hartikainen

**Comment by stephanie-wang** [comment]
Do you have the logs for the other raylet nodes?

**Comment by hartikainen** [comment]
Do you mean the `/tmp/ray` on the workers?

**Comment by stephanie-wang** [comment]
Hmm, it's a little hard to debug without access to all of the logs. A few questions:
1. Is this the first time that an actor dies in the job?
2. Do you know why the actor dies (is it intentional)?
3. Is it possible to reproduce the error, but get logs from all the nodes? Ideally, with `DEBUG` logging in the backend.

Thanks!

**Comment by hartikainen** [comment]
1. I believe so, although I'm not 100% sure. @richardliaw can you confirm this?
2. Unsure why it dies. Not intentional at least.
3. I can try. How do I get the `DEBUG` logging from the backend? Just build ray with `debug` pip extra and run it normally?

**Comment by stephanie-wang** [comment]
Okay, thanks!

Hmm, unfortunately there isn't an easy way to turn on debug logging without building from source right now, but I'll an open an issue for that and it should be possible soon. If it's not too much trouble, it'd be helpful to get the other logs still, without debug level.

**Comment by hartikainen** [comment]
I can build it from source. How do I change the debug level for that?

**Comment by stephanie-wang** [comment]
You will have to change [this line](https://github.com/ray-project/ray/blob/3027dde3037af9924d9ee31533d6c525b30214c6/src/ray/raylet/main.cc#L20) to read `ray::RayLogLevel::DEBUG`. Also, sorry about the mess, but there are some lines that you will probably want to comment out because they'll obscure the logs: [here](https://github.com/ray-project/ray/blob/3027dde3037af9924d9ee31533d6c525b30214c6/src/ray/raylet/node_manager.cc#L254), [here](https://github.com/ray-project/ray/blob/3027dde3037af9924d9ee31533d6c525b30214c6/src/ray/raylet/node_manager.cc#L262) and [here](https://github.com/ray-project/ray/blob/3027dde3037af9924d9ee31533d6c525b30214c6/src/ray/raylet/node_manager.cc#L284).

**Comment by raulchen** [comment]
@stephanie-wang @hartikainen 
You can set env var `export RAY_BACKEND_LOG_LEVEL=debug` to turn on debugging log at runtime.
