### ISSUE TITLE
[docs] [docs infra] Finish Sphinx migration

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#37944]
### Description

The Sphinx migration has been started but it needs to be completed. https://github.com/ray-project/ray/pull/35073
cc: @max

**Comment by peytondmurray** [comment]
I'm working on this in stages so the PR doesn't get overwhelming, and because there's a couple of different things we need to to make the Sphinx upgrade smooth. I'll add to this checklist as I go:

- [ ] Remove unnecessary doc dependencies. External modules for which documentation isn't being hosted shouldn't need to be installed to build the docs (e.g. tensorflow, torch, etc should be mocked out with `autodoc_mock_modules`)
- [ ] Remove `doc/requirements-doc.txt` in favor of an official `ray[docs]` extra that lives in `python/setup.py`. Consolidating requirements will make future maintenance easier.
- [ ] Attempt an upgrade to the latest version of Sphinx and all Sphinx-related dependencies. The docs will likely be broken/look very different due to changes in `pydata-sphinx-theme` and `sphinx-book-theme`. Determine the work needed to get the docs into a presentable state given the new styles.

**Comment by peytondmurray** [comment]
A few more todo items:

- [ ] We are dropping `sphinx-external-toc`, so there are a bunch of orphaned pages; we need to build a new toctree with these pages included to be displayed at the landing page for the docs.
- [ ] Move the CSAT widget out of a custom template. There's a [`pydata-sphinx-theme` layout guide](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/layout.html) that shows where different things can be placed; the HTML for this can just be put in the sphinx configuration instead.
- [ ] Sort out syntax highlighting. In addition to pygments, we are also loading highlight.js in multiple places - without extra work highlight.js will not work for dark/light theme switches.
