### ISSUE TITLE
Following PEP8 style guide

### ISSUE THREAD

**Issue by wesm** [ray-project/ray#381]
To make it easier for other Python developers to get involved in Ray, I strongly recommend following PEP8 (https://www.python.org/dev/peps/pep-0008/) and possibly some of the advice from the Google style guide (https://google.github.io/styleguide/pyguide.html). You can use `flake8` to check your Python code for compliance with PEP8, and other code smells.

**Comment by robertnishihara** [comment]
Good point! We'll prioritize that.

**Comment by robertnishihara** [comment]
This is largely addressed by #387, though there is still a bit more work to be done.

1. Everything under `examples/` is currently not being linted.
2. We aren't checking indentation because `flake8` seems to only check for 4 space indentation and we are using 2 space indentation.
3. We may want to use more powerful tools like pylint to catch a different subset of style errors.

**Comment by wesm** [comment]
Too late to switch to 4 spaces? I admit that 2 spaces makes my eyes bleed a little bit

**Comment by robertnishihara** [comment]
It's certainly not too late. We copied TensorFlow's convention here, but maybe that would be a good change.

**Comment by wesm** [comment]
That's a legacy Google thing; they recently have gotten with the times https://google.github.io/styleguide/pyguide.html?showone=Indentation#Indentation, but I imagine old habits die hard on their once-internal projects

**Comment by pcmoritz** [comment]
Yeah, let's switch. It seems 4 spaces is the norm in Python, IPython/Jupyter even "enforces" it by marking things red if they are indented with 2 spaces. r spaces also make indentation errors easier to spot.

**Comment by robertnishihara** [comment]
Sounds good.
