### ISSUE TITLE
[Serve] Allow setting scheduling strategy 

### ISSUE THREAD

**Issue by smit-kiri** [ray-project/ray#38526]
### Description

We can [set scheduling strategy for Ray Actors](https://docs.ray.io/en/latest/ray-core/scheduling/index.html#ray-scheduling-strategies), but we're unable to set it for Serve deployments. It'll be good to allow this field as a part of `ray_actor_options`.

### Use case

In response to [this KubeRay bug](https://github.com/ray-project/kuberay/issues/1333), we want to set the scheduling strategy for our deployments to `SPREAD` to spread the deployment replicas among different nodes so the service stays available during a node disruption.

**Comment by edoakes** [comment]
@smit-kiri you can now set `max_replicas_per_node` to specify how much you'd like to spread your replicas. If you want a strict spread, set this to `1`.

**Comment by prd-tuong-nguyen** [comment]
@edoakes I believe that setting `max_replicas_per_node` to 1 is not the most effective solution. For instance, if I need to deploy 4 replicas but have configured `max_replicas_per_node` to 1, I would require 4 separate nodes. However, it's possible to deploy the replicas across just 2 nodes. The same issue arises if we set the minimum number of replicas to 2 while also enabling auto-scaling.

**Comment by prd-tuong-nguyen** [comment]
@edoakes  Thank you for your quick reply. here is my usecase
## Use Case:
Configuration: Minimum of 2 workers, each equipped with 24GB VRAM.
Additional Deployment: A Ray Serve application configured with {num_gpus = 0.1, min_replicas = 2, max_replicas = 8, auto_scaling = True}, requiring 2GB VRAM per replica.
## Behavior with max_replicas_per_node:
- max_replicas_per_node = 1:
  - At deployment, each worker contains one replica, meeting the initial requirement. However, during scaling, up to 8 workers may be required to handle all replicas.
- max_replicas_per_node = 2:
  - At deployment, two replicas might be placed on the same worker, which doesn't meet the expectation of spreading across workers.
## Expected Behavior:
At deployment, the two initial replicas should be placed on different workers.
During scaling, replicas should be evenly distributed across the two existing workers if resources are available.
