### ISSUE TITLE
[CI] `linux://python/ray/tests:test_placement_group` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#38726]
- e2c6fc5e36aeaa2a8ede83500a01b4992702033e FAILED [Buildkite :ray: core: python tests](https://buildkite.com/ray-project/postmerge/builds/220#018a1a12-8e06-4ada-ba00-71a7a1e25956)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_placement_group-END
....

**Comment by vitsai** [comment]
Took a quick look at this. `ray.get()` times out due to lock contention during auto-init when ray client connection is enabled. So, for some reason, `ray.init` is taking longer than 3 minutes.

 One specific failure here (`test_placement_ready`): https://buildkite.com/ray-project/oss-ci-build-branch/builds/6484

**Comment by rkooo567** [comment]
Is there a PR now? If ^ is the root cause, I think we dont need to mark it as a blocker (let's fix it as p0 in 29)
