### ISSUE TITLE
[serve][grpc] `gRPCOptions` using `logger.warning` for validation errors

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#39163]
https://github.com/ray-project/ray/blob/master/python/ray/serve/config.py#L827

These should raise exceptions to catch issues early (unless these are non-fatal errors, but they look like it to me).

**Comment by GeneDer** [comment]
Yea, my intention is just to notify users that there might be typos in the function paths they passed. Technically proxies shouldn't fail due to this. And if all the functions are unable to be imported, I would expect the proxy actor can still start HTTP proxy without gRPC proxy running. But can totally just raise the error and stop right there. Will patch it after other higher priority items!
