### ISSUE TITLE
[serve] Router unable to schedule any requests under CPU contention

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#39645]
In two recent issues, we saw the symptom that requests couldn't be scheduled due to the "get queue length" timeout in the router:

- https://github.com/ray-project/ray/issues/39643
- https://github.com/ray-project/ray/issues/39418

These each have separate root causes, but we should handle this case more gracefully to avoid the router getting completely "stuck." Two possible solutions:

- Introduce a backoff policy for this timeout. This could be shared with the existing backoff for selecting replicas or could be a separate backoff policy only for the case where these timeouts occur.
- Always run the router in a separate thread with its own asyncio loop. This will help in the case where the asyncio loop is clogged, but we may still see the issue under heavy CPU contention. This would also remove the difference between the "sync" and "async" handles case.

**Comment by alexeykudinkin** [comment]
> Introduce a backoff policy for this timeout. This could be shared with the existing backoff for selecting replicas or could be a separate backoff policy only for the case where these timeouts occur.

There are a few ways we can do load-shedding in this case, but i think more importantly we actually should start doing the _shedding_ part, meaning that after we exhausted N retries, Proxy should just fail the request and give way to the other ones (as opposed to retrying indefinitely)

> Always run the router in a separate thread with its own asyncio loop. This will help in the case where the asyncio loop is clogged, but we may still see the issue under heavy CPU contention. This would also remove the difference between the "sync" and "async" handles case.

Ideally, all I/O alas request/response handling should happen on a single evloop, anything else have to be offloaded. 

Splitting I/O handling b/w multiple loops is actually tricky -- since we don't control where callbacks are called (ie await's are continued), it would be tricky to separate it on per component basis.

**Comment by edoakes** [comment]
Was closed in https://github.com/ray-project/ray/pull/39827
