### ISSUE TITLE
[runtime env] Code to reproduce wheel download URLs is out of date

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#39842]
The current master wheel download URLs are at 

https://github.com/ray-project/ray/blob/bb892a6bd0224ab3ae11859268ddef01cbb68e71/doc/source/ray-overview/installation.rst?plain=1#L143-L173

This is the source of truth.  But the function `get_wheel_filename` which is used to reproduce these filenames in the Python code is out of sync with the truth:

https://github.com/ray-project/ray/blob/bb892a6bd0224ab3ae11859268ddef01cbb68e71/python/ray/_private/utils.py#L1384-L1435

- The code produces filenames with `universal` in certain cases, but there are no longer any such filenames
- The code says there aren't master wheels for M1 macs, but this is no longer true
- Possibly other issues

The downstream effect is that the "conda" field of runtime_env won't work on the nightly build in these cases.

We should fix the code to put it back in sync, and add a comment to `installation.rst` that links back to `get_wheel_filename` to help prevent them going out of sync again.

**Comment by lejara** [comment]
Hello!
Can i work on this?

**Comment by architkulkarni** [comment]
Absolutely! Let me know if you need any pointers

**Comment by architkulkarni** [comment]
We should also update https://github.com/ray-project/ray/blob/3735ba410ddfa63cc8516f69fa8b3997259a3f11/release/runtime_env_tests/workloads/wheel_urls.py in the same PR.

**Comment by lejara** [comment]
Okay, got two questions!

1
you mind elaborating on what https://github.com/ray-project/ray/blob/3735ba410ddfa63cc8516f69fa8b3997259a3f11/release/runtime_env_tests/workloads/wheel_urls.py  needs updating

I haven't spot an issue. Besides, it not checking all the URLs. it will only test those that are compatible to the architecture the code is running on. Since `get_release_wheel_url()` and `get_master_wheel_url()` will invoke `get_wheel_filename()` without specifying an architecture. So it will use ` platform.processor`.

**Comment by lejara** [comment]
2
I am not sure what to add in the comment for `installation.rst`.
Do you me to add a github link to `get_wheel_filename()` and note that it must be up to date if any new python version or  architecture is added?

**Comment by architkulkarni** [comment]
1. Ah you're right, maybe just update this test then: https://github.com/architkulkarni/ray/blob/9ab37bc295e4c63fb962ae12e1018d6246689134/python/ray/tests/test_runtime_env.py#L111 
2. Yeah, that would be good. Basically just a note for any person that updates installation.rst with new filenames, that they should go to get_wheel_filename and update it there too.

**Comment by lejara** [comment]
Sure thing. I can make those changes.

I personally think it would be better to keep a running list of links that can be used in python and turn `get_wheel_filename()` to a method that would find those names based on the provide arguments and would throw an error if that name does not exist.

That way any changes, like support of  a python version, would propagate automatically without the need of manual change. 

I am not familiar with this code base, so you might have your reasons. I just thought i would thrown in a suggestion

**Comment by architkulkarni** [comment]
That would indeed be better if you can get it working! Definitely want to avoid manual updates where possible.  I think the only requirement would be that it continues to render nicely as a table in the docs.

**Comment by lejara** [comment]
okay i can give it a shot.

How does this implementation sound

1. Move all existing wheel URLs in `installation.rst` to a `wheels.yaml` 
In this format
```yaml
- Linux Python 3.10 (x86_64): https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp310-cp310-manylinux2014_x86_64.whl
- Linux Python 3.9 (x86_64): https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp39-cp39-manylinux2014_x86_64.whl
- Linux Python 3.8 (x86_64): https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
# ....
```
_Not sure where to place the `wheels.yaml` file_

2. Create a sphinx extension that will replace the keyword ``` :wheellink:`Linux Python 3.10 (x86_64)` ``` to the required hyperlink with provided label
3.  Create a method in [utils.py](https://github.com/ray-project/ray/blob/bb892a6bd0224ab3ae11859268ddef01cbb68e71/python/ray/_private/utils.py) that will read and parse the `wheels.yaml` file. It will return the data as a `dict`
4. Refactor `get_wheel_filename()` such that it will use the provided arguments to find right link and return the filename

So for any new updates. They only update a person need to do are always in  `installation.rst` for formatting and `wheels.yaml` for the actual link

**Comment by lejara** [comment]
I could also expand the sphinx extension to render out the entire table. That way the only thing that would need updating is `wheels.yaml`

**Comment by architkulkarni** [comment]
I don't have experience with sphinx extensions, but if it works, your approach sounds great! You can make the call on where `wheels.yaml` should live, I don't think we have any strict guidelines here.

@aslonnie any concerns about the above approach? The summary of the problem this solves is that we have code to generate the wheel URLs for use by runtime_env downloading, but today it needs to be manually kept in sync with the actual wheel URLs.  (Not sure who manages the wheel uploads)

**Comment by aslonnie** [comment]
> As I recall the wheel filename is autogenerated by the build and we don't have control over it

we do have control, but the file name is conforming with the wheel path standard. the s3 path is just our own thing.

- for the `universal`, maybe just throw an exception?
- I feel that you can just fix the `m1` part and call it a day.

because it is python standard, it does not really change much over time. so I am not so worried about docs consistency. if we already use sphinx extension to generate docs, then it is fine. if it needs a lot of extra work and need to introduce many additional dependencies and set up to make it work, then I think it is probably an overkill.

the real issue is test coverage. like if we expect that `get_wheel_filename()` function to work on m1, then we should have test that cover that use case.


also.. IMO we should list unstable `3.0.0.dev0` in docs.. instead, should have a more formal "nightly" build, with date as release numbers, on a consistent git commit, with )(some) test results attached with it, and have a list of urls/filenames in the release.  -- but that is a longer discussion..

**Comment by lejara** [comment]
okay, make sense. ill go to my previous changes and make a pr.
