### ISSUE TITLE
Feature enhancement of `get` method?

### ISSUE THREAD

**Issue by zbarry** [ray-project/ray#3991]
I was wondering if it would make sense to enhance `get` to be something like the following:

```python
def get(thing: Union[ray.ObjectID, Any]):
    """ Helper func that can handle both actual data and Ray futures. """

    if isinstance(thing, ray.ObjectID):
        return ray.get(thing)

    return thing
```

In my particular use case, I'm working on creating a system which could call computational functions with or without spawning Ray tasks. In this scenario, it made sense for me to implement the above. This way, I don't have to worry nearly as much about tracking whether something is a future or actual data.

No idea if this would be something you'd want to refactor into `ray.get()`, though. Thoughts?

E: also, just discovered / started using Ray, and it's been great so far given how incredibly flexible and general purpose it is! Appreciate the effort that went into it.

E: above would need to handle the case where `thing` is an iterable of futures.

**Comment by zbarry** [comment]
Thinking about this while working with my own `.get()` wrapper, I think the variety of cases you could find yourself handling when dealing with iterables which may or may not contain futures might be difficult to make a robust, general-purpose function for. Going to retract this for now!

**Comment by robertnishihara** [comment]
Thanks @zbarry I'd prefer to omit this for now since it's easy enough to implement as a helper function. We have implemented a helper function that can take tuples/ndarrays/dictionaries instead of just lists, though I think there may be enough variety in the desired behavior that it's better to leave up to applications for now.

https://github.com/ray-project/ray/blob/c4182463f6a9bac0ec07c068e0fa6f508e650de5/python/ray/experimental/api.py#L9
