### ISSUE TITLE
[Core][GCS FT] The ray list jobs command experiences significant delays after the head Pod recovers from a failure

### ISSUE THREAD

**Issue by kevin85421** [ray-project/ray#39947]
### What happened + What you expected to happen

https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1695265415103039

### Versions / Dependencies

2.7.0

### Reproduction script

1. Create a RayCluster with GCS FT
2. Use `ray job submit` to submit some jobs
3. Delete the head Pod
4. Run `ray list jobs` in the head Pod after it recovers from the failure

I cannot reproduce this consistently. I need to try 10x times to make it happen.

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
@jonathan-anyscale debugged the issue.

Looks like https://github.com/ray-project/ray/pull/35188#pullrequestreview-1439885335 is exactly happening now.

Basically, when we get a "LIST JOB"  RPC to GCS, it does 2 things.

1. Get the data from Redis
2. Get the pending # of tasks from all alive drivers via RPC (NumPendingTasks)

And it is what's happening;
1. When a node is killed abruptly from k8s cluster, it doesn't clean up sockets properly (this is an expected behavior), and that causes RPC (NumPendingTasks) to be pending until the keepalive timeout reaches (2+ minutes). 
2. After 2+ minutes, NumPendingTasks replies with a failure (connection timeout OR infamous "failed to connect to all addresses", but the state API already failed (because it has 30 seconds timeout).

@jonathan-anyscale will make a simple write up by tomorrow, and let's discuss the right solution.
