### ISSUE TITLE
What is the greatest limitation of Ray?

### ISSUE THREAD

**Issue by raopku** [ray-project/ray#400]
I recently analyzed the architecture of ray. I found ray is a greate, simple and user friendly product. I even can not find a disadvantage of ray. But, I think all products have the trade-off.  What is limitation of Ray when using with deep learning or machine learning?
-

**Comment by robertnishihara** [comment]
Well, certain things become trickier given the task latency and throughput goals as well as the generality that we're targeting. Making intelligent scheduling decisions is harder because the decisions need to be made very quickly and without a full picture of the computation graph. Fault tolerance is harder because of the size of the computation graph and the stateful nature of actors.

**Comment by robertnishihara** [comment]
Closing this for now. Please reopen if you have more questions!
