### ISSUE TITLE
[Core] resources_dir should be passed to runtime env plugins

### ISSUE THREAD

**Issue by JoostvDoorn** [ray-project/ray#40144]
### Description

Custom RuntimeEnvPlugins should have access to resources_dir to put their runtime resources in the same place with other runtime resources. Existing plugins have a `__init__` that passes this directory. It might make sense to pass this resources_dir to the `__init__` of the plugin.

### Use case

I am using the (experimental) runtime env plugin system to implement a custom runtime environment logic. When developing this I noticed it has been difficult to access the resources_dir to store the runtime environment resources in the `/tmp/ray/session_2021-11-03_16-33-59_356303_41018/runtime_resources` path that is used by all the natively included plugins of ray. I previously used `ray.worker.global_worker.node.get_session_dir_path()` to get this path in ray 2.4, but testing in ray 2.7 showed that it doesn't work anymore. The `RuntimeEnvContext` object `resources_dir` also doesn't seem to contain the relevant value when creating the plugin.

**Comment by dayshah** [comment]
So the resources_dir in the runtime env context is actually deprecated now, so that may be why it didn't contain the relevant value when creating the plugin. The resources directories for the plugins are actually just set by the runtime env agent to be relative to the runtime env dir, e.g. the pip plugin uses {runtime_env_dir}/pip as its resources_dir. And if you need some files in your ray runtime env, you should use working_dir described here https://docs.ray.io/en/latest/ray-core/handling-dependencies.html#using-local-files
