### ISSUE TITLE
Cluster between ARM64 and X86 machines

### ISSUE THREAD

**Issue by gliese581gg** [ray-project/ray#4015]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Machine 1 : Aarch64, Ubuntu 18.04 (NVIDIA Xavier board)
Machine 2 : X86, Ubuntu 16.04 (Workstation)
- **Ray installed from (source or binary)**:
Machine 1 : Source, Machine 2 : Binary
- **Ray version**: 0.6.3
- **Python version**: 3.6.7 (Machine 2 uses anaconda)
- **Exact command to reproduce**:

### Describe the problem

I ran following code in Machine 2 (X86 Workstation)

```py
import time, ray
import logging

b = ray.init()
print(b)
a = input('asdf')

@ray.remote
def f():
    time.sleep(0.01)
    return ray.services.get_node_ip_address()

# Get a list of the IP addresses of the nodes that have joined the cluster.
logging.basicConfig(filename='cluster.txt',level=logging.DEBUG)
print(ray.get([f.remote() for _ in range(100)]))

while True:
    time.sleep(1)
```

After the code stops at `a=input('asdf')`,

I ran `ray start --redis-address {redis address of workstation}` in Machine 1 (ARM64).

Then I press enter in Machine 2 (X86) and raylet on Machine 1 (ARM64) failed to get heartbeat and

shut down.

I tried same code with X86 embedded system and it worked well.

So I assume that this is ARM64 or OS issue.

Does anyone tried this? I have no idea what causes this issue.

**Comment by robertnishihara** [comment]
Some things to try.

1. Can you start Ray on the first machine by doing `ray start --head ...`?
2. After connecting with `ray.init(redis_address=...)`, can you call `ray.global_state.client_table()` and check that both nodes have successfully connected?
3. Make sure that when you are building from source, you are building from the 0.6.3 release commit so the versions match (instead of from the current master).
4. Check `/tmp/ray/` and see if there are any interesting log or error messages there.

**Comment by gliese581gg** [comment]
I reinstalled release version on the Arm64 machine and ray works perfectly now!

Thank you:)
