### ISSUE TITLE
Problem with function signatures?

### ISSUE THREAD

**Issue by zbarry** [ray-project/ray#4020]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.6.2
- **Python version**: 3.7
- **Exact command to reproduce**:

Given: 

```python
import ray

ray.init()

@ray.remote
def test(arg_1, arg_2, kwarg_1=None, kwarg_2='asdf'):
    return

print(test._function_signature)
```

The output is:

```
FunctionSignature(arg_names=['arg_1', 'arg_2', 'kwarg_1', 'kwarg_2'], 
arg_defaults=[<class 'funcsigs._empty'>, <class 'funcsigs._empty'>, None, 'asdf'], 
arg_is_positionals=[False, False, False, False], 
keyword_names={'kwarg_2', 'arg_1', 'kwarg_1', 'arg_2'}, 
function_name='test')
```

Would have expected `arg_is_positionals` to be true for `arg_1`, `arg_2`. Am I missing something about how these `FunctionSignature`s work?

Unrelated, but are those `_function_*` object attributes of `RemoteFunction`s following the leading `_` convention where you should not treat these as publicly exposed and as such could be removed at any time? Access to the signature especially is useful for the analysis pipeline I'm building on top of Ray at the moment.

**Comment by robertnishihara** [comment]
I see, yes, slightly unfortunately, the two fields of the remote function that are considered exposed are `test.remote` and `test._remote` (the latter provides a bit more configurability). Everything else is an implementation detail, and we prefix it with `_` in order to make it more hidden.

You're right that the way we handle function signatures is a bit hacky. There are some things that aren't supported yet, e.g.,
- We don't currently support Python 3 keyword-only arguments https://github.com/ray-project/ray/issues/2629
- We don't support `**kwargs` https://github.com/ray-project/ray/blob/9797028a91ed98a3251be95d2b33ae5f68c7e128/python/ray/signature.py#L81-L82
- We don't support `*args` in conjunction with keyword arguments. https://github.com/ray-project/ray/blob/9797028a91ed98a3251be95d2b33ae5f68c7e128/python/ray/signature.py#L81-L82

This will all get fixed, but it hasn't seemed to cause that many issues, so we haven't done it yet.

Can you elaborate a bit on your use case and how you are using types?

I'd suggest directly using the `funcsigs` module to interpret the signature of the underlying function, which currently is `test._function` (though that is considered unexposed).

**Comment by zbarry** [comment]
> This will all get fixed, but it hasn't seemed to cause that many issues, so we haven't done it yet.

Yup. Managed to work around this limitation so far pretty straightforwardly.

> I'd suggest directly using the `funcsigs` module to interpret the signature of the underlying function, which currently is `test._function` (though that is considered unexposed).

Right... don't know why I got so hyperfocused on using the unexposed function signature Ray generates, haha. 

Re: unexposed `_function`, might I suggest going the `functools` route and adding a `__wrapped__` attribute referencing the original function? See: https://docs.python.org/3/library/functools.html#functools.update_wrapper

> Can you elaborate a bit on your use case and how you are using types?

Yeah, definitely. What I'm building right now is a general-purpose data analysis pipeline framework where one can specify "stages" of computation, and with as little effort as possible, create their own reproducible pipelines (I'm a fan of emerging efforts w.r.t. reproducible data science & also not reinventing the wheel every time I start working on another project for a collaborator). You can see how Ray might be very useful for fine-grained parallelism and the ability to operate locally, in HPC environments, and on the cloud :).

Specifically here, this is work on being able to resume your computational functions from any point in your pipeline provided the dependencies to a step are already met... think the benefits of a Makefile/snakemake-style setup, but with all the advantages of the flexibility/fine-grained-ness that Python/Ray provides when used directly to define computational graphs.

Actual (pseudoish-)code for resuming & saving might look like:

```python
import ray

from functools import wraps

@stage_computation
@ray.remote
def _compute(name, group, file_path):

    return result

def stage_computation(func):

    @wraps(func)
    def wrapper(*args, **kwargs):

        # serialization / deserialization helpers to be potentially @ray.remote-
        # wrapped

        def _load(deserialization_instructions):
            return deserialization_instructions()

        def _save(result_, serialization_instructions):
            serialization_instructions(result_)

        if executing_this_remotely:
            _load = ray.remote(num_return_vals=num_outputs_of_upstream_function)(_load).remote
            _save = ray.remote(_save).remote

        if inputs_already_computed:
            args = ensure_iterable(_load(args[0]))

        result = func.remote(*args, **kwargs)

        _save(result_, serialization_instructions)

        return result

    return wrapper
```

Came up with this last night... might be a better way, but the idea here is that I have to fill in `*args` if it has already been computed in a previous run of the pipeline. I want Ray to return the same number of futures as that input-generating function spit out into its serialized data file for this purpose.

**Comment by richardliaw** [comment]
This should be fixed since we have kwargs support - feel free to reopen if this is an issue.
