### ISSUE TITLE
[RLlib] RLModule API support for custom init of WnB

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#40259]
### What happened + What you expected to happen

There is no possibility with the new `RLModule API` to use a custom initialization of weigths and biases. Performance of agents have been shown to be dependent on a good initialization. Specifically initializing biases to always zero can in some scenarios prevent the agent totally from learning.

### Versions / Dependencies

Python 3.9.12
Ray nightly
Linux Fedora 37

### Reproduction script

Run any example in RLlib and check a module's weights.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by gresavage** [comment]
I asked a similar question [here](https://discuss.ray.io/t/initialize-model-parameters-in-rlmodules/12417)

I would very much like to be able to initialize weights and biases as well - especially since this feature was available in Model V2 API and as @simonsays1980 mentioned good initialization can be the difference between whether or not a deep network learns. I think using the same kind of logic that's in `get_activation_fn` would be helpful in this regard.

In the old API, AFAIK, the initializer was either `xavier`, `normal`, or a custom callable. *As an enhancement* it would be nice to see full support for `torch`, `tf`, and `jax` initializers similar to activations rather than just a subset. I would also like to see the ability to specify configurations to pass to both the activations and initializers as keyword arguments.

I have done this already in a private repository on which I work:

1. using `inspect` to dynamically make a mapping from strings to initializers supported by the framework (thus any time a new initializer is added it is automatically supported)
2. using `inspect` along with decorators to wrap the activation and initializer in a `functools.partial` when a configuration dict is passed.

So an example configuration looks something like:

```yaml
...
framework: 'torch'
...
model:
  fcnet_activation: 'tanh'
  fcnet_activation_config: {}
  fcnet_initializer: 'orthogonal_'
  fcnet_initializer_config:
    gain: 1.41
...
```

I obviously also have custom RL Modules to accept these additional `kwargs` so the added functionality is actually used by the MLP heads.

Another alternative, or in addition, to using `inspect` is using `pydantic` where specifying an object type as `PyObject` allows for automatically mapping a valid import string to a python object. So pydantic will see `'torch.nn.init.orthogonal_'` and attempt to import it.
