### ISSUE TITLE
Unify ray discovery during tests

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#4031]
This came up while working on #3898 

At the moment, we have two different types of tests:

The ones in ray/test, which will be run with whichever version of ray is *installed* (this could be the one in the ray/ folder if `pip install -e` was used, or it could be the one in the site-packages folder, or in the user's local site-packages folders).

The ones in the subfolders of ray/python/ray, which will run whichever ray version is in the ray/ folder and this will fail if there is no binaries in that folder.

The reason for this difference is the discovery mechanism of pytest: If there is an __init__.py in the test directory, it will recursively try to go up until it finds the package, see https://docs.pytest.org/en/latest/goodpractices.html the part that says "pytest supports two common test layouts:").

This behavior is confusing at the moment and should be unified. I'd prefer if the installed version of Ray is always used. In this case we need to get rid of __init__.py in the test directories, which means we need to put test modules that get imported and test files that get run into separate directories.

cc @richardliaw @ericl @williamma12

**Comment by pcmoritz** [comment]
related but not the same: https://github.com/ray-project/ray/pull/3950

**Comment by ericl** [comment]
I'm not sure I see the difference here. In general you get undefined behaviour when the installed version of ray is not the same as the repo files, so this situation rarely arises.

**Comment by pcmoritz** [comment]
So they way I'm setting things up in bazel right now is by default no binaries are written to the ray/python/ray folder and they will only be written by setup.py (if the user did pip install -e .). If users do setup.py install, the second type of tests mentioned above wouldn't work any more then and that is clearly undesirable. The way we did it before (duplicating the files in ray/build as well as ray/python) was a bit sloppy anyways.

**Comment by williamma12** [comment]
The motivation behind #3950 is so that the relevant python ray tests are shipped with ray (so we can test ray by doing `pip install ray` and not have to clone the ray directory and worry about which ray was being called). 

Would it changing the rootdir be enough? If so, we can just add a `pytest.ini` file where the binaries are to [change the `rootdir`.](https://docs.pytest.org/en/latest/customize.html#finding-the-rootdir) As long as it is outside `ray/python/ray`, it won't affect the test `rootdir` of ray from Pypi and still allow pytest to find the correct `rootdir` if someone does `pip install -e .`

**Comment by ericl** [comment]
With bazel, won't the tests be running inside the bazel sandbox with `bazel test`? So it's kind of a moot point.

**Comment by ericl** [comment]
Actually, isn't this also an issue for non-test scripts such as `train.py` in rllib? If the binaries aren't written out by a bazel compile, then would you have to run a setup.py develop again on each compile?

If it's weird to have a bazel build copy files, you could have a side-effect target like:
`bazel run :install-dev`

**Comment by ericl** [comment]
Ok I think I understand what's going on: it's `pytest` that's the problem.

There's another solution which is implemented already by tune and rllib tests: don't use pytest. Those test files can be run directly, and this does the right thing (this explains why I never hit this issue :))

**Comment by ericl** [comment]
Can we please keep the rllib and tune tests as is, since they don't need pytest anyways?

**Comment by pcmoritz** [comment]
Well, it's nice to run everything in pytest in travis, as it keeps the output small (supressing stdout) and gives good error messages on failure.

But if you want to keep the status quo, can you make a PR that runs them without pytest in travis?

**Comment by ericl** [comment]
That sounds good (I think you just remove the "pytest" prefix?)

This should be just a temporary thing; when the bazel build works, I'm happy to port everything to `bazel test`.

**Comment by pcmoritz** [comment]
Yeah I agree! I want to keep things a little more incremental, there is already a lot going on in the current Bazel PR ;)

**Comment by robertnishihara** [comment]
@pcmoritz Most projects seem to have an `__init__.py` in the `tests/` directory. Can you explain why there is a difference in behavior between `python setup.py install` and `pip install -e .`? This so far has nothing to do with Bazel, so wouldn't any project have this problem?

@ericl @pcmoritz for testing, we should make sure to follow best practices and have a uniform testing strategy. I think this means doing the following:
- Converting everything to pytest (see https://github.com/ray-project/ray/issues/2774). @ericl if you prefer `unittest` and object to converting to `pytest` can you explain why? I've converted all the non RLlib and Tune tests and it's improved the CI experience a lot.
- Move Python tests into `python/ray/tests/` including tune and rllib tests. This seems to be how all projects do it, so I assume this is the best practice. If that's not the case, I'd be interested in seeing an example.

**Comment by pcmoritz** [comment]
@robertnishihara Please read the section "Choosing a test layout / import rules" in https://docs.pytest.org/en/latest/goodpractices.html and you'll understand the difference.

**Comment by pcmoritz** [comment]
The difference with bazel is that for "python setup.py install", we won't copy the binaries into the repo any more, which means the "Tests as part of application code" won't work (it would use the code in the repo, which doesn't have the binaries).

**Comment by robertnishihara** [comment]
Will removing the `__init__.py` from `python/ray/tests` prevent the tests from being shipped in the Ray wheels? It's important for the tests to be part of the wheels.

**Comment by robertnishihara** [comment]
From reading the pytest documentation, it sounds like in the `python setup.py install` case, you can just run `pytest --pyargs ray` and it will work (because it will use the installed ray and the tests from the installed ray (not the local tests).

I think there's no need to support the case where someone installs Ray non-locally (that is, not in editable mode) and then tries to run tests in the local repo.

**Comment by ericl** [comment]
> * Move Python tests into `python/ray/tests/` including tune and rllib tests.

I've explicitly moved these tests out for maintainability. Moving forward, in the bazel convention, tests should be co-located with their module. This simplifies a lot of things -- for one, you don't have to do cd ../../../.. to find your tests when developing your library. I think you see test in a dedicated dir in a lot of OSS projects because they are quite small and basically just have one module.

Also, I think that once we have `bazel test` working, we should just drop all the pytest / travis stuff. The bazel test runner is *far* better (you just `bazel test ...` in your project / sub-project and get parallel exec and nicely organized output).

**Comment by robertnishihara** [comment]
@ericl Isn't `bazel test` orthogonal to `pytest`/`travis`? I'm assuming it's just a way to run all of the tests, but that's orthogonal to what frameworks are used to write the test (e.g., googletest, pytest, unittest, etc) and orthogonal to where the CI actually runs (e.g., travis, jenkins, etc), right?

**Comment by pcmoritz** [comment]
Alright, I think we should use `--pyargs ray` as the short term workaround as @robertnishihara and move on to `bazel test` as soon as possible.

**Comment by ericl** [comment]
@robertnishihara right, though here the issue is that pytest is also being used as the test runner (and sets up the system path is nonstandard ways). RLlib / tune tests are written in pure unittest, but I guess in travis we still use pytest to run them.

**Comment by richardliaw** [comment]
Closed since we moved to Bazel.
