### ISSUE TITLE
Create Ray namespace for Kubernetes

### ISSUE THREAD

**Issue by vakker** [ray-project/ray#4112]
It would be a useful feature if the Ray master and workers were deployed to a separate namespace, so they don't pollute the default one.

It's an easy change in `kubernetes/*.yaml`, I can create a PR if that's useful.

**Comment by virtualluke** [comment]
I agree, I can add that to a PR I plan on putting in in the next day or so that also adds node antiaffinity to the deployment (which I think is useful as a default).  I view the kubernetes/ path to be an example deployment anyway (non comprehensive, non definitive) and to be seen as a good template for a kuberenetes cluster. Most likely different clusters and use cases would be configuring aspects differently (like number of replicas, custom resources, num_cpus limits, etc).

**Comment by robertnishihara** [comment]
@virtualluke if you could make that change in your PR that'd be awesome!

**Comment by vakker** [comment]
So shall I go ahead with [#4111](https://github.com/ray-project/ray/pull/4111)? Sorry for the confusion, I was just preparing the PR as a draft.
