### ISSUE TITLE
[data] inconsistent parallelism / block sizes when using ray.data.read_parquet().map_batches()

### ISSUE THREAD

**Issue by wingkitlee0** [ray-project/ray#41378]
### What happened + What you expected to happen

When reading multiple parquet files (say, _N_ of them) and setting `parallelism=N`, the resultant dataset has _N_ blocks and each block correspond to one file. However, when we run `ds.map_batches(..., batch_size=None)` , the number of blocks and block size may change (different from _N_), even tho `batch_size=None` supposed to mean "to use entire blocks as batches". 

This is a little bit problematic as the mapping function may expect the whole block as input (e.g., time series). This behavior only occurs when `map_batches` but not in `iter_batches(batch_size=None)`.

**Details**
Posting some extra details as I tried to debug it a little bit:
* It seems to be specific to `ParquetDatasource`:
  * In  `get_read_tasks()`, `parallelism=N` is used to split the `fragments` into _N_ chunks: `np.array_split(pq_fragments, parallelism)`
  * It then generates a list of `ReadTask` that would call `_read_fragment()` at some point. There should be _N_ tasks
  * In each `ReadTask` (iterator), it loops over each fragment and each "batch" (and yield the corresponding `pyarrow.Table` one by one).
  * Note that the "batch" is actually pyarrow's `RecordBatch`. As a result, each `ReadTask` returns one or more entries, depending on some non-trivial calculations and overrides of the `batch_size` (an arg of `to_batches()`) and the underlying number of row groups inside each parquet file..

**Expected behavior**
For a straight-forward `read_parquet(parallelism=N)` followed by `map_batches(batch_size=None)`, I would expect it to return _N_ rows.
It seems that we need an "auto" (or keep it as None) and a "strict" option that does not alter the batch size.

### Versions / Dependencies

3.0.0.dev0

### Reproduction script

```
import numpy as np
import ray
import ray.data


def reading_test(filename):
    # ray.data.DataContext.get_current().target_min_block_size = 1000000
    # ray.data.DataContext.get_current().target_max_block_size = 1000000
    ds2 = ray.data.read_parquet(
        filename,
        parallelism=5,
    )
    ds2_mapped = (
        ds2.map_batches(
            fn=lambda x: {
                "len": [len(x["id"])],
                "min": [np.min(x["id"])],
                "max": [np.max(x["id"])],
            },
            batch_size=None,
        )
    ).materialize()

    print("ds2_mapped.num_blocks (materialized):", ds2_mapped.num_blocks())

    result_2 = (ds2_mapped).take_all()

    print("len(result_2): ", len(result_2))
    print(result_2)


def main():

    # parallelism=N results in N blocks
    ds = ray.data.range(5_000_000, parallelism=5)

    print("number of blocks: ", ds.num_blocks())

    result_1 = (
        ds.map_batches(
            fn=lambda x: {
                "len": [len(x["id"])],
                "min": [np.min(x["id"])],
                "max": [np.max(x["id"])],
            },
            batch_size=None,  # batch_size=None should means batch:block = 1:1
        )
    ).take_all()

    # Gives number of blocks correctly
    print("len(result_1): ", len(result_1))

    # Save ds. It will save 5 files because there are 5 blocks.
    # I set the row_group_size to a lower value to that there are multiple row groups in each file
    ds.write_parquet("test2.parquet", row_group_size=500_000)

    # read the parquet file and run map_batches
    reading_test("test2.parquet")


if __name__ == "__main__":
    main()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by anyscalesam** [comment]
@scottjlee @c21 will need to look into this further before determining priority.

**Comment by scottjlee** [comment]
With `read_parquet`, each read task may generate multiple output blocks, depending on the size of the output -- blocks that exceed the max target block size will be split into multiple blocks. So, this is expected behavior with the current API, as Ray Data will dynamically adjust the number/size of blocks. 

If you want to force the output to contain N blocks, one workaround here is to increase the target max block size to effectively disable the block splitting logic (set `DataContext.target_max_block_size` to a large number).

**Comment by bdewilde** [comment]
For what it's worth, I was able to reproduce the original poster's problem, but _not_ the behavior described by @scottjlee .

I have target max block size set to the default of 128MB and read in 1 40MB parquet file of ~1.5M rows using `parallelism=1`. Printing the dataset shows that `ray` knows what's up: `Dataset(num_blocks=1, num_rows=1563418, schema=SCHEMA)` . I then call `Dataset.map_batches(preproc_func, batch_size=None, batch_format="pandas")`. Instead of one large batch, I get many batches of 10k rows apiece, just 0.4MB big according to `pandas.DataFrame.memory_usage()`. Strangely, if I call `.limit()` on the dataset using a value larger than the total number of rows, I do indeed get one large batch, 56MB big -- well under the max target size. I also get the expected batch size if I use `.iter_batches()`, i.e. `next(iter(ds.iter_batches(batch_size=None, batch_format="pandas")))`. 

This behavior has surprised me, it significantly harms performance, and I don't know how to resolve it in a way that doesn't require a major rewrite. Please help.

**Comment by Omkar4141** [comment]
How to decide num_blocks based on size of data ?

**Comment by wingkitlee0** [comment]
Closing this as it looks like `parallelism` is deprecated; haven't looked into the new `override_num_blocks` option yet.
