### ISSUE TITLE
Data - dataset.show() error is non deterministic and error code is illegible

### ISSUE THREAD

**Issue by anyscalesam** [ray-project/ray#41458]
### What happened + What you expected to happen

dataset.show() intermittently fails and the error message/trace stack is hard to decipher

### Versions / Dependencies

latest as of time of this bug which is ray28

### Reproduction script

See recording.

### Issue Severity

None

**Comment by anyscalesam** [comment]
This one maps to Ammar in go/ray-data-cuj @c21 can you pop in the recording as well so @Zandew  has context?

**Comment by Zandew** [comment]
The exception was `pyarrow.lib.ArrowInvalid: Referenced field image was extension<arrow.py_extension_type<ArrowTensorType>> but should have been extension<arrow.py_extension_type<ArrowTensorType>>`, which is weird because the two types are the same. I think it could have something to do with https://github.com/apache/arrow/pull/38608 (Nov 6), which was fixed by #41036 (Nov 20) (CUJ was on Nov 15). Although its still weird that the dataset could execute. I can't seem to reproduce this again.

**Comment by Zandew** [comment]
Closing as I cannot reproduce this currently anymore. I should have been resolved as described in the previous comment.
