### ISSUE TITLE
Set environment variables for actors and workers

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#418]
To support selecting a gpu for theano, an environment variable needs to be set before theano is imported. We should think about how to pass environment variables to actor processes when they are started by the local scheduler. See http://stackoverflow.com/questions/31983794/select-gpu-during-execution-in-theano.

**Comment by robertnishihara** [comment]
It's possible that the `CUDA_VISIBLE_DEVICES` approach to limiting which GPUs can be used will work with Theano as well (we should try it out), though it probably needs to be done before Theano is imported.

**Comment by richardliaw** [comment]
To add, PyTorch currently doesn't allow in-program control of threading (https://github.com/pytorch/pytorch/issues/975), so the best solution right now is to set `OMP_NUM_THREADS` before the ray program is run.

**Comment by chunyang-wen** [comment]
So can we set now? @robertnishihara @richardliaw

**Comment by edoakes** [comment]
This can be set by a method in the actor.

**Comment by robertnishihara** [comment]
Now it's possible to do this with [runtime environments](https://docs.ray.io/en/latest/advanced.html?highlight=environment%20variable#runtime-environments), e.g., 

```python
import os
import ray

runtime_env = {
    'env_vars': {'ENV_VAR_1': 'env_var_value'}
}

# Actors

@ray.remote(runtime_env=runtime_env)
class Actor:
    def method(self):
        print(os.environ['ENV_VAR_1'])

a = Actor.remote()
ray.get(a.method.remote())

# Tasks

@ray.remote(runtime_env=runtime_env)
def f():
    print(os.environ['ENV_VAR_1'])

ray.get(f.remote())
```

The output is

```
(Actor pid=13659) env_var_value
(f pid=13664) env_var_value
```

Note that if you want to set the environment variable for all actors/workers, you can do it with `ray.init(runtime_env=runtime_env)`.

This issue is old, but updating the answer because this issue is the first search result when I searched "Ray set environment variable for actor".
