### ISSUE TITLE
[rllib] Reward Shaping - Best Practices

### ISSUE THREAD

**Issue by dmadeka** [ray-project/ray#4223]
Quick questions:

- Whats the best way to use a `Filter` or a `FilterManager` to scale rewards?

- Whats the best way to `shape` rewards? For example, in the game `Pong` if you'd like to give a reward for everytime the agent is able to hit the ball (as opposed to just when a point is scored) can that be done?

**Comment by ericl** [comment]
I think the way to go is to use a reward wrapper around the environment: https://hub.packtpub.com/openai-gym-environments-wrappers-and-monitors-tutorial/

This would be registered as a custom env. You could easily use MeanStdFilter inside the wrapper without any filter manager (i.e. don't synchronize rewards across workers). Since the rewards will be highly correlated synchronization is probably not needed.

**Comment by dmadeka** [comment]
@ericl Thanks! Is there a way to do the same for advantages? Advantage normalization is usually super helpful

**Comment by ericl** [comment]
Hm, we standardize the advantages for PPO (see: standardize_fields arg in multi_gpu_optimizer.py), but currently not for other algorithms. This would probably have to be done in the loss function itself in some cases, and so would require code modifications.
