### ISSUE TITLE
[data] AutoscalingRequester actor prevents worker node down-scaling if scheduled on a node other than the head node

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#42253]
### What happened + What you expected to happen

The AutoscalingRequester actor can get scheduled to a worker node and will keep the worker node alive even if there are no tasks running. We should use hard affinity to pin the actor to the head node instead.

### Versions / Dependencies

3.0dev

### Reproduction script

Ray Data script on autoscaling cluster

### Issue Severity

None

**Comment by dominikgrygiel** [comment]
Hey, I think there might be a regression of this issue - https://github.com/ray-project/ray/issues/51559

**Comment by daiping8** [comment]
I also tested this issue in the latest version of Ray. The reason for this problem is that when Ray turns on autoscaller, it generates two actor instances, _StatsActor and AutoscalingRequester, when scaling worker nodes. These two actors are only created when they are first called. After creation, they are always in the active state and can be reused directly. They are globally unique and will not be destroyed when a single task ends. I am considering modifying the source code of Ray autoscaller to always start these two actors on the head node. This will not violate the original design intention of the two actors, but also ensure that the worker nodes can down-scaling normally. I will submit this PR later.
