### ISSUE TITLE
[Ray Dataset] Dataset progress bar is displayed incorrectly 

### ISSUE THREAD

**Issue by v4if** [ray-project/ray#42782]
### What happened + What you expected to happen

Ray dataset progress bar is displayed incorrectly. With parallelism 2, the total number of progress bars here keeps growing, and the remaining estimated time is always 0. I don’t know how much data has been processed and how much data is left.
![image](https://github.com/ray-project/ray/assets/16042235/1eef1c91-eeb0-43bc-93c6-0e4d201d17c3)

### Versions / Dependencies

Ray version: 2.9.1

### Reproduction script

```python
import ray
import numpy as np
import time

ray.init(num_cpus=6)
ray.data.DataContext.get_current().execution_options.verbose_progress = True


def transform1(image_batch):
    print("transform1 batch_size:", len(image_batch["image"]))

    time.sleep(3)

    return image_batch


def transform2(image_batch):
    print("transform2 batch_size:", len(image_batch["image"]))

    time.sleep(3)

    return image_batch


ray_dataset = (
    ray.data.from_items(
        [{"image": np.random.randn(224, 224, 3)} for x in range(2000)],
        parallelism=2,
    )
    .map_batches(transform1, batch_size=8)
    .map_batches(transform2, batch_size=8, num_cpus=0.5)
)

print("ray_dataset", ray_dataset)

for batch in ray_dataset.iter_torch_batches(batch_size=8):
    pass
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by scottjlee** [comment]
I modified the script above slightly to reduce the size of the dataset, like so:

```
import ray
import numpy as np
import time

ray.init(num_cpus=6)
ray.data.DataContext.get_current().execution_options.verbose_progress = True

def transform1(image_batch):
    time.sleep(1)
    return image_batch

def transform2(image_batch):
    time.sleep(1)
    return image_batch

paths = ["s3://anonymous@air-example-data/iris.csv"] * 10
ray_dataset = (
    ray.data.from_items(
        [{"image": np.random.randn(30, 30, 3)} for x in range(100)],
        parallelism=2,
    )
    .map_batches(transform1, batch_size=2)
    .map_batches(transform2, batch_size=2, num_cpus=0.5)
)

print("ray_dataset", ray_dataset)

for batch in ray_dataset.iter_torch_batches(batch_size=8):
    pass
```

During running the script (using ray master), I get the following output, which does show the progress updating:

```
Running: 1/6 CPU, 0/0 GPU, 2.1MB/1.0GB object_store_memory: : 0.00 bundle [00:50, ? bundle/s]                                                                                            
- MapBatches(transform1): 1 active, 0 queued, [cpu: 1.0, objects: 1.0MB]:  50%|█████████████████████████████████                                 | 1.00/2.00 [00:50<00:25, 25.4s/ bundle]
- MapBatches(transform2): 1 active, 0 queued, [cpu: 0.5, objects: 256.0MB]:  50%|████████████████████████████████                                | 1.00/2.00 [00:50<00:50, 50.6s/ bundle]
```

In the original script, `parallelism=2` creates two tasks, each of which takes a very long time (needs to process 1000 rows each). The total for the progress bar, when initially unknown (as is the case with the `MapBatches` output here), will be updated with the new estimate after each task completes ([code path](https://github.com/ray-project/ray/blob/727139c427a36b6a9883ad0fb4093a6143a810dd/python/ray/data/_internal/execution/operators/map_operator.py#L322-L331)). Because each of the two tasks takes a long time to complete, we don't see the total updating for a long time. By reducing the total data size, we are able to see that the progress bar does indeed update.

@v4if feel free to re-open this issue if you can confirm that on latest master. It's very possible that we have made a fix between ray 2.9.1 and now.
