### ISSUE TITLE
why serialize and deserialize actor not working?

### ISSUE THREAD

**Issue by chunyang-wen** [ray-project/ray#4295]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.4
- **Python version**: 3.6.5
- **Exact command to reproduce**: python file.py

### Describe the problem

I have no idea why ray hangs here. I also tried ray==0.6.3 from PIP, ray still hangs.

In another case:

+ first pickle a created actor and save the string into redis (`pickle.dumps`)
+ unpickle it (`pickle.loads`)
+ call member function of it, it also hangs.

### Source code / logs

```python
import os
import ray

import pickle

class B(object):

    def hi(self):
        print("Say HI")

    def gg(self):
        os._exit(0)


ray.init()

A = ray.remote(max_reconstructions=3)(B)

a = A.remote()

c = pickle.dumps(a)


d = pickle.loads(c)

e = d.hi.remote()

ray.get(e)

d = pickle.loads(c)
e = d.hi.remote()

ray.get(e)
```

**Comment by chunyang-wen** [comment]
It seems that actor created from `pickle.loads` can only be used once. Resubmitted task will be ignored.

```python
 A task was resubmitted, so we are ignoring it. This should only happen during reconstruction
```

maybe @raulchen can provide more details here.

**Comment by jovany-wang** [comment]
The identity for an actor task is a tuple: `(actor_id, handle_id)`.
`handle_1 = dumps(actor)` will generate a new `handle_id` for the variable `handle_1`, and let's say it `(actor_id, x)`. 

`handle_2 = loads(handle_1)`: `handle_2` have the same specification as `handle_1` ->`(actor_id, x)`.

If we `handle_3 = dumps(handle_1)` again,  the `handle_3` also have the same specification `handle_1` ->`(actor_id, x)`.

In Raylet, it doesn't allow that we submit the same specification(the tuple) twice. So you'll get the log: ` A task was resubmitted, so we are ignoring it. This should only happen during reconstruction`, and this task `(actor_id, x)` will not be executed.

=============================

Another question, why are we hanging at the `ray.get(e)` at the last statement in you script?
we can print `e` to trace it:
```python
ray.init()

A = ray.remote(max_reconstructions=3)(B)
a = A.remote()
c = pickle.dumps(a)
d = pickle.loads(c)
e = d.hi.remote()     # ObjectID(01000000fdef0f2dd5c38a849a67ebab9ece9e5a)
ray.get(e) 

d = pickle.loads(c)
e = d.hi.remote()    # ObjectID(01000000abc7f90173fb9e5a25ec76f9e37bada6)
ray.get(e)  
```
So, the last object `e  ObjectID(01000000abc7f90173fb9e5a25ec76f9e37bada6)` doesn't exists.

**Comment by jovany-wang** [comment]
I think we can improve the behavior for the issue: hanging at `ray.get(e)`.
Like if we found the task is duplicated in raylet, we can write  a meta message to the return object.

So, `ray.get(e)` will raise an exception with message: Failed to get since the task was duplicated. etc.

How do you guys think of this? @raulchen  @robertnishihara

**Comment by jovany-wang** [comment]
Thanks, I think It does make sense for the result.

Every actor handle keeps a `task_counter`, and the Raylet also keeps `expect_task_counter`s for all actors in Raylet's view.
```python
a = A.remote()   
```
Let's say the the `task_counter` in `a` is 0.
```python
c = pickle.dumps(a)
d = pickle.loads(c)
```
When we `dumps(a)`, we increase the `task_counter` for the result `c`. So, the `task_counter` of `c` is 1 now. After we `loads(c)` to `d`, the `task_counter` of `d` is 1 as well.
Right now, in `Raylet`'s view, the `expect_task_counter` of the actor is `0`.
```python
e = d.hi.remote()
```
After a remote call, the `task_counter` of `d` will be increased 1, so it's `2` now.
The Raylet received the task and check whether `expect_task_counter <= d.task_counter`. It passes because of `0 < 2`.  Also, the `expect_task_counter` of the actor will be updated to `d.task_counter`:2.

Then, 
```python
d = pickle.loads(c)
e = d.hi.remote()
```
We `loads(c)` to `d` again, so the `task_counter` of `d` is `1` because `c.task_counter` is `1`.
When we call `d.hi.remote()` again, we send a task to Raylet, The result of `check(expect_task_counter(2) <= d.task_counter(1))` is false, so , it'll be ignored.

================================================
The reason for hanging at the last statement `ray.get(e)` is the task will not be executed.

**Comment by jovany-wang** [comment]
I think we can improve the behavior to not hanging at `ray.get(e)`:
when the Raylet failed to check, we can put a meta message into the return object to say `Failed to executing task since xxxxxx`.

@raulchen  @robertnishihara  How do you guys thinks of this?

**Comment by richardliaw** [comment]
I think actor handle pickling should work now (unless you're restoring across different ray sessions).
