### ISSUE TITLE
[core][experimental] Support OSX for accelerated DAGs

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#43834]
### Description

Support OSX to improve development workflow for accelerated DAGs. Accelerated DAGs are currently not supported on OSX because OSX only supports named semaphores, not unnamed ones. We should check the performance and any behavior changes with named semaphores; if these are the same we can switch to always use named semaphores.

**Comment by jackhumphries** [comment]
It's not immediately clear to me why a semaphore is the right synchronization primitive to use for the mutable object manager. For example, consider this code:
```
 sem_wait(&channel.reader_semaphore);

  int64_t version_read = 0;
 RAY_LOG(DEBUG) << "ReadAcquire " << object_id
               << " version: " << channel.next_version_to_read;
 RAY_RETURN_NOT_OK(channel.mutable_object->header->ReadAcquire(
    channel.next_version_to_read, &version_read));
RAY_CHECK(version_read > 0);
channel.next_version_to_read = version_read;
channel.read_acquired = true;
```

If the reader semaphore is initialized with a value greater than 1, multiple readers in parallel will be able to advance beyond `sem_wait()` in `ReadAcquire()`. As a result, multiple readers will race to set `channel->next_version_to_read` and `channel->read_acquire`. Additionally, any readers in `ReadRelease()` will also race to set these two variables.

I am making the assumption that multiple readers will each call `ReadAcquire()` and `ReadRelease()`. Is my assumption incorrect or am I otherwise overlooking something?

**Comment by jackhumphries** [comment]
Actually, is the intent that each reader process has its own channel? In other words, each channel is private to a single reader?
