### ISSUE TITLE
[Doc] [Polish] Front page video box looks awkwardly stretched

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#44227]
### Description

Full screen, the front page video looks weirdly long horizontally. When it plays, there's big black boxes on the side.
<img width="1728" alt="Screenshot 2024-03-21 at 2 00 45 PM" src="https://github.com/ray-project/ray/assets/5459654/79dc6a5a-c35d-4907-bac8-36f747b63900">
<img width="1723" alt="Screenshot 2024-03-21 at 2 01 24 PM" src="https://github.com/ray-project/ray/assets/5459654/03601a11-6f2a-4bfe-ac95-336955503f32">

Full screen, Chrome, Macbook Pro M1

### Link

https://docs.ray.io/

**Comment by den319** [comment]
I think the issue of black boxes in both sides of the video in <iframe> element occurs due to use of inappropriate relation between width and height. I saw the code and tried to increase the height of <div> element wrapping <iframe> element for desktop-screen size and it worked for that perticular screen size. That is why I came up with the above conclusion. 
I'd like to work on this issue if you don't mind.

**Comment by architkulkarni** [comment]
cc @peytondmurray, what do you think?

**Comment by peytondmurray** [comment]
You've got a video that you're trying to fit in that rectangular section of the front page. The rectangle you want it to fit in doesn't have the same aspect ratio as your video. Your options to make the aspect ratio of the video match the rectangular area you want it to fit in are

1. Cropping the video
2. Have black bars on either the top/bottom or left/right (letterboxing)
3. Stretch the video to fit

IMO letterboxing is the least bad of these.

**Comment by peytondmurray** [comment]
In any case, we are removing the video in the [next iteration of the front page](https://github.com/ray-project/ray/issues/42068), so maybe we can just close this one out once that PR gets merged? (expected to be merged next week)
