### ISSUE TITLE
[Core] build error in arm aarch64 in gcc11

### ISSUE THREAD

**Issue by ashione** [ray-project/ray#44528]
### What happened + What you expected to happen

Fail to execute 
```shell
bazel build ray_pkg
```

<img width="1315" alt="image" src="https://github.com/ray-project/ray/assets/7359537/753a787e-5a4d-444b-a68f-138ed08c555c">

### Versions / Dependencies

Ray latest versions
Python : 3.10
OS : ubuntu 22.04 (docker in mac m3 arm64)
GCC 11

### Reproduction script

Execute any bazel target building within upb/protobuf.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by aslonnie** [comment]
you can follow https://github.com/ray-project/ray/blob/master/python/README-building-wheels.md to build the wheel with bazel.

**Comment by ashione** [comment]
> you can follow https://github.com/ray-project/ray/blob/master/python/README-building-wheels.md to build the wheel with bazel.

I guess you just don't get what I'm saying. It's none related of  compiler, but grpc submodule can not be built in arm64 chips, which is not fixed in manylinux.

**Comment by aslonnie** [comment]
hi, arm64 wheels build on our CI, it is being built by us regularly (many times every day). but it needs to use exactly the same image and toolchain environment to build.

here is a screenshot that what we just built today on master branch.

<img width="512" alt="image" src="https://github.com/ray-project/ray/assets/95255098/7276f446-2421-42d2-a02b-99a27c594914">

sorry but we won't fix issues that is not using the manylinux build environment to build, and on the manylinux build environment we are using, we are not seeing the issue you are reporting.

**Comment by aslonnie** [comment]
what bazel version are you using?

**Comment by ashione** [comment]
> what bazel version are you using?

5.4.1 (same with ray cicd env)

**Comment by ashione** [comment]
> hi, arm64 wheels build on our CI, it is being built by us regularly (many times every day). but it needs to use exactly the same image and toolchain environment to build.
> 
> here is a screenshot that what we just built today on master branch.
> 
> <img alt="image" width="512" src="https://private-user-images.githubusercontent.com/95255098/340836414-7276f446-2421-42d2-a02b-99a27c594914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NzcxOTcsIm5iZiI6MTcxODc3Njg5NywicGF0aCI6Ii85NTI1NTA5OC8zNDA4MzY0MTQtNzI3NmY0NDYtMjQyMS00MmQyLWEwMmItOTlhMjdjNTk0OTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA2MDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3Mjc2Y2YzZTYwYzYwMDU5ODMwZTAyYmMzMDRlZDk5MGQxOTkzYjczNDdhNWRjMWEzMDFiMGIwYmI3NmFhZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K8lsmastZPAyzKhzseYnACTO3EucutP0fNFy97iD7zo">
> sorry but we won't fix issues that is not using the manylinux build environment to build, and on the manylinux build environment we are using, we are not seeing the issue you are reporting.

I know that. However, the issue mentioned above is building in gcc11 on arm64 arch. Your pipeline works well under gcc10 unless you never upgrade gcc toolchain.

**Comment by aslonnie** [comment]
> > what bazel version are you using?
> 
> 5.4.1 (same with ray cicd env)

not sure what commit you are using, but we recently upgraded to `6.5.0`:

https://github.com/ray-project/ray/blob/master/.bazelversion

you should be using `bazelisk` to build, which might make it easier.

----

we do not really support building ray in 22.04, it is out of our support scope. even if it builds, it won't be publishable on pypi because it will not be manylinux compliant.

the manylinux2014 standard is here:
https://peps.python.org/pep-0599/

it very explicitly says how to compile a python wheel, with info about the libraries and compilers that one can use.

we do also compile on ubuntu (during CI testing) today, but it uses clang-12 and ubuntu 20.04. we are working on converting CI testing to use manylinux too so that testing is closer to release and more meaningful. one reason is that the ray binary parts compiled on ubuntu 22.04 or above does not work with conda (the default libstdc++ version coming with ubuntu 22.04 is too high..)

----

searching on the Internet, there is this:
https://github.com/grpc/grpc/issues/35052

which says the error will go away if you use clang; not sure if this helps or not.

**Comment by aslonnie** [comment]
fwiw, the `upb/protobuf` library (`grpc` library) probably should be upgraded.. the issue that the gcc compiler surfaces might be a real one.
