### ISSUE TITLE
[core][experimental] Accelerated DAG should throw an error if execution would deadlock due to NCCL ops

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#45594]
### What happened + What you expected to happen

NCCL ops are blocking and can deadlock if the user-specified DAG has a cycle. This can be fixed by enforcing a global execution order between actors, but for now, we should just throw an error if there is possibility of deadlock. For example, the following graph would hang.

```python
with InputNode() as inp:
  branch1 = a.foo.bind(inp)
  branch1.with_type_hint(TorchTensorType(transport="nccl"))
  branch2 = b.foo.bind(inp)
  branch2.with_type_hint(TorchTensorType(transport="nccl"))

  # Each actor will block trying to send their previous output to the other actor's `consume` task.
  a.consume.bind(branch2)
  b.consume.bind(branch1)
```

### Versions / Dependencies

3.0dev

### Reproduction script

see above

### Issue Severity

None

**Comment by kevin85421** [comment]
I want to make sure my understanding of this issue is correct.

A Ray actor will execute tasks one by one in `do_exec_tasks` in order. Thus, actor `a` will execute `a.foo` before `a.consume`, and actor `b` will execute `b.foo` before `b.consume`. However, `a.foo` relies on `b.consume`, `b.consume` relies on `b.foo`, `b.foo` relies on `a.consume`, and `a.consume` relies on `a.foo`. That's why deadlock happened.

If this is correct, what is the relationship between the deadlock and the NCCL operations? It seems like the deadlock will occur regardless of the channel being used.

**Comment by stephanie-wang** [comment]
The deadlock only happens when NCCL is used because NCCL is synchronous, meaning the sender cannot finish the op until the reader has read. For shared memory channels, we can buffer the result, so the sender can finish its send while the reader is still executing something else.

**Comment by kevin85421** [comment]
> The deadlock only happens when NCCL is used because NCCL is synchronous, meaning the sender cannot finish the op until the reader has read.

Got it.

> For shared memory channels, we can buffer the result, so the sender can finish its send while the reader is still executing something else.

Maybe I need to do some experiments locally. The `Channel`'s `begin_read` looks like a synchronous operation. It calls `ray.get`.

https://github.com/ray-project/ray/blob/56565a35923f59568dadc7a1bac84a697395156b/python/ray/experimental/channel/shared_memory_channel.py#L412-L428

**Comment by kevin85421** [comment]
Update:

> A Ray actor will execute tasks one by one in `do_exec_tasks` in order. Thus, actor `a` will execute `a.foo` before `a.consume`, and actor `b` will execute `b.foo` before `b.consume`. However, `a.foo` relies on `b.consume`, `b.consume` relies on `b.foo`, `b.foo` relies on `a.consume`, and `a.consume` relies on `a.foo`. That's why deadlock happened.

This only happens when the channels are NCCL channels. For the shared memory channel, the completion of the `write` function means that the data has been successfully written into the shared memory. However, for the NCCL channel, the completion of the `write` function means that the data is being read by the reader at the same time.
