### ISSUE TITLE
Fail to run tune with tensorflow and gpu

### ISSUE THREAD

**Issue by ZhangYuef** [ray-project/ray#4568]
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.5
- **Python version**: 3.6

### Describe the problem
I am trying to use ray with tensorflow following the tutorial ([link](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/tune_mnist_ray.py))
And I got a `tune error`:

### error log
```

Result logdir: ray_results/tune_gan_test
Number of trials: 2 ({'ERROR': 2})
ERROR trials:
 - train_gan_0_partition=0:     ERROR, 1 failures: ray_results/tune_gan_test/train_gan_0_partition=0_2019-04-05_16-25-5536of9abi/error_2019-04-05_16-26-02.txt
 - train_gan_1_partition=1:     ERROR, 1 failures: ray_results/tune_gan_test/train_gan_1_partition=1_2019-04-05_16-26-1038hprt_a/error_2019-04-05_16-26-12.txt

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/16 CPUs, 0/1 GPUs
Memory usage on this node: 53.0/67.5 GB
Result logdir: ray_results/tune_gan_test
Number of trials: 2 ({'ERROR': 2})
ERROR trials:
 - train_gan_0_partition=0:     ERROR, 1 failures: ray_results/tune_gan_test/train_gan_0_partition=0_2019-04-05_16-25-5536of9abi/error_2019-04-05_16-26-02.txt
 - train_gan_1_partition=1:     ERROR, 1 failures: ray_results/tune_gan_test/train_gan_1_partition=1_2019-04-05_16-26-1038hprt_a/error_2019-04-05_16-26-12.txt

Traceback (most recent call last):
  File "train.py", line 142, in <module>
    **gan_spec)
  File "/lib/python3.6/site-packages/ray/tune/tune.py", line 253, in run
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [train_gan_0_partition=0, train_gan_1_partition=1])
```

### Source code / logs
The code related to ray use:

```
# !!! Entrypoint for ray.tune !!!
def train(config={'partition': 0}, reporter=None):
    global status_reporter, partition_fn
    status_reporter = reporter
    partition_fn = config['partition']
    tf.app.run(main=main)


# !!! Example of using the ray.tune Python API !!!
if __name__ == "__main__":
    try:
        register_trainable('train_gan', train)
        gan_spec = {
            'stop': {
                'time_total_s': 600,
            },
            'config': {
                'partition': grid_search([0, 1]),
            },
        }

        ray.init()

        tune.run('train_gan',
                 name='tune_gan_test',
                 resources_per_trial={"gpu":1},
                 raise_on_failed_trial=True,
                 queue_trials=True,
                 with_server=False,
                 **gan_spec)

    except KeyboardInterrupt:
        os._exists(1)
```

How could I fix this? Thx for your help : )

**Comment by richardliaw** [comment]
Hi, can you post the output of the error_{date}.txt file shown in the terminal output?

**Comment by ZhangYuef** [comment]
> Hi, can you post the output of the error_{date}.txt file shown in the terminal output?

Of course.

The error file for trial 1:
```
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 409, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 314, in fetch_result
    result = ray.get(trial_future[0])
  File "/lib/python3.6/site-packages/ray/worker.py", line 2316, in get
    raise value
ray.exceptions.RayTaskError: ^[[36mray_worker^[[39m (pid=20375, host=vcl-dl-2)
  File "/lib/python3.6/site-packages/ray/tune/trainable.py", line 151, in train
    result = self._train()
  File "/lib/python3.6/site-packages/ray/tune/function_runner.py", line 203, in _train
    ("Wrapped function ran until completion without reporting "
ray.tune.error.TuneError: Wrapped function ran until completion without reporting results or raising an exception.
```

**Comment by richardliaw** [comment]
Oh, make sure in your main function you call the status_reporter as seen in the example. Can you try that out?

**Comment by ZhangYuef** [comment]
> Oh, make sure in your main function you call the status_reporter as seen in the example. Can you try that out?

I have the `status_reporter` in my main file as:

```
    with tf.Session() as sess:

        for idx in range(train_set.minibatches):
            global_cnt = 0
            for epoch in range(epoch_start + 1, config.nr_epoch + 1):
                global_cnt += 1
                _, accuracy, loss_batch, summary = sess.run([train, acc, loss,],
                                                                       feed_dict=feed_dict)

            # !!! Report status to ray.tune !!!
            if status_reporter:
                status_reporter(
                    mean_accuracy=accuracy)
```

**Comment by richardliaw** [comment]
hm, can you check that in the main file, `status_reporter` is not None? You can do this by turning `verbose=2` in `tune.run` and then printing the arguments in the training loop.

**Comment by ZhangYuef** [comment]
> hm, can you check that in the main file, `status_reporter` is not None? You can do this by turning `verbose=2` in `tune.run` and then printing the arguments in the training loop.

Hi, thx for your help. I simply add this in main file which I am not sure whether it is right.
```
def main(_):
    ## create a session
    tf.set_random_seed(12345) # ensure consistent results
  
    with tf.Session() as sess:

        for idx in range(train_set.minibatches):
    
            for epoch in range(epoch_start + 1, config.nr_epoch + 1):
                _, accuracy, loss_batch, adv_examples, summary = sess.run([train, acc, loss, adv, merged],
                                                                       feed_dict=feed_dict)
            # !!! Report status to ray.tune !!!
            print(status_reporter)
            if status_reporter:
                status_reporter(
                    mean_accuracy=accuracy)
```

The output of the errorr_{date}.txt file seems to be unchanged. As in complete:
```
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 409, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 314, in fetch_result
    result = ray.get(trial_future[0])
  File "/lib/python3.6/site-packages/ray/worker.py", line 2316, in get
    raise value
ray.exceptions.RayTaskError: ^[[36mray_worker^[[39m (pid=25712, host=vcl-dl-2)
  File "/lib/python3.6/site-packages/ray/tune/trainable.py", line 151, in train
    result = self._train()
  File "/lib/python3.6/site-packages/ray/tune/function_runner.py", line 203, in _train
    ("Wrapped function ran until completion without reporting "
ray.tune.error.TuneError: Wrapped function ran until completion without reporting results or raising an exception.

```

The output of the terminal:
```
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/16 CPUs, 0/1 GPUs
Memory usage on this node: 26.7/67.5 GB

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 1/16 CPUs, 1/1 GPUs
Memory usage on this node: 26.9/67.5 GB
Result logdir: /ray_results/tune_gan_test
Number of trials: 2 ({'RUNNING': 1, 'PENDING': 1})
PENDING trials:
 - train_gan_1_partition=1:     PENDING
RUNNING trials:
 - train_gan_0_partition=0:     RUNNING

^[[2m^[[36m(pid=1520)^[[0m usage: default_worker.py [-h] [-c CONTINUE_PATH] [-l LOSS]
^[[2m^[[36m(pid=1520)^[[0m default_worker.py: error: unrecognized arguments: --node-ip-address=162.105.94.50 --object-store-name=/tmp/ray/session_2019-04-08_14-54-41_1407/sockets/plasma_store --raylet-name=/tmp/ray/session_2019-04-08_14-54-41_1407/sockets/raylet --redis-address=111.111.111.50:32830 --temp-dir=/tmp/ray/session_2019-04-08_14-54-41_1407
^[[2m^[[36m(pid=1574)^[[0m usage: default_worker.py [-h] [-c CONTINUE_PATH] [-l LOSS]
^[[2m^[[36m(pid=1574)^[[0m default_worker.py: error: unrecognized arguments: --node-ip-address=111.111.111.50 --object-store-name=/tmp/ray/session_2019-04-08_14-54-41_1407/sockets/plasma_store --raylet-name=/tmp/ray/session_2019-04-08_14-54-41_1407/sockets/raylet --redis-address=162.105.94.50:32830 --temp-dir=/tmp/ray/session_2019-04-08_14-54-41_1407

```

**Comment by richardliaw** [comment]
Oh; can you remove these things? `[-h] [-c CONTINUE_PATH] [-l LOSS]` 

I think absl hijacks the sys args that Ray uses

**Comment by ZhangYuef** [comment]
> Oh; can you remove these things? `[-h] [-c CONTINUE_PATH] [-l LOSS]`
> 
> I think absl hijacks the sys args that Ray uses

Thanks Richard, after removing the absl outputs, I finally got the outputs of Ray and  found the problem was not related to Ray. So I closed this issue.

**Comment by Tabbi7** [comment]
I got the same error while performing a Flow training.

```
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/7 CPUs, 0/0 GPUs
Memory usage on this node: 11.2/17.2 GB
Result logdir: /Users/fabianafierro/ray_results/stabilizing_the_ring
Number of trials: 1 ({'ERROR': 1})
ERROR trials:
 - PPO_WaveAttenuationPOEnv-v0_0:	ERROR, 1000 failures: /Users/fabianafierro/ray_results/stabilizing_the_ring/PPO_WaveAttenuationPOEnv-v0_0_2020-06-02_13-28-052yion30s/error_2020-06-02_22-20-03.txt, [7 CPUs, 0 GPUs], [pid=76499], 68 s, 1 iter, 20000 ts, 2.37e+03 rew

Traceback (most recent call last):
  File "examples/train.py", line 404, in <module>
    main(sys.argv[1:])
  File "examples/train.py", line 392, in main
    train_rllib(submodule, flags)
  File "examples/train.py", line 213, in train_rllib
    run_experiments({flow_params["exp_tag"]: exp_config})
  File "/Users/fabianafierro/flow/flow/flow/lib/python3.6/site-packages/ray/tune/tune.py", line 324, in run_experiments
    return_trials=True)
  File "/Users/fabianafierro/flow/flow/flow/lib/python3.6/site-packages/ray/tune/tune.py", line 262, in run
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_WaveAttenuationPOEnv-v0_0])
```

**Comment by mahuangxu** [comment]
> I got the same error while performing a Flow training.
> 
> ```
> == Status ==
> Using FIFO scheduling algorithm.
> Resources requested: 0/7 CPUs, 0/0 GPUs
> Memory usage on this node: 11.2/17.2 GB
> Result logdir: /Users/fabianafierro/ray_results/stabilizing_the_ring
> Number of trials: 1 ({'ERROR': 1})
> ERROR trials:
>  - PPO_WaveAttenuationPOEnv-v0_0:	ERROR, 1000 failures: /Users/fabianafierro/ray_results/stabilizing_the_ring/PPO_WaveAttenuationPOEnv-v0_0_2020-06-02_13-28-052yion30s/error_2020-06-02_22-20-03.txt, [7 CPUs, 0 GPUs], [pid=76499], 68 s, 1 iter, 20000 ts, 2.37e+03 rew
> 
> Traceback (most recent call last):
>   File "examples/train.py", line 404, in <module>
>     main(sys.argv[1:])
>   File "examples/train.py", line 392, in main
>     train_rllib(submodule, flags)
>   File "examples/train.py", line 213, in train_rllib
>     run_experiments({flow_params["exp_tag"]: exp_config})
>   File "/Users/fabianafierro/flow/flow/flow/lib/python3.6/site-packages/ray/tune/tune.py", line 324, in run_experiments
>     return_trials=True)
>   File "/Users/fabianafierro/flow/flow/flow/lib/python3.6/site-packages/ray/tune/tune.py", line 262, in run
>     raise TuneError("Trials did not complete", errored_trials)
> ray.tune.error.TuneError: ('Trials did not complete', [PPO_WaveAttenuationPOEnv-v0_0])
> ```

I got the same question，I notice that the error says"Resources requested: 0/7 CPUs, 0/0 GPUs". After I delete the code"'num_gpus': 1", there will be no error.
How can I solove it? Thanks a lot!

**Comment by Jthon-lab** [comment]
> > I got the same error while performing a Flow training.
> > ```
> > == Status ==
> > Using FIFO scheduling algorithm.
> > Resources requested: 0/7 CPUs, 0/0 GPUs
> > Memory usage on this node: 11.2/17.2 GB
> > Result logdir: /Users/fabianafierro/ray_results/stabilizing_the_ring
> > Number of trials: 1 ({'ERROR': 1})
> > ERROR trials:
> >  - PPO_WaveAttenuationPOEnv-v0_0:	ERROR, 1000 failures: /Users/fabianafierro/ray_results/stabilizing_the_ring/PPO_WaveAttenuationPOEnv-v0_0_2020-06-02_13-28-052yion30s/error_2020-06-02_22-20-03.txt, [7 CPUs, 0 GPUs], [pid=76499], 68 s, 1 iter, 20000 ts, 2.37e+03 rew
> > 
> > Traceback (most recent call last):
> >   File "examples/train.py", line 404, in <module>
> >     main(sys.argv[1:])
> >   File "examples/train.py", line 392, in main
> >     train_rllib(submodule, flags)
> >   File "examples/train.py", line 213, in train_rllib
> >     run_experiments({flow_params["exp_tag"]: exp_config})
> >   File "/Users/fabianafierro/flow/flow/flow/lib/python3.6/site-packages/ray/tune/tune.py", line 324, in run_experiments
> >     return_trials=True)
> >   File "/Users/fabianafierro/flow/flow/flow/lib/python3.6/site-packages/ray/tune/tune.py", line 262, in run
> >     raise TuneError("Trials did not complete", errored_trials)
> > ray.tune.error.TuneError: ('Trials did not complete', [PPO_WaveAttenuationPOEnv-v0_0])
> > ```
> 
> I got the same question，I notice that the error says"Resources requested: 0/7 CPUs, 0/0 GPUs". After I delete the code"'num_gpus': 1", there will be no error.
> How can I solove it? Thanks a lot!

Hi, I met the same question when I run the flow project. Did you solve it?

**Comment by mahuangxu** [comment]
Please check if you are using the GPU version Pytorch or Tensorflow.












马黄旭
***@***.***
北京邮电大学
信息与通信工程学院
北京市海淀区西土城路10号，100876
---Original---
From: ***@***.***&gt;
Date: Sat, Aug 28, 2021 13:48 PM
To
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ray-project/ray] Fail to run tune with tensorflow and gpu (#4568)


I got the same error while performing a Flow training.


== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/7 CPUs, 0/0 GPUs
Memory usage on this node: 11.2/17.2 GB
Result logdir: /Users/fabianafierro/ray_results/stabilizing_the_ring
Number of trials: 1 ({'ERROR': 1})
ERROR trials:
&nbsp;- PPO_WaveAttenuationPOEnv-v0_0:ERROR, 1000 failures: /Users/fabianafierro/ray_results/stabilizing_the_ring/PPO_WaveAttenuationPOEnv-v0_0_2020-06-02_13-28-052yion30s/error_2020-06-02_22-20-03.txt, [7 CPUs, 0 GPUs], [pid=76499], 68 s, 1 iter, 20000 ts, 2.37e+03 rew


Traceback (most recent call last):
&nbsp; File "examples/train.py", line 404, in <module&gt;
&nbsp; &nbsp; main(sys.argv[1:])
&nbsp; File "examples/train.py", line 392, in main
&nbsp; &nbsp; train_rllib(submodule, flags)
&nbsp; File "examples/train.py", line 213, in train_rllib
&nbsp; &nbsp; run_experiments({flow_params["exp_tag"]: exp_config})
&nbsp; File "/Users/fabianafierro/flow/flow/flow/lib/python3.6/site-packages/ray/tune/tune.py", line 324, in run_experiments
&nbsp; &nbsp; return_trials=True)
&nbsp; File "/Users/fabianafierro/flow/flow/flow/lib/python3.6/site-packages/ray/tune/tune.py", line 262, in run
&nbsp; &nbsp; raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_WaveAttenuationPOEnv-v0_0])
I got the same question，I notice that the error says"Resources requested: 0/7 CPUs, 0/0 GPUs". After I delete the code"'num_gpus': 1", there will be no error.
How can I solove it? Thanks a lot!


Hi, I met the same question when I run the flow project. Did you solve it?


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.&nbsp;












马黄旭
***@***.***

北京邮电大学
信息与通信工程学院
北京市海淀区西土城路10号，100876

---Original---
From: ***@***.***&gt;
Date: Sat, Aug 28, 2021 13:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ray-project/ray] Fail to run tune with tensorflow and gpu (#4568)




   
I got the same error while performing a Flow training.
 == Status == Using FIFO scheduling algorithm. Resources requested: 0/7 CPUs, 0/0 GPUs Memory usage on this node: 11.2/17.2 GB Result logdir: /Users/fabianafierro/ray_results/stabilizing_the_ring Number of trials: 1 ({'ERROR': 1}) ERROR trials:  - PPO_WaveAttenuationPOEnv-v0_0:ERROR, 1000 failures: /Users/fabianafierro/ray_results/stabilizing_the_ring/PPO_WaveAttenuationPOEnv-v0_0_2020-06-02_13-28-052yion30s/error_2020-06-02_22-20-03.txt, [7 CPUs, 0 GPUs], [pid=76499], 68 s, 1 iter, 20000 ts, 2.37e+03 rew Traceback (most recent call last):   File "examples/train.py", line 404, in <module&gt;     main(sys.argv[1:])   File "examples/train.py", line 392, in main     train_rllib(submodule, flags)   File "examples/train.py", line 213, in train_rllib     run_experiments({flow_params["exp_tag"]: exp_config})   File "/Users/fabianafierro/flow/flow/flow/lib/python3.6/site-packages/ray/tune/tune.py", line 324, in run_experiments     return_trials=True)   File "/Users/fabianafierro/flow/flow/flow/lib/python3.6/site-packages/ray/tune/tune.py", line 262, in run     raise TuneError("Trials did not complete", errored_trials) ray.tune.error.TuneError: ('Trials did not complete', [PPO_WaveAttenuationPOEnv-v0_0])   
I got the same question，I notice that the error says"Resources requested: 0/7 CPUs, 0/0 GPUs". After I delete the code"'num_gpus': 1", there will be no error.
 How can I solove it? Thanks a lot!
  
Hi, I met the same question when I run the flow project. Did you solve it?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
