### ISSUE TITLE
[Data] ArrowNotImplementedError for array column after `map_batches` in pandas format

### ISSUE THREAD

**Issue by ducthienbui97** [ray-project/ray#45732]
### What happened + What you expected to happen

After a column with array elements went through `map_batches` with `panda` format, it cause error when trying to write that dataset or access schema

### Versions / Dependencies

ray==2.23.0
pyarrow==16.0.0

### Reproduction script

```py
import ray


def filter(batch):
    return batch

ds=ray.data.from_items([["test", "test"], ["test", "test"], ["test", "test"] ]).map_batches(filter, batch_format="pandas")
ds.schema()
```

```
pypi_ray/site-packages/ray/data/dataset.py", line 5199, in __repr__
    for name, type in zip(self.names, self.types):
/pypi_ray/site-packages/ray/data/dataset.py", line 5171, in types
    shape=dtype._shape, dtype=pa.from_numpy_dtype(dtype._dtype)
  File "pyarrow/types.pxi", line 5381, in pyarrow.lib.from_numpy_dtype
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: Unsupported numpy type 17

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by PranitKatwe** [comment]
Hello, I am looking to contribute to my first issue. I may not be sure what will work and what will not but I will try my best to help you out with the issue.

Possible Solutions:
1. I have tested the same code on 
ray= 2.32.0
pyarrow=17.0.0
It works for me and the dataset gets executed properly when I run on these versions.

2.  Try defining the schema explicitly while creating the dataset or after `map_batches`.

`import pyarrow as pa

ray.init()

schema = pa.schema([
    ('column1', pa.list_(pa.string())),
    ('column2', pa.list_(pa.string()))
])

ds = ray.data.from_items([["test", "test"], ["test", "test"], ["test", "test"]])
ds = ds.map_batches(filter, batch_format="pandas")
ds = ds.cast(schema)

ray.shutdown()`

3. Instead of using pandas batch format use `arrow` batch format which might handle the data types more consistently.
`ds = ds.map_batches(filter, batch_format="pyarrow")`

4. Try finding out which datatypes are you working with to get a clear idea. Try converting the data types before passing to Pyarrow.

5. It is possible that the `filter` function is returning pandas object arrays, try converting them to lists before returning.
` def filter(batch):
    # If your columns are object arrays, convert them to lists
    batch = batch.applymap(lambda x: x.tolist() if isinstance(x, np.ndarray) else x)
    return batch`

Let me know if any of the solutions work for you.

**Comment by richardliaw** [comment]
This now works on latest Ray.

**Comment by richardliaw** [comment]
That being said, @PranitKatwe -- very much appreciate your contribution here, very thorough! Please reach out to the Ray team on the Ray Slack, happy to work with you on finding areas for contribution!

**Comment by PranitKatwe** [comment]
Thank you for letting me know @richardliaw

**Comment by MissiontoMars** [comment]
@richardliaw May I ask in which pull request was it fixed? Could you provide the pull request link if it's convenient? Thanks

**Comment by richardliaw** [comment]
Hey @MissiontoMars, Unfortunately I think you'll have to try out different versions here (i just tested master and didn't get the same issue)
