### ISSUE TITLE
Core： ray job is  blocked  by scheduling

### ISSUE THREAD

**Issue by biingxiing** [ray-project/ray#46141]
### What happened + What you expected to happen

My task has been running for about 4 hours, and the CPUs in the cluster have started to become idle. However, there are still tasks that haven't been scheduled. I waited about 10 hours
<img width="1434" alt="image" src="https://github.com/ray-project/ray/assets/18545798/fec9029e-7e29-4371-99ea-c3745f0bce6a">

### Versions / Dependencies

ray-2.9.0
linux 

### Reproduction script

normal task and actor

### Issue Severity

High: It blocks me from completing my task.

**Comment by anyscalesam** [comment]
@biingxiing this issue is really vague... can you please provide an actual repro script beyond just "normal task and actor"; it can be one of a million reasons why your job doesn't get scheduled.

information on your cluster config in terms of resources would also be helpful. I'm closing this for now - please re-open with additional details and we can take a look at it.
