### ISSUE TITLE
can I use ray to speed a nested loop on huge list, like:

### ISSUE THREAD

**Issue by loveJasmine** [ray-project/ray#4677]
for i in range(N):
      for j in range(N):
           calc(N[i], N[j])

N is huge, like tens of millions

**Comment by robertnishihara** [comment]
I'm guessing that calc must be extremely fast? Maybe use batching to speed
things up, like

import ray

ray.init()

N = 10**5

@ray.remote
def calc_range(i1, i2):
    for i in range(i1, i2):
        for j in range(N):
            # calc(i, j)
            pass

batch_size = 10**3
result_ids = []
for i in range(0, N, batch_size):
    result_ids.append(calc_range.remote(i, i + batch_size))

results = ray.get(result_ids)

Note that you'll want to return something from the remote function and also
if you have a big object shared between all of the tasks, you may want to
put that in the object store with *ray.put* first and then pass the ID into
the remote function instead of passing the object in directly.

**Comment by robertnishihara** [comment]
I'm guessing that calc must be extremely fast? Maybe use batching to speed
things up, like

```python
import ray

ray.init()

N = 10**5

@ray.remote
def calc_range(i1, i2):
    for i in range(i1, i2):
        for j in range(N):
            # calc(i, j)
            pass

batch_size = 10**3
result_ids = []
for i in range(0, N, batch_size):
    result_ids.append(calc_range.remote(i, i + batch_size))

results = ray.get(result_ids)
```

Note that you'll want to return something from the remote function and also
if you have a big object shared between all of the tasks, you may want to
put that in the object store with *ray.put* first and then pass the ID into
the remote function instead of passing the object in directly.

**Comment by robertnishihara** [comment]
Closing because I think this is answered.
