### ISSUE TITLE
[<Ray co[Ray Train]save checkpoint 

### ISSUE THREAD

**Issue by Hxinyue** [ray-project/ray#46913]
### Description

１、run_config = RunConfig(storage_path="s3://bucket", name="unique_run_name")
２、The CheckpointConfig file in RunConfig does not give S3 a storage path and is saved locally by default. Can I not save the file? Because my train_loop_per_worker function also saves a checkpoints.

**Comment by justinvyu** [comment]
@Hxinyue For multi-node train runs, we only allow checkpointing to S3, since checkpointing locally will make the checkpoint unusable for recovery (if the node that the checkpoint was saved goes down).

For single-node runs, you can still keep the default local storage option. Feel free to re-open if you have more questions!

**Comment by akshay-raj-dhamija** [comment]
Hi @justinvyu A couple of clarifications:

- This breaks the [WandBLoggerCallback](https://docs.ray.io/en/latest/tune/api/doc/ray.air.integrations.wandb.WandbLoggerCallback.html#ray-air-integrations-wandb-wandbloggercallback). If we provide an `s3://` path to save the checkpoints in, the checkpoints only get saved on S3 and not as artifact on WandB, which was supported in earlier ray versions.

- The only s3 support behavior makes sense for model parallel approaches where the model is distributed across workers and can be lost if any worker goes down, but for data parallel approaches where all ranks should have the same model is it an overkill?
