### ISSUE TITLE
ModuleNotFoundError: No module named 'ray._raylet' when running test suite

### ISSUE THREAD

**Issue by warren-sentient** [ray-project/ray#4727]
### System information
- **OS and distro**: Windows 10 WSL, Linux Ubuntu 18.04)
- **Ray installed from**: binary
- **Ray version**: 0.6.6
- **Python version**: Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0] on linux2:

### Command to reproduce:
From the cloned repo folder (ray):
python -m pytest -v python/ray/tests/test_mini.py

It gives the same error on any of the tests I try to run

### Describe the problem
I am getting the following error "E ModuleNotFoundError: No module named 'ray._raylet'" when running the test suite on the latest source in git. I have tried python3 and it gives the same problem.

I have tried wiping everything and making sure there are no copies of Ray installed anywhere. Then cloning a fresh copy and reinstalling.

### Source code / logs
ImportError while loading conftest '/mnt/c/Users/warre_000/ray/python/ray/tests/conftest.py'.
python/ray/__init__.py:52: in <module>
    from ray._raylet import (
E   ModuleNotFoundError: No module named 'ray._raylet'

**Comment by robertnishihara** [comment]
Is it possible that the repository is slightly out of sync with the version of Ray installed from PyPI? Ignoring the tests, if you start Python (from some directory outside of the `ray` directory), and do `import ray; ray.init()`, does that work?

**Comment by PengZhenghao** [comment]
I saw this error before. It's likely happens when you messed up the ray install via (1) `pip install ray`, (2) `pip install <the link to the wheel>` and (3) `pip install -e . --verbose` when installing from source.

I remember that happen when I install ray from source via `pip install -e . --verbose` but without running `ray/ci/travis/install-bazel.sh` in the first place.

Try to remove installed ray and all relevant links and install it again following the [instruction](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by warren-sentient** [comment]
Thank you @pengzhenghao 

I had somehow missed running ray/ci/travis/install-bazel.sh first

I ran ray/ci/travis/install-bazel.sh and then pip install -e . --verbose and then the tests ran perfectly.

Thank you!
