### ISSUE TITLE
Put RayletClient into ray::raylet namespace

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#4753]
Currently, the RayletClient lives in the global namespace. It should be moved to ray::raylet.

see
https://github.com/ray-project/ray/blob/master/src/ray/raylet/raylet_client.h

**Comment by walterddr** [comment]
Hi here. I was wondering if anyone is working on this. I have push a branch for moving `RayleClient` to `ray::raylet` namespace but I am not sure what sort of testings I need to run (other than the build script) to ensure this change is safe to be merge. Please see them [here](https://github.com/walterddr/ray/commit/19e8350778a90dcd09b8321e68124f2bfe8782d4)

Thanks

**Comment by pcmoritz** [comment]
Hey @walterddr thanks, this is great! Can you open a PR? The CI will automatically run and tell us if any more changes are needed.

**Comment by walterddr** [comment]
Thanks @pcmoritz I just opened the PR. 

However I am not exactly sure if this is valid since most of the tests I tried to do in the checklist (instructions checklist template when opening the PR) but some of the scripts wont run correctly and travis has been failing for recent master commits. Since I am very new to ray-dev, I would much appreciate if you could provide more pointers :-)
