### ISSUE TITLE
[RFC] Reorganize ray repo

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#4816]
Currently, the top organization of the Ray repo is pretty hard to navigate. Something like the following would be more clear:

```
build/
core/
docs/
deploy/
rllib/
tune/
BUILD.bazel
CONTRIBUTING.rst
LICENSE
README.rst
```

Ideally, we'd also refactor `core`, `tune` and `rllib` to have separate setup.py scripts, so that they can be developed without needing to recompile ray core by default.

**Comment by hartikainen** [comment]
Just a random thought: At the point where `tune` and `rllib` have their own `setup.py` scripts, would it make sense to consider moving them into their own projects/repos? Tune, at least to my understanding, shouldn't depend so deeply on Ray that it couldn't be run as a separate repo with a normally imported ray? I don't know about rllib but would imagine things being same for it as well.

Obvisouly, there might be other benefits, like the already existing build system etc., for keeping the repos together, which might surpass the benefits of splitting the repos.

**Comment by richardliaw** [comment]
cc @robertnishihara @pcmoritz

**Comment by ericl** [comment]
I'm in general biased towards having a single repo, due to the need to maintain build and release processes and infrastructure (especially if we start adding larger scale tests). There are some benefits of a separate repo, but it would be substantial overhead to maintain I think.

**Comment by robertnishihara** [comment]
I agree that having one build/release/testing process is a huge benefit.

Regarding the repo structure, some questions:

1. Can you clarify where the Python/C++/Java code for the Ray core would go?
2. Where would we put the autoscaler and the currently experimental libraries like serving, streaming, training, etc?
3. Would any of the changes that you're proposing change anything for users? E.g., are you also proposing to change the structure of the PyPI package?
4. Regarding separate setup.py scripts for rllib/tune, can you elaborate on why recompiling Ray is an issue? Now that we're using bazel, compilation should be pretty quick, and for python modifications this should only be necessary when you rebase your branch on the master (which changes the C++ code).
5. One complexity that I anticipate here is that since the repo structure would no longer mirror the Python package structure, the build process would have to copy the Python files around to make the directory structure match and this would probably also break development mode (since we would have copies of the Python files). Does that make sense?

**Comment by zhijunfu** [comment]
@guoyuhong

**Comment by bbalaji-ucsd** [comment]
How about a [submodule](https://gist.github.com/gitaarik/8735255) for `rllib` and `tune`? That can resolve issues related to build/release cycle.

**Comment by ericl** [comment]
So a couple things:
- I think it makes sense to organize the components into directories by their logical project, instead of by language. This makes it easier for new developers to find where things are, and also allows commands like `bazel test //core/...` to make sense. We could have an `experimental` dir as well, or it could be under core, either seems ok to me.

- I'm proposing having separate `ray-core`, `ray-rllib`, `ray-tune` PyPI packages. However users would `pip install ray` which would automatically install all 3.

- I think that regardless of how easy it is to setup compilation, it is some barrier to entry which would be nice to remove. Though, there are probably some quick fixes we could make in the meantime.

- Re: mirroring Python package structure -- I don't think this would be an issue with separate pypi packages.

- Re: submodules, I'm not sure it solves the problem of having to run test infra on a separate repo. It could solve the release issue though (iirc, we already do something similar to this to vendor modin).

**Comment by rkooo567** [comment]
@ericl I think it is done? Please reopen if it doesn't!
