### ISSUE TITLE
Ray not using head server

### ISSUE THREAD

**Issue by jarlva** [ray-project/ray#4825]
Running a simple script below on a node the webgui shows that only node's workers are used and no head server (workers stay at 0/2). Also notice that traffic increments on the webgui head Recv (M/s) column. Both nodes show up on the webgui. Node PC is local. head is located in the cloud.

import time, ray
ray.init(redis_address="<ip>:6379")

@ray.remote
def f2():
    time.sleep(1)

start = time.time()
ray.get([f2.remote() for _ in range(30)])
end = time.time()
print('took ' + str(end - `start))

Troubleshooting:
Able to telnet from node to head via ports 6379, 6380.
head command: 
`ray start --head --redis-port=6379 --redis-shard-ports=6380  --node-manager-port=6381 --object-manager-port=6382 --include-webui
`
node command: `ray start --redis-address <ip>:6379`

Using Ray 0.7.0, Python 3.6.7 on ubuntu 18.

**Comment by robertnishihara** [comment]
So the application runs successfully but the scheduling isn't done properly?

What happens if you run `ray.global_state.client_table()` after `ray.init` (does it show two nodes)? What resources are associated with each node?

**Comment by jheffez** [comment]
The app runs successfully  on the local node only and uses all 4 cpu's/workers.  None on the head server. In the screenshot, ubuntu1 is the local node.

![image](https://user-images.githubusercontent.com/26058035/58231993-0adb4800-7d41-11e9-9bfa-6f68e7bb7900.png)


```
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
 import ray
 ray.init(redis_address="78.141.207.129:6379")
```
`{'node_ip_address': '10.0.0.40', 'redis_address': '78.141.207.129:6379', 'object_store_address': '/tmp/ray/session_2019-05-23_09-44-57_372914_1039/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2019-05-23_09-44-57_372914_1039/sockets/raylet', 'webui_url': 'http://78.141.207.129:8080/?token=0b0a5e113f0a742ad3aa682d3ab8c7790dd5d69c32a506c9', 'session_dir': '/tmp/ray/session_2019-05-23_09-44-57_372914_1039'}`



`ray.global_state.client_table()`

`[{'ClientID': '7bc75f9f01b11d958f0df98ddf322eeec00adee3', 'EntryType': 1, 'NodeManagerAddress': '78.141.207.129', 'NodeManagerPort': 6381, 'ObjectManagerPort': 6382, 'ObjectStoreSocketName': '/tmp/ray/session_2019-05-23_09-44-57_372914_1039/sockets/plasma_store', 'RayletSocketName': '/tmp/ray/session_2019-05-23_09-44-57_372914_1039/sockets/raylet', 'Resources': {'CPU': 2.0}}, {'ClientID': 'fe1fbdc6b54fda7b1684d6b2a746c882b4884735', 'EntryType': 0, 'NodeManagerAddress': '10.0.0.40', 'NodeManagerPort': 44027, 'ObjectManagerPort': 41425, 'ObjectStoreSocketName': '/tmp/ray/session_2019-05-23_09-44-57_372914_1039/sockets/plasma_store', 'RayletSocketName': '/tmp/ray/session_2019-05-23_09-44-57_372914_1039/sockets/raylet', 'Resources': {'CPU': 4.0}}]`


Also, a few minutes after running the above test I got:
`2019-05-23 09:51:30,601     ERROR worker.py:1678 -- Failed to connect to ray node fe1fbdc6b54fda7b1684d6b2a746c882b4884735 with status: IOError: Connection timed out. This may be since the node was recently removed.
(pid=1065, ip=78.141.207.129) Traceback (most recent call last):
(pid=1065, ip=78.141.207.129)   File "/root/tf2/lib/python3.6/site-packages/ray/workers/default_worker.py", line 98, in <module>
(pid=1065, ip=78.141.207.129)     ray.worker.global_worker.main_loop()
(pid=1065, ip=78.141.207.129)   File "/root/tf2/lib/python3.6/site-packages/ray/worker.py", line 1041, in main_loop
(pid=1065, ip=78.141.207.129)     task = self._get_next_task_from_raylet()
(pid=1065, ip=78.141.207.129)   File "/root/tf2/lib/python3.6/site-packages/ray/worker.py", line 1024, in _get_next_task_from_raylet
(pid=1065, ip=78.141.207.129)     task = self.raylet_client.get_task()
(pid=1065, ip=78.141.207.129)   File "python/ray/_raylet.pyx", line 245, in ray._raylet.RayletClient.get_task
(pid=1065, ip=78.141.207.129)   File "python/ray/_raylet.pyx", line 60, in ray._raylet.check_status
(pid=1065, ip=78.141.207.129) Exception: [RayletClient] Raylet connection closed.
(pid=1065, ip=78.141.207.129)
(pid=1065, ip=78.141.207.129) During handling of the above exception, another exception occurred:
(pid=1065, ip=78.141.207.129)
(pid=1065, ip=78.141.207.129) Traceback (most recent call last):
(pid=1065, ip=78.141.207.129)   File "/root/tf2/lib/python3.6/site-packages/ray/workers/default_worker.py", line 105, in <module>
(pid=1065, ip=78.141.207.129)     driver_id=None)
(pid=1065, ip=78.141.207.129)   File "/root/tf2/lib/python3.6/site-packages/ray/utils.py", line 68, in push_error_to_driver
(pid=1065, ip=78.141.207.129)     time.time())
(pid=1065, ip=78.141.207.129)   File "python/ray/_raylet.pyx", line 298, in ray._raylet.RayletClient.push_error
(pid=1065, ip=78.141.207.129)   File "python/ray/_raylet.pyx", line 60, in ray._raylet.check_status
(pid=1065, ip=78.141.207.129) Exception: [RayletClient] Connection closed unexpectedly.
(pid=1064, ip=78.141.207.129) Traceback (most recent call last):
(pid=1064, ip=78.141.207.129)   File "/root/tf2/lib/python3.6/site-packages/ray/workers/default_worker.py", line 98, in <module>
(pid=1064, ip=78.141.207.129)     ray.worker.global_worker.main_loop()
(pid=1064, ip=78.141.207.129)   File "/root/tf2/lib/python3.6/site-packages/ray/worker.py", line 1041, in main_loop
(pid=1064, ip=78.141.207.129)     task = self._get_next_task_from_raylet()
(pid=1064, ip=78.141.207.129)   File "/root/tf2/lib/python3.6/site-packages/ray/worker.py", line 1024, in _get_next_task_from_raylet
(pid=1064, ip=78.141.207.129)     task = self.raylet_client.get_task()
(pid=1064, ip=78.141.207.129)   File "python/ray/_raylet.pyx", line 245, in ray._raylet.RayletClient.get_task
(pid=1064, ip=78.141.207.129)   File "python/ray/_raylet.pyx", line 60, in ray._raylet.check_status
(pid=1064, ip=78.141.207.129) Exception: [RayletClient] Raylet connection closed.
(pid=1064, ip=78.141.207.129)
(pid=1064, ip=78.141.207.129) During handling of the above exception, another exception occurred:
(pid=1064, ip=78.141.207.129)
(pid=1064, ip=78.141.207.129) Traceback (most recent call last):
(pid=1064, ip=78.141.207.129)   File "/root/tf2/lib/python3.6/site-packages/ray/workers/default_worker.py", line 105, in <module>
(pid=1064, ip=78.141.207.129)     driver_id=None)
(pid=1064, ip=78.141.207.129)   File "/root/tf2/lib/python3.6/site-packages/ray/utils.py", line 68, in push_error_to_driver
(pid=1064, ip=78.141.207.129)     time.time())
(pid=1064, ip=78.141.207.129)   File "python/ray/_raylet.pyx", line 298, in ray._raylet.RayletClient.push_error
(pid=1064, ip=78.141.207.129)   File "python/ray/_raylet.pyx", line 60, in ray._raylet.check_status
(pid=1064, ip=78.141.207.129) Exception: [RayletClient] Connection closed unexpectedly.`

**Comment by elysiumHL** [comment]
#### I encountered the same issue
##### on the head
```
ray start --redis-port 16379 --redis-shard-ports 16380 --object-manager-port 18080 --node-manager-port 18081 --head --include-webui

Python 3.6.8 (default, Apr 25 2019, 21:02:35) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init(redis_address='localhost:16379',log_to_driver=True)
2019-05-24 09:05:42,564	WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2019-05-24 09:05:43,569	WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2019-05-24 09:05:44,573	WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2019-05-24 09:05:45,578	WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2019-05-24 09:05:46,582	WARNING services.py:142 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
```

**Comment by rkooo567** [comment]
I think this should've been fixed int he master. Please try again and reopen if it is still the case!
