### ISSUE TITLE
[rllib] DDPG Custom Models

### ISSUE THREAD

**Issue by bbalaji-ucsd** [ray-project/ray#4827]
### Describe the problem
It looks like DDPG algorithm doesn't use custom models unless you specify this algo specific parameter called `"use_state_preprocessor"`. And even after that it adds a couple of hidden layers with another config called `"critic_hiddens"`. This is inconsistent with the expectation set by custom model documentation. 

### Source code / logs
Code that enforces `"use_state_preprocessor"` : https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/ddpg/ddpg_policy_graph.py#L402 

Code that uses `"critic_hiddens"`: https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/ddpg/ddpg_policy_graph.py#L413

**Comment by mdeib** [comment]
It looks as though this still needs addressed. In addition to being extremely clunky there also does not seem to be any way to get the model on the GPU with pytorch due to tensors in the ddpg_torch_model.py file being defaulted onto the CPU. Setting a custom model should override all other model settings just like in every other RLlib algorithm to allow ease of generalization and usability.

**Comment by Graeme22** [comment]
+1 for this, not intuitive and clunky indeed

**Comment by ArturNiederfahrenhorst** [comment]
To me this seems to be disentangled nowadays. Closing because this appears to be solved and is inactive.
