### ISSUE TITLE
[RLlib] Model output action dimension doesn't match the specified action space and has attribute error when trying to compute actions.

### ISSUE THREAD

**Issue by Altman-conquer** [ray-project/ray#49226]
### What happened + What you expected to happen

I run the getting start script for [reinforcement learning](https://docs.ray.io/en/latest/ray-overview/getting-started.html) and make a  slight change at the action space because i want to try it in continous space. So I change it from gym.spaces.Discrete(2) to gym.spaces.Box(-1, 1). 

After training, the rl_module.forward_inference should produce an output with 1 dimension, but it output a tensor with shape (1,2). And the function "algo.compute_single_action(observation=obs)" also throw an error.

Below is the output of two corresponding function call.
```
print(f'1: {rl_module.forward_inference({"obs": torch.from_numpy(obs).unsqueeze(0)})}')
print(f'2: {algo.compute_single_action(observation=obs)}')
```

```
1: {'action_dist_inputs': tensor([[ 0.1184, -0.0039]])}
Traceback (most recent call last):
  File "C:\Users\24761\PycharmProjects\MyFinRL\tests\test_rllib_problem.py", line 96, in <module>
    print(f'2: {algo.compute_single_action(observation=obs)}')
  File "C:\Users\24761\miniconda3\envs\FinRL\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 2122, in compute_single_action
    policy = self.get_policy(policy_id)
  File "C:\Users\24761\miniconda3\envs\FinRL\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 1991, in get_policy
    return self.env_runner.get_policy(policy_id)
AttributeError: 'SingleAgentEnvRunner' object has no attribute 'get_policy'
```

### Versions / Dependencies

ray-2.40.0

i run code in windows 11

### Reproduction script

```
import gymnasium as gym
import numpy as np
import torch

from ray.rllib.algorithms.ppo import PPOConfig


class SimpleCorridor(gym.Env):
    def __init__(self, config):
        self.end_pos = config["corridor_length"]
        self.cur_pos = 0.0
        self.action_space = gym.spaces.Box(-1, 1, (1,), np.float32)  # left and right
        self.observation_space = gym.spaces.Box(0.0, self.end_pos, (1,), np.float32)

    def reset(self, *, seed=None, options=None):
        self.cur_pos = 0.0
        return np.array([self.cur_pos], np.float32), {}

    def step(self, action):
        print(self.cur_pos, action)

        if action[0] < 0 and self.cur_pos > 0:
            self.cur_pos -= action[0]
        elif action[0] > 0:
            self.cur_pos += action[0]
        terminated = self.cur_pos >= self.end_pos
        truncated = False
        reward = 1.0 if terminated else -0.1
        return np.array([self.cur_pos], np.float32), reward, terminated, truncated, {}

config = (
    PPOConfig().environment(
        SimpleCorridor,
        env_config={"corridor_length": 20},
    )
    .env_runners(num_env_runners=3)
)
algo = config.build()
rl_module = algo.get_module()

for i in range(1):
    results = algo.train()
    print(f"Iter: {i}; avg. results={results['env_runners']}")

env = SimpleCorridor({"corridor_length": 10})

obs, info = env.reset()
terminated = truncated = False
total_reward = 0.0
while not terminated and not truncated:
    print(f'1: {rl_module.forward_inference({"obs": torch.from_numpy(obs).unsqueeze(0)})}')
    print(f'2: {algo.compute_single_action(observation=obs)}')
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by simonsays1980** [comment]
@Altman-conquer thanks for raising this issue. This is a quick answer:

1. The output of your policy in case of a box space must be 2 b/c it outputs in this case the two parameters, mean and log standard deviation of a Normal distribution from which an action is then drawn. This is standard in deep RL. In case you are looking for a good summary of deep RL, [Spinning Up](https://spinningup.openai.com/en/latest/) by OpenAI is a good start.
2. This error is due to the fact that you use the new API stack, which is the standard today. That API stack has no `compute_single_action` anymore, but can uses a connector [`GetActions`](https://github.com/ray-project/ray/blob/master/rllib/connectors/module_to_env/get_actions.py) to draw an action from the corresponding distribution in case only action logits are given. You can take a look into our examples, e.g. [this one](https://github.com/ray-project/ray/blob/master/rllib/examples/inference/policy_inference_after_training_w_connector.py) to see how to use our `RLModule`s in inference.

**Comment by jianki1314** [comment]
Hello. I'd like to ask if the problem with your "get_policy" has been solved. Could you please tell me the solution?
thank you!!!
