### ISSUE TITLE
[RLlib] PyTorch grad_clip happens in place - Extra Grad Info Reports Unclipped Total Norm

### ISSUE THREAD

**Issue by dmadeka** [ray-project/ray#4965]
@ekl

https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/a3c/a3c_torch_policy.py#L63

https://pytorch.org/docs/master/_modules/torch/nn/utils/clip_grad.html#clip_grad_norm

**Comment by ericl** [comment]
We could set the reported norm to min(global_norm, clip_value)?

**Comment by gabiguetta** [comment]
Or add another different metric for the clipped value?
Both approaches sounds fine to me.

**Comment by richardliaw** [comment]
@gabiguetta are you interested in pushing a patch?

**Comment by Kittiwin-Kumlungmak** [comment]
Hello, guys.

How is it going with this issue.  Could anyone please verified my understanding about the grad_gnorm? 

Here, I am using A3C.

'grad_gnorm' is the grad value before clipping. Is that correct? 

So, the grad actually got clipped in the actual process, but not reporting here. Correct?

Or in my case, the grad was not clipped properly?

Because I tried changing 'grad_clip'. The grad_gnorm still roughly the same.

**Comment by christy** [comment]
Reported during RLlib office hours by Manny Vindiola, this is still a bug!
