### ISSUE TITLE
[tune] Implement BOHB

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#5100]
This is actually done already but requires some reversions in HyperBand (forcing it to have strict barriers).

**Comment by Michiel29** [comment]
If it's helpful for Triage, we are strongly looking forward to this. BOHB is a big upgrade over using Hyperband and Hyperopt separately. Was looking for this and happy to see it's on the list.

**Comment by richardliaw** [comment]
Thanks for making this comment! I actually have a fork that works already, and I just haven't gotten around to pushing it.

**Comment by Michiel29** [comment]
Great to hear! Will try it out whenever you push

**Comment by richardliaw** [comment]
Hi@Michiel29, @lisadunlap and I have merged this - could you try it out?

**Comment by Michiel29** [comment]
> Hi @Michiel29, @lisadunlap and I have merged this - could you try it out?

Yep, trying this out today. Thanks for completing it! Will let you know how it goes

**Comment by lisadunlap** [comment]
> Hi @Michiel29, @lisadunlap and I have merged this - could you try it out?

Same here!

**Comment by lisadunlap** [comment]
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/25967790/62976705-11bea780-bdd2-11e9-9d30-b4d49ae2e63d.png">

It seems to run well but this is the result I got with the default params. I think the mode should be set to 'max' instead of 'min, here is what I get when I change that 

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/25967790/62977035-cb1d7d00-bdd2-11e9-99f8-f239281c44f7.png">

**Comment by richardliaw** [comment]
Nice! Fixed in #5449.

**Comment by Michiel29** [comment]
Working great for me! Thanks!
