### ISSUE TITLE
No more upload wheels on all commits?

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#5190]
It seems like in `ray-wheels` s3 bucket, the commit wheels stopped appearing after https://github.com/ray-project/ray/commit/c3f8fc1c44e4fe2219a3356cc2b28527d2de196b. 

Is there a new location for these commits?

cc @robertnishihara @devin-petersohn

**Comment by pcmoritz** [comment]
They are in a different place now, under /master: see
https://github.com/ray-project/ray/pull/4949

**Comment by richardliaw** [comment]
Ah, thanks.

**Comment by robertnishihara** [comment]
To elaborate on the reason for this, before we were only building wheels for commits on the master branch. We changed it to build commits for wheels on all branches because we want to build wheels automatically for release branches. However, if we cherry-pick a commit from the master branch to a release branch, then both commits can have the same commit ID, and hence using the old convention, the wheels would override each other in the S3 bucket. To fix this issue, we now prefix all of the wheels with the branch name before the commit.

Ideally we'd go back and rename all of the older wheels to use the new convention.
