### ISSUE TITLE
Bazel/Protobuf build errors: LD_LIBRARY_PATH doesn't get searched

### ISSUE THREAD

**Issue by mawright** [ray-project/ray#5274]
### System information
- **OS Platform and Distribution**: Scientific Linux 7
- **Ray installed from (source or binary)**: Attempted source install
- **Ray version**: commit bf9199ad77b7ea900aefd2624374c78a6e6c49d8
- **Python version**: 3.6
- **Exact command to reproduce**: pip install -e . --verbose

### Describe the problem
Running `pip install -e .` under ray/python as instructed in the install instructions fails. In the log excerpt pasted below, a compiler seems to complain that it cannot find certain symbols in libstdc++.so. In this system, the copy of libstdc++.so in /lib64/ is very old. Instead, before trying to build from source I prepend to LD_LIBRARY_PATH a directory with a newer version. The log excerpt seems to show that one of the compiler calls doesn't get LD_LIBRARY_PATH exported to it.

This seems similar to these errors where people have some methods to make sure LD_LIBRARY_PATH gets exported:
https://github.com/tensorflow/tensorflow/issues/11805
https://github.com/bazelbuild/bazel/issues/2515
https://github.com/tensorflow/tensorflow/issues/3261

### Source code / logs
```
    bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)
    bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)
    bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)
    Target //:ray_pkg failed to build
```

The full log is attached

edit: uploaded the wrong log. will retry.

**Comment by mawright** [comment]
Here's the full log of the call to pip install
[log.txt](https://github.com/ray-project/ray/files/3433147/log.txt)

**Comment by wulinze** [comment]
This problem may caused by updated gcc without changing the link file of the /lib64/libstdc++.so.6. It must have a right link to the gcc build directory

**Comment by emacs18** [comment]
I am running into the same problem building bazel 6.2.1 on CentOS 6.6.
I use newer gcc than the system provided one.  Hence I set LD_LIBRARY_PATH in the shell environment, in ~/.bashrc as well as any shell script that I could find.  However I still run into "GLIBCXX_3.4.21 not found" type of error, because /lib64/libstdc++.so.6 is used rather than the one specified by LD_LIBRARY_PATH.

How can I tell bazel build script to always use libstdc++.so.6 found in directory specified by LD_LIBRARY_PATH?
Alternately how can I add -L/path/to/my/gcc/lib64 linker flag everywhere?
How can I also add -rpath-link linker flag everywhere?
