### ISSUE TITLE
pip version and the documentation synchronization

### ISSUE THREAD

**Issue by vkurenkov** [ray-project/ray#5306]
Ray's documentation sticks to the latest version by default but this version does not correspond to the latest pip version.

It is especially confusing in rllib's [models and preprocessors ](https://ray.readthedocs.io/en/latest/rllib-models.html), where the usage of modelv2 is introduced for the first time.

**Comment by richardliaw** [comment]
Let's point `latest/` to the latest release. 

For those who want to build from master or use the latest wheels snapshot, they can go to `https://ray.readthedocs.io/en/master/installation.html` rather than `https://ray.readthedocs.io/en/latest/installation.html`

cc @robertnishihara @ericl thoughts?

**Comment by robertnishihara** [comment]
Fine with me, though it means that documentation fixes/improvements will take longer to get to users.

**Comment by richardliaw** [comment]
After internal discussion, this is intentional due to how fast the libraries are moving right now.
