### ISSUE TITLE
Function definition collision for functions with duplicate names and bodies

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#5493]
While debugging with @edoakes we ran into this strange behavior:

```python
import ray
ray.init()

i = 1 
def f(): 
    return i 
f1 = ray.remote(f)

i = 2 
def f(): 
    return i 
f2 = ray.remote(f)

ray.get(f1.remote())
# The result is "2" but should be "1".
```

The reason is because we are hashing just the function code here https://github.com/ray-project/ray/blob/master/python/ray/function_manager.py#L128 and not the environment.

One solution that might work is using cloudpickle to pickle the function (including variables it closes over) and hash that.

**Comment by robertnishihara** [comment]
Hm, so I agree that it's weird, but this is actually consistent with Python.

```python
i = 1 
def f(): 
    return i 
f1 = f

i = 2 
def f(): 
    return i 
f2 = f

assert f1() == 2
```

I believe the reason is not really about the collision (there is that issue as well, which I'm fixing in https://github.com/ray-project/ray/pull/6175), but rather that we are lazily pickling the remote function the first time the remote function is invoked.

So I think this is actually the intended behavior.

Of course, the consistency with Python only goes so far. If you change `i` again, then that won't have any effect on the remote function.

**Comment by robertnishihara** [comment]
I think it's ok to close for now though the issue is still present.
