### ISSUE TITLE
[tune] Add a PBT example for PyTorch, Keras

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#5561]
Tune could use more examples. PBT would be a great example to add for PyTorch, Keras.

**Comment by martsalz** [comment]
Also for regression tasks

**Comment by hhbyyh** [comment]
Hi @richardliaw Just want to check if this is still open for contribution, since there's already a pbt +keras example and pytorch + PBT PR https://github.com/ray-project/ray/pull/5679. Thanks. 

I'm thinking DCGAN might be interesting for Pytorch (maybe too big?), or maybe just simple text classification.

**Comment by richardliaw** [comment]
@hhbyyh can never have enough examples - DCGAN would be awesome! In fact, a walkthrough would be amazing :)
