### ISSUE TITLE
Make it possible to accept some version mismatches?

### ISSUE THREAD

**Issue by johann-petrak** [ray-project/ray#5787]
Currently Ray is very picky about version of python, Pyarrow and Ray which have to match between a running cluster and client code. 

This will even fail if the difference is e.g. Python 3.6.7 vs. Python 3.6.8 
Would it be possible/reasonable to allow for such minor version discrepanices, at least by deliberately setting some config options or environment variable?

**Comment by pcmoritz** [comment]
Hey Johann,

The reason why we do this for python versions is because we use cloudpickle to serialize python code and ship it between different python processes. Python bytecode is not stable between python versions (see https://nedbatchelder.com/blog/200804/the_structure_of_pyc_files.html). It might be that it is stable between patch releases like 3.6.7 or 3.6.8, I don't know. But even if that is the case, it is still dangerous to have different environments, e.g. if versions of the installed packages are different you might run into compatibility problems. So I would recommend against it.

What is your use case? Are you trying to have a driver on your laptop that connects to a cluster? Making sure the versions agree would be the safest choice in that case.

Best,
Philipp.

**Comment by johann-petrak** [comment]
Thank you, I have seen the version dependency of cloudpickle now and for that reason it indeed makes a lot of sense to be that picky!

My use case was experimenting with a cluster where some of the nodes had a *slightly* different anaconda installation where for some reason or other the python differed in the last digit (and I was too lazy to create a separate environment just for testing).
However, creating a conda environment with a matching version is not too much hassle anyway.

I take back my feature request :)
