### ISSUE TITLE
Workload creates an unbounded number of actor handles.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#5814]
This may be a duplicate of https://github.com/ray-project/ray/issues/2798 (so I'm closing the other one). I just ran into this with @simon-mo in ray serve. This seems to be causing a gradual slowdown over time and also periodic latency spikes.

```python
import ray
ray.init()

@ray.remote 
class Foo: 
    def __init__(self): 
        self.i = 0 
        self.timestamps = [] 

    def run(self, handle): 
        print(self.i) 
        self.i += 1 
        self.timestamps.append(time.time()) 
        if self.i > 1000: 
            return 

        handle.run.remote(handle) 

    def get_timestamps(self): 
        return self.timestamps

f = Foo.remote()
f.run.remote(f)
```

When running this workload, I wasn't able to detect a slowdown, but I suspect I would see it if running the workload much longer.

If you check the debug state, you can see the max number of actor handles is growing unbounded.

TODO:
- Can we garbage collect the unused actor handles in the raylet (e.g., when they go out of scope in Python)? @stephanie-wang 
- We should push an error to the user when the actor handle count grows very large (so they know this is happening). Just the first time it happens. @simon-mo 
- We should display the number of actor handles in the web UI for each actor so that the user can see it easily there. @mitchellstern

**Comment by ericl** [comment]
How about we make the handle id deterministically (curworkerid, actorid). This deduplicates it by worker (there's no need for unique IDs per handle, just per worker).

**Comment by ericl** [comment]
Or remove actor handle id altogether, substituting (client ID, actor ID) as needed?

**Comment by stephanie-wang** [comment]
Yes, I think we should just use the actor or task ID of the submitter instead of generating a new handle ID each time. We'll have to keep some state on the worker about what actor "handles" it has in scope. I think this state should just be the actor ID and the sequence number of the last task that it submitted to that actor.

**Comment by stephanie-wang** [comment]
@edoakes and I discussed today and we think we should try the following:
- Replace actor handle IDs with the client ID (either the actor or task ID of the submitter). Each handle's state will be this client ID, the task counter for the last task that was submitted on the handle, and whether the handle is active.
- When the Python handle instance goes out of scope, mark the handle as inactive.
- If another handle is created for the same actor on this client, throw an exception to the client telling them to only use one handle per actor and client. This is so that we can catch issues like this one and issues where the same actor handle is unpickled twice by the same client.

Thoughts?
