### ISSUE TITLE
Upgrade cloudpickle

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#594]
The current tip of cloudpickle has a few fixes, including https://github.com/cloudpipe/cloudpickle/pull/88 and  hopefully soon https://github.com/cloudpipe/cloudpickle/pull/90 so we should upgrade once this is merged!

**Comment by robertnishihara** [comment]
What do you mean by upgrade? If we wait a little while then the changes will be included in a cloudpickle 2.3 and the upgrade will happen for free. The alternative I suppose is to change the installation instructions to install cloudpickle from a specific github URL instead of with `pip install cloudpickle`.

**Comment by robertnishihara** [comment]
Closing, because this will happen automatically with the next cloudpickle release.

**Comment by robertnishihara** [comment]
This latest release has the fixes https://github.com/cloudpipe/cloudpickle/releases/tag/v0.3.0.
