### ISSUE TITLE
how to print the message of enviroment in RL?

### ISSUE THREAD

**Issue by 1576012404** [ray-project/ray#6100]
System information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
Ray installed from (source or binary): pip3 install ray
Ray version: ray-0.8.0.dev6
Python version: 3.6.0

it seems that message printed in workers are ignored when i use print in the functions of environments,for example the reset,step functions in env. i can not see any print message in terminal.why?

**Comment by pengzhenghao** [comment]
A lot of places you need to concern when using print inside a remote function / worker.

First is when you initialize ray:
```
        ray.init(
            logging_level=logging.ERROR if not test_mode else logging.DEBUG,
            log_to_driver=True
        )
```
make sure log_to_driver is set and the logging_level is proper.

Second, if you using `tune.run` to train your agent, make sure the `log_level` in config passing into run is properly set.

Another way to debug is to set `ray.init(local_mode=True)` so that you can see the pring message.

**Comment by 1576012404** [comment]
thank you very much!

**Comment by 1576012404** [comment]
an other question
when i shutdown the process, ray is still running. so i run this process again, process will start fail due to   memory is full. so how to shutdown process safely.
in chineses:终止程序后，ray还在后台运行，重新启动程序，内存瞬间暴增，是终止程序的方式不对？

**Comment by pengzhenghao** [comment]
In command line:

1. `killall python`
2. `ray stop`

Or in python files `ray.shutdown()`.
I do it all the times by `ray.shutdown();ray.init()` in jupyter notebook when debugging :) 不客气
