### ISSUE TITLE
Publish tar.gz source archive to pypi

### ISSUE THREAD

**Issue by yizhexu** [ray-project/ray#6246]
I'm looking to leverage ray tune for my project at work. Due to legal requirement, my company asks researchers to submit package source archive on pypi to them so that they can review whether the content is banned by them or not.

Therefore I request maintainers to also upload a source archive to pypi. I believe when creating the whl format, an additional sdist argument would allow a tar.gz source archive. `python setup.py sdist bdist_wheel` for example. Then if you upload both tar.gz and whl to pypi at your release, it'd suffice my needs. 

Thank you!

**Comment by richardliaw** [comment]
cc @edoakes, who is managing the next release?

**Comment by edoakes** [comment]
You can also get the release source archives here:
https://github.com/ray-project/ray/releases

Does that work for you?

**Comment by yizhexu** [comment]
No, github release won't work for me cause my company didn't support that... Must through Pypi. Thank you!

**Comment by edoakes** [comment]
We discussed this, but unfortunately it will be a nontrivial amount of work due to how we have the code laid out and will result in some adverse effects we'd have to handle (e.g., `pip install` on Windows will try to build from source). If there is anything else that would work for you aside from uploading the source dist to PyPI, let me know, otherwise we'll keep this on our radar and try to handle it soon.
