### ISSUE TITLE
the initialization of actor

### ISSUE THREAD

**Issue by raopku** [ray-project/ray#653]
```

import ray
@ray.remote
class Counter(object):
  def __init__(self):
    self.value = 0

  def increment(self):
    self.value += 1
    return self.value
```
successs
```
a1 = Counter.remote()
a2 = Counter.remote()
```
failed:
```
cpu_acotr = ray.remote(num_gpus=0)(Counter)
cpu_acotr.remote()
```
the error log 
```
The function remote has a **kwargs argument, which is currently not supported.
The function _manual_init has a **kwargs argument, which is currently not supported.
The function __init__ has a **kwargs argument, which is currently not supported.
```

however i want to specify gpu resource used by actor dynamically instead of in the defination of actor like `@ray.remot(num_gpus=1)`. it is necessary for the development of general algorithm library base on ray.
I use ray 0.1.1
the error log looks strange

**Comment by pcmoritz** [comment]
Hey raopku,

the problem here is that you are trying to make a python class a remote class which is already a remote class. Remember that @ray.remote is for creating remote classes, not for instantiating them. The following should achieve what you want to do:

```
class Counter(object):
  def __init__(self):
    self.value = 0

  def increment(self):
    self.value += 1
    return self.value

CpuCounter = ray.remote(num_gpus=0)(Counter)
GpuCounter = ray.remote(num_gpus=1)(Counter)
```

and then instantiate the remote class (i.e. create an actor) like so

```
cpu_actor = CpuCounter.remote()
gpu_actor = GpuCounter.remote()
```

and then call it like

```
cpu_actor.increment.remote()
gpu_actor.increment.remote()
```

We are not giving a very good error message here and I'll keep the issue open until that is fixed!

Best,
Philipp.

**Comment by raopku** [comment]
Thank you. @pcmoritz 
` Remember that @ray.remote is for creating remote classes, not for instantiating them`
this helps me.
I had a redundant @ray.remote in the defination of Counter.
