### ISSUE TITLE
Allow for head to connect to workers

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#655]
Currently workers connect to head (or head's Redis). It would be great if it would be possible also to invert this. Then we could install workers on few machines and they would wait there running, until I run a head on my laptop which would connect to workers and workers would start pulling tasks from my laptop. This would help during development.

**Comment by mitar** [comment]
One other option would be to allow Redis server to be running independently from head. Then head could just connect to the Redis server.

**Comment by robertnishihara** [comment]
I see, it sounds like the main thing you want is to be able to develop from your laptop without having to ssh to a cluster, is that right?

The "head" could run on the cluster, and you could try running a "worker" on your laptop, for example, you can try the following.

On a remote machine, run the following (replacing the node IP address with something more correct).

```
ray start --head --redis-port=6379 --node-ip-address=123.45.67.89
```

On your laptop, run the following (replacing the node IP address with something more correct). Note that `--num-cpus=0` should prevent tasks from being scheduled on your laptop.

```
ray start --redis-address=123.45.67.89:6379 --node-ip-address=98.765.43.21 --num-cpus=0
```

Then run your script on your laptop using

```
ray.init(redis_address="123.45.67.89:6379")
```

**Note:** You'll have to make sure that your laptop and the remote machines can all communicate with each other properly (in both directions) using the provided IP addresses.

**Note:** I manually specified the node IP addresses because otherwise Ray will try to determine the node IP addresses itself using `ray.services.get_node_ip_address()`. On EC2 instances, this will find the node's private IP address, which your laptop will then use when trying to pull objects from the cluster, but it presumably needs to use the node's public IP address.

I think the above might work, but I'm not 100% sure.

**Comment by mitar** [comment]
Interesting. So any worker can submit tasks. It seems reasonable in retrospect. :-)

**Comment by robertnishihara** [comment]
Yeah, in fact, we really don't need the concept of a "head" node. The head node runs a few extra processes, but it'd be fine for these processes to run on any machine (and they can all run on different machines). The advantage of having them all run on the same machine is just that it simplifies the start up scripts a bit.

**Comment by mitar** [comment]
So what I am used to is to configure cluster on my own. So I would just have a Docker container with Redis, and then spawn few different containers for Ray. So my question is if you could document which exactly things are needed if I would run them manually.

**Comment by robertnishihara** [comment]
So, it depends on the level of granularity desired. For example, one reasonable thing to do would be to have one Docker container per machine. In the first Docker container, you would run something like `ray start --head --redis-port=6379 --num-redis-shards=3`. In the other Docker containers, you would run something like `ray start --redis-address=123.45.67.89:6379`, where you place `123.45.67.89` with the IP address of the first container.

Conceptually it makes perfect sense to have Redis running in its own Docker container (note we actually use multiple redis servers). We should probably change things to make this a bit easier

One completely different extreme, which isn't really supported, but can be done (we only do this for debugging if we need to start some processes in gdb) is to start each process separately. We have outdated instructions for doing this in this comment https://github.com/ray-project/ray/issues/108#issuecomment-292884182. However, these instructions are out of date.

I'll think over how to best do the thing you're trying to do.

**Comment by robertnishihara** [comment]
Ok, the instructions in this comment https://github.com/ray-project/ray/issues/108#issuecomment-308572084 should work for starting all of the processes on the head node separately.

**Comment by robertnishihara** [comment]
Closing for now. Feel free to reopen.
