### ISSUE TITLE
cross validation hyperparameter tuning

### ISSUE THREAD

**Issue by hugwi** [ray-project/ray#6560]
Is there any obvious reason that none of the examples for tune hyperparameter optimization is not using any form of cross validation? I know for instance that ASHA is built upon the idea that we can still compare relative performance with few iterations, but if we only uses a 20% of the data as validation, it's sufficient to compare the relative performance of hyperparameters?

**Comment by hugwi** [comment]
Is it only due to cross validation being too computationally heavy?

**Comment by richardliaw** [comment]
Yeah we don't have any cross validation examples mainly because it's typically not used in DL research. Also, every framework has its own recommended way to do cross validation, so it was implicit that the user would implement cross-validation themselves.

On the other hand, @anthonyhsyu and @inventormc have been working on https://github.com/ray-project/tune-sklearn which should provide cross validation support out of the box. It is still in pre-alpha so feel free to open issues/feature requests.

**Comment by edoakes** [comment]
Stale - please open new issue if still relevant

**Comment by mlguruz** [comment]
> Stale - please open new issue if still relevant

Hi all, 

I've been playing around with the idea of injecting **dependencies** on trials, and not sure what's the best way to do this? 

Cross validation can be thought of as an example, where the final score *depends on* each fold's result, which themselves could be separate Trials. 

I've looked at the `Repeater` *workaround*, and it helps a lot as in maybe, we could inject the **trial-wise dependencies** btw Trainable's `step` and Searcher's `suggest` and `on_trial_complete`, as we could store info in the config that is passed around. 

However, I'm not sure if this is the right path. Really looking for some suggestions here. 

Thanks!
