### ISSUE TITLE
Spurious warning message when submitting many tasks.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#6722]
```python
import ray

ray.init()

@ray.remote 
def double(x): 
    return x * 2

results = [double.remote(i) for i in range(100000)]

ray.get(results)
```

Running the above in IPython succeeds but prints the following warning.

**(pid=78589) [libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/wire_format_lite.cc:603] String field 'ray.rpc.CoreWorkerStats.current_task_func_desc' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.**
**(pid=raylet) [libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/wire_format_lite.cc:603] String field 'ray.rpc.CoreWorkerStats.current_task_func_desc' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.**

Note that the `ray.get` is not necessary to trigger the warning.

**Comment by robertnishihara** [comment]
cc @raulchen @zhijunfu in case you have some ideas about this.

**Comment by raulchen** [comment]
I haven't seen this error before.

**Comment by zhijunfu** [comment]
I haven't seen this either.

**Comment by ericl** [comment]
I think this is a warning related to stats collection
```
677004ee3d (Eric Liang     2019-12-28 14:40:32 -0800 1168)   if (!current_task_.TaskId().IsNil()) {
677004ee3d (Eric Liang     2019-12-28 14:40:32 -0800 1169)     stats->set_current_task_desc(current_task_.DebugString());
65acb54553 (Yunzhi Zhang   2019-12-30 13:08:08 -0800 1170)     for (auto const it : current_task_.FunctionDescriptor()) {
65acb54553 (Yunzhi Zhang   2019-12-30 13:08:08 -0800 1171)       stats->add_current_task_func_desc(it);
65acb54553 (Yunzhi Zhang   2019-12-30 13:08:08 -0800 1172)     }
65acb54553 (Yunzhi Zhang   2019-12-30 13:08:08 -0800 1173)   }
```

something to do with the types passed to that snippet above. cc @zzyunzhi

**Comment by ericl** [comment]
I think this can be solved by following the warning's recommendation and setting the proto field type to raw bytes.

**Comment by raulchen** [comment]
I just thought of a possible cause. When `--load-code-from-local` is not set, Python's function descriptor contains a fourth element, which is the hash value of the source code. This element is raw binary and not UTF-8-decodable.  But I don't see how it's related with many tasks.

To fix this issue, I think we can just make `CoreWorkerStats.current_task_func_desc` a single concatenated string, instead of `repeated string`. 

Also, @fyrestone is refactoring `FunctionDescriptor` as part of the cross-lang feature. He'll add a c++ class to represent function descriptor. So dealing with such problems will be easier after that.

**Comment by ericl** [comment]
I think the only relation to many tasks is that it delays exit until the first stats heartbeat.

**Comment by pcmoritz** [comment]
fixed by https://github.com/ray-project/ray/pull/6752
