### ISSUE TITLE
[streaming]why use actor

### ISSUE THREAD

**Issue by ancrs** [ray-project/ray#6741]
As I thought, when use the `map` operator, task(stateless) is enough; and `reduce` need actor(stateful). Why all works is actor in streaming, what's the pros

**Comment by raulchen** [comment]
@chaokunyang @liangyi123 can you help answer this question?

**Comment by chaokunyang** [comment]
Hi @ancrs, `map` operator can has state too. For example, flink calls it as [operator-state](https://ci.apache.org/projects/flink/flink-docs-release-1.9/dev/stream/state/state.html#operator-state).

Since `task` in ray are stateless, and `actor` is stateful, we choose actor to execute all operators.

**Comment by chaokunyang** [comment]
We are rewriting streaming python api, current streaming python api will be dropped soon. Please take a look at #6755 .
