### ISSUE TITLE
[tune] how to do distributed training one trial on two machines?

### ISSUE THREAD

**Issue by JiayuanSternLi** [ray-project/ray#6806]
### What is your question?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.5
TF 2.0.0
ubuntu 16.04
Ray 0.8.0dev

I have two v100 machines with 8*2 v100 GPUs
When doing distributed training, how could we run one trial on two machines? I want to test the training speed on these experiments: 
1 machine with 8 GPUs  VS 2 machine with 4 GPUs from each

However, I found that one trial could only run on one machine even though I have two machines connected:
![image](https://user-images.githubusercontent.com/33815430/72507770-78fbee80-387f-11ea-8970-2ce016eab7f5.png)

**Comment by hhbyyh** [comment]
cc @richardliaw Shall we add an example for this?

**Comment by richardliaw** [comment]
Yeah @hhbyyh, sounds good.

@JiayuanSternLi Out of the box, this won't work because TF doesn't automatically parallelize across different nodes. 

However, you should use the experimental TFTrainer (https://ray.readthedocs.io/en/latest/tf_distributed_training.html). This will allow you to distribute your TF2.0 model training setup across multiple nodes easily.

**Comment by dorcus01** [comment]
Hi, I have the same issue regarding allocating GPU resources among multiple nodes for one training task. When I'm doing hyperparameter tuning in ray, each node has a single GPU, but I want to use 2 GPUs for each training task. How can I achieve this?
