### ISSUE TITLE
[dashboard] Don't show idle workers in the dashboard

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#6954]
### Describe your feature request

One thing that’s a bit confusing about the dashboard right now is the worker counts. For example, when running actors it often shows more workers than cores, which could be confusing to those who aren’t familiar with how ray is implemented. I think it would be better if we just didn’t show IDLE  workers at all (or maybe have an off-by-default toggle to show them).

<img width="194" alt="Screen Shot 2020-01-29 at 1 12 24 PM" src="https://user-images.githubusercontent.com/9871461/73398158-ccb40200-4299-11ea-85b1-521059d52021.png">

**Comment by JackJHarris** [comment]
One side effect of hiding the the ray::IDLE processes from the dashboard is that it also hides where resources are being used by ray (e.g.,  system memory )

Although not explicit in the dashboard: an additional resource consumed by IDLE worker is redis connections.
Knowing the total number of workers (including those in ray::IDLE state) can help understand why a large job is failing due to max connection limitations (especially on system  with locked down `ulimit -n` configurations)

**Comment by rkooo567** [comment]
cc @mfitton Can you tag this issue to your sort/grouping PR and close it once that's merged?
