### ISSUE TITLE
[Dashboard] Documentation

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#7025]
From @richardliaw:

>  I really do think the dashboard will help Ray (and Tune, RLlib) users across the board, even at its current state!
“documenting the dashboard” means outlining its features and demo-ing use case. in other words, the documentation should answer three questions: “what is the dashboard, how do I use/install it, and why would I use it” (having a couple lines on the installation page really isn’t enough). Here is a good example: https://www.tensorflow.org/tensorboard/get_started

@ijrsvt do you want to take a crack at this?

**Comment by ijrsvt** [comment]
Sure!

**Comment by dclong** [comment]
Agree that we need more documentation on Ray Dashboard. I tried to set up a ray private cluster manually. The cluster works but I couldn't figure out how to use the Dashboard. It says that visit the Dashboard at localhost:8265. I assume localhost means the head node? However, visiting head_node_ip:8265 doesn't work for me. I'm using Ubuntu 18.04 and Ray 0.8.2. Below are the commands that I used to install nodejs and Ray. 
```
sudo apt-get install nodejs
pip3 install ray[debug,dashboard]
```

**Comment by pcmoritz** [comment]
@dclong By default, the dashboard just listens on `127.0.0.1`, which is why you can only access it from the node itself (i.e. through localhost). If you want to access it through a public IP, you need to pass an additional parameter in ray.init, i.e. you need to run `ray.init(webui_host="0.0.0.0")`. This will make it so the dashboard listens on all IP addresses, including the public one. Make sure to restrict access in that case, a dashboard that is open to the public is a security risk (that's why listening on `127.0.0.1`/localhost is the default).

@ijrsvt Can we include this information in the documentation?

**Comment by simon-mo** [comment]
@rkooo567 is working on this in #7304

**Comment by dclong** [comment]
@pcmoritz Thank you for the clarification! Can I pass a similar parameter when I start the head node using the command `ray start --head`?

**Comment by simon-mo** [comment]
Yes the argument is 
https://github.com/ray-project/ray/blob/d8eeb9641314740572e81f9836cbce3e5b8f2b73/python/ray/scripts/scripts.py#L203-L215

**Comment by dclong** [comment]
@simon-mo That's cool. Thank you very much!

**Comment by Data-drone** [comment]
can we specify a listen port for ray dashboard?

**Comment by rkooo567** [comment]
Done with #7304
