### ISSUE TITLE
[tune] When would explore function be called at pbt?

### ISSUE THREAD

**Issue by sherylwang** [ray-project/ray#7168]
Hi, I'm using pbt for hyperparameter searching. I'm wondering when would the explore function be called. Does it only be called after the exploit function(after cloning the weight  and hyperparameters from good model to poor model)?

**Comment by waldroje** [comment]
One simple situation is to control interaction between hyperparameters, example... . ensure that "train_batch_size" >= "sample_batch_size", if those two parameters where being updated.... so it could look something like this.

```
def explore(config):
    if "train_batch_size" in config:
        config["train_batch_size"] = max(config["train_batch_size"], config["sample_batch_size"])
```

**Comment by sherylwang** [comment]
I haven't found the meaning of sample_batch_size in tune. Is this a original parameter of tune? @waldroje

**Comment by waldroje** [comment]
rllib.Trainer inherits fromtune.Trainable, and rllib.Trainer has default config, which you can view in the code... has a pretty good explanation for most of the default configuration, of which includes both sample_batch_size and train_batch_size.

**Comment by krfricke** [comment]
Hi @sherylwang, this is an old issue but I'll still answer it. Yes, the explore function is only called after exploiting. This makes sense because otherwise you would train two trials with the same parameters from the same checkpoint, and should get very similar results. Exploring after exploiting ensures that you end up with a different configuration to continue your training.

The rest of the parameters seem to be relate to rllib.

For constraints in the parameters you can use a custom explore function that handles these cases. E.g. the function defined by @waldroje.

Please feel free to re-open or open a new issue if you still have questions.
