### ISSUE TITLE
Why is Redis mandatory for using Ray?

### ISSUE THREAD

**Issue by thedrow** [ray-project/ray#7239]
### What is your question?

It is not clear from the documentation why is Redis needed or that it is needed at all.

The installation guide only mentions that you need to specify a Redis port or one will be picked at random.
That implies that the Redis executable must be present alongside Ray but it isn't directly specified.

Can Redis be replaced with other backends or is there something unique that we use Redis for?

**Comment by thedrow** [comment]
@ray-project Can someone please address this question?

**Comment by sumanthratna** [comment]
> It is not clear from the documentation why is Redis needed or that it is needed at all.

[from the ray 1.0 whitepaper](https://docs.google.com/document/d/1lAy0Owi-vPz2jEqBSaHNQcy2IBSDEHyXNOQZlGuj93c/preview#heading=h.vgylh5bif9mk):
> The GCS is currently implemented in Redis, and we rely on Redis for pub-sub. However, an effort is underway to remove the redis dependency and enable pluggable persistent storage (e.g., MySQL).

> This holds the node locations of large shared memory objects. Raylets use redis pub-sub to get notified when an object they are interested in becomes available, and to pick a node to download object data from. When an object is created or deleted locally in shared memory, raylets are responsible for updating this table.

---

> Can Redis be replaced with other backends or is there something unique that we use Redis for?

not yet, but as mentioned above, redis may eventually be removed as a dependency.

**Comment by rkooo567** [comment]
Just to add more explanation, Redis is the data plane of the Ray cluster which stores cluster-level metadata. For example, it stores the state or Ray nodes or actors (like where actors are). 

Redis was hard dependency to Ray before, but as mentioned in the paper, we are moving towards removing it from a hard dependency. We built a new component gcs_server which can have pluggable backend (Redis by default). There are still more work to be done in order to remove Redis from hard dependency after 1.0.

**Comment by Jack47** [comment]
so redis is not a mandatory since  ray 1.10, see this ray blog:
https://www.anyscale.com/blog/redis-in-ray-past-and-future

**Comment by stefanbschneider** [comment]
>  ray 1.10

The blog says it's from Ray 1.11 onward.
