### ISSUE TITLE
Option to use hostnames instead of explicit ip addresses

### ISSUE THREAD

**Issue by rahulpalamuttam** [ray-project/ray#741]
Can we start ray using hostnames for the redis_address instead of an explicit IP?
This might be difficult to do correctly on the master node.
However, it should be easy on the worker node, and really only matters for the worker nodes connecting to the master.

Currently, plasma manager complains if a hostname is supplied instead of an IP.
The issue is [parse_ip_addr](https://github.com/ray-project/ray/blob/master/src/plasma/plasma_manager.cc#L1749) is returning -1 since the following [regex](https://github.com/ray-project/ray/blob/master/src/common/net.cc#L11) doesn't capture hostnames.

A simple quick fix I found was changing "%15[0-9.]:%5[0-9]" to "%[^:]:%5[0-9]".
There's probably a more careful way to do this using strtok.

**Comment by robertnishihara** [comment]
Did that fix end up working for you? That is, did your application successfully run after that change?

There are other places in the code base where we use IP addresses. For example, internally, when we start up a plasma manager, we tell it its own IP address, which it stores in Redis, and which other plasma managers use to connect to it (all of the plasma managers need to be able to get objects from all of the other plasma managers). That may not matter for your use case because you don't have to provide those IP addresses.

Out of curiosity, can you elaborate on why using hostnames instead of IP addresses is easier with your setup? Is it a matter of convenience or does something break when using IP addresses?

**Comment by rahulpalamuttam** [comment]
Right now it's a matter of convenience for when you want to spin up a ray cluster using docker-compose. Docker-compose allows you to define services and link them to each other. 

Imagine having two services, master (for ray master) and worker (for ray workers). You don't know what IP docker will be assign to the master service so using the hostname makes it easier.

You could explicitly set an IP when defining these services in the docker-compose.yml but it's just cleaner using hostnames. Docker-compose and Docker-swarm also makes it simple to scale these services. 

With that regex change, I've found that workers can use hostnames to connect to master via
"ray start --redis-address master:6379".

However, you still need to set the explicit IP when launching ray on the master node.
So you can't set --node-ip-address on master to its hostname.

**Comment by robertnishihara** [comment]
Fixed by #1177.
