### ISSUE TITLE
Lazy execution

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#758]
Is it possible to define a task as lazy executable? So Ray already supports re-running the task to re-create the object ID which got removed from the memory. Could there be a way to even initially say that there is no need to run the task immediately, but just give the object ID, and then when the user will call get, the task would run, if not already available?

**Comment by robertnishihara** [comment]
Do you have a use case where lazy evaluation would be helpful or important? It's certainly possible to implement this in Ray, but we'd prefer to not add additional functionality unless there is a big benefit.

It's also probably possible to implement something that wraps a remote function and only submits the task when you call `ray.get`.

But I'd be interested in knowing if you have a situation where the default behavior doesn't work well.

**Comment by mitar** [comment]
The use case is to potentially handle sets of object IDs which are larger than memory all together. For example, we would like to represent a dataset of videos like Python array of `[objectIds]`, where objectId is a decoded video into a 3D numpy array (2D frame, 1D time). And then we would like to send this dataset around. And some other functions would then go an iterate one by one on each sample (video) and do something with it. Now, if we in advance decode all videos, we will probably run out of memory and objects will start getting discarded. And when then task starts reading one by one, it will have to recreate them anyway. So putting a lazy flag could help us to hint Ray that this will happen. You can also imagine that we do a map on that list, where every worker gets a subset of videos to process. It is better that video gets decoded on demand on that same worker, than that they get decoded on one worker which happened to create the Python list of all videos, and then send over to workers who will deal with videos. We could do probably ourselves by creating subsets of videos first, but we would like to have separate dataset building and then processing of datasets. So building would create this lazy object, and then only when consumers start using it, on a worker to consume it, they will decode the video.

**Comment by rahulpalamuttam** [comment]
You might not need to implement lazy functionality within the ray system itself but have some lazy API calls that stitch together functions in a kernel, which ray then executes as a ray.remote helper function. 

I'm not incredibly familiar with the workings internally, but I believe each returned object of a ray remote function get's registered in plasma. I could be completely wrong about that but that's the only way I can see how ray gives us global object id's after a ray.remote call. It may be useful to have laziness if you want to avoid writing extra intermediate objects to plasma/arrow, but it should be done in a library that leverages ray instead of within the ray system itself for the reason @robertnishihara mentioned.

**Comment by mitar** [comment]
I think because Ray knows how to recompute every result of a task if needed, it has already 99% of thing needed to provide this. This is why I thought it would be nice to have it in Ray.

Of course everything can be solved with one more layer of abstraction. :-)

**Comment by robertnishihara** [comment]
Closing as out of scope for now.

**Comment by adrianloy** [comment]
We have a similiar use-case as the one described by @mitar : We want to transform datasets that are too large to ever be in memory together at the same time. We want to process it tile by tile (high-resolution microscopy images). Was there any progress on this issue since this issue was originally opened?
