### ISSUE TITLE
Use flatbuf instead of protobuf for task spec

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#7824]
### Brief description
Considering that flatbuf is more efficient that protobuf, and the task spec is used frequently when shipping by direct call, let's use flatbuf instead!

### Detail
1. We found that the cost of serializing/deserializing protobuf-based task-spec was too expensive when we profiling the perf. It has significantly reduced the cost after using flatbuf-based task-spec. I believe this can improve the direct call's perf.
2. The change might not be too heavy because we only change the rpc::TaskSpec from protobuf to flatbuf, and there's a `TaskSpecification` that wrappers it. The most usages is to use `TaskSpecification` on the current codebase.

@ericl @edoakes

**Comment by jovany-wang** [comment]
@raulchen @zhijunfu cc

**Comment by edoakes** [comment]
@jovany-wang can you post the results of profiling?

**Comment by jovany-wang** [comment]
@edoakes 
The flame graph that mocks a core worker is here https://qing-sth.oss-cn-beijing.aliyuncs.com/2.mock_worker.github.svg
It indicates that de/serializing costs around 25% CPU.


This page shows perfs of different components. https://google.github.io/flatbuffers/flatbuffers_benchmarks.html

**Comment by raulchen** [comment]
@jovany-wang can you also post the code of the benchmark?

**Comment by zhijunfu** [comment]
@raulchen It's just `[TestDirectActorTaskSubmissionPerf](https://github.com/ray-project/ray/blob/master/src/ray/core_worker/test/core_worker_test.cc#L668)` in core worker test, you can increase the number of tasks.

**Comment by zhijunfu** [comment]
@edoakes @ericl  Per our earlier investigations, the serialization/deserialization of `TaskSpec` protobuf is quite time consuming, and has a non-trivial impact for direct call performance. And flatbuf should be a lot faster on this perspective. 

Since we already have a wrapper of `TaskSpecification`, which is used widely, and there are few places that reference the underlying protobuf `TaskSpec` directly. This change should just replace the implementation of `TaskSpecification` to wrap on top of `flatbuf` instead of `protobuf`, the changes to other parts of code should be limited.

And other data structures that don't have a significant impact on performance can remain in `protobuf` since it's more convenient.

**Comment by edoakes** [comment]
@zhijunfu Sounds good. It would be great to prototype this and get some microbenchmark results.

**Comment by zhijunfu** [comment]
@edoakes Sure. @jovany-wang will be working on this, will update when results are ready.

**Comment by rkooo567** [comment]
@zhijunfu How's the status for this?

**Comment by zhijunfu** [comment]
@rkooo567 we made some progress on this, we had a prototype which changed TaskSpec and a few other structures to fb, and noticed some speedup on processing the tasks at the receiver side, while on the sender side there's no big difference.
