### ISSUE TITLE
[raysgd] Allow for passing options to DistributedDataParallel in DistributedTorchRunner

### ISSUE THREAD

**Issue by DavidMChan** [ray-project/ray#7854]
We have a use case where we're using "find_unused_parameters=True" in the DistributedDataParallel call  here:

https://github.com/ray-project/ray/blob/780c1c3b08d473ffa42b232586dfdbc0a0af54af/python/ray/util/sgd/torch/distributed_torch_runner.py#L87

i.e, our python code looks like: 
```python
self.models = [DistributedDataParallel(model, find_unused_parameters=True) for model in self.models]
```

Right now, we're sub-classing the three classes necessary to run the code (DistributedDataParallel, DistributedTorchRunner, and TorchTrainer), however it would be great if this behavior could be allowed in the base classes. 

I'd be happy to submit a PR for this, however it's unclear to me the cleanest way (or at least the idiomatic Ray way) to propagate the options to the root of the TorchTrainer.

**Comment by maximsmol** [comment]
So there are quite a few parameters we probably want to expose here (https://pytorch.org/docs/master/nn.html#torch.nn.parallel.DistributedDataParallel for reference). Not to mention other classes that we are creating on the inside (like `DistributedSampler`).

I think the way we're dealing with stuff like this right now is to marshal all the parameters via kwargs through Trainer then Runner then DistributedRunner (then possibly TrainingOperator), just like you said you are doing. For an example, see `data_loader_args`. This is because we try to keep `config` for the user (although we don't do a very good job not modifying it).

This isn't very good in my opinion. I think we need a better way to specify and expose system configuration.


Perhaps we should just transition the internal runner parameters to a normal dict? This way we can include a `ddp_params` key and just unwrap it internally. Similarly with `DistributedSampler`, etc. The same dict would include `data_loader_args`, `backend`, and a few others.

I think that we should keep stuff like `use_gpu`, `num_workers`, etc. in trainer kwargs because they are so commonly used.

Now I also want to note that `apex_args`, `use_fp16`, `use_tqdm`, etc. probably should be put in a dict as well, but they *are not* runner args, they are `TrainingOperator` args. So maybe there should be two dicts? Or just one global `system_params` dict to avoid having a dozen kwarg dicts in the future?

Any thoughts @richardliaw ? Are there maybe any libraries or python features for configuration management that we should consider using? I am not very well-versed in the Python ecosystem.

**Comment by richardliaw** [comment]
Another option is simply to expose more control via the operator:

```
Trainer(wrap_ddp=False)

class CustomOperator:
    def setup(self):
        new_models = [DDP(model, custom_arg) for model in self.models]
        self.set_models(new_models)
```

or we could venture into callback land a little more:
```
class CustomOperator:
    def _configure_models_ddp(cls, models, config):
        return [DDP(model, self.custom_arg) for model in models]
```

**Comment by richardliaw** [comment]
OK, sorry for not actually proposing a concrete suggestion. 

@DavidMChan, @maximsmol I know there might be push back, but what about`TorchTrainer(find_unused_parameters=False)`?

Among the parameters, the only other parameter I think anyone would ever use is `broadcast_buffers` and `bucket_cap_mb`. For reference, it seems like pytorchlightning sets `find_unused_parameters=True` automatically. I've also never seen anyone set any other parameter than `find_unused_parameters`.

This proposal is only a short term fix (since I can't think of a better way to cut abstractions). We can deprecate this parameter when we find a better API (presumably when we integrate different execution strategies).

**Comment by DavidMChan** [comment]
I'm open to this solution (since it solves my use case :+1:) but I think @maximsmol might be the right person to ask, since it begs a larger conversation around a much longer term decision for how to handle propagating arguments through raysgd. For what it's worth, I actually think I prefer the callback solution, since it seems to align closer with what already exists in the codebase.

**Comment by maximsmol** [comment]
I think this is fine for now. We will keep the API design in mind as we implement more examples and try to figure out something better.

**Comment by richardliaw** [comment]
OK, let's just do:

```
    trainer1 = TorchTrainer(
        model_creator=model_creator,
        data_creator=data_creator,
        optimizer_creator=optimizer_creator,
        loss_creator=lambda config: nn.MSELoss(),
        wrap_ddp=False,
        num_workers=2)
```

I forgot about the offer to contribute and went ahead and opened a PR because I was just playing around with it to see if it worked ...

**Comment by richardliaw** [comment]
@DavidMChan this is merged; take a look at master!
