### ISSUE TITLE
Calling ray.init with long temp_dir causes terminate

### ISSUE THREAD

**Issue by DavidMChan** [ray-project/ray#7945]
### What is the problem?

Calling `ray.init(temp_dir="string > 45 chars")` causes a std::terminate due to the 107 character socket length limit in unix: http://man7.org/linux/man-pages/man7/unix.7.html

(see also: https://unix.stackexchange.com/q/367008)

### Reproduction

```
import ray
ray.init(temp_dir='/tmp/long_path_name_that_exceeds_45_characters')
```

### Possible Solutions
(From @mehrdadn + Others)
- Abstract UNIX domain sockets (Linux only, needs support in the codebase, and might not be secure against other users)
- TCP sockets (also might not be secure against other users, but cross-platform)
- Warn users in the python, and exit gracefully

---
- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by mehrdadn** [comment]
To clarify, this happens because we already take up around half of the path space, so the path ends up something like this:

    /tmp/long_path_name_that_exceeds_45_characters/session_2020-04-08_16-22-43_486838_20570/sockets/raylet

I think we can use relative paths for `sockaddr_un`, so this might be another solution:

- Change directory level-by-level to the parent of the socket

- `bind`/`connect` the socket as needed via its filename

- Change directory back

This is only guaranteed to work for single-threaded processes, but perhaps we can guarantee that? If anyone has any thoughts please let me know, I'm happy to try to implement it.

**Comment by DavidMChan** [comment]
This is actually a duplicate of #7724 - I'm not sure which issue should be tracked/closed.

**Comment by mehrdadn** [comment]
Oh, thanks for finding this! I'll close this one then, we can track it over there.
