### ISSUE TITLE
[rllib] MADDPG different rank of shape for observation and action spaces

### ISSUE THREAD

**Issue by Fabien-Couthouis** [ray-project/ray#8185]
Hi all,

I am trying to train a MADDPG agent on [google football research environment](https://github.com/google-research/football).

Unfortunatly,  shapes of my observations and actions spaces are different:
observations_space: Box(42, 42, 4)
actions_space: Discrete(19) (I am aware I have to convert logits into discrete actions)

And then I have the following error:
`ValueError: Shape must be rank 4 but is rank 2 for 'policy_agent_0/critic/concat' (op: 'ConcatV2') with input shapes: [?,42,42,4], [?,42,42,4], [?,42,42,4], [?,42,42,4], [?,42,42,4], [?,19], [?,19], [?,19], [?,19], [?,19], [].`

comming from this line in maddpg_policy.py (in _build_critic_network method):
`out = tf.concat(out_n + act_n, axis=1)`

Is this a limitation of MADDPG, a miss usage or a problem in the implementation? @justinkterry 

Many thanks!

*Ray version and other system information (Python version, TensorFlow version, OS):*
tensorflow==2.1.0
ray==0.8.4

**Comment by akharitonov** [comment]
You either need to convert your observation space to a vector or use `use_state_preprocessor` in the policy definition. However, the latter will fail with the current code because of the following lines: [330](https://github.com/ray-project/ray/blob/97430b2d0fd835faa5aa012171bcd3a153b42a9d/rllib/contrib/maddpg/maddpg_policy.py#L330) and [360](https://github.com/ray-project/ray/blob/97430b2d0fd835faa5aa012171bcd3a153b42a9d/rllib/contrib/maddpg/maddpg_policy.py#L360) which require `self.config["model"]` while the variable `self.config` is never created in the initializer. 

Check following pull request for a quick and easy fix: https://github.com/ray-project/ray/pull/8343

**Comment by Fabien-Couthouis** [comment]
Hi @akharitonov, thanks for your reactivity!
