### ISSUE TITLE
[Core] Does ray scheduler get such overhead as expected

### ISSUE THREAD

**Issue by jenniew** [ray-project/ray#8243]
I use Ray 0.8.4. And I need to distribute workload on multiple nodes with Ray.  I have 4 nodes, and each node has 44 cores. I launch multiple tasks, then use ray.wait to wait the object ids to be ready. In each task, I print task start time. When I run 44 tasks on 1-node cluster, the last task starting time is ~0.03s later than the first task; when I run 88 tasks on 2-node cluster,  the last task starting time is ~0.06s later than the first task on each node; when I run 176 tasks on 4-node cluster, the last task starting time is ~0.1s later than the first task on each node. In my three tests, each time Ray would schedule same number of tasks on each node, why there has such different overhead in three tests? Are these cluster scheduler overheads as expected? If I have 100 nodes, the schedule delay for the last task may be like 2.5s even if each task may only take 0.01s.

**Comment by rkooo567** [comment]
Hi, @jenniew did you figure out anything? I’d like to follow up the conversation if you didn’t.

**Comment by jenniew** [comment]
No, I didn't figure out. Can some ray contributor look at this issue?

**Comment by rkooo567** [comment]
Scheduling itself has overhead because it is not just done within a single process. The basic scheduling request requires at least 2 IPC (worker -> node and worker -> worker to request to execute methods). Also, how ray scheduling works is as follow;

1. Worker (in your case the process that runs ray.init is a worker) sends a lease (this is a term used to schedule tasks. It means the worker will lease the worker to execute tasks) request to raylet.
2. Raylet checks if it is schedulable. If not, it replies to the worker to try other nodes that have available resources.
3. Worker tries to other nodes until it succeeds. 

That says, it seems to be normal there is some degree of overhead when you have many requests like that.

**Comment by wuisawesome** [comment]
Hey @jenniew (sorry I missed this months ago), can you try with a new version of Ray, we've merged a few bug fixes to the scheduling spillback algorithm that should've fixed this issue (Ray >= 1.0 iirc)
