### ISSUE TITLE
[rllib] Limit GPU resources with num_gpus configuration optiondoesn't seem to work

### ISSUE THREAD

**Issue by jangkj09** [ray-project/ray#8460]
### What is your question?
Based off the recommendations in the doc: https://docs.ray.io/en/master/rllib-training.html#specifying-resources
I set num_gpus = 1 for running on a server that has 4 GPUs. Even with this configuration set, when I run the basic PPO trainer, it seems to allocate to all 4 GPUs when examining the nvidia-smi output. Is the configuration not having any effect?

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray == 0.9.0.dev0
tensorflow ==2.1.0
Ubuntu 18.04

**Comment by ericl** [comment]
That only works with Ray tune.

**Comment by ericl** [comment]
You probably have to use Ray tune for that to work fully.

**Comment by jangkj09** [comment]
Even if I initialize ray with `ray.init(num_gpus = 1)` the settings seem to be overridden somewhere when instantiating PPOTrainer. Could you direct me to where this is happening? Also, is this what you meant by having to use Ray tune?

**Comment by shortstheory** [comment]
Hi, I have had the same issue when using PPOTrainer. My computer has 4 GPUs and I can see that the process which spawns PPOTrainer uses all 4 GPUs when using `nvidia-smi`, despite setting `num_gpus=1`, `num_workers=1`, `num_gpus_per_worker=1` in the `config` dict. I have also set `ray.init(num_gpus=1)`. Could you clarify what you mean by needing to use Ray Tune to make this work?

**Comment by mkeckjr** [comment]
I would also like to put my name in the hat for this. I use ray.init(num_gpus=0) on a machine with 8, and it used all 8 instead of 0. I don't see how tune makes this work, but would love some clarity on that.

Setting CUDA_VISIBLE_DEVICES does indeed address the issue, but using that type of solution will require a great deal of work all over my codebase, it's been designed around the functionality that ray claims to provide.
