### ISSUE TITLE
[tune] Usage of Tune search algorithms vs Random Search

### ISSUE THREAD

**Issue by jdavid04** [ray-project/ray#8674]
### What is your question?

I'm somewhat confused as to the use of sampling algorithms with Tune. For example, in https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/hyperopt_example.py, it seems that the script simply samples "num_samples" configurations initially and runs through these configurations (most of which are stopped from the scheduler). This makes the execution equivalent to a random search.

At what point is the sequential sampling algorithm triggered to generate new trials? Is this behaviour determined by specific parameters?

**Comment by richardliaw** [comment]
Yep! This is decided by `num_initial_points` in HyperOptSearch.

```
        n_initial_points (int): number of random evaluations of the
            objective function before starting to aproximate it with
            tree parzen estimators. Defaults to 20.
```

**Comment by jdavid04** [comment]
Thank you for the rapid response. I might be getting something wrong, but even if I set num_initial_points to 1, I consistently get the behaviour that the search generates num_samples random samples from the onset, regardless of the value for num_initial_points.

**Comment by Cryptiex** [comment]
I experienced the same behaviour as @jdavid04

**Comment by Cryptiex** [comment]
Any update on this? @richardliaw

**Comment by richardliaw** [comment]
@jdavid04 @Cryptiex I think the solution is to use a [ConcurrencyLimiter](https://docs.ray.io/en/master/tune/api_docs/suggestion.html#limiter). Let me know if this works; we may have to revisit the interface..

**Comment by flokde** [comment]
Hi, I am currently also facing this issue. Has there been an update or is the ConcurrencyLimiter still the way to go? Just to clarify the use of the ConcurrencyLimiter: If I set max_concurrent=4, the expected behaviour is that hyperopt would make 4 initial random guesses and then does another batch of 4 educated guesses and so on? 

Does use of a ConcurrencyLimiter make the parameter n_initial_points in HyperOptSearch unnecessary? Or would hyperopt continue to do random search in batches of 4 until n_inital_points is reached and then start making educated guesses (again, I assume 4 at a time)?

Help would be much appreciated, I have a hard time evaluating the exact process from the output.
Thank you very much!
