### ISSUE TITLE
[tune] how to check which hyperparams were perturbed in PBT? 

### ISSUE THREAD

**Issue by talipini** [ray-project/ray#8829]
Tune with PBT

### What is your question?
When PBT perturbs the hyperparams, is there a way to know which ones were changed from the source trial? I can get access to the new_config in restore_config to see the new values but I am trying to find out which hyperparams were perturbed from the source trial ?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray - 0.9.0.dev0
TF - 2.2.0
Python - 3.7.7

**Comment by amogkam** [comment]
Hi @talipini sorry for the late response! It seems like you have reset_config overridden in your Trainable and are using reuse_actors=True correct? If so, you can keep track of the old config yourself inside your Trainable. Something like this should work:
```
def reset_config(new_config):
    ...
    self.old_config = self.config
    self.config = new_config
```

Otherwise, if you simply want to view the perturbations and don't need to access it in your code, there are two ways: All perturbations are logged to stdout when they occur, and they are also written to pbt_policy.txt files in the experiment directory so you can look at the perturbations after the experiment has finished. In Ray 1.0, we also added a new utility to [replay](https://docs.ray.io/en/master/tune/api_docs/schedulers.html#population-based-training-replay-tune-schedulers-populationbasedtrainingreplay) the hyperparameter schedules of your experiment after it has finished.

**Comment by amogkam** [comment]
I'm going to close this for now, but please feel free to reopen this if you feel your question wasn't answered. Thanks!
