### ISSUE TITLE
[core] Ray should faithfully propagate exceptions from tasks

### ISSUE THREAD

**Issue by thomasdesr** [ray-project/ray#8948]
### Describe your feature request
If an exception is thrown in a task, that exception should be fully serialized and re-thrown when the result of that task is fetched (assuming serializability).

The specific gap I'm hitting is that while Ray will propagate the exceptions' class it does not propagate the specific instance of the exception. This means that while I can catch the same exception type; I have lost access to information captured in the original exception.

Concretely this fails and it should succeed:
```python
import ray


class HTTPException(Exception):
    def __init__(self, status_code: int):
        self.status_code = status_code


def do_work():
    raise HTTPException(404)


@ray.remote
def do_work_remotely():
    do_work()


if __name__ == "__main__":
    ray.init()

    try:
        ray.get(do_work_remotely.remote())
    except HTTPException as e:
        assert e.status_code == 404, "Incorrect status code"
```

**Comment by edoakes** [comment]
The reason this isn’t currently supported is because we currently only copy the traceback and type of the exception, then raise a RayTaskError with the relevant traceback that inherits from the original exception. However, I don’t see a reason why we can’t serialize the full exception object. 

We want to:

- Make it obvious to users that the exception occurred in their remote call, not locally.
- Make it easy for users to read the underlying exception and diagnose the issue.
- Allow users to interact with the raised exception object in the same way they would if the exception were local (this fits our motivation of easily going from regular Python code to distributed).

My suggested solution is to serialize the full exception object when an exception occurs and deserialize and raise that same object with two modifications:

1. The exception will inherit from `RayTaskError`.
2. The `__str__` method of the function will be modified to print what it currently does (some Ray-specific information and then the original exception).

One consideration is: what happens if the exception object isn't serializable? I don't expect this to happen often in practice, so I think raising a new exception in this case is acceptable.

@thomasdesr does that sound good to you and @pcmoritz @robertnishihara any thoughts?

**Comment by thomasdesr** [comment]
This sounds like a good path forward to me! :D

I definitely agree there are some risks inherent to serialization (e.g. non-serializable types, expensive serialization types, etc) but in order to support a "as if it was local" behavior I don't see an obvious path around supporting some way to pass the full exception object around.
