### ISSUE TITLE
Backend Redis sharding and replication management for fault tolerance and high availability

### ISSUE THREAD

**Issue by YuejiYang** [ray-project/ray#8969]
Based on my understanding which may be wrong, all shardings and replications of Redis servers live on the head node. This may hurt the fault tolerance and HA of the system in a cluster environment. 
I am curious about the implementation of the "per-shard chain replication". I think there should a credis module as commented in the code, but it seems not used yet. 
So, can anyone help me with my questions below:
1. How and where is "per-shard chain replication" implemented? And how to turn on this functionality.
2. Does the sharding work the same as that in the Redis server? Are there any special features of sharding that are designed for Ray?

Thank you in advance!

*Ray version and other system information (Python version, TensorFlow version, OS):* Current master branch

**Comment by rkooo567** [comment]
cc @raulchen 

I believe we are not fully HA for now. As you said, if the Redis at the head node is broken, the cluster will be crashed. Not sure if "per-shard chain replication" in Redis is implemented. Maybe @raulchen can answer this. 

We are currently in active progress to separate the GCS (in our default case Redis) from the head node and pluggable, so that users can plug any HA backend (e.g., etcd).

**Comment by rkooo567** [comment]
We are in progress of improving this by adapting pluggable GCS interface. Will close the issue as it is responded!
