### ISSUE TITLE
Why the more CPUs I use the slower the computations?

### ISSUE THREAD

**Issue by tevang** [ray-project/ray#9008]
Greetings,

I have used ray in a few other applications where the total number of operations was known in advance but in the current scenario, I cannot know the total number of function calls. Namely, I want to use ray as a thread pool, where I feed input data to the pool until there are no more. Normally the input data are bunch of lines from a file, and the function saves each bunch to a separate file, but for simplicity reasons, I will demonstrate what I mean with a slow function.

```
import ray
import time

class Parallel_Operations():

    def __init__(self, POOLSIZE):
        print("Using %i threads." % POOLSIZE)
        ray.init(num_cpus=POOLSIZE)
        for i in range(160000): # in reality, here I have an iterator which stops when it reaches the end of file
            _slow_function.remote()

@ray.remote
def _slow_function():
    benchmark()

def primes(n):
    """
    Just a slow function to monitor the real CPU usage.
    """
    if n == 2:
        return [2]
    elif n < 2:
        return []
    s = []
    for i in range(3, n + 1):
        if i % 2 != 0:
            s.append(i)
    mroot = n ** 0.5
    half = (n + 1) / 2 - 1
    i = 0
    m = 3
    while m <= mroot:
        if s[i]:
            j = int( (m * m - 3) / 2 )
            s[j] = 0
            while j < half:
                try:
                    s[j] = 0
                except IndexError:
                    break
                j += m
        i = i + 1
        m = 2 * i + 3
    l = [2]
    for x in s:
        if x:
            l.append(x)
    return l

def benchmark():
    """
        Just a slow function to monitor the real CPU usage.
    """
    for _ in range(4000):
        count = len(primes(10000000))


if __name__ == "__main__":

    POOLSIZE = 8  # the number of threads to use
    Parallel_Operations(POOLSIZE)
```

If I save this code to a file named `threadpool_test.py` and measure the time it takes to finish by varying `POOLSIZE`, I see that although every time `POOLSIZE` CPUs are fully occupied, the total time it takes to finish is smaller as the `POOLSIZE` decreases. Could somebody please point out what I am doing wrong?

**Comment by rkooo567** [comment]
There can be many causes. If poolsize is much bigger than the actual number of virtual CPUs, it wouldn't give you any speedup benefits. This is a good resource to understand when parallelization is not working properly. https://www.google.com/search?q=ray+tips&oq=ray+tips&aqs=chrome..69i57j0l4j69i60l3.1154j0j7&sourceid=chrome&ie=UTF-8

**Comment by tevang** [comment]
Your comment is not helpful. I doubt that you even looked at the example code I quoted. I still cannot understand why multiprocessing gives speedup but ray slows down the computations.

**Comment by virtualluke** [comment]
Just to help understand your situation... When you set POOLSIZE to x you see x CPUs pegged ? I know you say they are fully occupied.  Does seem odd.  Also curious what values you are setting POOLSIZE in relation to your total number of cpus. And what kind of time is your benchmark function taking roughly (with different values of POOLSIZE)?

@rkooo567 :  That google search link you gave had some "interesting" results, top one was https://www.vg247.com/2018/07/06/mystic-messenger-ray-route-tips-resources-another-story-mode/

Next was a Rachel Ray cooking link: https://www.foodnetwork.com/fn-dish/chefs/2014/02/rachael-rays-top-7-cooking-tips

pretty funny. I would avoid a non-deterministic link as a pointer to help with a question.

**Comment by rkooo567** [comment]
Sorry this is the right link. Idk how that link was pasted. https://rise.cs.berkeley.edu/blog/ray-tips-for-first-time-users/

Also, I definitely read your code. Your code runs a lot of computationally heavy remote functions with a fixed number of workers (== poolsize). You mentioned CPUs were saturated. You didn't mention anything about multiprocessing in your question. 

Here are possible scenarios.
1. Ray does not guarantee the cpu affinity. If you don't explicitly set `psutil.Process().cpu_affinity`, it relies on the OS scheduler. Afaik, multiprocessing guarantee the cpu affinity, so that can be one of the causes.  
2. Speed up is upper bounded by your CPUs. If your poolsize is bigger than the number of CPUs, not every worker is doing work "in parallel". Some of them are just waiting until it takes the CPU from other workers. 
3. There could be more, but I cannot guess them until I see how you pass lines to functions and how you write them to a disk. 

It is hard to know the cause from a single script. As @virtualluke said, it will be great if you can post 
1. number of virtual cpus of your machine.
2. If you are using cluster / single machine
3. The version of Ray.
4. The multiprocessing pool script.
5. The benchmark result (annotated with the pool size).

Also, it'll be great if you try 
1. Set cpu affinity to a single cpu at each remote function. 
```
@ray.remote(num_cpus=1) 
def _slow_function(): 
   resources = ray.ray.get_resource_ids() 
   cpus = [v[0] for v in resources['CPU']]
   psutil.Process().cpu_affinity(cpus)  
   benchmark()
```
2. Set poolsize to be equivalent to the number of virtual cpus on your machine.

**Comment by wayyoungboy** [comment]
I also have this problem. And I found that when num_cpus=1 in ray.remote, the cpus occupation of the work is still more than 100% when it is called. May as you said , it relies on the OS scheduler. @rkooo567
