### ISSUE TITLE
[rllib] turn-based multi-agent environments usage

### ISSUE THREAD

**Issue by rosnfeld** [ray-project/ray#9029]
### What is your question?

In the multi-agent environment docs, it says:

"Observations are a dict mapping agent names to their obs. Only those agents' names that require actions in the next call to `step()` will be present in the returned observation dict."

I take this to mean that one can implement turn-based games using this mechanism, e.g. the first player to go will be the only key in the observation dict returned by environment reset. I would assume the same holds for the observation dict returned by stepping the environment.

However, when RLlib steps an environment in base_env.py, it checks that the key set for the returned observations and rewards are the same:

```python
if set(obs.keys()) != set(rewards.keys()):
                raise ValueError(
                    "Key set for obs and rewards must be the same: "
                    "{} vs {}".format(obs.keys(), rewards.keys()))

```
The reward applies to the action taken in response to the previous observation, and the new observation dict (the one being checked against the rewards dict) should be for the next agent to act. If the agents in the reward and the agents in the next observation have to be the same, this would seem to prevent any other agents from ever acting. 

Am I misunderstanding something here?

### Versions
Ray version 0.85

**Comment by rusu24edward** [comment]
Hi @rosnfeld,

I raised this question in #7056. After thinking about this a lot, I realized that the way it is implemented actually makes the most sense. Here's why:

>> The reward applies to the action taken in response to the previous observation.

This is the assumption that is causing us some grief and is critical in MARL theory. The reward is not a function of just the state and the action, but it is actually a function of the state, action, AND **next state** (see Sutton p49 eq 3.6). This is important in RL and MARL because the environment can have a stochastic transition function. That **next state** part is immediately known by the *environment* when it processes the action, and therefore the *environment* is able to compute a reward right then. Now, in a single-agent problem, the *agent* is just given that reward because it is also given the next state immediately, even if the environment is stochastic. However, in a multi-agent problem, the next state that the *agent* observes is not necessarily the state that results from its action and environment stochasticity alone. In the turn-based model, the *agent's* next observation is of the state that results from its action AND all the other agents' actions. So that is why the reward should not be given to the *agent* until it also receives its next observation.

You can buffer the reward, as suggested in #7056, and return it along with the *agent's* next observation, something like:

```python
def reset(self):
    self.reward_buffer = {
        'agent0': 0,
        'agent1': 0,
        ...
    }
    return obs['agent0']

def step(self, action):
    # Process agent's action
    # Calculate reward resulting from (s, a, s')
    self.rewards[agent] = some_reward
    return obs[next_agent], self.rewards[next_agent], ...
```

Buffering may not be the best thing to do because it does not account for the next state as the *agent* sees it but for some previous state that some other *agent* saw. These are just things to keep in mind when designing a multi-agent environment. [This blog](https://bair.berkeley.edu/blog/2018/12/12/rllib/) does a good job introducing the issue of nonstationarity and you can listen to [this podcast](https://datascienceimposters.com/2020/10/05/can-team-sports-take-advantage-of-reinforcement-learning/) for another explanation.

**Comment by rosnfeld** [comment]
Thanks for posting this @rusu24edward - very nice complete answer.  I'll close this now.

**Comment by rusu24edward** [comment]
As a follow up, [here is a TurnBasedWrapper](https://github.com/LLNL/Admiral/blob/main/admiral/managers/turn_based_manager.py) that I created that can automatically make environments turn-based. This is designed for my specific environment ecosystem (wrapping my [AgentBasedSimulation](https://github.com/LLNL/Admiral/blob/main/admiral/envs/agent_based_simulation.py) interface), which has a few more requirements than the out-of-the-box MultiAgentEnv, but still very close.
