### ISSUE TITLE
[webui] start and end time boxes are confusing

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#913]
It looks like you can either move the slider or type in the start/end time boxes, which is pretty confusing since those boxes are also updated by the slider.

**Comment by alanamarzoev** [comment]
This behavior was intentional. I think it would be more confusing if these were out of sync. If the time windows said one thing, but the sliders said another, then both the user and the widget wouldn't know which to "listen" to -- so the choice would have to be made arbitrarily (i.e. - the sliders take priority over the time boxes, or vice-versa). 

The intended use case for the sliders is when a user doesn't have a specific window to zero in on, but instead would like to see things such as the last x% of tasks, or the tasks that happened in the last x% of time. This means that they don't have to know specific timing information, which is useful, especially if this is their "first look". 

The intended use case for the start/end time boxes was when a user had a specific interval of time that they wanted to look more closely at. This would usually happen after they got saw aggregate statistics through the bokeh summary plots or the overall task timeline. These start/end boxes would typically be used after the sliders, since the user is unlikely to know what time windows are of interest prior to seeing the full picture first.

@ericl @robertnishihara

**Comment by ericl** [comment]
Ah I see, from the UX perspective these should probably be different modes then. For example, you could have a radio button that chooses between the two input views. However, one should always be greyed out so it is clear which is the input and output.

**Comment by ericl** [comment]
Btw, one related issue I ran into is that it's far to easy to hang the web UI when there are large numbers of tasks (I was testing 1 million tasks).

I'm not exactly sure what I did, but if you fiddle with the timeline sliders the wrong way the UI will hang processing too many tasks.

cc @robertnishihara @alanamarzoev thoughts on how to prevent this from happening? I would propose enforcing a hard limit on the number of tasks (say, 50 thousand) and have the UI only allowing parameterization within this range, e.g:

- a box for max num tasks to render: 50-50000
- a box that lets you input the start time offset (separately, we need to show the min and max task times so that the user knows reasonable values to put here)

**Comment by alanamarzoev** [comment]
So this was an issue that we ran into before, but we never really came to a resolution. 

The default behavior right now is for it to render max(10k, most recent x) tasks (so if there's less than 10k total, it'll render all of them, otherwise it'll render the most recent 10k). 

I think one suggestion to prevent people from toggling the sliders too much was to print a warning to the user about it when there's over a certain amount of tasks, but I think there are better ways of handling this.

@ericl Wouldn't a box that lets you input the start time offset have the same utility as the initial start and end time boxes that we had?

**Comment by robertnishihara** [comment]
That could make a lot of sense. Let's track that in #933.

**Comment by robertnishihara** [comment]
Closing because this aspect of the UI has changed substantially in the current master.
