### ISSUE TITLE
[rllib] PolicyServer arbitrary code execution vulnerability due to deserializing user-controlled data

### ISSUE THREAD

**Issue by imanoracle** [ray-project/ray#9321]
It seems that Ray is vulnerable to an arbitrary code execution by unpickling untrusted data. Please look at this https://github.com/ray-project/ray/blob/master/rllib/utils/policy_server.py#L31

**Comment by rkooo567** [comment]
cc @thomasdesr

**Comment by thomasdesr** [comment]
Hey @imanoracle

Ray is essentially one big, very trusting, box so we strongly encourage people to not expose Ray to any untrusted clients. We've been comfortable so far not providing additional isolation inside a cluster since access to Ray is 
essentially already arbitrary code exec.

Thanks for flagging this though! In most systems this would be a huge problem :D

**Comment by imanoracle** [comment]
Thank you
