### ISSUE TITLE
RLlib crashes due to OSError: No space left on device

### ISSUE THREAD

**Issue by uuudown** [ray-project/ray#9392]
### What is your question?

We are using RLlib (Ray-0.8.0, Python 3.7, Tensorflow 2.2.0, PGAgent) with our own simulator for RL training. However, after around 4500 iterations, the session folder becomes extremely large (220GB) which crashed the whole system (reported as OSError: [Errno 28] No space left on device). We checked the files, and it is actually the output of the worker (e.g., worker-e9d9526283100ab366abc619fe3467ebfd5565b6.out) become too large which dump all the output of the simulator. Is there a way to disable the logging for these environment output? I tried to find some information online but could not find.

Thank you so much!

Best Regards,
Ang.

**Comment by DMTSource** [comment]
I also have this problem since I started using ray and it's remote workers in general in Ubuntu 1404. My /tmp folder(not the current session folder in /tmp/ray, or /tmp/ray, just the top of /tmp) rapidly fills with thousands of files and I have to use extra code to check for number of files and clear them very frequently during use of remote functions to prevent all machines on the cluster from quickly filling the hard drive. This issue can be really bad as in the past and was tricky to get the machine booted(very long to clear tmp, manual is faster in repair console) and in some rare cases it did damage before shutdown and the GUI required a reinstall to repair which was difficult to perform due to booting not working(not rays fault but the os was really messed up by the full HD).

file name:  
> python-core-worker-f5972a57049e6a93bf26af9cf0dd554d2ff4801f.<host>.<user>.log.WARNING.python-core-worker-f5972a57049e6a93bf26af9cf0dd554d2ff4801f20200709-171308.5147

contents example:
> Log file created at: 2020/07/09 17:13:08
> Running on machine: <host>
> Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
> W0709 17:13:08.851662  5147 reference_count.cc:196] Tried to decrease ref count for nonexistent object ID: 331f12b0ca0949937f8013f5bcca000800000000


file name:  
> raylet.<host>.<user>.log.WARNING.20200707-212428.2472
and same contents below but with name
> raylet.<host>.<user>.log.ERROR.20200707-212428.2472

contents example:
> Log file created at: 2020/07/07 21:24:28
> Running on machine: <host>
> Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
> E0707 21:24:28.866561  2472 process.cc:274] Failed to wait for process 2504 with error system:10: No child processes
> E0707 21:24:28.870051  2472 process.cc:274] Failed to wait for process 2503 with error system:10: No child processes
> E0707 21:24:28.870071  2472 process.cc:274] Failed to wait for process 2498 with error system:10: No child processes
> E0707 21:24:28.871675  2472 process.cc:274] Failed to wait for process 2506 with error system:10: No child processes
> E0707 21:24:28.875376  2472 process.cc:274] Failed to wait for process 2502 with error system:10: No child processes
> E0707 21:24:28.875411  2472 process.cc:274] Failed to wait for process 2505 with error system:10: No child processes
> E0707 21:24:28.875427  2472 process.cc:274] Failed to wait for process 2507 with error system:10: No child processes

I share this code example in case people with this issue are desperate to keep their machine alive & doing work, but there has to be a proper fix if anyone could share if they run into this issue as well:
```
def clean_up_tmp(verbose=False):
    tmp_dir = '/tmp/'
    files = [f_str for f_str in listdir(tmp_dir) if
             any(substring in f_str for substring in ['python-worker-','python-driver-','raylet.'])]
    if len(files) > 1000: # cleanup once too many files(will grow to thousands in top of tmp)
        if verbose:
            print("Cleaning up /tmp %d logs to prevent unmount of drive."%len(files))
        for f in files:
            # print(f)
            try:
                remove(tmp_dir+f)
            except:
                break
```

**Comment by uuudown** [comment]
Thank you for your solution. We will try! As an alternative way, we are now working on eliminating all the print statements in our simulator.

**Comment by mbbyn** [comment]
I am having the same issue, but I couldn't find any references on github nor the forums for a resolution. Is this still a user concern that we have to deal with ourselves? The issue basically is that when we run our docker containers long enough, the session logs volume fills up till the service fails due to out of space error.

I found ways to limit the log sizes for workers and Actors, but nothing to limit GCS, raylet or other system logs emitted by ray.
