### ISSUE TITLE
pip uninstall ray removes all ray files in the cloned repo

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#9426]
When installing ray for development using `python python/ray/setup-dev.py` inside a fork of ray then and then uninstalling ray it removes all the ray files inside the cloned ray repo.

**Comment by AmeerHajAli** [comment]
Closing issue as there is a warning on the website.

**Comment by sven1977** [comment]
It's due to the softlinking from the installation dir e.g. "[anaconda]/envs/[your env name]/site-packages/ray/..." into the local git clone.
Two possible solutions are:
- remove these links always before making any changes to the pip installation (also before upgrading to e.g. latest wheel).
- do the pip (un)installations first, then rollback the current working tree in the local git clone: `git checkout -f master` (make sure you commit any important changes beforehand, though!).
