### ISSUE TITLE
scheduler differences between wait and get ?

### ISSUE THREAD

**Issue by virtualluke** [ray-project/ray#947]
After finding some places in our flow where we don't need to block and can do some processing on intermediate results we changed our code to use wait instead of get.  In this case our cluster's machines never got a load over 10 (on a 56 core box) where with the get during the main processing the load was maxed out.

Here is some pseudo code of what we were doing in each case:

Get version:

```
results = ray.get([func.remote() for i in range(100)])

for x in results:
   Do work
```

Wait version:

```
results = [func.remote() for i in range(100)]

while True:
   ready, remaining = ray.wait(results)
   results = remaining

   for x in ready:
       data = ray.get(x)
       Do work
  
  if len(remaining) == 0
     break
```

No other code changes were made and we see significant load differences.

Also, as a test we tried changing the wait to block with num_returns=100 (in the above) and the wait version is still very low load with this change where it seems to us that the wait with that number blocking should be equivalent.

**Comment by robertnishihara** [comment]
This is a bit surprising. These two blocks of code look pretty equivalent to me.

In both cases, the scheduling and execution of the tasks is triggered by the call to `[func.remote() for i in range(100)]`, so that should max out the load even if you never call `ray.get` or `ray.wait` (is that consistent with what you're seeing?).

Some questions:
- Are the results of the two scripts the same?
- Do they take similar amounts of time or is one faster than the other?
- If you get rid of the `Do work` stuff in both cases, then do you still see the exact same behavior?

**Comment by virtualluke** [comment]
I am not sure the results are the same as the version with the wait was so slow I killed it after a few minutes.  I could tell from stuff in "Do Work" that the progress happening was much, much less on the wait version.

I will see what happens without the work, might not be until Monday.

I will try and come up with some sample actual code to be able to reproduce the issue.

**Comment by robertnishihara** [comment]
Sounds good.

**Comment by virtualluke** [comment]
I have tried a small example and am not seeing the behavior that I see in my regular program, still trying to reproduce what I am seeing in a simpler example.

**Comment by robertnishihara** [comment]
This should be fixed now.
