### ISSUE TITLE
Add manylinux2014 wheels to build

### ISSUE THREAD

**Issue by virtualluke** [ray-project/ray#9666]
### Describe your feature request
It would be nice to have manylinux2014 wheels generated.  These are based on centos7 level of libraries vs centos5 for manylinux1 as basic requirements.  I would gather most people using manylinux* can safely go to the latest manylinux2014 specification.

**Comment by robertnishihara** [comment]
@virtualluke can you say more about the advantage/disadvantage of doing this? Are you proposing this in addition to or instead of manylinux1?

- TensorFlow seems to do manylinux2010 https://pypi.org/project/tensorflow/#files
- Pyarrow seems to do manylinux1, manylinux2010, and manylinux2014 https://pypi.org/project/pyarrow/#files
