### ISSUE TITLE
[tune] Support for Python context manager finalization when scheduler stops trial

### ISSUE THREAD

**Issue by asmv** [ray-project/ray#9716]
### Describe your feature request

Currently when a trial is stopped by a scheduler, context managers do not appear to be closed automatically which might result in runaway resources. Calling the exit functions before the scheduler stops a trial would prevent any leaks.

#### Minimal Example

```python
from ray import tune

class DemoContextManager:

    def __init__(self, config):
        self.config = config

    def __enter__(self):
        print("Set up resource.", self.config)
        return self

    def __exit__(self, type, value, traceback):
        print("Clean up resource.", self.config)

def demofunc(config):
    with DemoContextManager(config):
        for i in range(10):
            tune.report(metric=i+config['x'])

def generator_func():
    yield 5
    yield 1
g = generator_func()

demoscheduler = tune.schedulers.MedianStoppingRule(min_samples_required=1, grace_period=0, metric="metric", mode="max")
tune.run(demofunc, local_dir=".", name="test", num_samples=2, scheduler=demoscheduler, config={'x': tune.sample_from(lambda _ : next(g))})
```

**Comment by richardliaw** [comment]
cc @krfricke

**Comment by krfricke** [comment]
Thanks @asmv for the issue.

I added a test here: https://github.com/ray-project/ray/pull/11889

It seems contexts are already being finalized when trials are stopped by Tune. I'm not sure if this is due to our changes on the function API (we introduced a graceful trial shutdown, but the test still worked for me when I removed that) or default Python behavior. Can you take a look at the test and confirm that it would catch your issue?

**Comment by asmv** [comment]
Yes, I believe this added test would catch the issue. The minimal example at the top of the issue works on the most recent version of Tune as well.
