### ISSUE TITLE
[rllib] Continuous instead of episodic problem

### ISSUE THREAD

**Issue by stefanbschneider** [ray-project/ray#9756]
If I have a continuous instead of episodic problem, would I have to change anything in RLlib to address it? Or just ensure that my environment always returns `done=False`?

In chapter 10.3 of [Sutton's book](http://incompleteideas.net/sutton/book/RLbook2018.pdf), I read that the average reward should be used for continuous problems instead of the discounted return. How would I achieve that? Or do I just have to set discount factor gamma to 0?

**Comment by sven1977** [comment]
Great question @stefanbschneider , haven't thought about this myself (@ericl?). Yes, the PG loss function would even slightly change in this case (in other words, we don't support this atm). It shouldn't be too hard to fix, though. Which algo are you using (some PG, I assume)? For PPO, for example, would could probably change the postprocess_trajectory method to calculate the average (over n timesteps) instead of the sum of rewards and also make sure that your value function learns to predict the average (not the discounted return till the end of the episode). Gamma should be 1.0 (no, not 0.0!).

**Comment by ericl** [comment]
I think you can use soft_horizon for this, that's intended for use with true MDP problems.

**Comment by stefanbschneider** [comment]
Thanks for the prompt response!

@sven1977 Yes, I'm using PPO. That would be great if you could provide further details how to achieve the desired behavior. Not coming from an RL background, I'm a bit overwhelmed and don't know where/how to start.
If I understand Sutton correctly, he argues in chapter 10.4 that no discounting should be used - hence, I considered setting gamma to 0.

@ericl Hm. The [docs](https://docs.ray.io/en/latest/rllib-training.html?highlight=soft_horizon#common-parameters) say 

```python
# Calculate rewards but don't reset the environment when the horizon is
# hit. This allows value estimation and RNN state to span across logical
# episodes denoted by horizon. This only has an effect if horizon != inf.
"soft_horizon": False,
```

I'm not sure if that really matches my problem since I don't have logical episodes. Or how would I use that? To what value would I set horizon? Wouldn't that be the same as choosing arbitrary episode lengths for my continuous problem?
Btw, I'm using the default MLP model for PPO at the moment; so no RNN.

**Comment by stefanbschneider** [comment]
What would happen, if I just always return `done = False` and otherwise keep my environment and PPO configuration unchanged? Is that generally a bad idea because training/evaluation is somehow tied to episodes?

**Comment by DanielWicz** [comment]
> What would happen, if I just always return `done = False` and otherwise keep my environment and PPO configuration unchanged? Is that generally a bad idea because training/evaluation is somehow tied to episodes?

Did you solve the problem ?

**Comment by stefanbschneider** [comment]
I'm not sure. I set `done = False` and `soft_horizon = True` and the environment runs continuously without resets as I want it.
Until now, I didn't change anything else, eg, regarding the calculation of average reward instead of discounted return.
The agent still learns reasonable behavior but it seems to work a bit worse compared to the episodic setting.

**Comment by DanielWicz** [comment]
@stefanbschneider  Thanks for your answer


> Great question @stefanbschneider , haven't thought about this myself (@ericl?). Yes, the PG loss function would even slightly change in this case (in other words, we don't support this atm). It shouldn't be too hard to fix, though. Which algo are you using (some PG, I assume)? For PPO, for example, would could probably change the postprocess_trajectory method to calculate the average (over n timesteps) instead of the sum of rewards and also make sure that your value function learns to predict the average (not the discounted return till the end of the episode). Gamma should be 1.0 (no, not 0.0!).

@sven1977  or @ericl 
There's an example how to use `postprocess_trajectory()` method ? Because, the discounted reward may or may not work depending on how small is gamma and how long is the continued trajectory. Therefore it would really appreciated, to see average reward and value function based on it.

**Comment by kk-55** [comment]
> 
> 
> Thanks for the prompt response!
> 
> @sven1977 Yes, I'm using PPO. That would be great if you could provide further details how to achieve the desired behavior. Not coming from an RL background, I'm a bit overwhelmed and don't know where/how to start.
> If I understand Sutton correctly, he argues in chapter 10.4 that no discounting should be used - hence, I considered setting gamma to 0.
> 
> @ericl Hm. The [docs](https://docs.ray.io/en/latest/rllib-training.html?highlight=soft_horizon#common-parameters) say
> 
> ```python
> # Calculate rewards but don't reset the environment when the horizon is
> # hit. This allows value estimation and RNN state to span across logical
> # episodes denoted by horizon. This only has an effect if horizon != inf.
> "soft_horizon": False,
> ```
> 
> I'm not sure if that really matches my problem since I don't have logical episodes. Or how would I use that? To what value would I set horizon? Wouldn't that be the same as choosing arbitrary episode lengths for my continuous problem?
> Btw, I'm using the default MLP model for PPO at the moment; so no RNN.

@stefanbschneider Really late but some annotations: IMO no discounting, as Sven already said, requires setting gamma to 1, otherwise you will discount rewards.
My thoughts about how horizon, soft_horizon and no_done_at_end work are as follows (no guarantee):

- **horzion**: By default, horizon is infinite but setting it to a positive integer means that current episode will end after horizon steps at the latest. I think done=True will be recorded.
- **soft_horizon**: If horizon is hit, this interval of steps is treated as a logical episode but instead of resetting the env to its start state the next episode will continue from the env state when horizon was hit.
- **no_done_at_end**: I think if no_done_at_end=True then each done=True (returned from env or hitting horizon) is ignored and always done=False is recorded in a SampleBatch.

In the meantime, do you know more about consequences of altering these config variables on learning continous or episodic tasks with RLlib?

**Comment by stefanbschneider** [comment]
@kk-55 I share your understanding of these three config params. I did try running a continuous problem by changing my env to always return `done=False`, setting `horizion=100`, `soft_horizon=True`, `no_done_at_end=True`. I left gamma unchanged.
Functionally, this lead to the expected result of running the environment without any reset. Not sure how the rewards were calculated in the background, but I guess they were calculated based on logical episodes of 100 time steps, as you said.
Overall, the training result was mediocre and I switched back to focusing on episodic problems. 

For reference, this is where I set the corresponding config options in my env: https://github.com/CN-UPB/DeepCoMP/blob/master/deepcomp/main.py#L49
I haven't tried in a while, but I think the env should still support continuous instead of episodic problems.
