### ISSUE TITLE
[Placement Group] Allow deleting placement groups

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#9793]
Add an API to list / delete placement groups.

**Comment by rkooo567** [comment]
I just realized this might have hard dependency to https://github.com/ray-project/ray/issues/9795 if we want to implement correctly. (because we should remove after all tasks that depend on this placement group has been done, or at least force kill them. The naive approach will make all pending tasks infeasible).

**Comment by ericl** [comment]
I think it's fine to make the tasks infeasible in the initial version,
though I agree it's not ideal.

**Comment by rkooo567** [comment]
@ericl Should we close this? I think all P0 for removing APIs are done.

**Comment by rkooo567** [comment]
Or I can bring it down to P2 (with addtional explanation).

**Comment by ericl** [comment]
Sounds good. Let's close and add more tasks for any refinements.
