### ISSUE TITLE
Document the global state API and give examples of how to use it.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#986]
Common questions include:

1. How do I know the number of CPUs in the cluster?
2. How do I know which machines the different tasks were scheduled on?
3. How do I know which machines the different objects live on?

**Comment by morrisirrom** [comment]
+1 for interest in this

**Comment by LinxiFan** [comment]
Ping: what are the functions that answer these questions?

**Comment by morrisirrom** [comment]
Sorry about the confusion--I deleted my question when I realized it had
already been asked/answered:
Here was my original question:
"I apologize if this is covered somewhere in the documents--but I cannot
find where.
I would like to use Ray in a dynamic fashion without knowing how many nodes
will be in my cluster, and therefor how many actors I can safely allocate.
I find that if allocate more actors than available resources, the system is
prone to deadlock.

Is there a way to query how many CPU/GPU's are available for allocating
Actors? Is there a way to ask ray: "Are N resources available in the
cluster?" So that I can determine if it is safe to allocate more actors,
etc?
I can use psutil.cpu_count, but that will only include local resources (and
not other nodes that may have room for actor allocation), right?

Thanks in advance!
"
and shortly after, I realized this was already addressed in an earlier
question, and an issue added to track:
"My apologies--I should have continued searching--I believe
https://github.com/ray-project/ray/issues/986 is the relevant issue."

... my intention was to avoid adding useless noise to the forums--sorry for
the confusion! :)

**Comment by robertnishihara** [comment]
@LinxiFan, you can use the following

1. `ray.global_state.cluster_resources()`
2. `ray.global_state.task_table()`
3. `ray.global_state.object_table()`

The last two should be used in conjunction with `ray.global_state.client_table()`.

**Comment by richardliaw** [comment]
Request to make this part of 0.6?
