### ISSUE TITLE
What's the usage of self.local_worker in TorchTrainer?

### ISSUE THREAD

**Issue by dorcus01** [ray-project/ray#9932]
### What is your question?
What's the usage of self.local_worker in TorchTrainer? I noticed that in the latest version of Ray, there's a new class LocalDistributedRunner. There's always one local work setup via _start_workers() while doing distributed training. Is there any specific reasons of doing it? 

I am trying to write some custom classes inherited from TorchTrainer, DistributedTorchTrainer. Previously with the older version of Ray, everything runs well, but now with the latest changes made to Ray, there're always hanging workers. 

*Ray version:  https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl
*Cloud: AWS

**Comment by richardliaw** [comment]
@dorcus01 thanks for opening this issue; we're going to revert this change. I will ping you when that's done.

The original reason is that having a worker on the main GPU simplifies debugging (because there is no layer between driver and training worker). But it seems like this causes more problems than it solves, so we'll fix this by 0.8.7. 

thanks again for opening this issue!
