### ISSUE TITLE
use_lstm not working with tuple action space

### ISSUE THREAD

**Issue by MoggeM** [ray-project/ray#9935]
When setting "use_lstm" with a tuple action space (with tensorflow) im getting the following error:

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Seems to be caused by:
self.action_dim = int(np.product(action_space.shape))
https://github.com/ray-project/ray/blob/master/rllib/models/tf/recurrent_net.py#L115

**Comment by jiajiexiao** [comment]
The problem seems due to the fact that ```action_space.shape```  returns ```None``` for tuple action space. For tuple action space, the ```action_dim``` should be just the length of the tuple. So maybe the bug could be fixed by changing https://github.com/ray-project/ray/blob/2f3ec4ef758ad482e46b3f4c72be9d10f46d7ae2/rllib/models/tf/recurrent_net.py#L116 and https://github.com/ray-project/ray/blob/2f3ec4ef758ad482e46b3f4c72be9d10f46d7ae2/rllib/models/torch/recurrent_net.py#L117  to the following:

```
        if action_space.shape is not None:
            self.action_dim = int(np.product(action_space.shape))
        else:
            self.action_dim = int(len(action_space))
```
