### ISSUE TITLE
Calling a remote function with a keyword argument fails

### ISSUE THREAD

**Issue by salsasepp** [ray-project/ray#998]
Not sure if this is a bug or a missing feature:
```
import ray

@ray.remote
def f(a):
    return a+1
    
ray.init()

f.remote(1)
f.remote(a=1)
```
 The last line produces this error message when using ray 0.2.0:

> Exception: The name 'a' is not a valid keyword argument for the function 'f'

**Comment by robertnishihara** [comment]
Good catch, and thanks for pointing this out! We probably want to modify this so that remote functions can be called in exactly the same way as regular functions.

The exception is being raised in this line

https://github.com/ray-project/ray/blob/5c70faf76be0039a893052f15e4005733492e5d0/python/ray/signature.py#L149

And the logic is generally in the file https://github.com/ray-project/ray/blob/master/python/ray/signature.py.

**Comment by jiamings** [comment]
+1
Hope to see this feature released soon!

**Comment by abishekk92** [comment]
@robertnishihara I can take a shot at this, if nobody is working on it?

**Comment by robertnishihara** [comment]
@abishekk92 sounds great, I don't think anyone is working on it at the moment.

**Comment by AdamGleave** [comment]
@robertnishihara can you review PR #2081 addressing this issue?
